arping.md: add German translation
tldr-pages/tldr pull request #10000
Opened 2023-03-30 16:42 UTC by Slotharmy

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-03-31 13:56 UTC, pixelcmtd requested changes

2023-03-31 13:56 UTC, pixelcmtd commented on pages.de/common/arping.md
> +> Nützlich für die Entdeckung MAC Addressen.
```suggestion
> Nützlich für die Entdeckung von MAC-Adressen.
```

2023-03-31 13:56 UTC, pixelcmtd commented on pages.de/common/arping.md
> +- Mit ARP Requests Paketen einen Host pingen:
```suggestion
- Pinge einen Host mit ARP Request Paketen:
```

2023-03-31 13:56 UTC, pixelcmtd commented on pages.de/common/arping.md
> +- Einen Host auf einem spezifizierten Interface pingen:
```suggestion
- Pinge einen Host auf einem spezifizierten Interface:
```

2023-03-31 13:56 UTC, pixelcmtd commented on pages.de/common/arping.md
> +- Einen Host pungen und nach der ersten Antwort aufhören:
```suggestion
- Pinge einen Host und höre nach der ersten Antwort auf:
```

2023-03-31 13:56 UTC, pixelcmtd commented on pages.de/common/arping.md
> +- Einen Host für eine bestimmte Anzahl pingen:
Worst phrasing ever. I asked ChatGPT and even it couldn't help me

<img width="611" alt="Pixel: Wie sagt man 'do something a specific number of times' auf Deutsch (im Imperativ)? ChatGPT: Um im Imperativ auszudrücken, dass jemand etwas eine bestimmte Anzahl von Malen tun soll, kann man im Deutschen folgende Konstruktion verwenden: 'Tu es (Anzahl) Mal!' Zum Beispiel: 'Schreib es fünf Mal auf!' 'Sag es dreimal laut!' 'Lies den Text zweimal durch!' 'Übe den Trick zehn Mal!' In diesem Fall wird das Verb im Infinitiv benutzt und die Anzahl der Wiederholungen wird mit dem entsprechenden Zahlwort angegeben. Pixel: wie formuliere ich es mit einer phrase, die eine nicht bekannte Anzahl ausdrückt (analog zu 'a specific number of times') ChatGPT: Um auszudrücken, dass jemand etwas eine nicht bekannte Anzahl von Malen tun soll, kann man im Imperativ im Deutschen folgende Konstruktion verwenden: 'Tu es mehrmals!' Zum Beispiel: 'Übe den Trick mehrmals, bis du ihn beherrschst!' 'Lies den Text mehrmals, um ihn besser zu verstehen!' 'Sag es mehrmals laut, damit es im Gedächtnis bleibt!' 'Schreib es mehrmals auf, um es auswendig zu lernen!' In diesem Fall wird das Verb im Infinitiv benutzt und die Phrase 'mehrmals' gibt an, dass die Handlung mehr als einmal ausgeführt werden soll, aber keine spezifische Anzahl festgelegt wird." src="https://user-images.githubusercontent.com/35269695/229135597-524fa3ac-c962-4359-ba4a-c58724fd11be.png">


```suggestion
- Pinge einen Host für eine bestimmte Anzahl:
```

2023-03-31 13:56 UTC, pixelcmtd commented on pages.de/common/arping.md
> +- ARP Request Packete broadcasten um die ARP Caches der Nachbarn zu aktualisieren:
```suggestion
- Broadcaste ARP Request Pakete um die ARP Caches der Nachbarn zu aktualisieren:
```

2023-04-01 04:46 UTC, kbdharun commented
Off topic: Nice this is the 10,000 th PR in tldr 🥳

2023-04-23 11:30 UTC, pixelcmtd approved these changes

2023-04-23 11:49 UTC, kbdharun approved these changes

2023-04-23 11:50 UTC, merged