Translate linux apk to it
tldr-pages/tldr pull request #10022
Opened 2023-04-07 13:26 UTC by Magrid0

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-04-10 16:37 UTC, blueskyson approved these changes

2023-04-12 19:12 UTC, mebeim requested changes
Thanks for the translation @Magrid0 :). Just a couple nitpicks, see below.

2023-04-12 19:12 UTC, mebeim commented on pages.it/linux/apk.md
> +- Prova a riparare un pacchetto o ad aggiornare un pacchetto senza dipendenze:
```suggestion
- Prova a riparare un pacchetto o ad aggiornare un pacchetto senza modificarne le dipendenze:
```

2023-04-12 19:12 UTC, mebeim commented on pages.it/linux/apk.md
> +- Ricerca dei pacchetti da una parola chiave:
```suggestion
- Ricerca pacchetti data una parola chiave:
```

2023-04-12 20:15 UTC, mebeim approved these changes

2023-04-12 20:16 UTC, merged