fold: add page; log: add Italian translation
tldr-pages/tldr pull request #10039
Opened 2023-04-09 19:23 UTC by Magrid0

- [ x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-04-09 20:40 UTC, SethFalco requested changes

2023-04-09 20:40 UTC, SethFalco commented on pages/linux/fold.md
> +- Fold lines in a fixed widht:
```suggestion
- Fold lines in a fixed width:
```

2023-04-09 20:40 UTC, SethFalco commented on pages/linux/fold.md
> +- Count Width in bytes (the default is to count in columns):
```suggestion
- Count width in bytes (the default is to count in columns):
```

2023-04-09 20:40 UTC, SethFalco commented on pages/linux/fold.md
> +- Break the line after the rightmost blank within the Width limit:
```suggestion
- Break the line after the rightmost blank within the width limit:
```

2023-04-10 16:23 UTC, blueskyson commented on pages.it/osx/log.md
> +`sudo log collect --last {{1h}} --output {{percorso/per/file.logarchive}}`
Reference: https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/common-arguments.md
```suggestion
`sudo log collect --last {{1h}} --output {{percorso/del/file.logarchive}}`
```

2023-04-10 16:23 UTC, blueskyson commented on pages/linux/fold.md
> +> More information: <https://www.ibm.com/docs/en/aix/7.1?topic=f-fold-command>.
We prefer manned.org or gnu's man page.
```suggestion
> More information: <https://manned.org/fold>.
```

2023-04-10 16:23 UTC, blueskyson commented on pages/linux/fold.md
> +`fold -w {{width}} {{file_name}}`
```suggestion
`fold -w {{width}} {{path/to/file_name}}`
```

2023-04-10 16:23 UTC, blueskyson commented on pages/linux/fold.md
> +`fold -b -w {{width_in_bytes}} {{file_name}}`
```suggestion
`fold -b -w {{width_in_bytes}} {{path/to/file_name}}`
```

2023-04-10 16:23 UTC, blueskyson commented on pages/linux/fold.md
> +`fold -s -w {{width}} {{file_name}}`
```suggestion
`fold -s -w {{width}} {{path/to/file_name}}`
```

2023-04-26 14:29 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-04-26 14:31 UTC, kbdharun commented on pages/linux/fold.md
> +`fold -w {{width}} {{path/to/file}}`
```suggestion
`fold --width {{width}} {{path/to/file}}`
```
We prefer long options, whenever possible.

2023-04-26 14:31 UTC, kbdharun commented on pages/linux/fold.md
> +`fold -b -w {{width_in_bytes}} {{path/to/file}}`
```suggestion
`fold --bytes --width {{width_in_bytes}} {{path/to/file}}`
```

2023-04-26 14:31 UTC, kbdharun commented on pages/linux/fold.md
> +`fold -s -w {{width}} {{path/to/file}}`
```suggestion
`fold --spaces --width {{width}} {{path/to/file}}`
```

2023-05-14 13:26 UTC, yutyo approved these changes
LGTM

2023-05-14 13:27 UTC, merged