Anki command tr
tldr-pages/tldr pull request #10035
Opened 2023-04-09 14:43 UTC by ilkermeliksitki

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-04-09 18:06 UTC, kbdharun reviewed
Thanks for your contribution and welcome to tldr, seems like you are creating new branches in your fork keeping your existing main branch as the base, in the future I would suggest using `tldr-pages:main` as the base branch. I have closed your other PR.

2023-04-09 18:06 UTC, kbdharun commented on pages.tr/common/dig.md
> +> Daha fazla bilgi için: <https://manned.org/dig>
```suggestion
> Daha fazla bilgi için: <https://manned.org/dig>.
```

2023-04-09 18:09 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page. **Also, wherever possible I would suggest translating the placeholder inside `<>` too.**

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/anki.md
> +- Çalıştır.
```suggestion
- Çalıştır:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/anki.md
> +- Belirtilen bir profil ismi ile çalıştır.
```suggestion
- Belirtilen bir profil ismi ile çalıştır:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/anki.md
> +- Belirtilen bir dil ile çalıştır.
```suggestion
- Belirtilen bir dil ile çalıştır:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/anki.md
> +- Belirtilen bir dizinden (konumdan) calıştır.
```suggestion
- Belirtilen bir dizinden (konumdan) calıştır:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/dig.md
> +- İlgili sunucu ile ilgili IP adresi sorgulaması yapılır.
```suggestion
- İlgili sunucu ile ilgili IP adresi sorgulaması yapılır:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/dig.md
> +- DNS sorgulaması için alternatif server kullanılır.
```suggestion
- DNS sorgulaması için alternatif server kullanılır:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/dig.md
> +- Tersine DNS sorgulaması yapılır.
```suggestion
- Tersine DNS sorgulaması yapılır:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/dig.md
> +- Belli başlı DNS sunucuları ile ilgili kayıtları sorgular.
```suggestion
- Belli başlı DNS sunucuları ile ilgili kayıtları sorgular:
```

2023-04-09 18:09 UTC, kbdharun commented on pages.tr/common/dig.md
> +`dig -x 1.1.1.1`
```suggestion
`dig -x {{1.1.1.1}}`
```

2023-04-09 18:10 UTC, kbdharun commented
Tip: In the file tab, you can batch all suggestions and make a single commit.

2023-04-09 19:50 UTC, Magrid0 approved these changes

2023-04-10 07:57 UTC, ilkermeliksitki commented
Thanks for your fixes. So, should I use my main branch that is based on tldr-pages:main while making a PR?  @kbdharun

2023-04-10 08:07 UTC, kbdharun commented
> Thanks for your fixes. So, should I use my main branch that is based on tldr-pages:main while making a PR? @kbdharun

Yes, when creating a new branch in future, you need to use it with `tldr-pages:main` as the source branch.

2023-04-21 06:14 UTC, kbdharun approved these changes

2023-05-09 01:44 UTC, pixelcmtd requested changes
Could you please translate the placeholders as well? I've added a suggestion for one of them

2023-05-09 01:44 UTC, pixelcmtd commented on pages.tr/common/anki.md
> +`anki -b {{path/to/directory}}`
```suggestion
`anki -b {{dizin/yolu}}`
```

2023-05-09 10:30 UTC, ilkermeliksitki commented
> Could you please translate the placeholders as well? I've added a suggestion for one of them

@pixelcmtd thank you for the suggestion. I have applied the change.

2023-05-09 21:15 UTC, pixelcmtd approved these changes

2023-05-09 21:16 UTC, merged