axel: add Spanish translation
tldr-pages/tldr pull request #10089
Opened 2023-04-19 00:55 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-04-19 06:20 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution. We can use long arguments here but IG the current one is fine.

2023-04-19 17:37 UTC, realFranco requested changes

2023-04-19 17:37 UTC, realFranco commented on pages.es/common/axel.md
> +> Soporta HTTP, HTTPS y FTP.
Hello, thank you for the contribution, I'll add a suggestion.

```suggestion
> Protocolos soportados HTTP, HTTPS y FTP.
```

2023-04-19 17:39 UTC, realFranco requested changes

2023-04-19 17:39 UTC, realFranco commented on pages.es/common/axel.md
> +- Descarga una URL a un archivo:
```suggestion
- Descarga un archivo alojado en una URL pública:
```

2023-04-19 17:46 UTC, realFranco requested changes

2023-04-19 17:46 UTC, realFranco commented on pages.es/common/axel.md
> +- Busca copias espejo:
```suggestion
- Busca un archivo utilizando un mirror haciendo uso del motor de búsqueda filesearching.com.
```

2023-05-19 18:53 UTC, navarroaxel commented on pages.es/common/axel.md
> +- Descarga con varias conexiones:
```suggestion
- Descarga con múltiples conexiones:
```

2023-05-19 18:53 UTC, navarroaxel commented on pages.es/common/axel.md
> +- Descarga y especifica nombre de archivo:
```suggestion
- Descarga y especifica un nombre de archivo:
```

2023-05-19 18:53 UTC, navarroaxel commented on pages.es/common/axel.md
> +- Descarga un archivo alojado en una URL pública:
```suggestion
- Descarga un archivo alojado en una URL:
```

2023-05-19 18:53 UTC, navarroaxel commented on pages.es/common/axel.md
> +- Busca un archivo utilizando un mirror haciendo uso del motor de búsqueda filesearching.com.
this is not a translation.

2023-05-23 01:45 UTC, kant commented on pages.es/common/axel.md
> +- Busca un archivo utilizando un mirror haciendo uso del motor de búsqueda filesearching.com.
@navarroaxel fixed

2023-06-27 00:38 UTC, kant commented
[![Codespell](https://github.com/tldr-pages/tldr/actions/workflows/codespell.yml/badge.svg)](https://github.com/tldr-pages/tldr/actions/workflows/codespell.yml)

2023-07-16 05:32 UTC, blueskyson approved these changes

2023-07-16 05:35 UTC, merged