hexdump: add pt_BR translation
tldr-pages/tldr pull request #10338
Opened 2023-06-06 00:10 UTC by paulosell

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-06-14 13:08 UTC, paulosell commented
@waldyrious

2023-06-19 18:45 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

Ref. https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/common-arguments.md

2023-06-19 18:45 UTC, kbdharun commented on pages.pt_BR/common/hexdump.md
> +`hexdump {{nome_do_arquivo}}`
```suggestion
`hexdump {{caminho/para/arquivo}}`
```

2023-06-19 18:45 UTC, kbdharun commented on pages.pt_BR/common/hexdump.md
> +`hexdump -C {{nome_do_arquivo}}`
```suggestion
`hexdump -C {{caminho/para/arquivo}}`
```

2023-06-19 18:45 UTC, kbdharun commented on pages.pt_BR/common/hexdump.md
> +`hexdump -C -n{{numero_de_bytes}} {{nome_do_arquivo}}`
```suggestion
`hexdump -C -n{{numero_de_bytes}} {{caminho/para/arquivo}}`
```

2023-06-19 18:45 UTC, kbdharun commented on pages.pt_BR/common/hexdump.md
> +`hexdump --no-squeezing {{nome_do_arquivo}}`
```suggestion
`hexdump --no-squeezing {{caminho/para/arquivo}}`
```

2023-06-19 22:54 UTC, paulosell commented on pages.pt_BR/common/hexdump.md
> +`hexdump {{nome_do_arquivo}}`
Fixed

2023-06-19 22:54 UTC, paulosell commented on pages.pt_BR/common/hexdump.md
> +`hexdump -C {{nome_do_arquivo}}`
Fixed

2023-06-19 22:54 UTC, paulosell commented on pages.pt_BR/common/hexdump.md
> +`hexdump -C -n{{numero_de_bytes}} {{nome_do_arquivo}}`
Fixed

2023-06-19 22:54 UTC, paulosell commented on pages.pt_BR/common/hexdump.md
> +`hexdump --no-squeezing {{nome_do_arquivo}}`
Fixed

2023-06-20 02:30 UTC, kbdharun approved these changes

2023-08-04 17:47 UTC, waldyrious commented
Are you learning some Portuguese, @kbdharun? 😉

Hey @paulosell, my apologies for taking a long time to get to this. I was going through a busy period and didn't have the mental bandwidth to review PRs with the due attention. I will now take care of this. Hope it wasn't too burdensome a wait!

2023-08-04 17:48 UTC, kbdharun commented
> Are you learning some Portuguese, @kbdharun? 😉

Maybe 😄

Just kidding referred to the common arguments page.

2023-08-04 17:49 UTC, waldyrious requested changes
Great work overall! I'm leaving just a few minor change suggestions.

Note: I realize the standard for the verbal tense to use hasn't been set in stone yet, so apologies if the existing pages gave you the wrong impression about what form to use for the descriptions.

2023-08-04 17:49 UTC, waldyrious commented on pages.pt_BR/common/hexdump.md
> +> Impressão de dados no formato ASCII, decimal, hexadecimal ou octal.
```suggestion
> Imprime dados no formato ASCII, decimal, hexadecimal ou octal.
```

2023-08-04 17:49 UTC, waldyrious commented on pages.pt_BR/common/hexdump.md
> +- Imprime a representação hexadecimal de um arquivo, substituindo linhas duplicadas por '*':
```suggestion
- Imprimir a representação hexadecimal de um arquivo, substituindo linhas duplicadas por '*':
```

2023-08-04 17:49 UTC, waldyrious commented on pages.pt_BR/common/hexdump.md
> +- Imprime a representação hexadecimal e ASCII de um arquivo, em duas colunas:
```suggestion
- Imprimir a representação hexadecimal e ASCII de um arquivo, em duas colunas:
```

2023-08-04 17:49 UTC, waldyrious commented on pages.pt_BR/common/hexdump.md
> +- Imprime a representação hexadecimal de um arquivo, porém apresentando apenas seus n primeiros bytes:
```suggestion
- Imprimir a representação hexadecimal de um arquivo, porém apresentando apenas seus n primeiros bytes:
```

2023-08-04 17:49 UTC, waldyrious commented on pages.pt_BR/common/hexdump.md
> +- Não substitui as linhas duplicadas por '*':
```suggestion
- Imprimir a representação hexadecimal completa de um arquivo (sem omitir linhas duplicadas):
```

2023-08-04 18:45 UTC, paulosell commented
@waldyrious all done! 😄

2023-08-04 23:03 UTC, waldyrious approved these changes
Great job, @paulosell! Thanks for the contribution, and sorry again for the delay! LGTM :+1:

2023-08-04 23:04 UTC, merged