yacc: add page
tldr-pages/tldr pull request #10439
Opened 2023-06-30 04:25 UTC by jahigd02

- [X ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X ] The page(s) have at most 8 examples.
- [X ] The page description(s) have links to documentation or a homepage.
- [ X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-07-03 02:26 UTC, kbdharun requested changes
Thanks for your contribution and welcome to tldr. I would suggest reading the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md) before contributing in future. 

~~I will update this page later today to comply with the style guide.~~ Thanks for the edit, I will review it soon.

2023-07-05 17:25 UTC, jahigd02 commented
Thank you @kbdharun! I appreciate the assistance. I ran the linter so it should be O.K. now.

2023-07-10 06:48 UTC, kbdharun commented
@jahigd02 Made some modifications to the page, can you check if it looks good to you?

2023-07-10 15:20 UTC, jahigd02 reviewed
Looks great :) thanks for all the help

2023-07-10 15:21 UTC, kbdharun commented on pages/common/yacc.md
> +`yacc -d {{path/to/grammar_file.y}}.y -v -b {{prefix}}`
```suggestion
`yacc -d {{path/to/grammar_file.y}} -v -b {{prefix}}`
```

2023-07-13 18:33 UTC, acuteenvy commented on pages/common/yacc.md
> +- Compile a grammar file, replace the 'y' prepending the output files with '{{prefix}}':
```suggestion
- Compile a grammar file, and prefix output filenames with `prefix` instead of `y`:
```

2023-07-14 12:20 UTC, acuteenvy approved these changes

2023-07-14 12:21 UTC, merged