Create list of kill signals for osx
tldr-pages/tldr pull request #10466
Opened 2023-07-07 16:21 UTC by munntjlx

This is mostly a reprint from the man signal (which lists the kill signal types)

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-07-07 16:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10466) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10466) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10466) it.</sub>

2023-07-09 07:31 UTC, kbdharun reviewed
Thanks for your contribution and welcome to tldr. Unfortunately, our style guide doesn't allow for these kinds of lists. 

An alternative is to link to the man page and add the command to check it locally. I have done the same in my suggestion below.

2023-07-09 07:31 UTC, kbdharun commented on pages/osx/signal.md
> +```
```suggestion
> Simplified software signal facilities.
> More information: <https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/signal.3.html>.

- View documentation for the command:

`man signal`
```

2023-07-12 10:30 UTC, kbdharun approved these changes

2023-07-12 13:55 UTC, munntjlx reviewed
Looks great!

2023-07-15 22:34 UTC, acuteenvy requested changes
`signal` is not a command and the linked man page just lists the signals that can be sent to processes via other means.
I don't think there's any other page documenting something that isn't a command.

> \- View documentation for the `signal` command:

If something like this ***is*** allowed, then that line should probably be reworded, as there is no `signal` command.

2023-07-16 17:25 UTC, kbdharun commented
> `signal` is not a command and the linked man page just lists the signals that can be sent to processes via other means.
> I don't think there's any other page documenting something that isn't a command.
> 
> > \- View documentation for the `signal` command:
> 
> If something like this ***is*** allowed, then that line should probably be reworded, as there is no `signal` command.

Yeah, we do have an exception of non command pages for `osx` (Macos) for non invokable daemons, etc. We can reword the the man page description here.

2023-07-16 17:27 UTC, kbdharun commented on pages/osx/signal.md
> +- View documentation for the `signal` command:
```suggestion
- View documentation for the list of signals in Mac OS:
```

2023-07-16 17:29 UTC, acuteenvy commented on pages/osx/signal.md
> +- View documentation for the `signal` command:
```suggestion
- View documentation about signals in Mac OS:
```

2023-07-16 17:34 UTC, acuteenvy commented
Merge whichever suggestion you think is better, I was making one at the same time as you.

2023-07-17 13:06 UTC, kbdharun approved these changes

2023-07-18 15:24 UTC, acuteenvy approved these changes

2023-07-18 17:11 UTC, merged