qm-suspend: add page
tldr-pages/tldr pull request #10469
Opened 2023-07-07 18:13 UTC by BabaYaga1221

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-07-07 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10469) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10469) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10469) it.</sub>

2023-07-07 23:21 UTC, einverne requested changes
Hi thank you for the new page, I left some suggestions for you to take a look.

2023-07-07 23:21 UTC, einverne commented on pages/linux/qm-suspend.md
> +`qm suspend -id 101`
id should in {}

2023-07-07 23:21 UTC, einverne commented on pages/linux/qm-suspend.md
> +> Suspends a virtual machine (VM) in the Proxmox Virtual Environment (PVE) cluster using the "qm" command-line tool.
```suggestion
> Suspends a virtual machine (VM) in the Proxmox Virtual Environment (PVE) .
```

2023-07-07 23:21 UTC, einverne commented on pages/linux/qm-suspend.md
> +- To specifies the ID of the virtual machine to suspend:
```suggestion
- Suspend virtual machine by id:
```

2023-07-08 12:18 UTC, BabaYaga1221 commented
@einverne Thanks sir, can you review now and suggest any other changes?

2023-07-08 18:06 UTC, kbdharun reviewed
Welcome to tldr and Thanks for your contribution. I have some suggestions for this page.

2023-07-08 18:06 UTC, kbdharun commented on pages/linux/qm-suspend.md
> +`qm suspend -{id} 101`
```suggestion
- Suspend virtual machine by id:

`qm suspend {{vm_id}} {{integer}}`
```
We follow a similar structure for other `qm` pages.

2023-07-08 18:06 UTC, kbdharun commented on pages/linux/qm-suspend.md
> +`qm suspend --vmid 101 --skiplock`
```suggestion
- Skip the lock check when suspending the VM:

`qm suspend {{vm_id}} {{integer}} --skiplock`
```

2023-07-08 18:06 UTC, kbdharun commented on pages/linux/qm-suspend.md
> +- To skips the lock check for storage when suspending the VM. Use with caution, as it may lead to data corruption in certain situations:
```suggestion
- Skip the lock check for storage when suspending the VM:
```

2023-07-08 18:06 UTC, kbdharun commented on pages/linux/qm-suspend.md
> +> Suspends a virtual machine (VM) in the Proxmox Virtual Environment (PVE).
```suggestion
> Suspends a virtual machine (VM) in the Proxmox Virtual Environment (PVE).
> Use `--skiplock` and `--skiplockstorage` flags with caution, as they may lead to data corruption in certain situations.
```

2023-07-08 18:06 UTC, kbdharun commented on pages/linux/qm-suspend.md
> +`qm suspend --vmid 101 --skiplockstorage`
```suggestion
`qm suspend {{vm_id}} {{integer}} --skiplockstorage`
```

2023-07-09 09:58 UTC, BabaYaga1221 commented
@kbdharun Thanks for your review, sir. can you please retake a look and suggest any changes?

2023-07-09 10:18 UTC, kbdharun approved these changes

2023-07-09 23:21 UTC, acuteenvy commented on pages/linux/qm-suspend.md
> +- Suspend virtual machine by id:
```suggestion
- Suspend a virtual machine by id:
```

2023-07-10 08:13 UTC, BabaYaga1221 commented
@acuteenvy append the changes as per your suggestion. Thanks

2023-07-12 16:56 UTC, acuteenvy approved these changes

2023-07-12 19:26 UTC, BabaYaga1221 commented
@einverne @acuteenvy @kbdharun can you merge this work? Thanks

2023-07-12 23:48 UTC, einverne approved these changes

2023-07-12 23:48 UTC, merged