cargo-*: add pt_BR translation
tldr-pages/tldr pull request #10502
Opened 2023-07-16 13:10 UTC by isaacvicente

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**
cargo 1.67.1 (8ecd4f20a 2023-01-10)

2023-08-04 18:11 UTC, waldyrious requested changes
@isaacvicente excellent work, thank you! :clap:

I've left some comments, but feel free to push back on any of them in case you disagree. Cheers, and apologies for the delay in getting to this PR (I'll try to handle the other ones ASAP).

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-clippy.md
> +- Exigir que o `Cargo.lock` esteja atualizado:
```suggestion
- Executar verificações garantindo que o `Cargo.lock` esteja atualizado:
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-clippy.md
> +- Tratar avisos como erros:
```suggestion
- Executar validações tratando avisos como erros:
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-doc.md
> +> Construir e visualizar a documentação de um pacote Rust offline.
```suggestion
> Constrói e visualiza a documentação de um pacote Rust, opcionalmente em modo offline.
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-doc.md
> +- Construir e visualizar a documentação padrão do pacote no navegador:
```suggestion
- Construir a documentação padrão do pacote e mostrá-la no navegador:
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-doc.md
> +- Visualizar a documentação de um pacote específico offline:
```suggestion
- Visualizar a documentação de um pacote específico sem acessar a rede:
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-rustc.md
> +> Compilar um pacote Rust e passar opções extras para o compilador.
```suggestion
> Compila um pacote Rust.
```

Não sei se vale a pena mencionar as opções extra na descrição principal, mas estou disposto a ser convencido do contrário :)

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-rustc.md
> +- Compilar os artefatos em modo de lançamento (release), com otimizações:
Como mencionado acima, se calhar "publicação" funciona melhor que "lançamento".

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-rustc.md
> +- Compilar com otimização de tamanho (`z` também desativa a vetorização de loops):
Podemos usar "ciclos" em vez de "loops"?

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-rustc.md
> +- Verificar se o seu pacote usa código inseguro (unsafe):
```suggestion
- Verificar se o pacote usa código com padrões inseguros de acesso à memória:
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-test.md
> +> Executar os testes unitários e de integração de um pacote Rust.
```suggestion
> Executa os testes unitários e de integração de um pacote Rust.
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-test.md
> +- Definir o número de casos de teste em execução simultânea:
```suggestion
- Definir o número de casos de teste para execução simultânea:
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-test.md
> +- Exigir que o `Cargo.lock` esteja atualizado:
```suggestion
- Executar os testes garantindo que o `Cargo.lock` esteja atualizado:
```

2023-08-04 18:11 UTC, waldyrious commented on pages.pt_BR/common/cargo-test.md
> +- Testar os artefatos em modo de lançamento (release), com otimizações:
Novamente, sugiro "publicação".

2023-08-05 00:37 UTC, isaacvicente commented on pages.pt_BR/common/cargo-build.md
> +- Compilar apenas o teste específico:
Acho que "um teste específico" fica mais simples e claro.

2023-08-05 00:38 UTC, isaacvicente commented on pages.pt_BR/common/cargo-build.md
> +- Compilar os artefatos em modo de lançamento (release), com otimizações:
Mudei para "publicação".

2023-08-05 00:40 UTC, isaacvicente commented on pages.pt_BR/common/cargo-rustc.md
> +- Compilar os artefatos em modo de lançamento (release), com otimizações:
Feito.

2023-08-05 00:40 UTC, isaacvicente commented on pages.pt_BR/common/cargo-rustc.md
> +- Compilar com otimização de tamanho (`z` também desativa a vetorização de loops):
Sim, tudo bem por mim.

2023-08-05 00:40 UTC, isaacvicente commented on pages.pt_BR/common/cargo-test.md
> +- Testar os artefatos em modo de lançamento (release), com otimizações:
Feito.

2023-08-05 00:48 UTC, isaacvicente commented
Also, @waldyrious, you don't need to apologize, we're all volunteers :)

2023-08-05 06:08 UTC, waldyrious approved these changes
Thanks for the quick turnaround! Looks good to me :)

2023-08-05 06:10 UTC, waldyrious commented
@kbdharun sorry to ping you but I'm not really sure who are the most active maintainers these days. This PR is ready to go as far as I'm concerned, and just needs an extra approving review.

2023-08-05 06:21 UTC, kbdharun approved these changes

2023-08-05 06:21 UTC, kbdharun commented
> This PR is ready to go as far as I'm concerned, and just needs an extra approving review.

Done

2023-08-05 14:09 UTC, merged