lsync: add page
tldr-pages/tldr pull request #10789
Opened 2023-10-01 16:10 UTC by parth93QA

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-02 10:36 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

2023-10-02 10:36 UTC, kbdharun commented on pages/linux/lsync.md
> +- Lsync with rsync-share ‘share’:
```suggestion
- Lsync with `rsync-share` share:
```

2023-10-02 10:36 UTC, kbdharun commented on pages/linux/lsync.md
> +`lsyncd -rsync {{/source_directory}} {{destination_host:/destination_directory}}`
```suggestion
`lsyncd -rsync {{/source_directory}} {{destination_host::/destination_directory}}`
```

2023-10-02 10:36 UTC, kbdharun commented on pages/linux/lsync.md
> +- Lsync with ssh connection:
```suggestion
- Lsync with SSH connection:
```

2023-10-02 11:05 UTC, parth93QA commented
Hi @kbdharun Done added all the changes as suggested

2023-10-02 11:06 UTC, kbdharun approved these changes

2023-10-02 13:52 UTC, acuteenvy requested changes
The filename is wrong - `lsync.md` instead of `lsyncd.md`. This also works on macOS, so the page should be moved to `common`.

2023-10-02 13:52 UTC, acuteenvy commented on pages/linux/lsync.md
> +`lsyncd -rsync {{/source_directory}} {{destination_host::/destination_directory}}`
https://github.com/lsyncd/lsyncd

>Lsyncd watches a local directory trees event monitor interface (inotify or fsevents). It aggregates and combines events for a few seconds and then ***spawns one (or more) process(es) to synchronize the changes. By default this is [rsync](http://rsync.samba.org/)***.

> `lsyncd -rsync /home remotehost.org::share/`
>
> This watches and rsyncs the local directory /home with all sub-directories and transfers them to 'remotehost' using the rsync-share 'share'.

```suggestion
- Watch the source for changes and run `rsync` to synchronize files to the destination on every change: 

`lsyncd -rsync {{path/to/source}} {{host::share_name}}`
```

2023-10-02 13:52 UTC, acuteenvy commented on pages/linux/lsync.md
> +`lsyncd -rsyncssh {{/home}} {{remotehost.org}} {{backup-home/}}`
```suggestion
- Use SSH instead of `rsyncd` shares:

`lsyncd -rsyncssh {{path/to/source}} {{host}} {{path/to/destination}}`
```

2023-10-02 13:52 UTC, acuteenvy commented on pages/linux/lsync.md
> +# lsync
```suggestion
# lsyncd
```

2023-10-02 13:52 UTC, acuteenvy commented on pages/linux/lsync.md
> +> It is often used to keep two directories on separate systems in sync, ensuring that changes made in one directory are immediately mirrored to the other.
```suggestion
> Watch files and directories and run `rsync` when they change.
> It is often used to keep two directories on separate systems in sync, ensuring that changes made in one directory are immediately mirrored to the other.
```

2023-10-02 15:24 UTC, parth93QA commented
Hi @acuteenvy All the changes are done as suggested

2023-10-02 15:45 UTC, kbdharun approved these changes

2023-10-04 00:56 UTC, acuteenvy approved these changes

2023-10-04 00:56 UTC, merged