resolvectl: add French translation
tldr-pages/tldr pull request #10799
Opened 2023-10-02 09:44 UTC by noraj

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-10-02 10:52 UTC, kbdharun requested changes
Thanks for your contribution. Some examples doesn't seem to align with the main page (https://github.com/tldr-pages/tldr/blob/main/pages/linux/resolvectl.md). Can you update this page to align with the English page or else make the modifications in the English page too?

2023-10-02 12:01 UTC, noraj commented
> Thanks for your contribution. Some examples doesn't seem to align with the main page (https://github.com/tldr-pages/tldr/blob/main/pages/linux/resolvectl.md). Can you update this page to align with the English page or else make the modifications in the English page too?

My bad, I forgot to synchronize my fork. I'll update this.

2023-10-02 12:41 UTC, kbdharun approved these changes

2023-10-04 05:18 UTC, nicokosi approved these changes
Looks good to me! 😎

2023-10-04 05:34 UTC, merged