du, dua, duc: add pt_BR pages
tldr-pages/tldr pull request #10810
Opened 2023-10-02 14:57 UTC by caduvieira

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-03 07:58 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-03 07:58 UTC, kbdharun commented on pages.pt_BR/common/duc.md
> +- Lista todos os arqivos e diretórios dentro do /usr/local, mostrando tamanho relativo dos arquivos em um [g]ráfico:
```suggestion
- Lista todos os arqivos e diretórios dentro do /usr/local, mostrando tamanho relativo dos arquivos em um [g]raph (gráfico):
```

We use mnemonics interchangeably to highlight long/short options. We can use the English word here and wrap the translation inside brackets.

2023-10-08 02:50 UTC, isaacvicente reviewed
Olá! Muito obrigado pela sua contribuição :)
Percebi aqui em que algumas vezes a frase foi traduzida de forma não usual, isto é, a ordem das palavras em inglês foram preservadas na tradução em português.
Recomendo que utilize de alguma IA (Bard, ChatGPT, etc), pois elas facilitarão o seu trabalho, já que ele se torna menos manual.
Ao finalizar a tradução, é aconselhável que você leia em voz alta, pra ver como ficou. Se a tradução soou estranha ou confusa, tente traduzir de outra forma (usando outra IA ou especificando o que quer para ela).

2023-10-08 02:50 UTC, isaacvicente commented on pages.pt_BR/common/du.md
> +> Uso do disco: estima e sumariza arquivos e diretórios do uso em espaço em disco.
```suggestion
> Uso de disco: estima e sumariza o uso de espaço em arquivos e diretórios.
```

2023-10-08 02:50 UTC, isaacvicente commented on pages.pt_BR/common/du.md
> +- Lista  os tamanhos dos diretórios e qualquer subdiretório, em uma unidade de tamanho (B/KiB/MiB):
```suggestion
- Lista os tamanhos dos diretórios e qualquer subdiretório, em uma unidade de tamanho (B/KiB/MiB):
```

2023-10-08 02:50 UTC, isaacvicente commented on pages.pt_BR/common/du.md
> +- Exibe o tamanho de um diretório único, em uma unidade compreensível por humanos:
```suggestion
- Exibe o tamanho de um único diretório, em uma unidade compreensível por humanos:
```

2023-10-08 02:50 UTC, isaacvicente commented on pages.pt_BR/common/du.md
> +- Lista em uma forma compreensível por humanos de um diretório todos os arquivos e diretórios dentro dele:
```suggestion
- Lista os tamanhos legíveis de um diretório e de todos os arquivos e diretórios dentro dele:
```

2023-10-08 02:50 UTC, isaacvicente commented on pages.pt_BR/common/dua.md
> +- Agrega o espaço em disco consumido de mais de m diretório ou arquivos:
```suggestion
- Agrega o espaço em disco consumido de um ou mais diretórios ou arquivos:
```

2023-10-08 02:58 UTC, isaacvicente requested changes
Poderia por favor aplicar as sugestões acima?
Se discordar de qualquer mudança pode falar tranquilo :)

2023-10-12 14:11 UTC, isaacvicente approved these changes
Pronto para merge! Muito obrigado!

2023-10-12 14:11 UTC, merged