yum.md: add Indonesia translation
tldr-pages/tldr pull request #10827
Opened 2023-10-03 08:42 UTC by fadharpra

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-03 08:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10827) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10827) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10827) it.</sub>

2023-10-04 09:42 UTC, fadharpra commented
Hi @reinhart1010, kindly review my request

2023-10-04 22:05 UTC, reinhart1010 requested changes
Hi, here are some comments from mine.

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +- Menginstall sebuah paket baru
```suggestion
- Instal sebuah paket baru
```
Imperative mood.

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +- Menginstall sebuah paket baru dan mengasumsikan jawaban ya untuk semua pertanyaan (juga berfungsi dengan perintah pembaruan, sangat berguna untuk pembaruan otomatis):
```suggestion
- Instal sebuah paket baru dan mengasumsikan jawaban [y]a untuk semua pertanyaan (juga berfungsi dengan perintah pembaruan, sangat berguna untuk pembaruan otomatis):
```

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +- Mencari sebuah paket yang menyediakan suatu perintah tertentu:
```suggestion
- Cari sebuah paket yang menyediakan suatu perintah tertentu:
```

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +- Menghapus sebuah paket
```suggestion
- Hapus paket yang terpasang sebelumnya:
```

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +- Menampilkan pembaruan yang tersedia untuk paket yang terpasang:
```suggestion
- Tampilkan pembaruan yang tersedia untuk paket yang terpasang:
```

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +- Memperbarui seluruh paket yang terpasang ke versi terbaru:
```suggestion
- Perbarui seluruh paket yang terpasang ke versi terbaru:
```

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +> Untuk perintah-perintah setara dalam pengelola paket lainnya, lihat https://wiki.archlinux.org/title/Pacman/Rosetta.
```suggestion
> Untuk perintah-perintah setara dalam pengelola paket lainnya, lihat <https://wiki.archlinux.org/title/Pacman/Rosetta>.
```
Use angled brackets for links (useful for some Markdown parsers like Kramdown)

2023-10-04 22:05 UTC, reinhart1010 commented on pages.id/linux/yum.md
> +> Informasi lebih lanjut: https://manned.org/yum.
```suggestion
> Informasi lebih lanjut: <https://manned.org/yum>.
```

2023-10-05 05:43 UTC, fadharpra commented
Hi @reinhart1010, i've update the file. Kindly check again ya

2023-10-05 07:48 UTC, reinhart1010 approved these changes
Thanks!

2023-10-05 08:05 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution and welcome to tldr.

2023-10-05 08:06 UTC, merged