windows/date: add Indonesian translation
tldr-pages/tldr pull request #10839
Opened 2023-10-04 12:53 UTC by hamexhanif

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-04 12:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10839) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10839) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10839) it.</sub>

2023-10-05 08:22 UTC, reinhart1010 requested changes
Thanks, here are some of my notes to review.

2023-10-05 08:22 UTC, reinhart1010 commented on pages.id/windows/date.md
> +- Menampilkan tanggal sistem saat ini tanpa meminta untuk memasukkan tanggal baru:
```suggestion
- Tampilkan tanggal sistem saat ini tanpa meminta untuk memasukkan tanggal baru:
```

2023-10-05 08:22 UTC, reinhart1010 commented on pages.id/windows/date.md
> +- Mengubah tanggal sistem saat ini ke tanggal tertentu:
```suggestion
- Ubah tanggal sistem saat ini ke tanggal tertentu:
```

2023-10-05 08:25 UTC, kbdharun approved these changes
Thanks for your contribution.
LGTM, after @reinhart1010's suggestions are addressed.

2023-10-05 13:01 UTC, reinhart1010 approved these changes
Thanks!

2023-10-05 13:22 UTC, kbdharun commented
Note: The reason why I closed and reopened the PR was to trigger a rerun of the stuck CI check (which happens sometimes due to some issue with GitHub API). Now it has passed,  will merge the PR.

2023-10-05 13:22 UTC, merged