windows/cd: update Indonesian translation
tldr-pages/tldr pull request #10841
Opened 2023-10-04 13:18 UTC by hamexhanif

add the 'go to root' description, reorder the translation according to the English version, update some translation details to obey the translation guideline

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-04 22:23 UTC, reinhart1010 requested changes
Hi, I'd like to request these changes, please.

2023-10-04 22:23 UTC, reinhart1010 commented on pages.id/windows/cd.md
> +- Menuju direktori tertentu di drive [d] yang berbeda:
```suggestion
- Pergi menuju direktori tertentu di [d]rive yang berbeda:
```

2023-10-04 22:23 UTC, reinhart1010 commented on pages.id/windows/cd.md
>  - Menampilkan nama dari direktori saat ini:
```suggestion
- Tampilkan nama dari direktori saat ini:
```
Imperative mood, see #8576

2023-10-04 22:23 UTC, reinhart1010 commented on pages.id/windows/cd.md
> +- Menuju root dari drive saat ini:
```suggestion
- Pergi menuju root dari drive saat ini:
```

2023-10-04 22:23 UTC, reinhart1010 commented on pages.id/windows/cd.md
>  - Menuju ke induk direktori dari direktori saat ini:
```suggestion
- Pergi menuju induk dari direktori dari saat ini:
```

2023-10-04 22:23 UTC, reinhart1010 commented on pages.id/windows/cd.md
> +- Menuju suatu direktori pada drive yang sama:
```suggestion
- Pergi menuju suatu direktori pada drive yang sama:
```

2023-10-05 08:17 UTC, reinhart1010 approved these changes
Thanks!

2023-10-05 08:23 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-05 08:24 UTC, merged