rmlint: add tagged example
tldr-pages/tldr pull request #10854
Opened 2023-10-05 12:24 UTC by xeruf

The terminology "issues" was very unclear, rmlint does not fix filesystem issues, only remove files. Also the tagged dirs concept which is vital was missing.

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** 2.10.2 on Arch

2023-10-07 15:42 UTC, gutjuri requested changes

2023-10-07 15:42 UTC, gutjuri commented on pages/common/rmlint.md
> +> Eliminate duplicate files and other file waste.
```suggestion
> Eliminate duplicate files and other  waste of storage.
```

2023-10-27 17:39 UTC, kbdharun commented on pages/common/rmlint.md
> +> More information: <https://rmlint.readthedocs.io/en/master/rmlint.1.html>.
```suggestion
> More information: <https://rmlint.readthedocs.io/en/latest/rmlint.1.html>.
```

2023-10-27 18:36 UTC, gutjuri approved these changes

2023-10-27 18:36 UTC, merged