php: add Deutsch translations
tldr-pages/tldr pull request #10857
Opened 2023-10-05 18:46 UTC by TheBulaDev

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-06 07:06 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

The path placeholder seems to be only translated as `file` instead of `path/to/file`.

2023-10-06 07:06 UTC, kbdharun commented on pages.de/common/php.md
> +`php {{datei}}`
```suggestion
`php {{pfad/zu/datei}}`
```

2023-10-06 07:06 UTC, kbdharun commented on pages.de/common/php.md
> +`php -l {{datei}}`
```suggestion
`php -l {{pfad/zu/datei}}`
```

2023-10-07 16:02 UTC, gutjuri requested changes

2023-10-07 16:02 UTC, gutjuri commented on pages.de/common/php.md
> +- Überprüfen Sie die Syntax eines PHP-Skripts:
```suggestion
- Überprüfe die Syntax eines PHP-Skripts:
```

2023-10-07 16:02 UTC, gutjuri commented on pages.de/common/php.md
> +- Analysieren Sie ein PHP-Skript und führen Sie es aus:
```suggestion
- Analysiere ein PHP-Skript und führe es aus:
```

2023-10-07 16:02 UTC, gutjuri commented on pages.de/common/php.md
> +`php -r "{{code}}"`
```suggestion
`php -r "{{befehl}}"`
```

2023-10-08 18:39 UTC, TheBulaDev commented on pages.de/common/php.md
> +- Informationen zu einer bestimmten Funktion anzeigen:
Vielen Dank für alle Ihre Vorschläge

2023-10-08 22:05 UTC, gutjuri approved these changes

2023-10-09 01:18 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-09 03:51 UTC, merged