shnsplit: add
tldr-pages/tldr pull request #10861
Opened 2023-10-06 01:56 UTC by Narfinger

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-06 01:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10861) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10861) before we can accept your contribution.<br/><hr/>**Narfinger** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10861) it.</sub>

2023-10-07 16:20 UTC, gutjuri requested changes

2023-10-07 16:20 UTC, gutjuri commented on pages/linux/shnsplit.md
> +`shnsplit -f file.cue file.wav`
```suggestion
`shnsplit -f {{path/to/file.cue}} {{path/to/file.wav}}`
```

2023-10-07 16:20 UTC, gutjuri commented on pages/linux/shnsplit.md
> +`shnsplit -f file.cue -o flac file.flac`
```suggestion
`shnsplit -f {{path/to/file.cue}} -o flac {{path/to/file.flac}}`
```

2023-10-07 16:20 UTC, gutjuri commented on pages/linux/shnsplit.md
> +`shnsplit -f file.cue file.wav -t "%n - %a - %t`
```suggestion
`shnsplit -f {{path/to/file.cue}} {{path/to/file.wav}} -t "%n - %a - %t`
```

2023-10-07 16:20 UTC, gutjuri commented on pages/linux/shnsplit.md
> +- Split a wav + cue file into multiple files:
```suggestion
- Split a .wav + .cue file into multiple files:
```

2023-10-07 16:20 UTC, gutjuri commented on pages/linux/shnsplit.md
> +- Split a flac file into multiple files:
```suggestion
- Split a .flac file into multiple files:
```

2023-10-07 16:20 UTC, gutjuri commented on pages/linux/shnsplit.md
> +- Split a wav file into files of the form track-number - album - title:
```suggestion
- Split a .wav file into files of the form track-number - album - title:
```

2023-10-09 07:39 UTC, gutjuri approved these changes

2023-10-10 07:46 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

Seems like `shtool split` is an alias of this so I will add an alias page too here for this.

Ref. 
```zsh
➜  ~ shnsplit
shnsplit: error: if file to be split is not given, then a split point file must be specified
shnsplit: 
shnsplit: type 'shnsplit -h' for help
➜  ~ shntool split
shntool [split]: error: if file to be split is not given, then a split point file must be specified
shntool [split]: 
shntool [split]: type 'shntool split -h' for help
```

2023-10-10 07:46 UTC, kbdharun commented on pages/linux/shnsplit.md
> +- Split a .wav file into files of the form track-number - album - title:
```suggestion
- Split a `.wav` file into files of the form "track-number - album - title":
```

2023-10-10 07:46 UTC, kbdharun commented on pages/linux/shnsplit.md
> +- Split a .flac file into multiple files:
```suggestion
- Split a `.flac` file into multiple files:
```

2023-10-10 07:51 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-10 07:52 UTC, merged