lz: add page
tldr-pages/tldr pull request #10870
Opened 2023-10-06 08:08 UTC by gutjuri

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Again a command with no options resulting in a short tldr page.

2023-10-07 07:43 UTC, reinhart1010 requested changes
Thanks for contributing! I'd like to suggest the following changes to simplify the command explanations.

2023-10-07 07:43 UTC, reinhart1010 commented on pages/linux/lz.md
> +> Shows a listing of the files inside a '.tar.gz' compressed archive.
```suggestion
> List all files inside a '.tar.gz' compressed archive.
```

2023-10-07 07:43 UTC, reinhart1010 commented on pages/linux/lz.md
> +- Show a listing of the files inside a compressed archive:
```suggestion
- List all files inside a compressed archive:
```

2023-10-08 13:22 UTC, reinhart1010 approved these changes
Thanks! But we will need to wait for another maintainer to approve this before doing the merge.

2023-10-08 13:58 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-08 13:58 UTC, merged