systemd-inhibit: add page
tldr-pages/tldr pull request #10879
Opened 2023-10-06 16:52 UTC by rothgar

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**
253

Adds command to #10191

2023-10-06 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10879) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10879) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10879) it.</sub>

2023-10-07 16:27 UTC, gutjuri requested changes

2023-10-07 16:27 UTC, gutjuri commented on pages/linux/systemd-inhibit.md
> +- Block system shutdown with sleep command:
```suggestion
- Block system shutdown for {{5}} seconds with sleep command:
```

2023-10-08 08:27 UTC, gutjuri approved these changes
Thanks!

2023-10-08 16:44 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution. I have some suggestions for this page.

2023-10-08 16:44 UTC, kbdharun commented on pages/linux/systemd-inhibit.md
> +- Block system shutdown for {{5}} seconds with sleep command:
```suggestion
- Block system shutdown for a specified number of seconds with the `sleep` command:
```

2023-10-08 16:44 UTC, kbdharun commented on pages/linux/systemd-inhibit.md
> +- Keep system from sleeping or idling until after download is finished:
```suggestion
- Keep the system from sleeping or idling until after the download is completed:
```

2023-10-08 16:44 UTC, kbdharun commented on pages/linux/systemd-inhibit.md
> +> Prohibit system from entering certain power states.
```suggestion
> Prohibit the system from entering certain power states.
```

2023-10-09 19:16 UTC, gutjuri approved these changes

2023-10-09 21:53 UTC, acuteenvy commented on pages/linux/systemd-inhibit.md
> +- List all active inhibition locks instead of acquiring one:
```suggestion
- List all active inhibition locks:
```

2023-10-09 21:53 UTC, acuteenvy commented on pages/linux/systemd-inhibit.md
> +- Keep the system from sleeping or idling until after the download is completed:
```suggestion
- Keep the system from sleeping or idling until the download is complete:
```

2023-10-09 21:53 UTC, acuteenvy commented on pages/linux/systemd-inhibit.md
> +- Ignore lid close switch until script exits:
```suggestion
- Ignore lid close switch until the script exits:
```

2023-10-09 21:53 UTC, acuteenvy commented on pages/linux/systemd-inhibit.md
> +`systemd-inhibit --who $USER --what shutdown sleep {{5}}`
Moved to another example to describe the option.
```suggestion
`systemd-inhibit --what shutdown sleep {{5}}`
```

2023-10-09 21:53 UTC, acuteenvy commented on pages/linux/systemd-inhibit.md
> +`systemd-inhibit --what handle-power-key {{command}}`
```suggestion
`systemd-inhibit --what handle-power-key {{command}}`

- Describe who and why created the inhibitor (default: the command and its arguments for `--who` and `Unknown reason` for `--why`):

`systemd-inhibit --who {{$USER}} --why {{reason}} --what {{operation}} {{command}}`
```

2023-10-10 03:27 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-10 03:28 UTC, merged