systemd-repart: add page
tldr-pages/tldr pull request #10880
Opened 2023-10-06 17:35 UTC by rothgar

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**
253

Adds command to #10191

2023-10-06 17:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10880) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10880) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10880) it.</sub>

2023-10-07 16:33 UTC, gutjuri requested changes

2023-10-07 16:33 UTC, gutjuri commented on pages/linux/systemd-repart.md
> +- Grow root partition size by 10 gigabytes:
```suggestion
- Grow root partition size to 10 gigabytes:
```
This is my understanding after reading the documentation. Is this correct?

2023-10-08 08:26 UTC, gutjuri approved these changes
Thanks!

2023-10-09 12:10 UTC, reinhart1010 approved these changes
LGTM, thanks for contributing!

2023-10-09 12:10 UTC, merged