qm cloud-init : add page
tldr-pages/tldr pull request #10891
Opened 2023-10-08 07:43 UTC by AaryaZ

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-08 07:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10891) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10891) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10891) it.</sub>

2023-10-08 16:06 UTC, kbdharun requested changes
Welcome to tldr and thanks for your contribution. In future, please read the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md) before creating a PR. In this case, I will manually update your page and fix it.

2023-10-08 16:23 UTC, AaryaZ commented
@kbdharun I will make the changes according to the style guide.

2023-10-08 16:29 UTC, kbdharun approved these changes

2023-10-10 05:26 UTC, kbdharun commented
> @kbdharun can you let me know what changes should be done so that the pr will be merged. also can you add hacktoberfest label to the pr

This PR will get merged once another maintainer approves it. And this PR is valid for hacktoberfest without adding the label as we add hacktoberfest topic to our repositories by default. Your contribution once merged will get counted over there after a 7 day wait period.

2023-10-11 04:28 UTC, blueskyson approved these changes

2023-10-11 05:25 UTC, merged