gladtex: add page
tldr-pages/tldr pull request #10892
Opened 2023-10-08 08:06 UTC by Sadeeed

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

issue: #7560

2023-10-08 08:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10892) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10892) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10892) it.</sub>

2023-10-08 16:41 UTC, kbdharun commented
@Sadeeed Thanks for your contribution, can you sign the CLA for the PR to go through?

2023-10-08 19:11 UTC, Sadeeed commented
@kbdharun signed, thanks

2023-10-09 12:03 UTC, reinhart1010 requested changes
Thanks for signing! Here are some note from mine to review:

+ It's okay to use `{{path/to/input.htex}}` and so
+ We prefer to use **command mnemonics** for command lines with short parameters (e.g. `-h` for `[h]elp`)

2023-10-09 12:03 UTC, reinhart1010 commented on pages/common/gladtex.md
> +`gladtex {{input_file.htex}} -b {{background_color}} -f {{foreground_color}}`
```suggestion
`gladtex {{path/to/input.htex}} -b {{background_color}} -f {{foreground_color}}`
```

2023-10-09 12:03 UTC, reinhart1010 commented on pages/common/gladtex.md
> +`pandoc -s -t html --gladtex {{file.md}} | gladtex -o {{file.html}}`
```suggestion
`pandoc -s -t html --gladtex {{path/to/input.md}} | gladtex -o {{path/to/output.html}}`
```

2023-10-10 03:35 UTC, kbdharun commented on pages/common/gladtex.md
> +> A LaTeX formula preprocessor for HTML files. Converts LaTeX formulas to images.
```suggestion
> A LaTeX formula preprocessor for HTML files.
> It converts LaTeX formulas to images.
```

2023-10-10 03:36 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-10 05:05 UTC, reinhart1010 approved these changes
Thanks!

2023-10-10 05:06 UTC, merged