git-guilt: add page
tldr-pages/tldr pull request #10890
Opened 2023-10-08 07:17 UTC by Sadeeed

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

#5137

2023-10-08 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10890) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10890) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10890) it.</sub>

2023-10-09 12:06 UTC, reinhart1010 requested changes
Thanks for contributing! Here are some of my notes to review.

2023-10-09 12:06 UTC, reinhart1010 commented on pages/common/git-guilt.md
> +`git guilt {{revision}} {{revision}}`
```suggestion
`git guilt {{first_revision}} {{last_revision}}`
```

2023-10-10 03:09 UTC, reinhart1010 approved these changes
Thanks! We need to wait naother maintainer to approve this before finally merge this PR.

2023-10-10 08:08 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-10 08:09 UTC, merged