Create ls.md
tldr-pages/tldr pull request #10900
Opened 2023-10-08 19:07 UTC by pranavupadhyay123

can you please tag this PR for "hacktoberfest"

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-08 19:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10900) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10900) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10900) it.</sub>

2023-10-09 04:02 UTC, kbdharun requested changes
Welcome to tldr and thanks for your contribution.

This page doesn't seem to align with an English page as we have `ls` in the [common directory](https://github.com/tldr-pages/tldr/blob/main/pages/common/ls.md) with commands that is the same between multiple platforms. Please translate that page instead.

Edit. This PR is already eligible for hacktoberfest as we have tagged our repos with the hacktoberfest label, once this PR gets merged your contribution will get counted there after a 7 day wait period.

2023-10-09 18:04 UTC, kbdharun approved these changes

2023-10-11 17:51 UTC, pranavupadhyay123 commented
hey, can you please label this PR for Hacktober Fest
`hacktoberfest-accepted`

2023-10-12 00:59 UTC, kbdharun commented
> hey, can you please label this PR for Hacktober Fest
> `hacktoberfest-accepted`

Hi, we automatically label any PRs that weren't merged with this label after October 29th.

Regarding this PR, it will automatically get counted after another maintainer approves and merges it.

2023-10-15 07:47 UTC, blueskyson approved these changes

2023-10-15 07:51 UTC, merged