scala-cli: add page
tldr-pages/tldr pull request #10909
Opened 2023-10-09 14:20 UTC by xRuiAlves

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** `1.0.4`

2023-10-09 14:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10909) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10909) it.</sub>

2023-10-09 14:50 UTC, pixelcmtd commented on pages/common/scala-cli.md
> +> More information: <https://scala-cli.virtuslab.org/>.
```suggestion
> More information: <https://scala-cli.virtuslab.org/docs/overview/>.
```

2023-10-09 15:09 UTC, pixelcmtd reviewed
oops I missed that

2023-10-09 15:09 UTC, pixelcmtd commented on pages/common/scala-cli.md
> +`scala-cli run {{script.scala}}`
```suggestion
`scala-cli run {{path/to/script.scala}}`
```

2023-10-09 15:09 UTC, pixelcmtd commented on pages/common/scala-cli.md
> +`scala-cli test {{script.scala}}`
```suggestion
`scala-cli test {{path/to/script.scala}}`
```

2023-10-09 15:09 UTC, pixelcmtd commented on pages/common/scala-cli.md
> +`scala-cli fmt {{script.scala}}`
```suggestion
`scala-cli fmt {{path/to/script.scala}}`
```

2023-10-09 15:09 UTC, pixelcmtd commented on pages/common/scala-cli.md
> +`scala-cli setup-ide {{script.scala}}`
```suggestion
`scala-cli setup-ide {{path/to/script.scala}}`
```

2023-10-10 03:55 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-10 03:55 UTC, kbdharun commented on pages/common/scala-cli.md
> +> Command-line tool to interact with the Scala language.
```suggestion
> Tool to interact with the Scala language.
```
Ref. https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#descriptions

2023-10-10 08:19 UTC, xRuiAlves commented on pages/common/scala-cli.md
> +> Command-line tool to interact with the Scala language.
Thanks! Makes sense

2023-10-10 08:21 UTC, kbdharun approved these changes

2023-10-11 07:55 UTC, gutjuri requested changes

2023-10-11 07:55 UTC, gutjuri commented on pages/common/scala-cli.md
> +- Format a Scala script:
Does it format the file in-place or does it output the formatted contents to stdout?

2023-10-11 11:42 UTC, gutjuri approved these changes
Thanks!

2023-10-11 15:40 UTC, xRuiAlves commented
@pixelcmtd Did I cover all of your suggestions? 🤔

2023-10-11 16:26 UTC, merged