nitch: add page
tldr-pages/tldr pull request #10917
Opened 2023-10-10 04:26 UTC by npv12

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-10 04:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10917) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10917) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10917) it.</sub>

2023-10-10 08:25 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution. I have some suggestions for this page.

Note: We use generic descriptions like `Display help:` and `Display version:` for help and version examples.

2023-10-10 08:25 UTC, kbdharun commented on pages/linux/nitch.md
> +- Return the system info like hostname, kernel, uptime, etc.:
```suggestion
- Return the system information like hostname, kernel, uptime, etc.:
```

2023-10-10 08:25 UTC, kbdharun commented on pages/linux/nitch.md
> +`nitch -f`
```suggestion
- Fetch the system information:

`nitch -f`

- Display help:

`nitch -h`

- Display version:

`nitch -v`
```

2023-10-10 11:30 UTC, npv12 commented
> Welcome to tldr and thanks for your contribution. I have some suggestions for this page.
> 
> Note: We use generic descriptions like `Display help:` and `Display version:` for help and version examples. Also we place these examples at the last part of the page with help being the last second command and version being the last one.

Thanks! Updated my MR

2023-10-10 15:59 UTC, kbdharun approved these changes

2023-10-10 22:14 UTC, acuteenvy commented on pages/linux/nitch.md
> +`nitch -f`
This is exactly the same as `nitch` without arguments.
```suggestion
```

2023-10-10 22:14 UTC, acuteenvy commented on pages/linux/nitch.md
> +`nitch -v`
https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax
```suggestion
- Display help:

`nitch --help`

- Display version:

`nitch --version`
```

2023-10-11 07:48 UTC, gutjuri requested changes
Thanks for your contribution. However, I'd delete the description of the -f option, as it does not seem to have an effect  ([it's not even implemented](https://github.com/ssleert/nitch/blob/main/src/flags/argParser.nim)). There also seems to be a `-a/--no-ascii` option, which is undocumented. I'm not sure whether it does anything, as I'm not familiar with the program. You might be a better judge to decide whether or not to include this option in the tldr page.

2023-10-11 07:48 UTC, gutjuri commented on pages/linux/nitch.md
> +
```suggestion
```

I'd delete this, as `-f` does not have an effect.

2023-10-11 07:55 UTC, npv12 commented
> Thanks for your contribution. However, I'd delete the description of the -f option, as it does not seem to have an effect ([it's not even implemented](https://github.com/ssleert/nitch/blob/main/src/flags/argParser.nim)). There also seems to be a `-a/--no-ascii` option, which is undocumented. I'm not sure whether it does anything, as I'm not familiar with the program. You might be a better judge to decide whether or not to include this option in the tldr page.

--no-ascii has no effect

2023-10-11 07:58 UTC, gutjuri approved these changes

2023-10-11 08:30 UTC, merged