pstoedit: add page
tldr-pages/tldr pull request #10939
Opened 2023-10-11 21:55 UTC by RedDeliciousApples

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**
4.00

see #7909

2023-10-12 10:36 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution. I have some suggestions for this page.

I am not sure if `magick` format is supported. I couldn't test the official packages as the site's download link didn't work. I downloaded `pstoedit` from Fedora repos and this is what I got in the output:

[out.txt](https://github.com/tldr-pages/tldr/files/12880374/out.txt)

@pixelcmtd Can you confirm if this flag works?

2023-10-12 10:36 UTC, kbdharun commented on pages/linux/pstoedit.md
> +- Convert a PDF page to PNG or JPEG [f]ormat:
```suggestion
- Convert a PDF page to PNG or JPEG format:
```
The long option doesn't seem to be present in the [manual](http://www.calvina.de/pstoedit/pstoedit.htm)

2023-10-12 10:36 UTC, kbdharun commented on pages/linux/pstoedit.md
> +`pstoedit -page {{page_number}}  -f magick {{filename}}  page.png|page.jpg`
```suggestion
`pstoedit -page {{page_number}}  -f magick {{path/to/file.pdf}}  {{page.png|page.jpg]}}`
```

2023-10-12 10:36 UTC, kbdharun commented on pages/linux/pstoedit.md
> +`pstoedit -f magick {{filename}} page%d.png|page%d.jpg`
```suggestion
`pstoedit -f magick {{path/to/file}} {{page%d.png|page%d.jpg}}`
```

2023-10-12 20:35 UTC, gutjuri requested changes

2023-10-12 20:35 UTC, gutjuri commented on pages/linux/pstoedit.md
> +> More information: <http://www.pstoedit.net/>.
```suggestion
> More information: <http://www.pstoedit.net>.
```

2023-10-12 20:35 UTC, gutjuri commented on pages/linux/pstoedit.md
> +`pstoedit -page {{page_number}}  -f magick {{path/to/file.pdf}}  {{page.png|page.jpg]}}`
```suggestion
`pstoedit -page {{page_number}} -f magick {{path/to/file.pdf}} {{page.png|page.jpg]}}`
```

2023-10-13 07:01 UTC, gutjuri approved these changes

2023-10-21 16:32 UTC, kbdharun approved these changes

2023-10-21 16:32 UTC, merged