nvim, passwd, rsync, rmdir, tldr: add pt_BR translation
tldr-pages/tldr pull request #10931
Opened 2023-10-11 12:30 UTC by cmhpedro

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-12 10:08 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-12 14:37 UTC, isaacvicente requested changes
Olá! Suas traduções estão muito boas, porém tem uma coisa importante:
os verbos precisam estar no presente do indicativo, ou seja, em vez de "transferir", use "transfere". Pense que o tempo verbal é aquele em que você descreve o que o comando faz. Logo, "esse comando **faz** algo" faz mais sentido que "esse comando _fazer_ algo", concorda?

Fiz as sugestões necessárias. Assim que elas forem commitadas, aplicarei o merge!
(obs.: as páginas que você traduziu são bastante relevantes! valeu por isso!!)

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Abrir um arquivo:
```suggestion
- Abre um arquivo:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Entrar no modo de edição de texto (mode de inserção):
```suggestion
- Entra no modo de edição de texto (mode de inserção):
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Copiar ("puxar") ou cortar ("apagar") a linha atual (cole-a com `P`):
```suggestion
- Copia ("yank") ou recorta ("delete") a linha atual (cole-a com `P`):
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Entrar no modo normal e desfazer a última operação:
```suggestion
- Entra no modo normal e desfaz a última operação:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Procurar por um padrão em um arquivo (pressione `n`/ `N` para ir para a próxima/prévia correspondência):
```suggestion
- Procura por um padrão em um arquivo (pressione `n`/ `N` para ir para a próxima/prévia correspondência):
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Executar uma substituição de expressão regular em todo o arquivo:
```suggestion
- Executa uma substituição de expressão regular em todo o arquivo:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Entrar no modo normal, salvar (gravar) o arquivo e sair:
```suggestion
- Entra no modo normal, salva (grava) o arquivo e sai:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/nvim.md
> +- Sair sem salvar:
```suggestion
- Sai sem salvar:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/passwd.md
> +- Alterar a senha do usuário atual interativamente:
```suggestion
- Altera a senha do usuário atual interativamente:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/passwd.md
> +- Alterar a senha de um usuário específico:
```suggestion
- Altera a senha de um usuário específico:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/passwd.md
> +- Obter o status atual do usuário:
```suggestion
- Obtém o status atual do usuário:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/passwd.md
> +- Deixar a senha da conta em branco (isso definirá a conta nomeada como sem senha):
```suggestion
- Deixa a senha da conta em branco (isso definirá a conta nomeada como sem senha):
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Transferir um arquivo:
```suggestion
- Transfere um arquivo:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Usar o modo de arquivo (recursivamente copiar diretórios, copiar links simbólicos sem resolver e preservar permissões, propriedade e tempos de modificação):
```suggestion
- Usa o modo de arquivo (copia recursivamente diretórios, copia links simbólicos sem resolver e preserva permissões, propriedade e tempos de modificação):
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Comprimir os dados à medida que são enviados ao destino, exibir progresso detalhado e legível, e manter arquivos parcialmente transferidos se forem interrompidos:
```suggestion
- Comprime os dados à medida que são enviados ao destino, exibe progresso detalhado e legível, e mantém arquivos parcialmente transferidos se forem interrompidos:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Recursivamente copiar diretórios:
```suggestion
- Copia recursivamente diretórios:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Transferir os conteúdos do diretório, mas não o diretório em si:
```suggestion
- Transfere os conteúdos do diretório, mas não o diretório em si:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Recursivamente copiar diretórios, user modo de arquivo, resolver links simbólicos e ignorar arquivos que são mais recentes no destino:
```suggestion
- Copia recursivamente diretórios, usa o modo de arquivamento, resolve links simbólicos e ignora arquivos que são mais recentes no destino:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/linux/rmdir.md
> +- Remover diretórios específicos:
```suggestion
- Remove diretórios específicos:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/linux/rmdir.md
> +- Remover diretórios aninhados específicos recursivamente:
```suggestion
- Remove diretórios aninhados específicos recursivamente:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/tldr.md
> +- Imprimir a página do tldr para um subcomando específico:
```suggestion
- Imprime a página do tldr para um subcomando específico:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/tldr.md
> +- Imprimir a página do tldr para um comando para uma [p]lataforma específica:
```suggestion
- Imprime a página do tldr para um comando para uma [p]lataforma específica:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/tldr.md
> +- Atualizar o cache local das páginas do tldr:
```suggestion
- Atualiza o cache local das páginas do tldr:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Transferir um diretório para um host remoto executando o `rsyncd` and excluir arquivos no destino que não existam na origem:
```suggestion
- Transfere um diretório para um host remoto executando o `rsyncd` and exclui arquivos no destino que não existem na origem:
```

2023-10-12 14:37 UTC, isaacvicente commented on pages.pt_BR/common/rsync.md
> +- Transferir um arquivo por SSH usando uma porta diferente da padrão (22) e mostrar o progresso global:
```suggestion
- Transfere um arquivo por SSH usando uma porta diferente da padrão (22) e mostra o progresso global:
```

2023-10-12 14:41 UTC, isaacvicente commented
Para aplicar todas as sugestões em um único commit (o que recomendamos), basta, em cada sugestão, clicar em "**Add suggestion to batch**". No final você dá o commit final.
Espero ter ajudado :)

![image](https://github.com/tldr-pages/tldr/assets/77455425/271f0845-9264-4b29-ae03-b6efa8ce004b)

2023-10-12 15:29 UTC, cmhpedro commented
Obrigado pelas observações e orientações! Todas elas já foram devidamente commitadas!

2023-10-13 20:47 UTC, isaacvicente approved these changes
De novo, muito obrigado pela sua contribuição :heart:
Espero que traduza mais páginas :)

2023-10-13 20:47 UTC, merged