az-apim, az, az-storage, az-group, az-tag, az-upgrade: add Spanish translation
tldr-pages/tldr pull request #10946
Opened 2023-10-12 08:40 UTC by crixodia

Added Spanish translation for the following pages:

- az-apim
- az,
- az-storage
- az-group
- az-tag
- az-upgrade

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-12 10:43 UTC, kbdharun requested changes
Thanks for your contribution.

Note to maintainers: This PR can be reviewed for files other than az-storage, we can review it after #10947's merge.

2023-10-12 12:41 UTC, kant commented
@kbdharun ok

2023-10-12 18:36 UTC, kant commented on pages.es/common/az-apim.md
> +- Crear una instancia de servicio de API Management:
Crear --> Crea

2023-10-12 18:43 UTC, kant commented on pages.es/common/az-apim.md
> +- Muestra detalles de una instancia de servicio de API Management:
instancia de servicio --> instancia del servicio

2023-10-13 21:31 UTC, kant approved these changes

2023-10-14 09:54 UTC, kbdharun approved these changes

2023-10-14 09:54 UTC, merged

2023-10-14 14:48 UTC, kant reviewed
LGTM