httpie: add german translation
tldr-pages/tldr pull request #10966
Opened 2023-10-13 06:30 UTC by jnmcfly

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-13 07:06 UTC, gutjuri requested changes
Apart from that LTGM. Thanks for your contribution!

2023-10-13 07:06 UTC, gutjuri commented on pages.de/common/httpie.md
> +- Sende eine POST-Anfrage mit umgeleiteter Eingabe:
```suggestion
- Sende eine POST-Anfrage mit einer Datei als Eingabe:
```

2023-10-17 06:27 UTC, gutjuri approved these changes

2023-10-19 09:36 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-19 09:37 UTC, merged