gcloud: add german translation
tldr-pages/tldr pull request #10961
Opened 2023-10-12 19:07 UTC by jnmcfly

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-12 20:13 UTC, gutjuri requested changes
Thanks for your contribution. In general, we use imperative in command descriptions. Apart from that, it looks good.

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Alle Eigenschaften in deiner aktiven Konfiguration auflisten:
```suggestion
- Liste alle Eigenschaften der aktiven Konfiguration auf:
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Bei deinem Google-Konto anmelden:
```suggestion
- Mit einem Google-Konto anmelden:
```

Imperative is very hard in this case, I wouldn't know how to do it.

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Das aktive Projekt festlegen:
```suggestion
- Lege das aktive Projekt fest:
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Eine SSH-Verbindung zu einer virtuellen Maschineninstanz herstellen:
```suggestion
- Stelle eine SSH-Verbindung zu einer virtuellen Maschineninstanz her:
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Alle Google Compute Engine-Instanzen in einem Projekt anzeigen. Instanzen aus allen Zonen werden standardmäßig aufgelistet:
```suggestion
- Zeige alle Google Compute Engine-Instanzen in einem Projekt an. Standardmäßig werden Instanzen aus allen Zonen aufgelistet:
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Eine kubeconfig-Datei mit den entsprechenden Anmeldeinformationen aktualisieren, um kubectl auf einen bestimmten Cluster in Google Kubernetes Engine auszurichten:
```suggestion
- Aktualisiere eine kubeconfig-Datei mit den entsprechenden Anmeldeinformationen, um kubectl auf einen bestimmten Cluster in Google Kubernetes Engine auszurichten:
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Alle gcloud CLI-Komponenten aktualisieren:
```suggestion
- Aktualisiere alle gcloud CLI-Komponenten:
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +- Hilfe für einen bestimmten Befehl anzeigen:
```suggestion
- Zeige Hilfe für einen bestimmten Befehl an:
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +
```suggestion
```

2023-10-12 20:13 UTC, gutjuri commented on pages.de/common/gcloud.md
> +
Remove empty line

2023-10-13 07:01 UTC, gutjuri approved these changes
Thank you!

2023-10-14 03:51 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-14 03:51 UTC, merged