az: update links and description
tldr-pages/tldr pull request #10963
Opened 2023-10-12 20:15 UTC by sebastiaanspeck

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-13 07:09 UTC, gutjuri requested changes
Thanks you! Looks fine to me, apart from the german word "Befehlszeile", which I changed to "Kommandozeile" in my suggestion.

2023-10-13 07:09 UTC, gutjuri commented on pages.de/common/az-config.md
> +> Teil von `az`, der Befehlszeilenschnittstelle von Azure.
```suggestion
> Teil von `az`, der Kommandozeilenschnittstelle von Azure.
```

2023-10-13 07:09 UTC, gutjuri commented on pages.de/common/az-logout.md
> +> Teil von `az`, der Befehlszeilenschnittstelle von Azure.
```suggestion
> Teil von `az`, der Kommandozeilenschnittstelle von Azure.
```

2023-10-13 11:04 UTC, sebastiaanspeck commented
> Thanks you! Looks fine to me, apart from the german word "Befehlszeile", which I changed to "Kommandozeile" in my suggestion.

Changed in all three az-files. Thank you for the suggestion!

2023-10-13 11:12 UTC, gutjuri commented
LGTM

2023-10-13 11:15 UTC, gutjuri approved these changes

2023-10-13 21:37 UTC, kant commented on pages.es/common/az-appconfig.md
>  > Administra configuraciones de aplicaciones en Azure.
Administra configuraciones --> Administra las configuraciones

2023-10-13 21:40 UTC, kant commented on pages.es/common/az-bicep.md
Line 11: Crear un archivo --> Crea un archivo

2023-10-13 21:41 UTC, kant commented on pages.es/common/az-feedback.md
>  - Envia comentarios al equipo de Azure CLI:
Envia --> Envía

2023-10-13 22:07 UTC, acuteenvy reviewed
There's recently been [a PR](https://github.com/tldr-pages/tldr/pull/10929) removing the "command-line client for Microsoft Azure" part as per the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#descriptions).

2023-10-14 03:37 UTC, kbdharun requested changes
Thanks for your contribution. As @acuteenvy says, we can drop the `the command-line client for Microsoft Azure` part. But the `azure-cli` -> `az` change LGTM as we have the page named `az` too (I will add an alias page named `azure-cli`).

2023-10-14 05:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10963) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=10963) before we can accept your contribution.<br/>**14** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: sebastiaanspeck<br/>:white_check_mark: dadav<br/>:white_check_mark: acuteenvy<br/>:white_check_mark: IMHOJEONG<br/>:white_check_mark: TheBulaDev<br/>:white_check_mark: kbdharun<br/>:white_check_mark: reinhart1010<br/>:white_check_mark: Vishnudas2003<br/>:white_check_mark: aditya955<br/>:white_check_mark: jnmcfly<br/>:white_check_mark: cmhpedro<br/>:white_check_mark: npv12<br/>:white_check_mark: ckorobov<br/>:white_check_mark: dmytrovoytko<br/>:x: Sebastiaan Speck<br/><hr/>**Sebastiaan Speck** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=10963) it.</sub>

2023-10-14 05:14 UTC, kbdharun requested changes
We don't specify the locale in Microsoft links as it will automatically redirect to the reader's preferred locale (it is especially useful for Bilingual speakers).

2023-10-14 11:30 UTC, sebastiaanspeck commented
Want to edit the new az-pages as well.

2023-10-15 06:34 UTC, gutjuri approved these changes

2023-10-15 07:41 UTC, kbdharun approved these changes

2023-10-15 07:42 UTC, merged