git-fresh-branch: add page
tldr-pages/tldr pull request #10972
Opened 2023-10-13 09:25 UTC by Sadeeed

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

#5137

2023-10-13 09:28 UTC, Sadeeed commented
**For the maintainers / reviewers**
Although I am following the command mnemonic structure, I can not find anything about in the style guide and it'd be great if someone could help me understand it fully so I don't miss any thing in the future.

Thanks

2023-10-13 11:31 UTC, reinhart1010 commented
> **For the maintainers / reviewers** Although I am following the command mnemonic structure, I can not find anything about in the style guide and it'd be great if someone could help me understand it fully so I don't miss any thing in the future.
> 
> Thanks

We originally introduce them as a workaround to document commands without [long parameter names](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax), such as the ones in the Command Prompt (Windows).

2023-10-13 11:47 UTC, reinhart1010 requested changes
By the way, here are some reviews from mine.

2023-10-13 11:47 UTC, reinhart1010 commented on pages/common/git-fresh-branch.md
> +- [c]reate an empty local branch:
```suggestion
- Create an empty local branch:
```

By the way, do not use mnemonics if it isn't linked to short command parameters (i.e. `-c`)

2023-10-13 11:47 UTC, reinhart1010 commented on pages/common/git-fresh-branch.md
> +> Creates an empty local branch.
```suggestion
> Create an empty local branch.
```

2023-10-14 04:01 UTC, kbdharun approved these changes
Thanks for your contribution. LGTM after @reinhart1010's suggestions.

2023-10-14 07:51 UTC, reinhart1010 approved these changes
Thanks!

2023-10-14 07:51 UTC, merged