Multi git commands: add pt_BR translation
tldr-pages/tldr pull request #10975
Opened 2023-10-14 01:07 UTC by cmhpedro

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-10-14 19:17 UTC, isaacvicente requested changes
Olá @cmhpedro! Muito obrigado pela sua contribuição! Sua tradução é muito importante :)
Fiz a review aqui e modifiquei algumas coisas, mas não todas que queria.
Poderia por favor aplicar minhas sugestões? Além disso, poderia por favor mudar "ramificação"/"ramificações" para "branch"/"branches"? Acho que, no contexto de Git, o termo 'branch' é familiar o suficiente para não ser traduzido.
Abs.

2023-10-14 19:22 UTC, isaacvicente commented
Hi @kbdharun! Is there a better way to review multiple files rather than manually making the suggestions? I had to manually replace "ramificação" to "branch" multiple times in this PR. If somehow I could do a file and replace in Vim would be amazing xD.

2023-10-15 08:09 UTC, kbdharun commented
> Hi @kbdharun! Is there a better way to review multiple files rather than manually making the suggestions? I had to manually replace "ramificação" to "branch" multiple times in this PR. If somehow I could do a file and replace in Vim would be amazing xD.

Unfortunately, there isn't a seamless way to review the same thing in multiple files in CLI. VSCode with the [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extension would work fine for doing the same graphically.

2023-10-15 12:33 UTC, cmhpedro commented
> Olá @cmhpedro! Muito obrigado pela sua contribuição! Sua tradução é muito importante :) Fiz a review aqui e modifiquei algumas coisas, mas não todas que queria. Poderia por favor aplicar minhas sugestões? Além disso, poderia por favor mudar "ramificação"/"ramificações" para "branch"/"branches"? Acho que, no contexto de Git, o termo 'branch' é familiar o suficiente para não ser traduzido. Abs.

Fiquei com essa dúvida durante a tradução, mas já alterei isso e corrigi alguns outros pequenos erros.

2023-10-15 12:41 UTC, isaacvicente approved these changes
Muito obrigado por aplicar as sugestões @cmhpedro!
Sua PR está pronta pra merge :tada:
Acredito que precisamos da review de outro contribuidor, (pela quantidade de arquivos modificados, acredito eu) porém em pouco tempo iremos dar merge em sua contribuição. Espero que traduza mais páginas! :)

2023-10-15 12:41 UTC, isaacvicente commented on pages.pt_BR/common/git-log.md
> +> Mostra um histórico dos commits.
```suggestion
> Mostra um histórico de commits.
```

2023-10-15 16:48 UTC, isaacvicente commented
this one can be merged as well @kbdharun :)
(sorry for pinging you, I just want to clean up the pull requests list)

2023-10-15 16:53 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-15 16:53 UTC, merged