pages.pt_BR: update multi common pages outdated translation
tldr-pages/tldr pull request #10982
Opened 2023-10-14 14:34 UTC by cmhpedro

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-10-14 19:31 UTC, isaacvicente requested changes
Boa @cmhpedro!! Valeu pelas atualizações dessas páginas!
Apenas modifiquei alguns verbos do começo das descrições para que ficassem coerentes.

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/bash.md
> +- Executar um script específico e para no primeiro [e]rro:
```suggestion
- Executa um script específico e para no primeiro [e]rro:
```

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/bash.md
> +- Executar um script específico exibindo cada comando antes de executá-lo:
```suggestion
- Executa um script específico exibindo cada comando antes de executá-lo:
```

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/gzip.md
> +- Descompactar um arquivo, substituindo-o pela versão não compactada original:
```suggestion
- Descompacta um arquivo, substituindo-o pela versão não compactada original:
```

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/uname.md
> +- Exibir informações sobre a arquitetura e o processador:
```suggestion
- Exibe informações sobre a arquitetura e o processador:
```

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/uname.md
> +- Exibir nome do kernel, lançamento do kernel e versão do kernel:
```suggestion
- Exibe nome do kernel, lançamento do kernel e versão do kernel:
```

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/uname.md
>  - Exibir o nome de rede do computador:
```suggestion
- Exibe o nome de rede do computador:
```

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/uname.md
> +- Exibir todas as informações disponíveis sobre o sistema:
```suggestion
- Exibe todas as informações disponíveis sobre o sistema:
```

2023-10-14 19:31 UTC, isaacvicente commented on pages.pt_BR/common/touch.md
> +- Crua arquivos especificados:
```suggestion
- Cria arquivos especificados:
```

2023-10-14 19:39 UTC, isaacvicente approved these changes
Como as sugestões que fiz não precisavam de sua observação, decide commitar logo.
Mas o que fiz foi mudar o tempo verbal de alguns verbos. Em vez do infinitivo "modificar", seria melhor "modifica", por exemplo. Isso porque, em cada descrição, acho importante que o comentário explique o que o comando faz.

De novo, muito obrigado :100:

2023-10-14 19:41 UTC, isaacvicente approved these changes
LGTM! :tada:

2023-10-14 19:48 UTC, isaacvicente commented
@kbdharun Can you please review the name of the PR? In this case I don't know which name would be appropriated following our guidelines.

2023-10-15 08:04 UTC, kbdharun commented
> @kbdharun Can you please review the name of the PR? In this case I don't know which name would be appropriated following our guidelines.

The name looks fine @isaacvicente, since this PR adds multiple pages it would be difficult to fit all the commands to the PR title as it would get truncated on the commit message.

2023-10-15 08:04 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-15 08:05 UTC, merged