add `packer fmt`
tldr-pages/tldr pull request #11047
Opened 2023-10-18 01:39 UTC by sharunkumar

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-18 01:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11047) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11047) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11047) it.</sub>

2023-10-18 01:53 UTC, arunsathiya approved these changes

2023-10-18 12:54 UTC, gutjuri requested changes
Thanks, I left a suggestion.

2023-10-18 12:54 UTC, gutjuri commented on pages/common/packer.md
> +`packer fmt {{path/to/config.json}}`
```suggestion
`packer fmt {{path/to/config.pkr.hcl}}`
```

The docs say that this command has no effect if a json file is passed. Thats why I suggest changing the file extension in the example. See: https://developer.hashicorp.com/packer/docs/commands/fmt

2023-10-20 01:02 UTC, sharunkumar commented
> Looking at https://github.com/hashicorp/packer/tree/main/website/content/docs/commands it looks like there are more subcommands. Maybe we should split it into own pages, e.g. `packer-fmt` etc?

correct, but according to the community guidelines, the main page should have the mostly used commands (up to 8) on the main page, and I guess in say, `packer-fmt` we should have all the formatting related options

2023-10-20 05:46 UTC, gutjuri approved these changes

2023-10-20 05:46 UTC, merged