abbr: add Polish translation
tldr-pages/tldr pull request #11059
Opened 2023-10-18 08:57 UTC by rozie

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-10-18 08:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11059) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11059) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11059) it.</sub>

2023-10-19 08:01 UTC, sebastiaanspeck approved these changes
LGTM!

2023-10-19 10:04 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

**Note to new maintainers**: Don't merge this PR until it is reviewed by the Code owner (native speaker).

2023-10-19 11:53 UTC, acuteenvy requested changes
Thanks for your contribution. Please use the imperative for descriptions, as per [the style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#imperative-mood).

2023-10-19 11:53 UTC, acuteenvy commented on pages.pl/linux/abbr.md
> +`ssh {{nazwa_hosta}} abbr --show | source`
```suggestion
> Zarządzaj skrótami dla powłoki fish.
> Zdefiniowane przez użytkownika słowa są zastępowane po wpisaniu dłuższymi zwrotami.
> Więcej informacji: <https://fishshell.com/docs/current/cmds/abbr.html>.

- Dodaj nowy skrót:

`abbr --add {{nazwa_skrótu}} {{polecenie}} {{argumenty_polecenia}}`

- Zmień nazwę istniejącego skrótu:

`abbr --rename {{stara_nazwa}} {{nowa_nazwa}}`

- Usuń istniejący skrót:

`abbr --erase {{nazwa_skrótu}}`

- Zaimportuj skróty zdefiniowane na innym hoście poprzez SSH:

`ssh {{nazwa_hosta}} abbr --show | source`
```

2023-10-19 16:15 UTC, acuteenvy approved these changes

2023-10-19 16:16 UTC, merged