asciitopgm: page addition
tldr-pages/tldr pull request #11050
Opened 2023-10-18 06:55 UTC by Gauravpadam

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Umbrella issue #10887

This PR adds asciitopgm page documentation

2023-10-18 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11050) it.</sub>

2023-10-18 12:49 UTC, gutjuri requested changes
Thank you. I added some suggestions.

2023-10-18 12:49 UTC, gutjuri commented on pages/common/asciitopgm.md
> +> Convert ASCII graphics into a PGM.
```suggestion
> Convert ASCII graphics into a PGM file.
```

2023-10-18 12:49 UTC, gutjuri commented on pages/common/asciitopgm.md
> +`asciitopgm inputfile > output.pgm`
```suggestion
`asciitopgm {{path/to/file}} > output.pgm`
```

2023-10-18 12:53 UTC, Gauravpadam commented on pages/common/asciitopgm.md
> +> Convert ASCII graphics into a PGM.
Sure, I'll do that

2023-10-18 12:59 UTC, Gauravpadam commented
@gutjuri I've implemented the suggestions, Would you please take a look?

2023-10-18 13:03 UTC, gutjuri approved these changes
Thanks!

2023-10-19 09:48 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-10-19 09:48 UTC, merged