ddgr: add page
tldr-pages/tldr pull request #11060
Opened 2023-10-18 09:25 UTC by aditya-shrivastavv

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-10-18 12:46 UTC, gutjuri requested changes
Thank you very much! I have some suggestions below.

2023-10-18 12:46 UTC, gutjuri commented on pages/common/ddgr.md
> +- To initiate an interactive mode:
```suggestion
- Start interactive mode:
```

2023-10-18 12:46 UTC, gutjuri commented on pages/common/ddgr.md
> +- To limit the search results number:
```suggestion
- Limit the search results number to N:
```

2023-10-18 12:46 UTC, gutjuri commented on pages/common/ddgr.md
> +- To show complete URL in search results:
```suggestion
- Show the complete URL in search results:
```

2023-10-18 12:46 UTC, gutjuri commented on pages/common/ddgr.md
> +- Search DuckDuckGo for a keyword and open the first result in a browser:
```suggestion
- Search DuckDuckGo for a keyword and open the first result in the browser:
```

2023-10-18 14:07 UTC, aditya-shrivastavv commented
Requested changes applied 👍. I will be more language conscious next time. Thank you

2023-10-18 21:34 UTC, gutjuri approved these changes
Thanks!

2023-10-19 08:00 UTC, sebastiaanspeck approved these changes
LGTM!

2023-10-19 08:00 UTC, merged