pnmtopng: add page
tldr-pages/tldr pull request #11072
Opened 2023-10-18 16:57 UTC by prerna120

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-10-18 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11072) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11072) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11072) it.</sub>

2023-10-19 07:14 UTC, gutjuri requested changes
Thank you, I added a suggestion.

2023-10-19 07:14 UTC, gutjuri commented on pages/common/pnmtopng.md
> +`pnmtopng  > {{path/to/file.pnm}}`
```suggestion
`pnmtopng {{path/to/file.pnm}} > {{path/to/file.png}}`
```

This is the correct way to call the program.

2023-10-19 11:09 UTC, kbdharun approved these changes
Thanks for your contribution.

LGTM after @gutjuri's suggestion.

2023-10-19 11:18 UTC, merged