cut: add pt_BR translation
tldr-pages/tldr pull request #11106
Opened 2023-10-19 21:31 UTC by FvFurquim

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-10-20 22:36 UTC, isaacvicente requested changes
Olá @FvFurquim! Pelo que percebi de sua tradução, você traduziu as opções.
As opções de um comando nunca são traduzidas, pois são iguais para qualquer idioma.
Por exemplo: "ls --help". O "--help" não pode ser traduzido, pois não existe a opção "--ajuda" no comando `ls`.

Se atente ao [guia de contribuição](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md) para mais dicas. É sempre importante seguí-lo, pois facilita nossa e sua vida :)

Muito obrigado pela sua contribuição! :heart:
Só preciso que aplique minhas sugestões.

2023-10-20 22:36 UTC, isaacvicente commented on pages.pt_BR/common/cut.md
> +`{{comando}} | cut --{{caracteres|campos}}={{1|1,10|1-10|1-|-10}}`
### 
```suggestion
`{{comando}} | cut --{{characters|fields}}={{1|1,10|1-10|1-|-10}}`
```

2023-10-20 22:36 UTC, isaacvicente commented on pages.pt_BR/common/cut.md
> +`{{comando}} | cut --delimiter="{{,}}" --{{campos}}={{1}}`
```suggestion
`{{comando}} | cut --delimiter="{{,}}" --{{fields}}={{1}}`
```

2023-10-20 22:36 UTC, isaacvicente commented on pages.pt_BR/common/cut.md
> +`cut --{{caracteres}}={{1}} {{caminho/para/arquivo}}`
```suggestion
`cut --{{characters}}={{1}} {{caminho/para/arquivo}}`
```

2023-10-21 20:52 UTC, FvFurquim commented on pages.pt_BR/common/cut.md
> +`{{comando}} | cut --{{caracteres|campos}}={{1|1,10|1-10|1-|-10}}`
Olá, faz sentido, eu pesquisei sobre isso antes de traduzir para entender se era uma flag ou não, mas acabei confundindo as coisas na hora de traduzir. Obrigado pelo aviso, vou tomar mais cuidado nas próximas traduções :)

2023-10-21 21:40 UTC, isaacvicente approved these changes
Tudo certo!
Valeu :)

2023-10-21 21:41 UTC, merged