pw-record: Update, remove depricated example (propose PR)
tldr-pages/tldr pull request #11174
Opened 2023-10-22 19:26 UTC by CheesyChocolate

Option `--list-targets` is no longer available in the recent versions of `pw-record`
[arch wiki page](https://wiki.archlinux.org/title/PipeWire#Microphone_is_not_detected_by_PipeWire)
[a related issue in pipewire git repo](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2564)

- [x] The page(s) are in the correct platform directories: common, linux, osx, windows, sunos, android, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

- **Version of the command being documented (if known):**
pipewire-audio 1:0.3.83-1
Compiled with libpipewire 0.3.83

can we do these in this pr?
- [ ]  remove deprecated option from `pw-cat` tldr page
- [ ] add more example if 3 example would be short!? (after removing deprecated example, only 3 remains) 
- [ ] Check and update TLDR pages in other languages

2023-10-22 19:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11174) it.</sub>

2023-10-22 19:41 UTC, CheesyChocolate commented
should we add more example if 3 example is not enough? (after removing deprecated example, only 3 remains)

2023-10-22 20:07 UTC, Managor commented
If you can think of valid use cases. There's no need to forcibly list more commands than are needed.

2023-10-22 20:21 UTC, Managor requested changes
Lets fix some of my own mistakes from when I wrote this page to conform with the style guide.

2023-10-22 20:21 UTC, Managor commented on pages/linux/pw-cat.md
>  > More information: <https://fedoraproject.org/wiki/QA:Testcase_PipeWire_PipeWire_CLI>.
```suggestion
> Play and record audio files through pipewire.
> More information: <https://fedoraproject.org/wiki/QA:Testcase_PipeWire_PipeWire_CLI>.
```

2023-10-22 20:21 UTC, Managor commented on pages/linux/pw-record.md
>  > More information: <https://fedoraproject.org/wiki/QA:Testcase_PipeWire_PipeWire_CLI>.
```suggestion
> Record audio files through pipewire
> Shorthand for pw-cat --record.
> More information: <https://fedoraproject.org/wiki/QA:Testcase_PipeWire_PipeWire_CLI>.
```

2023-10-22 23:07 UTC, CheesyChocolate commented
I will update turkish tldr pages as soon as I get a reply from a turkish friend. (his name is not google translator!!!)

2023-10-23 20:53 UTC, Managor approved these changes

2023-10-23 20:55 UTC, merged