grub-editenv: add page
tldr-pages/tldr pull request #11218
Opened 2023-10-24 17:58 UTC by SAYUK09

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-10-24 17:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11218) it.</sub>

2023-10-24 18:56 UTC, Magrid0 requested changes
Hi, thanks for contributing to this project, but unfortunately we can't accept this pull request, we advise to take a look to the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md) and update the file.

2023-10-25 12:17 UTC, SAYUK09 commented
> Hi, thanks for contributing to this project, but unfortunately we can't accept this pull request, we advise to take a look to the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md) and update the file.

I have made the changes. Please take a look now.
Thanks @Magrid0

2023-10-25 12:33 UTC, Magrid0 requested changes
it's still not correct

2023-10-25 12:33 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +## See Also
```suggestion

```

2023-10-25 12:33 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +- More information: [GRUB Documentation](https://www.gnu.org/software/grub/manual/grub/grub.html).
```suggestion
```

2023-10-25 12:33 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +> Edit GRUB environment variables on Linux.
```suggestion
> Edit GRUB environment variables on Linux.
> More information: <https://www.gnu.org/software/grub/manual/grub/grub.html>.

```

2023-10-25 12:44 UTC, Magrid0 requested changes
with this last change it should pass the check

2023-10-25 12:44 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +
```suggestion
```

2023-10-25 12:44 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +  `grub-editenv /boot/grub/grubenv set default=Ubuntu`
```suggestion
`grub-editenv /boot/grub/grubenv set default=Ubuntu`
```

2023-10-25 12:44 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +  `grub-editenv /boot/grub/grubenv list timeout`
```suggestion
`grub-editenv /boot/grub/grubenv list timeout`
```

2023-10-25 12:44 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +  `grub-editenv /boot/grub/grubenv unset saved_entry`
```suggestion
`grub-editenv /boot/grub/grubenv unset saved_entry`
```

2023-10-25 12:44 UTC, Magrid0 commented on pages/linux/grub-editenv.md
> +  `grub-editenv /boot/grub/grubenv list kernel_cmdline`
```suggestion
`grub-editenv /boot/grub/grubenv list kernel_cmdline`
```

2023-10-25 13:39 UTC, SAYUK09 commented
Thanks for helping our @kbdharun

2023-10-25 13:41 UTC, kbdharun approved these changes
LGTM, Welcome to tldr and thanks for your contribution.

2023-10-25 13:48 UTC, Magrid0 approved these changes
Looks good to me, thanks for your contribution!

2023-10-25 13:58 UTC, merged