Document dlang tools for linux
tldr-pages/tldr pull request #11321
Opened 2023-10-28 11:28 UTC by Magrid0

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

# Changes

- dmd: Add page
- ldc: Add page
- gdc: Add page
- dub: Add page

2023-10-28 15:03 UTC, pixelcmtd reviewed
You seem to have accidentally deleted the Style Guide. Could you please `git revert` that?

About `dmd`: As it is a compiler, I think the first example, or at least an example, should be straight compiling code, like in the `gcc` page or the `gdc` page you're also suggesting.

2023-10-28 15:03 UTC, pixelcmtd commented on pages/linux/gdc.md
> +`gdc {{Source_Name}}.d -o {{Output_File_Name}}`
Please use the path syntax [suggested in our style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths)

```suggestion
`gdc {{path/to/source.d}} -o {{path/to/output_executable}}`
```

2023-10-28 15:54 UTC, Magrid0 commented
> You seem to have accidentally deleted the Style Guide. Could you please `git revert` that?

How do I revert it from github? also it was not the original, i must've commited it accidentally while working on it

2023-10-28 16:17 UTC, kbdharun commented
> > You seem to have accidentally deleted the Style Guide. Could you please `git revert` that?
> 
> How do I revert it from github? also it was not the original, i must've commited it accidentally while working on it

You can perform an interactive rebase. i.e `git rebase -i HEAD~15` then you drop the unnecessary commits by changing the status from `pick` to `drop` or `d` for those ones.

I will do it for you right now.

2023-10-28 21:58 UTC, gutjuri requested changes
Thank you, I have some suggestions, mainly concerning parameter format and wording.

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dmd.md
> +`dmd -boundscheck=[on|safeonly|off]`
```suggestion
`dmd -boundscheck={{on|safeonly|off}}`
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dmd.md
> +`dmd -check=[h|help|?]`
```suggestion
`dmd -check={{h|help|?}}`
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dub.md
> +- Build and run D project:
```suggestion
- Build and run a D project:
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dub.md
> +- Update the dependencies in D project:
```suggestion
- Update the dependencies in a D project:
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dub.md
> +- Install dependencies specified in D project's `dub.json|dub.sdl` file:
```suggestion
- Install dependencies specified in a D project's `dub.json` or `dub.sdl` file:
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dub.md
> +- Create a new Dlang project [iterative mode]:
```suggestion
- Interactively create a new D project:
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dub.md
> +`dub init {{Project_Name}}`
```suggestion
`dub init {{project_name}}`
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/dub.md
> +`dub init {{Project_Name}} -n`
```suggestion
- Non-interactively create a new D project:

`dub init {{project_name}} -n`
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/gdc.md
> +> GNU front-end D Compiler.
```suggestion
> D compiler using gcc as a backend.
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/ldc.md
> +> LLVM front-end D compiler.
```suggestion
> D compiler using LLVM as a backend.
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/ldc.md
> +`ldc2 {{Source_file}}.d -of={{Output_Executable}}`
```suggestion
`ldc2 {{path/to/source.d}} -of={{path/to/output_executable}}`
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/ldc.md
> +`ldc2 -c {{Source_file}}.d`
```suggestion
`ldc2 -c {{path/to/source.d}}`
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/ldc.md
> +`ldc -mtriple={{Architecture-OS}} -c {{Source_file}}.d`
```suggestion
`ldc -mtriple={{architecture_OS}} -c {{path/to/source.d}}`
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/ldc.md
> +- Get basic help instruction:
```suggestion
- Display help:
```

2023-10-28 21:58 UTC, gutjuri commented on pages/common/ldc.md
> +- Get complete help instruction:
```suggestion
- Display complete help:
```

2023-10-29 07:58 UTC, gutjuri reviewed
There are still changes that I have requested. Just noting in case you have overlooked them

2023-10-29 08:08 UTC, kbdharun commented
Note: Don't merge this PR yet, I have some changes to do to the pages.

2023-10-29 12:39 UTC, gutjuri commented
closes #11314

2023-10-29 17:44 UTC, kbdharun approved these changes

2023-10-29 17:45 UTC, kbdharun commented
For the DMD link, we can use the generic URL. As the website redirects you to the correct documentation for your host platform.

2023-10-29 19:19 UTC, gutjuri approved these changes

2023-10-29 19:19 UTC, merged