pages.nl/*: add Dutch translations
tldr-pages/tldr pull request #11526
Opened 2023-11-16 18:54 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-11-16 20:14 UTC, Magrid0 approved these changes
Looks good to me

2023-11-17 07:34 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-11-17 10:24 UTC, leonvsc requested changes
Thanks for your contribution. I have a few suggestions. Mostly some spelling mistakes or some forgotten translations.

2023-11-17 10:24 UTC, leonvsc commented on pages.nl/windows/choco-install.md
> +`choco install {{pad\naar\pakketten_bastand.config}}`
```suggestion
`choco install {{pad\naar\pakketten_bestand.config}}`
```

2023-11-17 10:24 UTC, leonvsc commented on pages.nl/windows/choco-push.md
> +- Push een gecompileerd `nupkg` naar de gespecificeerde feed met een timeout in seconden (default is 2700):
```suggestion
- Push een gecompileerd `nupkg` naar de gespecificeerde feed met een timeout in seconden (standaard is 2700):
```

2023-11-17 10:24 UTC, leonvsc commented on pages.nl/windows/choco-uninstall.md
> +`choco uninstall {{pakket}} --version {{version}}`
```suggestion
`choco uninstall {{pakket}} --version {{versie}}`
```

2023-11-17 10:24 UTC, leonvsc commented on pages.nl/windows/choco.md
> +`choco {{command}}`
```suggestion
`choco {{commando}}`
```

2023-11-17 10:24 UTC, leonvsc commented on pages.nl/windows/choco.md
> +`choco {{command}} -?`
```suggestion
`choco {{commando}} -?`
```

2023-11-17 10:24 UTC, leonvsc commented on pages.nl/windows/select-string.md
> +> Je kan `Select-String` gebruiken zoaks `grep` in UNIX of `findstr.exe` in Windows.
```suggestion
> Je kan `Select-String` gebruiken zoals `grep` in UNIX of `findstr.exe` in Windows.
```

2023-11-17 10:24 UTC, leonvsc commented on pages.nl/windows/where-object.md
> +`Get-Alias | Where-Object -{{Property}} {{Name}} -{{eq}} {{name}}`
```suggestion
`Get-Alias | Where-Object -{{Propertie}} {{Naam}} -{{eq}} {{naam}}`
```

2023-11-17 10:39 UTC, leonvsc approved these changes

2023-11-17 10:39 UTC, merged