swaybg: add page
tldr-pages/tldr pull request #11533
Opened 2023-11-17 14:23 UTC by ivandimitrov8080

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

 swaybg version 1.2.0

2023-11-17 14:45 UTC, leonvsc approved these changes
LGTM! Thanks for your contribution.

2023-11-17 14:54 UTC, gutjuri requested changes
Thanks for you contribution! I have some suggestions.

2023-11-17 14:54 UTC, gutjuri commented on pages/linux/swaybg.md
> +`swaybg -i "{{path/to/image}}"`
```suggestion
`swaybg -i {{path/to/image}}`
```

In the past, we've omitted the quotation marks

2023-11-17 14:54 UTC, gutjuri commented on pages/linux/swaybg.md
> +`swaybg -i "{{path/to/image}}" -m {{stretch | fit | fill | center | tile | solid_color}}`
```suggestion
`swaybg -i {{path/to/image}} -m {{stretch|fit|fill|center|tile|solid_color}}`
```

In the other pages, we do not have spaces in such enumerations

2023-11-17 17:33 UTC, kbdharun reviewed
Thanks for your contribution. I have a suggestion for this page. We prefer long options throughout the pages (in most cases) and we highlight short options using mnemonics whenever applicable.

2023-11-17 17:33 UTC, kbdharun commented on pages/linux/swaybg.md
> +`swaybg -c {{"#rrggbb"}}`
```suggestion
- Set an [i]mage as wallpaper:

`swaybg --image {{path/to/image}}`

- Set the wallpaper [m]ode:

`swaybg --image {{path/to/image}} --mode {{stretch|fit|fill|center|tile|solid_color}}`

- Set a static [c]olor as a wallpaper:

`swaybg --color {{"#rrggbb"}}`
```

2023-11-17 18:22 UTC, acuteenvy approved these changes

2023-11-17 18:22 UTC, acuteenvy commented on pages/linux/swaybg.md
> +> More information: <https://github.com/swaywm/swaybg>.
The README doesn't contain a lot of info, I think the man page is better. It's even referenced in the README:
> See the man page, swaybg(1), for instructions on using swaybg.

```suggestion
> More information: <https://github.com/swaywm/swaybg/blob/master/swaybg.1.scd>.
```

2023-11-17 18:22 UTC, acuteenvy commented on pages/linux/swaybg.md
> +`swaybg --color {{"#rrggbb"}}`
```suggestion
- Set the wallpaper to an [i]mage:

`swaybg --image {{path/to/image}}`

- Set the wallpaper [m]ode:

`swaybg --image {{path/to/image}} --mode {{stretch|fit|fill|center|tile|solid_color}}`

- Set the wallpaper to a static [c]olor:

`swaybg --color {{"#rrggbb"}}`
```

2023-11-18 10:46 UTC, gutjuri approved these changes

2023-11-18 10:46 UTC, merged