nm, rm, xz: add Dutch translation
tldr-pages/tldr pull request #11546
Opened 2023-11-19 20:27 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-11-20 03:44 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-11-20 16:22 UTC, Waples commented
As a dutchy, I don't share your LGTM @kbdharun. There are typo's and some of the descriptions are not really typical Dutch, or to much Lazy dutch. @sebastiaanspeck can you update this?

2023-11-21 19:12 UTC, leonvsc requested changes
See my suggestions and comments.

2023-11-21 19:12 UTC, leonvsc commented on pages.nl/common/nm.md
> +- Toon alle symbolen, ook debugging symbolen:
I am not sure if this is a nice sentence to read.

2023-11-21 19:12 UTC, leonvsc commented on pages.nl/common/nm.md
> +- Ontwar C++ symbolen (maak ze leesbaar):
Same for this, what do you mean with `ontwar`?

2023-11-21 19:12 UTC, leonvsc commented on pages.nl/common/rm.md
> +- Verwijder specifieke bestanden, maar negeer niet-bestaanden:
I am not sure what the English sentence was but what do you mean with `maar negeer niet-bestaanden:`

2023-11-21 19:12 UTC, leonvsc commented on pages.nl/common/xz.md
> +- Comprimeer een bestand gebruik makend van xz file xz:
```suggestion
- Comprimeer een bestand gebruik makend van xz file:
```

I think you mean this?

2023-11-21 19:12 UTC, leonvsc commented on pages.nl/common/xz.md
> +- Comprimeer een bestand gebruik makend van de snelste compressie:
```suggestion
- Comprimeer een bestand, gebruik makend van de snelste compressie:
```

2023-11-21 19:12 UTC, leonvsc commented on pages.nl/common/xz.md
> +- Comprimeer een bestand gebruik makend van de bestee compressie:
```suggestion
- Comprimeer een bestand, gebruik makend van de beste compressie:
```

2023-11-23 13:36 UTC, leonvsc commented on pages.nl/common/nm.md
> +- Toon alle symbolen, ook debugging symbolen:
I just read the documentation and I accept this sentence.

2023-11-23 13:38 UTC, leonvsc commented on pages.nl/common/nm.md
> +- Ontwar C++ symbolen (maak ze leesbaar):
I think this is better:

```suggestion
- Transformeer C++ symbolen (maak ze leesbaar):
```

2023-11-23 13:39 UTC, leonvsc approved these changes
1 suggestion left.

2023-11-23 13:58 UTC, merged