vboxmanage-*: add page
tldr-pages/tldr pull request #11598
Opened 2023-11-27 19:59 UTC by HOIg3r

- [x] The page(s) are in the correct platform directories: `common`.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-11-28 09:37 UTC, gutjuri requested changes
Thank you! I have added some suggestions to fix some typos.

2023-11-28 09:37 UTC, gutjuri commented on pages/common/vboxmanage-export.md
> +`VBoxManage clonevm {{vm_name}} --name {{exemple_name}}`
```suggestion
`VBoxManage clonevm {{vm_name}} --name {{example_name}}`
```

2023-11-28 09:37 UTC, gutjuri commented on pages/common/vboxmanage-export.md
> +- Indicate the folder where the configuration of the new VM is gonna be stored:
```suggestion
- Indicate the folder where the configuration of the new VM will be stored:
```

2023-11-28 09:37 UTC, gutjuri commented on pages/common/vboxmanage-import.md
> +- Import a VM from a OVF or OVA file:
```suggestion
- Import a VM from an OVF or OVA file:
```

2023-11-29 18:34 UTC, HOIg3r commented on pages/common/vboxmanage-clonevm.md
> +`VBoxManage clonevm {{vm_name}} --name {{exemple_name}}`
I've tested and read up on the subject and the 2 are equivalent - you can use quotes or not.

2023-11-29 21:46 UTC, gutjuri approved these changes
Thanks!

2023-11-29 21:46 UTC, merged