mount.ddi: add page
tldr-pages/tldr pull request #11622
Opened 2023-12-01 04:29 UTC by quantumflo

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-12-01 20:47 UTC, acuteenvy requested changes
This is not an alias.

> **INVOCATION AS /SBIN/MOUNT.DDI**
> The systemd-dissect executable may be symlinked to /sbin/mount.ddi. If invoked through that it implements
> mount(8)'s "external helper" interface for the (pseudo) file system type "ddi". This means
> conformant disk images may be mounted directly via
>```
> # mount -t ddi myimage.raw targetdir/
>```
> in a fashion mostly equivalent to:
>```
> # systemd-dissect --mount myimage.raw targetdir/
>```

`mount.ddi --mount myimage.raw targetdir/` doesn't work. The equivalent is `mount.ddi myimage.raw targetdir/`.

2023-12-10 13:34 UTC, acuteenvy commented on pages/linux/mount.ddi.md
> +`tldr systemd-dissect`
```suggestion
# mount.ddi

> Mount Discoverable Disk Images.
> See `tldr systemd-dissect` for other commands relevant to DDIs.
> More information: <https://www.freedesktop.org/software/systemd/man/latest/systemd-dissect.html>.

- Mount an OS image:

`mount.ddi {{path/to/image.raw}} {{/mnt/image}}`
```

2023-12-10 13:47 UTC, kbdharun approved these changes
LGTM, after @acuteenvy's suggestion.

2023-12-25 16:50 UTC, acuteenvy approved these changes

2023-12-25 16:52 UTC, merged

2024-03-30 05:57 UTC, quantumflo commented
@kbdharun Please re add me as maintainer. I was removed due to 2 factor authentication

2024-03-30 06:00 UTC, kbdharun commented
> @kbdharun Please re add me as maintainer. I was removed due to 2 factor authentication not being enabled

Done, I have sent an invitation.