aws-kafka: add page
tldr-pages/tldr pull request #11696
Opened 2023-12-07 13:05 UTC by giladAlboher

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-12-08 09:32 UTC, mfrw reviewed
Thank you @giladAlboher for your contribution. I have a few review comments.
Place holders should be enclsed within `{{ }}` instead of `< >`
https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md

2023-12-08 09:32 UTC, mfrw commented on pages/common/aws-kafka.md
> +`aws kafka create-cluster --cluster-name <cluster-name> --broker-node-group-info instanceType=<instance-type>,clientSubnets=<subnet-ids> --kafka-version <kafka-version> --number-of-broker-nodes <numb
```suggestion
`aws kafka create-cluster --cluster-name {{cluster_name}} --broker-node-group-info instanceType={{instance_type}},clientSubnets={{subnet_ids}} --kafka-version {{kafka_version}} --number-of-broker-nodes {{number_of_broker_nodes}}`
```

2023-12-08 09:32 UTC, mfrw commented on pages/common/aws-kafka.md
> +`aws kafka describe-cluster --cluster-arn <cluster-arn>`
```suggestion
`aws kafka describe-cluster --cluster-arn {{cluster_arn}}`
```

2023-12-08 09:32 UTC, mfrw commented on pages/common/aws-kafka.md
> +`aws kafka create-configuration --name <configuration-name> --server-properties file://<path-to-server-properties-file>`
```suggestion
`aws kafka create-configuration --name {{configuration_name}} --server-properties {{file://{{path_to_server_properties_file}}`
```

2023-12-08 09:32 UTC, mfrw commented on pages/common/aws-kafka.md
> +`aws kafka describe-configuration --arn <configuration-arn>`
```suggestion
`aws kafka describe-configuration --arn {{configuration_arn}}`
```

2023-12-08 09:32 UTC, mfrw commented on pages/common/aws-kafka.md
> +`aws kafka update-cluster-configuration --cluster-arn <cluster-arn> --configuration-info arn=<configuration-arn>,revision=<configuration-revision>`
```suggestion
`aws kafka update-cluster-configuration --cluster-arn {{cluster_arn}} --configuration-info arn={{configuration_arn}},revision={{configuration_revision}}`
```

2023-12-08 09:32 UTC, mfrw commented on pages/common/aws-kafka.md
> +`aws kafka delete-cluster --cluster-arn <cluster-arn>`
```suggestion
`aws kafka delete-cluster --cluster-arn {{cluster_arn}}`
```

2023-12-13 07:06 UTC, kbdharun requested changes
Thanks for your contribution. I have some suggestions for this page.

---

_A minor nitpick from my side, for descriptions I wouldn't suggest capitalizing successive terms unless it's required. i.e. Use `Create a new MSK cluster` instead of `Create a New MSK Cluster`._

2023-12-13 07:06 UTC, kbdharun commented on pages/common/aws-kafka.md
> +`aws kafka describe-configuration --arn {{configuration_arn}}`
```suggestion
- Describe a MSK configuration:

`aws kafka describe-configuration --arn {{configuration_arn}}`
```

2023-12-13 07:06 UTC, kbdharun commented on pages/common/aws-kafka.md
> +- List Configurations:
```suggestion
- List all MSK configurations in the current region:
```

2023-12-13 07:06 UTC, kbdharun commented on pages/common/aws-kafka.md
> +- Update a Kafka Cluster Configuration:
```suggestion
- Update the MSK cluster configuration:
```

2023-12-13 07:06 UTC, kbdharun commented on pages/common/aws-kafka.md
> +- Delete a Kafka Cluster:
```suggestion
- Delete the MSK cluster:
```

2023-12-13 07:06 UTC, kbdharun commented on pages/common/aws-kafka.md
> +# AWS Kafka CLI Commands
```suggestion
# aws kafka
```
The page title must match with the command name.

2023-12-13 12:03 UTC, kbdharun commented on pages/common/aws-kafka.md
> +`aws kafka create-configuration --name {{configuration_name}} --server-properties {{file://{{path_to_server_properties_file}}`
@giladAlboher With this suggestion addressed, I think the PR is GTG.

2023-12-14 05:26 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-12-14 16:04 UTC, merged