!: add zh translation
tldr-pages/tldr pull request #11709
Opened 2023-12-10 05:47 UTC by Ren-Ma

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-12-10 05:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11709) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11709) it.</sub>

2023-12-10 11:03 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution. I have some suggestions for this page.

- Please sign the CLA in the above comment for this PR to go through.
- A command is missing after the last description (I have added it in my suggestion).

---

**Note**: I am not a native speaker and these placeholder suggestions were done based on the existing `zh` pages we have here. For any additional queries, I would suggest asking the native speakers (code owners) instead.

2023-12-10 11:03 UTC, kbdharun commented on pages.zh/common/!.md
> +- 替换最新命令的参数：
```suggestion
- 替换最新命令的参数：

`{{命令}} !*`
```

2023-12-10 14:05 UTC, einverne requested changes
Hi thank you for the translation page, I left a few suggestions for you.

2023-12-10 14:05 UTC, einverne commented on pages.zh/common/!.md
> +- 替换指定数量的行回查的命令：
```suggestion
- 替换指定数量的行回查的命令：
```

What do you mean `指定数量的行回查的命令` here, I check the English description

```
Substitute with a command that was used a specified number of lines back:
```

I think you may be referring to `specified number of lines back`, but I never see any translation like `行回查命令`. The English description is much clearer than it. Shall we use another expression?

2023-12-11 03:19 UTC, kbdharun approved these changes

2023-12-13 06:35 UTC, kbdharun commented
@einverne Any updates on this?

2023-12-13 06:36 UTC, einverne approved these changes
LGTM.

2023-12-13 06:37 UTC, merged