mpv: edit and add example
tldr-pages/tldr pull request #11734
Opened 2023-12-13 20:04 UTC by vitorhcl

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-12-14 05:17 UTC, kbdharun commented on pages.pt_BR/common/mpv.md
> +`ESQUERDA <ou> DIREITA`
@sebastiaanspeck What do you suggest doing in this case?

The command contains a keyboard shortcut which depending on the keyboard layout will differ in other languages, should we go with the English version to fix the errors? (Anything works for me)

2023-12-14 05:21 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

> For the URL, I would suggest going with a generic placeholder to highlight the file option better, even though having a Rickroll is cool 😄 (it makes it long) .

2023-12-14 05:21 UTC, kbdharun commented on pages/common/mpv.md
> +`mpv {{https://www.youtube.com/watch?v=dQw4w9WgXcQ|path/to/file}}'`
```suggestion
`mpv {{url|path/to/file}}'`
```

2023-12-14 05:21 UTC, kbdharun commented on pages.pt_BR/common/mpv.md
> +`mpv {{https://www.youtube.com/watch?v=dQw4w9WgXcQ|caminho/para/arquivo}}'`
```suggestion
`mpv {{url|caminho/para/arquivo}}'`
```

2023-12-14 15:38 UTC, kbdharun approved these changes

2023-12-15 21:51 UTC, isaacvicente requested changes
Olá! Muito obrigado pela sua contribuição! :tada: 

Sugeri algumas mudanças sobre o verbo usado nas descrições. O verbo tem que estar no presente do indicativo, ou seja, o verbo _explica_ ou _descreve_ o que o comando faz.

Espero revisar mais traduções suas! Valeu!

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Tocar um vídeo ou áudio de uma URL ou arquivo:
```suggestion
- Toca um vídeo ou áudio de uma URL ou arquivo:
```

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Avançar/retroceder 5 segundos:
```suggestion
- Avança/retrocede 5 segundos:
```

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Avançar/retroceder 1 minuto:
```suggestion
- Avança/retrocede 1 minuto:
```

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Aumentar ou diminuir a velocidade de reprodução em 10%:
```suggestion
- Aumenta ou diminui a velocidade de reprodução em 10%:
```

2023-12-15 21:51 UTC, isaacvicente commented on pages/common/mpv.md
> +- Take a screenshot of the current frame (saved to `mpv-shotNNNN.jpg` by default):
```suggestion
- Take a screenshot of the current frame (saved to `./mpv-shotNNNN.jpg` by default):
```

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Capturar a imagem atual (salva em `mpv-shotNNNN.jpg` por padrão):
```suggestion
- Captura a imagem atual (salva em `./mpv-shotNNNN.jpg` por padrão):
```

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Tocar um arquivo em uma velocidade especificada (1 por padrão):
```suggestion
- Toca um arquivo em uma velocidade especificada (1 por padrão):
```

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Tocar um arquivo usando um perfil definido no arquivo `mpv.conf`:
```suggestion
- Toca um arquivo usando um perfil definido no arquivo `mpv.conf`:
```

2023-12-15 21:51 UTC, isaacvicente commented on pages.pt_BR/common/mpv.md
> +- Mostrar a saída da webcam ou de outro dispositivo de entrada de vídeo:
```suggestion
- Mostra a saída da webcam ou de outro dispositivo de entrada de vídeo:
```

2023-12-17 04:46 UTC, isaacvicente approved these changes
Tradução pronta pro merge! Obrigado mais uma vez por traduzir :100:

2023-12-17 04:46 UTC, merged