cupsctl: add page
tldr-pages/tldr pull request #11745
Opened 2023-12-15 00:53 UTC by vitorhcl

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Partially fixes #6597

2023-12-15 09:00 UTC, gutjuri reviewed
Thanks, i have some suggestions. If they are addressed, the PR looks fine.

2023-12-15 09:00 UTC, gutjuri commented on pages/common/cupsctl.md
> +`cupsctl --remote-admin|--no-remote-admin`
```suggestion
- Enable or disable debug logging to the error_log file:

`cupsctl {{--debug-logging|--no-debug-loging}}`

- Enable or disable remote administration:

`cupsctl {{--remote-admin|--no-remote-admin}}`
```

To make clear that this is not the shell pipe `|` operator.

2023-12-15 09:00 UTC, gutjuri commented on pages.pt_BR/common/cupsctl.md
> +`cupsctl --remote-admin|--no-remote-admin`
```suggestion
- Ativar ou desativar o registro de depuração para o arquivo error_log:

`cupsctl {{--debug-logging|--no-debug-loging}}`

- Ativar ou desativar a administração remota:

`cupsctl {{--remote-admin|--no-remote-admin}}`
```

2023-12-15 14:39 UTC, gutjuri approved these changes

2023-12-15 18:47 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

**Note**: We don't need to highlight mnemonics in descriptions if the long option/term isn't highlighted in the main documentation. In this case, there aren't any long options so we could leave the descriptions as it is.

2023-12-15 18:47 UTC, kbdharun commented on pages/common/cupsctl.md
> +> Update or query a server's cupsd.conf.
```suggestion
> Update or query a server's `cupsd.conf`.
```
We wrap files inside backticks (as suggested in the style guide).

2023-12-15 18:47 UTC, kbdharun commented on pages/common/cupsctl.md
> +- Display current configuration values:
```suggestion
- Display the current configuration values:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/cupsctl.md
> +- Display current configuration values [E]ncrypting the connection to the scheduler:
```suggestion
- Enable encryption on the connection to the scheduler:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/cupsctl.md
> +- Enable or disable debug logging to the error_log file:
```suggestion
- Enable or disable debug logging to the `error_log` file:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/cupsctl.md
> +`cupsctl {{--debug-logging|--no-debug-loging}}`
```suggestion
`cupsctl {{--debug-logging|--no-debug-logging}}`
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpadmin.md
> +> Configure cups printers and classes.
```suggestion
> Configure CUPS printers and classes.
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpadmin.md
> +- [d]elete a specific printer or class:
```suggestion
- Delete a specific printer or class:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpadmin.md
> +- Add a printer to a [c]lass:
```suggestion
- Add a printer to a class:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpadmin.md
> +- [r]emove a printer from a class:
```suggestion
- Remove a printer from a class:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpoptions.md
> +- Set a new [o]ption on a specific printer:
```suggestion
- List printer-specific options of a specific printer:

`lpoptions -d {{printer}} -l`

- Set a new option on a specific printer:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpoptions.md
> +`lpoptions -d {{printer}} -o {{option[=value]}}`
```suggestion
`lpoptions -d {{printer}} -o {{option}}`
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpq.md
> +- Show the queued jobs of [a]ll printers enforcing [E]ncryption:
```suggestion
- Show the queued jobs of all printers enforcing encryption:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lpq.md
> +- Show the queued jobs in a [l]ong format:
```suggestion
- Show the queued jobs in a long format:
```

2023-12-15 18:47 UTC, kbdharun commented on pages/common/lprm.md
> +- Cancel multiple jobs with a [E]ncrypted connection to the server:
```suggestion
- Cancel multiple jobs with a encrypted connection to the server:
```

2023-12-15 21:05 UTC, isaacvicente requested changes
Olá @vitorhcl! Muito obrigado pela sua contribuição!!

Sua tradução está excelente e os exemplos são bem úteis :)

Porém, modifiquei algumas coisas que acho importante:
- A descrição de cada comando deve explicar **o que** o comando faz. Assim, por exemplo, "***lista*** arquivos e diretórios no diretório atual" é melhor que "***listar*** arquivos e diretórios no diretório atual" (para o comando `ls`). Sendo mais técnico, a descrição deve começar com um verbo no presente do indicativo.
- Removi o mnemônico de listagem longa, pois para o resto dos comandos, você não apresentou nenhum outro mnemônico. Sempre que possível, queremos que a página seja consistente (um exemplo clássico: `tldr tar`).

No mais, muito obrigado pela tradução e espero que revise mais traduções suas. :100: :tada:

2023-12-15 21:13 UTC, isaacvicente commented
@kbdharun Where can I write some general suggestions on pt_BR translations?

I'm asking this because of a pattern that I've noticed: in English, `find` "_find file in current directory_", is both in the infinitive form and present tense. So, it's not a problem to use the verb "find" in the `find` command, right?

In Portuguese, tough, find can mean "encontrar" or "encontra". "encontrar" is in the infinitive form, and "encontra" in the present tense form. The right form to use the verbs in Portuguese here is to use the present tense, because this form explains things, it's like you're describing how something work (that's what we want in the command's descriptions, right)?

That said, I wish to clarify this as a general suggestion for pt and pt_BR translations.

2023-12-15 21:42 UTC, vitorhcl commented
> Olá @vitorhcl! Muito obrigado pela sua contribuição!!
> 
> Sua tradução está excelente e os exemplos são bem úteis :)
> 
> Porém, modifiquei algumas coisas que acho importante:
> 
> * A descrição de cada comando deve explicar **o que** o comando faz. Assim, por exemplo, "_**lista**_ arquivos e diretórios no diretório atual" é melhor que "_**listar**_ arquivos e diretórios no diretório atual" (para o comando `ls`). Sendo mais técnico, a descrição deve começar com um verbo no presente do indicativo.
> * Removi o mnemônico de listagem longa, pois para o resto dos comandos, você não apresentou nenhum outro mnemônico. Sempre que possível, queremos que a página seja consistente (um exemplo clássico: `tldr tar`).
> 
> No mais, muito obrigado pela tradução e espero que revise mais traduções suas. 💯 🎉

Muito obrigado pela revisão!

Quanto à forma dos verbos, eu pessoalmente acho que o presente do indicativo causa uma certa estranheza e usei o infinitivo como se ele descrevesse **para que** o comando serve, mas de fato parece que não essa não é a forma tecnicamente correta. De qualquer maneira, eu notei uma certa inconsistência nas páginas em português (do Brasil, pelo menos) e estou disposto a ajudar a corrigi-las para a forma que você considera melhor.

2023-12-15 21:46 UTC, vitorhcl commented on pages/common/lpq.md
> +- Show the queued jobs in a long format:
Eu já tinha removido o mnemônico depois da revisão do @kbdharun 😅

2023-12-16 06:00 UTC, kbdharun commented
> @kbdharun Where can I write some general suggestions on pt_BR translations?

@isaacvicente As suggested by @sebastiaanspeck, we should document this in the language-specific rules section of the style guide (and maybe update existing pages for this). 

> In Portuguese, though, find can mean "encontrar" or "encontra". "encontrar" is in the infinitive form, and "encontra" in the present tense form. The right form to use the verbs in Portuguese here is to use the present tense, because this form explains things, like you're describing how something works (that's what we want in the command's descriptions, right?)

Yep, we should use the form which fits best (and is easy to understand) for your native language.

2023-12-17 04:41 UTC, isaacvicente commented
> > Olá @vitorhcl! Muito obrigado pela sua contribuição!!
> > Sua tradução está excelente e os exemplos são bem úteis :)
> > Porém, modifiquei algumas coisas que acho importante:
> > 
> > * A descrição de cada comando deve explicar **o que** o comando faz. Assim, por exemplo, "_**lista**_ arquivos e diretórios no diretório atual" é melhor que "_**listar**_ arquivos e diretórios no diretório atual" (para o comando `ls`). Sendo mais técnico, a descrição deve começar com um verbo no presente do indicativo.
> > * Removi o mnemônico de listagem longa, pois para o resto dos comandos, você não apresentou nenhum outro mnemônico. Sempre que possível, queremos que a página seja consistente (um exemplo clássico: `tldr tar`).
> > 
> > No mais, muito obrigado pela tradução e espero que revise mais traduções suas. 💯 🎉
> 
> Muito obrigado pela revisão!
> 
> Quanto à forma dos verbos, eu pessoalmente acho que o presente do indicativo causa uma certa estranheza e usei o infinitivo como se ele descrevesse **para que** o comando serve, mas de fato parece que não essa não é a forma tecnicamente correta. De qualquer maneira, eu notei uma certa inconsistência nas páginas em português (do Brasil, pelo menos) e estou disposto a ajudar a corrigi-las para a forma que você considera melhor.

Seria de enorme ajuda corrigir as formas verbais de outras páginas e ajudar a manter a consistência em futuras paǵinas! Conte comigo para isso :)

2023-12-17 04:42 UTC, isaacvicente approved these changes
LGTM :tada:

2023-12-17 04:42 UTC, merged