Update terminal-notifier: fix typo
tldr-pages/tldr pull request #11766
Opened 2023-12-16 02:10 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-12-16 06:25 UTC, kbdharun requested changes
Thanks for your contribution. Can you please update this page to match with the [English page](https://github.com/tldr-pages/tldr/blob/main/pages/osx/terminal-notifier.md)?

**Remainder**: Can you update your existing PRs which have blocking merge for the same @kant?

---

_I think minor typo fixes are fine but if a translation is outdated (and you are a native speaker) you should update it too parallelly to minimize multiple commits to the main branch as it triggers a new build (I am adding this proposal to the tracker to make its way to `CONTRIBUTING.md`) which uploads artifacts to the website repo increasing the size of it and making it harder to clone to update the website. (Regarding, this I have another proposal to separate assets and website which we discussed in the chatroom a while ago will open a broader discussion for it today.)_

2023-12-17 16:31 UTC, gutjuri approved these changes

2023-12-29 18:12 UTC, kant commented
> @kant still working on this?

Done!

2023-12-30 13:12 UTC, kbdharun approved these changes

2023-12-30 13:12 UTC, merged