scripts/deploy.sh: exit immediately if there aren't any changes
tldr-pages/tldr pull request #11836
Opened 2023-12-25 16:30 UTC by acuteenvy

https://github.com/tldr-pages/tldr/pull/11825#issuecomment-1868687824 didn't work because it did the opposite - exit when there are changes, proceed if there aren't. I forgot to add a `!`.

---

I removed some of the variables used only once, because their contents were shorter than the variable name itself.

By the way, it would be great if we had some written conventions regarding the shell scripts.

- some scripts use `$var`, some `${var}`
- some quote every variable, some don't, etc.

2023-12-25 17:36 UTC, kbdharun commented
> By the way, it would be great if we had some written conventions regarding the shell scripts.

Agreed, we could probably document them here https://github.com/tldr-pages/tldr/tree/main/scripts#readme and update the scripts to have a consistent style.

2023-12-25 18:11 UTC, kbdharun requested changes
Thanks for your contribution, I was testing the changes of this PR (I didn't test with multiple pages previously). I noticed a [regression](https://github.com/kbdkorg/tldr/actions/runs/7323410823/job/19945954955) where the build-pdf and deploy steps are skipped in the CI. Then I tested the same in the script in main (that I merged earlier today) it showed the [same issue](https://github.com/kbdkorg/tldr/actions/runs/7323441032). I have since reverted the commit in `main`, I would suggest testing changes to the script/CI in your fork to catch issues like this.

2023-12-25 18:31 UTC, acuteenvy commented
https://github.com/kbdkorg/tldr/actions/runs/7323410823/workflow
```yaml
    - name: Build PDF
      if: github.repository == 'tldr-pages/tldr' && github.ref == 'refs/heads/main'
      working-directory: ./scripts/pdf
      run: bash build-pdf.sh

    - name: Deploy
      if: github.repository == 'tldr-pages/tldr' && github.ref == 'refs/heads/main'
      run: bash scripts/deploy.sh
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
```

You are checking `if github.repository == 'tldr-pages/tldr` in `kbdkorg/tldr`, so the steps are skipped.

3 commits were merged into `main` while the changes were there and it worked just fine.
- https://github.com/tldr-pages/tldr-pages.github.io/commit/67b4a6d128f579ad4c64a75758efe831bcfefaad
- https://github.com/tldr-pages/tldr-pages.github.io/commit/54ed1e2759ab64fd7d0528b5fe6a2d49f0346e51
- https://github.com/tldr-pages/tldr-pages.github.io/commit/e9deebdb43cce43e3d357b3fd76e794f131262da

2023-12-25 18:37 UTC, kbdharun commented
@acuteenvy Thanks for pointing it out, I am extremely sorry for the mishap forgot to remove the lines (while testing).

2023-12-25 18:47 UTC, acuteenvy commented
No problem. I don't think there's even a way to tell GitHub to skip the next step using shell commands in the previous one.

We could prevent this from happening in the future if we put the deployment steps in a different file without `on: pull_request`.

2023-12-25 18:49 UTC, kbdharun approved these changes
Tested the changes (it works fine). Thanks for the fixes.

2023-12-25 18:51 UTC, kbdharun commented
> I think we could prevent this from happening in the future if we put the deployment steps in a different file without on: pull_request.

Separating the CI for commits to `main` and for PRs?

2023-12-26 03:11 UTC, gutjuri approved these changes

2023-12-26 10:15 UTC, kbdharun commented on scripts/deploy.sh
>    # Decrypt and add deploy key.
Yes, this block is still needed without the SSH key being imported the artifacts can't be committed to the static site. (i.e. `git push` won't work)

2023-12-26 13:02 UTC, merged