sntp: add page
tldr-pages/tldr pull request #11877
Opened 2023-12-28 06:19 UTC by taher-mosbah

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-12-28 06:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11877) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11877) before we can accept your contribution.<br/><hr/>**Mohamed Mosbah** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11877) it.</sub>

2023-12-28 17:08 UTC, kbdharun commented
Welcome to tldr and thanks for your contribution @taher-mosbah. Please sign the CLA in the above comment for this PR to go through.

2023-12-28 18:35 UTC, gutjuri requested changes
Thanks, I have added some suggestions.

2023-12-28 18:35 UTC, gutjuri commented on pages/osx/sntp.md
> +- Query SNTP server {{pool.ntp.org}} and display the time:
```suggestion
- Query the SNTP server `pool.ntp.org` and display the time:
```

2023-12-28 18:35 UTC, gutjuri commented on pages/osx/sntp.md
> +- Synchrize the system clock with {{pool.ntp.org}} SNTP server:
```suggestion
- Synchronize the system clock with the SNTP server at `pool.ntp.org`:
```

2023-12-28 18:35 UTC, gutjuri commented on pages/osx/sntp.md
> +- Enabe debug logging:
```suggestion
- Enable debug logging:
```

2023-12-30 10:04 UTC, taher-mosbah commented
Thanks for reviewing and sorry about the forced push, I signed CLA and implemented suggestions.

2023-12-30 14:16 UTC, gutjuri commented
LGTM, thanks

2023-12-30 14:16 UTC, gutjuri approved these changes

2023-12-30 14:30 UTC, vitorhcl requested changes
LGTM! Consider adding the "More information" link as I suggested.

2023-12-30 14:30 UTC, vitorhcl commented on pages/osx/sntp.md
> +> A very Simple Network Time Protocol client program.
```suggestion
> A very Simple Network Time Protocol client program.
> More information: <https://keith.github.io/xcode-man-pages/sntp.1>.
```

2023-12-30 15:15 UTC, kbdharun approved these changes
Thanks for your contribution and welcome to tldr.

LGTM, after @vitorhcl's suggestion.

2024-01-03 13:33 UTC, vitorhcl approved these changes

2024-01-03 13:43 UTC, kbdharun approved these changes

2024-01-03 13:44 UTC, merged