lsappinfo: add command
tldr-pages/tldr pull request #11878
Opened 2023-12-28 06:30 UTC by taher-mosbah

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-12-28 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11878) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=11878) before we can accept your contribution.<br/><hr/>**Mohamed Mosbah** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=11878) it.</sub>

2023-12-28 16:26 UTC, vitorhcl requested changes
Thanks for your contribution! I have some suggestions

2023-12-30 10:02 UTC, taher-mosbah commented
Thanks for reviewing and sorry about the forced push, I signed CLA and implemented suggestions.

2023-12-30 14:22 UTC, gutjuri approved these changes
Thanks!

2023-12-30 14:26 UTC, vitorhcl requested changes
LGTM, after you consider my suggestions:
- It's always good to have a "More information" link when possible
- I made it clear that the `lsappinfo list` command also shows the details of the apps.

Welcome to tldr and thanks for your contribution!

2023-12-30 14:26 UTC, vitorhcl commented on pages/osx/lsappinfo.md
> +> Control and query CoreApplicationServices about the app state on the system.
```suggestion
> Control and query CoreApplicationServices about the app state on the system.
> More information: <https://keith.github.io/xcode-man-pages/lsappinfo.8.html>.
```

2023-12-30 14:26 UTC, vitorhcl commented on pages/osx/lsappinfo.md
> +- List all running applications:
```suggestion
- List all running applications with their details:
```

2024-01-03 13:27 UTC, vitorhcl approved these changes
Thank you!

2024-01-03 13:46 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-01-03 13:46 UTC, merged