lex: add examples and add {Free,Net,Open}BSD pags
tldr-pages/tldr pull request #11895
Opened 2023-12-28 22:41 UTC by vitorhcl

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2023-12-29 00:04 UTC, vitorhcl commented
I have an idea, as in this case the options in all platforms are the same we could leave flex (as a more complete page) in common and leave lex as the POSIX page, referencing flex in this page, what do you think?

2023-12-29 02:16 UTC, kbdharun commented
> I have an idea, as in this case the options in all platforms are the same we could leave flex (as a more complete page) in common and leave lex as the POSIX page, referencing flex in this page, what do you think?

Sure, that would work too.

2023-12-29 16:37 UTC, gutjuri requested changes
Thanks, I have some suggestions

2023-12-29 16:37 UTC, gutjuri commented on pages/common/lex.md
> +- Generate an analyzer from a Lex file to the file `lex.yy.c`:
```suggestion
- Generate an analyzer from a Lex file, storing it to the file `lex.yy.c`:
```

2023-12-29 16:37 UTC, gutjuri commented on pages/freebsd/lex.md
> +- Generate an analyzer from a Lex file to the file `lex.yy.c`:
```suggestion
- Generate an analyzer from a Lex file, storing it to the file `lex.yy.c`:
```

This suggestion should also be applied to the other platform files.

2023-12-29 16:37 UTC, gutjuri commented on pages/freebsd/lex.md
> +- Write analyzer to `s`[`t`]`dout`:
```suggestion
- Write the analyzer to `s`[`t`]`dout`:
```

2023-12-29 16:45 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page. (continuing @gutjuri's review). Additionally, we can remove the mnemonic highlighting from the `stdout` string.

2023-12-29 16:45 UTC, kbdharun commented on pages/freebsd/lex.md
> +`lex -{-stdout|t} {{analyzer.l}}`
```suggestion
`lex -{{-stdout|t}} {{analyzer.l}}`
```

2023-12-29 16:45 UTC, kbdharun commented on pages/linux/lex.md
> +`lex -{-stdout|t} {{analyzer.l}}`
```suggestion
`lex -{{-stdout|t}} {{analyzer.l}}`
```

2023-12-29 16:45 UTC, kbdharun commented on pages/netbsd/lex.md
> +- Write analyzer to `s`[`t`]`dout`:
```suggestion
- Write analyzer to `stdout`:
```

2023-12-29 16:45 UTC, kbdharun commented on pages/netbsd/lex.md
> +`lex -{-stdout|t} {{analyzer.l}}`
```suggestion
`lex -{{-stdout|t}} {{analyzer.l}}`
```

2023-12-29 16:45 UTC, kbdharun commented on pages/linux/lex.md
> +- Generate an analyzer from a Lex file to the file `lex.yy.c`:
```suggestion
- Generate an analyzer from a Lex file, storing it to the file `lex.yy.c`:
```

2023-12-29 16:45 UTC, kbdharun commented on pages/netbsd/lex.md
> +- Generate an analyzer from a Lex file to the file `lex.yy.c`:
```suggestion
- Generate an analyzer from a Lex file, storing it to the file `lex.yy.c`:
```

2023-12-29 16:45 UTC, kbdharun commented on pages/openbsd/lex.md
> +- Write analyzer to `s`[`t`]`dout`:
```suggestion
- Generate an analyzer from a Lex file, storing it to the file `lex.yy.c`:

`lex {{analyzer.l}}`

- Write analyzer to `stdout`:
```

2023-12-29 16:45 UTC, kbdharun commented on pages/osx/lex.md
> +- Write analyzer to `s`[`t`]`dout`:
```suggestion
- Generate an analyzer from a Lex file, storing it to the file `lex.yy.c`:

`lex {{analyzer.l}}`

- Write analyzer to `stdout`:
```

2023-12-29 16:45 UTC, kbdharun commented on pages/osx/lex.md
> +`lex -{-stdout|t} {{analyzer.l}}`
```suggestion
`lex -{{-stdout|t}} {{analyzer.l}}`
```

2023-12-30 13:26 UTC, kbdharun commented on pages/linux/lex.md
> +- Write analyzer to `s`[`t`]`dout`:
```suggestion
- Write analyzer to `stdout`:
```

2024-01-01 14:58 UTC, gutjuri approved these changes

2024-01-03 13:52 UTC, kbdharun approved these changes

2024-01-03 13:56 UTC, kbdharun commented
@sebastiaanspeck The updated check PR script still seems to have some issues.

2024-01-03 15:00 UTC, kbdharun commented
> What exactly is the issue you try to point at?

Currently, there are two output prompts:

```
The page pages/common/lex.md already exists under the linux platform.
The page pages/linux/lex.md already exists under the common platform.
```

IMO we should only tell linux/other pages already exists under common and not the other way around. But IG it's fine if others don't have an issue with the current behavior

2024-01-07 09:13 UTC, kbdharun approved these changes

2024-01-07 09:14 UTC, merged