pages.pt_BR: update outdated pages (removals that needs a replacement)
tldr-pages/tldr pull request #11975
Opened 2024-01-02 17:14 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2024-01-03 03:20 UTC, vitorhcl requested changes

2024-01-03 03:20 UTC, vitorhcl commented on pages.pt_BR/common/docker.md
>  - Lista todos os containers Docker:
```suggestion
- Lista todos os containers Docker (em execução e parados):
```

2024-01-03 13:40 UTC, kbdharun approved these changes

2024-01-05 00:14 UTC, isaacvicente reviewed
Hi @vitorhcl!
As soon as the pages gets updated, I will approve this PR.
Let me know when this happen. For the current translation, everything seems right :+1:

2024-01-06 18:02 UTC, vitorhcl approved these changes
Thank you so much for the help @sebastiaanspeck

2024-01-07 09:08 UTC, kbdharun approved these changes

2024-01-07 10:34 UTC, merged