jbang: add Spanish translation
tldr-pages/tldr pull request #12067
Opened 2024-01-12 18:51 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2024-01-12 19:47 UTC, tricantivu requested changes
What do you think about using a preposition, for example:

```md
> programas **en** Java
```

2024-01-12 19:47 UTC, tricantivu commented on pages.es/common/jbang.md
> +- Inicializar una clase Java (útil para scripts):
```suggestion
- Inicializa una clase Java (útil para scripts):
```

2024-01-13 12:24 UTC, kant commented
> What do you think about using a preposition @kant?
> 
> ```
> > ... programas en Java
> ```

Done

2024-01-26 18:02 UTC, kbdharun commented on pages.es/common/jbang.md
> +`{{echo 'Files.list(Paths.get("/etc")).forEach(System.out::println);'}}} | jbang -`
```suggestion
`{{echo 'Files.list(Paths.get("/etc")).forEach(System.out::println);'}} | jbang -`
```

2024-01-26 18:09 UTC, kbdharun approved these changes

2024-01-27 20:31 UTC, tricantivu approved these changes
The pull request is becoming too big, the other suggestions may be addressed later.

2024-01-28 04:57 UTC, blueskyson approved these changes

2024-01-28 04:57 UTC, merged