rpicam: add page
tldr-pages/tldr pull request #12078
Opened 2024-01-15 20:28 UTC by MIfoodie

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

The version of the command being documented is the latest version.

2024-01-15 21:51 UTC, gutjuri reviewed
Thanks for your contribution, I have added some comments. However, we usually put pages for different commands into different files. I think that it would be better if you created one file for rpicam-hello, one for rpicam-jpeg and so on :)

2024-01-15 21:51 UTC, gutjuri commented on pages/linux/rpicam.md
> +`rpicam-hello --tuning-file {{tuning/file}}`
```suggestion
`rpicam-hello --tuning-file {{/usr/share/libcamera/ipa/rpi/path/to/config.json}}`
```

2024-01-15 21:51 UTC, gutjuri commented on pages/linux/rpicam.md
> +`rpicam-jpeg {{file.jpeg}}`
```suggestion
`rpicam-jpeg {{path/to/file.jpeg}}`
```

2024-01-15 21:51 UTC, gutjuri commented on pages/linux/rpicam.md
> +`rpicam-vid -t {{duration}} -o {{file.h264}}`
```suggestion
`rpicam-vid -t {{duration_in_ms}} -o {{path/to/file.h264}}`
```

2024-01-15 21:51 UTC, gutjuri commented on pages/linux/rpicam.md
> +- Capture a video:
```suggestion
- Capture a video for the specified duration:
```

2024-01-15 21:51 UTC, gutjuri commented on pages/linux/rpicam.md
> +`rpicam-raw -t {{duration}} -o {{file.raw}}`
```suggestion
`rpicam-raw -t {{duration_in_ms}} -o {{path/to/file.raw}}`
```

2024-01-16 01:16 UTC, MIfoodie commented
> Thanks for your contribution, I have added some comments. However, we usually put pages for different commands into different files. I think that it would be better if you created one file for rpicam-hello, one for rpicam-jpeg and so on :)

Ok sorry. First PR I was expecting there to be some problems :)

2024-01-16 17:16 UTC, MIfoodie commented
@gutjuri Could you help me fix what @tldr-bot doesn't like? I tried and it still doesn't like it :(

2024-01-16 17:38 UTC, gutjuri reviewed
I think it's the missing full stops. The error messages by @tldr-bot are less than helpful in this case :P

2024-01-16 17:38 UTC, gutjuri commented on pages/linux/rpicam-raw.md
> +> More information: <https://www.raspberrypi.com/documentation/computers/camera_software.html#rpicam-raw>
```suggestion
> More information: <https://www.raspberrypi.com/documentation/computers/camera_software.html#rpicam-raw>.
```

2024-01-16 17:38 UTC, gutjuri commented on pages/linux/rpicam-vid.md
> +> More information: <https://www.raspberrypi.com/documentation/computers/camera_software.html#rpicam-vid>
```suggestion
> More information: <https://www.raspberrypi.com/documentation/computers/camera_software.html#rpicam-vid>.
```

2024-01-17 01:05 UTC, vitorhcl requested changes
Thanks for your contribution! I have suggested some changes:
- If the value is already provided in the description, please don't use a placeholder, but rather leave it as part of the command. From the [contributing guide](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md#markdown-format):
> However, if the description suggests a specific value, leave it as part of the command, and **not** as a placeholder, for example:
> 
> ```md
> - Display records more recent than 3 days:
> 
> `lastlog --time 3`
> ```
- Fix the path placeholder syntax. See the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths):
> ### Paths
>
> - Use `{{filename}}` when just the file name is expected.
> - For any reference to paths of files or directories,
>  use the format `{{path/to/<placeholder>}}`,
>  except when the location is implicit.
> - When the path cannot be relative,
>  but has to start at the root of the filesystem,
>  prefix it with a slash,
>  such as `get {{/path/to/remote_file}}`.
> - In case of a possible reference both to a file or a directory,
>  use `{{path/to/file_or_directory}}`.

2024-01-17 01:42 UTC, MIfoodie commented on pages/linux/rpicam-jpeg.md
> +`rpicam-jpeg -o name/of/file.jpg`
I'm a little confused on this one. Shouldn't it just be {{filename}} because you are saving the image as a file, not to a file?

2024-01-17 01:49 UTC, MIfoodie commented on pages/linux/rpicam-still.md
> +`rpicam-still -e {{bmp}} -o name/of/file.bmp`
I think it should still be {{bpm}} because you can also use png,  yuv420, and png in that field?

2024-01-17 02:14 UTC, vitorhcl commented on pages/linux/rpicam-still.md
> +`rpicam-still -e {{bmp}} -o name/of/file.bmp`
Ok, so it can be specified separating each option with | and changing the description to something generic

2024-01-17 02:18 UTC, vitorhcl commented on pages/linux/rpicam-jpeg.md
> +`rpicam-jpeg -o name/of/file.jpg`
It depends if you can save in another dir or if the command only allows you to specify a filename so that the file is saved in the same folder.

2024-01-17 02:39 UTC, MIfoodie commented on pages/linux/rpicam-jpeg.md
> +`rpicam-jpeg -o name/of/file.jpg`
It's saved in the current folder you are in with the provided name.

2024-01-17 03:51 UTC, kbdharun commented on pages/linux/rpicam-jpeg.md
> +`rpicam-jpeg -o name/of/file.jpg`
> It's saved in the current folder you are in with the provided name.

Yeah, but you could save it on a different directory too, we use this path convention across our pages (so I would suggest applying the suggested changes).

2024-01-17 06:56 UTC, gutjuri approved these changes
Thanks for incorporating my feedback!

2024-01-17 16:18 UTC, MIfoodie reviewed
Applied your changes except for one which I had to resolve...

2024-01-17 19:16 UTC, vitorhcl approved these changes
LGTM, thanks for your contribution!

2024-01-18 10:23 UTC, kbdharun approved these changes
Welcome to tldr and thanks for your contribution.

LGTM, after @sebastiaanspeck's suggestions.

2024-01-18 19:05 UTC, MIfoodie commented on pages/linux/rpicam-still.md
> +`rpicam-still -o name/of/file.jpg --shutter {{100000000}}`
Oops! Forgot to change that one

2024-01-22 04:15 UTC, kbdharun approved these changes

2024-01-22 04:16 UTC, merged