lid: add Spanish translation
tldr-pages/tldr pull request #12071
Opened 2024-01-13 23:08 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2024-01-14 01:04 UTC, tricantivu requested changes

2024-01-14 01:04 UTC, tricantivu commented on pages.es/linux/lid.md
> +- Ver documentación de `libuser-lid`:
```suggestion
- Ve documentación de `libuser-lid`:
```

2024-01-14 01:04 UTC, tricantivu commented
LGTM, thanks.

2024-01-14 13:41 UTC, tricantivu submitted a review, later dismissed

2024-01-14 13:41 UTC, tricantivu commented on pages.es/linux/lid.md
> +> En Fedora y Arch Linux, el nombre binario `lid` es tomado por otro programa. Ver `tldr libuser-lid`.
```suggestion
> En Fedora y Arch Linux, `lid` es otro programa. Vea `tldr libuser-lid`.
```

2024-01-14 13:41 UTC, tricantivu commented on pages.es/linux/lid.md
> +> Consulta la base de datos ID y reporta los resultados.
```suggestion
> Consulta la base de datos de identificadores y reporta los resultados.
```

2024-01-21 07:07 UTC, blueskyson approved these changes

2024-01-21 07:11 UTC, merged