cp: replace ambiguous text
tldr-pages/tldr pull request #12080
Opened 2024-01-17 07:43 UTC by TAKE72K

cp -i: text files -> file, more general.

---

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2024-01-17 10:00 UTC, cyqsimon requested changes

2024-01-17 12:30 UTC, TAKE72K commented on pages/linux/cp.md
Agree, this way is better and also demostrates usage of `*`. Thanks for the suggestion.

2024-01-17 14:20 UTC, cyqsimon approved these changes

2024-01-18 01:21 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-01-18 01:21 UTC, merged