Unmount: add page
tldr-pages/tldr pull request #12155
Opened 2024-01-28 12:21 UTC by Velox0

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2024-01-28 12:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12155) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12155) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=12155) it.</sub>

2024-01-30 17:56 UTC, vitorhcl requested changes
LGTM, thank you for your contribution! We generally follow the pattern I suggested

2024-01-30 17:56 UTC, vitorhcl commented on pages/linux/unmount.md
> +> More information: <https://manned.org/umount.8>.
```suggestion
> More information: <https://manned.org/umount.8>.

- View documentation for the right command:

`tldr umount`
```

2024-01-30 17:56 UTC, vitorhcl commented on pages/linux/unmount.md
> +> Try `tldr umount` for the tldr.
```suggestion
```

2024-01-30 20:09 UTC, vitorhcl approved these changes

2024-01-30 20:10 UTC, vitorhcl commented
Thank you for your contribution and welcome to tldr! Let's see what the others think

2024-01-30 20:34 UTC, Velox0 commented
Thanks! I look forward to contributing more!

2024-01-31 09:23 UTC, Velox0 commented on pages/linux/unmount.md
> +- View documentation for the right command:
Thanks for your approval! I have commit the suggestion. Whenever it's convenient for you, could you please merge the pull request? Thanks!

2024-01-31 10:14 UTC, cyqsimon approved these changes

2024-01-31 10:14 UTC, merged