bash: add Polish page
tldr-pages/tldr pull request #12165
Opened 2024-01-30 14:55 UTC by maslo-sh

bash: add Polish page

- [✅  ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ✅ ] The page(s) have at most 8 examples.
- [ ✅ ] The page description(s) have links to documentation or a homepage.
- [✅  ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ✅ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known): 3.2.57(1)-release**

2024-02-03 19:55 UTC, Velox0 requested changes

2024-02-03 19:55 UTC, Velox0 commented on pages.pl/linux/bash.md
> +- `-r` Uruchom sesję Bash w trybie [r]estrykcyjnym (więcej o trybie restrykcyjnym na stronie <https://www.gnu.org/software/bash/manual/html_node/The-Restricted-Shell.html>).
```suggestion
- `-r` Uruchom sesję Bash w trybie [r]estrykcyjnym (więcej o trybie restrykcyjnym na stronie <https://www.gnu.org/software/bash/manual/html_node/The-Restricted-Shell.html>):
```

2024-02-04 14:11 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution, can you please sign the CLA above for this PR to go through?

2024-02-04 14:11 UTC, kbdharun commented on pages.pl/linux/bash.md
> +  `{{echo "echo 'bash uruchomiony'"}} | bash`
```suggestion
`bash --norc`

- `-c` Wywołaj określoną komendę w powłoce Bash:

`bash -c "{{komenda powłoki systemowej}}"`

- Uruchom przekazany jako argument skrypt shella:

`bash {{sciezka/do/skrypt.sh}}`

- `-x` Wykonaj przekazany jako argument skrypt, wypisując wszystkie wykonane w procesie komendy na standardowe wyjście `stdout`:

`bash -x {{sciezka/do/skrypt.sh}}`

- `-e` Wykonaj przekazany skrypt do pojawienia się pierwszego błędu:

`bash -e {{sciezka/do/skrypt.sh}}`

- Wykonaj komendę przekazaną przez strumień wejścia `stdin`:

`{{echo "echo 'bash uruchomiony'"}} | bash`
```

2024-02-04 17:41 UTC, maslo-sh commented on pages.pl/linux/bash.md
Done.

2024-04-18 03:51 UTC, kbdharun commented
@acuteenvy Feel free to take over/close this PR, since the author has been unresponsive for a while.

2024-04-18 16:22 UTC, acuteenvy approved these changes

2024-04-18 16:23 UTC, merged