scripts: use pathlib and simplify page iteration
tldr-pages/tldr pull request #12183
Opened 2024-02-01 23:44 UTC by vitorhcl

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

Now set-more-info-link.py uses pathlib instead of os.path, which gave 2 clear benefits:
- Simplified the code
- It finally works properly on Windows (it wasn't getting the TLDR_ROOT automatically because of backslash, so I imported update-link.py's get_tldr_root())

Also, when a page is given via --page/-p, it doesn't iterate over each page on each platform anymore.

2024-02-02 22:03 UTC, vitorhcl commented on scripts/set-more-info-link.py
> +        "Please set TLDR_ROOT to the location of a clone of https://github.com/tldr-pages/tldr."
Oh, I just copied from the other script, the other script had a logger that prefixed all errors, warnings, etc. accordingly, so I just replaced the logger.error, with a print. But sure, we can put the color again.

2024-02-04 14:34 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-02-06 15:49 UTC, blueskyson requested changes

2024-02-06 15:49 UTC, blueskyson commented on scripts/set-more-info-link.py
> +        args.page = f"{args.page.rstrip('.md')}.md"
I think `rstrip` is misused here. I found some error cases:
```python
>>> print('md5sum'.rstrip('.md'))
md5su
>>> print('md5sum.md'.rstrip('.md'))
md5su
>>> print('dd'.rstrip('.md'))

>>> print('dd.md'.rstrip('.md'))

```

2024-02-08 18:00 UTC, blueskyson approved these changes
Look good to me. This can be merged after someone tests single-page and sync-all-pages functionality.

2024-02-13 13:43 UTC, kbdharun approved these changes
> Look good to me. This can be merged after someone tests single-page and sync-all-pages functionality.

Tested both functionalities locally on Windows. It works fine, the PR is GTG.

2024-02-13 13:44 UTC, merged