pnmmargin, pnmmontage, pnmnlfilt, pnmnorm, pnmpad, pnmpaste: add pages
tldr-pages/tldr pull request #12187
Opened 2024-02-03 16:44 UTC by gutjuri

2024-02-04 14:17 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

2024-02-04 14:17 UTC, kbdharun commented on pages/common/pnmmontage.md
> +- Specify the quality of the packing. Larger values produce smaller packings but take longer to compute:
```suggestion
- Specify the quality of the packing (Note: larger values produce smaller packings but take longer to compute.):
```
Maybe, make it a note?

2024-02-04 14:17 UTC, kbdharun commented on pages/common/pnmnorm.md
> +- Force the brightest pixels to be white, the darkest pixels to be black and spread out the ones inbetween linearly:
```suggestion
- Force the brightest pixels to be white, the darkest pixels to be black and spread out the ones in between linearly:
```

2024-02-04 14:17 UTC, kbdharun commented on pages/common/pnmnlfilt.md
> +> Apply a nonlinear filter onto a PNM image.
```suggestion
> Apply a non-linear filter onto a PNM image.
```

2024-02-04 14:17 UTC, kbdharun commented on pages/common/pnmnorm.md
> +- Force the brightest pixels to be white, the darkest pixels to be black and spread out the ones inbetween quadratically such that pixels with a brightness of `n` become 50 percent bright:
```suggestion
- Force the brightest pixels to be white, the darkest pixels to be black and spread out the ones in between quadratically such that pixels with a brightness of `n` become 50 % bright:
```
Maybe we can go with the symbol here as the line is already long, and could probably cause certain translations to cross the 256-character limit.

2024-02-04 14:17 UTC, kbdharun commented on pages/common/pnmpad.md
> +`pnmpad -left {{100}} -right {{150}} -top {{123} -bottom {{456}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```suggestion
`pnmpad -left {{100}} -right {{150}} -top {{123}} -bottom {{456}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```

2024-02-04 14:17 UTC, kbdharun commented on pages/common/pnmpaste.md
> +- Paste the image read from stdin into the specified image:
```suggestion
- Paste the image read from `stdin` into the specified image:
```

2024-02-04 14:49 UTC, kbdharun approved these changes

2024-02-08 22:10 UTC, vitorhcl requested changes
Thanks for your contribution. I suggest fixing the range placeholders to follow the style guide

2024-02-08 22:10 UTC, vitorhcl commented on pages/common/pnmnlfilt.md
> +`pnmnlfilt {{0.0-0.5}} {{radius}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```suggestion
`pnmnlfilt {{0.0..0.5}} {{radius}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```

2024-02-08 22:10 UTC, vitorhcl commented on pages/common/pnmnlfilt.md
> +`pnmnlfilt {{1.0-2.0}} {{radius}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```suggestion
`pnmnlfilt {{1.0..2.0}} {{radius}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```

2024-02-08 22:10 UTC, vitorhcl commented on pages/common/pnmnlfilt.md
> +`pnmnlfilt {{-0.9-(-0.1)}} {{radius}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```suggestion
`pnmnlfilt {{-0.9..(-0.1)}} {{radius}} {{path/to/image.pnm}} > {{path/to/output.pnm}}`
```

2024-02-09 13:49 UTC, vitorhcl approved these changes

2024-02-09 13:53 UTC, merged