httpx: add new command
tldr-pages/tldr pull request #12279
Opened 2024-02-15 10:37 UTC by fazlearefin

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-02-15 23:15 UTC, vitorhcl requested changes
Thank you for this excellent PR! I have some suggestions

2024-02-15 23:15 UTC, vitorhcl commented on pages/common/httpx.md
> +- Run a probe against a URL [s]aving [s]creenshots of certain paths, with [s]creenshot [t]imeouts (assets are saved in ./output):
```suggestion
- Run a probe against a URL [s]aving [s]creenshots of certain paths, with [s]creenshot [t]imeouts (assets are saved in `./output`):
```
From the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#special-cases):
> Technical wording on description lines should use the `backtick` syntax.
> Use backticks on the following:
> 
> - Paths, e.g. `package.json`, `/etc/package.json`.
> - Extensions, e.g. `.dll`.
> - Commands, e.g. `ls`.
> - Standard streams: `stdout`, `stdin`, `stderr`. **Do not** use the full names (e.g. standard output).

2024-02-16 03:55 UTC, fazlearefin commented on pages/common/httpx.md
> +`httpx -probe -u {{host1}},{{host2}},{{hostN}} -p http:{{80,8000-8080}},https:{{443,8443}} -timeout {{10}}`
Wrong syntax if used in `httpx` as hosts must be separated by commas. Here is the output from `httpx`

```console
# WITH SPACE SEPARATED, ONLY THE FIRST HOST IS SCANNED

$ httpx -u www.google.com www.yahoo.com www.github.com -p http:80,81,https:443,8443 -timeout 5

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.4.0 (latest)
https://www.google.com
$

###############################################################

# USING THE CORRECT SYNTAX ALL HOSTS ARE SCANNED

$ httpx -u www.google.com,www.yahoo.com,www.github.com -p http:80,81,https:443,8443 -timeout 5 

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.4.0 (latest)
http://www.github.com
https://www.github.com
https://www.yahoo.com
http://www.google.com
https://www.google.com
http://www.yahoo.com
$ 
```

If we must follow the style guide here, maybe this is acceptable?

```console
`httpx -probe -u {{host1,host2,...}} -p http:{{80,8000-8080}},https:{{443,8443}} -timeout {{10}}`
```

2024-02-16 03:57 UTC, fazlearefin commented on pages/common/httpx.md
> +`httpx -u {{host1}},{{host2}},{{hostN}} -fc {{400,401,404}}`
See above comment.

2024-02-16 03:57 UTC, fazlearefin commented on pages/common/httpx.md
> +`httpx -u {{host1}},{{host2}},{{hostN}} -mc {{200,301,304}}`
See above comment.

2024-02-16 03:59 UTC, vitorhcl commented on pages/common/httpx.md
> +`httpx -probe -u {{host1}},{{host2}},{{hostN}} -p http:{{80,8000-8080}},https:{{443,8443}} -timeout {{10}}`
Oh, sorry, overlooked it, but yeah, this suggestion fits the style guide just fine.

2024-02-16 04:10 UTC, fazlearefin commented on pages/common/httpx.md
> +`httpx -probe -u {{host1}},{{host2}},{{hostN}} -p http:{{80,8000-8080}},https:{{443,8443}} -timeout {{10}}`
I will push the changes following the style guide.

2024-02-16 04:16 UTC, fazlearefin commented on pages/common/httpx.md
> +`httpx -probe -u {{host1}},{{host2}},{{hostN}} -p http:{{80,8000-8080}},https:{{443,8443}} -timeout {{10}}`
Fixed

2024-02-16 04:16 UTC, fazlearefin commented on pages/common/httpx.md
> +`httpx -u {{host1}},{{host2}},{{hostN}} -fc {{400,401,404}}`
Fixed

2024-02-16 04:16 UTC, fazlearefin commented on pages/common/httpx.md
> +`httpx -u {{host1}},{{host2}},{{hostN}} -mc {{200,301,304}}`
Fixed

2024-02-16 08:13 UTC, kbdharun approved these changes

2024-02-16 08:44 UTC, fazlearefin commented on pages/common/httpx.md
> +> (Note that this is not the Python HTTPX which has the exact same command name).
```suggestion
> Note: This page uses the same command name as the Python HTTPX library, but it's not related.
```

2024-02-16 08:45 UTC, fazlearefin commented on pages/common/httpx.md
> +> (Note that this is not the Python HTTPX which has the exact same command name).
I suggested an alternate suggestion below which I think is provides more clarity.

2024-02-16 14:26 UTC, vitorhcl commented on pages/common/httpx.md
> +> (Note that this is not the Python HTTPX which has the exact same command name).
```suggestion
> Note: not to be confused with Python HTTPX which has the exact same command name.
```
How about this?

2024-02-16 14:48 UTC, gutjuri approved these changes

2024-02-16 15:33 UTC, kbdharun approved these changes

2024-02-17 01:33 UTC, vitorhcl approved these changes

2024-02-17 04:14 UTC, merged