Apt cache
tldr-pages/tldr pull request #12357
Opened 2024-02-25 05:47 UTC by punkestu

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-02-25 10:30 UTC, kbdharun reviewed
Thanks for your contribution, seems like you used the existing branch from #12356 and the `add-apt-repository.md` file is present here too. You could either delete the file from this PR or you could close the other pull request (anything would work).

Btw, for `apt-cache.md`, can you translate the placeholders inside `{{}}` too?

2024-02-26 01:09 UTC, reinhart1010 requested changes
Thanks for contributing! Here are some of my notes to review.

2024-02-26 01:09 UTC, reinhart1010 commented on pages.id/linux/apt-cache.md
> +> Alat query paket untuk Debian dan Ubuntu.
```suggestion
> Pencari paket untuk Debian dan Ubuntu.
```

Might be better to simplify this `query tool` term.

2024-02-26 01:09 UTC, reinhart1010 commented on pages.id/linux/add-apt-repository.md
> +> Mengelola definisi repositori `apt`.
```suggestion
> Kelola definisi repositori `apt`.
```

Can you please change this (and subsequent) sentences to use imperative mood (see [this](https://share.reinhart1010.id/tldrguidelinesidspecific) and [this](https://share.reinhart1010.id/tldridimperativemood))?

2024-02-27 01:36 UTC, punkestu reviewed
I have fixed it

2024-03-02 09:17 UTC, kbdharun approved these changes

2024-03-06 17:23 UTC, reinhart1010 requested changes
Hi, can you also apply these changes? Thank you!

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/add-apt-repository.md
> +- Menambah repositori `apt` baru:
```suggestion
- Tambah repositori `apt` baru:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/add-apt-repository.md
> +- Menghilangkan sebuah repositori `apt`:
```suggestion
- Hilangkan sebuah repositori `apt`:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/add-apt-repository.md
> +- Memperbarui cache paket setelah menambahkan sebuah repositori:
```suggestion
- Perbarui cache paket setelah menambahkan sebuah repositori:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/add-apt-repository.md
> +- Mengizinkan sumber paket untuk didownload dari repositori:
```suggestion
- Izinkan sumber paket untuk diunduh dari repositori:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-cache.md
> +- Mencari paket di sumber yang sudah kamu miliki:
```suggestion
- Cari paket di sumber yang sudah dimiliki:
```

Avoid using first-person nouns such as `kamu`.

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-cache.md
> +- Menampilkan informasi tentang sebuah paket:
```suggestion
- Tampilkan informasi tentang sebuah paket:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-cache.md
> +- Menampilkan apakah sebuah paket sudah terinstal dan paling terbaru:
```suggestion
- Tampilkan apakah sebuah paket sudah terinstal dan paling terbaru:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-cache.md
> +- Menampilkan dependensi sebuah paket:
```suggestion
- Tampilkan dependensi sebuah paket:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-cache.md
> +- Menampilkan paket yang bergantung pada paket tertentu:
```suggestion
- Tampilkan paket yang bergantung pada paket tertentu:
```

2024-03-07 11:20 UTC, reinhart1010 approved these changes
Thanks!

2024-03-07 11:20 UTC, merged