apt-get: add Indonesian translation
tldr-pages/tldr pull request #12359
Opened 2024-02-25 06:03 UTC by punkestu

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-02-25 10:12 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution. I have a minor suggestion for this page.

We generally translate possible placeholders inside `{{}}` too.

2024-02-25 10:12 UTC, kbdharun commented on pages.id/linux/apt-get.md
> +`apt-get purge {{package}}`
```suggestion
`apt-get install {{paket}}`

- Menghapus sebuah paket:

`apt-get remove {{paket}}`

- Menghapus sebuah paket dan file konfigurasinya:

`apt-get purge {{paket}}`
```

**Ref.** https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/common-arguments.md

2024-02-25 11:06 UTC, kbdharun approved these changes

2024-02-26 01:01 UTC, reinhart1010 requested changes
Thanks contributing! While the content itself is OK, there are some few changes you'll need to comply with our [style guide](https://share.reinhart1010.id/tldrstyleguide).

2024-03-06 17:23 UTC, reinhart1010 requested changes
Hi, can you also apply these changes? Thank you!

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-get.md
> +- Menginstal sebuah paket, atau memperbaruinya ke versi terbaru yang tersedia:
```suggestion
- Pasang sebuah paket, atau perbarui ke versi terbaru yang tersedia:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-get.md
> +- Menghapus sebuah paket:
```suggestion
- Hapus sebuah paket:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-get.md
> +- Menghapus sebuah paket dan file konfigurasinya:
```suggestion
- Hapus sebuah paket dan file konfigurasinya:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-get.md
> +- Memperbarui semua paket yang terinstal ke versi terbaru yang tersedia:
```suggestion
- Perbarui semua paket yang terpasang ke versi terbaru yang tersedia:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-get.md
> +- Membersihkan repositori lokal - menghapus file paket (`.deb`) yang sebelumnya gagal didownload dan tidak bisa di download lagi:
```suggestion
- Bersihkan repositori lokal, hapus file paket (`.deb`) yang sebelumnya gagal diunduh dan tidak bisa diunduh kembali:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-get.md
> +- Menghapus semua paket yang tidak diperlukan lagi:
```suggestion
- Hapus semua paket yang tidak diperlukan kembali:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-get.md
> +- Memperbarui paket yang terinstal (mirip `upgrade`), tapi bedanya ini menghapus paket yang tidak dipakai lagi dan menginstal paket tambahan untuk memenuhi dependensi baru:
```suggestion
- Perbarui paket yang terinstal (mirip `upgrade`), namun hapus paket yang tidak dipakai kembali dan pasang paket tambahan untuk memenuhi dependensi baru:
```

2024-03-07 11:18 UTC, reinhart1010 approved these changes
Thanks!

2024-03-07 11:18 UTC, merged