apt-file: add Indonesian translation
tldr-pages/tldr pull request #12360
Opened 2024-02-25 06:27 UTC by punkestu

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-02-25 10:25 UTC, kbdharun reviewed
Thanks for your contribution, can you translate the placeholders (i.e. ones within `{{}}` that don't have these options like `search|find`, `show|list` and `search|find`)?

2024-02-25 11:06 UTC, kbdharun approved these changes

2024-02-26 01:05 UTC, reinhart1010 requested changes
Thanks for you contribution. Here are some of my reviews.

2024-02-26 01:05 UTC, reinhart1010 commented on pages.id/linux/apt-file.md
> +> Mencari file-file di dalam paket `apt`, termasuk yang belum diinstal.
```suggestion
> Cari kumpulan berkas di dalam paket `apt`, termasuk yang belum dipasang.
```

Can you please change this (and subsequent) sentences to use imperative mood (see [this](https://share.reinhart1010.id/tldrguidelinesidspecific) and [this](https://share.reinhart1010.id/tldridimperativemood))?

Additionally, as a maintainer I currently intend to deprecate `file` in favor of `berkas` for Indonesian translations.

2024-03-06 17:23 UTC, reinhart1010 requested changes
Hi, can you also apply these changes? Thank you!

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-file.md
> +- Memperbarui basis data metadata:
```suggestion
- Perbarui basis data metadata:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-file.md
> +- Mencari paket yang berisi nama file atau path yang diinputkan:
```suggestion
- Cari paket yang berisi nama file atau path yang diinputkan:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-file.md
> +- Menampilkan daftar konten dari sebuah paket:
```suggestion
- Tampilkan daftar konten dari sebuah paket:
```

2024-03-06 17:23 UTC, reinhart1010 commented on pages.id/linux/apt-file.md
> +- Mencari paket yang yang sesuai dengan `ekspresi_reguler`:
```suggestion
- Cari paket yang sesuai dengan `ekspresi_reguler`:
```

2024-03-08 01:11 UTC, reinhart1010 approved these changes
Thanks!

2024-03-08 01:11 UTC, merged