find: add pt_BR translation
tldr-pages/tldr pull request #12382
Opened 2024-02-26 00:13 UTC by dnielMantov

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):** 4.9.0

2024-02-26 03:49 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-02-29 22:59 UTC, vitorhcl requested changes
Thank you, Daniel!

O verbo "corresponder" foi usado no indicativo, mas ele deve estar no subjuntivo, para especificar uma condição (se o arquivo corresponde)

LGTM after my suggestion

2024-02-29 22:59 UTC, vitorhcl commented on pages.pt_BR/common/find.md
> +- Procura por arquivos que correspondem a padrões de caminho ou nome específico:
```suggestion
- Procura por arquivos que correspondam a padrões de caminho ou nome específico:
```

2024-02-29 22:59 UTC, vitorhcl commented on pages.pt_BR/common/find.md
> +- Procura por diretórios que correspondem a um nome específico, sem o uso de case-sensitive:
```suggestion
- Procura por diretórios que correspondam a um nome específico, sem o uso de case-sensitive:
```

2024-02-29 22:59 UTC, vitorhcl commented on pages.pt_BR/common/find.md
> +- Procura por arquivos que correspondem a um nome específico, excluindo certos caminhos:
```suggestion
- Procura por arquivos que correspondam a um nome específico, excluindo certos caminhos:
```

2024-02-29 22:59 UTC, vitorhcl commented on pages.pt_BR/common/find.md
> +- Procura por arquivos que correspondem a uma faixa de tamanho específica, limitando a profundidade recursiva para "1":
```suggestion
- Procura por arquivos que correspondam a uma faixa de tamanho específica, limitando a profundidade recursiva para "1":
```

2024-03-01 23:30 UTC, vitorhcl approved these changes
Thank you, merging now 🚀

2024-03-01 23:32 UTC, merged