exa: add French translation
tldr-pages/tldr pull request #12428
Opened 2024-02-29 18:50 UTC by Ceres445

- [x ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-02-29 18:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12428) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12428) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=12428) it.</sub>

2024-03-01 07:50 UTC, nicokosi commented on pages.fr/common/exa.md
> +> Un remplacement moderne pour `ls` (Lister le contenu du répertoire).
```suggestion
> Une alternative moderne à `ls` (pour lister le contenu de répertoires).
```

2024-03-01 07:51 UTC, nicokosi commented on pages.fr/common/exa.md
> +- Ne listez pas les fichiers mentionnés dans `.gitignore` :
```suggestion
- Lister les fichiers sauf ceux mentionnés dans `.gitignore` :
```

2024-03-01 07:53 UTC, nicokosi approved these changes
:ok: for me, even I propose suggestions. :relaxed:

2024-03-01 10:48 UTC, noraj requested changes
Thanks for the contribution.

2024-03-01 10:48 UTC, noraj commented on pages.fr/common/exa.md
> +> Plus d'information: <https://the.exa.website>.
> There must be a single blank space between special characters in the descriptions

see

https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#french-specific-rules

```suggestion
> Plus d'information : <https://the.exa.website>.
```

2024-03-01 10:48 UTC, noraj commented on pages.fr/common/exa.md
> +- Lister les fichiers un par ligne :
> Command and example descriptions on pages in French must use the third person singular present indicative tense

```suggestion
- Liste les fichiers, un par ligne :
```

2024-03-01 10:48 UTC, noraj commented on pages.fr/common/exa.md
> +- Répertorier les fichiers avec le plus gros en haut :
```suggestion
- Liste les fichiers avec le plus volumineux en haut :
```

2024-03-01 10:48 UTC, noraj commented on pages.fr/common/exa.md
> +- Afficher une arborescence de fichiers, sur trois niveaux de profondeur :
```suggestion
- Affiche une arborescence de fichiers, sur trois niveaux de profondeur :
```

2024-03-01 10:48 UTC, noraj commented on pages.fr/common/exa.md
> +- Répertorier les fichiers avec leur en-tête, leur icône et leur statut Git :
```suggestion
- Liste les fichiers avec leur en-tête, leur icône et leur statut Git :
```

2024-03-01 10:48 UTC, noraj commented on pages.fr/common/exa.md
> +- Ne listez pas les fichiers mentionnés dans `.gitignore` :
```suggestion
- Liste les fichiers sauf ceux mentionnés dans `.gitignore` :
```

2024-03-01 13:19 UTC, noraj requested changes
The last one ;)

2024-03-01 13:19 UTC, noraj commented on pages.fr/common/exa.md
> +- Lister les fichiers sauf ceux mentionnés dans `.gitignore` :
```suggestion
- Liste les fichiers sauf ceux mentionnés dans `.gitignore` :
```

2024-03-01 22:26 UTC, Ceres445 commented
All done yay

2024-03-01 23:41 UTC, noraj approved these changes

2024-03-02 16:26 UTC, blueskyson approved these changes

2024-03-02 16:26 UTC, merged