deno: add French translation
tldr-pages/tldr pull request #12427
Opened 2024-02-29 18:42 UTC by Ceres445

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-02-29 18:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12427) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=12427) it.</sub>

2024-03-01 05:32 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution.

Not a native speaker so I can't check the contents. I went through the syntax alone. For French pages generally, we add a space between the contents and the colon.

2024-03-01 05:32 UTC, kbdharun commented on pages.fr/common/deno.md
> +- Installer un script exécutable à partir d’une URL:
```suggestion
> Plus d'information : <https://deno.land>.

- Exécuter un fichier JavaScript ou TypeScript :

`deno run {{chemin/du/fichier.ts}}`

- Démarrer un REPL (shell interactif) :

`deno`

- Exécuter un fichier avec l'accès au réseau activé :

`deno run --allow-net {{chemin/du/fichier.ts}}`

- Exécuter un fichier à partir d’une URL :

`deno run {{https://deno.land/std/examples/welcome.ts}}`

- Installer un script exécutable à partir d’une URL :
```

2024-03-01 08:19 UTC, kbdharun approved these changes

2024-03-01 10:04 UTC, noraj requested changes
Thanks for your contribution, one little remark.

2024-03-01 10:04 UTC, noraj commented on pages.fr/common/deno.md
> +- Exécuter un fichier JavaScript ou TypeScript :
Command and example descriptions on pages in French must use the third person singular present indicative tense, cf. https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#french-specific-rules

2024-03-01 16:58 UTC, merged