pages.nl/*: add missing alias pages
tldr-pages/tldr pull request #12480
Opened 2024-03-07 20:51 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2024-03-08 09:42 UTC, leonvsc requested changes

2024-03-08 09:42 UTC, leonvsc commented on pages.nl/common/bmptoppm.md
> +> More information: <https://netpbm.sourceforge.net/doc/bmptoppm.html>.
```suggestion
> Meer informatie: <https://netpbm.sourceforge.net/doc/bmptoppm.html>.
```

2024-03-08 09:42 UTC, leonvsc commented on pages.nl/common/pgmslice.md
> +> More information: <https://netpbm.sourceforge.net/doc/pgmslice.html>.
```suggestion
> Meer informatie: <https://netpbm.sourceforge.net/doc/pgmslice.html>.
```

2024-03-11 15:19 UTC, leonvsc approved these changes

2024-03-11 15:21 UTC, kbdharun approved these changes

2024-03-11 15:28 UTC, merged