create fclones.md
tldr-pages/tldr pull request #12541
Opened 2024-03-22 03:03 UTC by MustCodeAl

add tldr for fclones

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **0.34.0**

2024-03-22 05:19 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

2024-03-22 05:19 UTC, kbdharun commented on pages/common/fclones.md
> +`fclones move {{path/to/target_directory}} <dupes.txt`
```suggestion
- Search for duplicate files in the current directory:

`fclones group .`

- Search multiple directories for duplicate files and cache the results:

`fclones group --cache {{path/to/directory1 path/to/directory2}}`

- Search only the specified directory for duplicate files, skipping subdirectories and save the results into a file:

`fclones group {{path/to/directory}} --depth 1 > {{path/to/file.txt}}`

- Move the duplicate files in a TXT file to a different directory:

`fclones move {{path/to/target_directory}} < {{path/to/file.txt}}`
```

2024-03-22 05:19 UTC, kbdharun commented on pages/common/fclones.md
> +`fclones link --soft <dupes.txt --dry-run 2>/dev/null`
```suggestion
- Perform a dry run for soft links  in a TXT file without actually linking:

`fclones link --soft < {{path/to/file.txt}} --dry-run 2 > /dev/null`
```

2024-03-22 05:19 UTC, kbdharun commented on pages/common/fclones.md
> +- Preprocess jpg files in the current directory by using an external command  to strip their exif data before matching for duplicates:
```suggestion
- Preprocess JPG files in the current directory by using an external command  to strip their EXIF data before matching for duplicates:
```

2024-03-23 23:54 UTC, MustCodeAl commented
Changes

> Thanks for your contribution. I have some suggestions for this page.

Changes accepted

2024-03-24 02:09 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-03-24 06:28 UTC, einverne requested changes
hi @MustCodeAl  thank you for the new page, there are two extra spaces in the description.

2024-03-24 06:28 UTC, einverne commented on pages/common/fclones.md
> +- Perform a dry run for soft links  in a TXT file without actually linking:
```suggestion
- Perform a dry run for soft links in a TXT file without actually linking:
```

2024-03-24 06:28 UTC, einverne commented on pages/common/fclones.md
> +- Preprocess JPEG files in the current directory by using an external command  to strip their EXIF data before matching for duplicates:
```suggestion
- Preprocess JPEG files in the current directory by using an external command to strip their EXIF data before matching for duplicates:
```

2024-03-24 06:43 UTC, einverne approved these changes
Looks good now.

2024-03-25 04:06 UTC, kbdharun approved these changes

2024-03-25 04:12 UTC, merged