fclones: add Spanish translation
tldr-pages/tldr pull request #12556
Opened 2024-03-26 20:54 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-03-27 00:52 UTC, realFranco requested changes

2024-03-27 00:52 UTC, realFranco commented on pages.es/common/fclones.md
> +- Busca archivos duplicados sólo en el directorio especificado, omitiendo los subdirectorios, y guardar los resultados en un archivo:
```suggestion
- Busca archivos duplicados sólo en el directorio especificado, omitiendo los subdirectorios y guarda los resultados en un archivo:
```

2024-03-27 00:56 UTC, tricantivu commented on pages.es/common/fclones.md
> +`fclones link --soft < {{ruta/al/archivo.txt}} --dry-run 2 > /dev/null`
```suggestion
`fclones link --soft < {{ruta/al/archivo.txt}} --dry-run 2> /dev/null`
```

I am not sure if the option `--dry-run` accepts an argument. If not, the redirection is erroneous.

The example is very similar to the [last one in this section of the project's README](https://github.com/pkolaczk/fclones/blob/main/fclones/README.md#removing-files)

2024-03-27 01:12 UTC, realFranco commented
> Do you think we should write `archivo de texto` instead of `archivo TXT` @kant @realFranco?
> 
> I think the former might be slightly ambiguous.

Hello @tricantivu thank you for your contribs.

About your question, I will opt for `archivo de texto` instead of include `TXT` on the example description.

2024-03-27 01:45 UTC, tricantivu commented on pages.es/common/fclones.md
> +- Mueve los archivos duplicados en un archivo TXT en un directorio diferente:
```suggestion
- Mueve los archivos duplicados en un archivo de texto en un directorio diferente:
```

2024-03-29 17:29 UTC, kant reviewed
LGTM

2024-03-29 20:30 UTC, realFranco approved these changes

2024-03-29 20:31 UTC, realFranco commented
LGTM

2024-03-29 20:51 UTC, tricantivu approved these changes

2024-04-03 05:12 UTC, kbdharun approved these changes

2024-04-03 05:12 UTC, merged