evtest: add page
tldr-pages/tldr pull request #12657
Opened 2024-04-19 20:13 UTC by plastik-flasche

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):** 1.35-1

2024-04-19 20:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12657) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12657) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=12657) it.</sub>

2024-04-20 04:06 UTC, cyqsimon requested changes
Hi welcome to the project and thanks for your contribution.

I did a brief test and it seems like `evtest` requires elevated privileges in all cases, so it's [recommended](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines) to prefix each command with `sudo`.

Otherwise LGTM.

2024-04-20 04:11 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-04-20 21:33 UTC, plastik-flasche commented
It works on my machine without sudo, that's why I didn't add it initially... It just says `Not running as root, no devices may be available.` but then proceeds to still list everything and let me do everything... Probably because of something specific to Arch, or because I'm in some group or something else...

Anyway, I added `sudo` to every command now and thanks for your time!

2024-04-21 06:00 UTC, kbdharun approved these changes

2024-04-21 06:24 UTC, cyqsimon approved these changes

2024-04-21 06:24 UTC, merged