Added `devcontainer.json`
tldr-pages/tldr pull request #12699
Opened 2024-04-30 10:12 UTC by okineadev

As you know, in order to start working on this project, you need to install the necessary tools and packages, but this can take time.

For this purpose, Codespaces was created, so that you can **immediately** start development in the right environment, and not waste your time installing packages and configuring

And in order to implement it in your project - I added `devcontainer.json`

---

As you could understand, development in **Codespaces** will not start immediately, because for this you need to configure prebuilds (pre-installs the necessary packages and saves a system image ready for development)

After accepting the PR, I recommend enabling prebuilds with an update frequency of 4 times a week (apt will update packages 4 times a week to ensure fresh updates)

![image](https://github.com/tldr-pages/tldr/assets/81070564/60f1b7d8-f5cf-413a-acce-e215427d79bd)

After that, developers can immediately start development in **Codespaces**

We can discuss what can be added to the configuration and what can be removed

2024-04-30 10:36 UTC, okineadev reviewed
![knuckles-approved](https://github.com/tldr-pages/tldr/assets/81070564/a27b3ffb-3f4e-4c41-9826-6fe0f8ebf501)

2024-04-30 17:34 UTC, Magrid0 approved these changes
Looks good to me

2024-05-01 17:49 UTC, okineadev commented
Why draft?

2024-05-02 00:40 UTC, kbdharun commented
> Why draft?

I drafted it so that it doesn't get immediately merged as I need to review and discuss the changes. Will get back later today.

2024-05-02 05:20 UTC, okineadev commented on .devcontainer/devcontainer.json
> +  "features": {
**Python** and **NodeJS** are loaded in "features".

2024-05-02 06:17 UTC, okineadev commented on .devcontainer/devcontainer.json
> +    "ghcr.io/devcontainers/features/python:1": {}
Python and NodeJS are loaded in "features".

2024-05-02 07:01 UTC, okineadev commented on .devcontainer/devcontainer.json
> +    "update-apt-packages": "sudo apt update && sudo apt upgrade -y",
This command updates apt-packages, this command takes some time, but with prebuilds you can save a few minutes (in prebuilds, all packages will be pre-installed)

2024-05-02 07:02 UTC, okineadev commented on .devcontainer/devcontainer.json
> +    "install-node-packages": "npm install"
This is where the **Python** and **NodeJS** packages are installed

2024-05-02 07:07 UTC, okineadev commented on .devcontainer/devcontainer.json
> +        "DavidAnson.vscode-markdownlint"
Here are the **vscode extensions** that will be installed on **Codespace**, I've added the [**EditorConfig**](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) and [**Markdownlint**](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) extensions

If you know any extensions that will be useful when working in this repository - let me know

2024-05-02 07:10 UTC, okineadev commented on .devcontainer/devcontainer.json
> +        "resmon.show.cpufreq": false
Disabling CPU clock and battery indicators due to uselessness.

Here's where I got it from - https://github.com/microsoft/vscode/blob/main/.devcontainer/devcontainer.json#L25-L26

2024-05-02 12:23 UTC, kbdharun reviewed
Thanks for the explanations, I am currently testing the configuration locally and will get back in a few minutes. Having a devcontainer file is useful so that gets approval from me. Unfortunately, it isn't possible for us to setup pre-builds as it is a paid feature for organizations as mentioned in https://docs.github.com/en/codespaces/prebuilding-your-codespaces/configuring-prebuilds, we don't have a lot of dependencies so just having a dev container config would be enough as it would just take 30 seconds to 1 minute for it to get initialized fully.

2024-05-02 12:53 UTC, kbdharun requested changes
The current devcontainer configuration unfortunately takes a long time to build as you mentioned (locally it took me 15-20 minutes). ~~Since pre-builds aren't an option for us. A better alternative would be to tweak the Devcontainer configuration to use a pre-built Docker image instead along with these additional configs (this way the Codespace would take a relatively same time for initialization). I will mark this PR as a draft and will work on testing and porting this to it instead.~~

2024-05-02 14:04 UTC, okineadev commented
> locally it took me 15-20 minutes

Then we can exclude "sudo apt upgrade -y"

---

> tweak the Devcontainer configuration to use a pre-built Docker image

Also, which prebuild Docker images are you talking about?

2024-05-02 14:07 UTC, kbdharun commented
> Then we can exclude "sudo apt upgrade -y"

That would work too. Will test your config with this.

> Also, which prebuild Docker images are you talking about?

I meant building a Docker image with deps installed and specifying it in the dev-container config along with a custom command for our usecase.

2024-05-02 14:16 UTC, kbdharun commented
> That would work too. Will test your config with this.

Yep, that worked perfectly which took the time to sub 1 minute for setup, I added a few extensions and made the container un-privileged (btw why was it set to privileged initially?).

2024-05-02 14:33 UTC, kbdharun approved these changes
LGTM, thanks for your contribution. _Tested this configuration with a codespace, the initialization took 1-2 minutes which IG is fine for most._

2024-05-02 15:24 UTC, okineadev commented
Great, so you can merge the branch!

2024-05-02 15:38 UTC, merged

2024-05-02 15:39 UTC, okineadev commented
![](https://media1.tenor.com/m/NIF8-DyWcZoAAAAd/pull-request-pr.gif)