added entry about updatekeys
tldr-pages/tldr pull request #12719
Opened 2024-05-03 18:21 UTC by Shensen1

Hi, 
my first public contribution here, so greetings to my Ma! :)

I think this one is essential, got stuck twice now by remembering this one and so I guess it should be shared with others 

- [x ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ x] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-05-03 18:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=12719) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=12719) it.</sub>

2024-05-03 18:38 UTC, Magrid0 requested changes

2024-05-03 18:38 UTC, Magrid0 commented on pages/common/sops.md
> +- Update the declared keys in .sops.yaml
```suggestion
- Update the declared keys in .sops.yaml:
```

2024-05-03 18:38 UTC, Magrid0 commented on pages/common/sops.md
> +- Update the declared keys in .sops.yaml
Hi, welcome to TlDr, as the bot said you have to add a : at the end of each command description

2024-05-03 18:55 UTC, Magrid0 requested changes

2024-05-03 18:55 UTC, Magrid0 commented on pages/common/sops.md
> +`sops updatekeys ./path/file.yaml`
```suggestion
`sops updatekeys {{/path/to/file.yaml}}`
```

And also add {{ }} around the file path

2024-05-03 19:40 UTC, Magrid0 commented
> Ok, nice So now just wait for another ok and then it gets pushed?

Yep!

> But why have the file paths to be in that format? actually wanted to add one simpler syntax example

Because the [Style Guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#example-commands) say they have to be written in this way

![image](https://github.com/tldr-pages/tldr/assets/73496008/3b3045b6-533c-491d-966f-4f1257152e65)

2024-05-03 19:56 UTC, Shensen1 commented
Ok, makes sense, head [guidelines](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines) in mind with

2. When in doubt, keep new command-line users in mind. Err on the side of clarity rather than terseness. For example, commands that require sudo should include it directly in the examples.

2024-05-04 07:22 UTC, kbdharun approved these changes
Welcome to tldr and thanks for your contribution. LGTM, after @sebastiaanspeck's suggestion above.

2024-05-04 08:09 UTC, Magrid0 approved these changes
LGTM, i think it'll be ready to merge after sebastiaanspeck suggestion

2024-05-18 20:50 UTC, spageektti commented
Since the author of this PR has been inactive for a long time, I have made the suggested changes.

[Maintainers Guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md#ii-handling-prs) says:

> If the only issues holding up a merge are **trivial fixes**
>   (typos, syntax errors, etc.), and the author doesn't respond in a day or two,
>   **maintainers can make the necessary changes themselves**,
>   and proceed with the merge process.

2024-05-18 21:17 UTC, spageektti approved these changes

2024-05-19 04:13 UTC, kbdharun commented on pages/common/sops.md
Just now noticed the page description looks a bit vague, maybe we could reword it to something more descriptive.

2024-05-19 09:08 UTC, kbdharun approved these changes

2024-05-19 09:09 UTC, merged