pages.*: sync page titles
tldr-pages/tldr pull request #12734
Opened 2024-05-05 09:31 UTC by sebastiaanspeck

This PR is the result of the newly introduced Python-script in #12732 

Edit: 
As long as #12732 is not merged, this is just for showcasing the output.

2024-05-05 09:40 UTC, Magrid0 approved these changes

2024-05-05 19:48 UTC, vitorhcl approved these changes

2024-05-05 20:58 UTC, kant requested changes
Some comments, some LGTM

2024-05-05 20:58 UTC, kant commented on pages.es/common/fossil-delete.md
LGTM

2024-05-05 20:58 UTC, kant commented on pages.es/common/fossil-forget.md
LGTM

2024-05-05 20:58 UTC, kant commented on pages.es/common/fossil-new.md
>  > Este comando es un alias de `fossil-init`.
> Este comando es un alias de `fossil init`.

2024-05-05 20:58 UTC, kant commented on pages.es/common/gh-cs.md
>  > Este comando es un alias de `gh-codespace`.
> Este comando es un alias de `gh codespace`.

2024-05-05 20:58 UTC, kant commented on pages.es/common/pio-init.md
LGTM

2024-05-05 20:58 UTC, kant commented on pages.es/common/tlmgr-arch.md
LGTM

2024-05-05 20:58 UTC, kant commented on pages.es/common/type.md
LGTM

2024-05-05 20:58 UTC, kant commented on pages.es/linux/ip-route-list.md
> Este comando es un alias de `ip route show`.

2024-05-05 21:39 UTC, noraj approved these changes
LGTM for the titles of French pages

2024-05-06 20:59 UTC, gutjuri approved these changes

2024-05-06 23:44 UTC, acuteenvy commented on pages.pl/common/clamav.md
It's not just the title, the entire page is misleading. This isn't even a command.

These pages with mismatched titles, it all looks like #11373 again. [It's an automatically generated page with `set-alias-page.py`](https://github.com/tldr-pages/tldr/commits/main/pages.pl/common/clamav.md), which as of now makes a whole lot of mistakes when translating pages.

2024-05-07 22:20 UTC, acuteenvy approved these changes

2024-05-08 00:48 UTC, acuteenvy commented on pages.pl/common/fossil-ci.md
>  > To polecenie jest aliasem `fossil-commit`.
Hyphens haven't been removed from descriptions. This is also the case with other languages.
```suggestion
> To polecenie jest aliasem `fossil commit`.
```

2024-05-08 00:48 UTC, acuteenvy commented on pages.pl/common/fossil-new.md
>  > To polecenie jest aliasem `fossil-init`.
```suggestion
> To polecenie jest aliasem `fossil init`.
```

2024-05-08 00:48 UTC, acuteenvy commented on pages.pl/common/gh-cs.md
>  > To polecenie jest aliasem `gh-codespace`.
```suggestion
> To polecenie jest aliasem `gh codespace`.
```

2024-05-08 00:48 UTC, acuteenvy commented on pages.pl/linux/ip-route-list.md
>  > To polecenie jest aliasem `ip-route-show`.
```suggestion
> To polecenie jest aliasem `ip route show`.
```

2024-05-08 00:51 UTC, acuteenvy commented
There are changes from #12732 here, could you please `git revert` that? (https://github.com/tldr-pages/tldr/pull/12734/commits/f7d3c18a7d38143f4424de51b093f5c81bf9228d)

2024-05-08 18:57 UTC, merged