git-tag: Add example on how to push a tag
tldr-pages/tldr pull request #13079
Opened 2024-06-19 10:00 UTC by ZeroOne3010

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

I think this is a pretty crucial piece of information on how you use tags in Git.

2024-06-19 10:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=13079) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=13079) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=13079) it.</sub>

2024-06-19 11:52 UTC, spageektti approved these changes

2024-06-19 14:25 UTC, vitorhcl requested changes
Thank you for your contribution!

Isn't remote a better term? Upstream is also used for forks.

LGTM after this issue is addressed.

2024-06-19 14:25 UTC, vitorhcl commented on pages/common/git-tag.md
> +- Push a tag to upstream:
```suggestion
- Push a tag to remote:
```

2024-06-19 14:25 UTC, vitorhcl commented on pages/common/git-tag.md
>  `git fetch --tags`
I can't suggest on the line above, but

```suggestion
- Get updated tags from remote:
```

2024-06-20 05:22 UTC, kbdharun approved these changes
Welcome to tldr and thanks for your contribution.

LGTM, after the above suggestions.

2024-06-20 05:57 UTC, ZeroOne3010 commented
> Isn't remote a better term? Upstream is also used for forks.

Yes, good point, of course! I just copied the term from the other example without stopping to think. 🤦 I've changed both of them now!

2024-06-20 16:31 UTC, spageektti commented on pages/common/git-tag.md
> +`git push origin tag {{tagname}}`
```suggestion
`git push origin tag {{tag_name}}`
```
Like in other examples.

2024-06-20 16:34 UTC, spageektti commented
Thanks for your contribution @ZeroOne3010. Can you please check my suggestion so we can merge this PR?

2024-06-20 17:18 UTC, merged