Macos iostat tldr
tldr-pages/tldr pull request #13119
Opened 2024-06-23 05:50 UTC by CJacob314

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- MacOS `iostat` version unknown

2024-06-23 05:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=13119) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=13119) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=13119) it.</sub>

2024-06-24 17:04 UTC, gutjuri requested changes
Thanks for you contribution! In our pages, we do not support general Markdown syntax (i.e. \*\*bold text \*\*). Could you please edit your PR as not to include such markup?

2024-06-24 17:18 UTC, CJacob314 commented
Sure, I'll revise my markdown according to that style as soon as I can.

2024-06-25 06:18 UTC, kbdharun reviewed
Welcome to tldr and thanks for your contribution. I have some suggestions for this page.

2024-06-25 10:48 UTC, CJacob314 commented on pages/osx/iostat.md
> +- Display statistics for the first disk every second ad infinitum:
This [isn't](https://en.wikipedia.org/wiki/Ad_infinitum) a typo.

2024-06-25 11:05 UTC, spageektti commented on pages/osx/iostat.md
> +- Display statistics for the first disk every second ad infinitum:
```suggestion
- Display statistics for the first disk every second indefinitely:
```
Not everyone may know what ad infinitum mean
```suggestion
- Display statistics for the first disk every second ad infinitum (indefinitely):
```

2024-06-25 13:52 UTC, spageektti approved these changes

2024-06-25 14:04 UTC, kbdharun approved these changes

2024-06-27 11:32 UTC, merged