dos2unix: add French translation
tldr-pages/tldr pull request #13599
Opened 2024-09-04 20:09 UTC by pascal-brand38

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-09-04 20:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=13599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=13599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=13599) it.</sub>

2024-09-07 10:12 UTC, noraj requested changes
1. Concernant la typographie, il doit y avoir un espace avant le `:`
2. Toutes les phrases doivent être au présent de l'indicatif plutôt qu'à l'infinitif

2024-09-07 10:12 UTC, noraj commented on pages.fr/linux/dos2unix.md
> +- Remplace les fins de lignes d'un fichier:
```suggestion
- Remplace les fins de lignes d'un fichier :
```

2024-09-07 10:12 UTC, noraj commented on pages.fr/linux/dos2unix.md
> +- Créer une copie avec des fins de lignes de type Unix:
```suggestion
- Crée une copie avec des fins de lignes de type Unix :
```

2024-09-07 10:12 UTC, noraj commented on pages.fr/linux/dos2unix.md
> +- Affiche les informations d'un fichier:
```suggestion
- Affiche les informations d'un fichier :
```

2024-09-07 10:12 UTC, noraj commented on pages.fr/linux/dos2unix.md
> +- Conserve/Ecrit/Supprime la marque d'ordre des octets (BOM):
```suggestion
- Conserve/Ecrit/Supprime la marque d'ordre des octets (BOM) :
```

2024-09-08 12:03 UTC, noraj approved these changes
LGTM now

2024-09-08 12:14 UTC, spageektti approved these changes

2024-09-08 12:14 UTC, merged