git-reflog: Update Spanish translation
tldr-pages/tldr pull request #13765
Opened 2024-09-20 18:29 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-09-26 07:55 UTC, nelsonfigueroa requested changes

2024-09-26 07:55 UTC, nelsonfigueroa commented on pages.es/common/git-reflog.md
> +`git reflog {{-n|--dry-run}} {{5}}`
I don't think this is correct. `git reflog -n 5` works, but not `git reflog --dry-run 5`. According to [the docs](https://git-scm.com/docs/git-reflog) the `--dry-run` option is only available for subcommands like `git reflog expire` and `git reflog delete`. 

For reference I tested this out on Git v.2.46.2

2024-09-26 08:01 UTC, nelsonfigueroa commented on pages.es/common/git-reflog.md
> +`git reflog {{-n|--dry-run}} {{5}}`
I'll create a separate PR for pages/common/git-reflog.md to change the example to use `{{-n|--max-count}}`

2024-09-26 08:07 UTC, nelsonfigueroa commented on pages.es/common/git-reflog.md
> +`git reflog {{-n|--dry-run}} {{5}}`
PR created: https://github.com/tldr-pages/tldr/pull/13837

2024-09-26 15:33 UTC, nelsonfigueroa approved these changes

2024-09-27 15:23 UTC, reinhart1010 approved these changes
LGTM

2024-09-27 15:24 UTC, merged