protonvpn-cli, protonvpn-cli-connect: fix link and update pages
tldr-pages/tldr pull request #13860
Opened 2024-09-27 19:28 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2024-09-29 15:42 UTC, kbdharun approved these changes

2024-09-30 01:46 UTC, cyqsimon requested changes

2024-09-30 01:46 UTC, cyqsimon commented on pages/linux/protonvpn-cli.md
>  > Official ProtonVPN client.
I think we should change the description. This rewrite, although widely used, does not seem like an officially-endorsed client. I could be wrong though; if that's the case, sources please.

2024-09-30 03:31 UTC, cyqsimon approved these changes

2024-10-02 06:18 UTC, merged