pages.pt_BR: add several linux pages
tldr-pages/tldr pull request #13951
Opened 2024-10-03 00:44 UTC by rffontenelle

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-10-03 10:56 UTC, rffontenelle commented
@sebastiaanspeck changed the PR name. Thanks.

2024-10-03 11:51 UTC, rffontenelle commented
Oh ok. I didn't realized you had it renamed so I was puzzling around look for what was wrong. I'll be more careful with the style next PRs

2024-10-04 23:20 UTC, renie requested changes
Just small fixes on some verbs to not use infinitive on the description of commands.

2024-10-04 23:20 UTC, renie commented on pages.pt_BR/linux/apport-bug.md
> +> Registrar um relatório de bug no Ubuntu.
```suggestion
> Registra um relatório de bug no Ubuntu.
```

2024-10-04 23:20 UTC, renie commented on pages.pt_BR/linux/cgclassify.md
> +> Mover tarefas em execução para `cgroups`.
```suggestion
> Move tarefas em execução para `cgroups`.
```

2024-10-04 23:20 UTC, renie commented on pages.pt_BR/linux/cgcreate.md
> +> Criar cgroups, usados para limitar, medir e controlar recursos usados pelos processos.
```suggestion
> Cria cgroups, usados para limitar, medir e controlar recursos usados pelos processos.
```

2024-10-04 23:20 UTC, renie commented on pages.pt_BR/linux/cgexec.md
> +> Limitar, medir e controlar recursos usados pelos processos.
```suggestion
> Limita, mede e controla recursos usados pelos processos.
```

2024-10-04 23:20 UTC, renie commented on pages.pt_BR/linux/ip-route-show.md
> +> Exibir subcomando para o gerenciamento de tabelas de roteamento de IP.
```suggestion
> Exibe subcomando para o gerenciamento de tabelas de roteamento de IP.
```

2024-10-04 23:20 UTC, renie commented on pages.pt_BR/linux/megatools-dl.md
> +> Baixar arquivos de `mega.nz`.
```suggestion
> Baixa arquivos de `mega.nz`.
```

2024-10-05 00:07 UTC, renie approved these changes
Now all seems good! Thanks for one more contribution! :sun_with_face:

2024-10-05 00:08 UTC, merged