cargo-add, cargo-bench, cargo-build, cargo-init: add French translation
tldr-pages/tldr pull request #14129
Opened 2024-10-11 12:23 UTC by trouyer

see #13570 

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

2024-10-11 12:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=14129) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=14129) before we can accept your contribution.<br/><hr/>**trouyer** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=14129) it.</sub>

2024-10-11 14:30 UTC, noraj requested changes
Thanks for your contribution, please fix the following issues.

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-add.md
> +- Ajoute une dépendance optionnelle, qui sera exposée comme une fonctionnalité du crate:
```suggestion
- Ajoute une dépendance optionnelle, qui sera exposée comme une fonctionnalité du crate :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-add.md
> +- Ajoute une dépendance avec toutes les fonctionnalités par défaut désactivées:
```suggestion
- Ajoute une dépendance avec toutes les fonctionnalités par défaut désactivées :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-bench.md
> +- Execute tous les benchmarks d'un paquet:
```suggestion
- Execute tous les benchmarks d'un paquet :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-bench.md
> +- Ne pas arréter quand un benchmark échoue:
```suggestion
- Ne pas arréter quand un benchmark échoue :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-bench.md
> +- Compile, mais n'exécute pas les benchmarks:
```suggestion
- Compile, mais n'exécute pas les benchmarks :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-bench.md
> +- Exécute le benchmark spécifié:
```suggestion
- Exécute le benchmark spécifié :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-bench.md
> +- Exécute les benchmarks avec un profile spécifique (défaut: `bench`):
```suggestion
- Exécute les benchmarks avec un profile spécifique (défaut : `bench`) :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-bench.md
> +- Exécute les benchmarks sur tous les examples cibles :
```suggestion
- Exécute les benchmarks sur tous les exemples cibles :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-build.md
> +- Compile les artefacts avec le mode release, avec des optimizations :
```suggestion
- Compile les artefacts avec le mode publication, avec des optimisations :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-init.md
> +> Equivalent de `cargo new`, mais spécifier un dossier est optionnel.
```suggestion
> Équivalent de `cargo new`, mais où spécifier un dossier est optionnel.
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-init.md
> +- Initilise un projet Rust binaire dans le dossier current :
```suggestion
- Initialise un projet Rust binaire dans le dossier courant :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-init.md
> +- Initialise un projet de bibliothèque Rust  dans le dossier spécifié :
```suggestion
- Initialise un projet de bibliothèque Rust dans le dossier spécifié :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-init.md
> +- Initialise un dépot de système de gestion de version dans le dossier du projet (defaut : `git`) :
```suggestion
- Initialise un dépôt de système de gestion de version dans le dossier du projet (défaut : `git`) :
```

2024-10-11 14:30 UTC, noraj commented on pages.fr/common/cargo-init.md
> +- Défini le nom du paquet (defaut: nom du dossier):
```suggestion
- Défini le nom du paquet (défaut : nom du dossier):
```

2024-10-13 06:18 UTC, trouyer commented
> Thanks for your contribution, please fix the following issues.

Thanks Noraj, it's fixed

2024-10-13 15:53 UTC, noraj approved these changes

2024-10-13 15:59 UTC, merged