time: update Dutch translation and titlecase Bash
tldr-pages/tldr pull request #14143
Opened 2024-10-12 16:27 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2024-10-13 16:49 UTC, spageektti requested changes
You sure bash should be Bash?

2024-10-13 16:49 UTC, spageektti approved these changes

2024-10-13 16:54 UTC, spageektti commented
> > You sure bash should be Bash?
> 
> Yes, I checked with other pages and the [Wikipedia](https://en.m.wikipedia.org/wiki/Bash_(Unix_shell))

I know
I checked Polish Wikipedia before the English one...

2024-10-14 09:30 UTC, leonvsc approved these changes

2024-10-14 09:30 UTC, merged