crane: add Dutch translation
tldr-pages/tldr pull request #14264
Opened 2024-10-18 05:41 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2024-10-19 14:23 UTC, leonvsc requested changes

2024-10-19 14:23 UTC, leonvsc commented on pages.nl/common/crane-registry.md
There is 2 times the help command in this file. Which one is right?

2024-10-19 14:23 UTC, leonvsc commented on pages.nl/common/gcrane-gc.md
This file is not translated.

2024-10-21 06:53 UTC, leonvsc commented on pages.nl/common/crane-registry.md
Yeah, I think it is good to have 2 different descriptions for the command. Because at the moment it looks like the same description, but 2 different commands.

2024-10-22 16:37 UTC, leonvsc approved these changes

2024-10-26 10:07 UTC, spageektti approved these changes

2024-10-26 10:07 UTC, merged