Create goenv.md
tldr-pages/tldr pull request #14303
Opened 2024-10-21 07:50 UTC by oneWalker

a golang versions manager

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-10-21 07:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=14303) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=14303) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=14303) it.</sub>

2024-10-21 10:48 UTC, spageektti commented on pages/common/goenv.md
> +- Set the default golang version:
```suggestion
- List all available `goenv` commands:

`goenv commands`

- Install a specific version of Golang:

`goenv install {{go_version}}`

- Use a specific version of Golang in the current project:

`goenv local {{go_version}}`

- Set the default Golang version:
```
```suggestion
- List all available Goenv commands:

`goenv commands`

- Install a specific version of Golang:

`goenv install {{go_version}}`

- Use a specific version of Golang in the current project:

`goenv local {{go_version}}`

- Set the default Golang version:
```

2024-10-24 18:07 UTC, gutjuri requested changes
LGTM after this and sebastiaanspeck's suggestions ;)

2024-10-24 18:07 UTC, gutjuri commented on pages/common/goenv.md
> +> Supports version numbers like " 1.16.15" or "1.22.8" etc.
```suggestion
> Supports version numbers like "1.16.15" or "1.22.8" etc.
```

2024-10-29 10:05 UTC, spageektti approved these changes

2024-10-29 16:53 UTC, gutjuri approved these changes

2024-10-29 18:12 UTC, merged