Add Page: dpigs
tldr-pages/tldr pull request #14359
Opened 2024-10-24 15:39 UTC by vp007-dev

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

resolves Issue #14020

2024-10-24 18:21 UTC, Managor requested changes

2024-10-24 18:21 UTC, Managor commented on pages/linux/dpigs.md
> +> Show which installed packages occupy the most space.
```suggestion
> Show which installed packages occupy the most space on `apt` based systems.
```

2024-10-24 18:21 UTC, Managor commented on pages/linux/dpigs.md
> +> More information: <https://manned.org/man/dpigs>.
```suggestion
> More information: <https://manned.org/man/dpigs>.
```
Redundant

2024-10-24 18:21 UTC, Managor commented on pages/linux/dpigs.md
> +> More information: <https://manned.org/man/dpigs>.
```suggestion
> More information: <https://manned.org/dpigs>.
```

2024-10-24 18:21 UTC, Managor commented on pages/linux/dpigs.md
> +`-h, --help`
This is not how our syntax works. Please take a look at other pages and see how you should format the commands.

2024-10-24 18:21 UTC, gutjuri requested changes
Thanks! We usually include the name of the command in the example and describe the different options as done in my suggestions. Feel free to check out other pages to get a feeling for how the pages are usually structured :)

2024-10-24 18:21 UTC, gutjuri commented on pages/linux/dpigs.md
> +> Sorts the installed packages by size and outputs the largest ones.
```suggestion
> Sort the installed packages by size and output the largest ones.
```

We usually use imperative in descriptions :)

2024-10-24 18:21 UTC, gutjuri commented on pages/linux/dpigs.md
> +`-s, --status=FILE`
```suggestion
- Use the specified file instead of the default dpkg [s]tatus file:

`dpigs --status={{path/to/file}}`
```

2024-10-24 18:21 UTC, gutjuri commented on pages/linux/dpigs.md
> +`-h, --help`
```suggestion
- Display the largest [S]ource packages of binary packages installed on the system:

`dpigs --source`

- Display package sizes in [H]uman-readable format:

`dpigs --human-readable`

- Display help:

`dpigs --help`
```

2024-10-24 18:21 UTC, gutjuri commented on pages/linux/dpigs.md
> +`-n, --lines=N`
```suggestion
- Display the N largest packages on the system:

`dpigs --lines={{N}}`
```

2024-10-24 19:05 UTC, gutjuri approved these changes
LGTM!

2024-10-25 03:21 UTC, Managor commented
I unresolved a second suggestion.

2024-10-25 03:23 UTC, Managor approved these changes

2024-10-25 03:23 UTC, Managor commented on pages/linux/dpigs.md
> +> More information: <https://manned.org/man/dpigs>.
```suggestion
> Show which installed packages occupy the most space on `apt` based systems.
> More information: <https://manned.org/dpigs>.
```

2024-10-27 16:43 UTC, merged