pvremove: add page
tldr-pages/tldr pull request #14360
Opened 2024-10-24 15:58 UTC by jackiesogi

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known): LVM version: 2.03.23(2) (2023-11-21) Library version: 1.02.197 (2023-11-21)**

2024-10-24 18:23 UTC, gutjuri approved these changes
Thanks! LGTM after my suggestions.

2024-10-24 18:23 UTC, gutjuri commented on pages/linux/pvremove.md
> +- Remove LVM label from a physical volume:
```suggestion
- Remove a LVM label from a physical volume:
```

2024-10-24 18:23 UTC, gutjuri commented on pages/linux/pvremove.md
> +- Remove LVM label without asking for confirmation:
```suggestion
- Remove a LVM label without asking for confirmation:
```

2024-10-24 18:23 UTC, gutjuri commented on pages/linux/pvremove.md
> +- Forcefully remove LVM label:
```suggestion
- Forcefully remove a LVM label:
```

2024-10-26 16:21 UTC, spageektti approved these changes

2024-10-26 16:22 UTC, spageektti requested changes

2024-10-26 16:22 UTC, spageektti commented on pages/linux/pvremove.md
> +`sudo pvremove --reportformat json {{physical_volume}}`
```suggestion
`sudo pvremove --verbose {{/dev/sdaXY}}`

- Remove a LVM label without asking for confirmation:

`sudo pvremove --yes {{/dev/sdaXY}}`

- Forcefully remove a LVM label:

`sudo pvremove --force {{/dev/sdaXY}}`

- Display output in JSON format:

`sudo pvremove --reportformat json {{/dev/sdaXY}}`
```

2024-10-27 16:25 UTC, spageektti approved these changes

2024-10-27 16:25 UTC, spageektti commented on pages/linux/pvremove.md
> +`sudo pvremove --reportformat json {{/dev/sdaXY}}`
```suggestion
`sudo pvremove --verbose {{/dev/sdXY}}`

- Remove a LVM label without asking for confirmation:

`sudo pvremove --yes {{/dev/sdXY}}`

- Forcefully remove a LVM label:

`sudo pvremove --force {{/dev/sdXY}}`

- Display output in JSON format:

`sudo pvremove --reportformat json {{/dev/sdXY}}`
```

2024-10-27 16:31 UTC, merged