!: Update adding missing command list
tldr-pages/tldr pull request #14404
Opened 2024-10-26 20:31 UTC by NOLED-CODE

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-10-27 00:07 UTC, renie requested changes
Just some simple changes on verbal tense.

2024-10-27 00:07 UTC, renie commented on pages.pt_BR/common/!.md
> +- Substituir com o último comando, mas sem o último argumento:
```suggestion
- Substitui com o último comando, mas sem o último argumento:
```

2024-10-27 00:07 UTC, renie commented on pages.pt_BR/common/!.md
> +- Imprimir o último comando que começa com uma string sem executá-lo.:
```suggestion
- Imprime o último comando que começa com uma string sem executá-lo.:
```

2025-01-17 10:13 UTC, Managor commented
@NOLED-CODE Can you finish this pull request?

2025-01-17 20:32 UTC, NOLED-CODE commented
Pls Review the new changes that I made.

2025-01-18 17:32 UTC, Managor approved these changes

2025-02-07 07:01 UTC, merged