windows/get*: add Korean translation
tldr-pages/tldr pull request #14524
Opened 2024-11-01 04:00 UTC by CodePsy-2001

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-02 02:37 UTC, CodePsy-2001 commented
@tldr-bot @sebastiaanspeck There was a typo in the original document, and I submitted a correction.

2024-11-02 07:29 UTC, IMHOJEONG approved these changes

2024-11-02 13:18 UTC, Zamoca42 requested changes

2024-11-02 13:18 UTC, Zamoca42 commented on pages.ko/windows/getmac.md
> +`getmac /s {{호스트명}} /u {{사용자 명}} /p {{비밀번호}}`
```suggestion
`getmac /s {{호스트명}} /u {{사용자명}} /p {{비밀번호}}`
```

2024-11-03 06:14 UTC, Zamoca42 approved these changes

2024-11-03 06:18 UTC, merged