common/v*: add and update Korean translation
tldr-pages/tldr pull request #14557
Opened 2024-11-02 03:25 UTC by CodePsy-2001

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-02 13:10 UTC, Zamoca42 requested changes

2024-11-02 13:10 UTC, Zamoca42 commented on pages.ko/common/vue-build.md
> +`vue build {{파일이름}}`
```suggestion
`vue build {{파일명}}`
```

2024-11-03 06:33 UTC, Zamoca42 approved these changes
LGTM!

2024-11-03 16:20 UTC, IMHOJEONG approved these changes

2024-11-03 17:12 UTC, merged