tldr: update Korean translation, common/t*: add Korean translation
tldr-pages/tldr pull request #14645
Opened 2024-11-05 12:11 UTC by CodePsy-2001

- **common/t*: add Korean translation**
- **tldr: update Korean translation**

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-06 01:08 UTC, CodePsy-2001 commented
I ran a local pull request test, but it's hard to interpret the log. What is the problem with the translation file?

2024-11-07 06:26 UTC, Zamoca42 requested changes

2024-11-07 06:26 UTC, Zamoca42 commented on pages.ko/common/tar.md
> +- 아카이브 [파]일에서 패턴과 일치하는 파일 [추]출:
```suggestion

> 아카이브 유틸리티.
> 종종 `gzip` 또는 `bzip2`와 같은 압축 방법과 결합하여 사용됩니다.
> 더 많은 정보: <https://www.gnu.org/software/tar>.

- 아카이브 생성 후 파일로 저장:

`tar cf {{경로/대상/파일.tar}} {{경로/대상/파일1 경로/대상/파일2 ...}}`

- g[z]ipped 아카이브 생성 후 파일로 저장:

`tar czf {{경로/대상/파일.tar.gz}} {{경로/대상/파일1 경로/대상/파일2 ...}}`

- 디렉토리에서 상대 경로를 사용하여 g[z]ipped (압축된) 아카이브 생성:

`tar czf {{경로/대상/파일.tar.gz}} --directory={{경로/대상/폴더}} .`

- (압축된) 아카이브 파일을 현재 디렉토리에 상세히 추출:

`tar xvf {{경로/대상/원본.tar[.gz|.bz2|.xz]}}`

- (압축된) 아카이브 파일을 대상 디렉토리에 추출:

`tar xf {{경로/대상/원본.tar[.gz|.bz2|.xz]}} --directory={{경로/대상/폴더}}`

- 파일 확장자를 사용하여 압축 프로그램을 자동으로 결정하고 압축 아카이브 생성 후 파일로 저장:

`tar caf {{경로/대상/파일.tar.xz}} {{경로/대상/파일1 경로/대상/파일2 ...}}`

- tar 파일의 내용을 상세히 목록화:

`tar tvf {{경로/대상/원본.tar}}`

- 아카이브 파일에서 패턴과 일치하는 파일 추출:
```

2024-11-07 06:26 UTC, Zamoca42 commented on pages.ko/common/tarsnap.md
> +- 하나 이상의 파일 또는 디렉토리에 대한 백업 아카이브 [생성], 암호화 키와 캐시 디렉토리 지정:
```suggestion
- 하나 이상의 파일 또는 디렉토리에 대한 백업 아카이브 생성, 암호화 키와 캐시 디렉토리 지정:
```

2024-11-07 06:26 UTC, Zamoca42 commented on pages.ko/common/tarsnap.md
> +- 특정 아카이브의 내용을 [상세] 모드로 목록화:
```suggestion
- 특정 아카이브 삭제:

`tarsnap -d --keyfile {{경로/대상/키_파일}} --cachedir {{경로/대상/캐시_디렉토리}} -f {{아카이브_이름}}`

- 특정 아카이브의 내용을 상세 모드로 목록화:
```

2024-11-07 06:26 UTC, Zamoca42 commented on pages.ko/common/transfersh.md
> +`transfersh --name {{파일이름}} {{경로/대상/파일}}`
```suggestion
`transfersh --name {{파일명}} {{경로/대상/파일}}`
```

2024-11-07 06:26 UTC, Zamoca42 commented on pages.ko/common/tuir.md
> +`tuir -s {{서브레디시트_이름}}`
```suggestion
- 서브레딧 열기:

`/{{서브레딧_이름}}`

- 링크 열기:

`o`

- 시작 시 특정 서브레딧 열기:

`tuir -s {{서브레딧_이름}}`
```

2024-11-07 06:26 UTC, Zamoca42 commented on pages.ko/common/twine.md
> +- 지정된 [사]용자 이름과 [비]밀번호로 PyPI에 업로드:
```suggestion
- Test PyPI 저장소에 업로드하여 검증:

`twine upload -r testpypi dist/*`

- 지정된 사용자 이름과 비밀번호로 PyPI에 업로드:
```

2024-11-07 06:26 UTC, Zamoca42 commented on pages.ko/common/twine.md
> +`twine upload -u {{사용자_이름}} -p {{비밀번호}} dist/*`
```suggestion
`twine upload -u {{사용자명}} -p {{비밀번호}} dist/*`
```

2024-11-08 07:11 UTC, Zamoca42 approved these changes

2024-11-09 04:29 UTC, merged