common/s*: add and update Korean translation
tldr-pages/tldr pull request #14666
Opened 2024-11-06 04:24 UTC by CodePsy-2001

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

The `pages.ko/common/scamper.md` document has an `outdated` error, but it's hard to figure out which sentence is in error. I need help.

2024-11-07 00:31 UTC, CodePsy-2001 commented
Why don't we let tldr-bot print out the test results in github issue to the specific command line?

2024-11-07 06:09 UTC, Zamoca42 requested changes

2024-11-07 06:09 UTC, Zamoca42 commented on pages.ko/common/simplehttpserver.md
> +`sudo simplehttpserver -basic-auth {{사용자이름}}:{{비밀번호}} -path {{/var/www/html}} -listen 0.0.0.0:80`
```suggestion
`sudo simplehttpserver -basic-auth {{사용자명}}:{{비밀번호}} -path {{/var/www/html}} -listen 0.0.0.0:80`
```

2024-11-07 06:09 UTC, Zamoca42 commented on pages.ko/common/steamcmd.md
> +`steamcmd +login {{사용자이름}} +app_update {{앱ID}} +quit`
```suggestion
`steamcmd +login {{익명}} +app_update {{앱ID}} +quit`

- 지정된 자격 증명을 사용하여 애플리케이션 설치 또는 업데이트:

`steamcmd +login {{사용자명}} +app_update {{앱ID}} +quit`
```

2024-11-08 07:10 UTC, Zamoca42 approved these changes

2024-11-09 00:54 UTC, IMHOJEONG approved these changes

2024-11-09 01:41 UTC, merged