linux/a*: add and update Korean translation
tldr-pages/tldr pull request #14680
Opened 2024-11-07 02:11 UTC by CodePsy-2001

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-07 03:11 UTC, IMHOJEONG approved these changes
LGTM

2024-11-07 15:23 UTC, Zamoca42 requested changes

2024-11-07 15:23 UTC, Zamoca42 commented on pages.ko/linux/apt-file.md
> +`apt-file {{search|find}} {{partial_path/to/file}}`
```suggestion
`apt-file {{search|find}} {{부분_경로/대상/파일}}`
```

2024-11-07 15:23 UTC, Zamoca42 commented on pages.ko/linux/ark.md
> +`ark --add-to {{경로/대상/압축파일}} {{경로/대상/파일1 경로/대상/파일2 ...}}`
```suggestion
`ark --batch {{경로/대상/압축_파일}}`

- 압축 파일을 특정 디렉토리에 추출:

`ark --batch --destination {{경로/대상/폴더}} {{경로/대상/압축_파일}}`

- 압축 파일이 존재하지 않을 경우 생성하고 특정 파일 추가:

`ark --add-to {{경로/대상/압축_파일}} {{경로/대상/파일1 경로/대상/파일2 ...}}`
```

2024-11-07 15:23 UTC, Zamoca42 commented on pages.ko/linux/atool.md
> +- 현재 디렉토리의 모든 Zip 및 rar 아카이브 추출:
```suggestion

> 다양한 형식의 압축 파일을 관리합니다.
> 더 많은 정보: <https://www.nongnu.org/atool/>.

- Zip 압축 파일의 파일 목록 표시:

`atool --list {{경로/대상/압축_파일.zip}}`

- tar.gz 압축 파일을 새로운 하위 디렉토리(또는 파일이 하나뿐인 경우 현재 디렉토리)에 풀기:

`atool --extract {{경로/대상/압축_파일.tar.gz}}`

- 두 개의 파일로 새로운 7z 압축 파일 생성:

`atool --add {{경로/대상/압축_파일.7z}} {{경로/대상/파일1 경로/대상/파일2 ...}}`

- 현재 디렉토리의 모든 Zip 및 rar 압축 파일 추출:
```

2024-11-08 07:12 UTC, Zamoca42 approved these changes

2024-11-08 07:21 UTC, merged