infection, influx, info, initdb, inkmake, inkscape: add Korean translation
tldr-pages/tldr pull request #14692
Opened 2024-11-07 10:59 UTC by IMHOJEONG

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-07 15:02 UTC, Zamoca42 requested changes

2024-11-07 15:02 UTC, Zamoca42 commented on pages.ko/common/inkscape.md
> +`inkscape {{경로/대상/파일이름.svg}} --select=path123 --verb="{{EditDuplicate;ObjectRotate90;FileSave;FileQuit}}"`
```suggestion
`inkscape {{경로/대상/파일명.svg}}`

- 기본 형식(PNG) 및 기본 해상도(96 DPI)를 사용하여 SVG 파일을 비트맵으로 내보냄:

`inkscape {{경로/대상/파일명.svg}} -o {{경로/대상/파일명.png}}`

- SVG 파일을 600x400 픽셀의 비트맵으로 내보내기 (가로와 세로 사이의 비율 왜곡이 발생할 수 있음):

`inkscape {{경로/대상/파일명.svg}} -o {{경로/대상/파일명.png}} -w {{600}} -h {{400}}`

- SVG 파일의 그림(모든 객체의 경계가 있는 상자)을 비트맵으로 내보냄:

`inkscape {{경로/대상/파일명.svg}} -o {{경로/대상/파일명.png}} -D`

- 해당 ID가 지정된 단일 객체를 비트맵으로 내보냄:

`inkscape {{경로/대상/파일명.svg}} -i {{id}} -o {{object.png}}`

- SVG 문서를 PDF로 내보내고 모든 텍스트를 경로로 변경:

`inkscape {{경로/대상/파일명.svg}} -o {{경로/대상/파일명.pdf}} --export-text-to-path`

- id="path123"로 객체를 복제하고, 복사본을 90도로 회전한 다음, 파일을 저장하고, Inkscape를 종료:

`inkscape {{경로/대상/파일명.svg}} --select=path123 --verb="{{EditDuplicate;ObjectRotate90;FileSave;FileQuit}}"`
```

2024-11-08 05:34 UTC, Zamoca42 approved these changes

2024-11-08 06:54 UTC, CodePsy-2001 approved these changes

2024-11-08 06:54 UTC, merged