systemctl: update Korean translation, linux/s*: add Korean translation
tldr-pages/tldr pull request #14715
Opened 2024-11-08 09:30 UTC by CodePsy-2001

- **linux/p*: add Korean translation**
- **linux/s*: add Korean translation**
- **systemctl: update Korean translation**

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-08 09:33 UTC, CodePsy-2001 commented
force-pushed: linux/p* branch were accidentally included and removed

2024-11-09 08:30 UTC, Zamoca42 requested changes

2024-11-09 08:30 UTC, Zamoca42 commented on pages.ko/linux/semanage.md
The translation format of the description needs to be modified.

2024-11-09 08:30 UTC, Zamoca42 commented on pages.ko/linux/shar.md
> +`shar --archive-name "{{내 파일}}" --cut-mark {{경로/대상/파일1 경로/대상/파일2 ...}} > {{경로/대상/아카이브.sh}}`
```suggestion
`shar --archive-name "{{내_파일}}" --cut-mark {{경로/대상/파일1 경로/대상/파일2 ...}} > {{경로/대상/아카이브.sh}}`
```

2024-11-09 08:30 UTC, Zamoca42 commented on pages.ko/linux/sqfscat.md
> +`sqfscat {{파일시스템.squashfs}} {{파일1 파일2 ...}}`
```suggestion
`sqfscat {{파일_시스템.squashfs}} {{파일1 파일2 ...}}`
```

2024-11-09 08:30 UTC, Zamoca42 commented on pages.ko/linux/sqfstar.md
> +`lz4cat {{아카이브.tar.lz4}} | sqfstar {{파일시스템.squashfs}} -regex "{{정규_표현식}}"`
```suggestion
`sqfstar {{파일_시스템.squashfs}} < {{아카이브.tar}}`

- `gzip`으로 압축된 tar 아카이브에서 특정 알고리즘으로 파일 시스템을 [comp]압축하여 squashfs 파일 시스템 생성:

`zcat {{아카이브.tar.gz}} | sqfstar -comp {{gzip|lzo|lz4|xz|zstd|lzma}} {{파일_시스템.squashfs}}`

- `xz`로 압축된 tar 아카이브에서 일부 파일을 제외하고 squashfs 파일 시스템 생성:

`xzcat {{아카이브.tar.xz}} | sqfstar {{파일_시스템.squashfs}} {{파일1 파일2 ...}}`

- `zstd`로 압축된 tar 아카이브에서 `.gz`로 끝나는 파일을 제외하고 squashfs 파일 시스템 생성:

`zstdcat {{아카이브.tar.zst}} | sqfstar {{파일_시스템.squashfs}} "{{*.gz}}"`

- `lz4`로 압축된 tar 아카이브에서 정규 표현식에 맞는 파일을 제외하고 squashfs 파일 시스템 생성:

`lz4cat {{아카이브.tar.lz4}} | sqfstar {{파일_시스템.squashfs}} -regex "{{정규_표현식}}"`
```

2024-11-11 06:05 UTC, Zamoca42 approved these changes

2024-11-11 06:05 UTC, merged