add-appxpackage : add french translation
tldr-pages/tldr pull request #14806
Opened 2024-11-12 17:22 UTC by Laykon4

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-12 20:23 UTC, noraj requested changes

2024-11-12 20:23 UTC, noraj commented on pages.fr/windows/add-appxpackage.md
> +- Ajouter un paquet d'application :
```suggestion
- Ajoute un paquet d'application :
```

2024-11-12 20:23 UTC, noraj commented on pages.fr/windows/add-appxpackage.md
> +- Ajouter un paquet d'application avec ses dependences:
```suggestion
- Ajoute un paquet d'application avec ses dependences :
```

2024-11-12 20:23 UTC, noraj commented on pages.fr/windows/add-appxpackage.md
> +- Installer une application en utilisant le fichier d'installation de l'application:
```suggestion
- Installe une application en utilisant le fichier d'installation de l'application :
```

2024-11-12 20:23 UTC, noraj commented on pages.fr/windows/add-appxpackage.md
> +- Ajouter un paquet non signé:
```suggestion
- Ajoute un paquet non signé :
```

2024-11-17 15:57 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-11-17 15:58 UTC, merged