fabric: add page
tldr-pages/tldr pull request #14926
Opened 2024-11-21 02:05 UTC by mjherich

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):** v1.4.107

2024-11-21 02:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=14926) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=14926) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=14926) it.</sub>

2024-11-22 18:19 UTC, mjherich commented
@danielmiessler Let me know what you think about this tldr

2024-11-22 23:00 UTC, gutjuri requested changes
Thanks, I have some suggestions.

2024-11-22 23:00 UTC, gutjuri commented on pages/common/fabric.md
> +- Run setup to configure fabric:
```suggestion
- Run the setup to configure fabric:
```

2024-11-22 23:00 UTC, gutjuri commented on pages/common/fabric.md
> +- Run a pattern with specified variables:
```suggestion
- Run a pattern with the specified variables:
```

2024-11-24 02:43 UTC, nelsonfigueroa approved these changes
Hello, thanks for you contribution! While there are some suggestions at the moment, I personally think this PR is good. I will leave it up to others to decide if the suggestions are necessary.

2024-11-24 09:45 UTC, spageektti approved these changes

2024-11-24 10:01 UTC, gutjuri approved these changes

2024-11-24 13:50 UTC, merged