accelerate, acme.sh-dns, ant: add pt_BR translation
tldr-pages/tldr pull request #14924
Opened 2024-11-20 21:30 UTC by victorhtl

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-11-21 18:26 UTC, renie requested changes
Thanks for you contribution @victorhtl !

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/accelerate.md
> +- Printa informações do ambiente:
```suggestion
- Mostra informações do ambiente:
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/accelerate.md
> +- Printa o custo de memória de GPU estimado para rodar um Modelo de Face aumentado com diferentes tipos de dados:
```suggestion
- Mostra o custo de memória de GPU estimado para rodar um Modelo de Face aumentado com diferentes tipos de dados:
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/accelerate.md
> +`accelerate estimate-memory {{name/model}}`
```suggestion
`accelerate estimate-memory {{nome/modelo}}`
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/accelerate.md
> +`accelerate test --config_file {{path/to/config.yaml}}`
```suggestion
`accelerate test --config_file {{caminho/para/config.yaml}}`
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/accelerate.md
> +`accelerate launch {{path/to/script.py}} {{--cpu}}`
```suggestion
`accelerate launch {{caminho/para/script.py}} {{--cpu}}`
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/accelerate.md
> +`accelerate launch {{path/to/script.py}} --multi_gpu --num_machines 2`
```suggestion
`accelerate launch {{caminho/para/script.py}} --multi_gpu --num_machines 2`
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/acme.sh-dns.md
> +- Emite um certificado wildcard (denotado por um asterisco (*)) usando um modo DNS API automático:
```suggestion
- Emite um certificado wildcard (denotado por um asterísco (*)) usando um modo DNS API automático:
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/acme.sh-dns.md
> +`acme.sh --issue --dns {{dns_cf}} --domain {{example.com}} --challenge-alias {{alias-for-example-validation.com}}`
```suggestion
`acme.sh --issue --dns {{dns_cf}} --domain {{example.com}} --challenge-alias {{apelido-para-exemplo-de-validacao.com}}`
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/acme.sh-dns.md
> +- Emite um certificado enquanto desabilita a pesquisa automática de DNS da Cloudflare/google depois que o registro DNS for adicionado, especificando um tempo de espera personalizado em segundos:
```suggestion
- Emite um certificado enquanto desabilita a pesquisa automática de DNS da Cloudflare/Google depois que o registro DNS for adicionado, especificando um tempo de espera personalizado em segundos:
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/ant.md
> +> Apache Ant: compile e administre projetos baseados em Java.
```suggestion
> Apache Ant: compila e administra projetos baseados em Java.
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/ant.md
> +`ant -f {{buildfile.xml}}`
```suggestion
`ant -f {{arquivo_de_build.xml}}`
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/ant.md
> +- Printa informações sobre possíveis alvos para este projeto:
```suggestion
- Mostra informações sobre possíveis alvos para este projeto:
```

2024-11-21 18:26 UTC, renie commented on pages.pt_BR/common/ant.md
> +- Printa informações de debug:
```suggestion
- Mostra informações de debug:
```

2024-11-22 15:04 UTC, renie approved these changes
All good now! Thanks for the contribution

2024-11-26 12:47 UTC, victorhtl commented
@sebastiaanspeck it just coincidence haha I'm another person and, actually, this is my first contribution to an open source project

2024-11-26 13:43 UTC, renie commented
I also had the same though of @sebastiaanspeck . Interesting coincidence!

2024-11-26 15:55 UTC, merged