zpaq: add page
tldr-pages/tldr pull request #15024
Opened 2024-12-02 15:47 UTC by dy-tea

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**
zpaq v7.15

2024-12-02 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=15024) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=15024) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=15024) it.</sub>

2024-12-02 16:00 UTC, spageektti commented on pages/common/zpaq.md
> +`zpaq a -k{{X}} {{path/to/archive.zpaq}} {{path/to/file_or_directory}}`
```suggestion
- Create or add to encrypted archive:

`zpaq a -k{{password}} {{path/to/archive.zpaq}} {{path/to/file_or_directory}}`
```

2024-12-07 13:48 UTC, gutjuri requested changes
Thanks, I have some suggestions!

2024-12-07 13:48 UTC, gutjuri commented on pages/common/zpaq.md
> +> Incremental Journaling Backup Utility and Archiver.
```suggestion
> Incremental journaling backup utility and archiver.
```

2024-12-07 13:48 UTC, gutjuri commented on pages/common/zpaq.md
> +- Create or add to encrypted archive:
```suggestion
- Create or add to an encrypted archive:
```

2024-12-07 13:48 UTC, gutjuri commented on pages/common/zpaq.md
> +- E[x]tract the most recent recent versions of files:
```suggestion
- E[x]tract the most recent versions of files:
```

2024-12-07 13:48 UTC, gutjuri commented on pages/common/zpaq.md
> +- [l]ist or compare external files to archive by dates:
```suggestion
- [l]ist the archive contents:
```

I think this makes it clearer for non-advanced users.

2024-12-07 13:48 UTC, gutjuri commented on pages/common/zpaq.md
> +`zpaq x {{path/to/archive.zpaq}} {{path/to/extract}} -to {{path/to/output}} -until {{YYYY-MM-DD}}`
```suggestion
- E[x]tract the specified files from the archive that are not newer than the specified date:

`zpaq x {{path/to/archive.zpaq}} {{path/in/archive/to/extract}} -to {{path/to/output}} -until {{YYYY-MM-DD}}`
```

2024-12-07 14:10 UTC, dy-tea commented on pages/common/zpaq.md
> +- E[x]tract the most recent recent versions of files:
Wow I'm amazed I missed that

2024-12-07 15:31 UTC, gutjuri approved these changes
Thanks!

2024-12-07 21:10 UTC, spageektti approved these changes
Thanks for your contribution

2024-12-07 21:10 UTC, merged