fd: add Chinese translation
tldr-pages/tldr pull request #15037
Opened 2024-12-04 04:31 UTC by Promix953

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-12-04 05:23 UTC, einverne requested changes
Hi @Promix953  thanks for the new translation. I left a comment for you.

Can you help fix the original English version according to this [guideline](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).

2024-12-04 05:23 UTC, einverne commented on pages.zh/common/fd.md
> +`fd --extension txt`
```suggestion
`fd --extension {{txt}}`
```

2024-12-04 05:23 UTC, einverne commented on pages.zh/common/fd.md
> +`fd "^foo"`
```suggestion
`fd "{{^foo}}"`
```

2024-12-04 06:21 UTC, Promix953 commented
> Hi @Promix953 thanks for the new translation. I left a comment for you.嗨，感谢新的翻译。我为您留下了一条评论。
> 
> Can you help fix the original English version according to this [guideline](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).你能根据这个指南帮助修复原始英文版本吗？

#15038

2024-12-06 00:24 UTC, einverne approved these changes
LGTM.

2024-12-08 08:29 UTC, blueskyson approved these changes

2024-12-08 14:42 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2024-12-08 14:43 UTC, merged