tuc: add page
tldr-pages/tldr pull request #15033
Opened 2024-12-03 17:13 UTC by GregPK

The examples are taken from original repo (https://github.com/riquito/tuc), just a shorter list.

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).

2024-12-07 13:39 UTC, gutjuri requested changes
Thanks! I removed the shell comments that show the commands' outputs -- I don't thinks that we do this in other pages. Apart from that, I added placeholders.

2024-12-07 13:39 UTC, gutjuri commented on pages/common/tuc.md
> +`\n echo "foo bar baz" | tuc -d ' ' -f 3,2,1    # => bazbarfoo`
```suggestion
`echo "foo bar baz" | tuc -d '{{ }}' -f {{3,2,1}}`
```

Why the `\n`?

2024-12-07 13:39 UTC, gutjuri commented on pages/common/tuc.md
> +`echo "foo bar baz" | tuc -d ' ' -r ' ➡ '  # => foo ➡ bar ➡ baz`
```suggestion
- Replace the delimiter `space` with an arrow:

`echo "foo bar baz" | tuc -d ' ' -r ' ➡ '`
```

2024-12-07 13:39 UTC, gutjuri commented on pages/common/tuc.md
> +`echo "foo bar    baz" | tuc -d ' ' -f 2:   # => bar    baz`
```suggestion
- Keep a range of fields:

`echo "foo bar    baz" | tuc -d ' ' -f {{2:}}`
```

2024-12-07 13:39 UTC, gutjuri commented on pages/common/tuc.md
> +`echo "a,b, c" | tuc -e '[, ]+' -f 1,3  # => ac`
```suggestion
- Cut using regular expressions:

`echo "a,b, c" | tuc -e '{{[, ]+}}' -f {{1,3}}`
```

2024-12-07 13:39 UTC, gutjuri commented on pages/common/tuc.md
> +`echo "foo bar baz" | tuc -d ' ' --json     # => ["foo","bar","baz"]`
```suggestion
- Emit JSON output:

`echo "foo bar baz" | tuc -d '{{ }}' --json`
```

2024-12-23 17:05 UTC, spageektti commented on pages/common/tuc.md
> +> A more user-friendly and powerful version of cut with sensible defaults.
```suggestion
> A more user-friendly and powerful version of `cut` with sensible defaults.
```

2024-12-23 17:06 UTC, spageektti commented
Hi. Thanks for your contribution. I wish a wonderful christmas time!

2024-12-23 17:06 UTC, spageektti approved these changes

2024-12-24 09:16 UTC, gutjuri approved these changes

2024-12-30 12:45 UTC, GregPK commented
@sebastiaanspeck Ready. Needed a rebase.

2024-12-30 13:38 UTC, merged