Added docker-context
tldr-pages/tldr pull request #15070
Opened 2024-12-07 17:11 UTC by 7aske

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-12-07 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=15070) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=15070) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=15070) it.</sub>

2024-12-07 19:09 UTC, acuteenvy requested changes
Thanks for your contribution. Please read the [style guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).

2024-12-07 19:09 UTC, acuteenvy commented on pages/common/docker-context.md
> +> Lets you switch between contexts to manage multiple Docker environments.
https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#imperative-mood
> All descriptions must be phrased in the imperative mood.

```suggestion
> Switch between contexts to manage multiple Docker environments.
```

2024-12-07 19:09 UTC, acuteenvy commented on pages/common/docker-context.md
> +`docker context ls`
https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#placeholder-syntax
> User-provided values should use the `{{placeholder}}` syntax in order to allow `tldr` clients to highlight them.

https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#naming
> Use `snake_case` for multi-word placeholders.

```suggestion
- Create a context using a specific Docker endpoint:

`docker context create {{my_context}} --docker "host={{tcp://remote-host:2375}}"`

- Create a context based on the `DOCKER_HOST` environment variable:

`docker context create {{my_context}}`

- Switch to a context:

`docker context use {{my_context}}`

- List all contexts:

`docker context ls`
```

2024-12-08 14:32 UTC, kbdharun approved these changes
LGTM, Welcome to tldr and thanks for your contribution.

2024-12-08 15:26 UTC, acuteenvy approved these changes

2024-12-08 15:26 UTC, merged