pacman-q, pacman-query: add Dutch translation
tldr-pages/tldr pull request #15315
Opened 2024-12-23 11:16 UTC by sebastiaanspeck

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2024-12-23 16:08 UTC, leonvsc requested changes

2024-12-23 16:08 UTC, leonvsc commented on pages.nl/linux/pacman-query.md
> +- Zoek welk pakket een bestand bezig ([o]):
Do we miss something here? It looks like the sentence is not completed.

2024-12-23 16:08 UTC, leonvsc commented on pages.nl/linux/pacman-query.md
> +- Toon information over een geïnstalleerd ([i]) pakket:
```suggestion
- Toon informatie over een geïnstalleerd ([i]) pakket:
```

2024-12-23 17:09 UTC, leonvsc approved these changes

2025-01-01 00:26 UTC, spageektti approved these changes

2025-01-01 00:26 UTC, merged