$: add zh translation
tldr-pages/tldr pull request #15364
Opened 2024-12-27 02:10 UTC by witt-bit

- [✔] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [✔] The page(s) have at most 8 examples.
- [✔] The page description(s) have links to documentation or a homepage.
- [✔] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [✔] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [✔] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2024-12-30 04:42 UTC, blueskyson approved these changes

2025-01-01 02:26 UTC, spageektti approved these changes
Thanks!

2025-01-03 08:27 UTC, P2Tree requested changes

2025-01-03 08:27 UTC, P2Tree commented on pages.zh/common/$.md
> +> 扩展 Bash 变量。
> 展开 Bash 变量。

2025-01-03 08:27 UTC, P2Tree commented on pages.zh/common/$.md
> +- 打印变量：
- 打印变量的值：

2025-01-03 08:27 UTC, P2Tree commented on pages.zh/common/$.md
> +- 使用 `命令` 的输出进行扩展并运行它。与将 `命令` 括在反引号中相同：
- 运行 `命令` 并展开它的输出。与将 `命令` 括在反引号中相同：

2025-01-03 10:47 UTC, witt-bit commented
Updated

2025-01-03 11:19 UTC, P2Tree commented
> @P2Tree I have edited your comments to add "```suggestion". This makes your comment more rich, easily shows the difference and it makes it easy for the author to commit your suggestion.

OK，I will pay attention next.

2025-01-04 02:38 UTC, merged