paste: add zh translation
tldr-pages/tldr pull request #15399
Opened 2024-12-31 08:28 UTC by witt-bit

- [✔] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [✔] The page(s) have at most 8 examples.
- [✔] The page description(s) have links to documentation or a homepage.
- [✔] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [✔] The page(s) follow the [style guide](/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md).
- [✔] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message-and-pr-title).
- **Version of the command being documented (if known):**

2025-01-03 02:00 UTC, P2Tree requested changes

2025-01-03 02:00 UTC, P2Tree commented on pages.zh/common/paste.md
> +- 合并两个文件，交替到新行中：
- 将两个文件中的所有行，交替合并：

2025-01-03 11:17 UTC, P2Tree commented on pages.zh/common/paste.md
> +- 合并两个文件，交替到新行中：
Thanks for notice, I will pay attention.

2025-01-04 02:56 UTC, blueskyson commented on pages.zh/common/paste.md
> +- 将所有行合并为一行，使用tab作为分隔符：
```suggestion
- 将所有行合并为一行，使用 tab 作为分隔符：
```

2025-01-04 02:56 UTC, blueskyson commented on pages.zh/common/paste.md
> +- 并排合并两个文件，每个文件以tab分隔为单独的列：
```suggestion
- 并排合并两个文件，每个文件以 tab 分隔为单独的列：
```

2025-01-06 05:19 UTC, blueskyson approved these changes

2025-01-06 05:21 UTC, merged