cf: add page
tldr-pages/tldr pull request #4284
Opened 2020-08-23 06:13 UTC by waciumawanjohi

Authored-by: Waciuma Wanjohi <code@waciuma.com>

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-08-24 09:34 UTC, owenvoke requested changes
Hi @waciumawanjohi, thanks for the page, it looks great!

Just one minor suggestion to simplify the first example. 👍🏻

2020-08-24 09:34 UTC, owenvoke commented on pages/common/cf.md
> +- Push an app the easiest way, using default settings:
This can probably be simplified to:
```suggestion
- Push an app using the default settings:
```

2020-08-24 21:09 UTC, sbrl approved these changes
Looks ok after @owenvoke's comments are addressed :-)

2020-08-25 16:09 UTC, waciumawanjohi commented
Updated the page. 🙂

2020-08-25 16:21 UTC, owenvoke approved these changes
LGTM!

2020-08-25 20:41 UTC, navarroaxel commented on pages/common/cf.md
> +> More information: <https://docs.cloudfoundry.org/>.
```suggestion
> More information: <https://docs.cloudfoundry.org>.
```

2020-08-25 20:44 UTC, navarroaxel commented on pages/common/cf.md
> +`cf create-service {{service}} {{plan}} {{chosen_service_name}}`
```suggestion
`cf create-service {{service}} {{plan}} {{service_name}}`
```

2020-08-25 20:47 UTC, navarroaxel commented on pages/common/cf.md
> +`cf run-task {{app_name}} {{script_command}} --name {{task_name}}`
Could we enclose {{script_command}} in quotes please?

```suggestion
`cf run-task {{app_name}} "{{script_command}}" --name {{task_name}}`
```

Passing code as a CLI argument may potentially include special characters and more than 1 word, which we want to ensure get passed correctly.

2020-08-25 20:50 UTC, navarroaxel commented on pages/common/cf.md
> +`cf bind-service {{app_name}} {{chosen_service_name}}`
The service is named by the user, `service_name` is not enough clear about that?
```suggestion
`cf bind-service {{app_name}} {{service_name}}`
```

2020-08-28 08:10 UTC, merged