bitwise:  add page
tldr-pages/tldr pull request #4289
Opened 2020-08-24 07:00 UTC by deep5050

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-08-24 07:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4289) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4289) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4289) it.</sub>

2020-08-24 09:42 UTC, owenvoke requested changes
Thanks @deep5050, just a few minor tweaks but it otherwise looks great. 👍🏻

2020-08-24 09:42 UTC, owenvoke commented on pages/linux/bitwise.md
> +- Interactive Mode:
```suggestion
- Run using interactive mode:
```

2020-08-24 09:42 UTC, owenvoke commented on pages/linux/bitwise.md
> +`bitwise 12345`
Just needs token syntax here, and a tweak to use sentence case:

```suggestion
- Convert from decimal:

`bitwise {{12345}}`
```

2020-08-24 09:42 UTC, owenvoke commented on pages/linux/bitwise.md
> +`bitwise 0x563d`
Just needs token syntax here, and a tweak to use sentence case:

```suggestion
- Convert from hexadecimal:

`bitwise {{0x563d}}`
```

2020-08-24 09:42 UTC, owenvoke commented on pages/linux/bitwise.md
> +- C-style Calculation:
```suggestion
- Convert a C-style calculation:
```

2020-08-24 10:09 UTC, owenvoke approved these changes

2020-08-24 21:10 UTC, sbrl approved these changes
Looks ok to me! Thanks, @deep5050 :D

Note that you still need to sign the CLA before we can merge this. Simply click on the link i in the comment left by @CLAassistant above :-)

2020-08-25 02:42 UTC, deep5050 commented
@sbrl done :)

2020-08-30 04:03 UTC, merged