tree: add -C
tldr-pages/tldr pull request #4295
Opened 2020-08-25 21:13 UTC by gfda

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-08-28 08:17 UTC, einverne requested changes
hi @gfda Thank you for the new command. But it seems this page has more than 8 examples. So we cannot accept this submission.

Do you think this command can be merged with other?

2020-08-28 10:33 UTC, navarroaxel commented
Testing the command, looks like we can combine:
```bash
`tree -L {{num}} -C`
```
or
```bash
`tree -a -C`
```

Could you add this to the command description to?
```
> More information: <http://mama.indstate.edu/users/ice/tree/>.
```

2020-08-28 11:38 UTC, gfda commented
Hello @einverne and @navarroaxel, thanks for the review.
I will try to merge with other commands.

2020-08-29 23:20 UTC, einverne approved these changes

2020-08-30 03:59 UTC, merged