btm: add page
tldr-pages/tldr pull request #4300
Opened 2020-08-27 17:37 UTC by pepellou

ibtm is a cross-platform graphical process/system monitor with a
customizable interface and a multitude of features.

It supports Linux, macOS, and Windows.
Inspired by both gtop and gotop.

More info: https://github.com/ClementTsang/bottom

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-08-27 17:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4300) it.</sub>

2020-08-27 17:44 UTC, navarroaxel commented on pages/common/btm.md
> +`btm --dot-marker`
```suggestion
`btm --dot_marker`
```

2020-08-31 00:13 UTC, sbrl requested changes
Thanks for the new page, @pepellou! I've left some comments below for you to review.

2020-08-31 00:13 UTC, sbrl commented on pages/common/btm.md
> +- Show default layout (cpu + memory + temperatures + disk + network + processes):
Perhaps this will read better?
```suggestion
- Show the default layout (cpu, memory, temperatures, disk, network, and processes):
```

2020-08-31 00:13 UTC, sbrl commented on pages/common/btm.md
> +- Enable basic mode, removing charts and condensing data (similar to "top"):
Perhaps this will read better?
```suggestion
- Enable basic mode, removing charts and condensing data (similar to `top`):
```

2020-08-31 00:13 UTC, sbrl commented on pages/common/btm.md
> +- Refresh every 250 milliseconds and show last 30 seconds in charts:
Perhaps this will read better?
```suggestion
- Refresh every 250 milliseconds and show the last 30 seconds in the charts:
```

2020-09-04 22:48 UTC, sbrl approved these changes
Thanks, @pepellou!

2020-09-04 22:49 UTC, merged