xpdf: add page
tldr-pages/tldr pull request #4303
Opened 2020-08-30 18:31 UTC by sahilister

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-08-30 18:35 UTC, sahilister commented
The last example about specifying zoom can also take `page`, `width` or `height` as parameters in addition to percentage values mentioned.

Should It have a additional command added or should it be incorporated in the last command itself?

2020-08-30 19:04 UTC, navarroaxel commented
> The last example about specifying zoom can also take `page`, `width` or `height` as parameters in addition to percentage values mentioned.

Checking the command: `height` is not working as a valid argument for me.

> 
> Should It have a additional command added or should it be incorporated in the last command itself?

I think an extra example saying the user can set initial zoom at page width or full page (or the expression that you like).

```
xpdf -z {{page|width}} {{path/to/file.pdf}}
```

2020-08-31 00:27 UTC, sbrl commented on pages/common/xpdf.md
> +`xpdf {{file.pdf}} {{5}}`
Did you mean to have a space before the colon `:` there?

2020-08-31 00:30 UTC, sbrl requested changes
Thanks for the new page, @sahilister! I've left some comments below for you to review.

2020-08-31 00:30 UTC, sbrl commented on pages/common/xpdf.md
> +- Open PDF file:
Perhaps this will read better?
```suggestion
- Open a PDF file:
```

2020-08-31 00:30 UTC, sbrl commented on pages/common/xpdf.md
> +- Open compressed PDF file:
Perhaps this will read better?
```suggestion
- Open a compressed PDF file:
```

2020-08-31 00:30 UTC, sbrl commented on pages/common/xpdf.md
> +- Open PDF file in fullscreen mode:
Perhaps this will read better?
```suggestion
- Open a PDF file in fullscreen mode:
```

2020-08-31 00:30 UTC, sbrl commented on pages/common/xpdf.md
> +- Specify initial zoom:
Perhaps this will read better?
```suggestion
- Specify the initial zoom:
```

2020-08-31 11:31 UTC, navarroaxel commented on pages/common/xpdf.md
> +`xpdf {{file.pdf}} {{5}}`
You can open more than 1 PDF using this command:
```bash
xpdf 1.pdf 2.pdf
```
You should prefix the page number `:` so the `xpdf` knows is not a file, is a PDF page:

```bash
xpdf 1.pdf :2
```
The `help` of this command:
```bash
$ xpdf --help
xpdf version 4.02
Copyright 1996-2019 Glyph & Cog, LLC
Usage: xpdf [options] [<PDF-file> [:<page> | +<dest>]] ...
```

2020-08-31 11:36 UTC, navarroaxel commented on pages/common/xpdf.md
> +`xpdf -fullscreen {{file.pdf}}`
Plase use `path/to/file.pdf` in all the examples, like:
```suggestion
`xpdf -fullscreen {{path/to/file.pdf}}`
```

2020-08-31 14:53 UTC, navarroaxel commented on pages/common/xpdf.md
> +`xpdf {{file.pdf.tar}}`
```suggestion
`xpdf {{path/to/file.pdf.tar}}`
```

2020-08-31 14:53 UTC, navarroaxel commented on pages/common/xpdf.md
> +`xpdf -z {{75}}% {{file.pdf}}`
```suggestion
`xpdf -z {{75}}% {{path/to/file.pdf}}`
```

2020-08-31 14:56 UTC, sahilister commented
@navarroaxel you're fast, I was going still going through previous requested changes and got the new update requests. :smile:

2020-08-31 14:58 UTC, navarroaxel commented
> @navarroaxel you're fast, I was going still going through previous requested changes and got the new update requests. smile

Sorry, I saw your commits while I was checking another PR. I wanted to be fast because you're focused in this PR right now! 😬

2020-08-31 14:59 UTC, sahilister commented
@navarroaxel about the command which opens two PDFs at once, in my usage, I never had to open two at once. 

So adding that here, I believe is kind of irrevelent.

2020-08-31 14:59 UTC, navarroaxel commented
> @navarroaxel you're fast, I was going still going through previous requested changes and got the new update requests. smile

> @navarroaxel you're fast, I was going still going through previous requested changes and got the new update requests. smile

@sahilister Sorry, I saw your commits while I was checking another PR. I wanted to be fast because you're focused in this PR right now! 😬

2020-08-31 15:01 UTC, navarroaxel commented
> So adding that here, I believe is kind of irrevelent.

@sahilister Yeah, I think is not required here. But I commented that usage to explain why the `:` are required for the `{{page_number}}` argument.

2020-09-04 22:54 UTC, sbrl approved these changes
Looks good to me! I've just fixed a minor grammatical/consistency issue I noticed if you don't mind :-)

Thanks for sticking with the review process!

2020-09-04 22:55 UTC, merged