nodemon: add page
tldr-pages/tldr pull request #4308
Opened 2020-08-31 14:31 UTC by Scaledi

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-08-31 14:37 UTC, navarroaxel commented on pages/common/nodemon.md
> +- Ignore spesific files:
```suggestion
- Ignore specific files:
```

2020-08-31 14:40 UTC, navarroaxel commented on pages/common/nodemon.md
> +> More information: <https://www.npmjs.com/package/nodemon/>.
I think we should use the official website:
```suggestion
> More information: <https://nodemon.io>.
```
or, the official docs site:
```suggestion
> More information: <https://github.com/remy/nodemon#nodemon>.
```

2020-08-31 14:43 UTC, navarroaxel commented on pages/common/nodemon.md
> +`nodemon yournodeargument`
```suggestion
`nodemon {{path/to/file.js}} {{arguments}}`
```

2020-08-31 14:44 UTC, navarroaxel commented on pages/common/nodemon.md
> +- Use any node argument in nodemon:
```suggestion
- Pass arguments to your node application:
```

2020-08-31 14:46 UTC, navarroaxel commented on pages/common/nodemon.md
> +`nodemon --exec "python --verbose" filename.py`
We try to set template to commands instead a specific one.
```suggestion
`nodemon --exec "{{command}}" {{path/to/script_file}}`
```

2020-08-31 14:47 UTC, navarroaxel commented on pages/common/nodemon.md
> +- Monitor non node files:
```suggestion
- Running non-node scripts:
```

2020-08-31 14:48 UTC, navarroaxel commented on pages/common/nodemon.md
> +`nodemon --ignore filename.js`
```suggestion
`nodemon --ignore {{path/to/file_or_directory}}`
```

2020-08-31 14:48 UTC, navarroaxel commented on pages/common/nodemon.md
> +- Watch a spesific file for reloads:
```suggestion
- Watch a spesific file for reloads:
```

2020-08-31 19:05 UTC, Scaledi commented on pages/common/nodemon.md
> +- Watch a spesific file for reloads:
Dont see any changes here

2020-08-31 19:10 UTC, navarroaxel commented on pages/common/nodemon.md
> +- Watch a spesific file for reloads:
updated! sorry.

2020-08-31 19:11 UTC, navarroaxel commented on pages/common/nodemon.md
> +- Running non-node scripts:
Sometimes I forgot the rules too:
```suggestion
- Run non-node scripts:
```

2020-08-31 19:17 UTC, Scaledi commented
@navarroaxel should all be fixed

2020-08-31 19:19 UTC, navarroaxel commented
> @navarroaxel should all be fixed

Thanks @Scaledi ! we should wait the feedback from another reviewer.

2020-08-31 19:28 UTC, Scaledi commented
> > @navarroaxel should all be fixed
> 
> Thanks @Scaledi ! we should wait the feedback from another reviewer.

cool. any reason why?
just trying to figure out how this works.... don't mean that in a rude way! just tryen to learn.

2020-08-31 19:37 UTC, navarroaxel commented
> > > @navarroaxel should all be fixed
> > 
> > 
> > Thanks @Scaledi ! we should wait the feedback from another reviewer.
> 
> cool. any reason why?
> just trying to figure out how this works.... don't mean that in a rude way! just tryen to learn.

np, we have a [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md) and the rule is `2 approved reviews by maintainers` before merge. Also I'm from :argentina: and English is not my mother language. So, I could be wrong about grammar.

2020-08-31 19:41 UTC, Scaledi commented
> > > > @navarroaxel should all be fixed
> > > 
> > > 
> > > Thanks @Scaledi ! we should wait the feedback from another reviewer.
> > 
> > 
> > cool. any reason why?
> > just trying to figure out how this works.... don't mean that in a rude way! just tryen to learn.
> 
> np, we have a [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md) and the rule is `2 approved reviews by maintainers` before merge. Also I'm from 🇦🇷 and English is not my mother language. So, I could be wrong about grammar.

see my edit... just got to the page before you reviewed it!

2020-09-04 23:04 UTC, sbrl requested changes
Thanks for the new page, @Scaledi! I've left some comments below for you to review.

Welcome to tldr pages :slightly_smiling_face:

2020-09-05 03:22 UTC, navarroaxel commented on pages/common/nodemon.md
> +`nodemon --inspect filename.js`
Just 1 slash:
```suggestion
`nodemon --inspect {{path/to/file.js}}`
```

2020-09-05 14:36 UTC, Scaledi commented
> Thanks for the new page, @Scaledi! I've left some comments below for you to review.
> 
> Welcome to tldr pages 🙂

Finished it all :) hope its better now!

2020-09-08 23:45 UTC, sbrl approved these changes
Thanks, @Scaledi :smiley_cat:

2020-09-08 23:45 UTC, merged