docker-system: add page
tldr-pages/tldr pull request #4310
Opened 2020-09-01 21:14 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-09-04 23:18 UTC, sbrl requested changes
Thanks for the new page, @navarroaxel! I've left some comments below for you to review.

2020-09-04 23:18 UTC, sbrl commented on pages/common/docker-system.md
> +# docker-system
Rogue dash here?
```suggestion
# docker system
```

2020-09-04 23:18 UTC, sbrl commented on pages/common/docker-system.md
> +- Show detailed information on space usage:
This might be better if it's consistent with the previous example?
```suggestion
- Show detailed information on disk usage:
```

2020-09-08 23:44 UTC, sbrl approved these changes

2020-09-10 01:29 UTC, einverne approved these changes
LGTM.

2020-09-10 01:29 UTC, merged