cargo-clippy: add page
tldr-pages/tldr pull request #4316
Opened 2020-09-05 20:01 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-09-09 00:13 UTC, sbrl requested changes
Thanks for the new page, @navarroaxel! I've left some comments below for you to review.

2020-09-09 00:13 UTC, sbrl commented on pages/common/cargo-clippy.md
> +- Run checks over your code:
We try to avoid `you` / `your` here (i.e. the 2nd person). What about this?
```suggestion
- Run checks over the code in the current directory:
```

2020-09-09 00:13 UTC, sbrl commented on pages/common/cargo-clippy.md
> +- Fail command when encountering warnings:
This sounds a bit odd. What about this instead?
```suggestion
- Treat warnings as errors:
```

2020-09-11 00:32 UTC, schneiderl approved these changes

2020-09-12 20:06 UTC, sbrl approved these changes
Thanks, @navarroaxel :heart:

2020-09-12 20:06 UTC, merged