delta: add page
tldr-pages/tldr pull request #4317
Opened 2020-09-05 20:34 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-09-09 00:19 UTC, sbrl requested changes
Thanks for the new page, @navarroaxel! I've left some comments below for you to review.

2020-09-09 00:19 UTC, sbrl commented on pages/common/delta.md
> +- Compare files or directories, showing the difference side by side:
Very minor thing, but this reads better:
```suggestion
- Compare files or directories, showing the differences side by side:
```

2020-09-09 00:19 UTC, sbrl commented on pages/common/delta.md
> +- Compare files or directories, ignoring any settings from git config:
Perhaps this will read better?
```suggestion
- Compare files or directories, ignoring any git configuration settings:
```

2020-09-09 00:19 UTC, sbrl commented on pages/common/delta.md
> +- Display the active values for all Delta options:
Perhaps this will read better?
```suggestion
- Display the current settings:
```

2020-09-09 00:43 UTC, sbrl approved these changes
Thanks, @navarroaxel!

2020-09-11 03:52 UTC, einverne approved these changes
LGTM.

2020-09-11 11:00 UTC, merged