dotnet-publish: add page
tldr-pages/tldr pull request #4321
Opened 2020-09-06 21:01 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-09-09 00:21 UTC, sbrl requested changes
Thanks for the new page, @navarroaxel! I've left some comments below for you to review.

2020-09-09 00:21 UTC, sbrl commented on pages/common/dotnet-publish.md
> +- Compile a .NET project without restoring the dependencies:
Perhaps this will read better?
```suggestion
- Compile a .NET project without restoring dependencies:
```

2020-09-09 00:21 UTC, sbrl commented on pages/common/dotnet-publish.md
> +- Compile a .NET project specifying the output directory:
Perhaps this will read better?
```suggestion
- Specify the output directory:
```

2020-09-09 00:44 UTC, sbrl approved these changes
Thanks, @navarroaxel - you've really been working hard at creating new pages recently I've noticed :D

2020-09-09 01:06 UTC, navarroaxel commented
> Thanks, @navarroaxel - you've really been working hard at creating new pages recently I've noticed :D

lol, I have a kind of ToDo list, and I don't found pages for the commands that I use and I learn in the process.

2020-09-11 00:33 UTC, schneiderl approved these changes

2020-09-11 00:33 UTC, schneiderl commented
LGTM

2020-09-11 00:33 UTC, merged