fix document style
tldr-pages/tldr pull request #4328
Opened 2020-09-09 08:34 UTC by hellojukay

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-09-09 08:48 UTC, hellojukay commented
It may be a mistake


![image](https://user-images.githubusercontent.com/10371891/92576417-16e37400-f2bc-11ea-9fb3-975be00e986b.png)

2020-09-09 10:31 UTC, navarroaxel requested changes
Hi @hellojukay, thanks for your contribution! I made a comment.

2020-09-09 10:31 UTC, navarroaxel commented on pages/common/ansible-playbook.md
> +`ansible-playbook {{playbook}} --tags tag1,tag2`
We need the `{{}}` for placeholders but I think is good explain is a comma separated list of tags. Maybe:
```suggestion
`ansible-playbook {{playbook}} --tags {{tag1,tag2}}`
```

2020-09-10 10:57 UTC, navarroaxel approved these changes

2020-09-11 00:35 UTC, schneiderl approved these changes

2020-09-11 03:54 UTC, einverne approved these changes

2020-09-11 03:55 UTC, merged