cargo-rustc: add page
tldr-pages/tldr pull request #4336
Opened 2020-09-14 00:14 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-09-15 16:47 UTC, mebeim requested changes
Thank you for the page @navarroaxel :) just some minor nitpicks below.

2020-09-15 16:47 UTC, mebeim commented on pages/common/cargo-rustc.md
> +- Build the package or packages defined by the `Cargo.toml` manifest file in the local path:
```suggestion
- Build the package or packages defined by the `Cargo.toml` manifest file in the current working directory:
```

2020-09-15 16:47 UTC, mebeim commented on pages/common/cargo-rustc.md
> +- Compile with size optimization:
```suggestion
- Compile with [s]ize optimization (`z` also turns off loop vectorization):
```

2020-09-15 16:47 UTC, mebeim commented on pages/common/cargo-rustc.md
> +> Compile a package, and pass extra options to the compiler.
```suggestion
> Compile a Rust package, and pass extra options to the compiler.
```

2020-09-15 16:59 UTC, mebeim approved these changes

2020-09-22 16:56 UTC, sbrl approved these changes
Thanks, @navarroaxel!

2020-09-22 16:56 UTC, merged