docker-rmi: add page
tldr-pages/tldr pull request #4339
Opened 2020-09-14 01:02 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-09-15 01:23 UTC, einverne reviewed
@navarroaxel I left a comment for you to take a look.

2020-09-15 01:23 UTC, einverne commented on pages/common/docker-rmi.md
> +> Run a command in a new Docker container.
Is this description right?

2020-09-15 01:32 UTC, navarroaxel commented on pages/common/docker-rmi.md
> +> Run a command in a new Docker container.
Nop, fixed @einverne !

2020-09-15 16:50 UTC, mebeim requested changes
Thank you @navarroaxel 😁 I've got a couple of suggestions below, other than that looks good.

2020-09-15 16:50 UTC, mebeim commented on pages/common/docker-rmi.md
> +- Remove one or more space-separated images:
```suggestion
- Remove one or more images given their names:
```
Clearer.

2020-09-15 16:50 UTC, mebeim commented on pages/common/docker-rmi.md
> +`docker rmi {{image(s)}}`
```suggestion
`docker rmi {{image1 image2 ...}}`
```
We usually prefer this for for multiple arguments.

2020-09-15 16:50 UTC, mebeim commented on pages/common/docker-rmi.md
> +- Remove an image without delete untagged parents:
```suggestion
- Remove an image without deleting untagged parents:
```
Typo.

2020-09-15 17:01 UTC, mebeim approved these changes
Sweet!

2020-09-18 05:35 UTC, einverne approved these changes
Great!

2020-09-18 05:35 UTC, merged