plutil: add page
tldr-pages/tldr pull request #4343
Opened 2020-09-15 13:25 UTC by mflint

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-09-15 13:52 UTC, navarroaxel requested changes
Hey @mflint, Thanks for your submission!

I made some comments

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +> View, convert, validate, or edit property list ("plist") files.
Note: I found some man pages like https://www.theiphonewiki.com/wiki/Plutil#Apple.27s_plutil but is not synced with the mac options.

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +`plutil -p {{file1.plist}} {{file2.plist}}`
We use this format:
```suggestion
`plutil -p {{path/to/file1.plist}} {{path/to/file2.plist}}`
```

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +`plutil -convert {{xml1|binary1|json|swift|objc}} {{file.plist}} -o {{new_file.plist}}`
```suggestion
`plutil -convert {{xml1|binary1|json|swift|objc}} {{path/to/file.plist}} -o {{path/to/new_file.plist}}`
```

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +`plutil -convert {{xml1|binary1|json|swift|objc}} {{file.plist}} -o -`
```suggestion
`plutil -convert {{xml1|binary1|json|swift|objc}} {{path/to/file.plist}} -o -`
```

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +- Convert a single plist file to a different format, writing to stdout:
```suggestion
- Convert a plist file to a different format, writing to `stdout`:
```

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +- Convert plist files to binary format, overwriting the original files in-place:
```suggestion
- Convert one or more space-separated plist files to binary format, overwriting the original files in-place:
```

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +- Convert plist files to XML format, overwriting the original files in-place:
```suggestion
- Convert one or more space-separated plist files to XML format, overwriting the original files in-place:
```

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +- Convert a single plist file to a different format, writing to a new file:
```suggestion
- Convert a plist file to a different format, writing to a new file:
```

2020-09-15 13:52 UTC, navarroaxel commented on pages/osx/plutil.md
> +- Dump the contents of plist files in human-readable format:
Maybe this description is more readable
```suggestion
- Display the contents of one or more space-separated plist files in human-readable format:
```

2020-09-16 07:13 UTC, mflint commented
Thank-you for your suggestions @navarroaxel. I'm not sure that "space separated" is needed, as this would violate the guidance to "avoid explaining general UNIX concepts that could apply to any command". But the rest is great - thank-you!

2020-09-16 10:28 UTC, navarroaxel commented
> Thank-you for your suggestions @navarroaxel. I'm not sure that "space separated" is needed, as this would violate the guidance to "avoid explaining general UNIX concepts that could apply to any command". But the rest is great - thank-you!

I'm not sure, several pages say that. maybe @sbrl or @mebeim could check this

2020-09-16 10:28 UTC, navarroaxel approved these changes

2020-09-16 11:15 UTC, mebeim commented
Hi there @navarroaxel thanks for the ping. I think there is no problem if we avoid saying "space separated" when it's already obvious from the example, I.E. the example contains `{{file1 file2 ...}}`. We prefer using `{{file1 file2 ...}}` instead of `{{file1}} {{file2}}` in such cases (or basically almost any case where the descriptions applies to "one or more files"). Same goes for `{{path/to/file1.plist}} {{path/to/file1.plist}}`, you can just make that `{{file1.plist file2.plist ...}}`. The `path/to/file` form is preferred when there is only one file or two different files with different meanings (e.g. one input and one output).

2020-09-16 11:18 UTC, mebeim requested changes
Suggestions from my above comment.

2020-09-16 11:18 UTC, mebeim commented on pages/osx/plutil.md
> +`plutil -p {{path/to/file1.plist}} {{path/to/file2.plist}}`
```suggestion
`plutil -p {{file1.plist file2.plist ...}}`
```

2020-09-16 11:18 UTC, mebeim commented on pages/osx/plutil.md
> +`plutil -convert xml1 {{path/to/file1.plist}} {{path/to/file2.plist}}`
```suggestion
`plutil -convert xml1 {{file1.plist file2.plist ...}}`
```

2020-09-16 11:18 UTC, mebeim commented on pages/osx/plutil.md
> +`plutil -convert binary1 {{path/to/file1.plist}} {{path/to/file2.plist}}`
```suggestion
`plutil -convert binary1 {{file1.plist file2.plist ...}}`
```

2020-09-16 12:23 UTC, mflint commented
Thank-you for the feedback @mebeim :)

2020-09-16 13:39 UTC, mebeim approved these changes

2020-09-16 13:40 UTC, merged