New page: Flameshot.md
tldr-pages/tldr pull request #4361
Opened 2020-09-26 15:09 UTC by jtm-lis

kindly translated by Andrew.

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-09-26 21:12 UTC, navarroaxel requested changes
Hey @jtm-lis, I left some comments to follow the guidelines.

2020-09-26 21:12 UTC, navarroaxel commented on pages.zh/linux/flameshot.md
> +# 火焰弹
```suggestion
# flameshot
```

2020-09-26 21:12 UTC, navarroaxel commented on pages.zh/linux/flameshot.md
> +带有gui界面的Screenshot工具，支持基本的图像编辑，例如文本，形状，颜色和imgur。更多信息 https://flameshot.js.org
```suggestion
带有gui界面的Screenshot工具，支持基本的图像编辑，例如文本，形状，颜色和imgur。更多信息: <https://flameshot.js.org>
```

2020-09-27 13:09 UTC, jtm-lis commented on pages.zh/linux/flameshot.md
> +# 火焰弹
Okay thank you sorry about that!

2020-09-27 13:10 UTC, jtm-lis commented on pages.zh/linux/flameshot.md
> +带有gui界面的Screenshot工具，支持基本的图像编辑，例如文本，形状，颜色和imgur。更多信息 https://flameshot.js.org
Sorry I missed that. Thank you!

2020-09-27 19:33 UTC, navarroaxel approved these changes
Thanks @jtm-lis!

2020-09-29 10:40 UTC, sbrl requested changes
Thanks for the translation, @jtm-lis! I've left some comments below for you to review.

Looks like some wires have been crossed with respect to the syntax here - I've left some comments below to correct the issues. The syntax for a tldr page is quite specific - try looking at the syntax in the English version of this page.

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +带有gui界面的Screenshot工具，支持基本的图像编辑，例如文本，形状，颜色和imgur。更多信息: <https://flameshot.js.org>
Missing syntax here
```suggestion
> 带有gui界面的Screenshot工具，支持基本的图像编辑，例如文本，形状，颜色和imgur。更多信息: <https://flameshot.js.org>.
```

The `> ` indicates a blockquote. The full-stop at the end is required by the linter (unfortunately the linter was implemented before multiple languages were supported by tldr-pages).

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +flameshot launcher
Missing code block syntax.
```suggestion
`flameshot launcher`
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +通过单击并拖动来截取屏幕截图:
Missing `-` dash for a bullet point here
```suggestion
- 通过单击并拖动来截取屏幕截图:
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +- flameshot gui
Rogue dash here, and missing code block syntax.
```suggestion
`flameshot gui`
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +全屏截图:
Same here.
```suggestion
- 全屏截图:
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +- flameshot full
Same here.
```suggestion
`flameshot full`
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +将保存屏幕快照的路径设置为:
Same here.
```suggestion
- 将保存屏幕快照的路径设置为:
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +- flameshot full --path {{path/to/directory}}
Same here.
```suggestion
`flameshot full --path {{path/to/directory}}`
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +将屏幕截图延迟N毫秒，然后输出到剪贴板:
Same here.
```suggestion
- 将屏幕截图延迟N毫秒，然后输出到剪贴板:
```

2020-09-29 10:40 UTC, sbrl commented on pages.zh/linux/flameshot.md
> +- flameshot full --delay {{2000}} --clipboard
Perhaps this will read better?
```suggestion
`flameshot full --delay {{2000}} --clipboard`
```

2020-09-29 12:47 UTC, jtm-lis commented
@sbrl  Hey I feel really bad, I submitted this late at night before bed, and didn't figure I would of caused such strife.

Anyway next up is French, so that one will be done right.

2020-10-01 14:22 UTC, jtm-lis commented
Reping @sbrl 

Please review the above, let me know if this reping is not needed and / or welcome. I figured you took a glance and left to more urgent pastures as often happens to me.

2020-10-01 20:07 UTC, sbrl approved these changes
Not a problem at all, @jtm-lis! I'm happy to help :-)

The extra ping doesn't actually have any effect - I get around to my GitHub notification once every few days :-)

Anyway, this looks fine to me now! Don't speak the language, ofo course :P

2020-10-01 20:07 UTC, sbrl approved these changes

2020-10-01 20:07 UTC, merged