dua: add page
tldr-pages/tldr pull request #4393
Opened 2020-10-01 12:38 UTC by thamaraiselvam

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-01 13:35 UTC, navarroaxel requested changes
Hey @thamaraiselvam, nice command! I left some comments

2020-10-01 13:35 UTC, navarroaxel commented on pages/common/dua.md
> +`dua --format {{format}}`
The help says this is all the possible options and case insensitive:
```suggestion
`dua --format {{metric|binary|bytes|GB|GiB|MB|MiB}}`
```

2020-10-01 13:35 UTC, navarroaxel commented on pages/common/dua.md
> +`dua --threads {{threads-count}}`
just `count` is ok
```suggestion
`dua --threads {{count}}`
```

2020-10-01 13:35 UTC, navarroaxel commented on pages/common/dua.md
> +- Control number of threads to be used:
```suggestion
- Set the number of threads to be used:
```

2020-10-01 13:35 UTC, navarroaxel commented on pages/common/dua.md
> +`dua {{directory}}`
we use this format for paths:
```suggestion
`dua {{path/to/directory}}`
```

2020-10-05 12:20 UTC, thamaraiselvam commented
@navarroaxel Updated changes

2020-10-05 12:21 UTC, navarroaxel approved these changes

2020-10-05 15:15 UTC, sbrl approved these changes
Thanks, @thamaraiselvam :slightly_smiling_face:

2020-10-05 15:15 UTC, merged