kind: add page
tldr-pages/tldr pull request #4394
Opened 2020-10-01 13:22 UTC by thamaraiselvam

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-01 20:03 UTC, sbrl requested changes
Thanks for the new page, @thamaraiselvam! I've left some comments below for you to review.

2020-10-01 20:03 UTC, sbrl commented on pages/common/kind.md
> +> Kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.
Maybe we could have this more concise?
```suggestion
> Tool for running local Kubernetes clusters using Docker container "nodes".
> Designed for testing Kubernetes itself, but may be used for local development or continuous integration.
```

2020-10-01 20:03 UTC, sbrl commented on pages/common/kind.md
> +`kind get clusters`
How does one determine which one to fetch? If it's by the keyword there, what about this?
```suggestion
- Get details about clusters, nodes, or the kubeconfig:

`kind get {{clusters|nodes|kubeconfig}}`
```

2020-10-01 20:03 UTC, sbrl commented on pages/common/kind.md
> +`kind export logs`
Same here.
```suggestion
- Export the kubeconfig or the logs:

`kind export {{kubeconfig|logs}}`
```

2020-10-05 12:30 UTC, thamaraiselvam commented
@sbrl updated changes

2020-10-05 15:16 UTC, sbrl approved these changes

2020-10-06 11:25 UTC, navarroaxel approved these changes

2020-10-06 11:25 UTC, merged