grex: add command
tldr-pages/tldr pull request #4396
Opened 2020-10-01 16:15 UTC by NanthR

Resolve #4245

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-01 16:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4396) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4396) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4396) it.</sub>

2020-10-01 20:10 UTC, sbrl requested changes
Thanks for the new page, @NanthR! I've left some comments below for you to review.

2020-10-01 20:10 UTC, sbrl commented on pages/common/grex.md
> +- Simple regex generation:
Perhaps this will read better?
```suggestion
- Generate a simple regular expression:
```

2020-10-01 20:10 UTC, sbrl commented on pages/common/grex.md
> +- Case insensitive regex generation:
Perhaps this will read better?
```suggestion
- Generate a case-insensitive regex:
```

2020-10-02 05:09 UTC, NanthR commented
Yup. That wording definitely reads better. Let me know if there is anything more you would like me to change.

2020-10-02 11:00 UTC, navarroaxel approved these changes

2020-10-02 19:25 UTC, sbrl approved these changes

2020-10-02 19:25 UTC, sbrl commented
Thanks, @NanthR!

2020-10-02 19:26 UTC, merged