nativefier: add German translation
tldr-pages/tldr pull request #4405
Opened 2020-10-01 21:52 UTC by ProfileID

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

Added German translation to nativefier.

2020-10-02 10:33 UTC, navarroaxel requested changes
Hey @ProfileID, thanks for your submission. I left a comment.

2020-10-02 10:33 UTC, navarroaxel commented on pages.de/common/nativefier.md
> +> Weitere Informationen <https://github.com/jiahaog/nativefier>.
The `exa` page use `Mehr`. And you missed the `:`
```suggestion
> Mehr Informationen: <https://github.com/jiahaog/nativefier>.
```

2020-10-02 19:13 UTC, sbrl reviewed
Thanks for the new page, @ProfileID! I've left a comment below for you to review.

2020-10-02 19:13 UTC, sbrl commented on pages.de/common/nativefier.md
> +`nativefier --Name {{Name}} {{URL}}`
I think we have a casing issue with the argument here. The original page uses `--name`, but here we have `--Name`?

2020-10-03 13:40 UTC, navarroaxel approved these changes

2020-10-03 14:36 UTC, schneiderl approved these changes
Do not know the language but seems good to me.

2020-10-05 13:59 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks, @ProfileID  :slightly_smiling_face:

2020-10-05 13:59 UTC, merged