openssl: add prime examples
tldr-pages/tldr pull request #4422
Opened 2020-10-02 17:37 UTC by IacobusKopiirefuto

Added two command for prime numbers. One generates a prime number, the other checks if given number is prime.

**Rational for exceeding 8 examples limit**:
I'm aware that this tldr page already has 8 examples, however all current examples are related to certificates. Direct generation of prime numbers using cryptographically secure methods is also a useful, even if it is just a niche function of openssl.

- [ ] The page has 8 or fewer examples.
- [- ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [-] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2020-10-02 17:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4422) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4422) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4422) it.</sub>

2020-10-02 20:05 UTC, sbrl commented
Hey there, @IacobusKopiirefuto! Ah, I totally see the predicament here. What about writing a page dedicated to the `prime` subcommand? We've done this before for other commands - for example `git merge`, and `docker ps`.

There are far too many uses for `openssl` to document them all in a single tldr page, so I suggest we refactor all the existing examples out into dedicated pages for each of the subcommands, and rewrite the `openssl` page to be a generic page for getting started with the `openssl` CLI tool.

2020-10-10 09:10 UTC, IacobusKopiirefuto commented
> What about writing a page dedicated to the `prime` subcommand? We've done this before for other commands - for example `git merge`, and `docker ps`.

@sbrl the problem is that `prime` subcommands doesn't have really that much options to fill its own page. It would be possible, but then it would just sort of duplicate its own manpage `man openssl prime`.

It might make more sense either to:
1. Create a page dedicated to `s_client` or `x509`. They might have more interesting option that could be mentioned. This would create space for the two `prime` examples on the main `openssl` page.
2. Exceed the tldr example limit just by one and only include the command for generating primes `openssl prime -generate -bits 2048 -hex`, as this command is probably more useful from the two commands that I wanted to include (the other was just checking if number is prime or not).

2020-10-12 21:06 UTC, sbrl commented
Ah, I see. While that's not necessarily a problem (eventually it would be awesome to have pages for all the openssl subcommands :D), I can see your point there.

Let's go with Option 1 there - it sounds like a good idea. Feel free to either add those pages to this PR or to open a new one for them after this one is merged.

2020-11-29 05:55 UTC, navarroaxel requested changes

2020-11-29 05:55 UTC, navarroaxel commented on pages/common/openssl.md
> +`openssl prime {{number}}`
```suggestion
```

2020-11-29 05:58 UTC, navarroaxel approved these changes

2020-12-04 18:59 UTC, sbrl approved these changes
Just tweaked the grammar a bit, and I think it's good to go!

Thanks to @IacobusKopiirefuto for the original PR, and @navarroaxel for tidying it up :slightly_smiling_face:

2020-12-04 18:59 UTC, sbrl commented
Uh oh, looks like there's a conflict preventing a merge :thinking:

2020-12-04 20:11 UTC, merged