apt*: add French translation
tldr-pages/tldr pull request #4441
Opened 2020-10-03 19:17 UTC by bbonnin

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-03 19:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4441) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4441) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4441) it.</sub>

2020-10-03 19:32 UTC, navarroaxel approved these changes

2020-10-04 14:43 UTC, Linkid requested changes
:+1:

2020-10-04 14:43 UTC, Linkid commented on pages.fr/linux/apt-file.md
> +- Énumére le contenu d'un paquet spécifique:
It is « Énum**è**re » ;)

2020-10-04 15:02 UTC, schneiderl approved these changes
Do not know the language but syntax-wise it looks good.

2020-10-05 05:42 UTC, bbonnin commented on pages.fr/linux/apt-file.md
> +- Énumére le contenu d'un paquet spécifique:
Oops... Fixed.

2020-10-05 10:22 UTC, merged