maim: add page
tldr-pages/tldr pull request #4468
Opened 2020-10-04 07:45 UTC by IDF31

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-10-04 07:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4468) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4468) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4468) it.</sub>

2020-10-04 13:34 UTC, navarroaxel commented on pages/linux/maim.md
> +> Screenshot utility: <https://github.com/naelstrof/maim>.
```suggestion
> Screenshot utility.
> More information: <https://github.com/naelstrof/maim>.
```

2020-10-04 13:34 UTC, navarroaxel commented on pages/linux/maim.md
> +`maim path/to/screenshot.png`
```suggestion
`maim {{path/to/screenshot.png}}`
```

2020-10-04 13:34 UTC, navarroaxel commented on pages/linux/maim.md
> +`maim --select path/to/screenshot.png`
```suggestion
`maim --select {{path/to/screenshot.png}}`
```

2020-10-04 13:34 UTC, navarroaxel commented on pages/linux/maim.md
> +`maim --window $(xdotool getactivewindow) path/to/screenshot.png`
```suggestion
`maim --window $(xdotool getactivewindow) {{path/to/screenshot.png}}`
```

2020-10-05 11:05 UTC, navarroaxel reviewed
Hey @IDF31, this should work, but looks we have an issue with the line feed in this file :thinking:

2020-10-05 11:05 UTC, navarroaxel commented on pages/linux/maim.md
> +> More information: <https://github.com/naelstrof/maim>.
```suggestion
> Screenshot utility.
> More information: <https://github.com/naelstrof/maim>.
```

2020-10-05 11:17 UTC, IDF31 commented on pages/linux/maim.md
> +> More information: <https://github.com/naelstrof/maim>.
Thanks I'll try, wasn't sure what was going on :P

2020-10-05 11:42 UTC, navarroaxel commented on pages/linux/maim.md
> +- Capture a screenshot of the current active window(requires xdotool):
```suggestion
- Capture a screenshot of the current active window (requires xdotool):
```

2020-10-05 11:42 UTC, navarroaxel commented on pages/linux/maim.md
> +- Capture a screenshot and save it as "path/to/screenshot.png":
Maybe this is better:
```suggestion
- Capture a screenshot and save it in the given path:
```

2020-10-21 10:51 UTC, navarroaxel commented
@sbrl, @owenvoke: could you please review?

2020-10-24 12:30 UTC, sbrl requested changes
Just a pair of minor comments :slightly_smiling_face:

2020-10-24 12:30 UTC, sbrl commented on pages/linux/maim.md
> +- Capture a screenshot of the current active window (requires xdotool):
Perhaps this will read better?
```suggestion
- Capture a screenshot of the current active window (requires `xdotool`):
```

2020-10-24 12:30 UTC, sbrl commented on pages/linux/maim.md
> +- Capture a screenshot and save it in the given path "path/to/screenshot.png":
Perhaps this will read better?
```suggestion
- Capture a screenshot and save it to the given path:
```

2020-10-24 21:22 UTC, navarroaxel approved these changes

2020-10-28 17:30 UTC, sbrl approved these changes
Thanks, @IDF31!

2020-10-28 17:30 UTC, merged