aws-vault: add page
tldr-pages/tldr pull request #4471
Opened 2020-10-04 10:26 UTC by anaynayak

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-04 10:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4471) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4471) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4471) it.</sub>

2020-10-04 13:30 UTC, navarroaxel approved these changes

2020-10-04 20:09 UTC, owenvoke requested changes
LGTM! Just one minor change to add additional token syntax.

2020-10-04 20:09 UTC, owenvoke commented on pages/common/aws-vault.md
> +`aws-vault exec {{profile}} -- aws s3 ls`
```suggestion
`aws-vault exec {{profile}} -- {{aws s3 ls}}`
```

2020-10-05 02:57 UTC, anaynayak commented on pages/common/aws-vault.md
> +`aws-vault exec {{profile}} -- aws s3 ls`
thanks. fixed.

2020-10-05 07:15 UTC, owenvoke approved these changes
LGTM, thank you!

2020-10-05 08:52 UTC, merged