pipx: add page
tldr-pages/tldr pull request #4477
Opened 2020-10-04 14:51 UTC by anaynayak

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-04 18:51 UTC, navarroaxel requested changes
Hey @anaynayak, thanks for your submission, I left some comments.

2020-10-04 18:51 UTC, navarroaxel commented on pages/common/pipx.md
> +`pipx run pycowsay moo`
```suggestion
`pipx run {{pycowsay}} {{moo}}`
```

2020-10-04 18:51 UTC, navarroaxel commented on pages/common/pipx.md
> +`pipx run --spec httpx-cli httpx http://www.github.com`
```suggestion
`pipx run --spec {{httpx-cli}} {{httpx}} {{http://www.github.com}}`
```

2020-10-05 02:55 UTC, anaynayak commented on pages/common/pipx.md
> +`pipx run pycowsay moo`
Thanks. Fixed it.

2020-10-05 02:55 UTC, anaynayak commented on pages/common/pipx.md
> +`pipx run --spec httpx-cli httpx http://www.github.com`
Thanks. Fixed it.

2020-10-05 08:53 UTC, owenvoke approved these changes

2020-10-05 10:33 UTC, navarroaxel approved these changes

2020-10-05 11:05 UTC, merged