x0vncserver: add page, screen: add commands
tldr-pages/tldr pull request #4478
Opened 2020-10-04 15:21 UTC by funwaa

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-04 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4478) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4478) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4478) it.</sub>

2020-10-04 19:14 UTC, navarroaxel requested changes
Hey @funwaa, thanks for your submission! I left some comments.

If you think your examples are more important than the current ones in the `screen.md` please discuss about it. But we can't publish pages with more than 8 examples.

2020-10-04 19:14 UTC, navarroaxel commented on pages/common/screen.md
> +`screen -x <name>`
The `md` pages can't have more than 8 examples, we have 10 here.

2020-10-04 19:14 UTC, navarroaxel commented on pages/linux/x0vncserver.md
> +> More information: <https://linux.die.net/man/1/x0vncserver>.
Here is the official docs
```suggestion
> More information: <https://tigervnc.org/doc/x0vncserver.html>.
```

2020-10-04 19:14 UTC, navarroaxel commented on pages/linux/x0vncserver.md
> +`x0vncserver -display :0 -passwordfile <file>`
```suggestion
`x0vncserver -display {{:0}} -passwordfile {{path/to/file}}`
```

2020-10-04 19:14 UTC, navarroaxel commented on pages/linux/x0vncserver.md
> +`x0vncserver -display :0 -rfbport <port>`
We use `{{` for arguments:
```suggestion
`x0vncserver -display {{:0}} -rfbport {{port}}`
```

2020-10-04 20:31 UTC, funwaa commented
I personally think that the -dr option for screen should be more in a cheatsheet than just "screen" without any options at all, but that's just my opinion. Thanks for the heads up and I'm sorry, I wasn't aware of the 8 commands maximum!

2020-10-20 11:09 UTC, navarroaxel commented on pages/linux/x0vncserver.md
> +`x0vncserver -display :0 -passwordfile <file>`
Hi @funwaa, you didn't apply 2 reviews.

2020-11-09 11:01 UTC, navarroaxel commented
@funwaa Can you apply the changes to the `screen.md` page to continue with this PR?

2020-11-21 03:07 UTC, navarroaxel requested changes

2020-11-21 03:07 UTC, navarroaxel commented on pages/common/screen.md
> +`screen -x <name>`
```suggestion
```

2020-11-21 03:13 UTC, navarroaxel requested changes

2020-11-21 03:13 UTC, navarroaxel commented on pages/linux/x0vncserver.md
> +- Specify a passwordfile:
```suggestion
- Start a VNC server with a passwordfile:
```

2020-11-21 03:13 UTC, navarroaxel commented on pages/linux/x0vncserver.md
> +- Change the default port:
```suggestion
- Start a VNC server using a specific port:
```

2020-11-21 03:14 UTC, navarroaxel requested changes

2020-11-21 03:14 UTC, navarroaxel commented on pages/linux/x0vncserver.md
> +- Start a VNC server with a passwordfile:
```suggestion
- Start a VNC server using a passwordfile:
```

2020-11-21 03:14 UTC, navarroaxel approved these changes

2020-11-27 01:03 UTC, sbrl approved these changes
Thanks, @funwaa!

2020-11-27 01:04 UTC, merged