replace: add page
tldr-pages/tldr pull request #4482
Opened 2020-10-04 16:58 UTC by CCreativeCND

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-04 16:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4482) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4482) it.</sub>

2020-10-04 18:17 UTC, navarroaxel requested changes
Hey @CCreativeCND, thanks for your submission. I left some comments.

2020-10-04 18:17 UTC, navarroaxel commented on pages/windows/replace.md
> +> Replaces files. It is related to robocopy, move, copy, and del. More information: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/replace.
```suggestion
> Replace files. It is related to robocopy, move, copy, and del commands.
> More information: <https://docs.microsoft.com/windows-server/administration/windows-commands/replace>.
```

2020-10-04 18:17 UTC, navarroaxel commented on pages/windows/replace.md
> +- Prompt before it replaces each file:
Maybe this is better:
```suggestion
- Interactively copy multiple files, with a prompt before replacing or adding a destination file:
```

2020-10-04 18:17 UTC, navarroaxel commented on pages/windows/replace.md
> +- Only adds files that do not already exist:
```suggestion
- Add files to the destination directory instead of replacing existing files:
```

2020-10-04 18:22 UTC, navarroaxel requested changes

2020-10-04 18:22 UTC, navarroaxel commented on pages/windows/replace.md
> +- Only replaces files in the destination directory which are older than the files in the source directory:
```suggestion
- Replace only files in the destination directory which are older than the files in the source directory:
```

2020-10-04 18:38 UTC, navarroaxel approved these changes

2020-10-06 15:49 UTC, sbrl approved these changes
Thanks, @CCreativeCND :slightly_smiling_face:

2020-10-06 15:49 UTC, merged