httpry: add page
tldr-pages/tldr pull request #4491
Opened 2020-10-05 01:06 UTC by WhileLoop

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [ x The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-05 01:09 UTC, WhileLoop commented
Closes #4095.

2020-10-05 10:58 UTC, navarroaxel requested changes
Hey @WhileLoop I left some comments.
WhileLoop w

2020-10-05 10:58 UTC, navarroaxel commented on pages/common/httpry.md
> +> More information: http://dumpsterventures.com/jason/httpry/.
```suggestion
> More information: <http://dumpsterventures.com/jason/httpry/>.
```

2020-10-05 10:58 UTC, navarroaxel commented on pages/common/httpry.md
> +`httpry -o out.log`
```suggestion
`httpry -o {{path/to/file.log}}`
```

2020-10-05 10:58 UTC, navarroaxel commented on pages/common/httpry.md
> +`httpry -i eth0 -b out.pcap`
```suggestion
`httpry -i {{eth0}} -b {{path/to/file.pcap}}`
```

2020-10-05 10:58 UTC, navarroaxel commented on pages/common/httpry.md
> +- Filter output by HTTP method strings:
:thinking: I always used `HTTP verbs` but MDN call them `request methods` 
```suggestion
- Filter output by a comma-separated list of HTTP method strings:
```

2020-10-05 10:58 UTC, navarroaxel commented on pages/common/httpry.md
> +`httpry -m get,head`
We can help with the option list here:
```suggestion
`httpry -m {{get|post|put|head|options|delete|trace|connect|patch}}`
```

2020-10-05 10:58 UTC, navarroaxel commented on pages/common/httpry.md
> +`httpry -r out.log 'host 192.168.5.25'`
Are you sure the `bpf-style` expression is not `src host ip`? based on reading the github README.
```suggestion
`httpry -r {{path/to/file.log}} '{{host 192.168.5.25}}'`
```

2020-10-05 10:58 UTC, navarroaxel commented on pages/common/httpry.md
> +`httpry -d -o /var/log/http.log`
```suggestion
`httpry -d -o {{path/to/file.log}}`
```

2020-10-05 15:49 UTC, WhileLoop commented
@navarroaxel Thanks for the feedback. I believe I have addressed all the issues.

2020-10-06 12:23 UTC, navarroaxel approved these changes

2020-10-06 16:28 UTC, sbrl approved these changes
Thanks, @WhileLoop :slightly_smiling_face:

2020-10-06 16:28 UTC, merged

2021-01-01 23:13 UTC, bl-ue commented
Oops! It looks like this didn't close the issue references because it wasn't in the description.  I'll close it myself.