dumpe2fs: add page
tldr-pages/tldr pull request #4497
Opened 2020-10-05 10:32 UTC by teeteejo

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-05 10:38 UTC, navarroaxel requested changes

2020-10-05 10:38 UTC, navarroaxel commented on pages/linux/dumpe2fs.md
> +`dumpe2fs {{/dev/sda1}}`
```suggestion
`dumpe2fs {{/dev/sdXN}}`
```

2020-10-05 10:38 UTC, navarroaxel commented on pages/linux/dumpe2fs.md
> +`dumpe2fs -b {{/dev/sda1}}`
```suggestion
`dumpe2fs -b {{/dev/sdXN}}`
```

2020-10-05 10:38 UTC, navarroaxel commented on pages/linux/dumpe2fs.md
> +`dumpe2fs -f {{/dev/sda1}}`
```suggestion
`dumpe2fs -f {{/dev/sdXN}}`
```

2020-10-05 10:38 UTC, navarroaxel commented on pages/linux/dumpe2fs.md
> +`dumpe2fs -h {{/dev/sda1}}`
```suggestion
`dumpe2fs -h {{/dev/sdXN}}`
```

2020-10-05 10:38 UTC, navarroaxel commented on pages/linux/dumpe2fs.md
> +`dumpe2fs -x {{/dev/sda1}}`
```suggestion
`dumpe2fs -x {{/dev/sdXN}}`
```

2020-10-05 10:38 UTC, navarroaxel commented on pages/linux/dumpe2fs.md
> +- Display ext2, ext3 and ext4 filesystem information for the device `/dev/sda1`:
```suggestion
- Display ext2, ext3 and ext4 filesystem information:
```

2020-10-05 10:42 UTC, teeteejo commented
Thank you @navarroaxel

2020-10-05 10:47 UTC, navarroaxel approved these changes

2020-10-21 10:51 UTC, navarroaxel commented
@sbrl, @owenvoke: could you please review?

2020-10-24 12:36 UTC, sbrl approved these changes
Thanks, @teeteejo!

Just made a really minor grammar fixx.

2020-10-24 12:36 UTC, merged