lilypond: add page
tldr-pages/tldr pull request #4500
Opened 2020-10-05 14:06 UTC by jpiamjariyakul

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-05 15:21 UTC, sbrl requested changes
Thanks for the new page, @jpiamjariyakul! I've left some comments below for you to review.

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +`lilypond {{name_file}}`
Perhaps this will read better?
```suggestion
`lilypond {{path/to/file}}`
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +- Compile file into PDF:
Perhaps this will read better?
```suggestion
- Compile a lilypond file into a PDF:
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +- Compile file into specified format:
Perhaps this will read better?
```suggestion
- Compile into the specified format:
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +`lilypond --formats={{format_dump}} {{name_file}}`
Perhaps this would be more consistent with other existing pages?
```suggestion
`lilypond --formats={{format_dump}} {{path/to/file}}`
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +- Show version of tool:
Perhaps this will read better?
```suggestion
- Show the current version of lilypond:
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +`lilypond --output={{name_output}} {{name_file}}`
Perhaps this will read better?
```suggestion
`lilypond --output={{path/to/output_file}} {{path/to/input_file}}`
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +`lilypond -s {{name_file}}`
Perhaps this will read better?
```suggestion
`lilypond -s {{path/to/file}}`
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +- Compile file into specified output name:
Perhaps this will read better?
```suggestion
- Compile the specified file, and also specify the output filename:
```

2020-10-05 15:21 UTC, sbrl commented on pages/common/lilypond.md
> +- Compile file, suppressing progress:
Perhaps this will read better?
```suggestion
- Compile the specified file, suppressing progress updates:
```

2020-10-05 15:35 UTC, jpiamjariyakul commented
Thanks for the suggestions @sbrl, definitely more consistent & comprehensive! Committed the suggestions.

2020-10-06 15:35 UTC, sbrl approved these changes
Thanks, @jpiamjariyakul :slightly_smiling_face:

2020-10-07 11:43 UTC, navarroaxel approved these changes

2020-10-07 11:43 UTC, merged