Create wget.md
tldr-pages/tldr pull request #4508
Opened 2020-10-05 19:22 UTC by d4rkshell

new command [wget]

- [x ] The page (if new), does not already exist in the repo.
- [ x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ x] The page has 8 or fewer examples.
- [ x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-05 19:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4508) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4508) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4508) it.</sub>

2020-10-05 19:54 UTC, navarroaxel commented
Oh @d4rkshell, `wget` already exists: https://github.com/tldr-pages/tldr/blob/master/pages/common/wget.md

2020-10-06 06:32 UTC, agnivade requested changes
Thanks, but we already have a page for wget in common. If you want to improve that, you are most welcome to edit that page.

2020-10-22 16:36 UTC, closed without merging

2020-10-22 16:36 UTC, d4rkshell commented
closing, no longer required