login: add page
tldr-pages/tldr pull request #4509
Opened 2020-10-05 19:25 UTC by en1gma713

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-05 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4509) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4509) it.</sub>

2020-10-05 21:19 UTC, en1gma713 commented
#2214

2020-10-06 09:28 UTC, owenvoke requested changes
Hi @en1gma713, just a few small grammatical changes and token syntax additions, but otherwise this looks good. Thanks!

2020-10-06 09:28 UTC, owenvoke commented on pages/linux/login.md
> +`login [user]`
```suggestion
- Login as a user:

`login {{user}}`
```

2020-10-06 09:28 UTC, owenvoke commented on pages/linux/login.md
> +`login -f [user]`
```suggestion
- Login as a user without authentication if user is preauthenticated:

`login -f {{user}}`
```

2020-10-06 09:28 UTC, owenvoke commented on pages/linux/login.md
> +`login -p [user]`
```suggestion
- Login as a user and preserve the environment:

`login -p {{user}}`
```

2020-10-06 09:28 UTC, owenvoke commented on pages/linux/login.md
> +`login -h [host] [user]`
```suggestion
- Login as a user on a remote host:

`login -h {{host}} {{user}}`
```

2020-10-06 09:28 UTC, owenvoke commented on pages/linux/login.md
> +# Login
```suggestion
# login
```

2020-10-06 11:46 UTC, en1gma713 commented
done

2020-10-06 11:49 UTC, owenvoke commented on pages/linux/login.md
> +# Login
@en1gma713, just this one and should be fine. 👍🏻 We tend to use lowercase titles for the pages. Cheers. 🙂

2020-10-06 11:52 UTC, owenvoke approved these changes
LGTM! Thanks @en1gma713. 🥳

2020-10-06 11:52 UTC, navarroaxel approved these changes

2020-10-06 11:52 UTC, merged