Add cheatsheet for docker-exec command
tldr-pages/tldr pull request #4518
Opened 2020-10-06 06:21 UTC by eshack94

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-06 06:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4518) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4518) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4518) it.</sub>

2020-10-06 12:00 UTC, owenvoke requested changes
Hi @eshack94, just a few review comments for using underscores in the tokens, and also possibly merging some of the examples. 🤔 Cheers.

2020-10-06 12:00 UTC, owenvoke commented on pages/common/docker-exec.md
> +`docker exec -d {{container-name}} {{command}}`
Apologies, another underscore here:
```suggestion
`docker exec -d {{container_name}} {{command}}`
```

2020-10-07 07:50 UTC, eshack94 commented on pages/common/docker-exec.md
> +`docker exec -it {{container-name}} /bin/sh`
Changes made. Thank you for the feedback!

2020-10-07 07:54 UTC, eshack94 commented on pages/common/docker-exec.md
> +`docker exec -i -d {{container-name}} {{command}}`
Changes made. Thanks for the feedback! 👍🏼

2020-10-07 07:55 UTC, eshack94 commented on pages/common/docker-exec.md
> +`docker exec -it -w {{path/to/directory}} {{container-name}} {{command}}`
Changes made.

2020-10-07 07:55 UTC, eshack94 commented on pages/common/docker-exec.md
> +`docker exec -d {{container-name}} mkdir {{directory-path}}`
Merged into one example. Good feedback. Thank you!

2020-10-07 07:55 UTC, eshack94 commented on pages/common/docker-exec.md
> +`docker exec -d {{container-name}} {{command}}`
Changed based on feedback. Thanks again.

2020-10-07 08:03 UTC, owenvoke approved these changes
Perfect! Thanks @eshack94.

2020-10-07 11:44 UTC, navarroaxel approved these changes

2020-10-07 11:45 UTC, merged