arecord: add example list audio devices and intractive interface
tldr-pages/tldr pull request #4530
Opened 2020-10-06 13:57 UTC by Ray6464

- [] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ x The page description includes a link to documentation or a homepage (if applicable).

2020-10-06 14:26 UTC, gutjuri requested changes

2020-10-06 14:26 UTC, gutjuri commented on pages/linux/arecord.md
> +- List all sound cards and digital audio devices
```suggestion
- List all sound cards and digital audio devices:
```

Apparently this is needed for formatting

2020-10-06 14:26 UTC, gutjuri commented on pages/linux/arecord.md
> +- Allow intractive interface like play/pause via spacebar/enter
```suggestion
- Allow intractive interface like play/pause via spacebar/enter:
```
This also

2020-10-11 03:14 UTC, navarroaxel requested changes
Thanks @Ray6464, just a few comments.

2020-10-11 03:14 UTC, navarroaxel commented on pages/linux/arecord.md
> +`arecord -i`
```suggestion
`arecord --interactive`
```

2020-10-11 03:14 UTC, navarroaxel commented on pages/linux/arecord.md
> +`arecord -l`
Please use long argument format:
```suggestion
`arecord --list-devices`
```

2020-10-11 03:14 UTC, navarroaxel commented on pages/linux/arecord.md
> +- Allow intractive interface like play/pause via spacebar/enter:
```suggestion
- Allow interactive interface (e.g. use space-bar or enter to play or pause):
```

2020-10-11 06:50 UTC, navarroaxel approved these changes

2020-10-11 09:27 UTC, gutjuri approved these changes

2020-10-12 21:28 UTC, sbrl approved these changes
Thanks, @Ray6464!

2020-10-12 21:28 UTC, merged