bat: add German translation
tldr-pages/tldr pull request #4537
Opened 2020-10-06 18:28 UTC by danwolb02

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

This adds a German translation for the `bat` page.

2020-10-06 18:32 UTC, navarroaxel approved these changes

2020-10-07 01:03 UTC, schneiderl requested changes
I've just left a minor comment for you. I do not know the language but sintax wise it looks good to me.

2020-10-07 01:03 UTC, schneiderl commented on pages.de/common/bat.md
> +`bat {{file1}} {{file2}} > {{target_file}}`
I believe we should also be translating the command params.

2020-10-07 01:03 UTC, schneiderl commented on pages.de/common/bat.md
> +`bat {{file1}} {{file2}} > {{target_file}}`
That applied to all examples we have here.

2020-10-07 05:39 UTC, danwolb02 commented
You're right, I'll change it.

2020-10-07 14:32 UTC, schneiderl approved these changes

2020-10-07 14:32 UTC, merged