git-ls-remote: add page
tldr-pages/tldr pull request #4538
Opened 2020-10-06 19:51 UTC by sanehab

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-07 19:52 UTC, sbrl approved these changes
Nice one, @sanehab!

2020-10-07 20:54 UTC, navarroaxel requested changes

2020-10-07 20:54 UTC, navarroaxel commented on pages/common/git-ls-remote.md
> +> If no name or url are given, then the configured upstream branch will be used, or remote origin if the former is not configured.
```suggestion
> If no name or URL are given, then the configured upstream branch will be used, or remote origin if the former is not configured.
```

2020-10-07 20:54 UTC, navarroaxel commented on pages/common/git-ls-remote.md
> +> Git command for listing references in a remote repository based or name or url.
```suggestion
> Git command for listing references in a remote repository based or name or URL.
```

2020-10-08 11:49 UTC, navarroaxel approved these changes

2020-10-08 11:50 UTC, merged