7z: add Spanish translation
tldr-pages/tldr pull request #4558
Opened 2020-10-07 17:14 UTC by kazulu

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-07 19:20 UTC, kazulu commented
@navarroaxel me gustaría saber tu opinión sobre el uso de la palabra `archivo` en el contexto de esta traducción, entendiendo que un archivo es el comprimido final de utilizar 7z sobre ficheros y directorios.

Quizás una opción sea utilizar `archivo` en lugar de `fichero`, `archivo comprimido` en lugar de `archivo` y `comprimir` en lugar de `archivar`.

2020-10-07 19:31 UTC, navarroaxel requested changes
Thanks @kazulu

2020-10-07 19:31 UTC, navarroaxel commented on pages.es/common/7z.md
> +- Archivar un fichero o un directorio:
```suggestion
- Archivar un archivo o un directorio:
```

2020-10-07 19:31 UTC, navarroaxel commented on pages.es/common/7z.md
> +- Extrae un archivo a stdout:
```suggestion
- Extrae un archivo a `stdout`:
```

2020-10-07 19:31 UTC, navarroaxel commented on pages.es/common/7z.md
> +- Lista el contenido de un fichero archivado:
:thinking: Esto si que suena mal, pero tampoco le hubiese puesto `archived.7z` a la página en inglés.
```suggestion
- Lista el contenido de un archivo archivado:
```
quizá podemos usar:
```suggestion
- Lista el contenido de un archivo 7z:
```

2020-10-07 19:46 UTC, navarroaxel commented
> @navarroaxel me gustaría saber tu opinión sobre el uso de la palabra `archivo` en el contexto de esta traducción, entendiendo que un archivo es el comprimido final de utilizar 7z sobre ficheros y directorios.
> 
> Quizás una opción sea utilizar `archivo` en lugar de `fichero`, `archivo comprimido` en lugar de `archivo` y `comprimir` en lugar de `archivar`.

Perdón, no lo había leído antes de hacer el review. La verdad que me gusta lo que decís @kazulu. Lo que pasa en que `fichero` es muy de España y casi ni se usa en Latam y no tenemos diferenciado (y no lo haría) es_es vs Español para Latam. Como si está con pt_PT y pt_BR.

2020-10-08 18:24 UTC, navarroaxel approved these changes

2020-10-08 22:04 UTC, schneiderl approved these changes
Don't know the language but looks good to me.

2020-10-08 22:26 UTC, merged