apt: add Malayalam translation
tldr-pages/tldr pull request #4562
Opened 2020-10-07 20:59 UTC by avronr

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-07 20:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4562) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4562) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4562) it.</sub>

2020-10-07 21:14 UTC, navarroaxel requested changes
Hey @avronr, this is our first Malayalam translation :tada: 

I don't speak the language but just 2 backticks to fix.

2020-10-07 21:14 UTC, navarroaxel commented on pages.ml/linux/apt.md
> +- ലഭ്യമായ പാക്കേജുകളുടെയും പതിപ്പുകളുടെയും പട്ടിക അപ്‌ഡേറ്റുചെയ്യുക (മറ്റ് ʻapt` കമാൻഡുകൾക്ക് മുമ്പ് ഇത് പ്രവർത്തിപ്പിക്കാൻ ശുപാർശ ചെയ്യുന്നു):
the backtick here:
```suggestion
- ലഭ്യമായ പാക്കേജുകളുടെയും പതിപ്പുകളുടെയും പട്ടിക അപ്‌ഡേറ്റുചെയ്യുക (മറ്റ് `apt` കമാൻഡുകൾക്ക് മുമ്പ് ഇത് പ്രവർത്തിപ്പിക്കാൻ ശുപാർശ ചെയ്യുന്നു):
```

2020-10-07 21:14 UTC, navarroaxel commented on pages.ml/linux/apt.md
> +- ഒരു പാക്കേജ് നീക്കംചെയ്യുക (പകരം `purge' ഉപയോഗിക്കുന്നത് അതിന്റെ കോൺഫിഗറേഷൻ ഫയലുകളും നീക്കംചെയ്യുന്നു):
the backtick here:
```suggestion
- ഒരു പാക്കേജ് നീക്കംചെയ്യുക (പകരം `purge` ഉപയോഗിക്കുന്നത് അതിന്റെ കോൺഫിഗറേഷൻ ഫയലുകളും നീക്കംചെയ്യുന്നു):
```

2020-10-07 21:18 UTC, avronr commented
@navarroaxel thanks for reviewing my PR.
I've made committed your suggestions. :)

2020-10-07 21:21 UTC, navarroaxel approved these changes

2020-10-08 22:06 UTC, schneiderl approved these changes

2020-10-08 22:25 UTC, merged