archey, groupdel, line, ntfsfix, pkrm, pwdx, userdel: add Spanish translations
tldr-pages/tldr pull request #4583
Opened 2020-10-08 18:08 UTC by quique

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-08 18:29 UTC, navarroaxel requested changes
Hey @quique, just a comment because we should use `sdXN` as template for `sda1`

2020-10-08 18:29 UTC, navarroaxel commented on pages.es/linux/ntfsfix.md
> +`sudo ntfsfix {{/dev/sdb2}}`
we should fix the English page too:
```suggestion
`sudo ntfsfix {{/dev/sdXN}}`
```

2020-10-08 21:57 UTC, schneiderl approved these changes
Don't know the language but looks good to me.

2020-10-09 11:04 UTC, navarroaxel approved these changes

2020-10-09 11:04 UTC, merged