Added pt-br choco, choco-install, choco-upgrade commands translation
tldr-pages/tldr pull request #4587
Opened 2020-10-08 22:57 UTC by brunoeduardodev

- [x ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-08 22:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4587) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4587) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4587) it.</sub>

2020-10-09 01:35 UTC, schneiderl requested changes
Hi,
I've left a few comments for you to take a look at. 
Thanks a lot for your contribution, it is very welcome.

2020-10-09 01:35 UTC, schneiderl commented on pages.pt_BR/windows/choco-install.md
> +`choco install {{package(s)}}`
Nós costumamos traduzir também os parâmetros. Algo do tipo: 
``suggestion
`choco install {{pacote(s)}}`
```

2020-10-09 01:35 UTC, schneiderl commented on pages.pt_BR/windows/choco-install.md
> +- Instalar um aquico específico "nuspec" ou "nupkg":
```suggestion
- Instalar um arquivo específico "nuspec" ou "nupkg":
```

2020-10-09 01:35 UTC, schneiderl commented on pages.pt_BR/windows/choco-upgrade.md
> +- Atualizr todos, exceto os pacotes separados por vírgula especificados:
Talvez isso soe melhor?
```suggestion
- Atualizar todos os pacotes, exceto os especificados separados por virgula:
```

2020-10-09 01:35 UTC, schneiderl commented on pages.pt_BR/windows/choco-install.md
> +> Mais informação: <https://chocolatey.org/docs/commands-install>.
Por padrão, usamos "Mais informações".
```suggestion
> Mais informações: <https://chocolatey.org/docs/commands-install>.
```

2020-10-09 01:35 UTC, schneiderl commented on pages.pt_BR/windows/choco-upgrade.md
> +> Mais informação: <https://chocolatey.org/docs/commands-upgrade>.
```suggestion
> Mais informações: <https://chocolatey.org/docs/commands-upgrade>.
```

2020-10-09 01:35 UTC, schneiderl commented on pages.pt_BR/windows/choco.md
> +> Mais informação: <https://chocolatey.org>.
```suggestion
> Mais informações: <https://chocolatey.org>.
```

2020-10-09 02:07 UTC, brunoeduardodev commented
Thanks, i added your sugestions, sorry for my mistakes, i'm new with open source community and i'm hoping i can help more with this great project

2020-10-09 11:09 UTC, navarroaxel requested changes
Hey @brunoeduardodev, thanks for your submission. You have some pending changes from @schneiderl. Ask if you have some question.

2020-10-09 11:09 UTC, navarroaxel commented on pages.pt_BR/windows/choco-install.md
> +`choco install {{package}} --version {{version}}`
Remember that you have to translate the arguments to make this easy to read for non-English speakers. e.g. `package` -> `pacote`

2020-10-09 15:23 UTC, schneiderl commented
@brunoeduardodev Don't be sorry 👍 It is great to see new people getting involved. 

There are still a couple of comments that still unaddressed. Would you mind taking a look at them?

2020-10-09 15:34 UTC, brunoeduardodev commented
I"m going to close the pull request and later i'll start a new with all fixes

2020-10-09 17:00 UTC, navarroaxel commented
Hey @brunoeduardodev, there is no need to close the PR, we can wait you to resolve the comments or you can convert the PR in a Draft PR you let us know that is a WIP PR.

Also, if you close this PR and open a new one, we lose the track of the comments that we made to you. Do you want I open this PR and we wait for your changes?

2020-10-09 19:06 UTC, brunoeduardodev commented
Okay, i think now i covered all the comments, could you take a look?

2020-10-10 18:25 UTC, schneiderl commented
@brunoeduardodev thank you for your patience with our review process. It all looks great to me now.

2020-10-10 18:25 UTC, schneiderl approved these changes

2020-10-10 18:26 UTC, schneiderl commented
Just wait for @navarroaxel review and I think we can merge this.

2020-10-10 19:38 UTC, navarroaxel approved these changes

2020-10-10 19:38 UTC, merged