Micro russian
tldr-pages/tldr pull request #4593
Opened 2020-10-09 09:29 UTC by NikonP

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-09 11:16 UTC, navarroaxel requested changes
Thanks @NikonP, I left you a comment.

2020-10-09 11:16 UTC, navarroaxel commented on pages/linux/aplay.md
> +# aplay
Please @NikonP remove this page from this PR.

2020-10-09 11:41 UTC, navarroaxel approved these changes
LGTM, thanks @NikonP

2020-10-09 15:54 UTC, schneiderl approved these changes
Don't know the language but looks good to me.

2020-10-09 17:04 UTC, merged

2020-10-12 21:00 UTC, sbrl commented
Feel free to open 1 big PR if you're translating lots of pages, with 1 commit per page  :-)