afinfo, afplay, airport, apachectl, archey, as, asr: add Spanish translation
tldr-pages/tldr pull request #4596
Opened 2020-10-09 11:42 UTC by dawalberto

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2020-10-09 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4596) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4596) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4596) it.</sub>

2020-10-09 11:56 UTC, navarroaxel requested changes
@dawalberto bienvenido y gracias por colaborar. I left you some comments.

2020-10-09 11:56 UTC, navarroaxel commented on pages.es/osx/afinfo.md
> +- Pinta la salida en formato xml:
The English page should have the format in upper case too :man_shrugging: 
```suggestion
- Imprime la salida en formato XML:
```

2020-10-09 11:56 UTC, navarroaxel commented on pages.es/osx/afplay.md
> +`afplay --time {{seconds}} {{path/to/file}}`
Deberías traducir también los argumentos en todos los ejemplos, para que los que no leen inglés lo puedan entender. Por ej:
```suggestion
`afplay --time {{segundos}} {{ruta/al/archivo}}`
```

2020-10-09 11:56 UTC, navarroaxel commented on pages.es/osx/airport.md
> +- Muestra la información del estado actual de la red inalámbrica :
```suggestion
- Muestra la información del estado actual de la red inalámbrica:
```

2020-10-09 11:56 UTC, navarroaxel commented on pages.es/osx/as.md
> +- Ensamblar la salida de un archivo dado:
A veces la traducción palabra por palabra no queda lindo
```suggestion
- Ensamblar la salida a un archivo especificado:
```

2020-10-09 11:56 UTC, navarroaxel commented on pages.es/osx/asr.md
> +- Clonar volúmenes sin el uso de una imagen de disco intermedia
```suggestion
- Clonar volúmenes sin el uso de una imagen de disco intermedia:
```

2020-10-09 11:56 UTC, navarroaxel commented on pages.es/osx/asr.md
> +`sudo asr restore --source {{image_name}}.dmg --target {{path/to/volume}}`
Por favor traduce los argumentos en las páginas, como:
```suggestion
`sudo asr restore --source {{nombre_de_imagen}}.dmg --target {{ruta/al/volumen}}`
```

2020-10-09 11:56 UTC, navarroaxel commented on pages.es/osx/apachectl.md
> +- Iniciar la tarea launchd org.apache.httpd:
No me siento bien con la mezcla entre infinitivo con imperativo. Creo que lo mejor es usar el imperativo en los ejemplos, no?
```suggestion
- Inicia la tarea launchd org.apache.httpd:
```

2020-10-09 13:18 UTC, navarroaxel requested changes
Hey @dawalberto just 2 easy comments.

2020-10-09 13:18 UTC, navarroaxel commented on pages.es/osx/afplay.md
> +`afplay --rate 2 {{ruta/al/archivo}}`
Perdón, no lo vi antes: los argument options deben ir en `{{}}`, después habría q arreglar la página en inglés también.
```suggestion
`afplay --rate {{2}} {{ruta/al/archivo}}`
```

2020-10-09 13:18 UTC, navarroaxel commented on pages.es/osx/afplay.md
> +`afplay --rate 0.5 {{ruta/al/archivo}}`
```suggestion
`afplay --rate {{0.5}} {{ruta/al/archivo}}`
```

2020-10-09 13:23 UTC, dawalberto commented on pages.es/osx/afplay.md
> +`afplay --rate 2 {{ruta/al/archivo}}`
No hay problema, enseguida lo arreglo! 😃

2020-10-09 13:54 UTC, navarroaxel approved these changes
LGTM, gracias @dawalberto

2020-10-12 21:00 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks, @dawalberto :slightly_smiling_face:

2020-10-12 21:00 UTC, merged