Show errors in journalctl
tldr-pages/tldr pull request #4601
Opened 2020-10-10 03:18 UTC by tom-on-the-internet

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-10 03:32 UTC, navarroaxel requested changes
Hey @tom-on-the-internet welcome and thanks for your submission. I left some comments.

2020-10-10 03:32 UTC, navarroaxel commented on pages/linux/journalctl.md
> +- Show all errors from this boot (-p is priority and 3 is for errors):
Is this better?
```suggestion
- Show all messages with priority level 3 (errors) from this boot:
```

2020-10-10 03:32 UTC, navarroaxel commented on pages/linux/journalctl.md
> +`journalctl -p 3 -b`
We can use long argument format to be easier for understand, and the argument option should be in `{{}}`
```suggestion
`journalctl -b --priority={{3}}`
```

2020-10-11 00:16 UTC, tom-on-the-internet commented
> Hey @tom-on-the-internet welcome and thanks for your submission. I left some comments.

Thanks so much!
Your suggestions look great.

2020-10-11 03:05 UTC, navarroaxel approved these changes
LGTM, thanks @tom-on-the-internet

2020-10-12 21:18 UTC, sbrl approved these changes
Thanks, @tom-on-the-internet! Looks good to me.

2020-10-12 21:18 UTC, merged