curl, docker, git, git-add, git-commi, git-status, npm  add id (indon…
tldr-pages/tldr pull request #4602
Opened 2020-10-10 04:08 UTC by irhamdz

- [x] The page (if new), does not already exist in the repo.

2020-10-10 04:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4602) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4602) before we can accept your contribution.<br/><hr/>**Irham Dzuhri** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4602) it.</sub>

2020-10-11 03:30 UTC, navarroaxel requested changes
Hi @irhamdz, welcome and thanks for your submission. I left some comments.

2020-10-11 03:30 UTC, navarroaxel commented on pages.id/common/curl.md
> +- Unduh file, mengikuti pengalihan [L] okasi, dan secara otomatis [C] melanjutkan (melanjutkan) transfer file sebelumnya:
```suggestion
- Unduh file, mengikuti pengalihan [L] okasi, dan secara otomatis [C] melanjutkan transfer file sebelumnya:
```

2020-10-11 03:30 UTC, navarroaxel commented on pages.id/common/curl.md
> +`curl {{http://example.com}} -o {{filename}}`
Could you translate the arguments like `filename` to be easier for non-English speakers?

2020-10-11 03:30 UTC, navarroaxel commented on pages.id/common/git-add.md
> +`git add {{path/to/file}}`
Could you translate `path/to/file`?

2020-10-11 03:30 UTC, navarroaxel commented on pages.id/common/git-commit.md
> +- otomatis merubah semua file yang dimodifikasi menjadi ke status stage dan menambahkan sebuah pesan:
```suggestion
- Otomatis merubah semua file yang dimodifikasi menjadi ke status stage dan menambahkan sebuah pesan:
```

2020-10-11 03:30 UTC, navarroaxel commented on pages.id/common/git-commit.md
> +- komit file tertentu (yang sudah di status stage):
```suggestion
- Komit file tertentu (yang sudah di status stage):
```

2020-10-11 03:31 UTC, navarroaxel commented
@irhamdz the commit author should match with your GitHub user to pass the license/cla check. Do you need some help fixing the commit author?

2020-10-11 03:37 UTC, irhamdz commented
> @irhamdz the commit author should match with your GitHub user to pass the license/cla check. Do you need some help fixing the commit author?

yes please I still confuse how to fix it

2020-10-11 03:39 UTC, navarroaxel commented
@irhamdz You should amend your commit using:
```bash
git commit --amend --author 'Your name <user@example.com>'
git push --force
```
And the name and email must match your GitHub account.

2020-10-12 02:23 UTC, irhamdz commented
@navarroaxel I update the PR and thanks for helping me with change the author commit :)

2020-10-12 03:59 UTC, navarroaxel approved these changes

2020-10-12 21:51 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-12 21:51 UTC, merged