chroma: add page
tldr-pages/tldr pull request #4603
Opened 2020-10-10 08:34 UTC by Starkiller645

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Fixes #4515

2020-10-10 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4603) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4603) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4603) it.</sub>

2020-10-10 15:38 UTC, owenvoke requested changes
It looks like all of these are the same, so it should be fine to merge them into a single command under the `pages/common` directory. 👍🏻

2020-10-10 20:21 UTC, Starkiller645 commented
I've moved the file into the common directory :)

2020-10-11 04:05 UTC, navarroaxel requested changes
Hey @Starkiller645, welcome and thanks for your submission. I left some comments.

2020-10-11 04:05 UTC, navarroaxel commented on pages/common/chroma.md
> +`chroma --lexer='python' {{source_file}}`
The argument options should be between `{}`:
```suggestion
`chroma --lexer="{{python}}" {{source_file}}`
```

2020-10-11 04:05 UTC, navarroaxel commented on pages/common/chroma.md
> +`chroma --lexer="go" --formatter="html" {{source_file}} > {{html_file}}`
```suggestion
`chroma --lexer="{{go}}" --formatter="{{html}}" {{source_file}} > {{html_file}}`
```

2020-10-11 04:05 UTC, navarroaxel commented on pages/common/chroma.md
> +`chroma --lexer="c++" --formatter="svg" --syle="monokai" {{source_file}} > {{svg_file}}`
```suggestion
`chroma --lexer="{{c++}}" --formatter="{{svg}}" --syle="{{monokai}}" {{source_file}} > {{svg_file}}`
```

2020-10-11 06:39 UTC, navarroaxel approved these changes

2020-10-11 08:44 UTC, owenvoke approved these changes

2020-10-11 08:44 UTC, merged