scoop-bucket, wsl, takeown: add Chinese translation
tldr-pages/tldr pull request #4604
Opened 2020-10-10 08:46 UTC by ChungZH

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-10 12:51 UTC, navarroaxel requested changes
Hi @ChungZH, thanks for your submission. I left some comments.

2020-10-10 12:51 UTC, navarroaxel commented on pages.zh/windows/scoop-bucket.md
> +> If Scoop doesn't know where the bucket is located its repository location must be specified.
Did you forget to translate this? :grin:

2020-10-10 12:51 UTC, navarroaxel commented on pages.zh/windows/takeown.md
> +`takeown /f {{path/to/file}}`
Could you translate the `path/to/file` to be easy to read for non-English speakers? the same for other commands here and `wsl`.

2020-10-10 13:27 UTC, navarroaxel approved these changes
LGTM, thanks @ChungZH

2020-10-12 20:52 UTC, schneiderl approved these changes
Don't know the language but looks good.

2020-10-12 21:06 UTC, merged