vim: add fr page, add line numbers command
tldr-pages/tldr pull request #4608
Opened 2020-10-10 10:40 UTC by tcarecolin

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-12 21:08 UTC, sbrl approved these changes
Thanks, @tcarecolin!

2020-10-28 18:36 UTC, navarroaxel requested changes
Just 1 comment.

2020-10-28 18:36 UTC, navarroaxel commented on pages.fr/common/vim.md
> +- Ouvrir un fichier:
Please use the French grammar in all examples:
```suggestion
- Ouvrir un fichier :
```

2020-10-31 20:42 UTC, navarroaxel approved these changes

2020-10-31 20:42 UTC, merged