mdls: add page
tldr-pages/tldr pull request #4618
Opened 2020-10-10 16:42 UTC by liamrosenfeld

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-10 16:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4618) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4618) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4618) it.</sub>

2020-10-11 05:55 UTC, navarroaxel requested changes
Hi @liamrosenfeld, welcome and thanks for your submission. I left some comments.

2020-10-11 05:55 UTC, navarroaxel commented on pages/osx/mdls.md
> +- Get all metadata for file:
```suggestion
- Display the list of metadata attributes for file:
```

2020-10-11 05:55 UTC, navarroaxel commented on pages/osx/mdls.md
> +`mdls {{file}}`
```suggestion
`mdls {{path/to/file}}`
```

2020-10-11 05:55 UTC, navarroaxel commented on pages/osx/mdls.md
> +- Get specific metadata attribute:
```suggestion
- Display a specific metadata attribute:
```

2020-10-11 05:55 UTC, navarroaxel commented on pages/osx/mdls.md
> +`mdls -name {{attribute}} {{file}}`
```suggestion
`mdls -name {{attribute}} {{path/to/file}}`
```

2020-10-11 05:55 UTC, navarroaxel commented on pages/osx/mdls.md
> +> Lists the metadata attributes for a file.
```suggestion
> Display the metadata attributes for a file.
```

2020-10-11 14:21 UTC, liamrosenfeld commented
Thank you for all those improvements! I squashed them into my commit.

2020-10-11 14:26 UTC, navarroaxel approved these changes
Thanks @liamrosenfeld, please don't `push --force` the next time. it's harder track the suggestions.

2020-10-12 21:29 UTC, sbrl approved these changes
Thanks, @liamrosenfeld! Looks ok to me. Welcome to tldr pages :-)

2020-10-12 21:29 UTC, merged