git: added FR translation + several updates
tldr-pages/tldr pull request #4619
Opened 2020-10-10 17:05 UTC by tcarecolin

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-10 23:30 UTC, schneiderl commented
wow. 
You are coming in very strong for a first contribution haha. Thank you for the massive PR. 
I guess this will take a little bit of time to review but I will be done as soon as possible. 
Thanks a lot for your contributions. I will take a better look at your PR in the next hours.

2020-10-11 03:53 UTC, navarroaxel commented
@tcarecolin Please fix the git conflict.

2020-10-12 20:47 UTC, schneiderl commented
After giving it a quick look I've realized that some (maybe most of them) parameters (inside {{}}) do not seem to be translated. 
We usually try to keep everything translated on the language-specific page, including parameters. Would you please take a look at that?

2020-11-01 15:04 UTC, sbrl reviewed
Hey wow thanks, @tcarecolin! That's a lot of translations. In future when you're translating multiple pages, could you avoid making changes to other languages (i.e. keep it to 1 language per PR) please? It's easy for us to miss something if you add 1 change to the English pages buried within 71 translated French pages :P

Anyway, I've just got 1 comment for you below :-)

2020-11-01 15:04 UTC, sbrl commented on pages/common/git-show.md
> +- Show information about the 3rd commit from the top of a branch:
Perhaps this will read better?
```suggestion
- Show information about the 3rd commit from the HEAD of a branch:
```

2020-11-02 13:04 UTC, navarroaxel requested changes

2020-11-02 13:04 UTC, navarroaxel commented on pages.fr/common/git-am.md
> +- Appliquer un fichier de patch:
Please apply the French grammar in all the pages:
```suggestion
- Appliquer un fichier de patch :
```

2020-11-05 19:27 UTC, sbrl approved these changes
Thanks, @tcarecolin! Looks ok to me after @navarroaxel's comments are addressed :-)

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-apply.md
> +- Stocke le resultat du correctif dans l index sans modifier la branche courrante:
```suggestion
- Stocke le resultat du correctif dans l index sans modifier la branche courrante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-apply.md
> +- Applique le correctif en ordre inverse:
```suggestion
- Applique le correctif en ordre inverse :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-apply.md
> +- Affiche les differencs resultantes et applique le correctif:
```suggestion
- Affiche les differencs resultantes et applique le correctif :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-apply.md
> +- Applique un correctif depuis une source distante:
```suggestion
- Applique un correctif depuis une source distante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-apply.md
> +- Applique le correctif et ajoute les fichiers a l index:
```suggestion
- Applique le correctif et ajoute les fichiers a l index :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-apply.md
> +- Afficher les messages a propos des fichiers corrigés:
```suggestion
- Afficher les messages a propos des fichiers corrigés :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-annex.md
> +- Recupére un ficheir ou un repertoire:
```suggestion
- Recupére un ficheir ou un repertoire :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-annex.md
> +- Synchronise un repository local avec un distant:
```suggestion
- Synchronise un repository local avec un distant :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-annex.md
> +- Affiche le statut courrand d un fichier ou repertoire:
```suggestion
- Affiche le statut courrand d un fichier ou repertoire :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-annex.md
> +- Ajoute un fichier:
```suggestion
- Ajoute un fichier :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-annex.md
> +- Initialize le repo avec git annex:
```suggestion
- Initialize le repo avec git annex :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-annex.md
> +- Aide:
```suggestion
- Aide :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-am.md
> +- Appliquer autant de fichier de correctif que possible, en enregistrant les morceaux échoués pour rejeter le fichier:
```suggestion
- Appliquer autant de fichier de correctif que possible, en enregistrant les morceaux échoués pour rejeter le fichier :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-am.md
> +- Annuler l'application d un fichier de patch:
```suggestion
- Annuler l'application d un fichier de patch :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-add.md
> +- Ajoute interactivement les parties d un fichier specifié:
```suggestion
- Ajoute interactivement les parties d un fichier specifié :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-add.md
> +- Ajouter un fichier interactivement:
```suggestion
- Ajouter un fichier interactivement :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-archive.md
> +- Ajoutez un chemin d'accès à chaque fichier pour l'archiver dans un répertoire spécifique:
```suggestion
- Ajoutez un chemin d'accès à chaque fichier pour l'archiver dans un répertoire spécifique :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-archive.md
> +- Crée une archive avec le contenu d un repertoire donné:
```suggestion
- Crée une archive avec le contenu d un repertoire donné :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-archive.md
> +- Crée une archive depuis le dernier commit de la branche spécifiée:
```suggestion
- Crée une archive depuis le dernier commit de la branche spécifiée :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-archive.md
> +- Pareil que ci-dessus mais ecrit dans l archive specifiée:
```suggestion
- Pareil que ci-dessus mais ecrit dans l archive specifiée :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-archive.md
> +- Crée une archive .zip avec le contenu de la HEAD et l'affiche sur la sortie stanard:
```suggestion
- Crée une archive .zip avec le contenu de la HEAD et l'affiche sur la sortie stanard :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-archive.md
> +- Crée une archive .tar avec le contenu de la HEAD et l'affiche sur la sortie stanard:
```suggestion
- Crée une archive .tar avec le contenu de la HEAD et l'affiche sur la sortie stanard :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bisect.md
> +- Démarrez une dissection sur une plage de commit délimitée par un bug connu et un commit propre connu (généralement plus ancien):
```suggestion
- Démarrez une dissection sur une plage de commit délimitée par un bug connu et un commit propre connu (généralement plus ancien) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bisect.md
> +- Pour chaque `git bisect` selectionné, le marquer comme "bad" ou "good" apres l'avoir testé pour le probléme:
```suggestion
- Pour chaque `git bisect` selectionné, le marquer comme "bad" ou "good" apres l'avoir testé pour le probléme :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bisect.md
> +- Apres que `git bisect` pointe vers le mauvais commit, terminer la dissection et retourner a la branche précedante:
```suggestion
- Apres que `git bisect` pointe vers le mauvais commit, terminer la dissection et retourner a la branche précedante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bisect.md
> +- Sauter un commit lorrs de la dissection (e.g. celui qui echoue les tests pour une autre raison):
```suggestion
- Sauter un commit lorrs de la dissection (e.g. celui qui echoue les tests pour une autre raison) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-blame.md
> +- Affiche le hash de commit et le nom de l auteur en face de chaque ligne:
```suggestion
- Affiche le hash de commit et le nom de l auteur en face de chaque ligne :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-blame.md
> +- Affiche le hash de commit le nom et l email de l auteur en face de chaque ligne:
```suggestion
- Affiche le hash de commit le nom et l email de l auteur en face de chaque ligne :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Liste les branches locale, prefixe la branche courrante avec `*`:
```suggestion
- Liste les branches locale, prefixe la branche courrante avec `*` :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Liste toutes les branches (locale et distantes):
```suggestion
- Liste toutes les branches (locale et distantes) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Affiche le nom de la branche courrante:
```suggestion
- Affiche le nom de la branche courrante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Crée une nouvelle branche depuis le commit courrant:
```suggestion
- Crée une nouvelle branche depuis le commit courrant :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Crée une nouvelle branche depuis un commit en particulier:
```suggestion
- Crée une nouvelle branche depuis un commit en particulier :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Renommer une branche (ne pas se trouver sur la branche pour le faire):
```suggestion
- Renommer une branche (ne pas se trouver sur la branche pour le faire) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Supprimer un branche locale (ne pas se trouver sur la branche pour le faire):
```suggestion
- Supprimer un branche locale (ne pas se trouver sur la branche pour le faire) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-branch.md
> +- Supprimer une branche distante:
```suggestion
- Supprimer une branche distante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bundle.md
> +- Empaquetez tout les objets et les refferences d'une branche spécifiée:
```suggestion
- Empaquetez tout les objets et les refferences d'une branche spécifiée :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bundle.md
> +- Crée un empaquetage de tout les fichiers de toutes les branches:
```suggestion
- Crée un empaquetage de tout les fichiers de toutes les branches :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bundle.md
> +- Crée un empaquetage des 5 derniers commits de la branche courrante:
```suggestion
- Crée un empaquetage des 5 derniers commits de la branche courrante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bundle.md
> +- Crée un empaquetage des 7 derniers jours:
```suggestion
- Crée un empaquetage des 7 derniers jours :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bundle.md
> +- Verifie qu'un empaquetage est valide et peut étre appliquer à la branche courrante:
```suggestion
- Verifie qu'un empaquetage est valide et peut étre appliquer à la branche courrante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bundle.md
> +- Affiche sur la sortie standard la liste des réfferences contenues dans un empaquetage:
```suggestion
- Affiche sur la sortie standard la liste des réfferences contenues dans un empaquetage :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-bundle.md
> +- Extraire une branche spécifique d'un fichier de bundle dans le référentiel actuel:
```suggestion
- Extraire une branche spécifique d'un fichier de bundle dans le référentiel actuel :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-cat-file.md
> +- Obtenir la taill [s] du commit HEAD en octets:
```suggestion
- Obtenir la taill [s] du commit HEAD en octets :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-cat-file.md
> +- Obtenir le type [t] (blob, tree, commit, tag) d'un objet git spécifié:
```suggestion
- Obtenir le type [t] (blob, tree, commit, tag) d'un objet git spécifié :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-cat-file.md
> +- Affiche le contenu [p] d'un objet git basé sur son type:
```suggestion
- Affiche le contenu [p] d'un objet git basé sur son type :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-check-ignore.md
> +- Verifie qu'un fichier ou repertoire est ignoré:
```suggestion
- Verifie qu'un fichier ou repertoire est ignoré :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-check-ignore.md
> +- Verifie que plusieurs fichiers ou repertoires sont ignorés:
```suggestion
- Verifie que plusieurs fichiers ou repertoires sont ignorés :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-check-ignore.md
> +- Utilisez des chemins d'accès, un par ligne, de `stdin`:
```suggestion
- Utilisez des chemins d'accès, un par ligne, de `stdin` :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-check-ignore.md
> +- Ne pas vérifier l'index (utilisé pour déboguer pourquoi les chemins ont été suivis et non ignorés):
```suggestion
- Ne pas vérifier l'index (utilisé pour déboguer pourquoi les chemins ont été suivis et non ignorés) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-check-ignore.md
> +- Inclure les details pour chaque occurence dans le chemin:
```suggestion
- Inclure les details pour chaque occurence dans le chemin :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Créer une branche et basculer dessus:
```suggestion
- Créer une branche et basculer dessus :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Créer une branche depuis une reférence spçifiaue et basculer dessus (par exemple, branche locales/distantes, tag, commit):
```suggestion
- Créer une branche depuis une reférence spçifiaue et basculer dessus (par exemple, branche locales/distantes, tag, commit) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Basculer sur une branche locale existante:
```suggestion
- Basculer sur une branche locale existante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Basculer sur la branche précedante:
```suggestion
- Basculer sur la branche précedante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Basculer sur une brnche distante existante:
```suggestion
- Basculer sur une brnche distante existante :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Annule tout les changements dans le repertoire courrant (voir `git reset` pour plus de commandes d'annulation):
```suggestion
- Annule tout les changements dans le repertoire courrant (voir `git reset` pour plus de commandes d'annulation) :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Annule tout les changements dans le fichier spécifié:
```suggestion
- Annule tout les changements dans le fichier spécifié :
```

2020-11-10 10:28 UTC, navarroaxel commented on pages.fr/common/git-checkout.md
> +- Remplace un fichier par sa version d'une autre branche:
```suggestion
- Remplace un fichier par sa version d'une autre branche :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-cherry-pick.md
> +- Applique un commit à la branche courrante:
```suggestion
- Applique un commit à la branche courrante :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-cherry-pick.md
> +- Appliquer une plage de commits à la branche courrante (voir aussi `git rebase --onto`):
```suggestion
- Appliquer une plage de commits à la branche courrante (voir aussi `git rebase --onto`) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-cherry-pick.md
> +- Appliquer plusieurs commits non sequentiels à la branche courrante:
```suggestion
- Appliquer plusieurs commits non sequentiels à la branche courrante :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-cherry-pick.md
> +- Appliquer les changements d'un commit a la branche courrante sans créer de commit:
```suggestion
- Appliquer les changements d'un commit a la branche courrante sans créer de commit :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-cherry.md
> +- Afficher les commits (et leurs messages) avec des commits équivalents en amont:
```suggestion
- Afficher les commits (et leurs messages) avec des commits équivalents en amont :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-cherry.md
> +- Spécifiez une branche amont et une branche de rubrique différentes:
```suggestion
- Spécifiez une branche amont et une branche de rubrique différentes :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-cherry.md
> +- Limiter les commits a ceux dans la limite donnée:
```suggestion
- Limiter les commits a ceux dans la limite donnée :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-clean.md
> +- Supprimer les fichiers non suivis par git:
```suggestion
- Supprimer les fichiers non suivis par git :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-clean.md
> +- Supprimer les fichiers non suivis par git de manière interactive:
```suggestion
- Supprimer les fichiers non suivis par git de manière interactive :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-clean.md
> +- Affiche les fichiers non suivis qui peuvent étre suprimmés:
```suggestion
- Affiche les fichiers non suivis qui peuvent étre suprimmés :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-clean.md
> +- Nettoyage forcé des fichiers non suivis par git:
```suggestion
- Nettoyage forcé des fichiers non suivis par git :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-clean.md
> +- Nettoyage forcé des repertoires non suivis par git:
```suggestion
- Nettoyage forcé des repertoires non suivis par git :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-clean.md
> +- Supprime tout les fichiers suivis, incluant ceux repertoriés par `.gitignore` et `.git/info/exclude`:
```suggestion
- Supprime tout les fichiers suivis, incluant ceux repertoriés par `.gitignore` et `.git/info/exclude` :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-config.md
> +- Liste les entrés de configurations locales (stockés dans `.git/config` du repertoire courrant):
```suggestion
- Liste les entrés de configurations locales (stockés dans `.git/config` du repertoire courrant) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-config.md
> +- Liste les entrés de conffigurations globales (stoqués dans `~/.gitconfig`):
```suggestion
- Liste les entrés de conffigurations globales (stoqués dans `~/.gitconfig`) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-config.md
> +- Liste toutes les entrés de conffiguration, globales et locales:
```suggestion
- Liste toutes les entrés de conffiguration, globales et locales :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-diff.md
> +- Afficher tout les changements sur les fichiers par rapport a la téte de branche:
```suggestion
- Afficher tout les changements sur les fichiers par rapport a la téte de branche :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-diff.md
> +- Comparer plusieurs fichiers de la branche courrante avec une autre branche:
```suggestion
- Comparer plusieurs fichiers de la branche courrante avec une autre branche :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-difftool.md
> +- Configurer Meld comme outil de comparaison par defaut:
```suggestion
- Configurer Meld comme outil de comparaison par defaut :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-difftool.md
> +- Utiliser un outil de comparaison spécifique (opendiff) pour afficher les changements depuis un commit:
```suggestion
- Utiliser un outil de comparaison spécifique (opendiff) pour afficher les changements depuis un commit :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fetch.md
> +- Cherche les dernières modifications du référentiel amont distant par défaut (si configuré):
```suggestion
- Cherche les dernières modifications du référentiel amont distant par défaut (si configuré) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fetch.md
> +- Cherche les nouvelles branches depuis un registre distant:
```suggestion
- Cherche les nouvelles branches depuis un registre distant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fetch.md
> +- Cherche les nouvelles branches depuis tout les registres distant:
```suggestion
- Cherche les nouvelles branches depuis tout les registres distant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fetch.md
> +- Recherche egalement les tags depuis le registre courrant:
```suggestion
- Recherche egalement les tags depuis le registre courrant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fetch.md
> +- Supprime les références locales de branches ayant été supprimés du registre distant:
```suggestion
- Supprime les références locales de branches ayant été supprimés du registre distant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-flow.md
> +- Initialiser dans un registre git existant:
```suggestion
- Initialiser dans un registre git existant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-flow.md
> +- Commencer le travail sur une fonctionnalité basé sur la branche `develop`:
```suggestion
- Commencer le travail sur une fonctionnalité basé sur la branche `develop` :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-flow.md
> +- Terminer le travail sur une branche de fonctionnalité, le merger dans la branche `develop` puis suprimmer:
```suggestion
- Terminer le travail sur une branche de fonctionnalité, le merger dans la branche `develop` puis suprimmer :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-flow.md
> +- Publier une fonctionalité sur le serveur distant:
```suggestion
- Publier une fonctionalité sur le serveur distant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-flow.md
> +- Recupérer un fonctionalité publiée par un autre utilisateur:
```suggestion
- Recupérer un fonctionalité publiée par un autre utilisateur :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-format-patch.md
> +-Créer un fichier de correctif .patch nommé automatiquement pour tout les commits non poussés:
```suggestion
- Créer un fichier de correctif .patch nommé automatiquement pour tout les commits non poussés :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-format-patch.md
> +- Crér un fichier correctif .patch pour les changements entre 2 révisions:
```suggestion
- Crér un fichier correctif .patch pour les changements entre 2 révisions :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-format-patch.md
> +- Créer un fichier correctif .patch pour les 3 derniers commits:
```suggestion
- Créer un fichier correctif .patch pour les 3 derniers commits :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fsck.md
> +- Verifier le registre courrant:
```suggestion
- Verifier le registre courrant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fsck.md
> +- Lister tout les tags trouvés:
```suggestion
- Lister tout les tags trouvés :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-fsck.md
> +- Lister tout les noeuds racine trouvés:
```suggestion
- Lister tout les noeuds racine trouvés :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-gc.md
> +- Optimise le registrey:
```suggestion
- Optimise le registrey :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-gc.md
> +- Optimise le registre plus agressivement, plus long:
```suggestion
- Optimise le registre plus agressivement, plus long :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-gc.md
> +- Afficher les objets a supprimer:
```suggestion
- Afficher les objets a supprimer :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-gc.md
> +- Supprime tout les objets trouvés sans l'afficher sur la sortie standart:
```suggestion
- Supprime tout les objets trouvés sans l'afficher sur la sortie standart :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-gc.md
> +- Afficher le manuel:
```suggestion
- Afficher le manuel :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-grep.md
> +- Rechercher une occrence dans les fichiers suivis:
```suggestion
- Rechercher une occrence dans les fichiers suivis :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-grep.md
> +- Rechercher une occrence dans les fichiers suivis d'appres un pattern de fichiers:
```suggestion
- Rechercher une occrence dans les fichiers suivis d'appres un pattern de fichiers :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-grep.md
> +- Rechercher une occrence dans les fichiers suivis et les sous-modules:
```suggestion
- Rechercher une occrence dans les fichiers suivis et les sous-modules :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-grep.md
> +- Rechercher une occurence à partir d un point spécifique dans l'historique:
```suggestion
- Rechercher une occurence à partir d un point spécifique dans l'historique :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-grep.md
> +- Rechercher une occurence dans toutes les branches:
```suggestion
- Rechercher une occurence dans toutes les branches :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-help.md
> +- Afficher le manuel d'une sous commande:
```suggestion
- Afficher le manuel d'une sous commande :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-help.md
> +- Méme chose dans un navigateur:
```suggestion
- Méme chose dans un navigateur :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-help.md
> +- Afficher la liste des sous commandes disponnibles:
```suggestion
- Afficher la liste des sous commandes disponnibles :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-help.md
> +- Lister les manuels disponnibles:
```suggestion
- Lister les manuels disponnibles :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-help.md
> +- Lister toutes les variables de configuration disponnibles:
```suggestion
- Lister toutes les variables de configuration disponnibles :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-imerge.md
> +- Démarrer un i-merge rebase (se placer dans la branche a rebaser d'abord):
```suggestion
- Démarrer un i-merge rebase (se placer dans la branche a rebaser d'abord) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-imerge.md
> +- Démarrer imerge merge (se placer dans la branche depuis laquelle merger d'abord):
```suggestion
- Démarrer imerge merge (se placer dans la branche depuis laquelle merger d'abord) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-imerge.md
> +- Afficher le diagramme ASCII du merge ou rebase en cours:
```suggestion
- Afficher le diagramme ASCII du merge ou rebase en cours :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-imerge.md
> +- Continuer l opperation après une résolution de conflit (d'abord `git add` les fichiers en conflits):
```suggestion
- Continuer l opperation après une résolution de conflit (d'abord `git add` les fichiers en conflits) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-imerge.md
> +- Terminer l'opperation i-merge après la resolution de tout les conflits:
```suggestion
- Terminer l'opperation i-merge après la resolution de tout les conflits :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-imerge.md
> +- Annuler l'opperation et retourner à la branche précédante:
```suggestion
- Annuler l'opperation et retourner à la branche précédante :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-init.md
> +- Initialise un nouveau registre git local:
```suggestion
- Initialise un nouveau registre git local :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-init.md
> +- Initialiser un référentiel barebones, adapté à une utilisation distante via ssh:
```suggestion
- Initialiser un référentiel barebones, adapté à une utilisation distante via ssh :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-instaweb.md
> +- Démare un serveur gitweb depuis le repository courrant:
```suggestion
- Démare un serveur gitweb depuis le repository courrant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-instaweb.md
> +- Écoute uniquement sur le port localhost:
```suggestion
- Écoute uniquement sur le port localhost :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-instaweb.md
> +- Écoute sur un port spécifique:
```suggestion
- Écoute sur un port spécifique :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-instaweb.md
> +- Utiliser un daemon http spécifique:
```suggestion
- Utiliser un daemon http spécifique :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-instaweb.md
> +- Lancer en méme temps qu un navigateur web:
```suggestion
- Lancer en méme temps qu un navigateur web :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-instaweb.md
> +- Stoppe le serveur:
```suggestion
- Stoppe le serveur :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-instaweb.md
> +- Redémarre le serveur:
```suggestion
- Redémarre le serveur :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Initialise le Git LFS:
```suggestion
- Initialise le Git LFS :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Suivre des fichiers correspondant à un pattern:
```suggestion
- Suivre des fichiers correspondant à un pattern :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Changer l'URL du point de terminaison Git LFS (utile si le serveur LFS est séparé du serveur Git):
```suggestion
- Changer l'URL du point de terminaison Git LFS (utile si le serveur LFS est séparé du serveur Git) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Lister les pattern de fichiers suivis:
```suggestion
- Lister les pattern de fichiers suivis :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Lister les fichiers suivis ayant été commité:
```suggestion
- Lister les fichiers suivis ayant été commité :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Pousser tout les objets LFS vers le serveur distant:
```suggestion
- Pousser tout les objets LFS vers le serveur distant :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Chercher tout les objets LFS:
```suggestion
- Chercher tout les objets LFS :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-lfs.md
> +- Charger tout les objets LFS:
```suggestion
- Charger tout les objets LFS :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher la séquence de commits à partir de l'actuel, dans l'ordre chronologique inverse du dépôt git dans le répertoire de travail actuel:
```suggestion
- Afficher la séquence de commits à partir de l'actuel, dans l'ordre chronologique inverse du dépôt git dans le répertoire de travail actuel :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher l'historique de fichiers ou repertoires en particulier:
```suggestion
- Afficher l'historique de fichiers ou repertoires en particulier :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher la liste des fichiers modifiés pour chaque commit:
```suggestion
- Afficher la liste des fichiers modifiés pour chaque commit :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher un graphique des commits dans la branche actuelle en utilisant uniquement la première ligne de chaque message de commit:
```suggestion
- Afficher un graphique des commits dans la branche actuelle en utilisant uniquement la première ligne de chaque message de commit :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher un graphique de tout les commits, tags et branches dans le dépot entier:
```suggestion
- Afficher un graphique de tout les commits, tags et branches dans le dépot entier :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher uniqueent les commits dont le message contient la chaine (non sensible à la case):
```suggestion
- Afficher uniqueent les commits dont le message contient la chaine (non sensible à la case) :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher les N derniers commits d'un utilisateur:
```suggestion
- Afficher les N derniers commits d'un utilisateur :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-log.md
> +- Afficher les commits entre deux dates:
```suggestion
- Afficher les commits entre deux dates :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-ls-tree.md
> +- Lister le contenu de l'arbre dans le commit, recursif avec les sous-arbres:
```suggestion
- Lister le contenu de l'arbre dans le commit, recursif avec les sous-arbres :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-ls-tree.md
> +- Lister uniquement les moms de fichiers de l'arbre dans un commit:
```suggestion
- Lister uniquement les moms de fichiers de l'arbre dans un commit :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-ls-remote.md
> +- Afficher les références du dépot configuré par défaut:
```suggestion
- Afficher les références du dépot configuré par défaut :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-ls-remote.md
> +- Afficher uniquement les références HEAD du dépot configuré par défaut:
```suggestion
- Afficher uniquement les références HEAD du dépot configuré par défaut :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-ls-remote.md
> +- Afficher uniquement les tags du dépot configuré par défaut:
```suggestion
- Afficher uniquement les tags du dépot configuré par défaut :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-ls-remote.md
> +- Afficher les références du dépot précisé:
```suggestion
- Afficher les références du dépot précisé :
```

2020-11-10 10:45 UTC, navarroaxel commented on pages.fr/common/git-ls-remote.md
> +- Afficher les références du dépot précisé filtrés par un pattern:
```suggestion
- Afficher les références du dépot précisé filtrés par un pattern :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-describe.md
> +
```suggestion
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-merge.md
> +- Merge une branche dans votre branche courrante:
```suggestion
- Merge une branche dans votre branche courrante 
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-merge.md
> +- Editer le message de merge:
```suggestion
- Editer le message de merge :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-merge.md
> +- Merge une branche et créer un commit de merge:
```suggestion
- Merge une branche et créer un commit de merge :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-merge.md
> +- Annuler un merge en cas de conflit:
```suggestion
- Annuler un merge en cas de conflit :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-merge.md
> +- Continuer un merge apreés une résolution de conflit:
```suggestion
- Continuer un merge apreés une résolution de conflit :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mergetool.md
> +- Démarrer l'outil de différences par défaut:
```suggestion
- Démarrer l'outil de différences par défaut :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mergetool.md
> +- Lister les outils de différences valides:
```suggestion
- Lister les outils de différences valides :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mergetool.md
> +- Démarrer l'outil de différences en précisant son nom:
```suggestion
- Démarrer l'outil de différences en précisant son nom :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mergetool.md
> +- Démarer l'outil de difféerences sans dialogues:
```suggestion
- Démarer l'outil de difféerences sans dialogues :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mergetool.md
> +- Utiliser explicitement l'outil de différences graphique (voir la variable de config `merge.guitool`):
```suggestion
- Utiliser explicitement l'outil de différences graphique (voir la variable de config `merge.guitool`) :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mergetool.md
> +- tiliser explicitement l'outil de différences clasique (voir la variable de config `merge.tool`):
```suggestion
- tiliser explicitement l'outil de différences clasique (voir la variable de config `merge.tool`) :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mv.md
> +- Déplace les fichiers dans l'index git, valide au prochain commit:
```suggestion
- Déplace les fichiers dans l'index git, valide au prochain commit :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mv.md
> +- Renome un fichier et met a jour l'index, valide au prochain commit:
```suggestion
- Renome un fichier et met a jour l'index, valide au prochain commit :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-mv.md
> +- Force l'écrasement d'un fichier:
```suggestion
- Force l'écrasement d'un fichier :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Lister toutes les notes et leurs objets rattachés:
```suggestion
- Lister toutes les notes et leurs objets rattachés :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Lister toutes les notes attaches a un objet donné:
```suggestion
- Lister toutes les notes attaches a un objet donné :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Afficher les notes attachés a un objet donné:
```suggestion
- Afficher les notes attachés a un objet donné :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Ajoute une note à un objet donné:
```suggestion
- Ajoute une note à un objet donné :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Ajoute une note à un objet donné, en spécifiant le message
```suggestion
- Ajoute une note à un objet donné, en spécifiant le message :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Edite une note éxistante:
```suggestion
- Edite une note éxistante :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Copy la note d'un objet vers un autre:
```suggestion
- Copy la note d'un objet vers un autre :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-notes.md
> +- Supprime toutes les notes d'un objet spécifié:
```suggestion
- Supprime toutes les notes d'un objet spécifié :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-pr.md
> +- Récupére une pull-request spécifique:
```suggestion
- Récupére une pull-request spécifique :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-pr.md
> +- Récupére une pull-request d un dépot spécifique:
```suggestion
- Récupére une pull-request d un dépot spécifique :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-pr.md
> +- Récupére une pull-request depuis sont url:
```suggestion
- Récupére une pull-request depuis sont url :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-pr.md
> +- Nettoie les branches de pull-request terminés:
```suggestion
- Nettoie les branches de pull-request terminés :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Rejouer les commits de la branche courrante sur la branche master:
```suggestion
- Rejouer les commits de la branche courrante sur la branche master :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Rejouer les comits interactivement, ce qui permet aux commits d'éte re-arrangés, exclus, combimés ou modifiés:
```suggestion
- Rejouer les comits interactivement, ce qui permet aux commits d'éte re-arrangés, exclus, combimés ou modifiés :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Continuer le re-jeu des commits apres la resolution d'un conflit:
```suggestion
- Continuer le re-jeu des commits apres la resolution d'un conflit :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Resoudre automatiquement les conflits en precisant la version a conserver (`theirs` signifie la version des fichiers a privilégier):
```suggestion
- Resoudre automatiquement les conflits en precisant la version a conserver (`theirs` signifie la version des fichiers a privilégier) :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Rejoue les 5 derniers commits, ce qui permet aux commits d'éte re-arrangés, exclus, combimés ou modifiés:
```suggestion
- Rejoue les 5 derniers commits, ce qui permet aux commits d'éte re-arrangés, exclus, combimés ou modifiés :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Déplacez une partie de la branche actuelle sur une nouvelle base, fournissant l'ancienne base à partir de laquelle commencer:
```suggestion
- Déplacez une partie de la branche actuelle sur une nouvelle base, fournissant l'ancienne base à partir de laquelle commencer :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Continuer le re-jeu des commits en sautant la résolution d'un conflit:
```suggestion
- Continuer le re-jeu des commits en sautant la résolution d'un conflit :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-rebase.md
> +- Annule l'operation (ex: en cas de conflict):
```suggestion
- Annule l'operation (ex: en cas de conflict) :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-reflog.md
> +- Affiche le reflog d'une branche spécifique:
```suggestion
- Affiche le reflog d'une branche spécifique :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-reflog.md
> +- Afficher le reflog de HEAD:
```suggestion
- Afficher le reflog de HEAD :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-reflog.md
> +- Affiche les 5 dérniéres entrés dans le reflog:
```suggestion
- Affiche les 5 dérniéres entrés dans le reflog :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-repack.md
> +- Empaqueter les objets décompressés dans le dépot courrant:
```suggestion
- Empaqueter les objets décompressés dans le dépot courrant :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-repack.md
> +- Egalement suprime les objets redondants après empaquetage:
```suggestion
- Egalement suprime les objets redondants après empaquetage :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-remote.md
> +- Ajoute un dépot:
```suggestion
- Ajoute un dépot :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-remote.md
> +- Affiche les informations a propos d'un dépot:
```suggestion
- Affiche les informations a propos d'un dépot :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-remote.md
> +- Affiche les dépots existants, leur nom et url:
```suggestion
- Affiche les dépots existants, leur nom et url :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-remote.md
> +- Change l'url d'un dépot (ajouter `--add` pour conserver l'url existante):
```suggestion
- Change l'url d'un dépot (ajouter `--add` pour conserver l'url existante) :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-remote.md
> +- Suprime un dṕot:
```suggestion
- Suprime un dṕot :
```

2020-11-10 10:57 UTC, navarroaxel commented on pages.fr/common/git-remote.md
> +- Renome un dépot:
```suggestion
- Renome un dépot :
```

2020-11-10 11:16 UTC, navarroaxel approved these changes

2020-11-10 11:17 UTC, merged