flutter: add test command
tldr-pages/tldr pull request #4625
Opened 2020-10-10 19:55 UTC by ev-john

Page requested #4190

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-10 19:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4625) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4625) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4625) it.</sub>

2020-10-11 06:02 UTC, navarroaxel requested changes
Hi @ev-john welcome. Just a little fix.

2020-10-11 06:02 UTC, navarroaxel commented on pages/common/flutter.md
> +- Run tests in terminal from the root of the project:
```suggestion
- Run tests in a terminal from the root of the project:
```

2020-10-11 16:00 UTC, ev-john commented
Thanks @navarroaxel

2020-10-11 16:01 UTC, navarroaxel approved these changes

2020-10-12 21:32 UTC, sbrl approved these changes
Thanks, @ev-john :heart:

2020-10-12 21:39 UTC, merged