gh: add repo clone example
tldr-pages/tldr pull request #4635
Opened 2020-10-11 12:57 UTC by aaditkamat

- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).

2020-10-11 14:14 UTC, navarroaxel requested changes
Hi @aaditkamat, thanks for your submission. I left a comment.

Remember that you can create pages like `gh-alias.md`, `gh-clone.md`, etc. to explain every subcommand in detail.

2020-10-11 14:14 UTC, navarroaxel commented on pages/common/gh.md
> +`gh repo clone {{OWNER/REPO}}`
Please use lower case and with full name:
```suggestion
`gh repo clone {{owner}}/{{repository}}`
```

2020-10-13 09:31 UTC, owenvoke approved these changes
LGTM after @navarroaxel's comment has been addressed.

I also agree that we can probably split `gh` up into sub-commands in future. 👍🏻

2020-10-13 10:36 UTC, navarroaxel approved these changes
Hey @aaditkamat, I applied the format fix to merge this PR. Thanks for your work!

2020-10-13 10:37 UTC, merged

2020-10-14 01:28 UTC, aaditkamat commented
Thank you @navarroaxel and @owenvoke!