exiftool: Change weblink
tldr-pages/tldr pull request #4648
Opened 2020-10-11 19:23 UTC by gutjuri

since the ond one doesn't work anymore

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-11 19:24 UTC, navarroaxel requested changes

2020-10-11 19:24 UTC, navarroaxel commented on pages/common/exiftool.md
> +> More information: <https://exiftool.org/>.
```suggestion
> More information: <https://exiftool.org>.
```

2020-10-11 19:26 UTC, navarroaxel approved these changes
LGTM

2020-10-12 13:01 UTC, owenvoke approved these changes

2020-10-12 13:02 UTC, merged