gnome-extensions: add page
tldr-pages/tldr pull request #4652
Opened 2020-10-11 21:14 UTC by BhaskarDutta2209

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-11 21:24 UTC, navarroaxel requested changes
Hey @BhaskarDutta2209, welcome and thanks for your submission. I left some comments.

Please add examples for:
```
gnome-extensions help {{subcommand}}
```
and:
```
gnome-extensions uninstall
```

2020-10-11 21:24 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +> Manage gnome extensions from the terminal.
```suggestion
> Manage gnome extensions from the terminal.
> More information: <https://wiki.gnome.org/Projects/GnomeShell/Extensions>.
```

2020-10-11 21:24 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +- Show info about a particular extension:
```suggestion
- Display information about a specific extension:
```

2020-10-11 21:24 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +`gnome-extensions info "{{extension name}}"`
The help page says `UUID` so:
```suggestion
`gnome-extensions info "{{extension_id}}"`
```

2020-10-11 21:24 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +`gnome-extensions enable "{{extension name}}"`
We use `_` for variable names:
```suggestion
`gnome-extensions enable "{{extension_id}}"`
```

2020-10-11 21:24 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +- Enable a particular extension:
```suggestion
- Enable a specific extension:
```

2020-10-11 21:24 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +- Disable particular extension:
```suggestion
- Disable specific extension:
```

2020-10-11 21:24 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +`gnome-extension disable "{{extension name}}"`
```suggestion
`gnome-extension disable "{{extension_id}}"`
```

2020-10-11 21:37 UTC, navarroaxel requested changes
Please @BhaskarDutta2209 revert the changes on files `build.sh` and `test.sh`

2020-10-11 22:03 UTC, BhaskarDutta2209 commented
I didn't make any changes to the file. I just use chmod to change the permissioning. No code is altered. If needed I can close this PR and create a new one if needed.

2020-10-11 22:07 UTC, navarroaxel requested changes

2020-10-11 22:07 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +`gnome-extensions help list`
```suggestion
`gnome-extensions help {{subcommand}}`
```

2020-10-11 22:07 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +- Display help for any sub-command, for example list:
Based on the `git` example:
```suggestion
- Display help for a subcommand (like `list`):
```

2020-10-11 22:11 UTC, navarroaxel requested changes

2020-10-11 22:11 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +- Disable specific extension:
```suggestion
- Disable a specific extension:
```

2020-10-11 22:11 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +- Uninstall specific extension:
```suggestion
- Uninstall a specific extension:
```

2020-10-11 22:11 UTC, navarroaxel commented on pages/linux/gnome-extensions.md
> +- Check the version:
```suggestion
- Display the version:
```

2020-10-11 22:28 UTC, navarroaxel approved these changes

2020-10-12 13:04 UTC, owenvoke approved these changes
Nice work, thanks @BhaskarDutta2209! 👍🏻

2020-10-12 13:04 UTC, merged

2020-10-12 13:35 UTC, BhaskarDutta2209 commented
Thanks a lot.