pi: add page
tldr-pages/tldr pull request #4653
Opened 2020-10-11 21:25 UTC by neel24

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-11 21:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4653) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4653) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4653) it.</sub>

2020-10-11 22:27 UTC, navarroaxel requested changes
Hey @neel24, welcome and thanks for your submission. I left some comments.

2020-10-11 22:27 UTC, navarroaxel commented on pages/linux/pi.md
> +> Prints 100 decimal digits of Archimedes' constant pi or a number of digits specified by an integer parameter on the command line.
The command could be used for Math operations in Bash, so it's something more than display numbers:
```suggestion
> Compute decimal Archimedes' constant Pi on the command line.
```

2020-10-11 22:27 UTC, navarroaxel commented on pages/linux/pi.md
> +- Print 100 decimal digits of Archimedes' constant pi:
```suggestion
- Display 100 decimal digits of Archimedes' constant Pi:
```

2020-10-11 22:27 UTC, navarroaxel commented on pages/linux/pi.md
> +- Show summary of options:
```suggestion
- Display help:
```

2020-10-11 22:27 UTC, navarroaxel commented on pages/linux/pi.md
> +- Show current version of program:
```suggestion
- Display version:
```

2020-10-11 22:27 UTC, navarroaxel commented on pages/linux/pi.md
> +- Output recommended readings:
```suggestion
- Display recommended readings:
```

2020-10-11 22:27 UTC, navarroaxel commented on pages/linux/pi.md
> +- Print *number* decimal digits of Archimedes' constant pi:
```suggestion
- Display `number` decimal digits of Archimedes' constant Pi:
```

2020-10-12 13:17 UTC, neel24 commented
@navarroaxel, I made the suggested changes with the [Make suggested changes](https://github.com/tldr-pages/tldr/pull/4653/commits/310b2ddfea6d850d56ec7c8a2cc6dd345ade2dbd) commit.

2020-10-12 13:23 UTC, navarroaxel approved these changes

2020-10-12 21:56 UTC, sbrl reviewed
Thanks for the new page, @neel24 ! I've left a comment below for you to review.

2020-10-12 21:56 UTC, sbrl commented on pages/linux/pi.md
> +- Display `number` decimal digits of Archimedes' constant Pi:
Perhaps this will read better?
```suggestion
- Display a specified number of decimal digits of Archimedes' constant Pi:
```

2020-10-14 21:57 UTC, sbrl approved these changes
Looks ok to me! Thanks, @neel24 😺

2020-10-14 21:57 UTC, merged