iex: add page
tldr-pages/tldr pull request #4658
Opened 2020-10-12 06:11 UTC by Schoonology

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-12 06:12 UTC, Schoonology commented
This was intended to address the `iex` component of https://github.com/tldr-pages/tldr/issues/2680. (The `elixir` half may take more thought, and will come later.)

2020-10-12 13:38 UTC, navarroaxel requested changes
Hi @Schoonology. Just 1 comment.

2020-10-12 13:38 UTC, navarroaxel commented on pages/common/iex.md
> +- Start an empty interactive session:
is `empty` for command history? I prefer the example description without empty:
```suggestion
- Start an interactive session:
```

2020-10-13 06:02 UTC, Schoonology commented
@navarroaxel Again, completely reasonable. 👍🏼

2020-10-13 18:39 UTC, navarroaxel approved these changes

2020-10-14 15:26 UTC, owenvoke approved these changes

2020-10-14 15:26 UTC, merged