nodenv: add page
tldr-pages/tldr pull request #4659
Opened 2020-10-12 06:23 UTC by Schoonology

I didn't notice an issue requesting `nodenv`, but went looking for other commonly used but missing commands. There is a tldr page for `rbenv` and other variants, but `nodenv` was conspicuously missing.

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-12 13:22 UTC, navarroaxel requested changes
Hi @Schoonology, welcome and thanks for your submission. I left some comments.

2020-10-12 13:22 UTC, navarroaxel commented on pages/common/nodenv.md
> +- Install a version of NodeJS:
Based on the `node` page we use `Node.js`:
```suggestion
- Install a specific version of Node.js:
```

2020-10-12 13:22 UTC, navarroaxel commented on pages/common/nodenv.md
> +- Use a specific version of NodeJS across the whole system:
```suggestion
- Use a specific version of Node.js across the whole system:
```

2020-10-12 13:22 UTC, navarroaxel commented on pages/common/nodenv.md
> +- Use a specific version of NodeJS with a directory:
```suggestion
- Use a specific version of Node.js with a directory:
```

2020-10-12 13:22 UTC, navarroaxel commented on pages/common/nodenv.md
> +- Show the NodeJS version for the current directory:
```suggestion
- Display the Node.js version for the current directory:
```

2020-10-12 13:22 UTC, navarroaxel commented on pages/common/nodenv.md
> +- Show the location of a NodeJS-installed command, e.g. `npm`:
```suggestion
- Display the location of a Node.js installed command (e.g. `npm`):
```

2020-10-12 23:54 UTC, Schoonology commented
@navarroaxel All of those suggestions made complete sense, so I accepted them.

2020-10-13 10:57 UTC, navarroaxel approved these changes

2020-10-14 15:31 UTC, owenvoke approved these changes

2020-10-14 15:32 UTC, merged