translate windows/sigverif
tldr-pages/tldr pull request #4669
Opened 2020-10-12 16:55 UTC by isrmicha

adding pt_BR translation to windows/sigverif.md

- [ ] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-12 18:30 UTC, navarroaxel requested changes
Hi @isrmicha, welcome and thanks for your submission. I left 1 comment.

Remember that you can translate more than 1 page in 1 PR, just send 1 commit per file. (no more than 10 translation per PR).
1 PR per page is only required for the primary (English) pages

2020-10-12 18:30 UTC, navarroaxel commented on pages.pt_BR/windows/sigverif.md
> +- Abre a itnerface de verificação de assinatura.
```suggestion
- Abre a interface de verificação de assinatura.
```

2020-10-12 20:58 UTC, schneiderl approved these changes
Hi, 
Thank you for your PR. It is really appreciated. 
It looks good to me after @navarroaxel comment is addressed.

2020-10-12 23:06 UTC, isrmicha reviewed
Thanks for the review

2020-10-13 10:48 UTC, navarroaxel approved these changes

2020-10-13 10:48 UTC, merged