exif: add page
tldr-pages/tldr pull request #4670
Opened 2020-10-12 17:31 UTC by ThatWeirdAndrew

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

#4639

2020-10-12 21:45 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2020-10-12 21:57 UTC, ThatWeirdAndrew commented on pages/linux/exif.md
> +`exif --output=new.jpg --ifd=0 --tag=Artist --set-value="John Smith" --no-fixup {{image.jpg}}`
Should new.jpg and --ifd=0 be surrounded in curly brackets as well?

2020-10-12 22:18 UTC, sbrl commented on pages/linux/exif.md
> +`exif --output=new.jpg --ifd=0 --tag=Artist --set-value="John Smith" --no-fixup {{image.jpg}}`
Ah, I missed that! Nice catch - suggestions updated.

2020-10-12 22:29 UTC, ThatWeirdAndrew commented
Alright, I've edited the file so it should be good now.

2020-10-14 14:29 UTC, navarroaxel requested changes
Hi @ThatWeirdAndrew welcome and thanks for your submission. I left some comments.

2020-10-14 16:55 UTC, ThatWeirdAndrew commented
Done

2020-10-14 17:00 UTC, navarroaxel approved these changes

2020-10-14 22:43 UTC, sbrl approved these changes
Thanks, @ThatWeirdAndrew!

2020-10-14 22:43 UTC, merged