jpegtran: add page
tldr-pages/tldr pull request #4695
Opened 2020-10-14 22:47 UTC by ev-john

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Page requested #4641

2020-10-15 10:59 UTC, navarroaxel requested changes
Hey @ev-john, thanks for your submission. I left some comments.

We need to add an example for `-outfile` because in a command concatenation with `&&`, the user can't use the `stdout` and `-outfile` is easier.

Maybe something like this (also saying the coordinates is not required for the point 0,0):

- Crop the image to a rectangular region of width `W` and height `H` from the upper left corner:

`jpegtran -crop {{W}}x{{H}} -outfile {{path/to/output.jpg}} {{path/to/image.jpg}}`

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +`jpegtran -flip {{horizontal|vertical}} {{/path/to/image.jpg}}`
```suggestion
`jpegtran -flip {{horizontal|vertical}} {{path/to/image.jpg}} > {{path/to/output.jpg}}`
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +- Mirror image horizontally or vertically:
```suggestion
- Mirror an image horizontally or vertically:
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +- Rotate image 90, 180 or 270 degrees clockwise:
```suggestion
- Rotate an image 90, 180 or 270 degrees clockwise:
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +`jpegtran -rotate {{90|180|270}} {{/path/to/image.jpg}}`
```suggestion
`jpegtran -rotate {{90|180|270}} {{path/to/image.jpg}} > {{path/to/output.jpg}}`
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +`jpegtran -transpose {{/path/to/image.jpg}}`
```suggestion
`jpegtran -transpose {{path/to/image.jpg}} > {{path/to/output.jpg}}`
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +`jpegtran -transverse {{/path/to/image.jpg}}`
```suggestion
`jpegtran -transverse {{path/to/image.jpg}} > {{path/to/output.jpg}}`
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +`jpegtran -grayscale {{/path/to/image.jpg}}`
```suggestion
`jpegtran -grayscale {{path/to/image.jpg}} > {{path/to/output.jpg}}`
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +- Crop the image to a rectangular region of width `W` and height `H`, starting at point `X` and `Y`:
We should say which is the origin (point 0,0) of the coordinate system. Maybe this is better:
```suggestion
- Crop the image to a rectangular region of width `W` and height `H`, starting at point `X` and `Y` from the upper left corner:
```

2020-10-15 10:59 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +`jpegtran -crop WxH+X+Y {{/path/to/image.jpg}}`
The variables should be between `{}`:
```suggestion
`jpegtran -crop {{W}}x{{H}}+{{X}}+{{Y}} {{path/to/image.jpg}} > {{path/to/output.jpg}}`
```

2020-10-15 21:42 UTC, ev-john commented
Thanks a lot @navarroaxel, everything updated now.

2020-10-16 08:50 UTC, owenvoke approved these changes
LGTM!

2020-10-16 09:13 UTC, navarroaxel requested changes
Thanks @ev-john, just a clarification.

2020-10-16 09:13 UTC, navarroaxel commented on pages/linux/jpegtran.md
> +- Crop the image to a rectangular region of width `W` and height `H` from the upper left corner:
```suggestion
- Crop the image to a rectangular region of width `W` and height `H` from the upper left corner, saving the output to a specific file:
```

2020-10-16 09:14 UTC, navarroaxel approved these changes

2020-10-16 09:14 UTC, merged

2020-10-16 18:14 UTC, ev-john commented
Thank you @navarroaxel @owenvoke :)