git-prune: add page
tldr-pages/tldr pull request #4696
Opened 2020-10-15 05:09 UTC by sanehab

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-15 05:17 UTC, sanehab commented
I'm interested in joining tldr to contribute more than just adding new pages, i can help with git and linux commands.

2020-10-15 11:23 UTC, navarroaxel commented
> I'm interested in joining tldr to contribute more than just adding new pages, i can help with git and linux commands.

@sanehab You should merge 5 non-trivial PRs to be allowed to [become a collaborator](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#when-to-change-roles). :muscle:

2020-10-15 11:25 UTC, navarroaxel requested changes
Thanks @sanehab, just 1 comment.

2020-10-15 11:25 UTC, navarroaxel commented on pages/common/git-prune.md
> +- Prune unreachable objects and show what has been pruned to stdout:
```suggestion
- Prune unreachable objects and display what has been pruned to `stdout`:
```

2020-10-15 12:20 UTC, navarroaxel approved these changes

2020-10-16 08:53 UTC, owenvoke approved these changes
Nice job, thanks @sanehab! 👏🏻

2020-10-16 08:53 UTC, merged