clamav, cmus: add Spanish translation
tldr-pages/tldr pull request #4698
Opened 2020-10-15 13:38 UTC by andoniaf

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-15 13:39 UTC, andoniaf commented on pages.es/linux/cmus.md
> +> Usa flechas para navegar, `<enter/return>` para seleccionar, y los números 1-8 para cambiar entra las diferentes vistas.
En la versión en ingles https://github.com/tldr-pages/tldr/blob/master/pages/linux/cmus.md habla de "arrow keys", pero creo que en Español no hace falta especificar que hablamos del teclado.

2020-10-15 14:55 UTC, navarroaxel requested changes
Hi @andoniaf, I left a few comments.

2020-10-15 14:55 UTC, navarroaxel commented on pages.es/linux/clamav.md
> +`clamscan {{path/to/file}}`
Por favor, traducí los params de ser posible:
```suggestion
`clamscan {{ruta/al/archivo}}`
```

2020-10-15 14:55 UTC, navarroaxel commented on pages.es/linux/clamav.md
> +`clamscan --recursive --infected {{path/to/directory}}`
```suggestion
`clamscan --recursive --infected {{ruta/al/directorio}}`
```

2020-10-15 14:55 UTC, navarroaxel commented on pages.es/linux/clamav.md
> +`clamscan --recursive --move={{directory}}`
```suggestion
`clamscan --recursive --move={{directorio}}`
```

2020-10-15 14:55 UTC, navarroaxel commented on pages.es/linux/cmus.md
> +> Usa flechas para navegar, `<enter/return>` para seleccionar, y los números 1-8 para cambiar entra las diferentes vistas.
Basandome en [Wikipedia](https://es.wikipedia.org/wiki/Tecla_de_direcci%C3%B3n), las posibles traducciones son: Las teclas de dirección, teclas de navegación, teclas de movimiento del cursor o flechas de dirección.
Creo que la traducción más clara para los lectores sería:
```suggestion
> Use las teclas de dirección para navegar, `<enter/return>` para seleccionar, y los números 1-8 para cambiar entra las diferentes vistas.
```
Or para más despistados:
```suggestion
> Use las teclas de flecha para navegar, `<enter/return>` para seleccionar, y los números 1-8 para cambiar entra las diferentes vistas.
```

2020-10-15 14:55 UTC, navarroaxel commented on pages.es/linux/cmus.md
> +`:add {{path/to/file_or_directory}}`
```suggestion
`:add {{ruta/al/archivo_o_directorio}}`
```

2020-10-16 05:11 UTC, andoniaf commented on pages.es/linux/cmus.md
> +> Usa flechas para navegar, `<enter/return>` para seleccionar, y los números 1-8 para cambiar entra las diferentes vistas.
Si, "teclas de dirección" era mi segunda opción favorita, voy a hacer el cambio. 👍

2020-10-16 05:11 UTC, andoniaf commented on pages.es/linux/clamav.md
> +`clamscan {{path/to/file}}`
Menudo despiste! Pasé tanto rato debatiendo conmigo mismo sobre "las flechas" que luego no me di cuenta de esto... Voy a cambiarlo, gracias! 😄

2020-10-16 09:09 UTC, navarroaxel requested changes
Hi @andoniaf, just 2 comments. Please don't push force because is harder for us to track the suggestion and changes.

2020-10-16 09:09 UTC, navarroaxel commented on pages.es/linux/clamav.md
> +- Escanear archivo en busca de virus:
```suggestion
- Escanear un archivo en busca de virus:
```

2020-10-16 09:09 UTC, navarroaxel commented on pages.es/linux/cmus.md
> +- Abrir cmus con un directorio concreto:
```suggestion
- Abrir cmus en un directorio concreto:
```

2020-10-16 10:24 UTC, andoniaf commented on pages.es/linux/clamav.md
> +- Escanear archivo en busca de virus:
👍

2020-10-16 10:24 UTC, andoniaf commented on pages.es/linux/cmus.md
> +- Abrir cmus con un directorio concreto:
👍

2020-10-16 10:27 UTC, navarroaxel approved these changes

2020-10-19 16:25 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-19 16:25 UTC, merged