translations for Docker, apt and apt-get
tldr-pages/tldr pull request #4707
Opened 2020-10-16 08:13 UTC by MarkusSYT

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-16 09:48 UTC, navarroaxel requested changes
Hey @MarkusSYT, welcome and thanks for your submission.

I'm sorry but your translations don't follow our rules completely, but don't worry. we can merge this if you:
1. Remove the `chmod.md` and `docker.md` pages from this PR.
2. Sync the `apt.md` and `apt-get.md` with the primary (English) pages (remove the examples that you have added).

Remember do not push force to the PRs because is harder for us to track the suggestion and changes, and feel free to open new PRs to add or edit the docker and chmod primary pages.

2020-10-16 09:48 UTC, navarroaxel commented on pages.de/common/chmod.md
> +- Kurzschreibweise um Rechte für User, Groups und others zu legen indem die Berechtigungen in Oktal angelegt werden:
The translation should be made from the primary (English) pages.

If you want to add an extra example you should send a PR for edit the `pages/common/chmod.md`, and you can include the update the German translation for `pages.de/common/chmod.md` in that PR.

2020-10-16 09:48 UTC, navarroaxel commented on pages.de/common/docker.md
> +- Baut einen Container über eine Dockerfile im selben Verzeichnis
The translation should be made from the primary (English) pages.

For docker we have specific subcommand pages like `docker-build.md`, `docker-start.md` etc.

If you want to add or edit examples you should send a PR for edit the primary page, and you can include the update for the German translation for the same page in that PR.

2020-10-16 09:48 UTC, navarroaxel commented on pages.de/common/docker.md
> +- Ein nicht verwendetest Image löschen:
Remember that the pages can have up to 8 examples, otherwise we can't merge the PR.

2020-10-16 09:48 UTC, navarroaxel commented on pages.de/linux/apt.md
> +`apt upgrade`
This example is not present in the primary page.

2020-10-16 09:48 UTC, navarroaxel commented on pages.de/linux/apt.md
> +`apt dist-upgrade`
These examples are not present in the primary page. Remember that the pages can have up to 8 example and this have 12.

2020-10-16 10:44 UTC, MarkusSYT commented
I changed it sorry for the trouble.

2020-10-16 10:50 UTC, navarroaxel approved these changes
Thanks @MarkusSYT, don't worry. I hope you'll send more PR!

2020-10-16 19:18 UTC, navarroaxel commented
No @MarkusSYT :scream_cat:  rollback that push force, maybe using `git reflog`

2020-10-16 19:33 UTC, MarkusSYT commented
Again sorry for that mistake :/
wasn't expecting that

2020-10-17 09:25 UTC, navarroaxel requested changes
Don't worry @MarkusSYT. I just left some comments.

2020-10-17 09:25 UTC, navarroaxel commented on pages.de/linux/ip-address.md
> +`ip address add {{IP Adresse}} dev {{eth0}}`
We use `snake_case` for variables:
```suggestion
`ip address add {{ip_adresse}} dev {{eth0}}`
```

2020-10-17 09:25 UTC, navarroaxel commented on pages.de/linux/ip-address.md
> +`ip address delete {{IP Adresse}} dev {{eth0}}`
```suggestion
`ip address delete {{ip_adresse}} dev {{eth0}}`
```

2020-10-17 09:25 UTC, navarroaxel commented on pages.de/linux/dnf.md
> +- Sucht nach speziellen Keywords:
Is there a translation for `keyword`?

2020-10-17 09:25 UTC, navarroaxel commented on pages.de/linux/ip.md
> +`ip addr add/del {{ip}}/{{mask}} dev {{interface}}`
Are there translations for `mask` and `interface`?

2020-10-17 10:19 UTC, MarkusSYT commented
there would be a translation for mask and interface but it is not used in information technology

2020-10-17 10:22 UTC, navarroaxel approved these changes

2020-10-19 16:41 UTC, sbrl approved these changes
Thanks, @MarkusSYT!

2020-10-19 16:41 UTC, sbrl commented
I'm going to  squash this to merge.

2020-10-19 16:41 UTC, merged