jq: add an example of skipping non-JSON lines
tldr-pages/tldr pull request #4711
Opened 2020-10-16 15:00 UTC by vforvova

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Hi 👋🏼

I add a new example that I find useful in my day-to-day work as it helps me to deal with reading JSON log streams with occasionally appearing non-JSON lines. For example, if you read a Node.js logger which produces JSON entries and from time to time you receive some non-JSON log entries from the Node.js itself.

Although the page has 9 examples already I decided to try it out anyway. I understand that the aim is to make the output as easy and beginner-friendly as possible, so I won't get hard feelings if the PR ends up closed. 🤗

2020-10-17 10:34 UTC, navarroaxel requested changes
Hi @vforvova, welcome and thanks for your submission. I didn't know that `jq` can skip invalid JSON lines :scream_cat:.

We should reduce the page to 8 examples :thinking: I think we can start merging the example 4 (`.[0]`) and 5 (`[0].key_name`). Could you try?

2020-10-18 17:02 UTC, vforvova commented
@navarroaxel sure. Will try to make something meaningful out of it 🤔

2020-10-18 18:24 UTC, vforvova commented
@navarroaxel please take a look, I am not sure if it is good.

2020-10-19 17:44 UTC, sbrl reviewed
While the example you're  adding is great @vforvova, it seems like it's an advanced use-case that's  designed to solve a specific problem. It's always challenging with pages like this to keep the example number down ( `awk` and `sed` also come to mind), but in tldr-pages it's also worth keeping the beginner in mind. Keeping the examples simple is helpful or the beginner to understand the basic syntax.

However, it looks like a great command to add to a more general jq cheat sheet.

2020-10-24 13:44 UTC, navarroaxel commented
Sorry @vforvova but after talk about this your example looks advanced for this pages and not common to use. Please, I invite you to continue contributing in this project.

2020-11-04 14:42 UTC, vforvova commented
@navarroaxel @sbrl hey guys, thanks for the feedback! It is fair enough and I am fine 😊 I guess it is ok to close the PR then, should it be me?

2020-11-04 20:20 UTC, closed without merging