ls, mv, rm: add Spanish translations
tldr-pages/tldr pull request #4718
Opened 2020-10-17 06:27 UTC by nicomt

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-17 09:39 UTC, navarroaxel requested changes
Hi @nicomt, welcome and thanks for your submission. I left some comments.

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/mv.md
> +> Mover o renombra archivos y directorios.
```suggestion
> Mueve o renombra archivos y directorios.
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/mv.md
> +- Mover archivos en ubicaciones arbitrarias:
Entiendo que hay que usar el imperativo como `lista` en `ls`:
```suggestion
- Mueve archivos en ubicaciones arbitrarias:
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/mv.md
> +- Solicitar confirmación antes de sobrescribir archivos existentes, independientemente de los permisos del archivo:
```suggestion
- Solicita confirmación antes de sobrescribir archivos existentes, independientemente de los permisos del archivo:
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/mv.md
> +- Mover archivos en modo detallado, mostrando los archivos después de moverlos:
```suggestion
- Mueve archivos en modo detallado, mostrando los archivos después de moverlos:
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/mv.md
> +- No sobrescribir archivos existentes en el destino:
```suggestion
- No sobrescribe archivos existentes en el destino:
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/mv.md
> +- Mover sin solicitar confirmación antes de sobrescribir archivos existentes:
I don't like the example descriptions for the English page:
```suggestion
- Mueve sin solicitar confirmación antes de sobrescribir archivos existentes:
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/rm.md
> +> Eliminar archivos o directorios.
```suggestion
> Elimina archivos o directorios.
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/rm.md
> +`rm {{ruta/hacia/archivo}} {{ruta/hacia/otro/archivo}}`
:thinking: Some Spanish pages use `ruta/hacia` but I prefer `ruta/al`, I think sounds a more complete sentence:
```suggestion
`rm {{ruta/al/archivo}} {{ruta/al/otro/archivo}}`
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/rm.md
> +`rm -r {{ruta/hacia/directorio}}`
```suggestion
`rm -r {{ruta/al/directorio}}`
```

2020-10-17 09:39 UTC, navarroaxel commented on pages.es/common/rm.md
> +`rm -rf {{ruta/hacia/directorio}}`
```suggestion
`rm -rf {{ruta/al/directorio}}`
```

2020-10-17 17:22 UTC, nicomt commented
@navarroaxel Thanks for reviewing the pull request. I applied all your suggestions

2020-10-17 17:50 UTC, navarroaxel approved these changes

2020-10-19 16:44 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-19 16:44 UTC, merged