gh: improve doc and add new example to cover all main gh commands
tldr-pages/tldr pull request #4722
Opened 2020-10-17 12:29 UTC by antoine-amara

correct some errors about gh issue view and gh pr view, due to api
changes.
add new example to cover all github process:
repo creation -> issue management -> pr management -> release management

Fixes: https://github.com/tldr-pages/tldr/issues/4701

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-17 17:58 UTC, navarroaxel requested changes
Hey @antoine-amara, sorry but the pages should have up to 8 examples. I think you should use this PR to create more pages to explain each subcommand in detail. Like #4717

2020-10-19 16:30 UTC, antoine-amara commented
Ok, thanks for the advice, I will update the commit and only keep the fixes.
I will update the PR title for clarity.

2020-10-19 16:47 UTC, sbrl requested changes
Hey there, @antoine-amara! Thanks for the edit. Unfortunately as @navarroaxel says we have a limit of 8 examples per page. However, this sounds like a great opportunity to create pages for the different subcommands of `gh` instead. For examples on how this is done, see the page for [`git merge`](https://github.com/tldr-pages/tldr/blob/master/pages/common/git-merge.md) or [`docker ps`](https://github.com/tldr-pages/tldr/blob/master/pages/common/docker-ps.md) for example.

2020-10-19 17:01 UTC, antoine-amara commented
Thanks @navarroaxel and @sbrl , I change the commit to only keep the fixes. I propose to change the order of the documented commands, too.

2020-10-19 18:22 UTC, sbrl requested changes
I've left some comments below for you to review.

2020-10-19 18:22 UTC, sbrl commented on pages/common/gh.md
> +- View and filter repository’s open issues:
Perhaps this will read better?
```suggestion
- View and filter a repository’s open issues:
```

2020-10-19 18:22 UTC, sbrl commented on pages/common/gh.md
> +- Check the status of your pull requests:
Generally we try to avoid the 2nd person (e.g. `you`, `your`, etc) in tldr-pages :slightly_smiling_face:

Can this be reworded at all?

2020-10-20 14:28 UTC, antoine-amara commented
thanks for the review @sbrl , I push a commit with some updates.

2020-10-24 12:22 UTC, sbrl approved these changes
Thanks, @antoine-amara!

2020-10-24 13:46 UTC, navarroaxel approved these changes

2020-10-24 13:46 UTC, merged