git-describe: add french translation
tldr-pages/tldr pull request #4724
Opened 2020-10-17 13:17 UTC by antoine-amara

add french translation for git-describe sub-command.

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-17 18:27 UTC, navarroaxel requested changes
Thanks @antoine-amara, just a few fixes.

2020-10-17 18:27 UTC, navarroaxel commented on pages.fr/common/git-describe.md
> +- Créer un nom avec un hash de commit de 4 lettres:
```suggestion
- Créer un nom avec un hash de commit de 4 lettres :
```

2020-10-17 18:27 UTC, navarroaxel commented on pages.fr/common/git-describe.md
> +- Créer un nom pour le dernier commit d'une branche donnée:
```suggestion
- Créer un nom pour le dernier commit d'une branche donnée :
```

2020-10-17 18:27 UTC, navarroaxel commented on pages.fr/common/git-describe.md
> +- Décrire un tag:
```suggestion
- Décrire un tag :
```

2020-10-17 18:27 UTC, navarroaxel commented on pages.fr/common/git-describe.md
> +- Générer un nom avec le chemin complet du tag:
```suggestion
- Générer un nom avec le chemin complet du tag :
```

2020-10-17 18:27 UTC, navarroaxel commented on pages.fr/common/git-describe.md
> +- Créer un nom unique pour le commit courant (le nom contient le tag le plus recent, le nombre de commits additionnel, and le hash abrégé du commit):
Please use the space before the `:`.
```suggestion
- Créer un nom unique pour le commit courant (le nom contient le tag le plus recent, le nombre de commits additionnel, and le hash abrégé du commit) :
```

2020-10-19 16:26 UTC, antoine-amara commented
thanks for the review, I fix the typos.

2020-10-19 16:38 UTC, navarroaxel approved these changes

2020-10-19 18:12 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

Feel free to open 1 big PR if you're translating lots of pages, with 1 commit per page  :-)

2020-10-19 18:15 UTC, merged