gradle: Add spanish translation
tldr-pages/tldr pull request #4728
Opened 2020-10-17 16:22 UTC by vfrico

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Hello, I've added the translation in spanish for gralde page.

2020-10-17 18:36 UTC, navarroaxel requested changes
Hi @vfrico, welcome and thanks for your submission. We use the present indicative for the example descriptions. I left some comments.

2020-10-17 18:36 UTC, navarroaxel commented on pages.es/common/gradle.md
> +- Compilar un proyecto:
```suggestion
- Compila un proyecto:
```

2020-10-17 18:36 UTC, navarroaxel commented on pages.es/common/gradle.md
> +- Excluit la tarea *test*:
```suggestion
- Excluye la tarea `test`:
```

2020-10-17 18:36 UTC, navarroaxel commented on pages.es/common/gradle.md
> +- Ejecutar en modo offline para prevenir que gradle acceda a la red durante una compilación:
```suggestion
- Ejecuta en modo offline para prevenir que gradle acceda a la red durante una compilación:
```

2020-10-17 18:36 UTC, navarroaxel commented on pages.es/common/gradle.md
> +- Limpiar el directorio de compilación:
```suggestion
- Limpia el directorio de compilación:
```

2020-10-17 18:36 UTC, navarroaxel commented on pages.es/common/gradle.md
> +- Compilar y generar un paquete:
```suggestion
- Compila y genera un paquete:
```

2020-10-17 22:28 UTC, vfrico commented
I've pushed a new commit with the new changes. Thanks!

2020-10-18 03:00 UTC, navarroaxel approved these changes

2020-10-19 17:11 UTC, sbrl reviewed
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-19 17:15 UTC, sbrl reviewed
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-19 17:16 UTC, sbrl approved these changes

2020-10-19 17:16 UTC, merged