ag, adguardhome: add Chinese translation
tldr-pages/tldr pull request #4732
Opened 2020-10-17 17:23 UTC by y1zhou

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-17 17:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4732) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4732) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4732) it.</sub>

2020-10-17 19:35 UTC, navarroaxel requested changes
Hi @y1zhou, welcome and thanks for your submission. I left 1 comment.

2020-10-17 19:35 UTC, navarroaxel commented on pages.zh/common/ag.md
> +> 查看更多信息: <https://github.com/ggreer/the_silver_searcher>.
```suggestion
> 更多信息: <https://github.com/ggreer/the_silver_searcher>.
```

2020-10-17 19:45 UTC, navarroaxel approved these changes

2020-10-19 16:55 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-19 16:56 UTC, merged