aws quicksight: add page
tldr-pages/tldr pull request #4738
Opened 2020-10-18 00:19 UTC by ahonarmand

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-18 03:39 UTC, navarroaxel requested changes
Hi @ahonarmand, welcome and thanks for your submission. I left some comments

2020-10-18 03:39 UTC, navarroaxel commented on pages/common/aws-quicksight.md
> +> CLI for AWS QuickSight - access QuickSight entities.
```suggestion
> CLI for AWS QuickSight.
> Access QuickSight entities.
```

2020-10-18 03:39 UTC, navarroaxel commented on pages/common/aws-quicksight.md
> +- Show data-sets:
Based on the AWS doc page
```suggestion
- List datasets:
```

2020-10-18 03:39 UTC, navarroaxel commented on pages/common/aws-quicksight.md
> +- See details of a dataset such as its input and output columns:
Maybe this is better:
```suggestion
- Display detailed information about a dataset:
```

2020-10-18 03:39 UTC, navarroaxel commented on pages/common/aws-quicksight.md
> +- See who has access to the dataset and what kind of actions they can perform on the dataset:
```suggestion
- Display who has access to the dataset and what kind of actions they can perform on the dataset:
```

2020-10-18 03:39 UTC, navarroaxel commented on pages/common/aws-quicksight.md
> +- Show users:
```suggestion
- List users:
```

2020-10-18 03:39 UTC, navarroaxel commented on pages/common/aws-quicksight.md
> +- Show groups:
```suggestion
- List groups:
```

2020-10-18 03:39 UTC, navarroaxel commented on pages/common/aws-quicksight.md
> +- Show dashboards:
```suggestion
- List dashboards:
```

2020-10-18 04:17 UTC, navarroaxel approved these changes

2020-10-19 17:19 UTC, sbrl approved these changes
Thanks, @ahonarmand!

2020-10-19 17:20 UTC, merged