notmuch: add page
tldr-pages/tldr pull request #4745
Opened 2020-10-18 07:14 UTC by Sadeeed

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Ref: #1162

2020-10-18 13:49 UTC, navarroaxel requested changes
Hey @Sadeeed, I left some comments.

2020-10-18 13:49 UTC, navarroaxel commented on pages/common/notmuch.md
> +`notmuch tag +{{custom-tag}} {{"search-term"}}`
We use snake_case for variable names and quotes outside:
```suggestion
`notmuch tag +{{custom_tag}} "{{search_term}}"`
```

2020-10-18 13:49 UTC, navarroaxel commented on pages/common/notmuch.md
> +- Remove tags for all messages matching the search term:
is 1 tag?
```suggestion
- Remove a tag for all messages matching a search term:
```

2020-10-18 13:49 UTC, navarroaxel commented on pages/common/notmuch.md
> +`notmuch tag -{{custom-tag}} {{"search-term"}}`
```suggestion
`notmuch tag -{{custom_tag}} "{{search_term}}"`
```

2020-10-18 13:49 UTC, navarroaxel commented on pages/common/notmuch.md
> +`notmuch search --format={{json|text}} --output={summary|threads|messages|files|tags} --limit={{X}} {{"search-term"}}`
```suggestion
`notmuch search --format={{json|text}} --output={{summary|threads|messages|files|tags}} --limit={{X}} "{{search_term}}"`
```

2020-10-18 13:49 UTC, navarroaxel commented on pages/common/notmuch.md
> +`notmuch reply --format={{default|headers-only}} --reply-to={{sender|all}} {{"search-term"}}`
```suggestion
`notmuch reply --format={{default|headers-only}} --reply-to={{sender|all}} "{{search_term}}"`
```

2020-10-18 13:49 UTC, navarroaxel commented on pages/common/notmuch.md
> +`notmuch search --format={{json|text}} --output={{summary|threads|messages|files|tags}} {{"search-term"}}`
```suggestion
`notmuch search --format={{json|text}} --output={{summary|threads|messages|files|tags}} "{{search_term}}"`
```

2020-10-18 13:49 UTC, navarroaxel commented on pages/common/notmuch.md
> +`notmuch count --output={{messages|threads}} {{"search-term"}}`
```suggestion
`notmuch count --output={{messages|threads}} "{{search_term}}"`
```

2020-10-18 13:50 UTC, navarroaxel requested changes

2020-10-18 13:50 UTC, navarroaxel commented on pages/common/notmuch.md
> +- Add tags for all messages matching the search term:
```suggestion
- Add a tag for all messages matching a search term:
```

2020-10-19 16:42 UTC, navarroaxel approved these changes

2020-10-19 18:17 UTC, sbrl approved these changes
Thanks, @Sadeeed! Looks ok to me. Just made a teensy grammar fix.

2020-10-19 18:17 UTC, merged

2020-10-19 18:18 UTC, sbrl commented
Just 1 command left in #1162! :tada: