cdk: add page
tldr-pages/tldr pull request #4756
Opened 2020-10-18 21:01 UTC by honarmand-io

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-19 11:06 UTC, navarroaxel requested changes
Hey @honarmand-io thanks, I left some comments.

2020-10-19 11:06 UTC, navarroaxel commented on pages/common/cdk.md
> +> CLI for AWS Cloud Development Kit (CDK).
```suggestion
> A CLI for AWS Cloud Development Kit (CDK).
```

2020-10-19 11:06 UTC, navarroaxel commented on pages/common/cdk.md
> +- Deploy the specified stack(s):
maybe
```suggestion
- Deploy a space-separated list of stacks:
```

2020-10-19 11:06 UTC, navarroaxel commented on pages/common/cdk.md
> +- Destroy the specified stack(s):
```suggestion
- Destroy a space-separated list of stacks:
```

2020-10-20 02:49 UTC, ahonarmand commented
Thanks for the review @navarroaxel !

2020-10-24 12:20 UTC, sbrl requested changes

2020-10-24 12:20 UTC, sbrl commented on pages/common/cdk.md
> +# aws cdk
This needs to exactly match the name of the command being documented.

2020-10-28 17:41 UTC, sbrl approved these changes
Thanks, @honarmand-io!

2020-10-28 17:41 UTC, merged