addr2line: add page
tldr-pages/tldr pull request #4761
Opened 2020-10-19 14:42 UTC by sedrubal

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- ~~The page description includes a link to documentation or a homepage (if applicable).~~

2020-10-19 15:37 UTC, navarroaxel requested changes
Thanks @sedrubal, just a few comments.

2020-10-19 15:37 UTC, navarroaxel commented on pages/linux/addr2line.md
> +- Get the file name and line number of an instruction address of an executable in the source code:
Maybe this is better
```suggestion
- Display the filename and line number of the source code from an instruction address of an executable:
```

2020-10-19 15:37 UTC, navarroaxel commented on pages/linux/addr2line.md
> +- Get the file name and line number of an instruction address of an executable in the source code:
Otherwise:
```suggestion
- Display the filename and line number from an instruction address of an executable in the source code:
```

2020-10-19 15:37 UTC, navarroaxel commented on pages/linux/addr2line.md
> +`addr2line --exe=<executable> <address>`
we use `{{}}` for tokens:
```suggestion
`addr2line --exe={{path/to/executable}} {{address}}`
```

2020-10-19 15:37 UTC, navarroaxel commented on pages/linux/addr2line.md
> +`addr2line --exe=<executable> --functions <address>`
```suggestion
`addr2line --exe={{path/to/executable}} --functions {{address}}`
```

2020-10-19 15:37 UTC, navarroaxel commented on pages/linux/addr2line.md
> +- Also show the function name:
```suggestion
- Display function name, filename and line number:
```

2020-10-19 15:37 UTC, navarroaxel commented on pages/linux/addr2line.md
> +`addr2line --exe=<executable> --functions --demangle <address>`
```suggestion
`addr2line --exe={{path/to/executable}} --functions --demangle {{address}}`
```

2020-10-20 09:21 UTC, sedrubal commented
Thanks for the review. I changed the mentioned things.

2020-10-20 12:31 UTC, navarroaxel approved these changes

2020-10-24 12:19 UTC, sbrl approved these changes
Thanks, @sedrubal!

I've just applied some minor grammatical fixes, if that's ok?

2020-10-24 12:21 UTC, merged

2020-10-24 13:27 UTC, sedrubal commented
> Thanks, @sedrubal!
> 
> I've just applied some minor grammatical fixes, if that's ok?

Yes, thanks :+1: