command: add -v example
tldr-pages/tldr pull request #4762
Opened 2020-10-19 14:47 UTC by sedrubal

- ~~The page (if new), does not already exist in the repo.~~
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- ~~The page description includes a link to documentation or a homepage (if applicable).~~

2020-10-19 14:55 UTC, navarroaxel requested changes
Hey @sedrubal, nice example. I left comments.

2020-10-19 14:55 UTC, navarroaxel commented on pages/common/command.md
> +- Find the path to the executable of the command ls:
Based on this output:
```
$ command -v ls
alias ls='ls --color=auto'
$ command -v bat
/usr/bin/bat
```
Maybe this is better:
```suggestion
- Display the path to the executable or the alias definition of a specific command:
```

2020-10-19 14:55 UTC, navarroaxel commented on pages/common/command.md
> +`command -v {{ls}}`
`command -v {{command}}` doesn't look good. Maybe:
```suggestion
`command -v {{command_name}}`
```

2020-10-20 09:24 UTC, sedrubal commented
Thanks for the fast review. I changed the mentioned things.

2020-10-20 10:59 UTC, navarroaxel approved these changes

2020-10-24 12:12 UTC, sbrl approved these changes
Thanks, @sedrubal!

2020-10-24 12:12 UTC, merged