gpupdate: add page
tldr-pages/tldr pull request #4772
Opened 2020-10-20 00:46 UTC by skitau

Another regular tool in the belt.

Happy Hacktoberfest!

2020-10-24 02:47 UTC, navarroaxel requested changes
Thanks @skitau, just 1 comments.

2020-10-24 02:47 UTC, navarroaxel commented on pages/windows/gpupdate.md
> +`gpupdate /Target=:{{Computer|User}}`
`target` is in lower case in the docs, also we use `snake_case` for variables like `user`:
```suggestion
`gpupdate /target=:{{computer|user}}`
```

2020-10-26 23:39 UTC, skitau commented
Forgot post a reply... Thanks for the pickup @navarroaxel . Have fixed.

2020-10-28 12:34 UTC, navarroaxel approved these changes

2020-10-28 18:49 UTC, sbrl approved these changes
Thanks, @skitau!

2020-10-28 18:50 UTC, merged