gh-release: add page
tldr-pages/tldr pull request #4773
Opened 2020-10-20 02:17 UTC by abeltay

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Add a new page for `gh release` subcommand

Ref: #4701

2020-10-22 00:21 UTC, navarroaxel requested changes
Hey @abeltay, this is a nice page to do. I left some comments.

I think we should add examples about `gh release download` and using the `--pattern` maybe for download `.deb` packages.
Also an example for `gh release upload`.

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +# gh-release
the page header is without `-` because should be exact to the subcommand:
```suggestion
# gh release
```

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +> More information: <https://cli.github.com/manual/gh_release_delete>.
```suggestion
> More information: <https://cli.github.com/manual/gh_release>.
```

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +> Manage GitHub pull requests from the command line.
This subcommand is specific for releases
```suggestion
> Manage GitHub releases from the command line.
```

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +- List GitHub Releases in a repository (Default limit 30):
Maybe we can say `GitHub repository` in the first example, but I think repeat `GitHub` in every example is noisy
```suggestion
- List releases in a GitHub repository, limit 30 items:
```

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +- List GitHub Releases in a repository (Default limit 30):
Otherwise:
```suggestion
- List the last 30 releases in a GitHub repository:
```

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +- View a GitHub Release:
```suggestion
- Display information about a specific release:
```

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +- Create a new GitHub Release:
```suggestion
- Create a new release:
```

2020-10-22 00:21 UTC, navarroaxel commented on pages/common/gh-release.md
> +- Delete a GitHub Release:
```suggestion
- Delete a specific release:
```

2020-10-23 12:10 UTC, navarroaxel commented
@abeltay I really like if you can add `gh release download|upload` examples, is not required, but I really like to have those examples.

2020-10-23 16:32 UTC, abeltay commented
@navarroaxel I've added upload and download commands

2020-10-23 16:37 UTC, navarroaxel requested changes
Just 1 comment.

2020-10-23 16:37 UTC, navarroaxel commented on pages/common/gh-release.md
> +`gh release upload {{tag}} {{file1 file2 ...}}`
```suggestion
`gh release upload {{tag}} {{path/to/file1}} {{path/to/file2}}`
```

2020-10-23 16:44 UTC, navarroaxel approved these changes

2020-10-24 05:25 UTC, navarroaxel commented
Please @abeltay **don't** push force, it's harder to use to track the changes and suggestions.

2020-10-24 05:26 UTC, navarroaxel approved these changes

2020-10-24 05:26 UTC, navarroaxel commented on pages/common/gh-release.md
> +- List releases in a GitHub repository, limit 30 items:
```suggestion
- List releases in a GitHub repository, limited to 30 items:
```

2020-10-24 13:09 UTC, sbrl approved these changes
Thanks, @abeltay!

2020-10-24 13:09 UTC, merged