kubectl: add pt_BR translation
tldr-pages/tldr pull request #4783
Opened 2020-10-20 17:00 UTC by caduvieira

- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-20 17:10 UTC, navarroaxel requested changes
Hi @caduvieira, I left 1 comment.

2020-10-20 17:10 UTC, navarroaxel commented on pages.pt_BR/common/kubectl.md
> +> Mais informações em: <https://kubernetes.io/docs/reference/kubectl/>.
We use this format:
```suggestion
> Mais informações: <https://kubernetes.io/docs/reference/kubectl/>.
```

2020-10-20 17:43 UTC, navarroaxel approved these changes

2020-10-24 12:26 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-24 12:26 UTC, merged