bat: add Spanish translation
tldr-pages/tldr pull request #4785
Opened 2020-10-20 18:25 UTC by agucova

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-20 18:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4785) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4785) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4785) it.</sub>

2020-10-20 18:30 UTC, agucova commented
Not sure how I screwed up the branches, I made the pull request directly from my fork to master.

2020-10-20 18:37 UTC, navarroaxel requested changes
Hi @agucova, welcome and thanks for your submission. I left some comments.

2020-10-20 18:37 UTC, navarroaxel commented on pages.es/common/bat.md
> +> Un clon de `cat` con resaltado de sintaxis e integración con `git`.
Usamos `Git` porque no hablamos del comando sino del VCS en general.
```suggestion
> Un clon de `cat` con resaltado de sintaxis e integración con Git.
```

2020-10-20 18:37 UTC, navarroaxel commented on pages.es/common/bat.md
> +- Concatenar varios archivos creando un nuevo archivo:
```suggestion
- Concatena varios archivos creando un nuevo archivo:
```

2020-10-20 18:37 UTC, navarroaxel commented on pages.es/common/bat.md
> +- Imprimir los contenidos de un archivo a la salida estándar (`stdout`):
Comunmente usamos `salida estándar` o `stdout` como sinonimos, no los relacionamos porque suponemos que el usuario ya sabe.
```suggestion
- Imprime los contenidos de un archivo a la salida estándar:
```

2020-10-20 18:37 UTC, navarroaxel commented on pages.es/common/bat.md
> +`bat {{archivo1}} {{archivo2}} > {{archivo_objetivo}}`
`archivo_objetivo` es una traducción muy literal, y no se usa mucho en español. Mejor usar `archivo_resultado` o `archivo_final`:
```suggestion
`bat {{archivo1}} {{archivo2}} > {{archivo_final}}`
```

2020-10-20 18:37 UTC, navarroaxel commented on pages.es/common/bat.md
> +`bat {{archivo1}} {{archivo2}} >> {{archivo_objetivo}}`
```suggestion
`bat {{archivo1}} {{archivo2}} >> {{archivo_final}}`
```

2020-10-20 18:42 UTC, agucova commented
Thanks for the suggestions, I'll keep a closer eye on future translations.

2020-10-20 18:48 UTC, navarroaxel requested changes

2020-10-20 18:48 UTC, navarroaxel commented on pages.es/common/bat.md
> +`bat -n {{file}}`
```suggestion
`bat -n {{archivo}}`
```

2020-10-20 18:48 UTC, navarroaxel commented on pages.es/common/bat.md
> +`bat --language json {{file.json}}`
```suggestion
`bat --language json {{archivo.json}}`
```

2020-10-20 19:05 UTC, navarroaxel approved these changes

2020-10-21 21:33 UTC, ferrvic commented
For the missing homepage you could use the link to the main repository here, in github: https://github.com/sharkdp/bat

2020-10-21 22:20 UTC, agucova commented
> For the missing homepage you could use the link to the main repository here, in github: [sharkdp/bat](https://github.com/sharkdp/bat)

I was thinking of doing that, but since the original English translation didn't include it either, I thought it was necessary to first modify it there. (Keeping them in sync)

I'm not sure if that's the case.

2020-10-21 22:33 UTC, ferrvic commented
> > For the missing homepage you could use the link to the main repository here, in github: [sharkdp/bat](https://github.com/sharkdp/bat)
> 
> I was thinking of doing that, but since the original English translation didn't include it either, I thought it was necessary to first modify it there. (Keeping them in sync)
> 
> I'm not sure if that's the case.

Well, I'm not sure what is the policy of the mantainers on this cases. Anyway, if you want, you could always submit another patch for the english page to add the project web page.

2020-10-21 22:59 UTC, agucova commented
I've added it, pending my PR to the english page.

2020-10-21 23:15 UTC, navarroaxel commented
@agucova You can add/edit an English page (and only 1) and include the translations in the same PR. So, you can add the edition for the English page in this PR and include the Spanish translation.
And why not add the link for the pages in `it`, `de`, `ko` and `pt_BR`.

2020-10-22 11:08 UTC, navarroaxel commented
LGTM

2020-10-24 12:41 UTC, sbrl approved these changes

2020-10-24 12:45 UTC, merged