docker: add Spanish translation
tldr-pages/tldr pull request #4789
Opened 2020-10-21 00:47 UTC by franciscollanquipichun

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-21 00:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4789) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4789) it.</sub>

2020-10-21 10:18 UTC, navarroaxel requested changes
Hi @franciscollanquipichun. Thanks, I left some comments.

Remember that you can send all your translations in 1 PR, just keep 1 commit per page and up to 15 pages per PR. The rule that 1 page per PR is for the primary (English) pages.

Also you can add/edit a primary page and include the Spanish translation in the same PR.

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +`docker run --name {{nombre_contenedor_personalizado}} {{imagen}}`
```suggestion
`docker run --name {{nombre_de_contenedor}} {{imagen}}`
```

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +`docker {{start|stop}} {{nombre_contenedor}}`
```suggestion
`docker {{start|stop}} {{nombre_de_contenedor}}`
```

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +- Inicia una shell dentro de un contenedor en ejecución:
```suggestion
- Inicia una línea de Comandos dentro de un contenedor en ejecución:
```

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +`docker logs -f {{nombre_contenedor}}`
```suggestion
`docker logs -f {{nombre_de_contenedor}}`
```

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +`docker rm {{nombre_contenedor}}`
```suggestion
`docker rm {{nombre_de_contenedor}}`
```

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +`docker exec -it {{nombre_contenedor}} {{sh}}`
```suggestion
`docker exec -it {{nombre_de_contenedor}} {{sh}}`
```

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +- Busca y sigue los registros de un contenedor:
```suggestion
- Obtiene y sigue los registros de un contenedor:
```

2020-10-21 10:18 UTC, navarroaxel commented on pages.es/common/docker.md
> +- Extraer una imagen de un registro de Docker:
Creo que está en la traducción más acertada:
```suggestion
- Descarga una imagen desde un registro de Docker:
```

2020-10-21 22:16 UTC, franciscollanquipichun commented
Hi @navarroaxel, thanks for the comments and suggestions

2020-10-21 23:01 UTC, navarroaxel approved these changes

2020-10-23 01:59 UTC, ivanhercaz approved these changes
Looks good to me! ¡Gracias @franciscollanquipichun!

2020-10-23 01:59 UTC, merged