docker-compose: add spanish translation
tldr-pages/tldr pull request #4790
Opened 2020-10-21 00:51 UTC by franciscollanquipichun

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-21 10:05 UTC, navarroaxel requested changes
Hi @franciscollanquipichun, welcome and thanks for your submission. Just 1 comment.

2020-10-21 10:05 UTC, navarroaxel commented on pages.es/common/docker-compose.md
> +- Detiene todo los contenedores:
```suggestion
- Detiene todos los contenedores en ejecución:
```

2020-10-21 12:15 UTC, navarroaxel approved these changes

2020-10-23 01:55 UTC, ivanhercaz approved these changes
Looks good to me! ¡Gracias @franciscollanquipichun!

2020-10-23 01:56 UTC, merged