mysql: Add spanish translation
tldr-pages/tldr pull request #4794
Opened 2020-10-21 19:38 UTC by ferrvic

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-21 19:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4794) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4794) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4794) it.</sub>

2020-10-21 20:33 UTC, navarroaxel requested changes
Hi @ferrvic, welcome and thanks for your submission. I left 1 comment.

2020-10-21 20:33 UTC, navarroaxel commented on pages.es/common/mysql.md
> +> Herramienta en línea de comandos para gestionar bases de datos MySQL
Que yo recuerde, en español se usa `de`:
```suggestion
> Herramienta de línea de comandos para gestionar bases de datos MySQL
```

2020-10-21 20:33 UTC, navarroaxel commented on pages.es/common/mysql.md
> +> Herramienta en línea de comandos para gestionar bases de datos MySQL
Que yo recuerde, en español se usa `de`:
```suggestion
> Herramienta de línea de comandos para gestionar bases de datos MySQL
```

2020-10-21 20:33 UTC, navarroaxel commented on pages.es/common/mysql.md
> +`mysql -e "source {{fichero.sql}}" {{nombre_base_de_datos}}`
Aunque en España se usa `fichero` o `archivo`. Mejor si usamos `archivo` que es lo más común en Latam:
```suggestion
`mysql -e "source {{archivo.sql}}" {{nombre_base_de_datos}}`
```

2020-10-21 21:20 UTC, ferrvic commented
I've applied the suggested changes. Thanks @navarroaxel!

2020-10-21 21:29 UTC, navarroaxel approved these changes

2020-10-24 12:39 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-24 12:39 UTC, merged