e2image: add page
tldr-pages/tldr pull request #4795
Opened 2020-10-21 22:33 UTC by deeeeeeps

Page requested #4250

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-21 22:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4795) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4795) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4795) it.</sub>

2020-10-22 19:52 UTC, navarroaxel requested changes
Hi @deeeeeeps, welcome and thanks for your submission. I left 2 comments.

2020-10-22 19:52 UTC, navarroaxel commented on pages/linux/e2image.md
> +`e2image {{/dev/sdXN}} {{path/to/image-file}}`
The variable names should be in `snake_case`, so it should be `image_file` but I think just `file` is enough. What do you think?
```suggestion
`e2image {{/dev/sdXN}} {{path/to/file}}`
```

2020-10-22 19:52 UTC, navarroaxel commented on pages/linux/e2image.md
> +- Save metadata located on device to the specified file:
```suggestion
- Write metadata located on device to a specific file:
```

2020-10-24 02:43 UTC, navarroaxel requested changes
Just a few more changes.

2020-10-24 02:43 UTC, navarroaxel commented on pages/linux/e2image.md
> +`e2image -I {{/dev/sdXN}} {{path/to/image-file}}`
```suggestion
`e2image -I {{/dev/sdXN}} {{path/to/file}}`
```

2020-10-24 02:43 UTC, navarroaxel commented on pages/linux/e2image.md
> +`e2image -r {{/dev/sdXN}} {{path/to/image-file}}`
```suggestion
`e2image -r {{/dev/sdXN}} {{path/to/file}}`
```

2020-10-24 02:43 UTC, navarroaxel commented on pages/linux/e2image.md
> +`e2image -Q {{/dev/sdXN}} {{path/to/image-file}}`
```suggestion
`e2image -Q {{/dev/sdXN}} {{path/to/file}}`
```

2020-10-24 13:04 UTC, sbrl commented on pages/linux/e2image.md
> +`e2image -Q {{/dev/sdXN}} {{path/to/image-file}}`
Or even 
```suggestion
`e2image -Q {{/dev/sdXN}} {{path/to/image_file}}`
```

2020-10-24 13:04 UTC, sbrl commented on pages/linux/e2image.md
> +`e2image -I {{/dev/sdXN}} {{path/to/image-file}}`
Or even
```suggestion
`e2image -I {{/dev/sdXN}} {{path/to/image_file}}`
```

2020-10-24 13:04 UTC, sbrl commented on pages/linux/e2image.md
> +`e2image -r {{/dev/sdXN}} {{path/to/image-file}}`
Or even
```suggestion
`e2image -r {{/dev/sdXN}} {{path/to/image_file}}`
```

2020-10-24 13:52 UTC, navarroaxel requested changes

2020-10-24 13:52 UTC, navarroaxel commented on pages/linux/e2image.md
> +`e2image {{/dev/sdXN}} {{path/to/file}}`
```suggestion
`e2image {{/dev/sdXN}} {{path/to/image_file}}`
```

2020-10-25 12:42 UTC, navarroaxel approved these changes

2020-10-28 17:48 UTC, sbrl approved these changes
Thanks, @deeeeeeps!

2020-10-28 17:48 UTC, merged