ifconfig, lua, mkdir: add French translation
tldr-pages/tldr pull request #4796
Opened 2020-10-21 23:38 UTC by ivorysoap

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-10-22 00:10 UTC, navarroaxel requested changes
Thanks @ivorysoap, I left some comments.

2020-10-22 00:10 UTC, navarroaxel commented on pages.fr/common/ifconfig.md
> +`ifconfig eth0`
This is a bug in the English page, the `eth0` should be between `{{}}`:
```suggestion
`ifconfig {{eth0}}`
```
You can add the fix here if you want.

2020-10-22 00:10 UTC, navarroaxel commented on pages.fr/common/ifconfig.md
> +`ifconfig eth0 down`
```suggestion
`ifconfig {{eth0}} down`
```

2020-10-22 00:10 UTC, navarroaxel commented on pages.fr/common/ifconfig.md
> +`ifconfig eth0 up`
```suggestion
`ifconfig {{eth0}} up`
```

2020-10-22 00:10 UTC, navarroaxel commented on pages.fr/common/ifconfig.md
> +`ifconfig eth0 {{addresse_ip}}`
```suggestion
`ifconfig {{eth0}} {{addresse_ip}}`
```

2020-10-22 03:27 UTC, ivorysoap commented
Sure, thanks for that.  Made the edits.

2020-10-22 10:56 UTC, navarroaxel approved these changes

2020-10-24 13:02 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-24 13:03 UTC, merged