lynx: add page
tldr-pages/tldr pull request #4815
Opened 2020-10-22 21:44 UTC by alimalek71

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-22 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4815) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4815) before we can accept your contribution.<br/><hr/>**Ali Malek** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4815) it.</sub>

2020-10-22 21:49 UTC, alimalek71 commented
#4629

2020-10-23 12:57 UTC, navarroaxel requested changes
Thanks @alimalek71 I left some comments.

2020-10-23 12:57 UTC, navarroaxel commented on pages/common/lynx.md
> +`lynx -cookie_file {{example.com}}`
Should we add a `{{path/to/file}}`?

2020-10-23 12:57 UTC, navarroaxel commented on pages/common/lynx.md
> +- Specify a file to use to read/write cookies:
```suggestion
- Open a link, using a specific file to read and write cookies:
```

2020-10-23 12:59 UTC, navarroaxel commented
Looks like there is another PR for this command #4764, but I prefer this page format. What should we do @sbrl?

2020-10-23 16:42 UTC, alimalek71 commented on pages/common/lynx.md
> +`lynx -cookie_file {{example.com}}`
Ops, nice catch yes of course :+1:

2020-10-23 17:04 UTC, navarroaxel commented
@alimalek71 question: if we merge the PR #4764, do you know how to merge from upstream resolving the conflicts and include your examples to the `lynx` page?

2020-10-23 17:22 UTC, alimalek71 commented
> @alimalek71 question: if we merge the PR #4764, do you know how to merge from upstream resolving the conflicts and include your examples to the `lynx` page?

Yes, I know.

2020-11-13 10:53 UTC, navarroaxel commented
@alimalek71 Could you merge the merge Lynx page in this PR?

2020-11-13 11:22 UTC, alimalek71 commented
Yes, I will start working on it soon

2020-11-14 05:42 UTC, alimalek71 commented
All conflicts resolved successfully, sir

2020-11-14 11:33 UTC, navarroaxel commented
@alimalek71 Looks like the merge is not ok. Which command did you use?

2020-11-15 10:21 UTC, alimalek71 commented
> @alimalek71 Looks like the merge is not ok. Which command did you use?

I use rebase! if it's not okay I can revert it and use merging solotion

2020-11-15 13:14 UTC, navarroaxel commented
@alimalek71 Please because all the commit and changes now are in the diff of this PR

2020-11-16 11:53 UTC, alimalek71 commented
I assume it is okay now :) plz recheck it

2020-11-20 09:33 UTC, alimalek71 commented
@alimalek71 requested a review from @navarroaxel

2020-11-21 02:59 UTC, navarroaxel requested changes
Please @alimalek71 leave some examples with the hotkeys to use this app, you can add up to 8 examples.

2020-12-07 04:34 UTC, navarroaxel approved these changes

2020-12-07 13:11 UTC, schneiderl approved these changes

2020-12-07 13:11 UTC, merged

2020-12-12 07:31 UTC, alimalek71 commented
@navarroaxel @schneiderl Thanks you a lot and I am sorry for not being reachable for a long time :heart: