docker-compose: add new example
tldr-pages/tldr pull request #4817
Opened 2020-10-22 22:22 UTC by alimalek71

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-23 12:42 UTC, navarroaxel requested changes
Nice @alimalek71, I left a comment.

2020-10-23 12:42 UTC, navarroaxel commented on pages/common/docker-compose.md
> +- Follow logs for one container:
```suggestion
- Follow logs for a specific container:
```

2020-10-23 16:58 UTC, navarroaxel approved these changes

2020-10-24 12:58 UTC, sbrl approved these changes

2020-10-24 12:59 UTC, sbrl commented
Looks like @CLAAssistant is having a hiccup - merging anyway

2020-10-24 12:59 UTC, merged