docker-images: add new example
tldr-pages/tldr pull request #4819
Opened 2020-10-22 22:43 UTC by alimalek71

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-23 11:28 UTC, navarroaxel requested changes
Thanks @alimalek71. I left some comments.

Could you please edit the other examples, replacing `-a` by `--all` and `-q` for `--quiet`?

2020-10-23 11:28 UTC, navarroaxel commented on pages/common/docker-images.md
> +- List add Docker images contain phrase:
Based on the `docker-ps.md` page:
```suggestion
- List images that contain a substring in their name:
```

2020-10-23 17:28 UTC, alimalek71 commented
> Thanks @alimalek71. I left some comments.
> 
> Could you please edit the other examples, replacing `-a` by `--all` and `-q` for `--quiet`?

Done.

2020-10-23 19:11 UTC, navarroaxel requested changes

2020-10-23 19:11 UTC, navarroaxel commented on pages/common/docker-images.md
> +`docker images {{"*name*"}}`
Out standard is quotes outside the `{{}}`:
```suggestion
`docker images "{{*name*}}"`
```

2020-10-27 09:05 UTC, navarroaxel approved these changes

2020-10-28 18:12 UTC, sbrl approved these changes
Thanks, @alimalek71 :slightly_smiling_face:

2020-10-28 18:12 UTC, merged