New example on oc and some typos fixed
tldr-pages/tldr pull request #4822
Opened 2020-10-23 14:50 UTC by siavashsoleymani

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2020-10-23 15:07 UTC, navarroaxel requested changes
Thanks @siavashsoleymani, just 1 comment.

2020-10-23 15:07 UTC, navarroaxel commented on pages/common/oc.md
> +- Change project to project_name:
Based on `git-checkout.md` and `git-switch.md` pages:
```suggestion
- Switch to an existing project:
```

2020-10-23 16:23 UTC, siavashsoleymani commented
@navarroaxel agree with you, thanks for point out. Done!

2020-10-23 16:33 UTC, navarroaxel approved these changes

2020-10-24 12:57 UTC, sbrl approved these changes
Great catches - thanks, @siavashsoleymani!

2020-10-24 12:58 UTC, merged

2020-10-24 14:57 UTC, siavashsoleymani commented
@sbrl it's my pleasure your welcome