mysqldump: Add spanish translation
tldr-pages/tldr pull request #4823
Opened 2020-10-23 15:58 UTC by ferrvic

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-23 17:09 UTC, navarroaxel requested changes
@ferrvic Thanks for your submission, but the translations should be made from the primary (English) pages. You can add/edit examples to the primary page in this PR and we can merge the edition and the translation together.

2020-10-23 17:09 UTC, navarroaxel commented on pages.es/commom/mysqldump.md
> +- Crea un backup de todas las bases de datos y redirige la salida a un fichero (se le pedirá la contraseña al usuario):
```suggestion
- Crea un backup de todas las bases de datos y redirige la salida a un archivo (se le pedirá la contraseña al usuario):
```

2020-10-24 12:59 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-24 23:37 UTC, ferrvic commented
> @ferrvic Thanks for your submission, but the translations should be made from the primary (English) pages. You can add/edit examples to the primary page in this PR and we can merge the edition and the translation together.

Thanks! Changes done!

2020-10-25 03:09 UTC, navarroaxel commented
@ferrvic you should remove the last example to match the English page, or add the 3rd example to the English page in this PR.

2020-11-04 19:27 UTC, schneiderl approved these changes

2020-11-04 19:32 UTC, navarroaxel approved these changes

2020-11-04 19:32 UTC, merged

2020-11-04 21:39 UTC, LukBukkit commented
Oh I spotted a typo in the folder name, instead of commo~m~, it should be common.
Take a look at the page `pages.es` folder: https://github.com/tldr-pages/tldr/tree/master/pages.es