page added for jcal
tldr-pages/tldr pull request #4833
Opened 2020-10-24 15:17 UTC by siavashsoleymani

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-10-24 21:55 UTC, navarroaxel requested changes
Hey @siavashsoleymani, Thanks for your submission.
When the command has different options (e.g. `cal`) we create a page in `osx` folder and another in the `linux` folder. I see `jcal` has the same content for the `linux` and `osx` folders, then a single copy in `common` is preferred.

2020-10-25 07:17 UTC, siavashsoleymani commented
Hey @navarroaxel thanks for your quick response. 
I thought we put the command in the common folder when all platforms support it, thanks for your explanation.
Done!

2020-10-25 12:42 UTC, navarroaxel approved these changes

2020-10-27 01:43 UTC, siavashsoleymani commented
Hi @navarroaxel would you please mark this as hacktoberfest-accepted if the review process takes time? Because hacktoberfest will ends in three days an I'm a little worried about it.

2020-10-27 10:35 UTC, sbrl reviewed
Thanks for the new page! I've left some comments below for you to review.

2020-10-27 10:35 UTC, sbrl commented on pages/common/jcal.md
> +- Display previous, current and next month:
Perhaps this will read better?
```suggestion
- Display the previous, current, and next months:
```

2020-10-27 10:35 UTC, sbrl commented on pages/common/jcal.md
> +> Prints calendar information in Jalali format, with the current day highlighted.
Perhaps this will read better?
```suggestion
> Display calendar information in the Jalali format, with the current day highlighted.
```

2020-10-27 10:47 UTC, siavashsoleymani commented
@sbrl my pleasure.
I agree with you thanks.
changes are done!

2020-10-27 10:50 UTC, sbrl approved these changes
Thanks, @siavashsoleymani!

2020-10-27 10:50 UTC, merged