gh-config: add page
tldr-pages/tldr pull request #4837
Opened 2020-10-24 17:17 UTC by TheLastGimbus

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Add a new page for `gh config`

I could not figure out what does `--host` option do - neither does it say anywhere in the official documentation. If someone ever knew, it would be nice to fill that

Ref: #4701

2020-10-24 22:56 UTC, navarroaxel requested changes
Thanks @TheLastGimbus, I left some comments.

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +# gh-config
```suggestion
# gh config
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +- Check what git protocol you are using:
We try to avoid `you`, `your`, etc.
```suggestion
- Display what Git protocol is being used:
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +- Change text editor to vim:
Based on `git-config.md`:
```suggestion
- Set text editor to Vim:
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +- Change protocol to ssh:
```suggestion
- Set protocol to SSH:
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +`gh config set git_protocol ssh`
The argument options should be highlighted:
```suggestion
`gh config set git_protocol {{ssh}}`
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +`gh config set editor vim`
```suggestion
`gh config set editor {{vim}}`
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +- Reset to default editor:
```suggestion
- Reset to default text editor:
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +`gh config set editor ""`
```suggestion
`gh config set editor {{""}}`
```

2020-10-24 22:56 UTC, navarroaxel commented on pages/common/gh-config.md
> +`gh config set prompt disabled`
```suggestion
`gh config set prompt {{disabled}}`
```

2020-10-25 03:17 UTC, navarroaxel approved these changes

2020-10-26 10:23 UTC, owenvoke reviewed
LGTM, but I'm just wondering if it'd be worth adding two examples to the top for generic `get`/`set` to cover any future additional config properties. i.e.

```markdown
- Get a specific configuration value:

`gh config get {{key}}`

- Set a specific configuration value:

`gh config set {{key}} {{value}}`
```

Also, I can't find the `--host` option that was mentioned, so not sure what that is. 🤷🏻

2020-10-26 11:58 UTC, TheLastGimbus commented
I added `set` example - `get` is obvious to figure out from it

> Also, I can't find the --host option

When you type `gh config set --help` - `-h, --host string   Set per-host setting` - I tried if it's about repo-specific, but couldn't get it to work - it's probably for different Enterprise hosts :shrug:

2020-10-26 13:41 UTC, owenvoke approved these changes
LGTM! Ah, yeah. I'd assume that's for per-Enterprise settings. 👍🏻 We can probably exclude that though for now.

2020-10-26 22:18 UTC, TheLastGimbus commented
Hey, so, can someone merge this? Everything is approved (I don't know why cla doesn't complete, but i've signed :ok_hand: ) soo...

2020-10-27 10:38 UTC, sbrl approved these changes
Thanks, @TheLastGimbus!

2020-10-27 10:38 UTC, merged

2020-10-27 10:59 UTC, owenvoke commented
Sorry, I was planning on merging but forgot to after I'd approved it. Thanks @TheLastGimbus 👍🏻