hunspell: add page
tldr-pages/tldr pull request #4842
Opened 2020-10-24 20:35 UTC by newAM

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-24 20:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4842) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4842) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4842) it.</sub>

2020-10-24 23:25 UTC, navarroaxel requested changes
Hi @newAM, welcome and thanks for your submission. I left some comments.

2020-10-24 23:25 UTC, navarroaxel commented on pages/common/hunspell.md
> +> More information: <http://hunspell.github.io/>.
```suggestion
> More information: <https://hunspell.github.io>.
```

2020-10-24 23:25 UTC, navarroaxel commented on pages/common/hunspell.md
> +`hunspell {{file}}`
```suggestion
`hunspell {{path/to/file}}`
```

2020-10-24 23:25 UTC, navarroaxel commented on pages/common/hunspell.md
> +`hunspell -d en_US {{file}}`
```suggestion
`hunspell -d {{en_US}} {{path/to/file}}`
```

2020-10-24 23:25 UTC, navarroaxel commented on pages/common/hunspell.md
> +`hunspell -l {{file}}`
```suggestion
`hunspell -l {{path/to/file}}`
```

2020-10-24 23:25 UTC, navarroaxel commented on pages/common/hunspell.md
> +- List bad words in a file:
```suggestion
- List misspelled words in a file:
```

2020-10-26 04:10 UTC, newAM commented
Made the suggested changes :+1:

2020-10-26 10:15 UTC, owenvoke approved these changes

2020-10-26 11:14 UTC, navarroaxel approved these changes

2020-10-26 11:14 UTC, merged