Add Indonesian language translation to Vue
tldr-pages/tldr pull request #4848
Opened 2020-10-25 06:30 UTC by mul14

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-25 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4848) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4848) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4848) it.</sub>

2020-10-25 12:48 UTC, navarroaxel approved these changes

2020-10-25 12:49 UTC, navarroaxel requested changes

2020-10-25 12:49 UTC, navarroaxel commented on pages.id/common/vue-init.md
> +`vue init {{path/to/template_directory}} {{project_name}}`
Please translate the arguments for get this easier for non-English speakers.

2020-10-25 14:20 UTC, navarroaxel approved these changes

2020-10-28 17:55 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-10-28 17:56 UTC, merged