badblocks, ddrescue, fdisk, fsck, ioping, smartctl, wipefs: change /dev/sda into /dev/sdX
tldr-pages/tldr pull request #4861
Opened 2020-10-25 20:26 UTC by Agno94

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-10-25 20:29 UTC, navarroaxel requested changes
Just 1 comment.

2020-10-25 20:29 UTC, navarroaxel commented on pages/linux/ddrescue.md
> +`sudo ddrescue --force --no-scrape {{/dev/sdX}} {{/dev/sdb}} {{path/to/log.txt}}`
```suggestion
`sudo ddrescue --force --no-scrape {{/dev/sdX}} {{/dev/sdY}} {{path/to/log.txt}}`
```

2020-10-25 20:38 UTC, navarroaxel approved these changes

2020-10-28 18:01 UTC, sbrl approved these changes
Thanks, @Agno94!

2020-10-28 18:02 UTC, sbrl commented
Looks like there's a conflict preventing the merge here @Agno94 - would you be able to assist here at all please?

2020-10-28 19:26 UTC, navarroaxel commented
@Agno94 Looks ready for merge, right?

2020-10-28 21:12 UTC, Agno94 commented
Yes

2020-10-29 11:21 UTC, merged

2020-10-29 11:23 UTC, navarroaxel commented
@Agno94 I invite you to collaborate sending a PR for add this rule to the <https://github.com/tldr-pages/tldr/blob/master/contributing-guides/style-guide.md> file.