rpmbuild: add new page
tldr-pages/tldr pull request #4864
Opened 2020-10-26 08:41 UTC by hellojukay

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-26 11:57 UTC, owenvoke requested changes
Hi @hellojukay, thanks for the new page. Just a few minor changes to the syntax, but otherwise looks good.

Also, do you know if there's a good official link that could be added to the page? 🤔

2020-10-26 11:57 UTC, owenvoke commented on pages/linux/rpmbuild.md
> +`rpmbuild -ba {{spec file}}`
```suggestion
`rpmbuild -ba {{path/to/spec_file}}`
```

2020-10-26 11:57 UTC, owenvoke commented on pages/linux/rpmbuild.md
> +`rpmbuild -bb {{spec file}}`
```suggestion
`rpmbuild -bb {{path/to/spec_file}}`
```

2020-10-26 11:57 UTC, owenvoke commented on pages/linux/rpmbuild.md
> +`rpmbuild -bb {{spec file}}  --define "{{variable1}} {{value1}}" --define "{{variable2 value2}}"`
```suggestion
- Specify additional variables when building a package:

`rpmbuild -bb {{path/to/spec_file}}  --define "{{variable1}} {{value1}}" --define "{{variable2 value2}}"`
```

2020-10-28 09:26 UTC, owenvoke approved these changes

2020-10-28 09:50 UTC, navarroaxel requested changes
Hey @hellojukay, just 2 comments.

2020-10-28 09:50 UTC, navarroaxel commented on pages/linux/rpmbuild.md
> +> More information: <https://docs.fedoraproject.org/en-US/quick-docs/creating-rpm-packages/index.html>.
```suggestion
> More information: <https://docs.fedoraproject.org/en-US/quick-docs/creating-rpm-packages/>.
```

2020-10-28 09:50 UTC, navarroaxel commented on pages/linux/rpmbuild.md
> +`rpmbuild -bb {{path/to/spec_file}}  --define "{{variable1}} {{value1}}" --define "{{variable2 value2}}"`
There is an extra space and the `{{}}` are not consistent.
```suggestion
`rpmbuild -bb {{path/to/spec_file}} --define "{{variable1}} {{value1}}" --define "{{variable2}} {{value2}}"`
```

2020-10-31 20:19 UTC, navarroaxel approved these changes

2020-10-31 20:20 UTC, merged