make: add --environment-overrides example
tldr-pages/tldr pull request #4870
Opened 2020-10-26 22:41 UTC by Lodifice

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

I find this option quite useful when I have to deal with poorly written Makefiles that do not define variables with `?=`.

2020-10-26 22:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4870) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4870) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4870) it.</sub>

2020-10-27 12:39 UTC, navarroaxel requested changes
Hi @Lodifice, welcome and thanks for your submission. LGTM

Can you add the more information link in the page header?
```
> More information: <https://www.gnu.org/software/make/manual/make.html>.
```

2020-10-27 13:31 UTC, Lodifice commented
Sure, no problem.

2020-10-27 13:40 UTC, navarroaxel approved these changes
Nice.

2020-10-28 18:20 UTC, sbrl approved these changes
Thanks, @Lodifice!

2020-10-28 18:22 UTC, merged