vnstat: add page
tldr-pages/tldr pull request #4875
Opened 2020-10-27 11:13 UTC by StackOverBuffer

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-27 11:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4875) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4875) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4875) it.</sub>

2020-10-28 18:16 UTC, sbrl requested changes
Thanks for the new page, @StackOverBuffer! I've left some comments below for you to review.

2020-10-28 18:16 UTC, sbrl commented on pages/linux/vnstat.md
> +- Display traffic summary for eth0:
Perhaps this will read better?
```suggestion
- Display traffic summary for a specific network interface:
```

2020-10-28 18:16 UTC, sbrl commented on pages/linux/vnstat.md
> +`vnstat -i eth0`
We use our special `{{token_syntax}}` to indicate values that the user can change :-)
```suggestion
`vnstat -i {{eth0}}`
```

2020-10-28 18:16 UTC, sbrl commented on pages/linux/vnstat.md
> +- Display live stats for eth0:
Perhaps this will read better?
```suggestion
- Display live stats for a specific network interface:
```

2020-10-28 18:16 UTC, sbrl commented on pages/linux/vnstat.md
> +`vnstat -l -i eth0`
Same here about the token syntax
```suggestion
`vnstat -l -i {{eth0}}`
```

2020-10-28 18:16 UTC, sbrl commented on pages/linux/vnstat.md
> +- Show traffic statistics on a hourly basis for the last 24 hours using a bar graph:
Perhaps this will read better?
```suggestion
- Show traffic statistics on an hourly basis for the last 24 hours using a bar graph:
```

2020-10-28 18:16 UTC, sbrl commented on pages/linux/vnstat.md
> +`vnstat -tr 30`
Same here about the token syntax :slightly_smiling_face: 
```suggestion
`vnstat -tr {{30}}`
```

2020-10-28 20:33 UTC, StackOverBuffer commented
Hi, 
thanks for reviewing. I have added your requested changes. Somehow I must have missed the token syntax in the style guide :D

2020-10-31 20:33 UTC, navarroaxel approved these changes

2020-11-01 14:44 UTC, sbrl approved these changes
Thanks, @StackOverBuffer :smiley:

2020-11-01 14:44 UTC, merged