paru: add page
tldr-pages/tldr pull request #4894
Opened 2020-10-29 17:44 UTC by silentnoodlemaster

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-29 17:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4894) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4894) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4894) it.</sub>

2020-10-30 20:55 UTC, owenvoke requested changes
Hi @silentnoodlemaster, thanks for the new page. Just a couple of minor typo changes below, but otherwise looks good to me. 👍🏻

2020-10-30 20:55 UTC, owenvoke commented on pages/linux/paru.md
> +- Interactvley seach and install a package:
```suggestion
- Interactively search for and install a package:
```

2020-10-30 20:55 UTC, owenvoke commented on pages/linux/paru.md
> +- Upgrade AUR pacckages:
```suggestion
- Upgrade AUR packages:
```

2020-10-30 20:55 UTC, owenvoke commented on pages/linux/paru.md
> +- Get information abaout a package:
```suggestion
- Get information about a package:
```

2020-10-30 22:07 UTC, owenvoke approved these changes

2020-11-01 13:42 UTC, sbrl approved these changes
Thanks, @silentnoodlemaster!

2020-11-01 13:42 UTC, merged