snake4: add page
tldr-pages/tldr pull request #4895
Opened 2020-10-29 17:53 UTC by sahilister

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-10-29 17:55 UTC, sahilister commented
Navigation in the game can be done with 4 different sets of key sets. Arrow keys being the easiest has been added to this commit.

2020-11-01 13:08 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2020-11-01 13:08 UTC, sbrl commented on pages/linux/snake4.md
> +> Snake game in terminal.
Perhaps this will read better?
```suggestion
> Snake game in the terminal.
```

2020-11-01 13:08 UTC, sbrl commented on pages/linux/snake4.md
> +- Start snake game:
Perhaps this will read better?
```suggestion
- Start a snake game:
```

2020-11-01 13:08 UTC, sbrl commented on pages/linux/snake4.md
> +- Show highscores:
Perhaps this will read better?
```suggestion
- Show the high scores:
```

2020-11-01 20:19 UTC, navarroaxel approved these changes

2020-11-05 19:34 UTC, sbrl approved these changes

2020-11-05 19:35 UTC, merged