snake4scores: add page
tldr-pages/tldr pull request #4896
Opened 2020-10-29 17:55 UTC by sahilister

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-10-29 17:57 UTC, sahilister commented
Pull request for `snake4` also made at -  #4895

2020-11-01 13:06 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2020-11-01 13:06 UTC, sbrl commented on pages/linux/snake4scores.md
> +> Show highscores of snake4 game.
Perhaps this will read better?
```suggestion
> Show the high scores from the snake4 game.
```

2020-11-01 13:06 UTC, sbrl commented on pages/linux/snake4scores.md
> +- Show highscores:
Perhaps this will read better?
```suggestion
- Show the highscores:
```

2020-11-01 20:26 UTC, navarroaxel approved these changes

2020-11-03 12:45 UTC, owenvoke approved these changes

2020-11-05 19:29 UTC, sbrl approved these changes
Thanks, @sahilister!

2020-11-05 19:29 UTC, merged