Create gh-repo.md
tldr-pages/tldr pull request #4897
Opened 2020-10-29 18:09 UTC by alexroseb

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

Ref: #4701

2020-10-29 18:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4897) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4897) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4897) it.</sub>

2020-10-30 20:44 UTC, owenvoke approved these changes

2020-10-31 20:29 UTC, navarroaxel requested changes
Thanks @alexroseb, just a few comments.

2020-10-31 20:29 UTC, navarroaxel commented on pages/common/gh-repo.md
> +- Fork and clone repository:
```suggestion
- Fork and clone a repository:
```

2020-10-31 20:29 UTC, navarroaxel commented on pages/common/gh-repo.md
> +- Clone repository:
```suggestion
- Clone a repository:
```

2020-10-31 20:29 UTC, navarroaxel commented on pages/common/gh-repo.md
> +- Create new repository (if the repository name is not set, it will default to the name of the current directory):
```suggestion
- Create new a repository (if the repository name is not set, it will default to the name of the current directory):
```

2020-11-04 01:23 UTC, einverne approved these changes
Although there is a minor suggestion, it looks good to me.

2020-11-04 01:23 UTC, einverne commented on pages/common/gh-repo.md
> +- Create a new repository (if the repository name is not set, it will default to the name of the current directory):
```suggestion
- Create a new repository (if the repository name is not set, the default name will be the name of the current directory):
```

Does this sound better?

2020-11-04 11:18 UTC, navarroaxel requested changes

2020-11-04 11:18 UTC, navarroaxel commented on pages/common/gh-repo.md
> +`gh repo fork {{owner}}/{{repository}} --clone=true`
If you use just `--clone`, gh reads `true` implicitly, to use `false` you need to explicitly include it `--clone=false`.
I prefer to simplify the command example:
```suggestion
`gh repo fork {{owner}}/{{repository}} --clone`
```

2020-11-04 11:18 UTC, navarroaxel commented on pages/common/gh-repo.md
> +`gh repo clone {{repository}}`
You should include the `owner` if the repo is not in your account:
```suggestion
`gh repo clone {{owner}}/{{repository}}`
```
Maybe you can add an extra example for clone the repositories in the logged in account.

2020-11-04 18:37 UTC, navarroaxel approved these changes

2020-11-04 18:37 UTC, merged