Improved spanish support
tldr-pages/tldr pull request #4899
Opened 2020-10-29 21:35 UTC by 1-byte-man

Translated 3 tldr pages

2020-10-29 21:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4899) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4899) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4899) it.</sub>

2020-10-30 10:47 UTC, navarroaxel requested changes
Hi @1-byte-man, welcome and thanks for your submission. I left some comments.

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/dnf.md
> +> Administrador de paquetes para RHEL, Centos y Fedora (Reemplaza a yum).
```suggestion
> Administrador de paquetes para RHEL, CentOS y Fedora (Reemplaza a yum).
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/dnf.md
> +> Más información en https://dnf.readthedocs.io
```suggestion
> Más información: <https://dnf.readthedocs.io>.
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/dnf.md
> +- Busca un paquete según palabras clave:
```suggestion
- Busca un paquete usando palabras clave:
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/dnf.md
> +`dnf search {{palabra clave}}`
We use `snake_case` for variable names:
```suggestion
`dnf search {{palabra_clave}}`
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/lsmod.md
> +> Muestra el estado de los módulos cargados en el kernel de linux. Vease tambien `modprobe` el cual carga módulos de kernel
I think that `,` is required for the correct grammar:
```suggestion
> Muestra el estado de los módulos cargados en el kernel de linux.
> Vease tambien `modprobe`, el cual carga módulos de kernel.
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/lsmod.md
> +- liste todos los módulos con:
```suggestion
- Lista todos los módulos de kernel cargados: 
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/lsusb.md
> +> Muestra información sobre puertos y dispositivos USB
```suggestion
> Muestra información sobre puertos y dispositivos USB.
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/lsusb.md
> +- Lista la jerarquía de dispositivos USB en forma de arbol
```suggestion
- Lista la jerarquía de dispositivos USB en forma de árbol:
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/lsusb.md
> +- Lista información destallada acerca de un dispositivo USB en especifico:
```suggestion
- Lista información detallada acerca de un dispositivo USB determinado:
```

2020-10-30 10:47 UTC, navarroaxel commented on pages.es/linux/lsusb.md
> +- Lista solo dispositivos con un ID de ensamblador y producto en especifico:
```suggestion
- Lista solo dispositivos con un ID de ensamblador y producto determinado:
```

2020-10-31 02:41 UTC, navarroaxel approved these changes
Thanks @1-byte-man.

2020-11-01 13:43 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-11-01 13:44 UTC, merged