openfortivpn: add page
tldr-pages/tldr pull request #4902
Opened 2020-10-30 01:03 UTC by robbyrenz

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

I decided to add a man page for a terminal-based VPN program that I use to tunnel to a VPN.

2020-10-30 11:14 UTC, navarroaxel requested changes
Thanks @robbyrenz, I left some comments.

I think you could add some extra examples using a `host` and `port` in the CLI, and another for `trusted-cert`

2020-10-30 11:14 UTC, navarroaxel commented on pages/linux/openfortivpn.md
> +`sudo openfortivpn -c config`
The `--config` is visible in `--help`:
```suggestion
`sudo openfortivpn --config=path/to/config`
```

2020-10-30 11:14 UTC, navarroaxel commented on pages/linux/openfortivpn.md
> +- Connect to a VPN defined in a {{/etc/openfortivpn/config}} file:
```suggestion
- Connect to a VPN using a specific configuration file (defaults to `/etc/openfortivpn/config`):
```

2020-10-30 11:14 UTC, navarroaxel commented on pages/linux/openfortivpn.md
> +`openfortivpn -u {{username}} -p {{password}}`
We prefer the long argument format:
```suggestion
`openfortivpn --username={{username}} --password={{password}}`
```

2020-10-30 11:14 UTC, navarroaxel commented on pages/linux/openfortivpn.md
> +> Client that connects to a VPN.
Based on `openconnect` for Cisco:
```suggestion
> A VPN client, for Fortinet's proprietary PPP+SSL VPN solution.
```

2020-10-31 17:37 UTC, robbyrenz commented
Thanks for the feedback! I have addressed all of them. Hope you can take a look again :smiley:

2020-10-31 19:52 UTC, navarroaxel requested changes
Thanks @robbyrenz just add the page link.

2020-10-31 19:52 UTC, navarroaxel commented on pages/linux/openfortivpn.md
> +> A VPN client, for Fortinet's proprietary PPP+SSL VPN solution.
Oh, I found the repo:
```suggestion
> A VPN client, for Fortinet's proprietary PPP+SSL VPN solution.
> More information: <https://github.com/adrienverge/openfortivpn>.
```

2020-10-31 22:03 UTC, robbyrenz commented on pages/linux/openfortivpn.md
> +> A VPN client, for Fortinet's proprietary PPP+SSL VPN solution.
Thanks for the link! I added it :+1:

2020-10-31 22:30 UTC, navarroaxel approved these changes

2020-11-01 14:52 UTC, sbrl commented on pages/linux/openfortivpn.md
> +`sudo openfortivpn --config=path/to/config`
Perhaps this will read better?
```suggestion
`sudo openfortivpn --config={{path/to/config}}`
```

2020-11-02 12:01 UTC, owenvoke approved these changes
LGTM after @sbrl's change has been applied.

2020-11-02 12:06 UTC, merged