adb*, chmod, weasyprint: add Russian translation
tldr-pages/tldr pull request #4905
Opened 2020-10-30 13:23 UTC by Bodyhealer

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-30 18:39 UTC, navarroaxel requested changes
Thanks @Bodyhealer, I don't speak the language but I have a few comments.

2020-10-30 18:39 UTC, navarroaxel commented on pages.ru/common/adb-reverse.md
> +> Больше информации на <https://developer.android.com/studio/command-line/adb>.
```suggestion
> Больше информации: <https://developer.android.com/studio/command-line/adb>.
```

2020-10-30 18:39 UTC, navarroaxel commented on pages.ru/common/adb-install.md
> +> Больше информации на <https://developer.android.com/studio/command-line/adb>.
```suggestion
> Больше информации: <https://developer.android.com/studio/command-line/adb>.
```

2020-10-30 18:39 UTC, navarroaxel commented on pages.ru/common/adb-shell.md
> +> Больше информации на <https://developer.android.com/studio/command-line/adb>.
```suggestion
> Больше информации: <https://developer.android.com/studio/command-line/adb>.
```

2020-10-30 18:39 UTC, navarroaxel commented on pages.ru/common/weasyprint.md
> +> Больше инофрмации: <https://weasyprint.org/>.
A typo I guess:
```suggestion
> Больше информации: <https://weasyprint.org/>.
```

2020-11-01 13:38 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-11-04 19:27 UTC, schneiderl approved these changes

2020-11-04 19:37 UTC, navarroaxel approved these changes

2020-11-04 19:37 UTC, merged