units.md, wtf.md: Add PT-BR translation
tldr-pages/tldr pull request #4908
Opened 2020-10-30 22:50 UTC by barbaraaliverti

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-30 22:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4908) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4908) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4908) it.</sub>

2020-10-31 02:38 UTC, navarroaxel requested changes
Hi @barbaraaliverti, welcome and thanks for your submission. I left some comments.

I don't speak Portuguese, I speak Spanish :argentina: but I tried to help with the translation :upside_down_face:

2020-10-31 02:38 UTC, navarroaxel commented on pages.pt_BR/linux/units.md
> +> Digitar 'search{{text}}' no console retornará uma lista de todas as unidades que contêm {{text}}.
The `'` is a bug in the English page, and you can add the `More information` link:
```suggestion
> Digitar `search{{text}}` no console retornará uma lista de todas as unidades que contêm `{{text}}`.
> Mais informações: <https://www.gnu.org/software/units/units.html>.
```
You can fix the English page in this PR too.

2020-10-31 02:38 UTC, navarroaxel commented on pages.pt_BR/linux/wtf.md
> +> Mais informações (em inglês): <https://manpages.debian.org/bsdgames/wtf.6.en.html>.
We don't mention the link language:
```suggestion
> Mais informações: <https://manpages.debian.org/bsdgames/wtf.6.en.html>.
```

2020-10-31 02:38 UTC, navarroaxel commented on pages.pt_BR/linux/wtf.md
> +- Expandir um acrônimo:
You shouldn't use infinite, you should use indicative mood, I think you should use:
```suggestion
- Expanda um acrônimo:
```
I could be wrong with this conjugation :grin:

2020-10-31 02:38 UTC, navarroaxel commented on pages.pt_BR/linux/wtf.md
> +- Especificar um tipo de busca computacional:
```suggestion
- Específica um tipo de busca computacional:
```

2020-10-31 20:08 UTC, barbaraaliverti commented
Thanks for your review, @navarroaxel :smile:

2020-10-31 20:10 UTC, navarroaxel requested changes
Thanks @barbaraaliverti, just 1 comment.

2020-10-31 20:10 UTC, navarroaxel commented on pages/linux/units.md
>  > Typing 'search {{text}}' in the prompt will display a list of all of the units containing {{text}}.
```suggestion
> Typing `search {{text}}` in the prompt will display a list of all of the units containing `{{text}}`.
```

2020-10-31 20:13 UTC, navarroaxel approved these changes

2020-11-01 14:30 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-11-01 14:30 UTC, merged