brew: Add spanish translation
tldr-pages/tldr pull request #4909
Opened 2020-10-31 00:45 UTC by moisesnandres

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-31 00:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4909) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4909) it.</sub>

2020-10-31 02:50 UTC, navarroaxel requested changes
Hi @moisesnandres, welcome and thanks for your submission. I left some comments.

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Buscar fórmulas y paquetes disponibles:
Se debe usar el modo indicativo, no infinitivo:
```suggestion
- Busca fórmulas y paquetes disponibles:
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Instalar la última version estable de una fórmula (usar `--devel` para versiones de desarrollo):
```suggestion
- Instala la última version estable de una fórmula (use `--devel` para versiones de desarrollo):
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Mostrar todas las fórmulas instaladas:
```suggestion
- Muestra todas las fórmulas instaladas:
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Mostrar fórmulas instaladas que no dependen de otras:
```suggestion
- Muestra fórmulas instaladas que no dependen de otras:
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Actualizar una fórmula instalada (si no se añade el nombre, se actualizarán todas las fórmulas):
This text is not cool in English for me.
Creo que `indicar` es el verbo más semántico para esto:
```suggestion
- Actualiza una fórmula instalada (si no se indica el nombre, se actualizan todas las fórmulas):
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Actualizar a la última versión de Homebre y todas sus fórmulas desde GitHub:
```suggestion
- Actualiza a la última versión de Homebrew y todas sus fórmulas desde GitHub:
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Remover versiones antiguas de fórmulas instaladas (si no se añade el nombre, se buscará en todas las fórmulas):
```suggestion
- Elimina versiones antiguas de fórmulas instaladas (si no se indica el nombre, se busca en todas las fórmulas):
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Mostrar información acerca de una fórmula (versión, ruta de instalación, dependencias, etc.):
```suggestion
- Muestra información acerca de una fórmula (versión, ruta de instalación, dependencias, etc.):
```

2020-10-31 02:50 UTC, navarroaxel commented on pages.es/osx/brew.md
> +- Revisar la instalación local de Homebrew para buscar problemas poteniales:
```suggestion
- Verifica la instalación local de Homebrew en busca de problemas poteniales:
```

2020-10-31 03:01 UTC, moisesnandres commented
Hi @navarroaxel , thanks for the review, I've just updated the file

2020-10-31 03:03 UTC, navarroaxel approved these changes
Thanks @moisesnandres, please **don't** push force, it's harder to use to track the suggestions and changes.

2020-11-01 13:48 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

Feel free to open 1 big PR if you're translating lots of pages, with 1 commit per page  :-)

2020-11-01 13:49 UTC, merged