rubocop, spotify: Add Spanish translation
tldr-pages/tldr pull request #4910
Opened 2020-10-31 03:19 UTC by moisesnandres

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-10-31 03:33 UTC, navarroaxel requested changes
Thanks @moisesnandres, just a few comments.

2020-10-31 03:33 UTC, navarroaxel commented on pages.es/osx/rubocop.md
> +- Verifica uno o más archivos o directorios específicos:
```suggestion
- Verifica uno o más archivos o directorios determinados:
```

2020-10-31 03:33 UTC, navarroaxel commented on pages.es/osx/rubocop.md
> +- Guarda el output en un archivo:
I think `salida` is the word because `salida estándar` is valid in Spanish, or `resultado`:
```suggestion
- Guarda la salida en un archivo:
```

2020-10-31 03:33 UTC, navarroaxel commented on pages.es/osx/rubocop.md
> +- Ejecuta solo las reglas especificadas:
```suggestion
- Ejecuta sólo determinadas reglas:
```

2020-10-31 03:33 UTC, navarroaxel commented on pages.es/osx/spotify.md
> +- Encuentra una canción por su nombre y escúchala:
Your talking about the command example, not the user:
```suggestion
- Encuentra una canción por su nombre y la reproduce:
```

2020-10-31 03:33 UTC, navarroaxel commented on pages.es/osx/spotify.md
> +- Encuentra una lista de reproducción por su nombre y escúchalo:
```suggestion
- Encuentra una lista de reproducción por su nombre y la reproduce:
```

2020-10-31 19:45 UTC, navarroaxel requested changes

2020-10-31 19:45 UTC, navarroaxel commented on pages.es/osx/rubocop.md
> +- Verifica todos los archivos en el directorio actual (incluyendo determinados):
I think you wanted to change the 2nd description, not this:
```suggestion
- Verifica todos los archivos en el directorio actual (incluyendo subdirectorios):
```

2020-11-01 14:20 UTC, sbrl approved these changes
Looks ok when @navarroaxel's suggestions are addressed

2020-11-02 15:24 UTC, navarroaxel approved these changes

2020-11-02 15:25 UTC, merged