adb: Add Spanish translation
tldr-pages/tldr pull request #4915
Opened 2020-10-31 16:41 UTC by moisesnandres

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-31 19:58 UTC, navarroaxel requested changes
Thanks @moisesnandres. I just made some comments.

Remember that for translations you can send more than 1 translated page in 1 PR, just keep 1 commit per file. This doesn't apply to the primary «English» pages.

2020-10-31 19:58 UTC, navarroaxel commented on pages.es/common/adb.md
> +`adb install -r {{path/to/file.apk}}`
Please translate the arguments for get this easier for non-English speakers:
```suggestion
`adb install -r {{ruta/al/archivo.apk}}`
```

2020-10-31 19:58 UTC, navarroaxel commented on pages.es/common/adb.md
> +`adb pull {{path/to/device_file_or_directory}} {{path/to/local_destination_directory}}`
```suggestion
`adb pull {{ruta/al/archivo_o_directorio_en_el_dispositivo}} {{ruta/al/directorio_de_destino_local}}`
```

2020-10-31 19:58 UTC, navarroaxel commented on pages.es/common/adb.md
> +`adb push {{path/to/local_file_or_directory}} {{path/to/device_destination_directory}}`
```suggestion
`adb push {{ruta/al/archivo_o_directorio_local}} {{ruta/al/directorio_de_destino_en_el_dispositivo}}`
```

2020-10-31 20:33 UTC, moisesnandres commented
@navarroaxel ok, I will add the next translations on this PR

2020-11-01 14:43 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

Looks ok to me after @navarroaxel's comments are addressed

2020-11-02 15:25 UTC, navarroaxel approved these changes

2020-11-02 15:25 UTC, merged