add tr page and translate 7z
tldr-pages/tldr pull request #4916
Opened 2020-10-31 18:28 UTC by Yutyo

- [.] The page (if new), does not already exist in the repo.
- [.] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [.] The page has 8 or fewer examples.
- [.] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [.] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [.] The page description includes a link to documentation or a homepage (if applicable).

2020-10-31 18:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4916) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4916) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4916) it.</sub>

2020-10-31 19:42 UTC, navarroaxel requested changes
Thanks @Yutyo 

Remember that for translations you can send more than 1 translated page in 1 PR. This doesn't apply to the primary «English» pages.

2020-10-31 19:42 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z a {{archived.7z}} {{path/to/file_or_directory}}`
Please translate the arguments for get this easier for non-English speakers.

2020-11-01 02:50 UTC, navarroaxel requested changes

2020-11-01 02:50 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z a {{archived.7z}} {{yoldan/dosya_veya_dizine}}`
Please translate `archived`, I know it's not a good filename. You can use `compressed_file` for the translation, or something similar.

2020-11-01 20:57 UTC, navarroaxel requested changes

2020-11-01 20:57 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z a {{sikistirilmis-dosya.7z}} {{yoldan/dosya_veya_dizine}}`
We use `snake_case` for variable names:
```suggestion
`7z a {{sikistirilmis_dosya.7z}} {{yoldan/dosya_veya_dizine}}`
```

2020-11-03 20:34 UTC, navarroaxel requested changes

2020-11-03 20:34 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z a {{sifrelenmiş-dosya.7z}} -p{{parola}} -mhe=on {{archived.7z}}`
```suggestion
`7z a {{sifrelenmiş_dosya.7z}} -p{{parola}} -mhe=on {{sikistirilmis_dosya.7z}}`
```

2020-11-03 20:34 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z x {{sikistirilmis-dosya.7z}}`
```suggestion
`7z x {{sikistirilmis_dosya.7z}}`
```

2020-11-03 20:34 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z x {{sikistirilmis-dosya.7z}} -so`
```suggestion
`7z x {{sikistirilmis_dosya.7z}} -so`
```

2020-11-03 20:34 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z x {{sikistirilmis-dosya.7z}} -o{{yoldan/çıktıya}}`
```suggestion
`7z x {{sikistirilmis_dosya.7z}} -o{{yoldan/çıktıya}}`
```

2020-11-03 20:34 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z l {{sikistirilmis-dosya.7z}}`
```suggestion
`7z l {{sikistirilmis_dosya.7z}}`
```

2020-11-03 20:34 UTC, navarroaxel commented on pages.tr/common/7z.md
> +`7z a -t{{zip|gzip|bzip2|tar}} {{archived.7z}} {{yoldan/dosya_veya_dizine}}`
```suggestion
`7z a -t{{zip|gzip|bzip2|tar}} {{sikistirilmis_dosya.7z}} {{yoldan/dosya_veya_dizine}}`
```

2020-11-03 20:35 UTC, navarroaxel approved these changes

2020-11-04 19:27 UTC, schneiderl approved these changes

2020-11-04 19:34 UTC, merged