create linux page in tr and apt-get
tldr-pages/tldr pull request #4917
Opened 2020-10-31 18:39 UTC by Yutyo

- [.] The page (if new), does not already exist in the repo.
- [.] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [.] The page has 8 or fewer examples.
- [.] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [.] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-10-31 19:39 UTC, navarroaxel approved these changes
Hi @Yutyo, welcome and thanks for your submission.

You should use `[x]` to mark a checkbox as checked.

2020-10-31 19:43 UTC, navarroaxel requested changes

2020-10-31 19:43 UTC, navarroaxel commented on pages.tr/linux/apt-get.md
> +`apt-get remove {{package}}`
Please translate the arguments for get this easier for non-English speakers.

2020-11-01 02:51 UTC, navarroaxel approved these changes

2020-11-01 14:54 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-11-01 14:54 UTC, merged