xkcdpass: add page and Polish translation
tldr-pages/tldr pull request #4919
Opened 2020-10-31 22:14 UTC by chanibal

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-11-01 02:56 UTC, navarroaxel requested changes
Thanks @chanibal, just 1 comment.

2020-11-01 02:56 UTC, navarroaxel commented on pages/common/xkcdpass.md
> +> Inspired by XKCD 936.
```suggestion
> Inspired by XKCD 936.
> More information: <https://github.com/redacted/XKCD-password-generator>.
```

2020-11-01 13:47 UTC, owenvoke approved these changes

2020-11-02 11:50 UTC, navarroaxel commented on pages.pl/common/xkcdpass.md
> +> Zainspirowane przez XKCD 936.
```suggestion
> Zainspirowane przez XKCD 936.
> Więcej informacji: <https://github.com/redacted/XKCD-password-generator>.
```

2020-11-02 11:51 UTC, navarroaxel approved these changes

2020-11-02 11:52 UTC, merged