git-clone: add single branch clone
tldr-pages/tldr pull request #4924
Opened 2020-11-01 19:40 UTC by iNemesis

- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-11-01 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4924) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4924) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4924) it.</sub>

2020-11-01 19:54 UTC, navarroaxel requested changes
Hi @iNemesis, welcome and thanks for your submission. I left 2 comments.

I think this page needs the basic example "clone into a specific directory":
```
git clone {{remote_repository_location}} {{path/to/directory}}
```
Could you add it?

2020-11-01 19:54 UTC, navarroaxel commented on pages/common/git-clone.md
> +`git clone -b {{branch_to_clone}} --single-branch {{remote_repository_location}}`
Please use the long argument format:
```suggestion
`git clone --branch {{name}} --single-branch {{remote_repository_location}}`
```

2020-11-01 19:54 UTC, navarroaxel commented on pages/common/git-clone.md
> +- Clone a single branch:
Based on the previous example description:
```suggestion
- Clone an existing repository only fetching a specific branch:
```

2020-11-01 20:05 UTC, navarroaxel requested changes

2020-11-01 20:05 UTC, navarroaxel commented on pages/common/git-clone.md
> +- Clone into a specific repository:
Cloud you move this example as example number 2?
 ```suggestion
- Clone an existing repository into a specific directory:
```

2020-11-01 20:06 UTC, iNemesis commented
Hi @navarroaxel, thanks for your suggestions !

I have added the "clone into a repository" command.

Have a nice day ;)

2020-11-01 20:09 UTC, navarroaxel approved these changes

2020-11-03 01:47 UTC, einverne approved these changes
Looks good.

2020-11-03 11:48 UTC, merged