ctr:  add page
tldr-pages/tldr pull request #4928
Opened 2020-11-04 07:03 UTC by hellojukay

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-11-04 09:44 UTC, owenvoke approved these changes
LGTM. 👍🏻

2020-11-04 12:07 UTC, navarroaxel requested changes
Thanks @hellojukay, I left some comments.

2020-11-04 12:07 UTC, navarroaxel commented on pages/linux/ctr.md
> +`ctr c list`
Please use long arguments format:
```suggestion
`ctr containers list`
```

2020-11-04 12:07 UTC, navarroaxel commented on pages/linux/ctr.md
> +`ctr i list`
```suggestion
`ctr images list`
```

2020-11-04 12:07 UTC, navarroaxel commented on pages/linux/ctr.md
> +`ctr i pull {{image}}`
```suggestion
`ctr images pull {{image}}`
```

2020-11-04 12:07 UTC, navarroaxel commented on pages/linux/ctr.md
> +`ctr i tag {{image1} {{image2}}`
I tried this command and I think this is better:
```suggestion
`ctr images tag {{source_image}}:{{source_tag}} {{target_image}}:{{target_tag}}`
```

2020-11-04 12:07 UTC, navarroaxel commented on pages/linux/ctr.md
> +- Tag a image:
```suggestion
- Tag an image:
```

2020-11-04 12:07 UTC, navarroaxel commented on pages/linux/ctr.md
> +- Pull image:
```suggestion
- Pull an image:
```

2020-11-05 10:08 UTC, navarroaxel requested changes

2020-11-05 10:08 UTC, navarroaxel commented on pages/linux/ctr.md
> +`ctr image pull {{image}}`
```suggestion
`ctr images pull {{image}}`
```

2020-11-05 10:08 UTC, navarroaxel approved these changes

2020-11-05 10:09 UTC, merged