docker-stats: add page
tldr-pages/tldr pull request #4939
Opened 2020-11-05 19:56 UTC by alimalek71

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-11-06 19:14 UTC, navarroaxel commented on pages/common/docker-stats.md
> +- Display live stream statistics on multiple containers by name or id:
```suggestion
- Display live stream statistics of a space-separated list of containers:
```

2020-11-06 19:14 UTC, navarroaxel commented on pages/common/docker-stats.md
> +`docker stats {{container_name container_id ...}}`
Based in the `docker container` we can use:
```suggestion
`docker stats {{container_name}}`
```
This command is advanced, I think the user knows they can use the name or the ID.

2020-11-06 19:14 UTC, navarroaxel commented on pages/common/docker-stats.md
> +- Show all containers including non running containers:
Based on `docker ps`, maybe this is better:
```suggestion
- Display all containers (running and stopped):
```

2020-11-10 10:15 UTC, navarroaxel approved these changes

2020-11-10 19:15 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2020-11-10 19:15 UTC, sbrl commented on pages/common/docker-stats.md
> +> Display a live stream of containers resource usage statistics.
Perhaps this will read better?
```suggestion
> Display a live stream of resource usage statistics for containers.
```

2020-11-10 19:15 UTC, sbrl commented on pages/common/docker-stats.md
> +- Display live stream of all running containers statistics:
Perhaps this will read better?
```suggestion
- Display a live stream for the statistics of all running containers:
```

2020-11-10 19:15 UTC, sbrl commented on pages/common/docker-stats.md
> +- Display live stream statistics of a space-separated list of containers:
Perhaps this will read better?
```suggestion
- Display a live stream of statistics for a space-separated list of containers:
```

2020-11-10 19:15 UTC, sbrl commented on pages/common/docker-stats.md
> +- Change columns format to display containers cpu usage percentage:
Perhaps this will read better?
```suggestion
- Change the columns format to display containers' cpu usage percentage:
```

2020-11-10 19:15 UTC, sbrl commented on pages/common/docker-stats.md
> +- Display all containers (running and stopped):
Perhaps this will read better?
```suggestion
- Display statistics for all containers (both running and stopped):
```

2020-11-18 12:35 UTC, navarroaxel commented
Could you merge with the upstream master to pass the CI check? Let me know if you need help to resolve that.

2020-11-20 09:29 UTC, alimalek71 commented
@navarroaxel Done

2020-11-27 00:56 UTC, sbrl approved these changes
Thanks, @alimalek71!

2020-11-27 00:56 UTC, merged