ls: add page
tldr-pages/tldr pull request #4941
Opened 2020-11-06 12:25 UTC by RobinKohrs

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-11-06 12:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4941) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4941) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4941) it.</sub>

2020-11-07 04:49 UTC, navarroaxel commented
@RobinKohrs Could you please sign the license/CLA to pass the check?

2020-11-07 08:08 UTC, RobinKohrs commented
@navarroaxel Sure thing! sorry about that. I'm completely new to this and just wanted the help on the command line. Thanks for pointing out to that.

2020-11-07 19:11 UTC, navarroaxel requested changes

2020-11-07 19:11 UTC, navarroaxel commented on pages/common/gdalbuildvrt.md
> +`gdalbuildvrt -input_file_list {{ my_list.txt }} {{ output.vrt }}`
```suggestion
`gdalbuildvrt -input_file_list {{path/to/list.txt}} {{path/to/output.vrt}}`
```

2020-11-07 19:11 UTC, navarroaxel commented on pages/common/gdalbuildvrt.md
> +`gdalbuildvrt {{ output.vrt }} {{ input_folder/*.tif }}`
```suggestion
`gdalbuildvrt {{path/to/output.vrt}} {{path/to/input_directory/*.tif}}`
```

2020-11-07 19:11 UTC, navarroaxel commented on pages/common/gdalbuildvrt.md
> +`gdalbuildvrt -separate {{ rgb.vrt }}  {{ red.tif green.tif blue.tif }}`
```suggestion
`gdalbuildvrt -separate {{path/to/rgb.vrt}}  {{path/to/red.tif}] {{path/to/green.tif}} {{path/to/blue.tif}}`
```

2020-11-07 19:11 UTC, navarroaxel commented on pages/common/gdalbuildvrt.md
> +`gdalbuildvrt -hidenodata -vrtnodata "0 0 255" {{ output.vrt }} {{ input_folder/*.tif }}`
```suggestion
`gdalbuildvrt -hidenodata -vrtnodata "{{0 0 255}}" {{path/to/output.vrt}} {{path/to/input_directory/*.tif}}`
```

2020-11-08 18:27 UTC, navarroaxel approved these changes

2020-11-10 19:00 UTC, sbrl approved these changes
Thanks, @RobinKohrs! Looks ok to me. Welcome to tldr pages :smiley_cat:

2020-11-10 19:02 UTC, merged

2020-11-11 07:24 UTC, RobinKohrs commented
Thanks so much!:) I'm relatively new to this and didn't know how exactly how to accept the changes @navarroaxel made. But glad it somehow worked.

2020-11-11 09:43 UTC, navarroaxel commented
Don't worry @RobinKohrs You can check how to accept the suggestions here: https://docs.github.com/en/enterprise-server@2.21/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request