which, tput, matlab: add French translation
tldr-pages/tldr pull request #4943
Opened 2020-11-09 04:47 UTC by ivorysoap

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-11-09 04:47 UTC, ivorysoap commented
Also fixed a small error in `pwd.md` that I introduced a couple weeks back

2020-11-09 10:15 UTC, navarroaxel requested changes

2020-11-09 10:15 UTC, navarroaxel commented on pages.fr/common/pwd.md
>  (c.-à-d. afficher le répertoire « physique ») :
All in one line:
```suggestion
- Affiche le répertoire actuel tout en traduisant les liens symboliques (c.-à-d. afficher le répertoire « physique ») :
```

2020-11-09 18:33 UTC, navarroaxel approved these changes

2020-11-10 19:04 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2020-11-10 19:10 UTC, merged