Patch/blockout
tldr-pages/tldr pull request #4945
Opened 2020-11-09 14:40 UTC by sahilister

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-11-10 10:19 UTC, navarroaxel commented on pages/common/blockout2.md
> +> More information: <https://www.blockout.net/blockout2/>.
I think the website doesn't support SSL
```suggestion
> More information: <http://www.blockout.net/blockout2/>.
```

2020-11-10 19:17 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2020-11-10 19:17 UTC, sbrl commented on pages/common/blockout2.md
> +- Navigate the piece in 2D plane:
Perhaps this will read better?
```suggestion
- Navigate the current piece on a 2D plane:
```

2020-11-10 19:17 UTC, sbrl commented on pages/common/blockout2.md
> +- Hard drop the piece:
Perhaps this will read better?
```suggestion
- Hard drop the current piece:
```

2020-11-11 09:44 UTC, navarroaxel approved these changes

2020-11-13 09:45 UTC, owenvoke approved these changes

2020-11-16 18:46 UTC, sbrl approved these changes
Thanks, @sahilister!

2020-11-16 18:46 UTC, merged