kjv: add page
tldr-pages/tldr pull request #4949
Opened 2020-11-10 19:57 UTC by FukurouMakoto

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-11-10 19:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4949) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4949) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4949) it.</sub>

2020-11-11 10:15 UTC, navarroaxel requested changes
Hi @FukurouMakoto, welcome and thanks for your submission. I left some comments.

2020-11-11 10:15 UTC, navarroaxel commented on pages/linux/kjv.md
> +`kjv Matthew 1:7-2-6`
This command has a typo:
```suggestion
`kjv {{Matthew}} {{1}}:{{7}}-{{2}}:{{6}}`
```

2020-11-11 10:15 UTC, navarroaxel commented on pages/linux/kjv.md
> +- Get a range of chapters and/or verses in a book:
Your command example is about verses, not chapters. So, this example description is confused. Maybe this is better:
```suggestion
- Display a specific range of verses of a book from different chapters:
```

2020-11-11 10:15 UTC, navarroaxel commented on pages/linux/kjv.md
> +- Search all verses that match a pattern:
```suggestion
- Display all verses that match a pattern:
```

2020-11-11 10:15 UTC, navarroaxel commented on pages/linux/kjv.md
> +`kjv Exodus/Plagues`
Based on the example description this command is not right:
```suggestion
`kjv /{{Plagues}}`
```

2020-11-11 10:15 UTC, navarroaxel commented on pages/linux/kjv.md
> +`kjv 1Jn/antichrist`
```suggestion
`kjv {{1Jn}}/{{antichrist}}`
```

2020-11-11 10:15 UTC, navarroaxel commented on pages/linux/kjv.md
> +- Search all verses in a book that match a pattern:
```suggestion
- Display all verses that match a pattern in a specific book:
```

2020-11-11 10:49 UTC, FukurouMakoto commented on pages/linux/kjv.md
> +`kjv Genesis 2`
Thank you for taking your time to review my pull request. 
In the future, should I follow this example when typing out arguments/parameters for this project?

2020-11-11 10:55 UTC, FukurouMakoto commented on pages/linux/kjv.md
> +- Open individual verse(s) of a specific chapter of a book:
I think that's fair. 
My concern was for people who possibly have never read the Bible before and thus would not know this, but after some consideration it seems unlikely such a person would make a Linux terminal their first place to do so.

2020-11-11 11:00 UTC, FukurouMakoto commented
@navarroaxel Thanks for your help and for reviewing the document. The changes have all been made.

2020-11-11 11:48 UTC, navarroaxel approved these changes

2020-11-13 09:33 UTC, owenvoke approved these changes
LGTM 👍🏻

2020-11-13 09:34 UTC, merged