cuyo: add page
tldr-pages/tldr pull request #4954
Opened 2020-11-14 06:42 UTC by sahilister

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-11-14 13:08 UTC, navarroaxel requested changes

2020-11-14 13:08 UTC, navarroaxel commented on pages/linux/cuyo.md
> +> More information: <https://www.karimmi.de/cuyo>.
```suggestion
> More information: <https://www.karimmi.de/cuyo/>.
```

2020-11-14 13:57 UTC, sahilister commented on pages/linux/cuyo.md
> +> More information: <https://www.karimmi.de/cuyo>.
Done!

2020-11-14 14:52 UTC, navarroaxel approved these changes

2020-11-16 18:50 UTC, sbrl approved these changes
Thanks :D

2020-11-16 18:51 UTC, merged