Added missing space
tldr-pages/tldr pull request #4955
Opened 2020-11-14 11:42 UTC by Chasarr

2020-11-14 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4955) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4955) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4955) it.</sub>

2020-11-14 13:06 UTC, navarroaxel requested changes
Could you please update the more information link to:
```
https://cmake.org/cmake/help/latest/manual/cmake.1.html
```

2020-11-16 09:35 UTC, Chasarr commented
Update the link like this?

2020-11-16 12:20 UTC, navarroaxel approved these changes

2020-11-16 18:53 UTC, sbrl approved these changes
Thanks for the edit!

2020-11-16 18:53 UTC, merged