resolveip: add page
tldr-pages/tldr pull request #4982
Opened 2020-11-23 20:10 UTC by sahilister

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-11-27 01:38 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2020-11-27 01:38 UTC, sbrl commented on pages/linux/resolveip.md
> +> Resolve host name to IP address and vice versa.
I think hostname is a single word.
```suggestion
> Resolve hostnames to their IP addresses and vice versa.
```

2020-11-27 01:38 UTC, sbrl commented on pages/linux/resolveip.md
> +- Resolve host name to IP address:
Perhaps this will read better?
```suggestion
- Resolve a hostname to an IP address:
```

2020-11-27 01:38 UTC, sbrl commented on pages/linux/resolveip.md
> +- Resolve IP address to host name:
Perhaps this will read better?
```suggestion
- Resolve an IP address to a hostname:
```

2020-11-30 12:10 UTC, navarroaxel approved these changes

2020-12-04 19:05 UTC, sbrl approved these changes
Thanks, @sahilister!

2020-12-04 19:05 UTC, merged