pip: subcommand for installs + editable install
tldr-pages/tldr pull request #4983
Opened 2020-11-24 04:39 UTC by metov

The `pip` file has a lot of commands, and many of them are different kinds of installation. I broke them into a separate file to keep `pip.md` concise. Since `pip-install.md` now has some room, I also added the useful command for installing in editable mode.

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-11-24 04:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4983) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4983) before we can accept your contribution.<br/><hr/>**konrad** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4983) it.</sub>

2020-11-27 01:44 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2020-11-27 01:44 UTC, sbrl commented on pages/common/pip.md
> +- Install a package (see `tldr pip install` for more install commands):
Perhaps this will read better?
```suggestion
- Install a package (see `tldr pip install` for more install examples):
```

2020-11-27 01:44 UTC, sbrl commented on pages/common/pip-install.md
> +- Install packages from file:
Perhaps this will read better?
```suggestion
- Install packages listed in a file:
```

2020-11-27 01:44 UTC, sbrl commented on pages/common/pip-install.md
> +- Install local package in develop (editable) mode:
Perhaps this will read better?
```suggestion
- Install the local package in the current directory in develop (editable) mode:
```

2020-11-30 11:31 UTC, einverne approved these changes
Seems good after @sbrl 's suggestions.

2020-12-02 05:44 UTC, metov commented on pages/common/pip.md
> +- Install a package (see `tldr pip install` for more install commands):
Great idea, thank you!

2020-12-02 05:52 UTC, metov commented
@einverne Awesome, thank you!

@sbrl Thanks for the suggestions, all accepted. Could you please re-review?

2020-12-02 12:25 UTC, schneiderl approved these changes
lgtm

2020-12-04 19:16 UTC, sbrl commented on pages/common/pip.md
> +- Install a package (see `tldr pip install` for more install examples):
I suggest avoiding the `tldr ` here, and keeping it to just the command + subcommand.
```suggestion
- Install a package (see `pip install` for more install examples):
```

2020-12-04 19:16 UTC, sbrl reviewed
Looks ok to me after 1 teensy comment above :-)

2020-12-22 06:41 UTC, metov commented
Hey @sbrl - I accepted your change, can you re-review please?

2020-12-27 01:21 UTC, owenvoke approved these changes

2020-12-30 13:24 UTC, sbrl approved these changes
Thanks, @metov!

2020-12-30 13:25 UTC, merged

2020-12-30 13:25 UTC, sbrl commented
I've been having a much-needed break, so I haven't been gotten around to PRs recently. Thanks for your patience!