find: add space to -exec example to avoid error
tldr-pages/tldr pull request #4987
Opened 2020-11-24 14:49 UTC by mojth

Add space before backslash in line 31. Without the space you would get the error message: missing argument to exec

- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-11-24 14:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4987) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4987) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4987) it.</sub>

2020-11-27 01:50 UTC, sbrl approved these changes
Wow, great catch @mojth!

Force-merging sincce this is a trivial change.

2020-11-27 01:52 UTC, sbrl commented on pages/common/find.md
> +`find {{root_path}} -name '{{*.ext}}' -exec {{wc -l {} }} \;`
Oh oops! I've just noticced that we now have a double space here - one inside the closing `}}` of the tldr-pages `{{token_syntax}}`, and the other now outside. I think this was fine as it was:

![Selection_2020-11-27_01:52:10_001_2dc5b7d](https://user-images.githubusercontent.com/9929737/100402033-2c627180-3053-11eb-811e-d95d311cfaaf.png)

2020-11-27 01:52 UTC, sbrl requested changes
See above

2020-11-27 05:28 UTC, mojth commented
If you copy and paste the example and then replace the "{{}}", you may miss the space. At least that's what happened to me. In my opinion, a space outside of "{{}}" is more visible. But I'm not married to the idea. If you oppose this change, I would be fine too.

2020-12-04 18:35 UTC, sbrl commented
Ah, I see @mojth. Generally we expect clients to parse out the `{{token_syntax}}` though. The reason it was done like that is because a triple `}}}` there may confuse in terms of syntax :P

2020-12-30 12:57 UTC, sbrl commented
I'm going to close this PR now, but I can always reopen if we want to continue the discussion.

2020-12-30 12:57 UTC, closed without merging