deactivate does not take environment name
tldr-pages/tldr pull request #4991
Opened 2020-11-26 17:03 UTC by andrewmarkallen

- [ ] The page has 8 or fewer examples.
- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

`conda deactivate environment` isn't a valid command. While calling deactivate without an environment based on the tldr example might seem obvious to experienced coders, it was the source of confusion in work today. I think the new change follows the guidelines for command examples:

> When in doubt, keep new command-line users in mind. Err on the side of clarity rather than terseness. For example, commands that require sudo should include it directly in the examples.

2020-11-26 17:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4991) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=4991) before we can accept your contribution.<br/><hr/>**Mark Allen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=4991) it.</sub>

2020-11-26 18:00 UTC, andrewmarkallen commented
Is it possible to merge this (pending approval of course)? I fixed my email address in a new commit but it's looking for the previous (misspelt, nonexistent email) to also sign CLA.

If not I have another branch ready to merge if you close this

2020-11-29 06:07 UTC, navarroaxel commented
@andrewmarkallen we have an issue because the pages can have up to 8 example, and I count 9 here.

2020-12-04 19:02 UTC, sbrl reviewed
Thanks for the PR, @andrewmarkallen! Unfortunately as @navarroaxel says we have a limit of 8 example per page, which means we're unable to merge until we drop below that limit.

However, in terms of grammar and syntax etc your edit looks good! Just 1 minor comment below.

Regarding your author issue with the commits: try squashing them together and force-pushing. In theory that should fix the problem?

2020-12-04 19:02 UTC, sbrl commented on pages/common/conda.md
> +- Load  an environment:
Double space here?
```suggestion
- Load an environment:
```

2020-12-20 02:56 UTC, navarroaxel approved these changes

2020-12-30 12:55 UTC, sbrl requested changes
Thanks for the edit @navarroaxel, but as far as I can see we're still at 9 examples here.

2021-01-02 15:30 UTC, bl-ue commented
@andrewmarkallen, thank you for this PR, but to me the new change doesn't improve clarity much.  A user will automatically associate "load" with "activate" and "unload" with "deactivate" when they see
```
- Load or unload an environment:

`conda {{activate|deactivate}} {{environment_name}}`
```
and this page already has 8 examples, which is the maximum.

2021-01-02 15:30 UTC, closed without merging

2021-01-02 15:31 UTC, bl-ue commented
You could open a PR to update that Python version in the 6th example--3.4 is really old.  3.9 is the current version...

2021-01-04 16:53 UTC, sbrl commented
This is an old PR so it doesn't matter much, but next time @bl-ue try to talk the user through it, and give them an opportunity to close the PR themselves :-)

2021-01-04 17:14 UTC, bl-ue commented
Okay @sbrl.  Maybe I was a little too eager to get issues/PR closed...

2021-01-04 17:54 UTC, sbrl commented
No worries! It's a balance between closing old PRs and giving users time to act of feedback. Generally a month of inactivity is enough to close a PR, hence the stale bot. But a number of issues are long-term tracking issues, which makes them a lot more difficult to close.

2021-01-04 17:58 UTC, bl-ue commented
Yeah, I know.  I'm working on trying to trim some of those down.  I've actually got 15+ closed since you added me as a collaborator 4 days ago.

2021-01-07 01:22 UTC, sbrl commented
Wow, that's a lot @bl-ue!