dkms: add page
tldr-pages/tldr pull request #4997
Opened 2020-11-29 00:11 UTC by samuel-w

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-11-30 11:28 UTC, einverne requested changes
Thank you for the new page, I've left a comment for you to take a look.

2020-11-30 11:28 UTC, einverne commented on pages/linux/dkms.md
> +`dkms install -m acpi_call -v 1.2.1`
```suggestion
`dkms install -m {{acpi_call}} -v {{1.2.1}}`
```

2020-11-30 11:28 UTC, einverne commented on pages/linux/dkms.md
> +`dkms remove -m acpi_call -v 1.2.1 --all`
```suggestion
`dkms remove -m {{acpi_call}} -v {{1.2.1}} --all`
```

2020-11-30 12:00 UTC, navarroaxel requested changes

2020-11-30 12:00 UTC, navarroaxel commented on pages/linux/dkms.md
> +> A framework that allows for dynamic building of kernel modules.
```suggestion
> A framework that allows for dynamic building of kernel modules.
> More information: <https://github.com/dell/dkms>.
```

2020-11-30 15:07 UTC, navarroaxel approved these changes

2020-12-02 08:12 UTC, einverne approved these changes

2020-12-02 08:12 UTC, merged