dotnet*: add Spanish translation
tldr-pages/tldr pull request #5001
Opened 2020-12-02 19:04 UTC by Nacho-source

- dotnet: add Spanish translation
- dotnet-build: add Spanish translation
- dotnet-restore: add Spanish translation
- dotnet-publish: add Spanish translation

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-12-02 19:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5001) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5001) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5001) it.</sub>

2020-12-02 21:49 UTC, schneiderl requested changes
Hi, thank you for the PR 👍 
I don't know the language so I'm not reviewing the Spanish files (only reviewing it syntax wise).
But there are changes on the English files which I'm assuming were made by mistake.
Could you please take a look at that? 

Thanks a lot for your translations, it really helps a lot.

2020-12-02 21:49 UTC, schneiderl commented on pages/common/dotnet-publish.md
> +
I believe this change was made by mistake, right?

2020-12-02 21:49 UTC, schneiderl commented on pages/common/dotnet-restore.md
> +
I believe this change was made by mistake, right?

2020-12-02 21:49 UTC, schneiderl commented on pages/common/dotnet.md
> +
I believe this change was made by mistake, right?

2020-12-03 12:20 UTC, schneiderl approved these changes
Looks good to me now. Thank you for your PR. 👍

2020-12-03 13:36 UTC, navarroaxel requested changes

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-publish.md
> +`dotnet publish --self-contained true --runtime {{identificador_del_tiempo_de_ejecución}} {{ruta/al/archivo_del_proyecto}}`
```suggestion
`dotnet publish --self-contained true --runtime {{identificador_del_entorno_en_tiempo_de_ejecución}} {{ruta/al/archivo_del_proyecto}}`
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-publish.md
> +`dotnet publish --runtime {{identificador_del_tiempo_de_ejecucución}} -p:PublishSingleFile=true {{ruta/al/archivo_del_proyecto}}`
```suggestion
`dotnet publish --runtime {{identificador_del_entorno_en_tiempo_de_ejecucución}} -p:PublishSingleFile=true {{ruta/al/archivo_del_proyecto}}`
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-publish.md
> +`dotnet publish --configuration Release {{ruta/al/archivo_del_proyecto}}`
The argument options should be between `{{}}`:
```suggestion
`dotnet publish --configuration {{Release}} {{ruta/al/archivo_del_proyecto}}`
```
The same should be applied to the English page.

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-publish.md
> +- Recorta librerías no usadas para reducir el tamaño de la aplicación desplegada:
The Spanish translation for `libraries` is `bibliotecas`:
```suggestion
- Recorta las bibliotecas no usadas para reducir el tamaño de la aplicación:
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-publish.md
> +`dotnet publish --self-contained true --runtime {{identificador_del_tiempo_de_ejecución}} -p:PublishTrimmed=true {{ruta/al/archivo_del_proyecto}}`
```suggestion
`dotnet publish --self-contained true --runtime {{identificador_del_entorno_de_tiempo_de_ejecución}} -p:PublishTrimmed={{true}} {{ruta/al/archivo_del_proyecto}}`
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-restore.md
> +> Más información: https://docs.microsoft.com/dotnet/core/tools/dotnet-restore.
```suggestion
> Más información: <https://docs.microsoft.com/dotnet/core/tools/dotnet-restore>.
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-restore.md
> +- Restaura depedencias sin tomar las solicitudes HTTP:
```suggestion
- Restaura depedencias sin almacenar las solicitudes HTTP en caché:
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-restore.md
> +- Restaura dependencias usando las fallas del paquete fuente como advertencias:
```suggestion
- Restaura dependencias usando los orígenes con error como advertencias:
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet-restore.md
> +`dotnet restore --verbosity {{el|mínimo|normal|diagnóstico|detallado}}
```suggestion
`dotnet restore --verbosity {{quiet|minimal|normal|detailed|diagnostic}}
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet.md
> +> Más información en: https://docs.microsofot.com/dotnet/core/tools
```suggestion
> Más información: <https://docs.microsofot.com/dotnet/core/tools>.
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet.md
> +`dotnet new {{nombre_corto_modelo}}`
```suggestion
`dotnet new {{nombre_de_la_plantilla}}`
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet.md
> +- Construye y ejectura el proyecto .NET en el directorio actual:
```suggestion
- Compila y ejectura el proyecto .NET en el directorio actual:
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet.md
> +- Ejecuta una aplicación dotnet empaquetada (solo necesita el tiempo de ejecución, el resto de los comandos requieren el SDK de .NET Core instalado):
```suggestion
- Ejecuta una aplicación dotnet empaquetada (solo necesita el entorno en tiempo de ejecución, el resto de los comandos requieren el SDK de .NET Core instalado):
```

2020-12-03 13:36 UTC, navarroaxel commented on pages.es/common/dotnet.md
> +`dotnet {{ruta/a/aplicación.dll}}`
```suggestion
`dotnet {{ruta/a/la/aplicación.dll}}`
```

2020-12-03 15:22 UTC, navarroaxel requested changes

2020-12-03 15:22 UTC, navarroaxel commented on pages.es/linux/apt-cache.md
> +> Herramienta de consulta de paquetes de Debian y Ubuntu.
```suggestion
> Herramienta de consulta de paquetes para Debian y Ubuntu.
```

2020-12-03 15:22 UTC, navarroaxel commented on pages.es/linux/apt-file.md
> +> Busca archivos en paquetes apt, inluidos los que aún no fueron instalados.
```suggestion
> Busca archivos en paquetes apt, incluyendo los que aún no fueron instalados.
```

2020-12-03 15:22 UTC, navarroaxel commented on pages.es/linux/apt.md
> +- Muestra información para un paquete:
```suggestion
- Muestra la información de un paquete:
```

2020-12-03 15:22 UTC, navarroaxel commented on pages.es/linux/cmus.md
> +- Pausa/reproduci la canción actual:
```suggestion
- Pausa/reproduce la canción actual:
```

2020-12-03 15:22 UTC, navarroaxel commented on pages.es/linux/line.md
> +- Lee una  entrada:
Doble space
```suggestion
- Lee una entrada:
```

2020-12-03 15:22 UTC, navarroaxel commented on pages.es/linux/apt.md
> +- Elimina un paquete (si se utiliza `purge` también se eliminan sus archivos de configuración):
```suggestion
- Elimina un paquete (si se utiliza `purge` también elimina sus archivos de configuración):
```

2020-12-03 15:24 UTC, navarroaxel requested changes

2020-12-03 15:24 UTC, navarroaxel commented on pages.es/linux/lsb_release.md
> +> Proporciona cierta LSB (Linux Standard Base) e información específica de la distribución.
```suggestion
> Proporciona información específica de la distribución y LSB (Linux Standard Base).
```

2020-12-03 17:50 UTC, navarroaxel approved these changes

2020-12-03 17:50 UTC, merged