tmpmail: add page
tldr-pages/tldr pull request #5026
Opened 2020-12-13 01:52 UTC by GianniBYoung

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2020-12-14 12:46 UTC, navarroaxel requested changes
Can we send emails with this `tmpmail`?

2020-12-14 12:46 UTC, navarroaxel commented on pages/common/tmpmail.md
> +- Open email with given browser (default is w3m):
```suggestion
- Open email with a specific browser (default is w3m):
```

2020-12-14 12:46 UTC, navarroaxel commented on pages/common/tmpmail.md
> +- Open user specified message:
```suggestion
- Open a specific message:
```

2020-12-14 12:46 UTC, navarroaxel commented on pages/common/tmpmail.md
> +- View a temporary email's most recent email:
Is this for received emails right? (no sent)
```suggestion
- Display the most recent received email:
```

2020-12-14 12:46 UTC, navarroaxel commented on pages/common/tmpmail.md
> +- Create a temporary email:
I'm not sure if we should call this `inbox`:
```suggestion
- Create a temporary inbox:
```

2020-12-14 20:08 UTC, GianniBYoung commented
> Can we send emails with this `tmpmail`?

No we can't, it is mainly meant for reciving verification emails when signing up for a service.

2020-12-14 20:36 UTC, navarroaxel approved these changes

2020-12-18 13:21 UTC, sahilister approved these changes
Thanks @GianniBYoung for your contribution and welcome to tldr-pages.

2020-12-18 13:22 UTC, merged