scp: add port (-P) example
tldr-pages/tldr pull request #5027
Opened 2020-12-14 09:13 UTC by kjoshi

The `ssh` example shows how to connect to the remote host using a specific port (`-p`), and in the past I've been caught-out that specifying a port with `scp` uses `-P` instead.

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2020-12-14 09:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5027) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5027) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5027) it.</sub>

2020-12-14 12:34 UTC, navarroaxel requested changes

2020-12-14 12:34 UTC, navarroaxel commented on pages/common/scp.md
> +- Specify which port to connect to the remote host on:
Maybe this is better:
```suggestion
- Use a specific port when connecting to the remote host:
```

2020-12-14 12:39 UTC, navarroaxel commented
Could you please add the link? thanks
```
> More information: <https://man.openbsd.org/scp>.
```

2020-12-14 16:39 UTC, kjoshi commented
Thanks @navarroaxel, your wording was nicer!

2020-12-14 16:57 UTC, navarroaxel approved these changes

2020-12-17 09:44 UTC, einverne approved these changes

2020-12-17 09:44 UTC, einverne commented on pages/common/scp.md
> +`scp {{path/to/local_file}} {{remote_host}}:{{path/to/remote_file}} -P {{port}}`
For me, I often use this format.

```suggestion
`scp {{path/to/local_file}} -P {{port}} {{remote_host}}:{{path/to/remote_file}}`
```

2020-12-17 10:16 UTC, merged