Add `kubectl describe` example
tldr-pages/tldr pull request #5032
Opened 2020-12-16 20:07 UTC by makusu2

https://github.com/tldr-pages/tldr/pull/4494 added `kubectl describe` help, but the main page still doesn't mention it. Add a note about its usage.

This is an important command, but it exceeds the suggested limit of 8 examples (do subcommands count as "examples"?). We could instead replace the `kubectl get` example with `kubectl {{get|describe}}`, but I'm really not a fan of that, since they're two different subcommands.

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2020-12-16 20:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5032) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5032) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5032) it.</sub>

2020-12-17 11:00 UTC, navarroaxel requested changes
We can't accept more than 8 examples, but maybe you can add a description like:
```
> See also `kubectl describe` and other pages for additional information.
```
in the header like the `hg.md` page has.

2020-12-17 21:47 UTC, makusu2 commented
> We can't accept more than 8 examples, but maybe you can add a description like:
> 
> ```
> > See also `kubectl describe` and other pages for additional information.
> ```
> 
> in the header like the `hg.md` page has.

Sure, I can do that. I've kept my removal of "all" from the `get` example, since that's just incorrect (that's what `describe` is for).

2020-12-18 11:51 UTC, navarroaxel approved these changes

2020-12-19 19:20 UTC, sbrl approved these changes
Thanks, @makusu2!

2020-12-19 19:20 UTC, merged