Add information about custom output for lsblk
tldr-pages/tldr pull request #5039
Opened 2020-12-21 02:40 UTC by sbuller

I generally find the output of lsblk presets to be lacking, and a customized output is very helpful, particularly as I've provided.

- [x] The page has 8 or fewer examples.
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2020-12-21 02:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5039) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5039) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5039) it.</sub>

2020-12-21 12:16 UTC, navarroaxel requested changes

2020-12-21 12:16 UTC, navarroaxel commented on pages/linux/lsblk.md
> +- Produce a customized summary:
```suggestion
- Display a customized summary using a comma-separated list of columns:
```

2020-12-21 12:16 UTC, navarroaxel commented on pages/linux/lsblk.md
> +`lsblk --output NAME,SERIAL,MODEL,TRAN,TYPE,SIZE,FSTYPE,MOUNTPOINT`
The argument options should be between token syntax `{{}}`:
```suggestion
`lsblk --output {{NAME}},{{SERIAL}},{{MODEL}},{{TRAN}},{{TYPE}},{{SIZE}},{{FSTYPE}},{{MOUNTPOINT}}`
```

2020-12-21 22:29 UTC, sbuller commented
Thanks for the edits. Do you need anything from me?

2020-12-22 07:52 UTC, einverne approved these changes
Looks good. Thanks @sbuller .

2020-12-22 11:58 UTC, navarroaxel approved these changes

2020-12-22 11:59 UTC, merged