tmutil: add page
tldr-pages/tldr pull request #5054
Opened 2020-12-27 17:02 UTC by GingkathFox

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-12-27 17:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5054) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5054) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5054) it.</sub>

2020-12-27 20:00 UTC, navarroaxel requested changes

2020-12-27 21:54 UTC, GingkathFox commented
@navarroaxel fixed :3

2020-12-27 21:56 UTC, navarroaxel approved these changes

2020-12-29 11:43 UTC, einverne approved these changes
Looks good, thank you for the new page.

2020-12-29 11:43 UTC, merged