dust: add page
tldr-pages/tldr pull request #5055
Opened 2020-12-30 05:20 UTC by diohabara

- [x] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2020-12-30 11:23 UTC, navarroaxel requested changes
Hi @diohabara, welcome and thanks for your submission. I left some comments.

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +- Show the information of A and B directories in the current directory:
```suggestion
- Display information for a space-separated list of directories:
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +`dust A B`
```suggestion
`dust {{path/to/directory1}} {{path/to/directory2}}`
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +- Show only 30 directories instead of showing default number of directories:
```suggestion
- Display 30 directories (defaults to 21):
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +`dust -n 30`
We prefer long argument format:
```suggestion
`dust --number-of-lines {{30}}`
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +`dust -d 3`
The argument option should be between curly braces:
```suggestion
`dust --depth {{3}}`
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +- Show 3 levels of subdirectories:
```suggestion
- Display information for the current directory, up to 3 levels deep:
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +`dust -r`
```suggestion
`dust --reverse`
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +- Severse order of output, with root at the lowest:
```suggestion
- Display the biggest directories at the top in descending order:
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +`dust -X ignore`
```suggestion
`dust --ignore-directory {{file_or_directory_name}}`
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +- Ignore all files and directories with the name 'ignore':
```suggestion
- Ignore all files and directories with a specific name:
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +`dust -b`
```suggestion
`dust --no-percent-bars`
```

2020-12-30 11:23 UTC, navarroaxel commented on pages/common/dust.md
> +- Do not show percentages or draw ASCII bars:
```suggestion
- Do not display percent bars and percentages:
```

2020-12-31 09:06 UTC, diohabara commented
@navarroaxel 
Should I `rebase -i` to put together these commits?

2020-12-31 16:16 UTC, bl-ue commented
@diohabara yes, please do.  Next time you should click the "Add suggestion to batch" button on each suggestion in the "Files changed" tab.  You could have then applied all of the suggestions in one commit, to avoid this :)

See the [docs](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes).

2020-12-31 21:48 UTC, navarroaxel commented
> Should I `rebase -i` to put together these commits?

@diohabara no, it's ok, we squash before merge.

2020-12-31 21:48 UTC, navarroaxel approved these changes

2020-12-31 21:52 UTC, bl-ue commented
Oh okay @navarroaxel.  Good to know.

2021-01-01 21:47 UTC, bl-ue approved these changes

2021-01-01 21:47 UTC, merged