acpi, flatpak, i3, iptables: add Chinese translation
tldr-pages/tldr pull request #5061
Opened 2020-12-31 05:56 UTC by whriedplanck

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2020-12-31 05:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5061) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5061) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5061) it.</sub>

2021-01-01 00:13 UTC, whriedplanck commented
All done.

2021-01-01 05:23 UTC, navarroaxel requested changes
Hi @whriedplanck, welcome and thanks for your submission. I left some comments.

2021-01-01 05:23 UTC, navarroaxel commented on pages.zh/linux/acpi.md
> +> 更多信息参见：<https://sourceforge.net/projects/acpiclient/files/acpiclient/>.
```suggestion
> 更多信息：<https://sourceforge.net/projects/acpiclient/files/acpiclient/>.
```

2021-01-01 05:23 UTC, navarroaxel commented on pages.zh/linux/i3.md
> +> 更多信息参见：https://i3wm.org/docs/userguide.html>.
```suggestion
> 更多信息：https://i3wm.org/docs/userguide.html>.
```

2021-01-01 05:23 UTC, navarroaxel commented on pages.zh/linux/iptables.md
> +> 更多信息参见： <https://www.netfilter.org/projects/iptables/>.
```suggestion
> 更多信息： <https://www.netfilter.org/projects/iptables/>.
```

2021-01-01 05:23 UTC, navarroaxel commented on pages.zh/linux/flatpak.md
> +`flatpak run {{name}}`
Please translate the arguments for get this easier for non-English speakers (in all examples).

2021-01-01 10:52 UTC, whriedplanck commented
Hi, @navarroaxel, thank you for reviewing. I'll change them soon.

2021-01-01 11:18 UTC, whriedplanck commented
@navarroaxel I've had them changed ~ Thanks for suggestions! :D

2021-01-01 14:04 UTC, navarroaxel approved these changes

2021-01-01 22:26 UTC, bl-ue approved these changes

2021-01-01 22:26 UTC, merged