git-bugreport: add page
tldr-pages/tldr pull request #5097
Opened 2021-01-06 18:28 UTC by bl-ue

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For #3953

2021-01-06 18:29 UTC, bl-ue commented
>```
>pages/common/git-bugreport.md:3 MD013/line-length Line length [Expected: 250; Actual: 289]
>```
`tldrl` doesn't report this... 🤔

2021-01-07 02:08 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2021-01-07 02:08 UTC, sbrl commented on pages/common/git-bugreport.md
> +> Captures information about the user's machine, Git client, and repository state, as well as a form requesting information about the behavior the user observed, into a single text file which the use
Perhaps we could be more concise?
```suggestion
> Captures debug information from the system and user, generating a text file to aid in the reporting of a bug in Git.
```

2021-01-07 02:08 UTC, sbrl commented on pages/common/git-bugreport.md
> +- Create a new bugreport file in the specified, creating the directory if it does not exist:
Perhaps this will read better?
```suggestion
- Create a new bugreport file in the specified directory, creating it if it does not exist:
```

2021-01-07 02:08 UTC, sbrl commented on pages/common/git-bugreport.md
> +- Create a new bugreport file with the filename suffix in the specified `strftime` format:
Perhaps this will read better?
```suggestion
- Create a new bugreport file with the specified filename suffix in `strftime` format:
```

2021-01-07 21:42 UTC, sbrl approved these changes
Thanks, @bl-ue!

2021-01-08 07:36 UTC, navarroaxel approved these changes

2021-01-08 07:36 UTC, merged