rename git to Git
tldr-pages/tldr pull request #5105
Opened 2021-01-07 14:11 UTC by schneiderl

This PR renames "git" to "Git" in all occurrences across tldr (except in command examples and scripts, as it would cause a negative impact).
**Why?**
On the official website, git always starts with an uppercase.

2021-01-07 14:17 UTC, bl-ue approved these changes

2021-01-07 15:29 UTC, glenacota requested changes
Wow, thanks for your great effort, @schneiderl !!
However, there are still a few occurrences of the lowercase git, such as in `CONTRIBUTING.md:L120`, `dvc-diff.md:L10`, `git-instaweb.md:L6`. 

Could you please re-check? Thanks!

2021-01-07 15:31 UTC, bl-ue commented
You've got a really sharp eye, @glenacota! 😎

2021-01-07 15:42 UTC, schneiderl commented
@glenacota I added those and a few others that were missing - it looks like my regex skills still on vacation.

Thank you for noticing.

2021-01-07 15:44 UTC, bl-ue commented
Looks like there's some more @schneiderl:
```
pages.it/common/git-describe.md:18
pages.it/common/git-svn.md:18
pages.zh_TW/common/tldr.md:14
pages.th/common/tldr.md:14
pages.zh/common/tldr.md:14
```

2021-01-07 15:49 UTC, schneiderl commented
Nice @bl-ue thank you. 
I've added those.

Thanks for the help.

2021-01-07 15:49 UTC, bl-ue approved these changes

2021-01-07 15:51 UTC, glenacota approved these changes
LGTM, nice one ;)

2021-01-07 16:22 UTC, navarroaxel requested changes

2021-01-07 16:22 UTC, navarroaxel commented on pages/common/chezmoi.md
> +- Set chezmoi up on another machine by downloading existing dotfiles from a Git repo:
```suggestion
- Set chezmoi up on another machine by downloading existing dotfiles from a Git repository:
```

2021-01-07 16:22 UTC, navarroaxel commented on pages.es/common/git-submodule.md
> +`git submodule foreach Git pull`
```suggestion
`git submodule foreach git pull`
```

2021-01-07 16:23 UTC, schneiderl commented
nice catches @navarroaxel

2021-01-07 16:25 UTC, navarroaxel approved these changes

2021-01-07 22:04 UTC, sbrl approved these changes
![](https://imgs.xkcd.com/comics/regular_expressions.png)

2021-01-07 23:22 UTC, waldyrious commented
It's gonna be weird adjusting to seeing Git capitalized, but I concede that it is the logical choice. Go forth and prosper, you have my blessing! 🖖

2021-01-07 23:22 UTC, waldyrious approved these changes

2021-01-08 09:31 UTC, owenvoke approved these changes

2021-01-08 12:58 UTC, sahilister approved these changes

2021-01-08 13:07 UTC, sbrl commented
Wow, that's a lot of approvals! I think we can merge this then :P

2021-01-08 13:09 UTC, bl-ue commented
It really is!!! But why not just wait a little longer? How about 9 hours, since that's 24 hours after your approval?

2021-01-08 13:09 UTC, merged

2021-01-08 13:10 UTC, bl-ue commented
Never mind! You just merged it :D Cool!

2021-01-08 13:10 UTC, sbrl commented
Generally speaking PRs should be open for 48 hours before merging @bl-ue, to give people time to review (unless it's a trivial change). But in this case, we have so many approvals it doesn't matter

2021-01-08 13:11 UTC, bl-ue commented
Gotcha!

2021-01-08 14:07 UTC, bl-ue commented
@sbrl It looks look rebased this, but didn't you intend to squash?

2021-01-10 20:14 UTC, zlatanvasovic reviewed
Approved. I thought I had done this a while ago. :open_mouth:

2021-01-10 20:20 UTC, bl-ue commented
@zlatanvasovic I saw this just today, I believe you're thinking of #4060 "Github -> GitHub", which I and @schneiderl also did afterwards :smile:

2021-01-16 16:35 UTC, sbrl commented
Oops, @bl-ue! I did mean to squash.