gh-help: add page
tldr-pages/tldr pull request #5129
Opened 2021-01-10 14:08 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For: #4701

2021-01-10 14:09 UTC, bl-ue requested changes

2021-01-10 14:09 UTC, bl-ue commented on pages/common/gh-help.md
> +- Display a markdown reference of all gh commands:
```suggestion
- Display a markdown reference of all `gh` commands:
```

2021-01-10 14:12 UTC, bl-ue reviewed
I'm not sure if this is consistent with our other pages, but I would prefer the example description without the first "the":
```diff
- Display the general help
+ Display general help
```
...also for the others.

What do you think?

2021-01-10 14:16 UTC, bl-ue approved these changes

2021-01-10 14:23 UTC, navarroaxel commented on pages/common/gh-help.md
> +> Display help about GitHub CLI command.
```suggestion
> Display help about the GitHub CLI command.
```

2021-01-10 14:24 UTC, bl-ue approved these changes

2021-01-11 16:24 UTC, owenvoke approved these changes

2021-01-11 16:24 UTC, merged