gh-reference: add page
tldr-pages/tldr pull request #5130
Opened 2021-01-10 14:19 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For: #4701

2021-01-10 14:21 UTC, bl-ue requested changes
One tiny nit, otherwise LGTM!

2021-01-10 14:21 UTC, bl-ue commented on pages/common/gh-reference.md
> +> Display a reference about GitHub CLI command.
```suggestion
> Display a reference about the GitHub CLI command.
```

2021-01-10 14:23 UTC, bl-ue approved these changes

2021-01-10 14:29 UTC, bl-ue commented
This is a weird, but useful, command.  It's strange that it's listed in the `gh` help or tab-completion 🤔

2021-01-10 15:26 UTC, navarroaxel commented
> This is a weird, but useful, command. It's strange that it's listed in the `gh` help or tab-completion thinking

Maybe because this is listed in the `gh help` section in the man pages, it's like an easter egg that this runs as a subcommand.

2021-01-10 15:35 UTC, bl-ue commented
>`gh help` section in the man pages

For some reason or other I'm not getting this.  When I run `man gh` it doens't say anything about `gh help`.

2021-01-10 16:01 UTC, navarroaxel commented
@bl-ue actually I was talking about the web man pages https://cli.github.com/manual/gh_help_reference

2021-01-10 16:01 UTC, bl-ue commented
Oh oops!! 🤣

2021-01-16 16:27 UTC, sbrl approved these changes
Nice one!

2021-01-16 16:27 UTC, merged