gh-secret: add page
tldr-pages/tldr pull request #5133
Opened 2021-01-10 19:49 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For: #4701

2021-01-10 19:52 UTC, bl-ue reviewed
What do you mean by "local path"?  "Local repo"?

2021-01-10 19:55 UTC, navarroaxel commented
> What do you mean by "local path"? "Local repo"?

When your `pwd` is inside a Git repository (has a parent folder with a .git/ dir) the `gh` command assume you want to edit that repository.

2021-01-10 19:58 UTC, bl-ue commented
How about changing it to something like "current repo"?  Because that wasn't obvious to me at first, and it may not be (or may be :smile:) to new users.

2021-01-10 20:01 UTC, navarroaxel commented on pages/common/gh-secret.md
> +- Set a secret from `stdin` for the repository in the local path:
```suggestion
- Set a secret from `stdin` for the current repository:
```

2021-01-10 20:01 UTC, navarroaxel commented on pages/common/gh-secret.md
> +- List secret keys for the repository in the local path:
```suggestion
- List secret keys for the current repository:
```

2021-01-10 20:01 UTC, navarroaxel commented on pages/common/gh-secret.md
> +- Remove a secret for the repository in the local path:
```suggestion
- Remove a secret for the current repository:
```

2021-01-10 20:03 UTC, bl-ue requested changes
1 comment.  Otherwise LGTM!

2021-01-10 20:03 UTC, bl-ue commented on pages/common/gh-secret.md
> +- Set a secret from `stdin` for the current repository:
```suggestion
- Set a secret from a file for the current repository:
```

2021-01-10 20:05 UTC, bl-ue approved these changes
Nice. It has a full, beautiful 8 examples! 😉

2021-01-16 16:34 UTC, sbrl approved these changes
Thanks, @navarroaxel!

2021-01-16 16:34 UTC, merged