gh-completion: add page
tldr-pages/tldr pull request #5134
Opened 2021-01-10 20:07 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For: #4701

2021-01-10 20:14 UTC, bl-ue requested changes

2021-01-10 20:14 UTC, bl-ue commented on pages/common/gh-completion.md
> +- Append the `gh` completion script to the `.bashrc`:
```suggestion
- Append the `gh` completion script to `~/.bashrc`:
```

2021-01-10 20:14 UTC, bl-ue commented on pages/common/gh-completion.md
> +- Append the `gh` completion script to the `.zshrc`:
```suggestion
- Append the `gh` completion script to `~/.zshrc`:
```

2021-01-10 20:14 UTC, bl-ue commented on pages/common/gh-completion.md
> +- Print a completion script to `stdout`:
This can be simplified, e.g.:
```suggestion
- Print a completion script:
```

2021-01-10 22:23 UTC, bl-ue approved these changes
Looks good!

By the way, thank you so much for pushing the `gh` page suite to completion!!! 💙

2021-01-13 09:25 UTC, owenvoke approved these changes

2021-01-13 09:25 UTC, merged