partx: add page
tldr-pages/tldr pull request #5158
Opened 2021-01-18 01:29 UTC by sbrl

Found this gem when I wanted to mount a multi-partition disk image backup I took of a hard disk today.

Ref this superuser answer for usage in context: https://superuser.com/a/803776/164168

2021-01-18 03:10 UTC, bl-ue requested changes

2021-01-18 03:10 UTC, bl-ue commented on pages/linux/partx.md
> +> Parse a partition table and tell ther kernel about it.
```suggestion
> Parse a partition table and tell the kernel about it.
> More information: <https://man7.org/linux/man-pages/man8/partx.8.html>.
```

2021-01-18 15:28 UTC, owenvoke approved these changes
LGTM after @bl-ue's suggestion has been resolved.

2021-01-21 00:38 UTC, schneiderl approved these changes
lgtm after @bl-ue's comments are addressed.

2021-01-22 22:59 UTC, bl-ue approved these changes

2021-01-22 22:59 UTC, merged