scrot : add command to display a countdown before taking a screenshot
tldr-pages/tldr pull request #5162
Opened 2021-01-19 15:28 UTC by Raizo62

2021-01-19 15:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5162) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5162) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5162) it.</sub>

2021-01-19 16:42 UTC, bl-ue requested changes
@Raizo62 thank you for the page update!  Could you please change the example to use long options (if possible)?

2021-01-20 19:10 UTC, bl-ue approved these changes

2021-01-21 10:41 UTC, owenvoke approved these changes
LGTM!

2021-01-21 10:41 UTC, merged