Add SSH reverse proxy
tldr-pages/tldr pull request #5164
Opened 2021-01-20 03:01 UTC by yangvw

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2021-01-20 03:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5164) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5164) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5164) it.</sub>

2021-01-20 10:14 UTC, navarroaxel commented
Hi @yangvw, could you please sign the license to pass the `license/cla` check?

2021-01-20 12:23 UTC, bl-ue requested changes
Hello @yangvw and thank you for page update!  I've left some comments below for you to review.

2021-01-20 12:23 UTC, bl-ue commented on pages/common/ssh.md
> +- SSH reverse proxy: Expose a localhost port on the remote server (Set `GatewayPorts yes` in sshd_config to allow internet access):
Two things here:
1. Does "localhost port on the remote server" mean a port that is open on the server, localhost referring to the server itself?
2. "Set `GatewayPorts yes` in sshd_config" &mdash; is `sshd_config` on the server or client?

Also, will you please put `sshd_config` in backticks per WIP PR #5128?

2021-01-22 12:18 UTC, bergentroll commented on pages/common/ssh.md
> +`ssh -NTR {{remote_port}}:localhost:{{local_port}} {{remote_host}}`
For me this duplicates the `ssh -L {{9999}}:{{example.org}}:{{80}}` example and also a bit inconsistent with it.

2021-01-22 23:02 UTC, sbrl commented on pages/common/ssh.md
> +`ssh {{username}}@{{remote_host}} -p {{2222}} {{command -with -flags}}`
I'm not a fan of combining these examples here. It makes the page more dense and difficult to follow for the beginner.

2021-02-06 14:22 UTC, bl-ue commented
Closing as the author seems unavailable and the PR appears to be redundant.

2021-02-06 14:22 UTC, closed without merging