smbget: add page
tldr-pages/tldr pull request #5187
Opened 2021-01-25 23:06 UTC by sawshep

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2021-01-26 00:34 UTC, bl-ue requested changes
Thank you for the new page @sawshep!  I've left some comments below for you to review.

2021-01-26 00:34 UTC, bl-ue commented on pages/linux/smbget.md
> +
When possible, we like to add more information links:
```suggestion
https://www.samba.org/samba/docs/current/man-html/smbget.1.html

```

2021-01-26 00:34 UTC, bl-ue commented on pages/linux/smbget.md
> +`smbget -R {{smb://server/share}}`
```suggestion
`smbget --recursive {{smb://server/share}}`
```

2021-01-26 00:34 UTC, bl-ue commented on pages/linux/smbget.md
> +> Wget-like utility for downloading files from SMB servers.
Maybe this would work (@sbrl, @navarroaxel)?
```suggestion
> `wget`-like utility for downloading files from SMB servers.
```

2021-01-30 21:06 UTC, bl-ue commented on pages/linux/smbget.md
> +> Wget-like utility for downloading files from SMB servers.
I think it's ok.

2021-01-30 21:06 UTC, bl-ue approved these changes

2021-01-30 21:07 UTC, navarroaxel approved these changes

2021-01-30 21:07 UTC, merged