sudo: add link and 4 examples
tldr-pages/tldr pull request #5202
Opened 2021-01-29 16:21 UTC by laurent-indermuehle

* Add a link to the documentation
* Add example to launch shell with root environment
* Add example to launch shell without root environment
* Add example to launch shell with user environment
* Add example to list allowed and forbidden commands

- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-01-29 16:25 UTC, laurent-indermuehle commented
By reading the contribution guide I understood that we should prefer "--login" over "-i" but I respected the existing examples.
It's my first contribution to tldr so feel free to  correct me and overwrites the arguments:

-i => --login
-s => --shell
-u => --user={{user}}
-l => --list

2021-01-29 16:39 UTC, bl-ue commented
@laurent-indermuehle

>but I respected the existing examples

Go ahead and **dis**repect them! :D
Please change the new and the existing examples to use long options ;)

2021-01-29 21:30 UTC, bl-ue requested changes
Thank you for the page update @laurent-indermuehle! I've left some comments below for you to review.

2021-01-29 22:03 UTC, laurent-indermuehle commented on pages/common/sudo.md
> +- Launch the default shell with superuser privileges without his environment:
No, '-s' won't give you a fresh environment. The login-specific files from the user who run `sudo -s` will still be sourced.

2021-01-29 22:05 UTC, bl-ue commented on pages/common/sudo.md
> +- Launch the default shell with superuser privileges without his environment:
Okay, then can you come up with something that doesn't use 'his'? We're supposed to avoid personal pronouns when possible...

2021-01-30 20:58 UTC, bl-ue commented on pages/common/sudo.md
> +- Launch the default shell with superuser privileges without his environment:
How about just this?
```suggestion
- Launch the default shell with superuser privileges:
```

2021-01-30 20:59 UTC, bl-ue commented on pages/common/sudo.md
> +- Launch the default shell with superuser privileges without his environment:
Nevermind&mdash;I see you just made a change :D

2021-01-30 20:59 UTC, bl-ue approved these changes

2021-01-30 21:01 UTC, laurent-indermuehle commented
@bl-ue thanks for the review! Glad I could contribute.

2021-01-30 21:04 UTC, navarroaxel approved these changes

2021-01-30 21:04 UTC, merged