hostnamectl: Add 2 examples
tldr-pages/tldr pull request #5203
Opened 2021-01-29 19:43 UTC by laurent-indermuehle

* How to add a pretty name by fixing the static name first
* How to remove a hostname

- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2021-01-29 20:43 UTC, bl-ue requested changes
Thank you for the page update @laurent-indermuehle! I've left some comments below for you to review.

2021-01-29 20:43 UTC, bl-ue commented on pages/linux/hostnamectl.md
> +- Reset a hostname to its defaults value by passing the empty string:
```suggestion
- Reset hostname to its default value:
```

2021-01-29 20:43 UTC, bl-ue commented on pages/linux/hostnamectl.md
>  `sudo hostnamectl set-hostname "{{some_hostname}}"`
I know you didn't do this, but...see my comment below.
```suggestion
`sudo hostnamectl set-hostname "{{hostname}}"`
```

2021-01-29 20:43 UTC, bl-ue commented on pages/linux/hostnamectl.md
> +`sudo hostnamectl set-hostname --static "{{some_hostname.example.com}}" && sudo hostnamectl set-hostname --pretty "{{some_hostname}}"`
I don't think underscores are actually allowed in domain names...see the [IETF DNS Specification (RFC 1035)](https://tools.ietf.org/html/rfc1035) :)
```suggestion
`sudo hostnamectl set-hostname --static "{{hostname.example.com}}" && sudo hostnamectl set-hostname --pretty "{{hostname}}"`
```

2021-01-30 20:56 UTC, bl-ue approved these changes

2021-01-30 20:59 UTC, navarroaxel approved these changes

2021-01-30 21:00 UTC, merged