Add @schneiderl as org owner
tldr-pages/tldr pull request #5232
Opened 2021-02-04 23:02 UTC by schneiderl

This closes #5224

Once again, thank you for the invite. 😄

2021-02-04 23:09 UTC, bl-ue requested changes
Looks like you mostly forgot to change the dates! :smile:

An automated system would sure be nice, as I have difficulty doing this myself ;)

2021-02-04 23:09 UTC, bl-ue commented on MAINTAINERS.md
> +  [17 January 2020](https://github.com/tldr-pages/tldr/issues/3764) — [8 January 2021](https://github.com/tldr-pages/tldr/issues/5224)
```suggestion
  [17 January 2020](https://github.com/tldr-pages/tldr/issues/3764) — [3 February 2021](https://github.com/tldr-pages/tldr/issues/5224)
```

2021-02-04 23:09 UTC, bl-ue commented on MAINTAINERS.md
> +  [4 January 2021](https://github.com/tldr-pages/tldr/issues/5224) — present
```suggestion
  [3 February 2021](https://github.com/tldr-pages/tldr/issues/5224) — present
```

2021-02-04 23:42 UTC, navarroaxel approved these changes
Looks good after the comments of @bl-ue get addressed

2021-02-05 00:01 UTC, schneiderl commented
lol I thought I've changed that. thank you for the heads up @bl-ue

2021-02-05 00:39 UTC, bl-ue commented
@schneiderl since you're now owner :smile:, will you please tell me, are you able to merge this PR though it's blocked by a request for changes? Just curious :)

2021-02-05 00:50 UTC, sbrl approved these changes
:heart:

2021-02-05 00:53 UTC, bl-ue approved these changes

2021-02-05 00:53 UTC, merged

2021-02-05 01:20 UTC, schneiderl commented
@bl-ue I can't tell for sure because it was merged already but I believe I've seen this happen before so I would say yes it is possible.

2021-02-05 01:29 UTC, bl-ue commented
Really cool.

2021-02-13 21:53 UTC, zlatanvasovic reviewed
Approved.