sort: explain the behavior of the "-t" argument
tldr-pages/tldr pull request #5233
Opened 2021-02-05 08:06 UTC by CrispyBaguette

The behavior of the "-t" argument was not explained, potentially causing confusion in case of reckless copypasting (not that I would know anything about that).

- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).

2021-02-05 12:03 UTC, bl-ue requested changes
Hi @CrispyBaguette, excellent change! I've left a comment below for you to review.

2021-02-05 12:03 UTC, bl-ue commented on pages/common/sort.md
> +- Sort the passwd file by the 3rd field, numerically and using ":" as a field separator:
Perhaps this will read better?
```suggestion
- Sort `/etc/passwd` by the 3rd field of each line numerically, using ":" as a field separator:
```

2021-02-05 12:09 UTC, bl-ue approved these changes

2021-02-05 12:28 UTC, bl-ue requested changes
Actually, I found a few more things ;)

In addition to my suggestions, will you please change `-r` to `--reverse` and `-u` to `--unique` in the other examples?  The longer options are much easier to read.

2021-02-05 12:28 UTC, bl-ue commented on pages/common/sort.md
>  `sort -t: -k 3n /etc/passwd`
```suggestion
`sort --field-separator={{:}} --key={{3n}} {{/etc/passwd}}`
```

2021-02-05 12:28 UTC, bl-ue commented on pages/common/sort.md
>  `sort -n {{path/to/file}}`
```suggestion
`sort --numeric-sort {{path/to/file}}`
```

2021-02-09 12:33 UTC, bl-ue commented
@CrispyBaguette will you please change `-r` to `--reverse` and `-u` to `--unique` in the other examples? The longer options are much easier to read.

Then I think this will OK to merge. 👍🏻

2021-02-09 12:43 UTC, bl-ue approved these changes
LGTM!  Nice catch @CrispyBaguette (😋? :D)

2021-02-09 14:56 UTC, navarroaxel approved these changes

2021-02-09 14:56 UTC, merged