btrfs,btrfs-device,btrfs-filesystem,btrfs-subvolume,btrfs-scrub: add Simplified Chinese translation
tldr-pages/tldr pull request #5244
Opened 2021-02-05 17:31 UTC by CoelacanthusHex

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2021-02-05 17:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5244) it.</sub>

2021-02-05 17:36 UTC, bl-ue commented
Hi @CoelacanthusHex, this is great, but this PR will have to wait a little while, see my PR #5240 for normalizing punctuation across all Chinese pages.

2021-02-05 19:07 UTC, CoelacanthusHex commented
ok, I am waiting, and I will correct punctuation in my pr as #5240 do when it be merged

2021-02-05 19:10 UTC, bl-ue commented
Please feel free to contribute suggestions to that PR, as I don't know Chinese. I'd love for some help from native Chinese speakers ;)

2021-02-07 13:30 UTC, bl-ue requested changes
Hi @CoelacanthusHex, I found a little oversight.

Also, will you please:
1. Change all colons (including ones at the end of example descriptions) to Chinese colons (`：`)
2. Change all periods (including ones at the end of more information links) to Chinese periods (`。`)

Thank you!

2021-02-07 13:30 UTC, bl-ue commented on pages.zh/linux/btrfs-device.md
> +- 从btrfs文件系统中删除设备:
```suggestion
- 从 btrfs 文件系统中删除设备:
```

2021-02-07 13:43 UTC, CoelacanthusHex commented
> Hi @CoelacanthusHex, I found a little oversight.
> 
> Also, will you please:
> 
>     1. Change all colons (including ones at the end of example descriptions) to Chinese colons (`：`)
> 
>     2. Change all periods (including ones at the end of more information links) to Chinese periods (`。`)
> 
> 
> Thank you!

Done!

2021-02-07 13:48 UTC, bl-ue commented
Great.  I think this PR will be merged soon, as I find all of the punctuation and formatted well.  I especially like what you've done here:
https://github.com/tldr-pages/tldr/pull/5244/files#diff-4a913c56aa1d36868ed6ef85cf4d56a934b94c19d5b650f0e4a90d47fc46fcdfR3,
with the `（COW）`, because that solves an issue I've been having with the Chinese parentheses around English sentences (#5240).

2021-02-07 19:07 UTC, navarroaxel commented on pages.zh/linux/btrfs-device.md
> +> 更多信息可参见：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-device>。
I think we use this for the link:
```suggestion
>  更多信息：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-device>。
```

2021-02-07 19:09 UTC, bl-ue commented on pages.zh/linux/btrfs-device.md
> +> 更多信息可参见：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-device>。
According to Google:
- `更多信息可参见` = `For more information, see` 
- `更多信息` = `More information`

2021-02-07 19:12 UTC, bl-ue requested changes
@CoelacanthusHex please apply @navarroaxel's suggestion and these.

See https://github.com/tldr-pages/tldr/pull/5244#discussion_r571672380.  We prefer the shorter version.

2021-02-07 19:12 UTC, bl-ue commented on pages.zh/linux/btrfs-filesystem.md
> +> 更多信息可参见：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-filesystem>。
```suggestion
> 更多信息：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-filesystem>。
```

2021-02-07 19:12 UTC, bl-ue commented on pages.zh/linux/btrfs-scrub.md
> +> 更多信息可参见：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-scrub>。
```suggestion
> 更多信息：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-scrub>。
```

2021-02-07 19:12 UTC, bl-ue commented on pages.zh/linux/btrfs-subvolume.md
> +> 更多信息可参见：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-subvolume>。
```suggestion
> 更多信息：<https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-subvolume>。
```

2021-02-09 10:04 UTC, navarroaxel approved these changes

2021-02-12 21:11 UTC, sbrl approved these changes
Thanks, @CoelacanthusHex!

This reminds me, I should write another page for a btrfs subcommand to keep the ball rolling.

2021-02-12 21:12 UTC, sbrl commented
Are we ok to merge here, @bl-ue/

2021-02-12 21:12 UTC, bl-ue commented
@sbrl I'd like to wait for #5240.

2021-02-28 00:26 UTC, bl-ue commented
Waiting for #5240.  Sorry, I need to get back to that.

2021-03-14 01:48 UTC, einverne approved these changes
Looks good to me. @bl-ue is it good to merge?

2021-03-14 03:35 UTC, bl-ue commented
https://github.com/tldr-pages/tldr/pull/5240 soooorry about this, I need to get back to that ☹️

2021-03-30 13:36 UTC, bl-ue commented
Okay, yes, #5240 will be my first priority (besides PR reviews) 👍🏻

2021-05-17 17:32 UTC, marchersimon commented
How about we merge this PR for now and make changes when we're done with #5240? Many people could use the pages in the meantime.

2021-05-17 17:35 UTC, bl-ue approved these changes
Thank you @CoelacanthusHex!  I'm terrible sorry that this has taken nearly half a year, especially on your first PR 😖

2021-05-17 17:35 UTC, CleanMachine1 approved these changes

2021-05-17 17:35 UTC, CleanMachine1 commented
Merging.

2021-05-17 17:36 UTC, merged