Add Simple Chinese translation
tldr-pages/tldr pull request #5246
Opened 2021-02-06 14:08 UTC by zjuyk

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-02-06 14:09 UTC, zjuyk commented
Add translation for commands which begin with 'a'.

2021-02-06 14:11 UTC, bl-ue commented
@zjuyk several pages have a space after the Chinese colon&mdash;will you please remove them?  If there's a Chinese colon, it shouldn't have a space after. Only English colons need spaces after.

2021-02-06 14:15 UTC, zjuyk commented
I'll review and fix them.

2021-02-06 14:28 UTC, zjuyk commented
@bl-ue I remove the space after the Chinese colon. Are there any other typos?

2021-02-06 15:19 UTC, bl-ue commented
Yes, these pages have more than one newline:

- a2enconf
- aplay
- arecored

Please make sure they have exactly 1 newline at the end.

2021-02-06 15:37 UTC, bl-ue requested changes
Hi, I found a few oversights.

2021-02-06 15:37 UTC, bl-ue commented on pages.zh/linux/add-apt-repository.md
>  > apt 仓库管理.
```suggestion
> apt 仓库管理。
```

2021-02-06 15:37 UTC, bl-ue commented on pages.zh/linux/arithmetic.md
> +- 指定范围。加法和乘法问题限定 0 到指定范围之间的数字，包含上区间。减法和除法问题限制结果和运算数字必须在 0 到指定范围之间。
```suggestion
- 指定范围。加法和乘法问题限定 0 到指定范围之间的数字，包含上区间。减法和除法问题限制结果和运算数字必须在 0 到指定范围之间：
```

2021-02-06 15:37 UTC, bl-ue commented on pages.zh/linux/ac.md
> +> 打印用户连接时长数据
```suggestion
> 打印用户连接时长数据。
```

2021-02-06 16:11 UTC, bl-ue commented
Well this looks good @zjuyk! Hopefully #5240 will agree with this, because the style you're using in these pages (pure Chinese punctuation) is the best, I think.  But I'd like to wait for that one to merged, then I'll merge this one.

2021-02-08 09:27 UTC, Proscream approved these changes

2021-02-08 12:33 UTC, bl-ue commented
I marked this PR as a draft to avoid merging.  It's waiting on #5240.

2021-02-11 14:25 UTC, bl-ue approved these changes

2021-02-12 21:18 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2021-02-28 00:26 UTC, bl-ue commented
Waiting for #5240.  Sorry, I need to get back to that.

2021-04-25 01:55 UTC, bl-ue commented
I'll refresh this now.

2021-05-01 18:04 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2021-05-01 18:43 UTC, bl-ue commented
Apologies @zjuyk for this 可怕的传奇！😅  I'll merge this PR now, _finally_.

2021-05-01 18:43 UTC, merged