iotop: add sudo to all commands
tldr-pages/tldr pull request #5267
Opened 2021-02-15 18:13 UTC by Managor

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-02-15 18:20 UTC, bl-ue commented
@Managor will you please update the translations as well?

2021-02-15 19:15 UTC, Managor commented
Are there any? When using the "Go to file" on github, it shows no other files than just this.

2021-02-15 19:39 UTC, bl-ue commented
Ah, I see! I could've checked myself :smile:

2021-02-15 19:43 UTC, bl-ue requested changes
Nice @Managor.  Let's also use the long options here, while we're at it.

2021-02-15 19:43 UTC, bl-ue commented on pages/common/iotop.md
> +`sudo iotop -o`
```suggestion
`sudo iotop --only`
```

2021-02-15 19:43 UTC, bl-ue commented on pages/common/iotop.md
> +`sudo iotop -b`
```suggestion
`sudo iotop --batch`
```

2021-02-15 19:43 UTC, bl-ue commented on pages/common/iotop.md
>  - Show only I/O usage of processes(Default is to show all threads):
Looks like this got message up at some point ;)
```suggestion
- Show only I/O usage of processes (default is to show all threads):
```

2021-02-15 19:43 UTC, bl-ue commented on pages/common/iotop.md
> +`sudo iotop -p {{PID}}`
```suggestion
`sudo iotop --pid={{PID}}`
```

2021-02-15 19:43 UTC, bl-ue commented on pages/common/iotop.md
> +`sudo iotop -P`
```suggestion
`sudo iotop --processes`
```

2021-02-15 19:43 UTC, bl-ue commented on pages/common/iotop.md
> +`sudo iotop -u {{user}}`
```suggestion
`sudo iotop --user={{user}}`
```

2021-02-15 19:43 UTC, bl-ue commented on pages/common/iotop.md
> +`sudo iotop -a`
```suggestion
`sudo iotop --accumulated`
```

2021-02-15 23:17 UTC, bl-ue approved these changes

2021-02-18 23:17 UTC, sbrl approved these changes
Thanks, @Managor!

2021-02-18 23:18 UTC, merged