pacman-query: add page
tldr-pages/tldr pull request #5269
Opened 2021-02-15 21:09 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For: #5256

2021-02-16 18:52 UTC, bl-ue requested changes

2021-02-16 18:52 UTC, bl-ue commented on pages/linux/pacman-query.md
> +- List orphan packages (installed as dependency not required by any):
```suggestion
- List orphan packages (installed as dependencies but not required by any package):
```

2021-02-16 18:52 UTC, bl-ue commented on pages/linux/pacman-query.md
> +- Find which package owns a certain file:
```suggestion
- Find which package owns a file:
```

2021-02-16 18:52 UTC, bl-ue commented on pages/linux/pacman-query.md
> +- List only the explicitly installed packages and versions:
```suggestion
- List only packages and versions that were explicitly installed:
```

2021-02-16 19:09 UTC, bl-ue approved these changes

2021-02-18 23:21 UTC, sbrl approved these changes
Thanks, @navarroaxel!

2021-02-19 00:44 UTC, merged