pacman-remove: add page
tldr-pages/tldr pull request #5273
Opened 2021-02-17 13:15 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For: #5256

2021-02-17 13:34 UTC, bl-ue requested changes

2021-02-17 13:34 UTC, bl-ue commented on pages/linux/pacman-remove.md
> +- List the affect packages without remove them:
```suggestion
- List packages that would be affected (does remove any packages):
```

2021-02-17 13:34 UTC, bl-ue commented on pages/linux/pacman-remove.md
> +- Remove a package and all packages that depend on them:
```suggestion
- Remove a package and all packages that depend on it:
```

2021-02-17 13:34 UTC, bl-ue commented on pages/linux/pacman-remove.md
> +`pacman --remove --noconfirm {{filename}}`
Mistake?
```suggestion
`pacman --remove --noconfirm {{package_name}}`
```

2021-02-17 13:42 UTC, navarroaxel commented on pages/linux/pacman-remove.md
> +`pacman --remove --noconfirm {{filename}}`
Yep

2021-02-17 14:48 UTC, bl-ue approved these changes

2021-02-18 23:27 UTC, sbrl reviewed
Thanks for the new page! I've left some comments below for you to review.

Also, shouldn't these pacman commands be prefixed with `sudo`, since they require root?

2021-02-18 23:27 UTC, sbrl commented on pages/linux/pacman-remove.md
> +- Remove a package and its dependencies and configuration files:
Perhaps this will read better?
```suggestion
- Remove a package and both its dependencies and configuration files:
```

2021-02-18 23:27 UTC, sbrl commented on pages/linux/pacman-remove.md
> +- List packages that would be affected (does remove any packages):
Perhaps this will read better?
```suggestion
- List packages that would be affected (does not remove any packages):
```

2021-02-18 23:37 UTC, sbrl approved these changes
Thanks, @navarroaxel!

2021-02-19 10:29 UTC, merged