Vercel CLI
tldr-pages/tldr pull request #5278
Opened 2021-02-18 19:52 UTC by TGIFelix

- [x ] The page (if new), does not already exist in the repo.
- [x ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ x] The page has 8 or fewer examples.
- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x ] The page description includes a link to documentation or a homepage (if applicable).

2021-02-18 19:55 UTC, bl-ue requested changes
Hello @TGIFelix and thank you for the new page! I've left some comments below for you to review.

2021-02-18 19:55 UTC, bl-ue commented on pages/common/vercel.md
> +> https://vercel.com/docs/cli
```suggestion
> More information: <https://vercel.com/docs/cli>.
```

2021-02-18 19:55 UTC, bl-ue commented on pages/common/vercel.md
> +- Remove a deployment
```suggestion
- Remove a deployment:
```

2021-02-18 19:55 UTC, bl-ue commented on pages/common/vercel.md
> +`vercel /path/to/my_project`
prefer relative when possible (also simpler :wink:)
```suggestion
`vercel {{path/to/project}}`
```

2021-02-18 19:55 UTC, bl-ue commented on pages/common/vercel.md
> +`vercel rm <project name>`
We have specific syntax for user-provided values:
```suggestion
`vercel rm {{project_name}}`
```

2021-02-18 20:00 UTC, bl-ue requested changes
I've suggested some grammar changes.  Please feel free to discuss them.

2021-02-18 20:02 UTC, navarroaxel reviewed
I think we should add examples for `init`, `--build-env`, `--env` and `--regions`.
Looks like we have subcommands here. Also `now` was replaced by `vercel`, so I think we should delete now.md on this PR.

2021-02-18 20:02 UTC, bl-ue approved these changes

2021-02-18 20:55 UTC, navarroaxel requested changes
please add the `--build-env`

2021-02-18 20:55 UTC, navarroaxel commented on pages/common/vercel.md
> +`vercel -e {{ENV}}={{var}}`
```suggestion
`vercel --env {{ENV}}={{var}}`
```

2021-02-18 20:55 UTC, navarroaxel commented on pages/common/vercel.md
> +`vercel rm {{project_name}}`
Please use long argument format
```suggestion
`vercel remove {{project_name}}`
```

2021-02-18 21:42 UTC, bl-ue commented
@TGIFelix also delete `now.md`.

2021-02-18 22:07 UTC, bl-ue approved these changes

2021-02-18 23:36 UTC, sbrl approved these changes
Hey there, @TGIFelix! Welcome to tldr-pages. This looks great to me - thanks!

2021-02-19 10:11 UTC, navarroaxel approved these changes

2021-02-19 10:11 UTC, merged

2021-02-19 10:15 UTC, TGIFelix commented
Thanks a lot for your help folks. Sorry for such a messy pull request, but at least I know now for future contributions!

2021-02-19 10:18 UTC, navarroaxel commented
Don't worry @TGIFelix that was a common review process!
Also `vercel` has a lot of subcommands like `vercel secrets`. You can send more PR's adding pages like `vercel-secrets.md`, `vercel-env.md`, etc.