speedtest: add page
tldr-pages/tldr pull request #5282
Opened 2021-02-19 15:30 UTC by marchersimon

speedtest: add page

2021-02-19 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5282) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5282) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5282) it.</sub>

2021-02-19 15:34 UTC, bl-ue requested changes
Looks good @marchersimon, however there's no link.  Will you please add a link in the form:
```
> Test internt bandwith using speedtest.net
> More information: <url here (https if possible)>.`
```

2021-02-19 15:34 UTC, bl-ue commented on pages/linux/speedtest.md
> +> Test internet bandwidth using speedtest.net
```suggestion
> Test internet bandwidth using https://www.speedtest.net.
```

2021-02-19 15:34 UTC, bl-ue commented on pages/linux/speedtest.md
> +- Run basic speedtest:
```suggestion
- Run a basic speedtest:
```

2021-02-19 15:34 UTC, bl-ue commented on pages/linux/speedtest.md
> +- Use https instead of http:
```suggestion
- Use HTTPS instead of HTTP:
```

2021-02-19 16:39 UTC, navarroaxel commented
Hi @marchersimon we have a `speedtest-cli` in https://github.com/tldr-pages/tldr/blob/master/pages/common/speedtest-cli.md maybe we need an alias because the package install both commands `speedtest` and `speedtest-cli`.

2021-02-19 17:20 UTC, bl-ue commented
@navarroaxel are you sure it's the same one?

2021-02-19 17:22 UTC, navarroaxel commented
yep, but I didn't mean to close this PR. I think we need an alias page because I think a few people use `speedtest-cli`

2021-02-19 17:25 UTC, bl-ue commented
We also need an alias system in general 🙏🏻

2021-02-19 18:23 UTC, marchersimon commented
> yep, but I didn't mean to close this PR. I think we need an alias page because I think a few people use `speedtest-cli`

How can I do that? I didn't find anything about alias pages in `CONTRIBUTING.md`

2021-02-21 02:01 UTC, einverne approved these changes
Looks good to me, thanks for the new page.

2021-02-21 05:10 UTC, navarroaxel approved these changes

2021-02-21 12:42 UTC, bl-ue commented
I already have a PR queued for speedtest-cli.  I vote for: merge this PR as is and then after #5284 is merged, sync that and this page.  @navarroaxel @einverne what do you think?

2021-02-21 12:56 UTC, einverne commented
> I already have a PR queued for speedtest-cli.  I vote for: merge this PR as is and then after #5284 is merged, sync that and this page.  @navarroaxel @einverne what do you think?

It's ok with me, but we seems to need an alias mechanism.

2021-02-21 13:04 UTC, bl-ue commented
Totally, but that's for a different day unfortunately.  Ideally we would use YAML frontmatter and place 
```markdown
---
title: speedtest-cli
alias: speedtest
---
```
as the only content in `speedtest-cli.md`.  Someday we shall do it, because everyone uses frontmatter and it could solve a lot of problems for us, but...

2021-02-21 13:05 UTC, bl-ue approved these changes

2021-02-21 13:05 UTC, merged

2021-02-21 18:24 UTC, bl-ue commented
Oops! this was in `linux/`.  I'll move it to `common/` in this experimental PR that I'm opening.