tex, pdftex, latex, pdflatex, tlmgr, texdoc, texliveonfly: add german translation
tldr-pages/tldr pull request #5305
Opened 2021-02-22 09:55 UTC by marchersimon

2021-02-23 02:33 UTC, bl-ue requested changes

2021-02-23 02:33 UTC, bl-ue commented on pages.de/common/texliveonfly.md
> +-Lade fehlende Packages während dem Kompilieren herunter:
```suggestion
- Lade fehlende Packages während dem Kompilieren herunter:
```

2021-02-23 02:33 UTC, bl-ue commented on pages.de/common/texdoc.md
> +- Öffne die vollständige Dokumentation von `texdoc`
```suggestion
- Öffne die vollständige Dokumentation von `texdoc`:
```

2021-02-23 12:14 UTC, bl-ue approved these changes

2021-02-25 23:05 UTC, sbrl reviewed
Nice work, @marchersimon! However the English versions of these pages have yet to be merged, so I'm hesitant to merge this PR since I've left some comments on that one. Not knowing German myself, I'm unsure as to whether my comments will affect the German translations or not.

2021-02-26 09:18 UTC, marchersimon commented
@sbrl, all except for the one I left open for now only concerned English grammar. However I will proofread my translations once more and see if I can find any room for improvement.

2021-02-26 12:07 UTC, bl-ue approved these changes

2021-02-28 14:27 UTC, navarroaxel approved these changes

2021-02-28 14:27 UTC, merged