pngcheck: add page
tldr-pages/tldr pull request #5310
Opened 2021-02-25 13:49 UTC by rhapsodyn

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-02-25 13:57 UTC, bl-ue commented on pages/common/pngcheck.md
> +- Print summary (width & height & color depth):
```suggestion
- Print summary (width, height, and color depth):
```

2021-02-25 14:02 UTC, bl-ue requested changes
Hi @rhapsodyn, thank you for the new page.  I've left some comments below, for you to review.

2021-02-25 14:02 UTC, bl-ue commented on pages/common/pngcheck.md
> +`pngcheck foo.png`
```suggestion
`pngcheck {{image.png}}`
```

2021-02-25 14:02 UTC, bl-ue commented on pages/common/pngcheck.md
> +`pngcheck -c foo.png`
```suggestion
`pngcheck -c {{image.png}}`
```

2021-02-25 14:02 UTC, bl-ue commented on pages/common/pngcheck.md
> +`pngcheck -cvt foo.png`
```suggestion
`pngcheck -cvt {{image.png}}`
```

2021-02-25 14:02 UTC, bl-ue commented on pages/common/pngcheck.md
> +> Pngcheck verifies the integrity of PNG, JNG and MNG files (by checking the internal 32-bit CRCs, a.k.a. checksums, and decompressing the image data).
```suggestion
> Print detailed information about and verify PNG, JNG, and MNG files.
```

2021-02-25 14:02 UTC, bl-ue commented on pages/common/pngcheck.md
> +> It can optionally dump almost all of the chunk-level information in the image in human-readable form.
```suggestion
```

2021-02-26 12:06 UTC, bl-ue approved these changes

2021-02-26 15:13 UTC, owenvoke approved these changes
LGTM! Just a couple of minor changes I'd suggest, but they aren't really necessary, just suggestions.

2021-02-26 15:13 UTC, owenvoke commented on pages/common/pngcheck.md
> +- Print summary (width, height, and color depth):
```suggestion
- Print a summary for an image (width, height, and color depth):
```

2021-02-26 15:13 UTC, owenvoke commented on pages/common/pngcheck.md
> +- Print detailed information:
```suggestion
- Print [v]erbose information for an image:
```

2021-02-26 15:13 UTC, owenvoke commented on pages/common/pngcheck.md
> +- Print [c]olorized output:
```suggestion
- Print information for an image with [c]olorized output:
```

2021-02-27 03:17 UTC, navarroaxel commented on pages/common/pngcheck.md
> +`pngcheck -cvt {{image.png}}`
I think we could add some extra examples:
```suggestion
`pngcheck -cvt {{image.png}}`

- Receive an image from stdin and display detailed information:

`cat {{path/to/image.png}} | pngcheck -cvt`

- [s]earch for PNGs within a specific file and display information about them:

`pngcheck -s {{image.png}}`

- Search for PNGs within another file and e[x]tract them:

`pngcheck -x {{image.png}}`
```

2021-02-28 16:54 UTC, navarroaxel approved these changes

2021-02-28 17:08 UTC, navarroaxel commented on pages/common/pngcheck.md
> +- [s]earch for PNGs within a specific file and display information about them:
No. Looks like a PNG could be built by a PNG composition. Or you can hide PNG in another type of binary files

2021-02-28 17:11 UTC, bl-ue commented on pages/common/pngcheck.md
> +- [s]earch for PNGs within a specific file and display information about them:
Hmm...so a 'PNG' is actually just an object.  🤔 

I guess we should keep it as is then!

2021-02-28 17:11 UTC, bl-ue approved these changes

2021-02-28 17:11 UTC, merged