pacman-mirrors: add page
tldr-pages/tldr pull request #5315
Opened 2021-02-27 12:56 UTC by marchersimon

The man page and the Manjaro wiki state that it's necessary to run `sudo pacman -Syyu` after every run of `pacman-mirrors`. However I'm not sure if and where I should add that to the tldr page.

2021-02-27 20:43 UTC, navarroaxel requested changes

2021-02-27 20:43 UTC, navarroaxel commented on pages/linux/pacman-mirrors.md
> +`sudo pacman-mirrors --status`
Doesn't require sudo.
```suggestion
`pacman-mirrors --status`
```

2021-02-27 20:43 UTC, navarroaxel commented on pages/linux/pacman-mirrors.md
> +`sudo pacman-mirrors -f`
We prefer long arguments
```suggestion
`sudo pacman-mirrors --fasttrack`
```

2021-02-27 20:43 UTC, navarroaxel commented on pages/linux/pacman-mirrors.md
> +`sudo pacman-mirrors --get-branch`
Doesn't require sudo.
```suggestion
`pacman-mirrors --get-branch`
```

2021-02-27 20:43 UTC, navarroaxel commented on pages/linux/pacman-mirrors.md
> +- Check, which branch you are on:
```suggestion
- Display which branch you are on:
```

2021-02-27 20:43 UTC, navarroaxel commented on pages/linux/pacman-mirrors.md
> +`sudo pacman-mirrors --api --setbranch {{stable|unstable|testing}}`
A typo here:
```suggestion
`sudo pacman-mirrors --api --set-branch {{stable|unstable|testing}}`
```

2021-02-27 20:46 UTC, bl-ue commented on pages/linux/pacman-mirrors.md
> +- Check, which branch you are on:
I think this is better:
```suggestion
- Display the current branch:
```

2021-02-27 20:49 UTC, navarroaxel commented on pages/linux/pacman-mirrors.md
> +- Check, which branch you are on:
Thanks @bl-ue !

2021-02-28 03:02 UTC, navarroaxel reviewed
I think we can add the warning in the command description section.

2021-02-28 03:02 UTC, navarroaxel commented on pages/linux/pacman-mirrors.md
> +> Generate a pacman mirrorlist for Manjaro Linux.
```suggestion
> Generate a pacman mirrorlist for Manjaro Linux.
> Every run of pacman-mirrors requires you to synchronize your database and update your system using `sudo pacman -Syyu`.
```

2021-02-28 15:16 UTC, bl-ue approved these changes

2021-02-28 15:16 UTC, bl-ue commented on pages/linux/pacman-mirrors.md
> +- Generate a mirrorlist, using the default settings:
Whoops! found one thing:
```suggestion
- Generate a mirrorlist using the default settings:
```

2021-02-28 15:22 UTC, bl-ue approved these changes

2021-02-28 17:23 UTC, navarroaxel approved these changes

2021-02-28 17:23 UTC, merged