Translate base64.md to TR
tldr-pages/tldr pull request #5318
Opened 2021-02-28 20:23 UTC by Yutyo

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-02-28 20:55 UTC, bl-ue commented on pages.tr/common/base64.md
> +> Bir dosya veya standart veriyi Base64 formatında şifrele veya yalın veri çıktısı olarak deşifre et.
There should be an empty newline after the page description.
```suggestion
> Bir dosya veya standart veriyi Base64 formatında şifrele veya yalın veri çıktısı olarak deşifre et.

```

2021-02-28 21:05 UTC, bl-ue requested changes
Looks good. I'd like to wait on merging this, though, because we have a PR in progress (#5234) that's modifying `base64.md` and `base32.md` and I'd like to get that merged and this updated first.

2021-03-07 22:42 UTC, bl-ue requested changes
@Yutyo, please apply these changes from #5234.

2021-03-07 22:42 UTC, bl-ue commented on pages.tr/common/base64.md
> +`base64 -d {{dosyaismi}}`
```suggestion
`base64 --decode {{dosyaismi}}`
```

2021-03-07 22:42 UTC, bl-ue commented on pages.tr/common/base64.md
> +`{{herhangibirkomut}} | base64 -d`
```suggestion
`{{herhangibirkomut}} | base64 --decode`
```

2021-03-07 22:59 UTC, bl-ue approved these changes

2021-03-08 20:16 UTC, sbrl approved these changes
Thanks, @Yutyo!

2021-03-08 20:16 UTC, merged