docker~.md: add Turkish translations
tldr-pages/tldr pull request #5321
Opened 2021-02-28 22:43 UTC by Yutyo

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-02-28 22:47 UTC, bl-ue commented
This is beautiful @Yutyo! I'll get started reviewing this.

2021-02-28 22:50 UTC, bl-ue requested changes
Found jJust two tiny oversights.

2021-02-28 22:50 UTC, bl-ue commented on pages.tr/common/docker-network.md
> +- Kullanıcı tarafından belirtilmiş bir ağ oluştur
```suggestion
- Kullanıcı tarafından belirtilmiş bir ağ oluştur:
```

2021-02-28 22:50 UTC, bl-ue commented on pages.tr/common/docker-machine.md
> +`docker-machine create {{isim}}
```suggestion
`docker-machine create {{isim}}`
```

2021-03-01 21:02 UTC, Yutyo commented
The change requests seem to be outdated, therefore it shouldn't say "changes requested".

2021-03-01 21:05 UTC, bl-ue approved these changes
It's because the person who requested the changes needs to approve, or the requested changes need to be dismissed by another collaborator.  They should be gone now.

---

Wow&mdash;really nice job @Yutyo!  This is a great batch of stuff.

2021-03-02 11:26 UTC, navarroaxel approved these changes

2021-03-02 11:26 UTC, merged