tree.md: add Turkish translation
tldr-pages/tldr pull request #5331
Opened 2021-03-01 21:20 UTC by Yutyo

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-03-01 21:24 UTC, bl-ue requested changes

2021-03-01 21:24 UTC, bl-ue commented on pages.tr/linux/tree.md
> +rint directories within the tree hierarchy, using the wildcard (glob) pattern, and pruning out directories that aren't ancestors of the wanted one:
```suggestion
```

2021-03-01 21:57 UTC, bl-ue approved these changes

2021-03-02 11:11 UTC, navarroaxel approved these changes

2021-03-02 11:12 UTC, merged