Create tcpdump.md
tldr-pages/tldr pull request #5340
Opened 2021-03-03 10:07 UTC by tcpdump-examples

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-03-03 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5340) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5340) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5340) it.</sub>

2021-03-04 05:56 UTC, Yutyo approved these changes
I think it looks OK at the moment. LGTM!

2021-03-04 15:09 UTC, bl-ue requested changes
Hey there @tcpdump-examples!  This is long-needed page, so I'd like to thank you for it!

However, it isn't consistent with the rest of our pages in a few spots, so please apply my syntactic suggestions below so I can have a look at the semantics 😉

2021-03-04 15:09 UTC, bl-ue commented on pages/linux/tcpdump.md
> +`tcpdump -i ens160 -c 5 -nn tcp`
Why are there two `n`'s here?
```suggestion
`tcpdump --interface={{interface}} --count={{5}} -nn tcp`
```

2021-03-04 15:09 UTC, bl-ue commented on pages/linux/tcpdump.md
> +`$ tcpdump -i ens160 -w /tmp/network-%H-%M.pcap -W 48 -G 300 -C 100`
```suggestion
`tcpdump --interface={{interface}} -w {{path/to/file.pcap}} -W {{48}} -G {{300}} -C {{100}}`
```

2021-03-04 15:09 UTC, bl-ue commented on pages/linux/tcpdump.md
> +`tcpdump src 100.10.8.121`
```suggestion
`tcpdump {{100.10.8.121}}`
```

2021-03-08 19:24 UTC, sbrl reviewed
Looks ok to me when @bl-ue's comments are addressed :-)

2021-03-26 00:38 UTC, bl-ue commented on pages/linux/tcpdump.md
> +> [useful tcpdump examples](https://www.howtouselinux.com/post/10-useful-tcpdump-command-examples).
ping @tcpdump-examples

2021-03-26 17:39 UTC, marchersimon commented on pages/linux/tcpdump.md
> +- Capture traffic on specific interface:
```suggestion
- Capture traffic on a specific interface:
```

2021-03-26 17:40 UTC, marchersimon commented on pages/linux/tcpdump.md
> +> [useful tcpdump examples](https://www.howtouselinux.com/post/10-useful-tcpdump-command-examples).
According to the maintainers guide we can commit the chnanges ourselves and merge, right?

2021-03-26 17:46 UTC, bl-ue commented on pages/linux/tcpdump.md
> +> [useful tcpdump examples](https://www.howtouselinux.com/post/10-useful-tcpdump-command-examples).
Yeah, it's been almost a month now so I think we should just take over 👍🏻

2021-03-26 17:50 UTC, marchersimon approved these changes

2021-03-26 17:57 UTC, bl-ue commented
Haha, I just happened to notice that we (me, @tcpdump-examples, @sbrl, @marchersimon and @Yutyo) all missed the fact that [`common/tcpdump.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/tcpdump.md) (as opposed to this PR's _[`common/linux.md`](https://github.com/tldr-pages/tldr/pull/5340/files#diff-37ab68d030f793f4a18b75a2eb21caf0d126ac5b841ebd2b9eb91c287376519c)_) is one of our oldest pages, being added in PR #138. :smile:

I'm going to close this PR as the existing page already 8 examples and the author of this PR appears to have abandoned it.

2021-03-26 17:57 UTC, closed without merging