next: add page
tldr-pages/tldr pull request #5385
Opened 2021-03-07 20:13 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-03-07 20:22 UTC, bl-ue requested changes
Nice.  I've left a few comments.

2021-03-07 20:22 UTC, bl-ue commented on pages/common/next.md
> +> The Reactjs framework to build optimized web applications.
```suggestion
> Server-side rendered React framework for building optimized web applications.
```

2021-03-07 20:22 UTC, bl-ue commented on pages/common/next.md
> +- Start the current application in a specific port:
```suggestion
- Start the current application and listen on a specific port:
```

2021-03-07 20:22 UTC, bl-ue commented on pages/common/next.md
> +- Start the compiled application in a specific port:
```suggestion
- Start the compiled application and listen on a specific port:
```

2021-03-07 20:27 UTC, bl-ue approved these changes

2021-03-08 19:57 UTC, sbrl approved these changes
Thanks, @navarroaxel!

2021-03-08 19:57 UTC, sbrl commented on pages/common/next.md
> +> React framework that uses server-side rendered for building optimized web applications.
Perhaps this will read better?
```suggestion
> React framework that uses server-side rendering for building optimized web applications.
```

2021-03-08 19:58 UTC, bl-ue commented on pages/common/next.md
> +> React framework that uses server-side rendered for building optimized web applications.
That was my mistake.

2021-03-08 20:50 UTC, merged