arduino: add page
tldr-pages/tldr pull request #5389
Opened 2021-03-09 17:49 UTC by marchersimon

2021-03-09 18:00 UTC, bl-ue requested changes
Cool page @marchersimon.  I've left one tiny comment below.

2021-03-09 21:19 UTC, bl-ue approved these changes

2021-03-13 20:22 UTC, sbrl reviewed
Thanks for the new page! I've left some comments below for you to review.

2021-03-13 20:22 UTC, sbrl commented on pages/common/arduino.md
> +> Arduino Studio - Integrated Development Environment for Arduino boards.
This might be more accurate.
```suggestion
> Arduino Studio - Integrated Development Environment for the Arduino platform.
```

2021-03-13 20:22 UTC, sbrl commented on pages/common/arduino.md
> +- Build a sketch, put the build results in the build directory an reuse any previous build results in that directory:
typo?
```suggestion
- Build a sketch, put the build results in the build directory, and reuse any previous build results in that directory:
```

2021-03-13 21:42 UTC, sbrl approved these changes
Thanks, @marchersimon!

2021-03-13 21:43 UTC, merged