paru: change last example
tldr-pages/tldr pull request #5417
Opened 2021-03-11 16:41 UTC by agstrc

Change "paru -P --stats", which no longer works, to a new, and also useful, example.

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-03-11 16:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5417) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5417) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5417) it.</sub>

2021-03-11 16:47 UTC, agstrc commented
Example showing that the previous command no longer works:
![example](https://user-images.githubusercontent.com/50991916/110822855-4164b880-8270-11eb-94db-885dbbf3be9f.png)

2021-03-11 16:50 UTC, bl-ue approved these changes
Nice.  @agstrc while you're here, do you mind updating the more information link to begin with a capital 'M' like this:
```diff
- https://github.com/morganamilo/paru
+ https://github.com/Morganamilo/paru
```
That's the real URL.

2021-03-11 16:50 UTC, owenvoke approved these changes

2021-03-11 16:53 UTC, bl-ue commented
Pinging @navarroaxel as he's an (the?) arch master @tldr-pages 🙂

2021-03-13 12:11 UTC, navarroaxel requested changes

2021-03-13 12:11 UTC, navarroaxel commented on pages/linux/paru.md
> +- Download PKGBUILDs from the AUR or ABS:
This download all the package source files not only the `PKGBUILD`.
```suggestion
- Download `PKGBUILD` and other package source files from the AUR or ABS:
```
@bl-ue ?

2021-03-13 15:12 UTC, agstrc commented
Just pushed the requested changes

2021-03-13 15:45 UTC, navarroaxel approved these changes

2021-03-13 15:48 UTC, bl-ue approved these changes
One minor change, but looks good otherwise 👍🏻

2021-03-13 15:48 UTC, bl-ue commented on pages/linux/paru.md
> +- Display the `PKGBUILD` of a package:
```suggestion
- Display the `PKGBUILD` file of a package:
```

2021-03-13 16:02 UTC, merged

2021-03-13 16:06 UTC, bl-ue commented
Welcome to tldr-pages, @agstrc! 🙂