Add flatpak info and remove
tldr-pages/tldr pull request #5422
Opened 2021-03-12 11:03 UTC by evaleries

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-03-12 11:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5422) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5422) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5422) it.</sub>

2021-03-12 12:37 UTC, bl-ue requested changes
Thank you for the page update @evaleries (and filling it up to the max of 8 examples :wink:).  I've left two comments below for you to review.

2021-03-12 12:37 UTC, bl-ue commented on pages/linux/flatpak.md
> +`flatpak remove {{name/application id}}`
I think we could be a bit more consisten with the other examples here.
```suggestion
`flatpak remove {{name}}`
```

2021-03-12 12:37 UTC, bl-ue commented on pages/linux/flatpak.md
> +`flatpak info {{name/application id}}`
Same here.
```suggestion
`flatpak info {{name}}`
```

2021-03-12 12:38 UTC, bl-ue commented on pages/linux/flatpak.md
> +
Apply this suggestion to fix @tldr-bot's warning.
```suggestion
```

2021-03-12 12:39 UTC, bl-ue commented
Also @evaleries, will you please sign the [CLA](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5422) to pass the `license/cla` CI check?

2021-03-12 12:53 UTC, bl-ue approved these changes
Very nice, thank you @evaleries!!

2021-03-12 15:14 UTC, marchersimon commented on pages/linux/flatpak.md
> +- Get an info from installed application:
Just a little suggestion to keep it consistent with our other pages:
```suggestion
- Show information about an installed application:
```

2021-03-12 15:22 UTC, owenvoke approved these changes
LGTM after @marchersimon's comment has been addressed.

2021-03-26 17:45 UTC, marchersimon commented on pages/linux/flatpak.md
> +- Get an info from installed application:
@evaleries why did you mark that as resolved?

2021-03-27 14:33 UTC, bl-ue approved these changes

2021-03-27 14:35 UTC, marchersimon approved these changes

2021-03-27 14:36 UTC, merged

2021-03-27 14:37 UTC, bl-ue commented
Welcome to tldr-pages, @evaleries! 🎉