tldrl: add Turkish translation
tldr-pages/tldr pull request #5465
Opened 2021-03-17 12:25 UTC by Yutyo

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-03-17 14:24 UTC, bl-ue requested changes
Thank you, @Yutyo!

2021-03-17 14:24 UTC, bl-ue commented on pages.tr/common/tldrl.md
> +>  `tldr-lint` komutunun aynısı.
```suggestion
> `tldr-lint` komutunun aynısı.
```

2021-03-17 19:33 UTC, bl-ue approved these changes

2021-03-17 20:52 UTC, marchersimon commented on pages.tr/common/tldrl.md
> + `tldr tldr-lint`
```suggestion
`tldr tldr-lint`
```

2021-03-19 09:37 UTC, marchersimon approved these changes

2021-03-19 10:09 UTC, navarroaxel approved these changes

2021-03-19 10:09 UTC, merged