yay: add information on how to remove package
tldr-pages/tldr pull request #5486
Opened 2021-03-22 12:58 UTC by periode

Hello! Here's a PR for adding a line on how to remove a package with Yay.

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

(fun fact: [this](https://github.com/Jguer/yay/issues/496) is currently the first search result for "how to remove a package yay", and isn't particularly helpful/healthy ;) )

2021-03-22 12:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5486) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5486) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5486) it.</sub>

2021-03-22 13:03 UTC, navarroaxel requested changes

2021-03-22 13:03 UTC, navarroaxel commented on pages/linux/yay.md
> +`yay -Rs {{package_name}}`
```suggestion
`yay -Rns {{package_name}}`
```

2021-03-22 13:03 UTC, navarroaxel commented on pages/linux/yay.md
> +- Remove an installed package:
Based on [pacman-remove](https://github.com/tldr-pages/tldr/blob/master/pages/linux/pacman-remove.md)
```suggestion
- Remove an installed package and both its dependencies and configuration files:
```

2021-03-25 01:01 UTC, sbrl approved these changes
Hey there, @periode! Welcome to tldr-pages :wave: 

Wow, this is really the top search result? Impressive haha :P

Anyway, this looks fine to me after @navarroaxel's comments are addressed.

2021-03-25 01:46 UTC, bl-ue approved these changes

2021-03-25 12:30 UTC, navarroaxel approved these changes

2021-03-25 12:31 UTC, merged