xdg-open: add pages
tldr-pages/tldr pull request #5516
Opened 2021-03-28 11:51 UTC by goznalo-git

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

Hey, a couple pages on the xdg-open tool, quite useful to open files in graphical applications. I also added the Spanish translation.

2021-03-28 12:43 UTC, marchersimon requested changes
Thanks for the new page! 
I've just a few suggestions. Also, adding `xdg-open .` for opening the current directory in the default file manager would be great.

2021-03-28 12:43 UTC, marchersimon commented on pages.es/linux/xdg-open.md
> +`xdg-open {{pagina_web}}`
```suggestion
`xdg-open {{https://www.ejemplo.es}}`
```

2021-03-28 12:43 UTC, marchersimon commented on pages.es/linux/xdg-open.md
> +`xdg-open {{archivo_imagen}}`
```suggestion
`xdg-open {{ruta/al/imagen}}`
```

2021-03-28 12:43 UTC, marchersimon commented on pages.es/linux/xdg-open.md
> +`xdg-open {{archivo_pdf}}`
```suggestion
`xdg-open {{ruta/al/pdf}}`
```

2021-03-28 12:43 UTC, marchersimon commented on pages/linux/xdg-open.md
> +`xdg-open {{website}}`
```suggestion
`xdg-open {{https://example.com}}`
```

2021-03-28 12:43 UTC, marchersimon commented on pages/linux/xdg-open.md
> +`xdg-open {{image_file}}`
```suggestion
`xdg-open {{path/to/image}}`
```

2021-03-28 12:43 UTC, marchersimon commented on pages/linux/xdg-open.md
> +`xdg-open {{pdf_file}}`
```suggestion
`xdg-open {{path/to/pdf}}`
```

2021-03-28 16:04 UTC, goznalo-git reviewed
All suggestions added

2021-03-28 16:09 UTC, marchersimon approved these changes

2021-03-28 18:10 UTC, bl-ue approved these changes
Looks good to me. I'm not sure about More information link—there ought to be one, but I can only find a die.net man page, no man7.org one 🤷🏻

2021-03-28 18:14 UTC, navarroaxel requested changes

2021-03-28 18:14 UTC, navarroaxel commented on pages/linux/xdg-open.md
> +- Display the command's help:
```suggestion
- Display help:
```

2021-03-28 18:14 UTC, navarroaxel commented on pages/linux/xdg-open.md
> +- Open an URL in the system's default browser:
Based on `gh-gist` and other pages we can simplify this sentence:
```suggestion
- Open an URL in the default browser:
```

2021-03-28 18:14 UTC, navarroaxel commented on pages/linux/xdg-open.md
> +- Open an image in the system's default image viewer:
```suggestion
- Open an image in the default image viewer:
```

2021-03-28 18:14 UTC, navarroaxel commented on pages/linux/xdg-open.md
> +- Open a PDF in the system's default PDF viewer:
```suggestion
- Open a PDF in the default PDF viewer:
```

2021-03-28 18:14 UTC, navarroaxel commented on pages/linux/xdg-open.md
> +- Open the current directory in the system's default file explorer:
```suggestion
- Open the current directory in the default file explorer:
```

2021-03-28 18:14 UTC, navarroaxel commented on pages.es/linux/xdg-open.md
> +- Muestra la ayuda del comando:
```suggestion
- Muestra la ayuda:
```

2021-03-29 07:34 UTC, goznalo-git reviewed
All changes accepted!

2021-03-29 08:21 UTC, marchersimon approved these changes

2021-03-29 11:43 UTC, navarroaxel requested changes

2021-03-29 11:43 UTC, navarroaxel commented on pages/linux/xdg-open.md
> +> Opens a file or URL in the user's preferred application.
```suggestion
> Opens a file or URL in the user's preferred application.
> More information: <https://man.archlinux.org/man/xdg-open.1>.
```

2021-03-29 11:43 UTC, navarroaxel commented on pages.es/linux/xdg-open.md
> +> Abre un archivo o URL en la aplicación predeterminada del usuario.
```suggestion
> Abre un archivo o URL en la aplicación predeterminada del usuario.
> Más información: <https://man.archlinux.org/man/xdg-open.1>.
```

2021-03-29 12:44 UTC, navarroaxel approved these changes

2021-03-29 12:44 UTC, merged