autopep8: init english and dutch pages
tldr-pages/tldr pull request #5645
Opened 2021-03-30 16:20 UTC by Waples

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-03-30 16:35 UTC, bl-ue requested changes
Welcome back @Waples!  I left some comments below.  Please also update the Dutch translation when you've applied the suggestions to the English one.

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +- Print the diff for the fixed source:
```suggestion
- Format a file, displaying a diff of the changes:
```

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +- Print out formatted file with set maximium allowed line length:
```suggestion
- Format a file to stdout, with a custom maximium line length:
```

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +- Format the file in-pace:
```suggestion
- Format a file in-pace:
```

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +- Format the files in-pace recursivly in dir:
```suggestion
- Recursively format all files in a directory in-place:
```

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +> Automatically formats Python code to confrom to the PEP 8 style guide.
```suggestion
> Format Python code according to the PEP 8 style guide.
```

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +`autopep8 {{path/to/file}} --max-line-length {{len}}`
```suggestion
`autopep8 {{path/to/file.py}} --max-line-length {{len}}`
```

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +`autopep8 --in-place {{path/to/file}}`
```suggestion
`autopep8 --in-place {{path/to/file.py}}`
```

2021-03-30 16:35 UTC, bl-ue commented on pages/common/autopep8.md
> +`autopep8 --in-place --recursive {{path/to/dir}}`
```suggestion
`autopep8 --in-place --recursive {{path/to/directory}}`
```

2021-03-30 16:35 UTC, bl-ue commented on pages.nl/common/autopep8.md
> +`autopep8 {{pad/naar/bestand}} --max-line-length {{len}}`
```suggestion
`autopep8 {{pad/naar/bestand.py}} --max-line-length {{len}}`
```

2021-03-30 16:35 UTC, bl-ue commented on pages.nl/common/autopep8.md
> +`autopep8 --diff {{pad/naar/bestand}}`
```suggestion
`autopep8 --diff {{pad/naar/bestand.py}}`
```

2021-03-30 16:35 UTC, bl-ue commented on pages.nl/common/autopep8.md
> +`autopep8 --in-place {{pad/naar/bestand}}`
```suggestion
`autopep8 --in-place {{pad/naar/bestand.py}}`
```

2021-03-31 10:10 UTC, Waples commented
@bl-ue changes made.

2021-03-31 10:39 UTC, navarroaxel approved these changes

2021-03-31 14:24 UTC, bl-ue commented
@Waples thank you.  [Here](https://github.com/tldr-pages/tldr/pull/5645#discussion_r604255392) however, I updated the page description, and in d3970373d3ee077ed840236a3f44d75d2f2b9a53 I don't see an update to the nl one—can you update that real quick as well?

2021-04-01 07:44 UTC, Waples commented
@bl-ue change made

2021-04-01 12:30 UTC, bl-ue commented on pages.nl/common/autopep8.md
> +`autopep8 {{pad/naar/bestand.py}} --max-line-length {{len}}`
```suggestion
`autopep8 {{pad/naar/bestand.py}} --max-line-length {{lengte}}`
```

2021-04-02 18:26 UTC, Waples commented
nittpicker :p @bl-ue changes made

2021-04-02 18:31 UTC, bl-ue approved these changes
Thank you @Waples!

2021-04-02 18:31 UTC, merged