runit, runsv, runsvdir, runsvchdir, sv: add more information link and move to common/
tldr-pages/tldr pull request #5648
Opened 2021-03-30 21:04 UTC by marchersimon

For #5510

2021-03-30 21:18 UTC, marchersimon commented
Actually there are some other pages in the runit bundle, which are in the wrong directory. Should I add them here?

2021-03-30 21:22 UTC, bl-ue commented
Sure, just add their names to the PR title e.g. `runit, page1, page: ...`

2021-03-30 21:48 UTC, marchersimon commented
Just found some more

2021-03-30 21:50 UTC, bl-ue commented
Well, changes like this are what keep the older parts of tldr-pages from decaying and crumbling away.  It's always good to refresh all the pages every once in a while 👍🏻

2021-03-30 21:52 UTC, bl-ue requested changes
Remove `/en` i18n

2021-03-30 21:52 UTC, bl-ue commented on pages.zh/common/runsvchdir.md
> +> 更多信息： <https://manpages.ubuntu.com/manpages/latest/en/man8/runsvchdir.8.html>.
```suggestion
> 更多信息： <https://manpages.ubuntu.com/manpages/latest/man8/runsvchdir.8.html>.
```

2021-03-30 21:52 UTC, bl-ue commented on pages/common/runsvchdir.md
> +> More information: <https://manpages.ubuntu.com/manpages/latest/en/man8/runsvchdir.8.html>.
```suggestion
> More information: <https://manpages.ubuntu.com/manpages/latest/man8/runsvchdir.8.html>.
```

2021-03-30 21:52 UTC, bl-ue commented on pages.zh/common/runsvdir.md
> +> 更多信息： <https://manpages.ubuntu.com/manpages/latest/en/man8/runsvdir.8.html>.
```suggestion
> 更多信息： <https://manpages.ubuntu.com/manpages/latest/man8/runsvdir.8.html>.
```

2021-03-30 21:52 UTC, bl-ue commented on pages/common/runsvdir.md
> +> More information: <https://manpages.ubuntu.com/manpages/latest/en/man8/runsvdir.8.html>.
```suggestion
> More information: <https://manpages.ubuntu.com/manpages/latest/man8/runsvdir.8.html>.
```

2021-03-30 21:52 UTC, marchersimon commented
Well, after that PR, I have successfully eliminated over 50% of all sunos pages :sweat_smile:

2021-03-30 21:54 UTC, marchersimon commented
What sould we do about [pages.zh/sunos/sv.md](https://github.com/tldr-pages/tldr/blob/master/pages.zh/sunos/sv.md) and [pages.zh/osx/sv.md](https://github.com/tldr-pages/tldr/blob/master/pages.zh/osx/sv.md)?

2021-03-30 21:55 UTC, bl-ue commented
If you eliminate all of them, we can remove the whole platform, and then re-add it some time as `solaris` 🤓

2021-03-30 21:58 UTC, marchersimon commented
> If you eliminate all of them, we can remove the whole platform, and then re-add it some time as `solaris` nerd_face

There would be only 4 pages left in sunos and I don't think there'll be new ones

2021-03-30 22:01 UTC, bl-ue commented
>What sould we do about [pages.zh/sunos/sv.md](https://github.com/tldr-pages/tldr/blob/master/pages.zh/sunos/sv.md) and [pages.zh/osx/sv.md](https://github.com/tldr-pages/tldr/blob/master/pages.zh/osx/sv.md)?

Discard the latter. The former is more recent ([Oct 2020](https://github.com/tldr-pages/tldr/pull/4389) vs. [March 2019](https://github.com/tldr-pages/tldr/pull/2831)) and it's slightly more accurate (the variables in the latter are e.g. `target directory/target service` vs. `directory/service` etc.)

2021-03-30 22:01 UTC, bl-ue commented
>There would be only 4 pages left in sunos and I don't think there'll be new ones

Maybe we could figure out that they are usable on Linux and move them there (or common/)

2021-03-30 22:16 UTC, bl-ue approved these changes
Love these big cleanup PRs! 🤺

2021-03-31 10:52 UTC, navarroaxel approved these changes

2021-03-31 10:52 UTC, merged