sunos/*: add morre information link
tldr-pages/tldr pull request #5649
Opened 2021-03-30 22:29 UTC by marchersimon

For #5510

2021-03-30 22:32 UTC, marchersimon commented
According to the urls `svcadm`, `svccfg`, `svcs` and `truss` are linux commands the rest is sunos only.

2021-03-30 22:33 UTC, sbrl approved these changes
Thanks, @marchersimon!

2021-03-30 22:34 UTC, sbrl commented
> According to the urls `svcadm`, `svccfg`, `svcs` and `truss` are linux commands the rest is sunos only.

The copies in `sunos` are probably implemented slightly differently to the `linux` versions then I guess?

2021-03-30 22:39 UTC, marchersimon commented
At least the man pages are the same. Is this reason enough to move them to common?

2021-03-30 23:42 UTC, bl-ue commented
Seems like it to me. @sbrl?

2021-03-31 10:42 UTC, navarroaxel requested changes

2021-03-31 10:42 UTC, navarroaxel commented on pages.zh/sunos/dmesg.md
> +> 更多信息： <https://www.unix.com/man-page/sunos/1m/dmesg/>.
```suggestion
> 更多信息： <https://www.unix.com/man-page/sunos/1m/dmesg>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/devfsadm.md
> +> More information: <https://www.unix.com/man-page/sunos/1m/devfsadm/>.
```suggestion
> More information: <https://www.unix.com/man-page/sunos/1m/devfsadm>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/dmesg.md
> +> More information: <https://www.unix.com/man-page/sunos/1m/dmesg/>.
```suggestion
> More information: <https://www.unix.com/man-page/sunos/1m/dmesg>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/prctl.md
> +> More information: <https://www.unix.com/man-page/sunos/1/prctl/>.
```suggestion
> More information: <https://www.unix.com/man-page/sunos/1/prctl>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/prstat.md
> +> More information: <https://www.unix.com/man-page/sunos/1m/prstat/>.
```suggestion
> More information: <https://www.unix.com/man-page/sunos/1m/prstat>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/svcadm.md
> +> More information: <https://www.unix.com/man-page/linux/1m/svcadm/>.
```suggestion
> More information: <https://www.unix.com/man-page/linux/1m/svcadm>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/snoop.md
> +> More information: <https://www.unix.com/man-page/sunos/1m/snoop/>.
```suggestion
> More information: <https://www.unix.com/man-page/sunos/1m/snoop>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/svccfg.md
> +> More information: <https://www.unix.com/man-page/linux/1m/svccfg/>.
```suggestion
> More information: <https://www.unix.com/man-page/linux/1m/svccfg>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/svcs.md
> +> More information: <https://www.unix.com/man-page/linux/1/svcs/>.
```suggestion
> More information: <https://www.unix.com/man-page/linux/1/svcs>.
```

2021-03-31 10:42 UTC, navarroaxel commented on pages/sunos/truss.md
> +> More information: <https://www.unix.com/man-page/linux/1/truss/>.
```suggestion
> More information: <https://www.unix.com/man-page/linux/1/truss>.
```

2021-03-31 11:08 UTC, navarroaxel approved these changes

2021-03-31 11:09 UTC, merged