ip-neighbour: add page
tldr-pages/tldr pull request #5697
Opened 2021-04-06 13:05 UTC by patricedenis

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-04-07 00:14 UTC, schneiderl approved these changes

2021-04-07 02:24 UTC, bl-ue commented
@patricedenis will you please use the manned.org link here?

2021-04-07 10:00 UTC, marchersimon requested changes

2021-04-07 10:00 UTC, marchersimon commented on pages/linux/ip-neighbour.md
> +`sudo ip neighbour change/replace {{ip_address}} lladdr {{new_mac_address}} dev {{eth0}}`
```suggestion
`sudo ip neighbour {{change|replace}} {{ip_address}} lladdr {{new_mac_address}} dev {{eth0}}`
```

2021-04-07 12:11 UTC, bl-ue commented on pages/linux/ip-neighbour.md
> +`sudo ip neigh flush dev {{eth0}}`
What about `neighbor` (the American spelling)?  It it supported as well?

2021-04-07 12:11 UTC, bl-ue commented on pages/linux/ip-neighbour.md
> +- Add/Delete an ARP entry for the neighbour {{ip_address}} to eth0:
Let's do uppercase IP instead of lowercase, and put `eth0` in backticks, @marchersimon.

2021-04-07 12:15 UTC, bl-ue commented on pages/linux/ip-neighbour.md
> +`sudo ip neighbour add/del {{ip_address}} lladdr {{mac_address}} dev {{eth0}} nud reachable`
Yeah, @patricedenis we have a particular syntax just for indicating that multiple stated options are allowed.

2021-04-07 13:14 UTC, marchersimon commented on pages/linux/ip-neighbour.md
> +`sudo ip neigh flush dev {{eth0}}`
Indeed. Should we change it?

2021-04-07 13:17 UTC, bl-ue commented on pages/linux/ip-neighbour.md
> +`sudo ip neigh flush dev {{eth0}}`
I would, #5221

2021-04-07 14:00 UTC, patricedenis commented on pages/linux/ip-neighbour.md
> +`sudo ip neigh flush dev {{eth0}}`
Okay. Shoud I rename the file as well : ip-neighbour.md to ip-neighbor.md?

2021-04-07 14:02 UTC, patricedenis commented on pages/linux/ip-neighbour.md
> +`sudo ip neighbour add/del {{ip_address}} lladdr {{mac_address}} dev {{eth0}} nud reachable`
I see it now ^^ thanks

2021-04-07 14:02 UTC, bl-ue commented
@patricedenis: _after we've applied all of the suggestions_, let's rename this this page, the PR, and the commands from `neighbour` (British spelling) to `neighbor` (American spelling) because the command supports this and we tend to prefer American spelling because it's more standard, see #5221.

2021-04-07 14:04 UTC, patricedenis commented
> @patricedenis: _after we've applied all of the suggestions_, let's rename this this page, the PR, and the commands from `neighbour` (British spelling) to `neighbor` (American spelling) because the command supports this and we tend to prefer American spelling because it's more standard, see #5221.

All right, that what I just ask before so I will do it as well.

2021-04-07 14:06 UTC, patricedenis commented
I think I will commit all the suggestions and after that I will rebase the whole to have a clean "add page PR". It is better as I understood, am I right?

2021-04-07 15:01 UTC, bl-ue commented
>I think I will commit all the suggestions and after that I will rebase the whole to have a clean "add page PR". It is better as I understood, am I right?

Really, it doesn't matter at all.  Since we squash all of the commits into one just before merging, it will end up as one clean commit whether you yourself make a clean commit or messy commits.  I recommend taking it easy and just committing as necessary, not bothering to rebase, because you can.

2021-04-07 15:05 UTC, patricedenis commented
I tried to rename the branch and it closed the PR, is that normal?


@bl-ue 
> Really, it doesn't matter at all. Since we squash all of the commits into one just before merging, it will end up as one clean commit whether you yourself make a clean commit or messy commits. I recommend taking it easy and just committing as necessary, not bothering to rebase, because you can.

All right.
Thanks again

2021-04-07 15:21 UTC, marchersimon approved these changes

2021-04-07 16:06 UTC, bl-ue commented
>I tried to rename the branch and it closed the PR, is that normal?

I see, I'm not sure if you can do that; at any rate, this is a temporary branch and so the name matters little.  You could even call it `asdf1234` and it wouldn't matter 😉

2021-04-07 16:15 UTC, bl-ue commented
Now wait, it looks like maybe `neighbour` (british) is correct!! Because there's no man page for `ip-neighbor`, just one for `ip-neighbour`

Maybe you should actually revert and go back to the British spelling... 🙂

2021-04-07 16:17 UTC, marchersimon commented
@bl-ue I forgot to check that too, sorry. I just looked if `ip neighbor` worked - which it does.

2021-04-08 08:01 UTC, patricedenis commented
I think @bl-ue is right because I couldn't find any `ip neighbor` page neither on my local man pages nor on the Web (manned.org, man7.org, ...).

Should we add a note to enlighten that `ip neighbor` is OK to use as well?

2021-04-08 13:03 UTC, bl-ue commented
I don't really think so; they're so similar that pointing that might just be distracting.

2021-04-08 13:04 UTC, bl-ue approved these changes
Thank you, @patricedenis!

2021-04-08 13:04 UTC, merged