apt-tools: add more info links and update apt-file
tldr-pages/tldr pull request #5710
Opened 2021-04-08 14:20 UTC by patricedenis

- [ ] The page (if new), does not already exist in the repo.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-04-08 14:23 UTC, patricedenis commented
#5510

2021-04-08 14:25 UTC, patricedenis commented
I placed manned.org links as I understood we do now in #5143. Or I am supposed to link to the official Debian latest man pages?

2021-04-08 14:26 UTC, patricedenis commented
For the deprecation of the usage of apt-key, see:

- [](https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html)

- [](https://wiki.debian.org/DebianRepository/UseThirdParty)

2021-04-08 14:58 UTC, bl-ue commented on pages/linux/apt-file.md
> +`apt-file {search|find} {{part/of/filename}}`
```suggestion
`apt-file {{search|find}} {{part/of/filename}}`
```

2021-04-08 14:58 UTC, bl-ue commented on pages/linux/apt-file.md
> +`apt-file {show|list} {{package_name}}`
```suggestion
`apt-file {{show|list}} {{package_name}}`
```

2021-04-08 14:58 UTC, bl-ue commented on pages/linux/apt-file.md
> +`apt-file {search|find} --regexp {{pattern}}
```suggestion
`apt-file {{search|find}} --regexp {{pattern}}
```

2021-04-08 14:58 UTC, bl-ue commented on pages/linux/apt-key.md
> +> in maintainer scripts to remove existing keys from the main keyring.
```suggestion
> Note: `apt-key` is now deprecated (except for the use of `apt-key del` in maintainer scripts).
```

2021-04-08 14:58 UTC, bl-ue commented on pages/linux/apt-key.md
> +> Be carefull as `apt-key` is now deprecated except for the use of `apt-key del` in maintainer scripts to remove existing keys from the main keyring.
```suggestion
> Note: `apt-key` is now deprecated (except for the use of `apt-key del`).
```

2021-04-08 15:03 UTC, bl-ue commented
@patricedenis will you please also update the translations with this info (at least the links)?  Feel free to [`set-more-info-link.py`](https://github.com/tldr-pages/tldr/blob/ce4846141a0950fb05d467dd6849a311574c06e0/scripts/set-more-info-link.py) for that.  Usage:
```
python3 set-more-info-link.py -p platform/page.md "https://new.link"
# e.g.
python3 set-more-info-link.py -p linux/apt.md "https://manned.org/apt.8"
```
The nice thing about it as that it will add the link to all of the translations of the page, in the [page's language](https://github.com/tldr-pages/tldr/blob/ce4846141a0950fb05d467dd6849a311574c06e0/scripts/set-more-info-link.py#L8-L33).

2021-04-08 15:10 UTC, patricedenis commented
oh great !

2021-04-08 16:13 UTC, patricedenis commented
I'm not sure for my history of commit cause I made some commits from Web interface and pull them after that to local git structure which did not catch them as single one but as a whole merge commit. So I split them up after that but the original commit hashes are lost even if I have rewritten the content. 
I'm not sure I clear as well here ^^.

2021-04-08 17:08 UTC, bl-ue commented
No problem @patricedenis, it really doesn't matter what the commits look like as long as the files look the way we want them to in the end.

2021-04-08 17:10 UTC, bl-ue commented on pages/linux/apt-key.md
> +> Note: `apt-key` is now deprecated (except for the use of `apt-key del`).
I had an old suggestion that suggested this, it it got erased and then I made a new one but forgot to add this:
```suggestion
> Note: `apt-key` is now deprecated (except for the use of `apt-key del` in maintainer scripts).
```

2021-04-08 17:12 UTC, bl-ue commented
I'll like this PR in #5510

2021-04-08 17:19 UTC, bl-ue commented
@patricedenis will you please also add the link to [`apt-mark.md`](https://github.com/tldr-pages/tldr/blob/ce4846141a0950fb05d467dd6849a311574c06e0/pages/linux/apt-mark.md)?

2021-04-08 20:57 UTC, patricedenis commented
> I'll link this PR in #5510

done it already in the first comment ^^

2021-04-08 21:05 UTC, patricedenis commented
done, I forgot it thanks!

2021-04-08 21:14 UTC, bl-ue approved these changes
Nice good batch of links, thank you @patricedenis.

2021-04-09 03:08 UTC, navarroaxel approved these changes

2021-04-11 14:57 UTC, sbrl reviewed
Awesome work! Thanks so much for this.

Considering that `apt` is a debian-specific command though, wouldn't The Debian man pages be preferable here? e.g. <https://manpages.debian.org/apt/apt-mark.8.en.html>.

2021-04-11 15:45 UTC, patricedenis commented
I'm OK with that. I just did'nt get where do we need to apply the manned.org links.
When we have some distribution specific command we ink to the distribution official man pages?

2021-04-11 16:00 UTC, patricedenis commented
In that case, I should update all the links to the Debian man pages, I checked they're all included.
What do you think?

2021-04-14 12:07 UTC, navarroaxel requested changes

2021-04-14 12:07 UTC, navarroaxel commented on pages.es/linux/apt.md
> +> Más información: <https://manpages.debian.org/latest/apt/apt.8.en.html>.
```suggestion
> Más información: <https://manpages.debian.org/latest/apt/apt.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.it/linux/apt-mark.md
> +> Maggiori informazioni: <https://manpages.debian.org/latest/apt/apt-mark.8.en.html>.
```suggestion
> Maggiori informazioni: <https://manpages.debian.org/latest/apt/apt-mark.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.pt_BR/linux/apt-cache.md
> +> Mais informações: <https://manpages.debian.org/latest/apt/apt-cache.8.en.html>.
```suggestion
> Mais informações: <https://manpages.debian.org/latest/apt/apt-cache.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.pt_BR/linux/apt-file.md
> +> Mais informações: <https://manpages.debian.org/latest/apt-file/apt-file.1.en.html>.
```suggestion
> Mais informações: <https://manpages.debian.org/latest/apt-file/apt-file.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.pt_BR/linux/apt-get.md
> +> Mais informações: <https://manpages.debian.org/latest/apt/apt-get.8.en.html>.
```suggestion
> Mais informações: <https://manpages.debian.org/latest/apt/apt-get.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.pt_BR/linux/apt-key.md
> +> Mais informações: <https://manpages.debian.org/latest/apt/apt-key.8.en.html>.
```suggestion
> Mais informações: <https://manpages.debian.org/latest/apt/apt-key.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.pt_BR/linux/apt-mark.md
> +> Mais informações: <https://manpages.debian.org/latest/apt/apt-mark.8.en.html>.
```suggestion
> Mais informações: <https://manpages.debian.org/latest/apt/apt-mark.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.pt_BR/linux/apt.md
> +> Mais informações: <https://manpages.debian.org/latest/apt/apt.8.en.html>.
```suggestion
> Mais informações: <https://manpages.debian.org/latest/apt/apt.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.pt_BR/linux/aptitude.md
> +> Mais informações: <https://manpages.debian.org/latest/aptitude/aptitude.8.en.html>.
```suggestion
> Mais informações: <https://manpages.debian.org/latest/aptitude/aptitude.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.tr/linux/apt-get.md
> +> Daha fazla bilgi için: <https://manpages.debian.org/latest/apt/apt-get.8.en.html>.
```suggestion
> Daha fazla bilgi için: <https://manpages.debian.org/latest/apt/apt-get.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.tr/linux/aptitude.md
> +> Daha fazla bilgi için: <https://manpages.debian.org/latest/aptitude/aptitude.8.en.html>.
```suggestion
> Daha fazla bilgi için: <https://manpages.debian.org/latest/aptitude/aptitude.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.zh/linux/apt-file.md
> +> 更多信息： <https://manpages.debian.org/latest/apt-file/apt-file.1.en.html>.
```suggestion
> 更多信息： <https://manpages.debian.org/latest/apt-file/apt-file.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.zh/linux/apt-cache.md
> +> 更多信息： <https://manpages.debian.org/latest/apt/apt-cache.8.en.html>.
```suggestion
> 更多信息： <https://manpages.debian.org/latest/apt/apt-cache.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.zh/linux/apt-get.md
> +> 更多信息： <https://manpages.debian.org/latest/apt/apt-get.8.en.html>.
```suggestion
> 更多信息： <https://manpages.debian.org/latest/apt/apt-get.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.zh/linux/apt-key.md
> +> 更多信息： <https://manpages.debian.org/latest/apt/apt-key.8.en.html>.
```suggestion
> 更多信息： <https://manpages.debian.org/latest/apt/apt-key.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.zh/linux/apt-mark.md
> +> 更多信息： <https://manpages.debian.org/latest/apt/apt-mark.8.en.html>.
```suggestion
> 更多信息： <https://manpages.debian.org/latest/apt/apt-mark.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.zh/linux/apt.md
> +> 更多信息： <https://manpages.debian.org/latest/apt/apt.8.en.html>.
```suggestion
> 更多信息： <https://manpages.debian.org/latest/apt/apt.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages.zh/linux/aptitude.md
> +> 更多信息： <https://manpages.debian.org/latest/aptitude/aptitude.8.en.html>.
```suggestion
> 更多信息： <https://manpages.debian.org/latest/aptitude/aptitude.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages/linux/apt-add-repository.md
> +> More information: <https://manpages.debian.org/latest/software-properties-common/apt-add-repository.1.en.html>.
```suggestion
> More information: <https://manpages.debian.org/latest/software-properties-common/apt-add-repository.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages/linux/apt-get.md
> +> More information: <https://manpages.debian.org/latest/apt/apt-get.8.en.html>.
```suggestion
> More information: <https://manpages.debian.org/latest/apt/apt-get.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages/linux/apt-key.md
> +> More information: <https://manpages.debian.org/latest/apt/apt-key.8.en.html>.
```suggestion
> More information: <https://manpages.debian.org/latest/apt/apt-key.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages/linux/apt-mark.md
> +> More information: <https://manpages.debian.org/latest/apt/apt-mark.8.en.html>.
```suggestion
> More information: <https://manpages.debian.org/latest/apt/apt-mark.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages/linux/apt.md
> +> More information: <https://manpages.debian.org/latest/apt/apt.8.en.html>.
```suggestion
> More information: <https://manpages.debian.org/latest/apt/apt.html>.
```

2021-04-14 12:07 UTC, navarroaxel commented on pages/linux/aptitude.md
> +> More information: <https://manpages.debian.org/latest/aptitude/aptitude.8.en.html>.
```suggestion
> More information: <https://manpages.debian.org/latest/aptitude/aptitude.html>.
```

2021-04-15 23:36 UTC, sbrl commented on pages.es/linux/apt-add-repository.md
> +> Más información: <https://manpages.debian.org/latest/software-properties-common/apt-add-repository.1.en.html>.
```suggestion
> Más información: <https://manpages.debian.org/latest/software-properties-common/apt-add-repository.1.html>.
```

2021-04-15 23:36 UTC, sbrl commented on pages.de/linux/apt-add-repository.md
> +> Mehr Informationen: <https://manpages.debian.org/latest/software-properties-common/apt-add-repository.1.en.html>.
```suggestion
> Mehr Informationen: <https://manpages.debian.org/latest/software-properties-common/apt-add-repository.1.html>.
```

2021-04-15 23:37 UTC, sbrl commented on pages.de/linux/apt-get.md
> +> Mehr Informationen: <https://manpages.debian.org/latest/apt/apt-get.8.en.html>.
```suggestion
> Mehr Informationen: <https://manpages.debian.org/latest/apt/apt-get.8.html>.
```

2021-04-15 23:37 UTC, sbrl commented on pages.de/linux/apt.md
> +> Mehr Informationen: <https://manpages.debian.org/latest/apt/apt.8.en.html>.
```suggestion
> Mehr Informationen: <https://manpages.debian.org/latest/apt/apt.8.html>.
```

2021-04-15 23:37 UTC, sbrl commented on pages.es/linux/apt-cache.md
> +> Más información: <https://manpages.debian.org/latest/apt/apt-cache.8.en.html>.
```suggestion
> Más información: <https://manpages.debian.org/latest/apt/apt-cache.8.html>.
```

2021-04-15 23:37 UTC, sbrl commented on pages.es/linux/apt-file.md
> +> Más información: <https://manpages.debian.org/latest/apt-file/apt-file.1.en.html>.
```suggestion
> Más información: <https://manpages.debian.org/latest/apt-file/apt-file.1.html>.
```

2021-04-15 23:45 UTC, sbrl commented
Haha wow @navarroaxel, that was a lot of comments? Perhaps next time in this instance it might have been better and less overwhelming to leave 1 generic comment?

@patricedenis: I've taken the liberty of making the more information links you've added language-agnostic, if that's ok?

For future reference, the find-in-files feature of GitHub's Atom works splendidly for this.

2021-04-15 23:45 UTC, sbrl approved these changes

2021-04-17 08:04 UTC, patricedenis commented
@sbrl no problemo, thanks !

> For future reference, the find-in-files feature of GitHub's Atom works splendidly for this.

OK, I didn't know the function. I will try it next time. thanks again !

And a big thank you as well to @navarroaxel for the complete review !

2021-04-17 13:25 UTC, navarroaxel approved these changes

2021-04-17 13:26 UTC, merged