debuild: add Chinese translation
tldr-pages/tldr pull request #5801
Opened 2021-04-21 02:44 UTC by sandylaw

Description: add debuild pages in pages.zh/linux.
- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).
@ChungZH @KsRyY @whriedplanck

2021-04-21 14:17 UTC, bl-ue requested changes

2021-04-21 14:17 UTC, bl-ue commented on pages.zh/linux/debuild.md
> +> 更多信息： <https://manpages.debian.org/debuild>。
```suggestion
> 更多信息：<https://manpages.debian.org/debuild>。
```

2021-04-21 14:17 UTC, bl-ue commented on pages.zh/linux/debuild.md
> +> 从源代码构建`Debian`软件包的工具。
```suggestion
> 从源代码构建 `Debian` 软件包的工具。
```

2021-04-21 14:17 UTC, bl-ue commented on pages.zh/linux/debuild.md
> +- 生成软件包后，不运行`lintian`（检查常见打包错误）：
```suggestion
- 生成软件包后，不运行 `lintian`（检查常见打包错误）：
```

2021-04-22 01:33 UTC, bl-ue commented on pages.zh/linux/debuild.md
> +> 更多信息：<https://manpages.debian.org/debuild>。
```suggestion
> 更多信息：<https://manpages.debian.org/debuild>.
```

2021-04-22 20:04 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me after @bl-ue's comments are addressed.

Thanks :slightly_smiling_face:

2021-04-24 12:28 UTC, navarroaxel approved these changes

2021-04-24 13:14 UTC, bl-ue approved these changes

2021-04-24 13:14 UTC, merged