rolldice: add page
tldr-pages/tldr pull request #5811
Opened 2021-04-21 21:41 UTC by vappolinario

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-04-21 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5811) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=5811) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=5811) it.</sub>

2021-04-21 21:53 UTC, bl-ue requested changes
Cool @vappolinario.

Will you please add a "More information" link?  If you can't find any good official link, you can use https://manned.org/rolldice.  Here's an example: [`pages/common/goimports.md`](https://github.com/tldr-pages/tldr/blob/06bcfd34f08f89bf7562a570320f25e0678622e7/pages/common/goimports.md)

2021-04-21 22:32 UTC, vappolinario commented
@bl-ue I found the command's github repo but the man page you linked seems more complete, which should i use?

2021-04-22 06:44 UTC, marchersimon commented
@vappolinario in this case I'd say we should prefer <manned.org/rolldice>.

2021-04-22 06:53 UTC, marchersimon requested changes

2021-04-22 06:53 UTC, marchersimon commented on pages/linux/rolldice.md
> +- Roll a single 20 sided die:
```suggestion
- Roll a single 20 sided dice:
```
As far as I know, `dice` is more common than `die`.

2021-04-22 06:53 UTC, marchersimon commented on pages/linux/rolldice.md
> +`rolldice d20`
```suggestion
`rolldice d{{20}}`
```
We keep any variables in `{{ }}`

2021-04-22 06:53 UTC, marchersimon commented on pages/linux/rolldice.md
> +`rolldice 2d6s1`
```suggestion
`rolldice {{2}}d{{6}}s{{1}}`
```

2021-04-22 06:53 UTC, marchersimon commented on pages/linux/rolldice.md
> +`rolldice 2d20+5`
```suggestion
`rolldice {{2}}d{{20}}{{+5}}`
```

2021-04-22 06:53 UTC, marchersimon commented on pages/linux/rolldice.md
> +- Roll two six sided dice and keep the highest roll:
```suggestion
- Roll two six sided dice and drop the lowest roll:
```
I think that explains better what `s1` does.

2021-04-22 12:58 UTC, bl-ue commented
>@bl-ue I found the command's github repo but the man page you linked seems more complete, which should i use?
>
>https://github.com/sstrickl/rolldice

Personally, I like the GitHub repository because the first thing I want to know when I see a new command is the source/homepage of it.  But since this is old tool circa 1999 I think the man page is fine.

2021-04-22 13:47 UTC, marchersimon commented on pages/linux/rolldice.md
> +- Roll a d20 two times:
```suggestion
- Roll a 20 sided dice two times:
```

2021-04-22 15:49 UTC, marchersimon approved these changes

2021-04-22 17:16 UTC, bl-ue approved these changes

2021-04-22 20:17 UTC, sbrl approved these changes
Looks fine to me! Thanks, @vappolinario :smiley_cat: 

In terms of the more info link, normally we would prefer to link to the GH repo, but in this case the GH repo has a very..... brief README, so the man page is preferable in this instance.

2021-04-22 20:17 UTC, merged