histexpand, history: add Spanish translation
tldr-pages/tldr pull request #5825
Opened 2021-04-23 17:16 UTC by Nacho-source

- [ ] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-04-23 17:19 UTC, navarroaxel approved these changes

2021-04-23 17:29 UTC, bl-ue requested changes

2021-04-23 17:29 UTC, bl-ue commented on pages.es/common/history.md
> +> Más información: <https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html#Bash-History-Builtins>.
This link can be shortened a bit:
```suggestion
> Más información: <https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html>.
```

2021-04-23 17:29 UTC, bl-ue commented on pages/common/history.md
> +> More information: <https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html#Bash-History-Builtins>.
```suggestion
> More information: <https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html>.
```

2021-04-23 18:19 UTC, marchersimon approved these changes

2021-04-24 02:14 UTC, bl-ue approved these changes

2021-04-24 02:14 UTC, merged

2021-04-24 02:14 UTC, bl-ue commented
Thank you for this and your other PRs, @Nacho-source!