chrony, ntpq: add page
tldr-pages/tldr pull request #5828
Opened 2021-04-24 18:35 UTC by RH-sdavey

- [X] The page (if new), does not already exist in the repo.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines).

2021-04-24 18:59 UTC, bl-ue requested changes
Thank you for the new pages @RH-sdavey!  Will you please add links to them? https://manned.org/chronyc and https://manned.org/ntpq will work well if you can't find anything more canonical.

2021-04-24 18:59 UTC, bl-ue commented on pages/linux/chronyc.md
> +> Query Chrony (NTP) daemon.
```suggestion
> Query the Chrony NTP daemon.
```

2021-04-24 18:59 UTC, bl-ue commented on pages/linux/chronyc.md
> +- Use chronyc in interactive mode:
```suggestion
- Start chronyc in interactive mode:
```

2021-04-24 18:59 UTC, bl-ue commented on pages/linux/chronyc.md
> +- Display tracking stats for chrony daemon:
```suggestion
- Display tracking stats for the Chrony daemon:
```

2021-04-24 18:59 UTC, bl-ue commented on pages/linux/chronyc.md
> +- Print time sources chrony is currently using as a time source:
```suggestion
- Print the time sources that Chrony is currently using as a time source:
```

2021-04-24 18:59 UTC, bl-ue commented on pages/linux/ntpq.md
> +> Query Network Time Protocol (NTP) daemon.
```suggestion
> Query the Network Time Protocol (NTP) daemon.
```

2021-04-24 18:59 UTC, bl-ue commented on pages/linux/ntpq.md
> +- Use ntpq in interactive mode:
```suggestion
- Start ntpq in interactive mode:
```

2021-04-25 08:55 UTC, marchersimon requested changes

2021-04-25 08:55 UTC, marchersimon commented on pages/linux/chronyc.md
> +
```suggestion
More information: <https://chrony.tuxfamily.org/doc/4.0/chronyc.html>.

```

2021-04-25 08:55 UTC, marchersimon commented on pages/linux/ntpq.md
> +
```suggestion
More information: <https://www.eecis.udel.edu/~mills/ntp/html/ntpq.html>.

```

2021-04-25 08:55 UTC, marchersimon commented on pages/linux/ntpq.md
> +`ntpq -i`
```suggestion
`ntpq --interactive`
```
For reference: the long options are neither listed in the official man page, nor by `ntpq --help`, but they are in <https://manned.org/ntpq> and they do work

2021-04-25 08:55 UTC, marchersimon commented on pages/linux/ntpq.md
> +`ntpq -p`
```suggestion
`ntpq --peers`
```

2021-04-25 08:55 UTC, marchersimon commented on pages/linux/ntpq.md
> +`ntpq -np`
```suggestion
`ntpq --numeric --peers`
```

2021-04-25 08:55 UTC, marchersimon commented on pages/linux/ntpq.md
> +`ntpq -d`
```suggestion
`ntpq --debug-level`
```

2021-04-25 08:55 UTC, marchersimon commented on pages/linux/ntpq.md
> +`ntpq -c rv`
```suggestion
`ntpq --command={{rv}}`
```

2021-04-25 13:39 UTC, bl-ue commented
Whoa, that's a lot of errors.  Let me minimize those...

2021-04-25 14:00 UTC, bl-ue approved these changes

2021-04-25 16:07 UTC, marchersimon commented on pages/linux/ntpq.md
> +- Print list of ntp peers:
```suggestion
- Print a list of ntp peers:
```
@bl-ue should we use ``` `ntp` ``` or `NTP` here?

2021-04-25 16:07 UTC, marchersimon commented on pages/linux/ntpq.md
> +- Print list of ntp peers without resolving hostnames from IP addresses:
```suggestion
- Print a list of ntp peers without resolving hostnames from IP addresses:
```

2021-04-25 16:11 UTC, bl-ue commented on pages/linux/ntpq.md
> +- Print list of ntp peers:
Probably the latter, `NTP`.

2021-04-25 16:15 UTC, marchersimon commented on pages/linux/chronyc.md
> +- Display verbose information about each ntp source:
```suggestion
- Display verbose information about each NTP source:
```

2021-04-25 16:15 UTC, marchersimon commented on pages/linux/ntpq.md
> +- Start ntpq in interactive mode:
```suggestion
- Start `ntpq` in interactive mode:
```

2021-04-25 16:15 UTC, marchersimon commented on pages/linux/ntpq.md
> +- Use ntpq in debugging mode:
```suggestion
- Use `ntpq` in debugging mode:
```

2021-04-25 16:15 UTC, marchersimon commented on pages/linux/ntpq.md
> +- Print ntp system variables values:
```suggestion
- Print NTP system variables values:
```

2021-04-25 16:35 UTC, marchersimon approved these changes

2021-04-25 16:41 UTC, navarroaxel approved these changes

2021-04-25 16:47 UTC, bl-ue approved these changes

2021-04-25 16:47 UTC, merged