dumpsys: add Chinese translation
tldr-pages/tldr pull request #6024
Opened 2021-05-23 09:00 UTC by BillLucky

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-05-23 11:36 UTC, bl-ue requested changes

2021-05-23 11:36 UTC, bl-ue commented on pages.zh/android/dumpsys.md
> +- 指定超时时间，以秒为单位（默认为10s）：
Missing space?
```suggestion
- 指定超时时间，以秒为单位（默认为 10s）：
```

2021-05-23 11:36 UTC, bl-ue commented on pages.zh/android/dumpsys.md
> +- 列出 `dumpsys`可以提供的所有服务信息：
```suggestion
- 列出 `dumpsys` 可以提供的所有服务信息：
```

2021-05-23 13:37 UTC, bl-ue approved these changes

2021-05-23 13:47 UTC, marchersimon approved these changes

2021-05-23 13:57 UTC, navarroaxel commented on pages.zh/android/dumpsys.md
> +`dumpsys {{service}}`
You can translate the argument option to help non-English speakers.

2021-05-23 14:00 UTC, marchersimon commented on pages.zh/android/dumpsys.md
> +`dumpsys {{service}}`
Should we maybe make a general rule if placeholders for command arguments should be translated too?

2021-05-23 14:02 UTC, navarroaxel commented on pages.zh/android/dumpsys.md
> +`dumpsys {{service}}`
Yeah, why not? If it's a placeholder it should be translated.

2021-05-23 14:28 UTC, BillLucky commented on pages.zh/android/dumpsys.md
> +`dumpsys {{service}}`
like this: https://github.com/tldr-pages/tldr/pull/6019#discussion_r637554415

And actually the placeholder service has been translated. It is a '服务'. Do we need to highlight it or use backticks to distinguish it?

Thanks for review.  @navarroaxel @marchersimon

2021-05-23 15:37 UTC, marchersimon commented on pages.zh/android/dumpsys.md
> +`dumpsys {{service}}`
I was thinking of this:
```suggestion
`dumpsys {{服务}}`
```

2021-05-25 02:07 UTC, BillLucky reviewed
`service` has been translated @navarroaxel

2021-05-25 02:11 UTC, bl-ue commented on pages.zh/android/dumpsys.md
> +`dumpsys {{service}}`
@BillLucky yes, what @marchersimon suggested is what @navarroaxel is getting at, and what I would think would be the best thing to do.  **But**, you raise an interesting point.  Do most Chinese people have to translate it into English in their minds in order to use it, like you're saying?

2021-05-25 02:28 UTC, navarroaxel commented on pages.zh/android/dumpsys.md
> +`dumpsys {{service}}`
@BillLucky yeah, we do that for translations.

2021-05-25 02:29 UTC, navarroaxel commented
> `service` has been translated @navarroaxel

I don't see new commit/changes :thinking:

2021-05-25 02:29 UTC, navarroaxel commented
> `service` has been translated @navarroaxel

@BillLucky I don't see new commit/changes :thinking:

2021-05-25 05:11 UTC, BillLucky commented
> > `service` has been translated @navarroaxel
> 
> @BillLucky I don't see new commit/changes 🤔

Oh, because `service` is Chinese `服务`  .
the previous translation has already included @navarroaxel

2021-05-25 16:41 UTC, navarroaxel approved these changes

2021-05-25 16:42 UTC, navarroaxel approved these changes

2021-05-25 16:56 UTC, bl-ue approved these changes

2021-05-25 16:56 UTC, merged