caddy: add page
tldr-pages/tldr pull request #6115
Opened 2021-06-11 17:50 UTC by ddgond

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-06-11 17:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6115) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=6115) it.</sub>

2021-06-11 17:53 UTC, bl-ue requested changes
A few grammar suggestions. :)

2021-06-11 17:53 UTC, bl-ue commented on pages/common/caddy.md
> +> A powerful, enterprise-ready, open source web server with automatic HTTPS written in Go.
```suggestion
> A powerful, enterprise-ready, open source web server with automatic HTTPS, written in Go.
```

2021-06-11 17:53 UTC, bl-ue commented on pages/common/caddy.md
> +- Start Caddy with a specified Caddyfile:
```suggestion
- Start Caddy with the specified Caddyfile:
```

2021-06-11 17:53 UTC, bl-ue commented on pages/common/caddy.md
> +- Run a simple file server on a specified port with a browsable interface:
```suggestion
- Run a simple file server on the specified port with a browsable interface:
```

2021-06-11 17:57 UTC, ddgond commented
Thanks for the suggestions! I've also added the trailing newline that was originally missing.

2021-06-11 17:59 UTC, navarroaxel approved these changes

2021-06-11 20:12 UTC, marchersimon requested changes
Just a few syntax related suggestions

2021-06-11 20:12 UTC, marchersimon commented on pages/common/caddy.md
> +`caddy run --config /example/Caddyfile`
```suggestion
`caddy run --config {{path/to/Caddyfile}}`
```
We use this syntax for specifying files.

2021-06-11 20:12 UTC, marchersimon commented on pages/common/caddy.md
> +`caddy file-server --listen :8000 --browse`
```suggestion
`caddy file-server --listen :{{8000}} --browse`
```
We wrap variable options in `{{ }}`, so clients can highlight them.

2021-06-11 20:12 UTC, marchersimon commented on pages/common/caddy.md
> +`caddy reverse-proxy --from :80 --to localhost:8000`
```suggestion
`caddy reverse-proxy --from :{{80}} --to localhost:{{8000}}`
```

2021-06-11 20:24 UTC, bl-ue approved these changes
Looks good modulo @marchersimon's suggestions :)

2021-06-11 20:31 UTC, ddgond commented
Thanks for the quick responses! Should be all set now.

2021-06-11 20:58 UTC, marchersimon approved these changes
Thanks @ddgond

2021-06-11 21:05 UTC, bl-ue commented
>Thanks for the quick responses! Should be all set now.

I'm sorry, I should've been faster — I didn't realize that 3 hours ago I was [requested](https://github.com/tldr-pages/tldr/pull/6115#event-4879417085) for review 😂

2021-06-12 08:16 UTC, mfrw approved these changes

2021-06-12 13:47 UTC, CleanMachine1 approved these changes

2021-06-12 14:01 UTC, merged

2021-06-12 14:01 UTC, bl-ue commented
Welcome to tldr-pages, @ddgond! :)