git-rename-remote: add page
tldr-pages/tldr pull request #6138
Opened 2021-06-17 19:52 UTC by CleanMachine1

- [x] The page (if new), does not already exist in the repo.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

For #5137 

I couldn't find any more use cases for this command, if you can, please suggest them

2021-06-17 20:11 UTC, bl-ue requested changes

2021-06-17 20:11 UTC, bl-ue commented on pages/common/git-rename-remote.md
> +`git rename-remote upstream origin`
```suggestion
`git rename-remote {{upstream}} {{origin}}`
```

2021-06-18 08:23 UTC, owenvoke approved these changes
Nice job, I always forget about all the `git-extras` scripts.

2021-06-18 11:49 UTC, bl-ue approved these changes

2021-06-18 15:24 UTC, navarroaxel approved these changes
There are a `git remote rename` built-in command, I guess this can replace the remote destination instead of get this error:
```
error: remote "name" already exists.
```

2021-06-18 21:39 UTC, merged