convert: add ico convert example
tldr-pages/tldr pull request #6143
Opened 2021-06-19 06:23 UTC by GRA0007

- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

A common command I use a lot, felt it could be useful here

2021-06-19 08:51 UTC, marchersimon requested changes

2021-06-19 08:51 UTC, marchersimon commented on pages/common/convert.md
> +`convert {{image1.png}} {{image2.png}} {{image3.png}} {{image.ico}}
This will fix the error:
```suggestion
`convert {{image1.png}} {{image2.png}} {{image3.png}} {{image.ico}}`
```

2021-06-19 08:51 UTC, marchersimon commented on pages/common/convert.md
> +- Create a favicon from several sized images:
Do you mean "several images with different sizes"?

2021-06-19 08:53 UTC, marchersimon commented
Hey @GRA0007, I changed the base branch to `main`, since we changed our default branch some time ago.

2021-06-19 19:06 UTC, sbrl commented
@marchersimon that could maybe a good check to implement in @tldr-bot to make sure we don't accidentally merge something into `master` :P

2021-06-21 04:23 UTC, GRA0007 commented
Thanks everyone, honestly I just saw a missing bit of info and did everything through the github ui, I'm surprised it tried to merge into master if your branch is called `main`. I'll fix up those issues too :)

2021-06-21 04:57 UTC, navarroaxel approved these changes

2021-06-21 07:22 UTC, marchersimon approved these changes
Thanks @GRA0007

2021-06-21 07:23 UTC, merged