linux/t*: add information link
tldr-pages/tldr pull request #6166
Opened 2021-06-23 20:46 UTC by CleanMachine1

for #6062

2021-06-23 20:47 UTC, CleanMachine1 commented on pages/linux/trap.md
> +> More information: N/A
Need some help with this one

2021-06-23 21:29 UTC, bl-ue requested changes

2021-06-23 21:29 UTC, bl-ue commented on pages/linux/trap.md
> +> More information: N/A.
Why not https://manned.org/trap?
```suggestion
> More information: <https://manned.org/trap>.
```

2021-06-23 22:14 UTC, CleanMachine1 commented on pages/linux/trap.md
> +> More information: N/A.
I cant tell if it is correct or not

2021-06-24 12:26 UTC, bl-ue commented on pages/linux/trap.md
> +> More information: N/A.
Looks like it to me.

2021-06-25 19:47 UTC, sbrl approved these changes
Thanks, @CleanMachine1!

2021-06-27 16:26 UTC, SethFalco approved these changes

2021-06-27 18:06 UTC, marchersimon approved these changes

2021-06-28 22:48 UTC, merged