bash: add traditional Chinese translation
tldr-pages/tldr pull request #6191
Opened 2021-07-03 07:14 UTC by blueskyson

- [ x] The page (if new), does not already exist in the repo.
- [ x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ x] The page has 8 or fewer examples.
- [ x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ x] The page description includes a link to documentation or a homepage (if applicable).

2021-07-04 02:38 UTC, navarroaxel approved these changes

2021-07-05 20:40 UTC, marchersimon requested changes
The colon is missing from the last two examples. I can't make a suggestion, because GitHub alsways converts them to ASCI if I copy them.

2021-07-06 07:12 UTC, blueskyson commented
@marchersimon I forgot to put colons to the last 2 lines. I'll fix it in the next commitment.

2021-07-06 10:35 UTC, marchersimon approved these changes
Thanks @blueskyson

2021-07-06 10:35 UTC, merged