jhat: add Chinese translation
tldr-pages/tldr pull request #6265
Opened 2021-07-26 12:00 UTC by BillLucky

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-07-26 16:55 UTC, marchersimon commented on pages.zh/common/jhat.md
> +- 分析堆转储文件（来自 jmap），通过http端口 7000  进行查看：
```suggestion
- 分析堆转储文件（来自 jmap），通过 http 端口 7000 进行查看：
```

2021-07-26 16:55 UTC, marchersimon commented on pages.zh/common/jhat.md
> +- 通过jhat 分析转储文件，指定使用8GB RAM（建议使用 2-4 倍的转储大小）：
```suggestion
- 通过 jhat 分析转储文件，指定使用 8GB RAM（建议使用 2-4 倍的转储大小）：
```

2021-07-27 08:21 UTC, marchersimon approved these changes
Thanks @BillLucky

2021-07-28 06:06 UTC, blueskyson approved these changes

2021-08-04 12:11 UTC, einverne requested changes
Thank you for translating the page, but according to the [guideline](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md), we often add path to file when we refer a file.

By the way, I often use the `.hprof` as the file extension.

2021-08-04 12:11 UTC, einverne commented on pages.zh/common/jhat.md
> +`jhat {{堆转储文件}}`
```suggestion
`jhat {{路径/堆转储文件}}`
```

2021-08-04 12:11 UTC, einverne commented on pages.zh/common/jhat.md
> +`jhat -p {{端口}} {{堆转储文件}}`
```suggestion
`jhat -p {{端口}} {{路径/堆转储文件}}`
```

2021-08-04 12:11 UTC, einverne commented on pages.zh/common/jhat.md
> +`jhat -J-mx8G {{堆转储文件}}`
```suggestion
`jhat -J-mx8G {{路径/堆转储文件}}`
```

2021-08-05 01:53 UTC, BillLucky commented on pages.zh/common/jhat.md
> +`jhat {{堆转储文件}}`
OK，Thanks for your review

2021-08-06 08:25 UTC, einverne approved these changes

2021-08-06 08:25 UTC, merged