useradd, userdel, usermod: add Spanish translation
tldr-pages/tldr pull request #6292
Opened 2021-08-02 19:19 UTC by victorhck

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-08-03 12:15 UTC, navarroaxel requested changes

2021-08-03 12:15 UTC, navarroaxel commented on pages.es/linux/userdel.md
> +- Elimina un usuario junto con su directorios home y mail spool:
```suggestion
- Elimina un usuario junto con su directorio home y mail spool:
```

2021-08-03 12:15 UTC, navarroaxel commented on pages.es/linux/usermod.md
> +`usermod -m -d {{ruta/a/home}} {{usuario}}`
```suggestion
`usermod -m -d {{ruta/al/home}} {{usuario}}`
```

2021-08-03 15:56 UTC, victorhck commented
agree!

2021-08-03 17:12 UTC, navarroaxel approved these changes

2021-08-05 12:18 UTC, marchersimon approved these changes
Thanks @victorhck

2021-08-05 12:18 UTC, merged

2021-08-05 17:34 UTC, victorhck commented
a pleasure! ;)