asciidoctor: add page
tldr-pages/tldr pull request #6455
Opened 2021-09-02 17:41 UTC by glapa-grossklag

Closes #6425.

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-09-02 18:22 UTC, pixelcmtd requested changes
The descriptions of the examples shouldn't contain the file names, instead you might use something like `Convert an AsciiDoc file to [...]`.

2021-09-02 18:47 UTC, marchersimon commented on pages/common/asciidoctor.md
> +`asciidoctor {{path/to/document.adoc}}`
```suggestion
- Convert a specific `.adoc` file to HTML (the default output format):

`asciidoctor {{path/to/file.adoc}}`
```
This is the format we usually use.

2021-09-02 19:31 UTC, glapa-grossklag commented on pages/common/asciidoctor.md
> +`asciidoctor {{path/to/document.adoc}}`
Got it, thanks! :-)

2021-09-03 06:26 UTC, glapa-grossklag commented on pages/common/asciidoctor.md
> +> An AsciiDoc processor to read and translate AsciiDoc to a publishable format.
Yes, I agree. What do you think about the following?
> Convert AsciiDoc files to a publishable format.

2021-09-03 08:43 UTC, pixelcmtd commented on pages/common/asciidoctor.md
> +> An AsciiDoc processor to read and translate AsciiDoc to a publishable format.
I don't like that. It doesn't describe the tool, but what you do with it, and just kinda sounds off to me.

2021-09-03 14:38 UTC, sbrl commented on pages/common/asciidoctor.md
> +> An AsciiDoc processor to read and translate AsciiDoc to a publishable format.
@nicokosi's suggestion seems the most logical to me

2021-09-03 16:45 UTC, marchersimon commented on pages/common/asciidoctor.md
> +`asciidoctor --backend=pdf --require=asciidoctor-pdf {{path/to/file.adoc}}`
Even though it's a fixed value in *this* example, it's still an argument and should go in token syntax:
```suggestion
`asciidoctor --backend={{pdf}} --require={{asciidoctor-pdf}} {{path/to/file.adoc}}`
```

2021-09-03 18:05 UTC, marchersimon approved these changes
Thanks @glapa-grossklag

2021-09-03 18:46 UTC, navarroaxel approved these changes

2021-09-03 19:38 UTC, sbrl approved these changes
Thanks, @glapa-grossklag!

2021-09-03 20:07 UTC, pixelcmtd approved these changes

2021-09-03 20:09 UTC, merged

2021-09-05 10:30 UTC, nicokosi reviewed
Well done! 👍