tlmgr-info: add page
tldr-pages/tldr pull request #6511
Opened 2021-09-12 18:51 UTC by marchersimon

For #6464

2021-09-12 20:58 UTC, navarroaxel approved these changes

2021-09-13 07:03 UTC, pixelcmtd requested changes

2021-09-13 07:03 UTC, pixelcmtd commented on pages/common/tlmgr-info.md
> +- Show only specific information abouta package:
```suggestion
- Show only specific information about a package:
```

2021-09-13 10:45 UTC, pixelcmtd approved these changes

2021-09-13 10:45 UTC, merged