Fix bug
tldr-pages/tldr pull request #6529
Opened 2021-09-15 09:47 UTC by anderly011

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

2021-09-15 11:51 UTC, navarroaxel requested changes
Hi @anderly011, welcome and thanks for your submission. I left some comments.

2021-09-15 11:51 UTC, navarroaxel commented on pages.zh/linux/cal.md
> +> 更多信息：https://manned.org/cal.
```suggestion
> 更多信息：<https://manned.org/cal>.
```

2021-09-15 11:51 UTC, navarroaxel commented on pages.zh/linux/chage.md
> +> 更多信息：https://manned.org/chage.
```suggestion
> 更多信息：<https://manned.org/chage>.
```

2021-09-15 11:51 UTC, navarroaxel commented on pages.zh/linux/chage.md
> +`sudo chage -d 0`
This should be fixed in the main page too.
```suggestion
`sudo chage -d {{0}}`
```

2021-09-15 11:59 UTC, navarroaxel approved these changes

2021-09-15 12:01 UTC, navarroaxel approved these changes

2021-09-15 12:13 UTC, blueskyson approved these changes

2021-09-15 12:13 UTC, blueskyson commented on pages.zh/linux/chage.md
> +- 启用密码在10天内过期：
Almost done, thank you. Please place one space before/after English words and numbers.
```suggestion
- 启用密码在 10 天内过期：
```

2021-09-15 12:14 UTC, merged

2021-09-15 12:15 UTC, navarroaxel commented
Congratulations @anderly011 :tada:

2021-09-15 12:16 UTC, anderly011 commented
Thanks all!

2021-10-03 11:34 UTC, hmsjy2017 reviewed
😀