ganache-cli: add page
tldr-pages/tldr pull request #6535
Opened 2021-09-16 03:04 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-09-16 11:34 UTC, SethFalco requested changes

2021-09-16 11:34 UTC, SethFalco commented on pages/common/ganache-cli.md
> +`ganache-cli --secure --unlock "{{account_address1}}" --unlock "{{account_address2""`
```suggestion
`ganache-cli --secure --unlock "{{account_address1}}" --unlock "{{account_address2}}"`
```

Is this what you mean?

2021-09-16 11:51 UTC, navarroaxel commented on pages/common/ganache-cli.md
> +`ganache-cli --secure --unlock "{{account_address1}}" --unlock "{{account_address2""`
re-checking the docs:
```suggestion
`ganache-cli --secure --unlock "{{account_private_key1}}" --unlock "{{account_private_key2}}"`
```

2021-09-16 11:55 UTC, SethFalco approved these changes

2021-09-16 19:25 UTC, pixelcmtd requested changes

2021-09-16 19:25 UTC, pixelcmtd commented on pages/common/ganache-cli.md
> +- Run Ganache and log all request to stdout:
```suggestion
- Run Ganache and log all requests to stdout:
```

2021-09-16 19:31 UTC, pixelcmtd approved these changes

2021-09-17 16:12 UTC, marchersimon approved these changes

2021-09-17 16:13 UTC, merged