dir: add german translation
tldr-pages/tldr pull request #6620
Opened 2021-10-01 01:10 UTC by derNiklaas

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-10-01 01:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6620) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6620) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=6620) it.</sub>

2021-10-01 12:15 UTC, navarroaxel requested changes

2021-10-01 12:15 UTC, navarroaxel commented on pages.de/windows/dir.md
> +> Weitere Informationen: <https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/dir>.
We prefer language agnostic links for Microsoft pages.
```suggestion
> Weitere Informationen: <https://docs.microsoft.com/windows-server/administration/windows-commands/dir>.
```

2021-10-01 12:15 UTC, navarroaxel commented on pages.de/windows/dir.md
> +`dir {{pfad/zu/verzeichnis}} /q`
We only accept translations of the main pages, to keep this simple to maintain. You can add  these examples to the English page if you want.

2021-10-01 12:52 UTC, navarroaxel approved these changes

2021-10-01 21:37 UTC, pixelcmtd commented on pages.de/windows/dir.md
> +> Zeigt den Inhalt von Arbeitsverzeichnisses an.
```suggestion
> Zeige den Inhalt von Verzeichnissen an.
```

2021-10-01 21:37 UTC, pixelcmtd commented on pages.de/windows/dir.md
> +- Zeigt den Inhalt (inklusive versteckte Inhalte) des aktuellen Arbeitsverzeichnisses an:
```suggestion
- Zeige den Inhalt, inklusive versteckter Inhalte, des aktuellen Arbeitsverzeichnisses an:
```

2021-10-01 21:37 UTC, pixelcmtd commented on pages.de/windows/dir.md
> +- Zeigt den Inhalt (inklusive versteckte Inhalte) des angegebenen Arbeitsverzeichnisses an:
```suggestion
- Zeige den Inhalt, inklusive versteckte Inhalte, des angegebenen Verzeichnisses an:
```

2021-10-01 21:37 UTC, pixelcmtd commented on pages.de/windows/dir.md
> +- Zeigt den Inhalt des angegebenen Arbeitsverzeichnisses an:
```suggestion
- Zeige den Inhalt des angegebenen Verzeichnisses an:
```

2021-10-02 22:33 UTC, pixelcmtd commented on pages.de/windows/dir.md
> +- Zeigt den Inhalt des aktuellen Arbeitsverzeichnisses an:
```suggestion
- Zeige den Inhalt des aktuellen Verzeichnisses an:
```

2021-10-02 22:33 UTC, pixelcmtd commented on pages.de/windows/dir.md
> +- Zeige den Inhalt, inklusive versteckter Inhalte, des aktuellen Arbeitsverzeichnisses an:
```suggestion
- Zeige den Inhalt, inklusive versteckter Inhalte, des aktuellen Verzeichnisses an:
```

2021-10-03 14:51 UTC, marchersimon approved these changes
Thanks @derNiklaas

2021-10-03 14:51 UTC, merged