npx: add German translation
tldr-pages/tldr pull request #6632
Opened 2021-10-01 10:15 UTC by schwarmco

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-10-01 12:51 UTC, navarroaxel requested changes

2021-10-01 12:51 UTC, navarroaxel commented on pages.de/common/npx.md
> +`npx -p {{package_name}} {{module_name}}`
I think `paket_name` is the translation :thinking: 
```suggestion
`npx -p {{paket_name}} {{module_name}}`
```

2021-10-01 15:47 UTC, navarroaxel approved these changes

2021-10-03 14:40 UTC, marchersimon approved these changes
Looks good, thanks @schwarmco

2021-10-03 14:41 UTC, merged