node: add French translation
tldr-pages/tldr pull request #6688
Opened 2021-10-02 15:28 UTC by Nico385412

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

 - **Version of the command being documented (if known):**

2021-10-02 18:35 UTC, navarroaxel requested changes

2021-10-02 18:35 UTC, navarroaxel commented on pages.fr/common/node.md
> +`node {{chemin/vers/le/fichier}}`
I think that we use this form:
```suggestion
`node {{chemin/vers/fichier}}`
```

2021-10-02 18:35 UTC, navarroaxel commented on pages.fr/common/node.md
> +`node --no-lazy --inspect-brk {{path/to/file}}`
```suggestion
`node --no-lazy --inspect-brk {{chemin/vers/fichier}}`
```

2021-10-03 07:22 UTC, Nico385412 commented on pages.fr/common/node.md
> +`node --no-lazy --inspect-brk {{path/to/file}}`
done 👍

2021-10-03 07:22 UTC, Nico385412 commented on pages.fr/common/node.md
> +`node {{chemin/vers/le/fichier}}`
done 👍

2021-10-03 12:56 UTC, navarroaxel approved these changes

2021-10-04 16:05 UTC, marchersimon approved these changes
👍🏽

2021-10-04 16:05 UTC, merged

2021-10-04 16:06 UTC, marchersimon commented
@Nico385412 would you like to help out with #6509? We'd just need a translation of a single sentence. Thanks

2021-10-05 22:29 UTC, Nico385412 commented
> @Nico385412 would you like to help out with #6509? We'd just need a translation of a single sentence. Thanks

done ;) 
https://github.com/tldr-pages/tldr/pull/6823