adduser: add german translation
tldr-pages/tldr pull request #6690
Opened 2021-10-02 16:23 UTC by lemeleti

- [x ] The page (if new), does not already exist in the repository.
- [x ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x ] The page has 8 or fewer examples.
- [x ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x ] The page description includes a link to documentation or a homepage (if applicable).

 - **Version of the command being documented (if known):**

2021-10-02 16:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6690) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6690) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=6690) it.</sub>

2021-10-02 18:22 UTC, navarroaxel requested changes

2021-10-02 18:22 UTC, navarroaxel commented on pages.de/linux/adduser.md
> +`adduser {{username}}`
Please translate placeholders to help non-English speakers
```suggestion
`adduser {{benutzername}}`
```

2021-10-02 18:22 UTC, navarroaxel commented on pages.de/linux/adduser.md
> +`adduser --no-create-home {{username}}`
```suggestion
`adduser --no-create-home {{benutzername}}`
```

2021-10-02 18:22 UTC, navarroaxel commented on pages.de/linux/adduser.md
> +`adduser --ingroup {{group}} {{username}}`
```suggestion
`adduser --ingroup {{gruppe}} {{benutzername}}`
```

2021-10-02 18:22 UTC, navarroaxel commented on pages.de/linux/adduser.md
> +`adduser {{username}} {{group}}`
```suggestion
`adduser {{benutzername}} {{gruppe}}`
```

2021-10-02 18:22 UTC, navarroaxel commented on pages.de/linux/adduser.md
> +`adduser --shell {{path/to/shell}} {{username}}`
```suggestion
`adduser --shell {{pfad/zu/shell}} {{benutzername}}`
```

2021-10-02 18:22 UTC, navarroaxel commented on pages.de/linux/adduser.md
> +`adduser --home {{path/to/home}} {{username}}`
```suggestion
`adduser --home {{pfad/zu/home}} {{benutzername}}`
```

2021-10-02 18:34 UTC, navarroaxel approved these changes

2021-10-03 19:00 UTC, marchersimon commented on pages.de/linux/adduser.md
> +- Hinzufügen eines vorhandenen Benutzers zur angegebenen Gruppe:
```suggestion
- Füge einen vorhandenen Benutzer zur angegebenen Gruppe hinzu:
```

2021-10-03 19:28 UTC, marchersimon commented on pages.de/linux/adduser.md
> +- Erzeuge einen neuen Benutzer und füge ihn zur angegebenen Gruppe hinzu:
```suggestion
- Erstelle einen neuen Benutzer und füge ihn zur angegebenen Gruppe hinzu:
```

2021-10-04 06:34 UTC, lemeleti commented
Used wrong commit message format. That's why theres a force-push.

2021-10-04 07:45 UTC, marchersimon commented
@lemeleti the commit message doesn't matter. Whoever merges the PR can set the commit message

2021-10-04 07:46 UTC, marchersimon approved these changes
Thanks

2021-10-04 07:47 UTC, merged