du: add German translation
tldr-pages/tldr pull request #6693
Opened 2021-10-02 16:59 UTC by k-stz

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-10-02 18:50 UTC, navarroaxel requested changes

2021-10-02 18:50 UTC, navarroaxel commented on pages.de/common/du.md
> +`du -h --max-depth=N {{Pfad/zum/Verzeichnis}}`
```suggestion
`du -h --max-depth=N {{pfad/zu/verzeichnis}}`
```

2021-10-02 18:50 UTC, navarroaxel commented on pages.de/common/du.md
> +`du -{{b|k|m}} {{Pfad/zum/Verzeichnis}}`
We use `pfad/zu/verzeichnis`
```suggestion
`du -{{b|k|m}} {{pfad/zu/verzeichnis}}`
```

2021-10-02 18:50 UTC, navarroaxel commented on pages.de/common/du.md
> +`du -h {{Pfad/zum/Verzeichnis}}`
```suggestion
`du -h {{pfad/zu/verzeichnis}}`
```

2021-10-02 18:50 UTC, navarroaxel commented on pages.de/common/du.md
> +`du -ah {{Pfad/zum/Verzeichnis}}`
```suggestion
`du -ah {{pfad/zu/verzeichnis}}`
```

2021-10-02 18:50 UTC, navarroaxel commented on pages.de/common/du.md
> +`du -sh {{Pfad/zum/Verzeichnis}}`
```suggestion
`du -sh {{pfad/zu/verzeichnis}}`
```

2021-10-02 19:44 UTC, k-stz commented on pages.de/common/du.md
> +`du -sh {{Pfad/zum/Verzeichnis}}`
fixed with latest commit

2021-10-02 22:30 UTC, pixelcmtd commented on pages.de/common/du.md
> +- Liste die Größe von Verzeichnissen und Unterverzeichnissen in für Menschen lesbaren Einheiten auf (d. h. die automatische Auswahl der geeigneten Einheit für jede Größe):
```suggestion
- Liste die Größe von Verzeichnissen und Unterverzeichnissen in menschenlesbaren Einheiten auf (d.h. automatische Auswahl der geeigneten Einheit für jede Größe):
```

2021-10-02 22:30 UTC, pixelcmtd commented on pages.de/common/du.md
> +- Zeige die Größe eines Verzeichnisses in für Menschen lesbaren Einheiten:
```suggestion
- Zeige die Größe eines einzelnen Verzeichnisses in menschenlesbaren Einheiten:
```

2021-10-02 22:30 UTC, pixelcmtd commented on pages.de/common/du.md
> +- Liste die Größe eines Verzeichnisses und seiner Dateien in für Menschen lesbaren Einheiten:
```suggestion
- Liste die Größe eines Verzeichnisses und seiner Dateien in menschenlesbaren Einheiten:
```

2021-10-02 22:30 UTC, pixelcmtd commented on pages.de/common/du.md
> +- Auflistung der menschenlesbaren Größen eines Verzeichnisses und aller Unterverzeichnisse, bis zu einer Tiefe von `N` Ebenen:
```suggestion
- Liste die menschenlesbaren Größen eines Verzeichnisses und aller Unterverzeichnisse, bis zu einer Tiefe von `N` Ebenen:
```

2021-10-02 22:30 UTC, pixelcmtd commented on pages.de/common/du.md
> +- Liste die Größe aller `.jpg`-Dateien in Unterverzeichnissen des aktuellen Verzeichnisses auf, in für menschenlesbaren Einheiten und zeige am Ende die kumulierte Gesamtsumme an:
```suggestion
- Liste die menschenlesbare Größe aller `.jpg`-Dateien in Unterverzeichnissen des aktuellen Verzeichnisses auf und zeige am Ende die kumulierte Gesamtsumme an:
```

2021-10-03 03:32 UTC, navarroaxel approved these changes

2021-10-03 14:55 UTC, marchersimon approved these changes
Thanks @k-stz

2021-10-03 14:56 UTC, merged