fscrypt: add page
tldr-pages/tldr pull request #6694
Opened 2021-10-02 17:40 UTC by ezr

- [ x] The page (if new), does not already exist in the repository.
- [ x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ x] The page has 8 or fewer examples.
- [ x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ x] The page description includes a link to documentation or a homepage (if applicable).

 - **Version of the command being documented (if known):** fscrypt version v0.3.0

2021-10-02 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6694) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=6694) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=6694) it.</sub>

2021-10-02 20:13 UTC, ezr commented
> The [build](https://github.com/tldr-pages/tldr/actions/runs/1298720895) for this PR failed with the following error(s):
> 
> ```
> pages/linux/fscrypt.md:
> Error: Parse error on line 4:
> ....com/google/fscrypt>- Prepare the root
> -----------------------^
> Expecting 'END_INFORMATION_LINK_URL', got 'NEWLINE'
> pages/linux/fscrypt.md:4: TLDR011 Page never contains more than a single empty line
> ```
> 
> Please fix the error(s) and push again.

I was missing a period at the end of line 4. I added the period with a second commit. I don't know how to push again.

2021-10-02 22:13 UTC, CleanMachine1 requested changes

2021-10-02 22:13 UTC, CleanMachine1 commented on pages/linux/fscrypt.md
> +`fscrypt encrypt /path/to/dir`
```suggestion
`fscrypt encrypt {{path/to/directory}}`
```
Following our syntax.

2021-10-02 22:13 UTC, CleanMachine1 commented on pages/linux/fscrypt.md
> +`fscrypt unlock /path/to/dir`
```suggestion
`fscrypt unlock {{path/to/encrypted_directory}}`
```

2021-10-02 22:13 UTC, CleanMachine1 commented on pages/linux/fscrypt.md
> +`fscrypt lock /path/to/dir`
```suggestion
`fscrypt lock {{path/to/encrypted_directory}}`
```

2021-10-02 22:44 UTC, CleanMachine1 approved these changes

2021-10-05 19:19 UTC, marchersimon approved these changes
Thanks @ezr

2021-10-05 19:20 UTC, merged