pacstall: add page
tldr-pages/tldr pull request #6732
Opened 2021-10-03 15:32 UTC by Fabiokleis

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-03 16:24 UTC, nicokosi commented
`pacman` seems to a be Linux-only, so I think it that this new page should be ` pages/linux/pacstall.md` (and not `pages/common/pacstall.md`)

2021-10-03 16:28 UTC, Fabiokleis commented
@nicokosi ok, I'll move to

2021-10-03 16:51 UTC, blueskyson reviewed
Thanks for contribution. Here are some suggestions.

2021-10-03 16:51 UTC, blueskyson commented on pages/linux/pacstall.md
> +> Pacstall, making easier to install programs.
I'm not sure if `pacstall` includes AUR repositories, its repo says it related to AUR.
```suggestion
> Pacstall, make it easier to install AUR packages for Ubuntu.
```

2021-10-03 16:51 UTC, blueskyson commented on pages/linux/pacstall.md
> +`pacstall -Qi {{packagename}}`
Use snake_case.
```suggestion
`pacstall -Qi {{package_name}}`
```

2021-10-03 16:51 UTC, blueskyson commented on pages/linux/pacstall.md
> +- List all packages are installed:
```suggestion
- List all installed packages:
```

2021-10-03 16:51 UTC, blueskyson commented on pages/linux/pacstall.md
> +- Install program, its the same of apt install:
```suggestion
- Install program, equivalent of apt install:
```

2021-10-03 16:51 UTC, blueskyson commented on pages/linux/pacstall.md
> +- Remove program, its the same of apt remove:
```suggestion
- Remove program, equivalent of apt remove:
```

2021-10-03 16:51 UTC, blueskyson commented on pages/linux/pacstall.md
> +- Update packages, its the same of apt upgrade:
```suggestion
- Update packages, equivalent of apt upgrade:
```

2021-10-03 16:55 UTC, blueskyson approved these changes
👍

2021-10-04 02:59 UTC, navarroaxel requested changes
Nice command.

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +> Pacstall, make it easier to install AUR packages for Ubuntu.
I think this is a better command description
```suggestion
> An AUR package manager for Ubuntu.
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -S program`
We prefer long arguments if available
```suggestion
`pacstall --search {{package_name}}`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -I program`
We use token syntax for argument options
```suggestion
`pacstall --install {{package_name}}`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +- Remove program, equivalent of apt remove:
```suggestion
- Remove a package:
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -R program`
```suggestion
`pacstall --remove {{package_name}}`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -U`
```suggestion
`pacstall --update`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -Up`
```suggestion
`pacstall --upgrade`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -Qi {{package_name}}`
```suggestion
`pacstall --query-info {{package_name}}`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -L`
```suggestion
`pacstall --list`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +- Search for program in repositories, its equivalent of apt search:
```suggestion
- Search the package database for a package name:
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +- Install program, equivalent of apt install:
```suggestion
- Install a package:
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +`pacstall -A {{https://github/gitlab.com/example}}`
We use this placeholder in the `git-clone` page, I think it fits here.
```suggestion
`pacstall --add-repo {{remote_repository_location}}`
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +- Show package info:
```suggestion
- Display information about a package:
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +- Add one more repository to search:
```suggestion
- Add a repository to the database (only GitHub and GitLab are supported):
```

2021-10-04 02:59 UTC, navarroaxel commented on pages/linux/pacstall.md
> +- Update packages, equivalent of apt upgrade:
```suggestion
- Update all packages:
```

2021-10-04 14:36 UTC, navarroaxel approved these changes

2021-10-04 14:46 UTC, merged