rpm: add more information link
tldr-pages/tldr pull request #6754
Opened 2021-10-03 21:28 UTC by derNiklaas

- [x] The page (if new), does not already exist in the repository.
- [x] The page description includes a link to documentation or a homepage (if applicable).

Partial fix for #6062

2021-10-03 21:30 UTC, navarroaxel requested changes

2021-10-03 21:30 UTC, navarroaxel commented on pages/linux/rpm.md
> +> More information: <https://manned.org/rpm.8>
The `.8` is not required
```suggestion
> More information: <https://manned.org/rpm>.
```

2021-10-03 21:31 UTC, navarroaxel approved these changes

2021-10-04 09:01 UTC, marchersimon commented on pages/linux/rpm.md
> +> More information: <https://manned.org/rpm>.
I think we should definitively link to the official page here.
```suggestion
> More information: <https://rpm.org/>.
```

2021-10-04 14:00 UTC, marchersimon approved these changes
Thanks @derNiklaas

2021-10-04 14:00 UTC, merged