cgroups: add page
tldr-pages/tldr pull request #6766
Opened 2021-10-04 05:40 UTC by Ray6464

cgroups are used via cgcreate, cgexec, and cgclassify, and users may look for `tldr cgcreate` or something, so i'll make individual pages for them.

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-10-06 10:40 UTC, marchersimon commented
If `cgroup` isn't a command on its own, we can't document it.

2021-10-10 13:48 UTC, SethFalco commented
I'm with @marchersimon.

Basically, this suggests we should have a new type of page (we have a regular page, and an alias page already) which behaves as an index page for related commands.

To find commands under `cgroups`, that's where the search feature of clients would probably come in handy. I don't think there needs to be a manually maintained set of index pages.

2021-10-11 01:52 UTC, sbrl commented
Hmmm, if people are trying to view it and getting confused then it may be worth making an exception here. This could maybe be an expanded alias page? A page must have at least 1 example I would think, so perhaps 1 example for each command in question would work?

2021-10-13 02:42 UTC, Ray6464 commented
> Hmmm, if people are trying to view it and getting confused then it may be worth making an exception here. This could maybe be an expanded alias page? A page must have at least 1 example I would think, so perhaps 1 example for each command in question would work?

Yes, something like this should make it better.

2021-12-01 18:56 UTC, marchersimon commented
I don't think we can merge this as is, because it's just pointing to other tldr pages. We should add least add a few examples as ＠sbrl said above:

> A page must have at least 1 example I would think, so perhaps 1 example for each command in question would work?

2021-12-02 02:12 UTC, sbrl requested changes

2021-12-02 02:12 UTC, sbrl commented on pages/linux/cgroups.md
> +- Show the tldr page for a cgclassify:
Perhaps this will read better?
```suggestion
- Show the tldr page for `cgclassify`:
```

2021-12-02 02:12 UTC, sbrl commented on pages/linux/cgroups.md
> +- Show the tldr page for a cgcreate:
```suggestion
- Show the tldr page for `cgcreate`:
```

2021-12-02 02:12 UTC, sbrl commented on pages/linux/cgroups.md
> +- Show the tldr page for a cgexec:
Perhaps this will read better?
```suggestion
- Show the tldr page for `cgexec`:
```

2021-12-07 20:33 UTC, sbrl approved these changes
Thanks, @Ray6464!

2021-12-10 09:57 UTC, navarroaxel approved these changes

2021-12-10 09:57 UTC, merged