aws-cur: add pt_BR translation
tldr-pages/tldr pull request #6782
Opened 2021-10-04 13:05 UTC by caduvieira

- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-04 13:16 UTC, navarroaxel requested changes

2021-10-04 13:16 UTC, navarroaxel commented on pages.pt_BR/common/aws-cur.md
> +`aws cur put-report-definition --report-definition file://{{caminho/para/definição-do-relatório.json}}`
We use `snake_case` for placeholders
```suggestion
`aws cur put-report-definition --report-definition file://{{caminho/para/definição_do_relatório.json}}`
```

2021-10-04 13:27 UTC, navarroaxel approved these changes

2021-10-04 13:38 UTC, navarroaxel commented on pages.pt_BR/common/aws-cur.md
> +`aws cur put-report-definition --report-definition file://{{caminho/para/definição-do-relatório.json}}`
@caduvieira Oh, I see this issue is in the main (English) page too. Could you edit that page inside this PR?

2021-10-06 11:09 UTC, marchersimon approved these changes
Thanks @caduvieira

2021-10-06 11:09 UTC, merged