whoami: add Indonesia translation
tldr-pages/tldr pull request #6810
Opened 2021-10-05 13:32 UTC by evaleries

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-10-05 14:57 UTC, navarroaxel requested changes

2021-10-05 14:57 UTC, navarroaxel commented on pages.id/windows/whoami.md
> +> Info lebih lanjut: <https://docs.microsoft.com/windows-server/administration/windows-commands/whoami>.
We use this text for `More information`:
```suggestion
> Informasi lebih lanjut: <https://docs.microsoft.com/windows-server/administration/windows-commands/whoami>.
```

2021-10-05 17:56 UTC, navarroaxel approved these changes

2021-10-06 10:33 UTC, theodorusclarence approved these changes

2021-10-06 13:51 UTC, marchersimon approved these changes
Thanks @evaleries

2021-10-06 13:52 UTC, merged