scutil, screencapture, systemsetup, readlink, softwareupdate: add pt_PT translation
tldr-pages/tldr pull request #7088
Opened 2021-10-18 12:53 UTC by rubenandre

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-11-01 04:10 UTC, navarroaxel requested changes
Sorry for the delay for the review !

2021-11-01 04:10 UTC, navarroaxel commented on pages.pt_PT/osx/readlink.md
> +> Mais informação: <https://www.gnu.org/software/coreutils/readlink>.
```suggestion
> Mais informações: <https://www.gnu.org/software/coreutils/readlink>.
```

2021-11-01 10:24 UTC, rubenandre commented on pages.pt_PT/osx/readlink.md
> +> Mais informação: <https://www.gnu.org/software/coreutils/readlink>.
fixed

2021-11-01 12:06 UTC, navarroaxel approved these changes

2021-11-04 19:32 UTC, marchersimon approved these changes
Thanks @rubenandre

2021-11-04 19:33 UTC, merged