sdcv, visudo: add link and --version example
tldr-pages/tldr pull request #7207
Opened 2021-10-25 08:41 UTC by werewolf-65

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-29 23:42 UTC, CleanMachine1 requested changes

2021-10-29 23:42 UTC, CleanMachine1 commented on pages/common/visudo.md
>  - Check sudoers file for errors:
```suggestion 
- Check the sudoers file for errors:
```

2021-10-29 23:42 UTC, CleanMachine1 commented on pages/common/visudo.md
>  - Edit sudoers file:
```suggestion 
- Edit the sudoers file:
```

2021-11-04 20:09 UTC, marchersimon commented on pages/common/visudo.md
> +> More information: <https://manned.org/visudo>.
We should use the official website here:
```suggestion
> More information: <https://www.sudo.ws/man/1.8.13/visudo.man.html>.
```

2021-11-06 11:35 UTC, marchersimon approved these changes
Thanks @werewolf-65

2021-11-06 11:35 UTC, marchersimon commented
@mfrw @CleanMachine1 could you please review this?

2021-11-25 21:31 UTC, sbrl approved these changes
Thanks, @werewolf-65!

2021-11-25 21:32 UTC, sbrl commented
Merging, as this has been sitting around a while and all comments appear to have been addressed.

2021-11-25 21:32 UTC, merged

2021-11-28 03:59 UTC, werewolf-65 commented
> Merging, as this has been sitting around a while and all comments appear to have been addressed.

Thanks!