mp3info: add page
tldr-pages/tldr pull request #7235
Opened 2021-10-26 18:45 UTC by MDecker-MobileComputing

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**
0.8.5a

2021-11-01 04:05 UTC, navarroaxel requested changes

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +`mp3info {{path/to/mp3file}}`
```suggestion
`mp3info {{path/to/file.mp3}}`
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +`mp3info -i {{path/to/mp3file}}`
```suggestion
`mp3info -i {{path/to/file.mp3}}`
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +`mp3info -a "{{artist_name}}" -t "{{song_title}}" -l "{{album_title}}" -y {{year}} -c "{{comment_text}}" {{path/to/mp3file}}`
```suggestion
`mp3info -a "{{artist_name}}" -t "{{song_title}}" -l "{{album_title}}" -y {{year}} -c "{{comment_text}}" {{path/to/file.mp3}}`
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +`mp3info -n {{track_number}} {{path/to/mp3file}}`
```suggestion
`mp3info -n {{track_number}} {{path/to/file.mp3}}`
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +`mp3info -g {{genre_number}} {{path/to/mp3file}}`
```suggestion
`mp3info -g {{genre_number}} {{path/to/file.mp3}}`
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +- Set music genre for MP3 file:
```suggestion
- Set music genre for a specific MP3 file:
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +- Set number of track on album:
```suggestion
- Set number of track on album for a specific MP3 file:
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +- Set values for ID3v1 tags in a MP3 file:
```suggestion
- Set values for ID3v1 tags in a specific MP3 file:
```

2021-11-01 04:05 UTC, navarroaxel commented on pages/common/mp3info.md
> +- Show all ID3v1 tags of a MP3 file:
```suggestion
- Show all ID3v1 tags of a specific MP3 file:
```

2021-11-06 21:15 UTC, navarroaxel approved these changes

2021-11-07 14:05 UTC, marchersimon commented on pages/common/mp3info.md
> +- Set number of track on album for a specific MP3 file:
```suggestion
- Set the number of the track in the album for a specific MP3 file:
```

2021-11-07 14:05 UTC, marchersimon commented on pages/common/mp3info.md
> +- Print list of numbers for all music genres:
```suggestion
- Print a list of valid genres and their numeric codes:
```

2021-11-07 14:05 UTC, marchersimon commented on pages/common/mp3info.md
> +- Set music genre for a specific MP3 file:
```suggestion
- Set the music genre for a specific MP3 file:
```

2021-11-07 16:15 UTC, marchersimon approved these changes
Thanks @MDecker-MobileComputing

2021-11-07 16:16 UTC, merged