dolt-clone: add page
tldr-pages/tldr pull request #7237
Opened 2021-10-26 19:25 UTC by wenz

For #5471

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-11-01 04:36 UTC, navarroaxel requested changes

2021-11-01 04:36 UTC, navarroaxel commented on pages/common/dolt-clone.md
> +- Clone a repository and add a remote (defaults to origin):
```suggestion
- Clone an existing repository and add a specific remote (defaults to origin):
```

2021-11-01 04:36 UTC, navarroaxel commented on pages/common/dolt-clone.md
> +- Clone a repository into a new directory (defaults to the repository name):
```suggestion
- Clone an existing repository into a specific directory (defaults to the repository name):
```

2021-11-01 04:36 UTC, navarroaxel commented on pages/common/dolt-clone.md
> +`dolt clone {{repository_url}} {{directory_name}}`
Git supports a path, I think Dolt too
```suggestion
`dolt clone {{repository_url}} {{path/to/directory}}`
```

2021-11-01 04:36 UTC, navarroaxel commented on pages/common/dolt-clone.md
> +- Clone a branch in the repository (defaults to all branches):
Based on the `git-clone` page
```suggestion
- Clone an existing repository only fetching a specific branch (defaults to all branches):
```

2021-11-03 08:05 UTC, wenz commented
Thank you for the suggestions, committed them!

2021-11-05 08:49 UTC, marchersimon approved these changes
Thanks @wenz

2021-11-06 21:10 UTC, navarroaxel approved these changes

2021-11-06 21:10 UTC, navarroaxel commented on pages/common/dolt-clone.md
> +`dolt clone --aws-creds-type {{creds_type}} {{repository_url}}`
```suggestion
`dolt clone --aws-creds-type {{credentials_type}} {{repository_url}}`
```

2021-11-06 21:10 UTC, navarroaxel commented on pages/common/dolt-clone.md
> +`dolt clone --aws-creds-file {{creds_file}} {{repository_url}}`
```suggestion
`dolt clone --aws-creds-file {{credentials_file}} {{repository_url}}`
```

2021-11-06 21:11 UTC, merged