avifenc: add page
tldr-pages/tldr pull request #7240
Opened 2021-10-26 22:20 UTC by muhlinux

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 0.9.3

2021-11-01 04:37 UTC, navarroaxel commented
@muhlinux Could you please sign the license to pass the CLA check?

2021-11-01 04:49 UTC, navarroaxel requested changes

2021-11-01 04:49 UTC, navarroaxel commented on pages/linux/avifenc.md
> +- Convert an image from png to avif:
```suggestion
- Convert a specific PNG image to AVIF:
```

2021-11-01 04:49 UTC, navarroaxel commented on pages/linux/avifenc.md
> +`avifenc image.png image.avif`
```suggestion
`avifenc {{path/to/image.png}} {{path/to/image.avif}}`
```

2021-11-01 04:49 UTC, navarroaxel commented on pages/linux/avifenc.md
> +`avifenc --speed 2 image.png image.avif`
```suggestion
`avifenc --speed {{2}} {{path/to/image.png}} {{path/to/image.avif}}`
```

2021-11-01 04:49 UTC, navarroaxel commented on pages/linux/avifenc.md
> +- Encoder speed (0-10, slowest-fastest, default: 6):
Based on the `zstd` page
```suggestion
- Encode with a specific speed, where 0=slowest, 10=fastest, and 6=default:
```

2021-11-07 13:39 UTC, marchersimon approved these changes
Looks good after ＠navarroaxel's comments have been addressed.
Thanks

2021-11-23 01:31 UTC, navarroaxel approved these changes

2021-11-23 01:32 UTC, navarroaxel commented
@muhlinux could you please sign the license to pass the CLA check?

2022-01-08 00:01 UTC, closed without merging