lxc-network, lxc-profile: add page
tldr-pages/tldr pull request #7280
Opened 2021-10-28 14:06 UTC by mtausig

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

4.0.7

2021-10-30 19:39 UTC, navarroaxel requested changes

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-network.md
> +- Show configuration of an existing network:
```suggestion
- Show configuration of a specific network:
```

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-network.md
> +- Add a running instance to a network:
Should be running?
```suggestion
- Add a running instance to a specific network:
```

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-network.md
> +- Set bridge interface of a network:
```suggestion
- Set a bridge interface of a specific network:
```

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-network.md
> +- Disable NAT for a network:
```suggestion
- Disable NAT for a specific network:
```

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-profile.md
> +- Show configuration of a profile:
```suggestion
- Show configuration of a specific profile:
```

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-profile.md
> +- Edit profile with editor:
```suggestion
- Edit a specific profile in the default editor:
```

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-profile.md
> +- Edit profile by importing a file:
```suggestion
- Edit a specific profile importing the configuration values from a file:
```

2021-10-30 19:39 UTC, navarroaxel commented on pages/linux/lxc-profile.md
> +- Launch a new container with profiles:
```suggestion
- Launch a new container with specific profiles:
```

2021-10-30 19:45 UTC, navarroaxel approved these changes
Remember that you can apply all the suggestions using **1 commit** with `add to batch` <https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request>.
![image](https://user-images.githubusercontent.com/1536740/139556591-02e7ea45-4495-41ef-bdae-e68d77063c8f.png)

2021-10-30 19:46 UTC, mtausig commented
> Remember that you can apply all the suggestions using **1 commit** with `add to batch` 

Thanks, I overlooked that.
But nevermind, I'll just squash them when the reviews are done.

2021-10-30 19:57 UTC, navarroaxel commented
@mtausig Don't worry, we squash when we merge.

2021-11-06 21:06 UTC, marchersimon approved these changes
Thanks @mtausig
There are just a few minor things I'll quickly apply myself

2021-11-06 21:06 UTC, marchersimon commented on pages/linux/lxc-network.md
> +- Show configuration of a specific network:
```suggestion
- Show the configuration of a specific network:
```

2021-11-06 21:06 UTC, marchersimon commented on pages/linux/lxc-profile.md
> +- List available profiles:
```suggestion
- List all available profiles:
```

2021-11-06 21:06 UTC, marchersimon commented on pages/linux/lxc-profile.md
> +> Manage profile for LXD containers.
```suggestion
> Manage profiles for LXD containers.
```

2021-11-06 21:06 UTC, marchersimon commented on pages/linux/lxc-profile.md
> +- Show configuration of a specific profile:
```suggestion
- Show the configuration of a specific profile:
```

2021-11-06 21:08 UTC, merged