jupyter: add pt_BR translation
tldr-pages/tldr pull request #7285
Opened 2021-10-28 19:31 UTC by andrecoco

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 14:21 UTC, navarroaxel requested changes

2021-10-30 14:21 UTC, navarroaxel commented on pages.pt_BR/common/jupyter.md
> +- Abrir um caderno Jupyter específico:
```suggestion
- Abre um caderno Jupyter específico:
```

2021-10-30 14:21 UTC, navarroaxel commented on pages.pt_BR/common/jupyter.md
> +- Inicie um servidor de notebooks Jupyter no diretório atual:
```suggestion
- Inicia um servidor de notebooks Jupyter no diretório atual:
```

2021-10-30 14:21 UTC, navarroaxel commented on pages.pt_BR/common/jupyter.md
> +- Exportar um caderno Jupyter específico para outro formato:
```suggestion
- Exporta um caderno Jupyter específico para outro formato:
```

2021-10-30 14:21 UTC, navarroaxel commented on pages.pt_BR/common/jupyter.md
> +- Inicie um servidor em uma porta específica:
```suggestion
- Inicia um servidor em uma porta específica:
```

2021-10-30 14:21 UTC, navarroaxel commented on pages.pt_BR/common/jupyter.md
> +- Pare o servidor atualmente em funcionamento:
```suggestion
- Para o servidor atualmente em funcionamento:
```

2021-10-30 14:21 UTC, navarroaxel commented on pages.pt_BR/common/jupyter.md
> +- Inicie o JupyterLab, se instalado, no diretório atual:
```suggestion
- Inicia o JupyterLab, se instalado, no diretório atual:
```

2021-10-30 14:26 UTC, navarroaxel approved these changes

2021-11-04 09:10 UTC, marchersimon approved these changes
Thanks @andrecoco

2021-11-04 09:10 UTC, merged