emacs: add pt_BR translation
tldr-pages/tldr pull request #7297
Opened 2021-10-29 13:58 UTC by andrecoco

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 13:38 UTC, navarroaxel requested changes
Hi @andrecoco, welcome and thanks for your submission. I left some comments.

2021-10-30 13:38 UTC, navarroaxel commented on pages.pt_BR/common/emacs.md
> +- Iniciar o Emacs e abra um arquivo:
Please use presente indicativo:
```suggestion
- Inicia o Emacs e abra um arquivo:
```

2021-10-30 13:38 UTC, navarroaxel commented on pages.pt_BR/common/emacs.md
> +- Iniciar o Emacs em modo console (sem uma janela X):
```suggestion
- Inicia o Emacs em modo console (sem uma janela X):
```

2021-10-30 13:38 UTC, navarroaxel commented on pages.pt_BR/common/emacs.md
> +- Iniciar um servidor Emacs em segundo plano (acessível através do `emacsclient`):
```suggestion
- Inicia um servidor Emacs em segundo plano (acessível através do `emacsclient`):
```

2021-10-30 13:38 UTC, navarroaxel commented on pages.pt_BR/common/emacs.md
> +- Parar um servidor Emacs em funcionamento e todas as suas instâncias, pedindo confirmação em arquivos não salvos:
```suggestion
- Para um servidor Emacs em funcionamento e todas as suas instâncias, pedindo confirmação em arquivos não salvos:
```

2021-10-30 13:38 UTC, navarroaxel commented on pages.pt_BR/common/emacs.md
> +- Abrir um arquivo em uma linha especificada:
```suggestion
- Abre um arquivo em uma linha especificada:
```

2021-10-30 13:38 UTC, navarroaxel commented on pages.pt_BR/common/emacs.md
> +- Deixar o Emacs:
```suggestion
- Deixa o Emacs:
```

2021-10-30 13:38 UTC, navarroaxel commented on pages.pt_BR/common/emacs.md
> +- Salvar um arquivo em Emacs:
```suggestion
- Salva um arquivo em Emacs:
```

2021-10-30 14:20 UTC, andrecoco commented
Thanks for the comments, i'll check the other translations i did for those mistakes

2021-10-30 14:26 UTC, navarroaxel approved these changes

2021-11-01 19:56 UTC, marchersimon approved these changes
Thanks @andrecoco

2021-11-01 19:56 UTC, merged