dumpzilla
tldr-pages/tldr pull request #7303
Opened 2021-10-29 21:43 UTC by ciph3rz

- [x ] The page (if new), does not already exist in the repository.
- [ x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x ] The page has 8 or fewer examples.
- [ x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-29 21:43 UTC, ciph3rz commented
#6863

2021-10-30 14:08 UTC, navarroaxel commented on pages/common/dumpzilla.md
> +- Extract complete listing of browser download history:
Where is stored?

2021-10-30 14:08 UTC, navarroaxel commented on pages/common/dumpzilla.md
> +- Gather summary data from browser profile:
Print a summary or it's dumped to a file?

2021-11-05 01:52 UTC, einverne requested changes

2021-11-05 01:52 UTC, einverne commented on pages/common/dumpzilla.md
> +- Extract complete listing of browser bookmarks:
Same here,  store in the current directory?

2021-12-21 00:01 UTC, closed without merging