Add the built-in HTTP server command
tldr-pages/tldr pull request #7305
Opened 2021-10-30 05:04 UTC by laurixyz

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

**Version of the command being documented (if known):** 3.9.7

2021-10-30 05:43 UTC, mfrw approved these changes
LGTM

2021-10-30 13:40 UTC, navarroaxel requested changes

2021-10-30 13:40 UTC, navarroaxel commented on pages/common/python.md
> +- Start the built-in HTTP server (http://127.0.0.1:8000) in the current directory:
```suggestion
- Start the built-in HTTP server on port 8000 in the current directory:
```

2021-10-30 13:40 UTC, navarroaxel commented on pages/common/python.md
> +`python -m http.server`
```suggestion
`python -m {{http.server}}`
```

2021-10-31 05:07 UTC, navarroaxel approved these changes

2021-10-31 05:07 UTC, merged