bg: add Nepali translation
tldr-pages/tldr pull request #7309
Opened 2021-10-30 08:03 UTC by werewolf-65

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 12:37 UTC, navarroaxel requested changes

2021-10-30 12:37 UTC, navarroaxel commented on pages.ne/common/bg.md
> +> निलम्बित गरिएका कामहरुलाई (जस्तै `Ctrl + Z`) प्रयोग गरेर) पुन: सुरु गर्छ, अनि तिनीहरुलाई पृष्ठभूमिमा चलाइरहन्छ।
```suggestion
> निलम्बित गरिएका कामहरुलाई (जस्तै `Ctrl + Z` प्रयोग गरेर) पुन: सुरु गर्छ, अनि तिनीहरुलाई पृष्ठभूमिमा चलाइरहन्छ।
```

2021-10-30 19:02 UTC, navarroaxel approved these changes

2021-11-01 19:54 UTC, marchersimon approved these changes
Thanks @werewolf-65

2021-11-01 19:55 UTC, merged