cpuid: add Spanish translation
tldr-pages/tldr pull request #7310
Opened 2021-10-30 08:10 UTC by maegop

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 12:11 UTC, navarroaxel requested changes

2021-10-30 12:11 UTC, navarroaxel commented on pages.es/linux/cpuid.md
> +- Display information for all CPUs:
```suggestion
- Muestra información de todas los CPUs:
```

2021-10-30 12:11 UTC, navarroaxel commented on pages.es/linux/cpuid.md
> +- Muestra información sobre todas los CPUs:
```suggestion
- Muestra información sólo para la CPU actual:
```

2021-10-30 12:11 UTC, navarroaxel commented on pages.es/linux/cpuid.md
> +- Mostrar la información hexadecimal en bruto sin decodificar:
```suggestion
- Muestra la información hexadecimal en bruto sin decodificar:
```

2021-10-31 14:45 UTC, navarroaxel approved these changes

2021-11-02 16:33 UTC, marchersimon approved these changes

2021-11-02 16:33 UTC, merged