systemctl: add Spanish translation
tldr-pages/tldr pull request #7312
Opened 2021-10-30 08:13 UTC by maegop

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 12:01 UTC, navarroaxel requested changes
Remember that for translations you can send more than 1 translated page in 1 PR, just keep 1 commit per file and I recommend no more than 15 pages. This doesn't apply to the main «English» pages.

2021-10-30 12:01 UTC, navarroaxel commented on pages.es/linux/systemctl.cmd
> +- Iniciar/Parar/Reiniciar/Recargar un servicio:
```suggestion
- Inicia/Para/Reinicia/Recarga un servicio:
```

2021-10-30 12:01 UTC, navarroaxel commented on pages.es/linux/systemctl.cmd
> +- Mostrar el estado de una unidad:
```suggestion
- Muestra el estado de una unidad:
```

2021-10-30 12:01 UTC, navarroaxel commented on pages.es/linux/systemctl.cmd
> +- Habilitar/Deshabilitar una unidad para que se inicie en el arranque:
```suggestion
- Habilita/Deshabilita una unidad para que se inicie en el arranque:
```

2021-11-02 21:21 UTC, CleanMachine1 approved these changes

2021-11-18 10:33 UTC, navarroaxel approved these changes

2021-11-18 10:34 UTC, merged