vmstat: add Spanish translation
tldr-pages/tldr pull request #7314
Opened 2021-10-30 08:17 UTC by maegop

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 08:21 UTC, maegop reviewed
sugestion changed

2021-10-30 12:21 UTC, navarroaxel requested changes

2021-10-30 12:21 UTC, navarroaxel commented on pages.es/linux/vmstat.md
> +> Reporte de información sobre procesos, memoria, paginación, IO en bloque, traps, discos y actividad del CPU.
```suggestion
> Reporta información sobre procesos, memoria, paginación, IO en bloque, traps, discos y actividad del CPU.
```

2021-10-30 12:21 UTC, navarroaxel commented on pages.es/linux/vmstat.md
> +- Mostrar las estadísticas de la memoria virtual:
```suggestion
- Muestra las estadísticas de la memoria virtual:
```

2021-10-31 14:47 UTC, navarroaxel approved these changes

2021-11-02 16:36 UTC, marchersimon approved these changes

2021-11-02 16:37 UTC, merged