powerprofilesctl: add page
tldr-pages/tldr pull request #7315
Opened 2021-10-30 10:40 UTC by gotlougit

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 10:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7315) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7315) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7315) it.</sub>

2021-10-30 14:39 UTC, navarroaxel requested changes

2021-10-30 14:39 UTC, navarroaxel commented on pages/linux/powerprofilesctl.md
> +> Makes power profiles handling available over D-Bus.
```suggestion
> Make power profiles handling available over D-Bus.
```

2021-10-30 14:39 UTC, navarroaxel commented on pages/linux/powerprofilesctl.md
> +- Set a particular power profile:
```suggestion
- Set a specific power profile:
```

2021-10-30 14:39 UTC, navarroaxel commented on pages/linux/powerprofilesctl.md
> +`powerprofilesctl set {{arg_value}}`
We use this kind of placeholders:
```suggestion
`powerprofilesctl set {{profile_name}}`
```

2021-10-30 18:38 UTC, navarroaxel approved these changes

2021-11-01 12:39 UTC, marchersimon approved these changes
Thanks @gotlougit

2021-11-01 12:39 UTC, merged