neofetch: add pt_BR translation
tldr-pages/tldr pull request #7316
Opened 2021-10-30 13:41 UTC by andrecoco

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-30 13:45 UTC, navarroaxel requested changes

2021-10-30 13:45 UTC, navarroaxel commented on pages.pt_BR/common/neofetch.md
> +- Ocultar/Mostrar arquitetura do SO:
```suggestion
- Oculta/Mostra arquitetura do SO:
```

2021-10-30 13:45 UTC, navarroaxel commented on pages.pt_BR/common/neofetch.md
> +- Habilitar/desabilitar a marca da CPU na saída:
```suggestion
- Habilita/Desabilita a marca da CPU na saída:
```

2021-10-30 13:45 UTC, navarroaxel commented on pages.pt_BR/common/neofetch.md
> +- Volte à configuração padrão, ou crie-a se for a primeira vez que o programa for executado:
Please presente indicativo
```suggestion
- Volta à configuração padrão, ou crie-a se for a primeira vez que o programa for executado:
```

2021-10-30 13:45 UTC, navarroaxel commented on pages.pt_BR/common/neofetch.md
> +- Habilite/Desabilite uma linha de informação da saída, onde 'infoname' é o nome da função no arquivo de configuração, por exemplo, 'memory':
```suggestion
- Habilita/Desabilita uma linha de informação da saída, onde 'infoname' é o nome da função no arquivo de configuração, por exemplo, 'memory':
```

2021-10-30 14:24 UTC, navarroaxel approved these changes
Remember that you can apply all the suggestions in one commit, adding them to a batch <https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request>.
![image](https://user-images.githubusercontent.com/1536740/139536925-f3eae257-b4cc-471c-bbc5-6f79744239ec.png)

2021-11-01 12:41 UTC, marchersimon approved these changes
Thanks @andrecoco

2021-11-01 12:41 UTC, merged