shasum: add more information link
tldr-pages/tldr pull request #7321
Opened 2021-10-30 19:59 UTC by mere-teresa

See #6062

- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-10-30 20:02 UTC, navarroaxel requested changes

2021-10-30 20:02 UTC, navarroaxel commented on pages/common/shasum.md
> +> More information: https://man.archlinux.org/man/shasum.1perl
We prefer manned
```suggestion
> More information: <https://manned.org/shasum>.
```

2021-11-02 14:30 UTC, navarroaxel approved these changes

2021-11-02 14:36 UTC, pixelcmtd approved these changes

2021-11-02 15:11 UTC, mfrw approved these changes
LGTM

2021-11-02 15:11 UTC, merged