phar: add more information link
tldr-pages/tldr pull request #7322
Opened 2021-10-30 20:02 UTC by mere-teresa

See #6062

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2021-10-30 20:04 UTC, navarroaxel requested changes

2021-10-30 20:04 UTC, navarroaxel commented on pages/linux/phar.md
> +> More information: https://man.archlinux.org/man/phar.1
```suggestion
> More information: <https://manned.org/phar>.
```

2021-11-02 14:20 UTC, navarroaxel approved these changes

2021-11-02 21:11 UTC, CleanMachine1 approved these changes

2021-11-02 21:11 UTC, merged