locale:add file
tldr-pages/tldr pull request #7328
Opened 2021-10-31 01:27 UTC by Managor

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-31 21:15 UTC, navarroaxel requested changes

2021-11-01 01:21 UTC, Managor commented on pages/linux/locale.md
> +- List the global locale variables and their values:
Yes

2021-11-01 02:44 UTC, navarroaxel commented on pages/linux/locale.md
> +- List the global locale variables and their values:
Based on the man page, I think the example description should be something similar to this.
```suggestion
- List values for environment variables for each locale category setting:
```
But, I don't like this suggestion at all. Let's wait for another reviewer.

2021-11-01 11:33 UTC, marchersimon commented on pages/linux/locale.md
> +- List the global locale variables and their values:
How about
```suggestion
- List all global environment variables, describing the user's locale:
```

2021-11-01 12:49 UTC, Managor commented on pages/linux/locale.md
> +- List the global locale variables and their values:
Is the comma grammatically correct?

2021-11-01 14:43 UTC, marchersimon commented on pages/linux/locale.md
> +- List the global locale variables and their values:
Looks like you can write it with and without. I've edited my suggestion above to remove it.

2021-11-01 17:16 UTC, Managor commented on pages/linux/locale.md
> +- List the global locale variables and their values:
The one with the comma sounded like the act of listing is describing the locale while without it sounds more like the listed variables themselves are doing it.

2021-11-01 19:36 UTC, marchersimon approved these changes
Thanks @Managor

2021-11-17 20:50 UTC, CleanMachine1 approved these changes

2021-11-17 21:49 UTC, navarroaxel approved these changes

2021-11-17 21:49 UTC, merged