Powertop: add more information link
tldr-pages/tldr pull request #7345
Opened 2021-10-31 10:49 UTC by gotlougit

- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-10-31 14:42 UTC, navarroaxel requested changes

2021-10-31 14:42 UTC, navarroaxel commented on pages/linux/powertop.md
> +> More information: <https://01.org/powertop/>.
I think this is better source
```suggestion
> More information: <https://github.com/fenrus75/powertop>.
```

2021-10-31 19:09 UTC, navarroaxel approved these changes

2021-11-02 17:17 UTC, CleanMachine1 approved these changes

2021-11-02 17:17 UTC, merged