translate print.md to tr
tldr-pages/tldr pull request #7364
Opened 2021-11-01 11:40 UTC by yutyo

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-11-01 12:25 UTC, navarroaxel requested changes

2021-11-01 12:25 UTC, navarroaxel commented on pages.tr/linux/print.md
> +`print {{filename}}`
translate the placeholder `filename`

2021-11-12 19:39 UTC, CleanMachine1 approved these changes
Approval for after when axel's suggestions are added.

2021-12-27 08:09 UTC, yutyo commented on pages.tr/linux/print.md
> +`print {{filename}}`
done

> translate the placeholder `filename`

2021-12-27 12:14 UTC, navarroaxel approved these changes

2021-12-27 12:15 UTC, merged