dphys-swapfile: add page
tldr-pages/tldr pull request #7386
Opened 2021-11-07 15:13 UTC by MDecker-MobileComputing

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-11-07 17:00 UTC, CleanMachine1 requested changes

2021-11-07 17:00 UTC, CleanMachine1 commented on pages/linux/dphys-swapfile.md
> +- Create new swap file (e.g., after changes in file `/etc/dphys-swapfile `):
```suggestion
- Create a new swap file:
```

2021-11-08 12:19 UTC, navarroaxel commented on pages/linux/dphys-swapfile.md
> +> More information: <https://manpages.debian.org/jessie/dphys-swapfile/dphys-swapfile.8.en.html>.
This link will be on sync with the latest version
```suggestion
> More information: <https://manpages.debian.org/latest/dphys-swapfile/dphys-swapfile.html>.
```

2021-11-10 19:43 UTC, marchersimon approved these changes
Thanks @MDecker-MobileComputing

2021-11-10 19:47 UTC, navarroaxel approved these changes

2021-11-14 01:30 UTC, sbrl approved these changes
Thanks, @MDecker-MobileComputing!

2021-11-14 01:31 UTC, sbrl commented
Merging anyway, as @CleanMachine1's comments appear to have been addressed.

2021-11-14 01:32 UTC, merged