i3-scrot: add page
tldr-pages/tldr pull request #7400
Opened 2021-11-09 18:33 UTC by marchersimon

2021-11-10 09:02 UTC, navarroaxel commented on pages/linux/i3-scrot.md
> +> The default save location is `~/Pictures` and can be changes in `~/.config/i3-scrot.conf`.
```suggestion
> The default save location is `~/Pictures` and can be changed in `~/.config/i3-scrot.conf`.
```

2021-11-10 09:05 UTC, navarroaxel approved these changes

2021-11-25 21:34 UTC, sbrl approved these changes
Thanks, @marchersimon!

2021-11-25 21:35 UTC, sbrl requested changes

2021-11-25 21:35 UTC, sbrl commented on pages/linux/i3-scrot.md
> +`i3-scrot --secect-to-clibpoard`
According [to the source](https://gitlab.manjaro.org/packages/community/i3/i3-scrot/-/blob/master/i3-scrot#L55), I think this is a typo.
```suggestion
`i3-scrot --select-to-clibpoard`
```

2021-11-28 14:33 UTC, CleanMachine1 approved these changes

2021-11-28 14:33 UTC, merged