sed: fix -i example
tldr-pages/tldr pull request #7413
Opened 2021-11-12 09:05 UTC by Pakku

The empty argument '' causes the command to return an error.

- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

2021-11-12 09:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7413) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7413) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7413) it.</sub>

2021-11-12 09:45 UTC, marchersimon commented
Both variants work for me. Could you please provide the exact command you executed and the error you got?

2021-11-12 11:23 UTC, Pakku commented
Sure, this is what I'm getting. It appears that with the first variant, the second parameter is treated as the name of the file.

```
{▸} ~ sed -i '' 's/find/replace/g' example.txt
sed: can't read s/find/replace/g: No such file or directory
{▪} ~ sed -i 's/find/replace/g' example.txt   
{▸} ~ 
```

As a reference, [here](https://github.com/tldr-pages/tldr/blob/main/pages/common/sed.md) is without the empty parameter.

2021-11-12 11:28 UTC, marchersimon commented
My bad, I wrote `' ''s...` instead of `'' 's...`, which worked.

2021-11-12 11:28 UTC, marchersimon approved these changes
Thanks @Pakku

2021-11-12 11:40 UTC, navarroaxel approved these changes

2021-11-12 11:45 UTC, navarroaxel requested changes
I've tested the example and it's working properly. Are you using `macOS`?

2021-11-12 11:50 UTC, Pakku commented
Yes, i'm using macOS. Is it working for you with the empty parameter? For me, it is taking the second parameter as the file path instead of the find/replace string.

2021-11-12 14:02 UTC, marchersimon commented
@navarroaxel for me it also didn't work under Linux on bash and zsh with GNU sed 4.8

2021-11-13 22:12 UTC, navarroaxel commented
@Pakku Did you install `sed` using `brew install gnu-sed`?
GNU `sed` != macOS `sed`

2021-11-15 06:01 UTC, Pakku commented
You are right @navarroaxel ! It seems that i'm using GNU sed 😅 Sorry for the inconveniences!

2021-11-15 06:01 UTC, closed without merging