CONTRIBUTING: clarify guideline for new PRs
tldr-pages/tldr pull request #7450
Opened 2021-11-16 16:10 UTC by mfrw

PRs should be created against the `main` branch as base instead of
`master`

Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

Closes: #7449

2021-11-16 16:23 UTC, navarroaxel approved these changes

2021-11-17 05:39 UTC, blueskyson commented on CONTRIBUTING.md
> +*Note*: when submitting a new command, please base your PR against the `main` branch and don't forget to check if there's already a pull request in progress for it.
I think the description can be refined to the following:
```suggestion
*Note*: please base your PR against the `main` branch, and check if there's already a pull request in progress for it.
```

2021-11-17 13:59 UTC, blueskyson approved these changes

2021-11-17 14:47 UTC, mfrw commented
Probably can anyone request changes here to block merging, till we have signoff from other folks as well.
@navarroaxel ? maybe ? can you please block this :)

2021-11-17 14:48 UTC, navarroaxel requested changes
sure

2021-11-17 16:53 UTC, marchersimon approved these changes
Thanks @mfrw

2021-11-17 17:15 UTC, CleanMachine1 approved these changes
the word base could confuse some newcomers however LGTM

2021-11-17 17:28 UTC, marchersimon commented
What just happened there? Is this some kind of GitHub superpower I haven't heard of yet?
![image](https://user-images.githubusercontent.com/50295997/142251246-eac1b073-f412-4d30-8165-fa14d1e95b44.png)

2021-11-17 17:31 UTC, navarroaxel commented
@marchersimon he removed my block to merge :laughing:

2021-11-17 17:32 UTC, CleanMachine1 commented
@marchersimon 

Cant tell which part of what you mean so heres both just in case :shrug: 

I removed the review from pressing "changes requested" in the merge section of this page, then the "..."  and dismissed.

The "merge block" is simply a review where this is selected

```
Request changes

Submit feedback that must be addressed before merging.
```

Not really a "merge block" however its a good alternative!

2021-11-17 17:34 UTC, marchersimon commented
I didn't know it was possible to dismiss requested changes 😅 
And I also didn't know about merge blocks. Thanks for the explanation.

2021-11-17 18:11 UTC, sbrl approved these changes
Seems good to me.

2021-11-17 18:14 UTC, mfrw commented
Thank you all. Merging now :)

2021-11-17 18:15 UTC, merged