ytfzf: add page
tldr-pages/tldr pull request #7458
Opened 2021-11-18 13:45 UTC by kyteinsky

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 1.2.0

2021-11-18 21:16 UTC, navarroaxel submitted a review, later dismissed

2021-11-18 21:16 UTC, navarroaxel commented on pages/linux/ytfzf.md
> +`ytfzf -t {{search text}}`
We prefer long arguments
```suggestion
`ytfzf --show-thumbnails {{search text}}`
```

2021-11-18 21:16 UTC, navarroaxel commented on pages/linux/ytfzf.md
> +`ytfzf -mal {{search text}}`
We use `snake_case` for placeholders
```suggestion
`ytfzf --audio-only --auto-select --loop {{search_pattern}}`
```

2021-11-18 21:16 UTC, navarroaxel commented on pages/linux/ytfzf.md
> +`ytfzf -dH`
```suggestion
`ytfzf --download --choose-from-history`
```

2021-11-18 21:16 UTC, navarroaxel commented on pages/linux/ytfzf.md
> +`ytfzf -mA {{search text}}`
```suggestion
`ytfzf --audio-only --select-all {{search_pattern}}`
```

2021-11-18 21:16 UTC, navarroaxel commented on pages/linux/ytfzf.md
> +`ytfzf -TD {{search text}}`
```suggestion
`ytfzf --trending --ext-menu {{search_pattern}}`
```

2021-11-18 21:16 UTC, navarroaxel commented on pages/linux/ytfzf.md
> +`ytfzf -P {{search text}}`
```suggestion
`ytfzf --peertube {{search_pattern}}`
```

2021-11-19 04:59 UTC, kyteinsky commented
I'll commit the changes, but was just curious why use the long args when short ones are easier to use and suit tldr better?

2021-11-19 10:37 UTC, navarroaxel commented
> I'll commit the changes, but was just curious why use the long args when short ones are easier to use and suit tldr better?

1. Easier to infer what does each argument in the example without read the man page.
2. Easier to remember than two or three random letters.

2021-11-19 13:50 UTC, kyteinsky commented
Yeah makes sense. After all, they'll be looking at the thing for the first time, so long arguments would be good.

2021-11-25 20:57 UTC, sbrl requested changes
Thanks for the new page! I've left some comments below for you to review.

2021-11-25 20:57 UTC, sbrl commented on pages/linux/ytfzf.md
> +- Play only audio of first item in loop:
Perhaps this will read better?
```suggestion
- Play only the audio of the first item in a loop:
```

2021-11-25 20:57 UTC, sbrl commented on pages/linux/ytfzf.md
> +- Search videos in YouTube and display the thumbnails:
Perhaps this will read better?
```suggestion
- Search for videos on YouTube and display the thumbnails:
```

2021-11-25 20:57 UTC, sbrl commented on pages/linux/ytfzf.md
> +- Download a video from history:
Perhaps this will read better?
```suggestion
- Download a video from the history:
```

2021-11-25 20:57 UTC, sbrl commented on pages/linux/ytfzf.md
> +- Play all the music found in one search:
Perhaps this will read better?
```suggestion
- Play all the music found in a search:
```

2021-11-25 20:57 UTC, sbrl commented on pages/linux/ytfzf.md
> +- See the trending videos in external menu:
Perhaps this will read better?
```suggestion
- See the trending videos in an external menu:
```

2021-11-25 21:05 UTC, kyteinsky commented
Ahh those articles :neutral_face:

2021-11-25 21:12 UTC, kyteinsky commented
Please squish the commits.

2021-11-25 21:29 UTC, sbrl approved these changes
Thanks, @kyteinsky!

Yeah, we have a special button in the GitHub web interface to squash on merge :D

2021-11-25 21:30 UTC, kyteinsky commented
> Yeah, we have a special button in the GitHub web interface to squash on merge :D

That's nice to know :)

2021-11-28 14:34 UTC, CleanMachine1 approved these changes

2021-11-28 14:35 UTC, merged