typeorm: add page
tldr-pages/tldr pull request #7474
Opened 2021-11-23 02:28 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 0.2.41

2021-11-27 06:49 UTC, blueskyson approved these changes

2021-11-28 14:32 UTC, CleanMachine1 approved these changes

2021-12-02 01:59 UTC, sbrl requested changes

2021-12-02 01:59 UTC, sbrl commented on pages/common/typeorm.md
> +> A JavaScript ORM that can run in Node.js, browsers, Cordova, Ionic, React Native, NativeScript, and Electron platforms.
Tiny suggestion
```suggestion
> A JavaScript ORM that can run on Node.js, browser, Cordova, Ionic, React Native, NativeScript, and Electron platforms.
```

2021-12-02 01:59 UTC, sbrl commented on pages/common/typeorm.md
> +- Generate initial TypeORM project structure:
Perhaps this will read better?
```suggestion
- Generate a new initial TypeORM project structure:
```

2021-12-02 01:59 UTC, sbrl commented on pages/common/typeorm.md
> +- Create a migration file with the SQL sentences to update the schema:
Never heard of an SQL sentence before. Did you mean `statement` here instead?

2021-12-02 01:59 UTC, sbrl commented on pages/common/typeorm.md
> +- Create a new entity file into a specific directory:
Perhaps this will read better?
```suggestion
- Create a new entity file in a specific directory:
```

2021-12-02 01:59 UTC, sbrl commented on pages/common/typeorm.md
> +- Display the SQL sentences to be executed by `typeorm schema:sync` on the default connection:
Again with the SQL sentences. Is this some kind of tool-specific technical language? 'cause I certainly haven't heard of it elsewhere.

2021-12-02 01:59 UTC, sbrl commented on pages/common/typeorm.md
> +- Execute a specific SQL sentence on the default connection:
Same here.

2021-12-07 20:45 UTC, sbrl approved these changes
Thanks, @navarroaxel!

2021-12-07 20:45 UTC, merged