vegeta: french traduction
tldr-pages/tldr pull request #7488
Opened 2021-11-28 19:46 UTC by melvinxeu

- [X The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-12-07 21:19 UTC, sbrl approved these changes
Don't speak the language, but the syntax looks fine to me!

Thanks :slightly_smiling_face:

2021-12-23 13:35 UTC, navarroaxel requested changes

2021-12-23 13:35 UTC, navarroaxel commented on pages.fr/common/vegeta.md
> +- Lancer une attaque d'une durée de 30 secondes:
```suggestion
- Lancer une attaque d'une durée de 30 secondes :
```

2021-12-23 13:35 UTC, navarroaxel commented on pages.fr/common/vegeta.md
> +> Plus d'informations: <https://github.com/tsenart/vegeta>.
```suggestion
> Plus d'informations : <https://github.com/tsenart/vegeta>.
```

2021-12-23 13:35 UTC, navarroaxel commented on pages.fr/common/vegeta.md
> +- Lancez une attaque sur un serveur avec un certificat HTTPS auto-signé.:
```suggestion
- Lancez une attaque sur un serveur avec un certificat HTTPS auto-signé :
```

2021-12-23 13:35 UTC, navarroaxel commented on pages.fr/common/vegeta.md
> +- Lancer une attaque et reporter les résultats sur un graphique (latence en fonction du temps):
```suggestion
- Lancer une attaque et reporter les résultats sur un graphique (latence en fonction du temps) :
```

2021-12-23 13:35 UTC, navarroaxel commented on pages.fr/common/vegeta.md
> +- Lancer une attaque et afficher un rapport:
```suggestion
- Lancer une attaque et afficher un rapport :
```

2021-12-23 13:35 UTC, navarroaxel commented on pages.fr/common/vegeta.md
> +- Lancer une attaque avec un taux de 10 demandes par seconde:
```suggestion
- Lancer une attaque avec un taux de 10 demandes par seconde :
```

2021-12-23 13:35 UTC, navarroaxel commented on pages.fr/common/vegeta.md
> +- Lancer une attaque contre plusieurs URL à partir d'un fichier:
```suggestion
- Lancer une attaque contre plusieurs URL à partir d'un fichier :
```

2021-12-23 13:36 UTC, navarroaxel approved these changes

2021-12-23 13:37 UTC, merged