nitrogen: init nitrogen commands
tldr-pages/tldr pull request #7492
Opened 2021-11-29 03:53 UTC by Dale-Muccignat

- [ x] The page (if new), does not already exist in the repository.
- x[ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ x] The page has 8 or fewer examples.
- [ x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-11-29 03:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7492) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7492) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7492) it.</sub>

2021-11-29 04:48 UTC, einverne requested changes
hi @Dale-Muccignat thank you for the new page. I've just added a small suggestion.

2021-11-29 04:48 UTC, einverne commented on pages/linux/nitrogen.md
> +`nitrogen {{/path/to/directory/}}`
```suggestion
`nitrogen {{path/to/directory/}}`
```

We do not use the leading `/` here.

2021-11-29 04:48 UTC, einverne commented on pages/linux/nitrogen.md
> +`nitrogen --set-auto {{/path/to/file}}`
```suggestion
`nitrogen --set-auto {{path/to/file}}`
```

2021-11-29 04:55 UTC, einverne approved these changes
Cool, thanks.

2021-11-29 11:04 UTC, navarroaxel commented on pages/linux/nitrogen.md
> +> More information: <https://github.com/l3ib/nitrogen/>.
```suggestion
> More information: <https://github.com/l3ib/nitrogen>.
```

2021-11-29 11:04 UTC, navarroaxel commented on pages/linux/nitrogen.md
> +`nitrogen {{path/to/directory/}}`
```suggestion
`nitrogen {{path/to/directory}}`
```

2021-11-29 11:04 UTC, navarroaxel commented on pages/linux/nitrogen.md
> +- View and set the desired wallpaper/s from a specific directory:
The `/` only adds noise
```suggestion
- View and set the wallpapers from a specific directory:
```

2021-11-29 11:04 UTC, navarroaxel commented on pages/linux/nitrogen.md
> +`nitrogen --restore &`
The `&` is to send the command to the background? it's not part of the app params itself.
```suggestion
`nitrogen --restore`
```

2021-11-29 11:04 UTC, navarroaxel commented on pages/linux/nitrogen.md
> +> Nitrogen is a fast and lightweight desktop background browser and setter for X Window.
```suggestion
> Desktop background browser and setter for X Window.
```

2021-11-29 23:02 UTC, Dale-Muccignat commented
Thank you for your feedback and reviews thus far. They are all good points.

2021-11-30 21:26 UTC, sbrl approved these changes
Thanks, @Dale-Muccignat!

2021-11-30 21:26 UTC, merged