abbr: add page
tldr-pages/tldr pull request #7508
Opened 2021-12-04 15:11 UTC by JohannesPertl

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known): 3.3.1

2021-12-04 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7508) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7508) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7508) it.</sub>

2021-12-05 13:35 UTC, EmilySeville7cfg requested changes
It's better to use long options to make tldr pages more readable and memorizable.

2021-12-05 13:35 UTC, EmilySeville7cfg commented on pages/linux/abbr.md
> +`abbr -a -g gco git checkout`
It's better to use long options to make tldr pages more readable and memorizable:

```suggestion
`abbr --add gco git checkout`
```

Maybe better to remove `-g` flag to make abbreviation universal and automatically visible in other shell sessions.

2021-12-05 21:25 UTC, navarroaxel commented on pages/linux/abbr.md
> +> Manages abbreviations for the fish shell.
```suggestion
> Manage abbreviations for the fish shell.
```

2021-12-05 21:25 UTC, navarroaxel commented on pages/linux/abbr.md
> +> User-defined words are replaced with longer phrases after they are entered.
```suggestion
> User-defined words are replaced with longer phrases after they are entered.
```

2021-12-05 21:25 UTC, navarroaxel commented on pages/linux/abbr.md
> +`abbr --rename gco gch`
I think this is more clear:
```suggestion
`abbr --rename {{old_name}} {{new_name}}`
```

2021-12-05 21:25 UTC, navarroaxel commented on pages/linux/abbr.md
> +`abbr --add gco git checkout`
Perhaps this better
```suggestion
`abbr --add {{abbreviation_name}} {{command}} {{command_arguments}}`
```

2021-12-05 21:25 UTC, navarroaxel commented on pages/linux/abbr.md
> +`abbr --erase gco`
```suggestion
`abbr --erase {{abbreviation_name}}`
```

2021-12-05 21:25 UTC, navarroaxel commented on pages/linux/abbr.md
> +`ssh another_host abbr -s | source`
We prefer long arguments if available
```suggestion
`ssh {{host_name}} abbr --show | source`
```

2021-12-05 21:25 UTC, navarroaxel commented on pages/linux/abbr.md
> +- Import the abbreviations defined on another_host over SSH.:
```suggestion
- Import the abbreviations defined on another host over SSH:
```

2021-12-08 11:58 UTC, navarroaxel approved these changes

2021-12-24 23:09 UTC, sbrl approved these changes
While that last command demonstrates the functionality of other commands, it's very cool so it can stay :-)

Great job!

2021-12-24 23:09 UTC, merged