msiexec: Add Indonesian translation
tldr-pages/tldr pull request #7537
Opened 2021-12-14 08:20 UTC by reinhart1010

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 5.0.22000.1

Added  Indonesian translation to #7513

2021-12-16 11:12 UTC, navarroaxel requested changes

2021-12-16 11:12 UTC, navarroaxel commented on pages.id/windows/msiexec.md
> +> Informasi lebih lanjut: <https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec>.
```suggestion
> Informasi lebih lanjut: <https://docs.microsoft.com/windows-server/administration/windows-commands/msiexec>.
```

2021-12-16 11:12 UTC, navarroaxel commented on pages.id/windows/msiexec.md
> +- Memasang sebuah program melalui file MSI:
I'm not sure which verb mood are you using, but the example descriptions should be in indicative mood.

2021-12-18 19:43 UTC, navarroaxel approved these changes

2021-12-22 21:31 UTC, CleanMachine1 approved these changes

2021-12-30 10:57 UTC, merged