spctl: add page
tldr-pages/tldr pull request #7565
Opened 2021-12-21 08:28 UTC by timphan92

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2021-12-21 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7565) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7565) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7565) it.</sub>

2021-12-21 12:22 UTC, navarroaxel requested changes

2021-12-21 12:22 UTC, navarroaxel commented on pages/osx/spctl.md
> +`spctl --add --label "RuleName" {{path/to/file}}`
We use `snake_case` for placeholders
```suggestion
`spctl --add --label "{{rule_name}}" {{path/to/file}}`
```

2021-12-21 12:22 UTC, navarroaxel commented on pages/osx/spctl.md
> +> Utility for managing Gatekeeper in OS X
```suggestion
> Utility for managing Gatekeeper in macOS.
```

2021-12-21 12:22 UTC, navarroaxel commented on pages/osx/spctl.md
> +- Turn off gatekeeper:
```suggestion
- Turn off Gatekeeper:
```

2021-12-21 12:22 UTC, navarroaxel commented on pages/osx/spctl.md
> +- Turn on gatekeeper:
```suggestion
- Turn on Gatekeeper:
```

2021-12-22 07:42 UTC, blueskyson approved these changes
Look good to me.

2021-12-22 10:25 UTC, navarroaxel approved these changes

2021-12-22 10:25 UTC, navarroaxel commented on pages/osx/spctl.md
> +- Add a rule to allow an application to run (Labeling of rule is optional):
```suggestion
- Add a rule to allow an application to run (labeling of rule is optional):
```

2021-12-22 10:26 UTC, merged