fr : docker : explain how to display the images already downloaded
tldr-pages/tldr pull request #7567
Opened 2021-12-21 10:27 UTC by Raizo62

Hi

In pages.fr/common/docker.md,  add how to display the images already downloaded : 
`docker images`

2021-12-21 10:34 UTC, Raizo62 commented
I believe that this command is usefull.
I must remove a other command ? Which ? the first (`docker ps`) because it is include in the second (`docker ps -a`)

2021-12-21 12:05 UTC, navarroaxel requested changes
Hi @Raizo62, we have 2 issues here:
1. For us, the translation pages are just translation from the main English pages. Because it's harder to maintain, and keep in sync if every language adds editions. So, you should send your edit in the main page first.
2. We have an strict rule that all pages can have up to 8 examples.

I think `docker images` is a basic command, and for this page we can merge `ps` and `ps -a` examples to add the `images` example.

2021-12-21 21:46 UTC, sbrl commented
We already have a more detailed page for `docker images` here: <https://github.com/tldr-pages/tldr/blob/main/pages/common/docker-images.md>

The page for the top-level `docker` commands is one of those pages that has *far* too much functionality to completely represent in a single page (similar to `git` for example), so we have sub-pages for each subcommand thereof.

2021-12-22 07:25 UTC, Raizo62 commented
> We already have a more detailed page for docker images here: https://github.com/tldr-pages/tldr/blob/main/pages/common/docker-images.md

Yes, but we look the page "docker-images.md" only if we already know that we must use the parameter "images" to display the list of downloaded images. This is not obvious.

2021-12-22 07:31 UTC, blueskyson approved these changes
Look good to me.

2021-12-22 10:29 UTC, navarroaxel commented on pages/common/docker.md
>  `docker ps -a`
```suggestion
`docker ps --all`
```

2021-12-22 10:29 UTC, navarroaxel commented on pages.fr/common/docker.md
>  `docker ps -a`
```suggestion
`docker ps --all`
```

2021-12-22 10:37 UTC, navarroaxel approved these changes

2021-12-28 09:26 UTC, einverne approved these changes
Looks good, thanks.

2021-12-29 22:49 UTC, CleanMachine1 approved these changes

2021-12-30 12:37 UTC, merged