add page for yt-dlp
tldr-pages/tldr pull request #7604
Opened 2022-01-02 12:13 UTC by n14s

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-01-02 12:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7604) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7604) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7604) it.</sub>

2022-01-02 13:40 UTC, navarroaxel requested changes

2022-01-02 13:40 UTC, navarroaxel commented on pages/common/yt-dlp.md
> +`yt-dlp -f "bv*+ba/b "https://www.youtube.com/watch?v=oHg5SJYRHA0"`
We prefer long arguments if available
```suggestion
`yt-dlp --format "{{bv*+ba/b}}" "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"`
```

2022-01-02 13:40 UTC, navarroaxel commented on pages/common/yt-dlp.md
> +`yt-dlp -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re"`
```suggestion
`yt-dlp --output "{{%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s}}" "{{https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re}}"`
```

2022-01-02 13:40 UTC, navarroaxel commented on pages/common/yt-dlp.md
> +> More information: <https://github.com/yt-dlp/yt-dlp>
```suggestion
> More information: <https://github.com/yt-dlp/yt-dlp>.
```

2022-01-02 18:13 UTC, n14s commented on pages/common/yt-dlp.md
> +`yt-dlp -f "bv*+ba/b "https://www.youtube.com/watch?v=oHg5SJYRHA0"`
Missed that, thanks alot!

2022-01-02 19:53 UTC, blueskyson commented on pages/common/yt-dlp.md
> +`yt-dlp "https://www.youtube.com/watch?v=oHg5SJYRHA0"`
```suggestion
- Download a video or playlist (with the default options from command below):

`yt-dlp "https://www.youtube.com/watch?v=oHg5SJYRHA0"`
```

2022-01-02 19:53 UTC, blueskyson commented on pages/common/yt-dlp.md
> +`yt-dlp --format "{{bv*+ba/b}}" "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"`
```suggestion
- Download best format that contains video, and if it doesn't already have an audio stream, merge it with best audio-only format (Default):

`yt-dlp --format "{{bv*+ba/b}}" "{{https://www.youtube.com/watch?v=oHg5SJYRHA0}}"`
```

2022-01-02 19:53 UTC, blueskyson commented on pages/common/yt-dlp.md
> +`yt-dlp --output "{{%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s}}" "{{https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re}}"`
```suggestion
- Download YouTube playlist videos in separate directory indexed by video order in a playlist:

`yt-dlp --output "{{%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s}}" "{{https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re}}"`
```

2022-01-02 19:53 UTC, blueskyson commented on pages/common/yt-dlp.md
> +`yt-dlp -o "%(upload_date>%Y)s/%(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re"`
```suggestion
- Download YouTube playlist videos in separate directories according to their uploaded years:

`yt-dlp -o "%(upload_date>%Y)s/%(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re"`
```

2022-01-02 19:53 UTC, blueskyson commented on pages/common/yt-dlp.md
> +`yt-dlp -o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/user/TheLinuxFoundation/playlists"`
```suggestion
- Download all playlists of YouTube channel/user and keep each playlist in separate directories:

`yt-dlp -o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/user/TheLinuxFoundation/playlists"`
```

2022-01-02 19:53 UTC, blueskyson commented on pages/common/yt-dlp.md
> +`yt-dlp -u user -p password -P "~/MyVideos" -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" "https://www.udemy.com/java-tutorial"`
```suggestion
- Download Udemy course and keep each chapter in separate directories under "~/MyVideos":

`yt-dlp -u user -p password -P "~/MyVideos" -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" "https://www.udemy.com/java-tutorial"`
```

2022-01-02 19:53 UTC, blueskyson commented on pages/common/yt-dlp.md
> +`yt-dlp -P "C:/MyVideos" -o "%(series)s/%(season_number)s - %(season)s/%(episode_number)s - %(episode)s.%(ext)s" "https://videomore.ru/kino_v_detalayah/5_sezon/367617"`
```suggestion
- Download entire series season and keep each series and each season in separate directories under "C:/MyVideos":

`yt-dlp -P "C:/MyVideos" -o "%(series)s/%(season_number)s - %(season)s/%(episode_number)s - %(episode)s.%(ext)s" "https://videomore.ru/kino_v_detalayah/5_sezon/367617"`
```

2022-01-07 21:58 UTC, closed without merging

2022-01-07 21:59 UTC, navarroaxel commented
Oh, you deleted the branch. Just a rebase interactive, commit amend and a push force you could fix the author stuff.