airportd, automountd, coreautha, coreauthd, nfcd: add page
tldr-pages/tldr pull request #7608
Opened 2022-01-03 03:10 UTC by pixelcmtd

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

**Version of the command being documented (if known):**
Darwin 21.2, macOS 12.1

2022-01-31 11:53 UTC, navarroaxel commented
@pixelcmtd we need links to merge this.

2022-01-31 12:01 UTC, navarroaxel commented on pages/osx/automountd.md
> +> It should not be invoked manually.
```suggestion
> It should not be invoked manually.
> More information: <https://www.manpagez.com/man/8/automountd/>.
```

2022-01-31 12:18 UTC, pixelcmtd commented
> we need links to merge this.

@navarroaxel why? is there some new rule that i'm not aware of?

2022-01-31 12:21 UTC, navarroaxel commented
> @navarroaxel why? is there some new rule that i'm not aware of?

@pixelcmtd We planned to add the [links rule](https://github.com/tldr-pages/tldr/issues/5510#issuecomment-816520051) to the linter but before we want to add all missing links.

2022-01-31 17:52 UTC, pixelcmtd commented
> We planned to add the [links rule](https://github.com/tldr-pages/tldr/issues/5510#issuecomment-816520051) to the linter but before we want to add all missing links.

@navarroaxel So half of #6596 is now basically impossible? That helps.

2022-01-31 17:58 UTC, navarroaxel approved these changes

2022-02-01 09:14 UTC, EmilySeville7cfg requested changes

2022-02-01 09:14 UTC, EmilySeville7cfg commented on pages/osx/coreautha.md
> +> It should not be invoked manually.
```suggestion
> It should not be invoked manually.
> See also: `coreauthd`.
```

2022-02-01 09:14 UTC, EmilySeville7cfg commented on pages/osx/coreauthd.md
> +> It should not be invoked manually.
```suggestion
> It should not be invoked manually.
> See also: `coreautha`.
```

2022-02-01 15:02 UTC, pixelcmtd commented
> [Preferably one line; two are acceptable if necessary.](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#layout)

@EmilySeville7cfg

2022-02-01 16:12 UTC, EmilySeville7cfg approved these changes

2022-02-01 16:46 UTC, navarroaxel requested changes

2022-02-01 16:46 UTC, navarroaxel commented on pages/osx/coreauthd.md
> +> It should not be invoked manually.
We always use the `see also` in the 2nd line
```suggestion
> A system daemon providing the `LocalAuthentication` framework.
> It should not be invoked manually. See also: `coreautha`.
```

2022-02-01 16:46 UTC, navarroaxel commented on pages/osx/coreautha.md
> +> It should not be invoked manually.
```suggestion
> A system agent providing the `LocalAuthentication` framework.
> It should not be invoked manually. See also: `coreauthd`.
```

2022-02-01 20:21 UTC, pixelcmtd commented
That's so unlogical in this case tho

2022-02-01 20:38 UTC, navarroaxel approved these changes

2022-02-01 20:38 UTC, merged