apt, dpkg: add Indonesian translation
tldr-pages/tldr pull request #7614
Opened 2022-01-05 15:37 UTC by azraeljd

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-01-05 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7614) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7614) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7614) it.</sub>

2022-01-05 18:37 UTC, navarroaxel approved these changes

2022-01-05 18:37 UTC, navarroaxel commented on pages.id/linux/dpkg.md
> +`dpkg -S {{nama file}}`
```suggestion
`dpkg -S {{nama_file}}`
```

2022-01-06 02:41 UTC, reinhart1010 requested changes

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +> Pengganti apt-get yang direkomendasikan ketika digunakan secara interaktif di Ubuntu versi 16.04 atau yang lebih baru.
```suggestion
> Pengganti `apt-get` yang direkomendasikan ketika digunakan secara interaktif di Ubuntu versi 16.04 atau yang lebih baru.
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +`apt search {{paket}}`
```suggestion
`apt search {{nama_atau_deskripsi_paket}}`
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +- Mencari paket:
```suggestion
- Mencari paket yang tersedia dengan nama atau deskripsi tertentu:
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +- Memperlihatkan paket yang tersedia:
```suggestion
- Memperlihatkan informasi tentang suatu paket:
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +`apt show {{paket}}`
```suggestion
`apt show {{nama_paket}}`
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +`sudo apt install {{paket}}`
```suggestion
`sudo apt install {{nama_paket}}`
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +`sudo apt remove {{paket}}`
```suggestion
`sudo apt remove {{nama_paket}}`
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +- Memperbarui paket yang terinstal ke versi terbaru:
```suggestion
- Memperbarui seluruh paket yang terpasang ke versi terbaru:
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +- Menghapus sebuah paket (menggunakan `purge` juga menghapus file konfigurasi):
```suggestion
- Menghapus sebuah paket (gunakan `sudo apt purge` untuk menghapus paket beserta file konfigurasinya):
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +- Memperlihatkan daftar semua paket:
```suggestion
- Memperlihatkan daftar semua paket yang tersedia di dalam repositori:
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/apt.md
> +- Memperlihatkan daftar paket yang terinstal:
```suggestion
- Memperlihatkan daftar paket yang telah terpasang:
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/dpkg.md
> +- Instal sebuah paket:
```suggestion
- Memasang paket dari sebuah file DEB:
```

2022-01-06 02:41 UTC, reinhart1010 commented on pages.id/linux/dpkg.md
> +- Menghapus sebuah paket:
```suggestion
- Menghapus pemasangan sebuah paket:
```

2022-01-06 05:24 UTC, reinhart1010 approved these changes
Thanks

2022-01-06 13:03 UTC, merged