mkfs.ext4: add Indonesian translation
tldr-pages/tldr pull request #7623
Opened 2022-01-07 09:54 UTC by azraeljd

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-01-07 10:05 UTC, navarroaxel approved these changes

2022-01-08 07:48 UTC, blueskyson approved these changes

2022-01-08 13:41 UTC, reinhart1010 requested changes
Here's a minor edit for you

2022-01-08 13:41 UTC, reinhart1010 commented on pages.id/linux/mkfs.ext4.md
> +- Membuat sistem file ext4 didalam partisi 1 di perangkat b (`sdb1`):
```suggestion
- Membuat sistem file ext4 di dalam partisi 1 di perangkat B (`sdb1`):
```

2022-01-09 06:01 UTC, reinhart1010 approved these changes
Thanks!

2022-01-09 06:01 UTC, merged