2to3: add french translation
tldr-pages/tldr pull request #7633
Opened 2022-01-09 16:15 UTC by Nico385412

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-01-09 17:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +> Plus d'informations: <https://docs.python.org/3/library/2to3.html>.
We use this French grammar rule:
```suggestion
> Plus d'informations : <https://docs.python.org/3/library/2to3.html>.
```

2022-01-10 02:43 UTC, navarroaxel requested changes

2022-01-10 02:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +- Afficher les changements qui seront effectués sans les effectuer (coup d'essai):
Here too
```suggestion
- Afficher les changements qui seront effectués sans les effectuer (coup d'essai) :
```

2022-01-10 02:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +- Convertir un fichier Python 2 en Python 3:
```suggestion
- Convertir un fichier Python 2 en Python 3 :
```

2022-01-10 02:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +- Afficher une liste de toutes les fonctionnalités de language qui peuvent être converties de Python 2 vers Python 3:
```suggestion
- Afficher une liste de toutes les fonctionnalités de language qui peuvent être converties de Python 2 vers Python 3 :
```

2022-01-10 02:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +- Convertir toutes les fonctionnalités de Python 2 vers Python 3 sauf exceptions spécifiques:
```suggestion
- Convertir toutes les fonctionnalités de Python 2 vers Python 3 sauf exceptions spécifiques :
```

2022-01-10 02:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +- Convertir des fonctionnalités spécifiques de Python 2 vers Python 3:
```suggestion
- Convertir des fonctionnalités spécifiques de Python 2 vers Python 3 :
```

2022-01-10 02:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +- Convertir tous les fichier Python2 vers Python 3 dans un dossier:
```suggestion
- Convertir tous les fichier Python2 vers Python 3 dans un dossier :
```

2022-01-10 02:43 UTC, navarroaxel commented on pages.fr/common/2to3.md
> +- Executer 2to3 avec plusieurs fil d'exécution:
```suggestion
- Executer 2to3 avec plusieurs fil d'exécution :
```

2022-01-10 11:40 UTC, navarroaxel approved these changes

2022-01-12 12:52 UTC, blueskyson approved these changes

2022-01-12 12:52 UTC, merged