xfreerdp: add /sound example
tldr-pages/tldr pull request #7634
Opened 2022-01-09 19:57 UTC by HazemBZ

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 2.4.1

2022-01-09 19:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7634) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7634) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7634) it.</sub>

2022-01-09 19:59 UTC, navarroaxel requested changes

2022-01-09 19:59 UTC, navarroaxel commented on pages/linux/xfreerdp.md
> +`xfreerdp /u:{{username}} /p:{{password}} /v:{{ip_address}} /sound:sys:alsa`
```suggestion
`xfreerdp /u:{{username}} /p:{{password}} /v:{{ip_address}} /sound:{{sys:alsa}}`
```

2022-01-09 19:59 UTC, navarroaxel commented on pages/linux/xfreerdp.md
> +- Connect to a FreeRDP server and Activate audio output redirection using device sys:alsa
```suggestion
- Connect to a FreeRDP server and activate audio output redirection using `sys:alsa` device:
```

2022-01-09 20:29 UTC, navarroaxel approved these changes

2022-01-10 05:25 UTC, mfrw approved these changes
Thank you @HazemBZ for your contribution.
LGTM

2022-01-10 05:25 UTC, merged