distrobox: add page
tldr-pages/tldr pull request #7638
Opened 2022-01-10 17:28 UTC by misobarisic

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

**Version of the command being documented (if known): 1.2.10**

2022-01-10 17:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7638) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7638) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7638) it.</sub>

2022-01-10 20:54 UTC, navarroaxel requested changes

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-enter.md
> +> Manual page viewer for distrobox.
```suggestion
> Manual page viewer for distrobox.
> More information: <https://distrobox.privatedns.org>.
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-create.md
> +> Manual page viewer for distrobox.
```suggestion
> Manual page viewer for distrobox.
> More information: <https://distrobox.privatedns.org>.
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-rm.md
> +> Manual page viewer for distrobox.
```suggestion
> Manual page viewer for distrobox.
> More information: <https://distrobox.privatedns.org>.
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-rm.md
> +`distrobox-rm container-name`
We use `snake_case` for placeholders
```suggestion
`distrobox-rm {{container_name}}`
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-rm.md
> +`distrobox-rm container-name --force`
```suggestion
`distrobox-rm {{container_name}} --force`
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-list.md
> +- List all distrobox containers (verbose):
```suggestion
- List all distrobox containers with verbose information:
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-create.md
> +`distrobox-create my-alpine-container --image alpine`
```suggestion
`distrobox-create {{container_name}} --image {{alpine}}`
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-create.md
> +`distrobox-create --clone ubuntu-container ubuntu-copy`
```suggestion
`distrobox-create --clone {{container_name}} {{cloned_container_name}}`
```

2022-01-10 20:54 UTC, navarroaxel commented on pages/linux/distrobox-create.md
> +- Create a distrobox:
```suggestion
- Create a distrobox using the Alpine image:
```

2022-01-11 12:20 UTC, navarroaxel commented
Hi @misobarisic, you marked my suggestions as resolved, but I can't see the changes applied.

2022-01-11 17:30 UTC, navarroaxel approved these changes

2022-01-12 11:28 UTC, navarroaxel requested changes

2022-01-12 11:28 UTC, navarroaxel commented on pages/linux/distrobox-create.md
> +> More information: <https://distrobox.privatedns.org>
```suggestion
> More information: <https://distrobox.privatedns.org>.
```

2022-01-12 11:28 UTC, navarroaxel commented on pages/linux/distrobox-enter.md
> +> More information: <https://distrobox.privatedns.org>
```suggestion
> More information: <https://distrobox.privatedns.org>.
```

2022-01-12 11:28 UTC, navarroaxel commented on pages/linux/distrobox-list.md
> +> More information: <https://distrobox.privatedns.org>
```suggestion
> More information: <https://distrobox.privatedns.org>.
```

2022-01-12 11:28 UTC, navarroaxel commented on pages/linux/distrobox-rm.md
> +> More information: <https://distrobox.privatedns.org>
```suggestion
> More information: <https://distrobox.privatedns.org>.
```

2022-01-15 13:15 UTC, sbrl commented on pages/linux/distrobox-create.md
> +> Manual page viewer for distrobox.
All these descriptions for these pages are the same. The description should describe what the command does.

2022-01-17 21:51 UTC, misobarisic commented
All pages have been updated with their corresponding descriptions.

2022-01-18 05:56 UTC, navarroaxel approved these changes

2022-01-18 12:38 UTC, navarroaxel commented on pages/linux/distrobox-create.md
> +> This command takes care of creating the container with input name and image.
```suggestion
> Create Distrobox containers with input name and image.
```

2022-01-18 12:38 UTC, navarroaxel commented on pages/linux/distrobox-enter.md
> +> This command takes care of entering the container with the name specified.
Perhaps this is more clear.
```suggestion
> Run a command in a Distrobox container.
```

2022-01-18 12:38 UTC, navarroaxel commented on pages/linux/distrobox-rm.md
> +> This command deletes one of the available distroboxes.
```suggestion
> Delete Distrobox containers.
```

2022-01-18 12:38 UTC, navarroaxel commented on pages/linux/distrobox-list.md
> +> This command lists available distroboxes. It detects them and lists them separately from the rest of normal podman or docker containers.
```suggestion
> List available Distrobox containers. It detects them and lists them separately from the rest of normal podman or Docker containers.
```

2022-01-18 18:53 UTC, CleanMachine1 commented on pages/linux/distrobox-create.md
> +> This command takes care of creating the container with input name and image.
```suggestion
> Create Distrobox containers with an input name and image.
```

2022-01-22 06:01 UTC, blueskyson approved these changes

2022-01-22 19:28 UTC, merged