grep: add Russian translation
tldr-pages/tldr pull request #7668
Opened 2022-01-16 11:06 UTC by dremdem

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-01-16 11:48 UTC, EmilySeville7cfg requested changes
Use [imperative mood](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#imperative-mood). :)

2022-01-16 11:48 UTC, EmilySeville7cfg commented on pages.ru/common/grep.md
> +- Поиск в файле по шаблону:
```suggestion
- Искать в файле по шаблону:
```

2022-01-16 11:48 UTC, EmilySeville7cfg commented on pages.ru/common/grep.md
> +- Поиск по заданной подстроке (регулярные выражения отключены):
```suggestion
- Искать по заданной подстроке (регулярные выражения отключены):
```

2022-01-16 11:48 UTC, EmilySeville7cfg commented on pages.ru/common/grep.md
> +- Поиск по шаблону во всех файлах в директории рекурсивно, показывая номера строк, там где подстрока была найдена, исключая бинарные(двоичные) файлы:
```suggestion
- Искать по шаблону во всех файлах директории рекурсивно, показывая номера строк, там где подстрока была найдена, исключая бинарные (двоичные) файлы:
```

2022-01-16 11:48 UTC, EmilySeville7cfg commented on pages.ru/common/grep.md
> +- Используются расширенные регулярные выражения (поддержка `?`, `+`, `{}`, `()` и `|`), без учета регистра:
```suggestion
 Искать, используя расширенные регулярные выражения (поддержка `?`, `+`, `{}`, `()` и `|`), без учета регистра:
```

2022-01-16 11:48 UTC, EmilySeville7cfg commented on pages.ru/common/grep.md
> +- Поиск строк, где есть совпадение по шаблону поиска, вывод только совпадающей части текста:
```suggestion
- Искать строки, где есть совпадение по шаблону поиска, выводя только совпадающие части текста:
```

2022-01-16 11:48 UTC, EmilySeville7cfg commented on pages.ru/common/grep.md
> +- Поиск строк в стандартном потоке ввода которые не совпадают с шаблоном поиска:
```suggestion
- Искать строки в стандартном потоке ввода, которые не совпадают с шаблоном поиска:
```

2022-01-16 15:49 UTC, dremdem commented on pages.ru/common/grep.md
> +- Поиск в файле по шаблону:
Changed.

2022-01-16 15:49 UTC, dremdem commented on pages.ru/common/grep.md
> +- Поиск по заданной подстроке (регулярные выражения отключены):
Changed.

2022-01-16 15:49 UTC, dremdem commented on pages.ru/common/grep.md
> +- Поиск по шаблону во всех файлах в директории рекурсивно, показывая номера строк, там где подстрока была найдена, исключая бинарные(двоичные) файлы:
Changed.

2022-01-16 15:49 UTC, dremdem commented on pages.ru/common/grep.md
> +- Используются расширенные регулярные выражения (поддержка `?`, `+`, `{}`, `()` и `|`), без учета регистра:
Changed.

2022-01-16 15:49 UTC, dremdem commented on pages.ru/common/grep.md
> +- Поиск строк, где есть совпадение по шаблону поиска, вывод только совпадающей части текста:
Changed.

2022-01-16 15:49 UTC, dremdem commented on pages.ru/common/grep.md
> +- Поиск строк в стандартном потоке ввода которые не совпадают с шаблоном поиска:
Changed.

2022-01-16 16:28 UTC, navarroaxel approved these changes

2022-01-18 13:51 UTC, blueskyson approved these changes

2022-01-18 13:52 UTC, merged