tail: page update
tldr-pages/tldr pull request #7681
Opened 2022-01-19 03:39 UTC by EmilySeville7cfg

- [ ] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

# ToDo

- [x] Use long options
- [x] Fix placeholders

2022-01-19 04:31 UTC, mfrw approved these changes
LGTM.
Thank you @EmilySeville7cfg

2022-01-19 15:28 UTC, navarroaxel requested changes

2022-01-19 15:28 UTC, navarroaxel commented on pages/common/tail.md
> +`tail --follow={{path/to/file}} --retry`
This "sounds" better, also the `=` makes some dark magic that I don't understand yet.
```suggestion
`tail --retry --follow {{path/to/file}}`
```
I don't know what this means, the `all.json` exists:
```bash
$ tail --retry --follow=all.json
tail: invalid argument ‘all.json’ for ‘--follow’
Valid arguments are:
  - ‘descriptor’
  - ‘name’
```
The command with `=` doesn't fail if the file is not created yet, and follow the file when it appears.

2022-01-19 21:10 UTC, sbrl commented
If macOS doesn't support long form arguments, then we either need to clone the original page into `osx`, or keep using short form arguments on this page.

2022-01-20 03:34 UTC, EmilySeville7cfg commented
Related issue: #7688.

2022-01-20 05:38 UTC, blueskyson commented on pages/common/tail.md
>  - Show last 'num' lines in file:
```suggestion
- Show last 'count' lines in file:
```

2022-01-20 05:38 UTC, blueskyson commented on pages/common/tail.md
>  - Show all file since line 'num':
```suggestion
- Show all file since line 'count':
```

2022-01-20 05:38 UTC, blueskyson commented on pages/common/tail.md
>  - Show last 'num' bytes in file:
```suggestion
- Show last 'count' bytes in file:
```

2022-01-20 12:09 UTC, navarroaxel commented on pages/common/tail.md
> +- Show all file since line 'count':
Perhaps this is better
```suggestion
- Print a file from a specific line number:
```

2022-01-20 12:09 UTC, navarroaxel commented on pages/common/tail.md
> +- Show last 'count' bytes in file:
```suggestion
- Print a specific count of bytes from the end of a given file.
```

2022-01-20 12:09 UTC, navarroaxel commented on pages/common/tail.md
>  - Keep reading file until `Ctrl + C`:
This is more specific
```suggestion
- Print the last lines of a given file and keep reading file until `Ctrl + C`:
```

2022-01-23 02:06 UTC, navarroaxel approved these changes

2022-01-23 02:06 UTC, merged