mpg123: add page
tldr-pages/tldr pull request #7689
Opened 2022-01-20 07:16 UTC by hellojukay

- [x] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-01-21 07:39 UTC, EmilySeville7cfg requested changes
I think we should mainly focus on a tool CLI instead of it's interactive usage in general case. ;) But I don't want to say that described interactive usage is useless.

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +`mpg123 {{path/target_file1.mp3}} {path/target_file2.mp3}}`
```suggestion
`mpg123 {{path/to/file1.mp3}} {{path/to/file2.mp3}} ...`
```

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +> More information: <https://www.mpg123.de/>.
Maybe better use manned.org:

```suggestion
> More information: <https://manned.org/mpg123.1>.
```

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +- Interactive command  to jump forward to the next song:
```suggestion
- Interactive command to jump forward to the next song:
```

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +- Interactive command  to jump back to the beginning for the song:
```suggestion
- Interactive command to jump back to the beginning for the song:
```

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +- Interactive command  to stop or replay:
```suggestion
- Interactive command to stop or replay:
```

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +- Interactive command  to fast forward:
```suggestion
- Interactive command to fast forward:
```

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +- Interactive command  to quit:
```suggestion
- Interactive command to quit:
```

2022-01-21 07:39 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +- Play mp3 files:
```suggestion
- Play the specified mp3 files:
```

2022-01-21 07:53 UTC, EmilySeville7cfg approved these changes

2022-01-21 07:53 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +> More information: <<https://manned.org/mpg123.1>.
```suggestion
> More information: <https://manned.org/mpg123.1>.
```

2022-01-21 08:04 UTC, EmilySeville7cfg approved these changes
Everything looks normal. :sunglasses:

2022-01-21 08:04 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +> Console MPEG Audio Player.
Maybe this better:

```suggestion
> Console MPEG audio player.
```

2022-01-21 08:04 UTC, EmilySeville7cfg commented on pages/linux/mpg123.md
> +- Play a mp3 from stdin:
```suggestion
- Play the mp3 from stdin:
```

2022-01-21 11:55 UTC, pixelcmtd commented on pages/linux/mpg123.md
> +`mpg123 -`
We usually use examples like this (e.g. `tldr llvm-as`):

```suggestion
`cat {{file.mp3}} | mpg123 -`
```

2022-01-22 05:41 UTC, blueskyson commented on pages/linux/mpg123.md
> +> More information: <https://manned.org/mpg123.1>.
```suggestion
> More information: <https://manned.org/mpg123>.
```

2022-01-23 02:03 UTC, navarroaxel commented on pages/linux/mpg123.md
> +- Interactive command to jump forward to the next song:
We don't mark the hotkeys for terminal apps
```suggestion
- Jump forward to the next song:
```

2022-01-23 02:03 UTC, navarroaxel commented on pages/linux/mpg123.md
> +- Interactive command to jump back to the beginning for the song:
```suggestion
- Jump back to the beginning for the song:
```

2022-01-23 02:03 UTC, navarroaxel commented on pages/linux/mpg123.md
> +- Interactive command to quit:
```suggestion
- Quit:
```

2022-01-23 02:03 UTC, navarroaxel commented on pages/linux/mpg123.md
> +- Interactive command to stop or replay:
Should we specify the current track?
```suggestion
- Stop or replay the current file:
```

2022-01-23 16:35 UTC, blueskyson approved these changes

2022-01-23 16:39 UTC, merged

2022-01-23 16:40 UTC, EmilySeville7cfg commented
Thanks! :З