add basic info on dm-tool
tldr-pages/tldr pull request #7691
Opened 2022-01-20 19:25 UTC by godalming123

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-01-20 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7691) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7691) it.</sub>

2022-01-21 03:50 UTC, einverne commented on pages/linux/dm-tool.md
> +# dm-tool
Need an empty line.

2022-01-21 05:59 UTC, einverne commented on pages/linux/dm-tool.md
> +A tool to commnicate with the lightdm display manager. EG: lock currect session and show lightdm, list all open sessions, connect an existing x server to the display manager.
```suggestion
> A tool to control the display manager.
```

2022-01-21 05:59 UTC, einverne commented on pages/linux/dm-tool.md
> +More informatioin: https://www.mankier.com/1/dm-tool.
```suggestion
> More information: <https://www.mankier.com/1/dm-tool>.
```

2022-01-21 07:46 UTC, EmilySeville7cfg requested changes

2022-01-21 07:46 UTC, EmilySeville7cfg commented on pages/linux/dm-tool.md
> +`dm-tool switch-to-greeter`
```suggestion
- Show the greeter while keeping current desktop session in ram and waiting to be restored upon authentication by logged in user:

`dm-tool switch-to-greeter`
```

2022-01-21 07:46 UTC, EmilySeville7cfg commented on pages/linux/dm-tool.md
> +`dm-tool swict-to-user {{username}} [{{session}}]`
```suggestion
- Switch to the specified user, showing an authentication prompt if required:

`dm-tool switch-to-user {{username}} [{{session}}]`
```

2022-01-21 07:46 UTC, EmilySeville7cfg commented on pages/linux/dm-tool.md
> +`dm-tool lock`
```suggestion
- Lock the current session:

`dm-tool lock`
```

2022-01-21 07:46 UTC, EmilySeville7cfg commented on pages/linux/dm-tool.md
> +`dm-tool add-seat [{{name}}={{value}}]`
```suggestion
- Add a new X server instance:

`dm-tool add-seat [{{name}}={{value}}]`
```

2022-01-21 08:11 UTC, godalming123 commented
This is fixed in add-dm-tool branch

2022-01-25 19:31 UTC, closed without merging

2022-01-25 19:34 UTC, godalming123 commented
the new PR with the actual branch is [here](https://github.com/tldr-pages/tldr/pull/7710)