yum: add Spanish translation
tldr-pages/tldr pull request #7696
Opened 2022-01-21 21:07 UTC by GhostViz

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

Resolves #7695

2022-01-21 21:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7696) before we can accept your contribution.<br/><hr/>**Joe Nichols** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7696) it.</sub>

2022-01-22 05:26 UTC, blueskyson commented on pages.es/linux/yum.md
> +- Elimina un paquete
```suggestion
- Elimina un paquete:
```

2022-01-22 17:54 UTC, navarroaxel requested changes
Thanks @GhostViz, I left some comments.

2022-01-22 17:54 UTC, navarroaxel commented on pages.es/linux/yum.md
> +- Actualice los paquetes instalados a las versiones más recientes disponibles:
```suggestion
- Actualiza los paquetes instalados a las versiones más recientes disponibles:
```

2022-01-22 17:54 UTC, navarroaxel commented on pages.es/linux/yum.md
> +- Instala un nuevo paquete respondiendo si a todas las preguntas:
Please include the indications in parenthesis
```suggestion
- Instala un nuevo paquete respondiendo si a todas las preguntas (también trabaja con actualizaciones, util para actualizaciones automáticas):
```

2022-01-22 17:54 UTC, navarroaxel commented on pages.es/linux/yum.md
> +> Más información: <https://man7.org/linux/man-pages/man8/yum.8.html>.
We use this source now, could you please update the English and Persian pages too?
```suggestion
> Más información: <https://manned.org/yum>.
```

2022-01-24 14:16 UTC, navarroaxel approved these changes

2022-01-25 08:41 UTC, EmilySeville7cfg requested changes

2022-01-25 08:41 UTC, EmilySeville7cfg commented on pages.es/linux/yum.md
> +> Más información: <https://manned.org/yum>.
```suggestion
> Más información: <https://man7.org/linux/man-pages/man8/yum.8.html>.
```

We prefer manned.org in a general case but the [original page](https://github.com/tldr-pages/tldr/blob/main/pages/linux/yum.md) uses another manual source so it's better to use the same one I think.

2022-01-25 08:44 UTC, EmilySeville7cfg approved these changes
LGTM ;)

2022-01-25 12:43 UTC, merged