ln, dig, df, du, tree: add Spanish translation
tldr-pages/tldr pull request #7726
Opened 2022-01-28 01:32 UTC by jreyes33

I chose not to translate `example.com` in the `dig` page because it is reserved by an RFC and neither `ejemplo.es` nor `ejemplo.com` are.

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2022-01-28 12:06 UTC, navarroaxel requested changes

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/dig.md
> +- Consulta la(s) IP(s) asociadas a un nombre de equipo (récords A):
```suggestion
- Consulta la(s) IP(s) asociadas a un nombre de equipo (registros A):
```

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/dig.md
> +- Obtiene una respuesta detallada para un dominio determinado (ŕecords A):
```suggestion
- Obtiene una respuesta detallada para un dominio determinado (registros A):
```

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/dig.md
> +- Consulta un tipo de récord DNS específico asociado a un dominio determinado:
```suggestion
- Consulta un tipo de registro DNS específico asociado a un dominio determinado:
```

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/dig.md
> +- Obtiene todos los tipos de récords para un dominio determinado:
```suggestion
- Obtiene todos los tipos de registros para un dominio determinado:
```

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/dig.md
> +- Realiza una búsqueda DNS inversa para una dirección IP (récord PTR):
```suggestion
- Realiza una búsqueda DNS inversa para una dirección IP (registro PTR):
```

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/du.md
> +> Uso de disco: estima y resume uso espacio de disco de archivos y directorios.
```suggestion
> Uso de disco: estima y resume el uso de espacio en disco de archivos y directorios.
```

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/tree.md
> +- Imprime archivos dentro de la jerarquía de árbol, especificando un patrón comodín, y excluye los directorios que no contengan archivos coincidentes:
```suggestion
- Imprime archivos dentro de la jerarquía de árbol, especificando un patrón comodín, excluyendo los directorios que no contengan archivos coincidentes:
```

2022-01-28 12:06 UTC, navarroaxel commented on pages.es/common/tree.md
> +- Imprime archivos dentro de la jerarquía de árbol, especificando un patrón, y excluye los directorios que no sean ancestros del especificado:
```suggestion
- Imprime archivos dentro de la jerarquía de árbol, especificando un patrón, excluyendo los directorios que no sean ancestros del especificado:
```

2022-01-28 21:01 UTC, jreyes33 commented
Thanks for the review, @navarroaxel. I've applied the suggestions and updated the PR.

2022-01-29 20:09 UTC, navarroaxel approved these changes

2022-02-02 15:46 UTC, blueskyson approved these changes

2022-02-02 15:50 UTC, merged