source: add Indonesian translation
tldr-pages/tldr pull request #7738
Opened 2022-02-01 06:52 UTC by amarps

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-02-01 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7738) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7738) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7738) it.</sub>

2022-02-01 11:57 UTC, navarroaxel approved these changes

2022-02-02 07:59 UTC, reinhart1010 requested changes

2022-02-02 07:59 UTC, reinhart1010 commented on pages.id/common/source.md
> +`source {{path/to/file}}`
```suggestion
`source {{jalan/menuju/file}}`
```

2022-02-02 07:59 UTC, reinhart1010 commented on pages.id/common/source.md
> +`. {{path/to/file}}`
```suggestion
`. {{jalan/menuju/file}}`
```

2022-02-02 11:01 UTC, reinhart1010 commented on pages.id/common/source.md
> +- Mengevaluasi konten pada file yang ditentukan (`.` alternatif dari `source`)
```suggestion
- Mengevaluasi konten pada file yang ditentukan (`.` adalah alias dari `source`)
```

I think it's clearer to state that "`.` is an alias of `source`"

2022-02-02 11:39 UTC, reinhart1010 approved these changes
Thanks!

2022-02-02 11:39 UTC, merged