bat, gdb: add Indonesian translation
tldr-pages/tldr pull request #7745
Opened 2022-02-03 14:08 UTC by amarps

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-02-03 17:59 UTC, navarroaxel requested changes

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/bat.md
> +# cat
```suggestion
# bat
```

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/bat.md
> +> Informasi lebih lanjut: <https://www.gnu.org/software/coreutils/cat>.
```suggestion
> Informasi lebih lanjut: <https://github.com/sharkdp/bat>.
```

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/gdb.md
> +`gdb {{berkas-exe}}`
We use `snake_case` for placeholders
```suggestion
`gdb {{berkas_exe}}`
```

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/gdb.md
> +- menambahkan sebuah proses pada gdb:
```suggestion
- Menambahkan sebuah proses pada gdb:
```

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/gdb.md
> +`gdb -p {{berkas-exe}}`
```suggestion
`gdb -p {{berkas_exe}}`
```

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/gdb.md
> +`gdb -c {{core}} {{berkas-exe}}`
```suggestion
`gdb -c {{core}} {{berkas_exe}}`
```

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/gdb.md
> +`gdb -ex "{{perintah}}" {{berkas-exe}}`
```suggestion
`gdb -ex "{{perintah}}" {{berkas_exe}}`
```

2022-02-03 17:59 UTC, navarroaxel commented on pages.id/common/gdb.md
> +`gdb --args {{berkas-exe}} {{argumen1}} {{argumen2}}`
```suggestion
`gdb --args {{berkas_exe}} {{argumen1}} {{argumen2}}`
```

2022-02-05 12:34 UTC, navarroaxel approved these changes

2022-03-02 20:44 UTC, CleanMachine1 approved these changes

2022-03-02 20:44 UTC, merged