bash-it: add page
tldr-pages/tldr pull request #7752
Opened 2022-02-06 15:15 UTC by EmilySeville7cfg

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-02-06 15:21 UTC, EmilySeville7cfg commented
@gaelicWizard, please review this page also. :)

2022-02-12 01:23 UTC, CleanMachine1 requested changes

2022-02-12 01:23 UTC, CleanMachine1 commented on pages/common/bash-it.md
> +- Restart Bash entirely:
```suggestion
- Restart Bash:
```

2022-02-16 00:05 UTC, gaelicWizard approved these changes

2022-02-17 22:10 UTC, sbrl reviewed
Does this function like a package manager for Bash? You don't mention how to install/remove individual items at all? I'm confused.

2022-02-17 22:10 UTC, sbrl commented on pages/common/bash-it.md
> +> A collection of community Bash commands and scripts for Bash 3.2+.
Perhaps this will read better?
```suggestion
> A collection of community contributed Bash commands and scripts for Bash 3.2+.
```

2022-02-20 08:33 UTC, EmilySeville7cfg commented
> Does this function like a package manager for Bash? You don't mention how to install/remove individual items at all? I'm confused.

I think you can treat `bash-it` as a package manager built-in to this framework.

2022-02-20 19:25 UTC, gaelicWizard commented
It's not a package manager; there are no packages. it's more like a startup framework, with a lot of built-in plugins. It's like "Oh My Zsh"

2022-04-02 23:51 UTC, CleanMachine1 approved these changes

2022-06-26 22:08 UTC, sbrl approved these changes
Ah, ok - that makes sense! Thanks for explaining :-)

2022-06-26 22:08 UTC, merged