nm: update page
tldr-pages/tldr pull request #7758
Opened 2022-02-06 23:15 UTC by EmilySeville7cfg

- [ ] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

## ToDo

- [x] prefer long options
- [x] fix placeholders

2022-02-06 23:16 UTC, navarroaxel approved these changes

2022-02-07 00:01 UTC, pixelcmtd requested changes

2022-02-07 00:01 UTC, pixelcmtd commented on pages/common/nm.md
> +`nm --undefined-only {{path/to/file.o}}`
```suggestion
`nm -u {{path/to/file.o}}`
```

2022-02-07 00:01 UTC, pixelcmtd commented on pages/common/nm.md
> +`nm --debug-syms {{path/to/file.o}}`
```suggestion
`nm -a {{path/to/file.o}}`
```

2022-02-07 07:45 UTC, mfrw reviewed
Given these pages are in common, should we create new pages for `osx` which in my understanding would not have the long version of the flags ?

2022-02-07 13:50 UTC, pixelcmtd commented
> should we create new pages for `osx` which [...] would not have the long version of the flags ?

if we were to do something like that, i'd instead make new `linux` pages which have the long options, because initially the long options were a gnu-specific thing, for example, early freebsd versions didn't have it either.

2022-02-14 11:41 UTC, EmilySeville7cfg commented
> if we were to do something like that, i'd instead make new linux pages which have the long options, because initially the long options were a gnu-specific thing, for example, early freebsd versions didn't have it either.

I think we can use `general/` for pages with most portable options (short/long) and `linux/` for just GNU options.

2022-02-14 11:43 UTC, merged