Create maestral.md
tldr-pages/tldr pull request #7759
Opened 2022-02-06 23:50 UTC by whitemuu

new command

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

2022-02-06 23:53 UTC, EmilySeville7cfg requested changes

2022-02-06 23:53 UTC, EmilySeville7cfg commented on pages/common/maestral.md
> +> Maestral is a lightweight Dropbox client for macOS and Linux.
```suggestion
> Maestral is a lightweight Dropbox client for macOS and Linux.
> More information: <https://maestral.app/cli>.
```

2022-02-06 23:53 UTC, EmilySeville7cfg commented on pages/common/maestral.md
> +`maestral filestatus {{local_path}}`
```suggestion
`maestral filestatus {{path/to/file_or_directory}}`
```

2022-02-07 00:19 UTC, CleanMachine1 commented on pages/common/maestral.md
> +> Maestral is a lightweight Dropbox client for macOS and Linux.
```suggestion
> A lightweight Dropbox client for macOS and Linux.
```

2022-02-07 00:20 UTC, CleanMachine1 commented
Thanks for your contribution! I have left a review, after I will approve :)

2022-02-07 00:29 UTC, CleanMachine1 approved these changes

2022-02-07 00:29 UTC, CleanMachine1 commented on pages/common/maestral.md
> +- Get current status of Maestral:
```suggestion
- Print current status of Maestral:
```

2022-02-07 01:00 UTC, EmilySeville7cfg approved these changes

2022-02-07 01:00 UTC, EmilySeville7cfg commented on pages/common/maestral.md
> +- Get sync status of a specific file or folder:
```suggestion
- Print sync status of a specific file or folder:
```

2022-02-07 01:04 UTC, merged

2022-02-07 01:05 UTC, EmilySeville7cfg commented
Thanks for your contribution! ❤️