dotnet-tool: add page
tldr-pages/tldr pull request #7769
Opened 2022-02-10 17:19 UTC by navarroaxel

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** 5.0.405

2022-02-11 19:30 UTC, CleanMachine1 approved these changes

2022-02-12 09:20 UTC, EmilySeville7cfg requested changes

2022-02-12 09:20 UTC, EmilySeville7cfg commented on pages/common/dotnet-tool.md
> +`dotnet tool install --global dotnet-ef`
```suggestion
- Install a global tool (don't use `--global` for local tools):

`dotnet tool install --global {{dotnetsay}}`
```

Maybe it's better to use some sample global tool and more general description.

2022-02-12 09:20 UTC, EmilySeville7cfg commented on pages/common/dotnet-tool.md
> +`dotnet tool update --global {{tool_name}}`
```suggestion
- Update a specific global tool (don't use `--global` for local tools):

`dotnet tool update --global {{tool_name}}`
```

2022-02-12 09:20 UTC, EmilySeville7cfg commented on pages/common/dotnet-tool.md
> +`dotnet tool uninstall {{tool_name}}`
```suggestion
- Uninstall a global tool (don't use `--global` for local tools):

`dotnet tool uninstall --global {{tool_name}}`
```

2022-02-12 09:20 UTC, EmilySeville7cfg commented on pages/common/dotnet-tool.md
> +`dotnet tool list`
```suggestion
- List installed global tools (don't use `--global` for local tools):

`dotnet tool list --global`
```

2022-04-02 17:09 UTC, EmilySeville7cfg approved these changes

2022-04-02 22:16 UTC, merged