puppet-agent: Add disable agent & enable example
tldr-pages/tldr pull request #7787
Opened 2022-02-16 11:20 UTC by lauberv

- [X] The page (if new), does not already exist in the repository.
- [X] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [X] The page has 8 or fewer examples.
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-02-16 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7787) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7787) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7787) it.</sub>

2022-02-16 13:15 UTC, navarroaxel requested changes

2022-02-16 13:15 UTC, navarroaxel commented on pages/common/puppet-agent.md
> +`puppet agent --disable "<your message>"`
We try to avoid `you/your`. We use this token syntax and `snake_case` for placeholders.
```suggestion
`puppet agent --disable "{{message}}"`
```

2022-02-16 13:15 UTC, navarroaxel commented on pages/common/puppet-agent.md
> +- Disable puppet agent
Don't forget the colon `:`
```suggestion
- Disable the agent:
```

2022-02-16 13:15 UTC, navarroaxel commented on pages/common/puppet-agent.md
> +- Enable puppet agent
```suggestion
- Enable the agent:
```

2022-02-16 15:03 UTC, navarroaxel approved these changes

2022-02-16 15:05 UTC, lauberv commented
Thanks @navarroaxel for your feedback I will try to be more careful in my next modification

2022-02-16 15:10 UTC, navarroaxel commented
> Thanks @navarroaxel for your feedback I will try to be more careful in my next modification

Don't worry @lauberv, welcome and thanks for your submission.

2022-02-17 13:22 UTC, mfrw approved these changes
LGTM.
Thank you @lauberv for your contirbution.

2022-02-17 13:23 UTC, merged