gow: add page
tldr-pages/tldr pull request #7805
Opened 2022-02-20 22:05 UTC by michaelcale

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-02-21 00:05 UTC, Waples approved these changes

2022-02-21 10:11 UTC, navarroaxel requested changes

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +# Go Watch
The page title should be the command name
```suggestion
# gow
```

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +- Start and watch current directory:
```suggestion
- Start and watch the current directory:
```

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +`gow -v -w={{dir1,dir2 ...}} run .`
```suggestion
`gow -v -w={{path/to/directory1,path/to/directory2,...}} run .`
```

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +`gow run . {{arg1 arg2 ...}}`
We don't abbrev 
```suggestion
`gow run . {{argument1 argument2 ...}}`
```

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +- Specify file extensions to watch
```suggestion
- Watch the specified file extensions:
```

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +`gow -e={{go,html ...}} run .`
```suggestion
`gow -e={{go,html}} run .`
```

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +- Help
```suggestion
- Display help:
```

2022-02-21 10:11 UTC, navarroaxel commented on pages/common/gow.md
> +- Pass arguments to the app
```suggestion
- Start the application with the specified arguments:
```

2022-02-25 09:17 UTC, navarroaxel approved these changes

2022-02-25 09:18 UTC, merged