zip: refresh
tldr-pages/tldr pull request #7827
Opened 2022-02-27 20:31 UTC by git-em

Expand options, add basic invocation (without opts), rm -s option

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-02-27 20:37 UTC, git-em commented
See https://github.com/tldr-pages/tldr/pull/7825#issuecomment-1053651249

2022-03-01 06:49 UTC, blueskyson commented on pages/common/zip.md
>  - Delete files from an existing zip file:
This is more precise.
```suggestion
- Delete entries from an existing zip file:
```

2022-03-01 06:49 UTC, blueskyson commented on pages/common/zip.md
> +`zip --delete {{compressed.zip}} "{{foo/*.tmp}}"`
Provide 3 useful syntax.
```suggestion
`zip --delete {{compressed.zip}} "{{foo/file}}" "{{foo/bar/*}}" "{{*.ext}}"`
```

2022-03-08 23:11 UTC, CleanMachine1 commented
Hi, thanks for your contribution, could you please change the syntax of the things like {{path/to/file1}} to be {{[path/to/file_1}}

2022-03-10 23:36 UTC, CleanMachine1 approved these changes

2022-03-12 08:04 UTC, EmilySeville7cfg requested changes

2022-03-12 08:04 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +`zip --exclude {{path/to/exclude}} --recurse-paths {{compressed.zip}} {{path/to/directory}}`
```suggestion
`zip --exclude {{path/to/file1 path/to/file2 ...}} --recurse-paths {{compressed.zip}} {{path/to/directory}}`
```

2022-03-12 08:04 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +`zip {{compressed.zip}} {{path/to/file}}`
```suggestion
`zip {{path/to/compressed.zip}} {{path/to/file1 path/to/file2 ...}}`
```

2022-03-12 08:04 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +`zip --delete {{compressed.zip}} "{{foo/file}}" "{{foo/bar/*}}" "{{*.ext}}"`
```suggestion
`zip --delete {{path/to/compressed.zip}} {{path/to/file_to_remove1 path/to/file_to_remove2 ...}}`
```

2022-03-12 08:04 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +`zip --show-files {{compressed.zip}}`
```suggestion
`zip --show-files {{path/to/compressed.zip}}`
```

2022-03-19 18:42 UTC, navarroaxel commented on pages/common/zip.md
> +`zip --exclude {{path/to/exclude}} --recurse-paths {{compressed.zip}} {{path/to/directory}}`
I think the current example is better.

2022-03-20 02:55 UTC, EmilySeville7cfg requested changes

2022-03-20 02:55 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +- Package and compress files:
```suggestion
- Package and compress the specified files:
```

2022-03-20 02:55 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +- Package and compress files and directories recursively:
```suggestion
- Package and compress the specified files and directories recursively:
```

2022-03-20 02:55 UTC, EmilySeville7cfg commented on pages/common/zip.md
>  - Archive a directory and its contents with the highest level [9] of compression:
```suggestion
- Archive the specified directory with the highest level (9) of compression:
```

2022-03-20 02:55 UTC, EmilySeville7cfg commented on pages/common/zip.md
>  - Create an encrypted archive (user will be prompted for a password):
```suggestion
- Create the encrypted archive (user will be prompted for the password):
```

2022-03-20 02:55 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +- Add files to an existing zip file:
```suggestion
- Add the specified files to the existing zip file:
```

2022-03-20 02:55 UTC, EmilySeville7cfg commented on pages/common/zip.md
> +- Delete entries from an existing zip file:
```suggestion
- Delete the specified entries from the existing zip file:
```

2022-03-20 02:55 UTC, EmilySeville7cfg commented on pages/common/zip.md
>  - List files within a specified archive (without extracting them):
```suggestion
- List files within the specified archive (without extracting them):
```

2022-06-06 05:34 UTC, mfrw commented
Looks like there is one more PR for refreshing zip:
- #7996 

What should we do with this PR ?

2022-06-06 09:55 UTC, EmilySeville7cfg commented
@mfrw, I think we can merge them (take my changes and apply them to this PR where needed). I can close my PR.

2022-06-07 01:34 UTC, mfrw commented
> @mfrw, I think we can merge them (take my changes and apply them to this PR where needed). I can close my PR.

@EmilySeville7cfg In my opinion, the PR #7996 seems more complete.
Probably we should reopen that and port changes from here.
/cc @git-em @navarroaxel

2022-07-26 21:27 UTC, CleanMachine1 commented
closing due to inactivity, open again if you would still like to contribute this.

2022-07-26 21:27 UTC, closed without merging