Create fstab.md
tldr-pages/tldr pull request #7883
Opened 2022-03-13 16:33 UTC by qube-03

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

This is my first time making a pull request and I don't quite know how it works. Please tell me if I did anything wrong.

2022-03-13 16:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7883) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7883) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7883) it.</sub>

2022-03-14 02:59 UTC, mfrw reviewed
Wondering if we should add something that is not a command.
Although, one example [cgroups](https://github.com/tldr-pages/tldr/blob/main/pages/linux/cgroups.md) comes to mind.
Thoughts ?

2022-03-14 09:31 UTC, EmilySeville7cfg commented
> Wondering if we should add something that is not a command.
> Although, one example [cgroups](https://github.com/tldr-pages/tldr/blob/main/pages/linux/cgroups.md) comes to mind.
> Thoughts ?

It's a good idea. Just instead of code samples any other one-liners will be placed such as configs. The problem arises when tl;dr page describes config that doesn't support joining several lines and mandates `\n`.

2022-03-14 11:47 UTC, navarroaxel commented
> Wondering if we should add something that is not a command. Although, one example [cgroups](https://github.com/tldr-pages/tldr/blob/main/pages/linux/cgroups.md?rgh-link-date=2022-03-14T02%3A59%3A44Z) comes to mind. Thoughts ?

`tldr` is for command examples, so it could be command related to `fstab`, example:

```markdown
`echo '/swapfile none swap defaults 0 0' | tee --append /etc/fstab`
```

2022-03-14 18:39 UTC, qube-03 commented
ill fix the errors soon, i need to study as of right now, thanks everyone for the help so far :)

2022-03-18 17:01 UTC, qube-03 reviewed
i hopefully fixed the errors mentioned above. if there are still problems please let me know

2022-03-19 07:40 UTC, EmilySeville7cfg requested changes

2022-03-19 07:40 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +>DO NOT edit this file if you don't know what you're doing.
```suggestion
> /etc/fstab automatically mounts partitions with different options.
> It is not a command, but a text file you edit with an editor of choice.
> More information: <https://manned.org/fstab>.
```

2022-03-19 07:40 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +>UUID/Label | Directory to mount to | Type of the partition | Options for mounting | Dump | Order in which partitions are read by 'fsck'
```suggestion
`UUID/Label | Directory to mount to | Type of the partition | Options for mounting | Dump | Order in which partitions are read by 'fsck'`
```

2022-03-19 07:40 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +>UUID/Label | Directory to mount to | Type of the partition | Options for mounting | Dump | Order in which partitions are read by 'fsck'
The first is the code description and the second is always the code example. Don't reverse the order.

2022-04-06 19:45 UTC, qube-03 commented
hi, recently ive had some stress with school but i did not forget this pr. thanks for checking in, i'll resolve errors soon

2022-06-06 09:47 UTC, EmilySeville7cfg requested changes
Please fix syntax errors. 😄

2022-06-06 09:47 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +# fstab
```suggestion
# fstab
```

2022-07-24 02:16 UTC, EmilySeville7cfg requested changes

2022-07-24 02:16 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +>You can also define this with Partition Labels, if you have that.
```suggestion
- Here you put the "UUID" of the partition you wish to auto-mount. You can get the UUID by running: `sudo blkid`. You can also define this with Partition Labels, if you have that:

`UUID/Label`
```

2022-07-24 02:16 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +>Be aware that the directory needs to exist before you can mount to it. Create the directory you want with 'mkdir'.
```suggestion
- Tell fstab where to mount your partition to, for example: `/media/Harddrive`. Be aware that the directory needs to exist before you can mount to it. Create the directory you want with 'mkdir':

`Directory`
```

2022-07-24 02:16 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +`sudo blkid`
```suggestion
- Put the type of your partition here. To figure out what partition type your partition is, run: `sudo blkid`:

`Type of the partition`
```

2022-07-24 02:16 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +>Seperate each option with , (without spaces inbetween)
```suggestion
- Here you can tell fstab what additional settings you want to mount your partition with. For example: `defaults -> Mounts with all default options (see manpage)`, `exec -> Allow programs to be run`, `users -> All users are able to auto-mount this partition`. Seperate each option with , (without spaces inbetween):

`Options for mounting`
```

2022-07-24 02:16 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +>Pass: Tell fstab which partitions to check first on boot (with fsck).
```suggestion
- These Options aren't as important, you can just set them both to 0. Pass: Tell fstab which partitions to check first on boot (with fsck):

`Dump/Pass`
```

2022-07-24 02:18 UTC, EmilySeville7cfg requested changes
Remove examples from description: they make it too long.

2022-07-24 02:18 UTC, EmilySeville7cfg commented on pages/linux/fstab.md
> +- Here you can tell fstab what additional settings you want to mount your partition with. For example: `defaults -> Mounts with all default options (see manpage)`, `exec -> Allow programs to be run`,
```suggestion
- Here you can tell fstab what additional settings you want to mount your partition with. Seperate each option with , (without spaces inbetween):
```

2022-07-24 02:20 UTC, EmilySeville7cfg commented
Errors are fixed because no author response is obtain for a long time.

2022-07-25 09:49 UTC, marchersimon commented
I'm really not sure if we should accept this page. We had this situation a few times in the past and always decided that it should be addad to another project like `cheat.sh` instead. 

I know it's often frustrating to have to reject seemingly good ideas, but we just don't have the capabilities to maintain all this. When we accept non-command pages, there would have to be a whole new style guide, probably new syntax, new rules, etc.

(Also, `cgroups` does fit this project's scope, because it's merely an alias page to a few other commands. A little unusual, but not much.)

2022-07-25 09:54 UTC, qube-03 commented
ill be honest, i kinda forgot about this contribution. originally though, i thought of tldr being an 'ez help' kinda program which the name suggests. im not sure if youd have to make a whole new stylesheet guide for 'non command pages' cuz i think no matter what man page, it can be shortened for this project

the decision is up to you after all tho since i didnt really do much except the initial commig

2022-07-25 10:31 UTC, marchersimon commented
Thanks for understanding. You could try contributing your page to [cheat](https://github.com/cheat/cheat).

2022-07-25 13:12 UTC, navarroaxel commented
> I'm really not sure if we should accept this page. We had this situation a few times in the past and always decided that it should be addad to another project like `cheat.sh` instead.

I think we can accept 1 o 2 examples like the following:

`echo '/swapfile none swap defaults 0 0' | tee --append /etc/fstab`

but not an explanation about the structure of this file.

2022-07-25 13:12 UTC, navarroaxel requested changes
> I'm really not sure if we should accept this page. We had this situation a few times in the past and always decided that it should be addad to another project like `cheat.sh` instead.

I think we can accept 1 o 2 examples like the following:

`echo '/swapfile none swap defaults 0 0' | tee --append /etc/fstab`

but not an explanation about the structure of this file.

2022-07-26 06:55 UTC, marchersimon commented
@navarroaxel but we can't just throw in `'/swapfile none swap defaults 0 0'` without explaining its structure. That probably wouldn't be very useful.

2022-07-26 11:08 UTC, navarroaxel commented
> @navarroaxel but we can't just throw in `'/swapfile none swap defaults 0 0'` without explaining its structure. That probably wouldn't be very useful.

@marchersimon well, in the example description we can explain some params. Anyway this isn't a command.

2022-08-02 19:16 UTC, sbrl commented
Sorry, tldr-pages only documents commands, so we can't accept this page. However, there are a number of sister projects like the aforementioned `cheat.sh` where this would fit better.

2022-08-02 19:16 UTC, closed without merging