zek: add page
tldr-pages/tldr pull request #7888
Opened 2022-03-14 07:07 UTC by mfrw

Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-03-14 07:09 UTC, mfrw commented on pages/common/zek.md
> +- Generate a Go struct from an XML from stdin and send output to a file:
```suggestion
- Generate a Go struct from a given XML from stdin and send output to a file:
```

2022-03-14 07:09 UTC, mfrw commented on pages/common/zek.md
> +- Generate an example Go program from an XML from stdin and send output to a file:
```suggestion
- Generate an example Go program from a given XML from stdin and send output to a file:
```

2022-03-14 09:19 UTC, EmilySeville7cfg requested changes

2022-03-14 09:19 UTC, EmilySeville7cfg commented on pages/common/zek.md
> +`curl -s {{https://url.to.xml}} | zek -o {{path/to/output.go}}`
```suggestion
`curl -s {{https://url/to/xml}} | zek -o {{path/to/output.go}}`
```

2022-03-17 00:08 UTC, EmilySeville7cfg approved these changes

2022-03-17 11:41 UTC, navarroaxel approved these changes

2022-03-17 11:43 UTC, merged