color, dir, nautilus, touch, wal: add Catalan translation. acpi: update Catalan translation
tldr-pages/tldr pull request #7965
Opened 2022-04-06 20:37 UTC by Seifer23

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

2022-04-06 20:49 UTC, EmilySeville7cfg requested changes

2022-04-06 20:49 UTC, EmilySeville7cfg commented on pages.ca/windows/color.md
> +`color {{foreground_code}}{{background_code}}`
```suggestion
`color {{codi_de_primer_pla}}{{codi_fons}}`
```

Google translate suggests this.

2022-04-06 20:51 UTC, EmilySeville7cfg requested changes

2022-04-06 20:51 UTC, EmilySeville7cfg commented on pages.ca/common/touch.md
> +`touch {{path/to/file{1,2,3}.txt}}`
```suggestion
`touch {{camí/al/fitxer{1,2,3}.txt}}`
```

2022-04-07 15:44 UTC, EmilySeville7cfg approved these changes

2022-04-07 16:28 UTC, navarroaxel approved these changes

2022-04-07 16:29 UTC, merged