chsh: refresh page
tldr-pages/tldr pull request #7998
Opened 2022-04-13 07:32 UTC by EmilySeville7cfg

- [ ] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-04-14 15:06 UTC, mfrw commented on pages/common/chsh.md
> +- Set a specific login shell for a current user interactively:
maybe `the` sounds better .. but agian .. I am not a grammar expert 
```suggestion
- Set a specific login shell for the current user interactively:
```

2022-04-14 15:06 UTC, mfrw commented on pages/common/chsh.md
> +- Set a specific login shell for a current user:
```suggestion
- Set a specific login shell for the current user:
```

2022-04-14 15:06 UTC, mfrw commented on pages/linux/chsh.md
> +- Set a specific login shell for a current user interactively:
```suggestion
- Set a specific login shell for the current user interactively:
```

2022-04-14 15:06 UTC, mfrw commented on pages/linux/chsh.md
> +- Set a specific login shell for a current user:
```suggestion
- Set a specific login shell for the current user:
```

2022-11-12 18:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7998) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=7998) before we can accept your contribution.<br/><hr/>**EmilySeville7cfg** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=7998) it.</sub>

2022-12-15 12:47 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2022-12-26 08:39 UTC, pixelcmtd requested changes
`--list-shells` isn't portable.

2022-12-30 01:41 UTC, kbdharun approved these changes

2023-01-09 14:16 UTC, mfrw commented on pages/common/chsh.md
> +> Change a user's login shell.
How about we do not put an article here:
`Change user's login shell` ?

2023-01-09 14:20 UTC, mfrw commented on pages/common/chsh.md
> +> Change a user's login shell.
How about we drop the article: ~a/the~

Just like we have for `[l]ist available shells` :)
```suggestion
> Change user's login shell.
```

2023-01-09 15:54 UTC, mfrw approved these changes
LGTM :)
Thanks @EmilySeville7cfg

2023-01-09 16:35 UTC, merged