xed: add page
tldr-pages/tldr pull request #8009
Opened 2022-04-15 03:49 UTC by EmilySeville7cfg

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):** latest

2022-04-15 03:56 UTC, navarroaxel commented on pages/linux/xed.md
> +`xed --encoding {{WINDOWS-1252}} {{path/to/document{1,2,...}}}`
```suggestion
`xed --encoding {{WINDOWS-1252}} {{path/to/document1 path/to/document2 ...}}`
```

2022-04-15 04:55 UTC, EmilySeville7cfg commented on pages/linux/xed.md
> +`xed --encoding {{WINDOWS-1252}} {{path/to/document{1,2,...}}}`
Fixed in two examples at once 😄

2022-04-15 12:14 UTC, blueskyson approved these changes

2022-05-02 09:29 UTC, mfrw approved these changes
LGTM with a teeny nitpick

2022-05-02 09:29 UTC, mfrw commented on pages/linux/xed.md
> +- Open file and go to a specific line:
```suggestion
- Open a file and go to a specific line:
```

2022-05-02 11:02 UTC, navarroaxel requested changes

2022-05-02 11:02 UTC, navarroaxel commented on pages/linux/xed.md
> +- Open files in a specific encoding:
```suggestion
- Open files using a specific encoding:
```

2022-06-03 05:28 UTC, mfrw commented
@navarroaxel Ping :)

2022-06-03 09:01 UTC, navarroaxel approved these changes

2022-06-03 09:01 UTC, merged