Create dumpcap.md file
tldr-pages/tldr pull request #8042
Opened 2022-04-21 17:17 UTC by Straightbuggin

Add some common commands when trying to capture packets using dumpcap, which is part of wireshark.

- [X ] The page (if new), does not already exist in the repository.
- [X ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ X] The page has 8 or fewer examples.
- [ X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [X ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ X] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-04-21 17:51 UTC, navarroaxel submitted a review, later dismissed

2022-04-21 17:51 UTC, navarroaxel commented on pages/common/dumpcap.md
> +# dumpcap - Dump network traffic
This should be the command name
```suggestion
# dumpcap
```

2022-04-21 17:51 UTC, navarroaxel commented on pages/common/dumpcap.md
> +> Preferably one line; two are acceptable if necessary.
:eyes: 
```suggestion
```

2022-04-21 17:51 UTC, navarroaxel commented on pages/common/dumpcap.md
> +`dumpcap -D`
We prefer long arguments if available
```suggestion
`dumpcap --list-interfaces`
```

2022-04-21 17:51 UTC, navarroaxel commented on pages/common/dumpcap.md
> +`dumpcap -i 1`
```suggestion
`dumpcap --interface 1`
```

2022-04-21 17:51 UTC, navarroaxel commented on pages/common/dumpcap.md
> +`dumpcap -i 1 -w path/to/write/file/to.pcapng`
```suggestion
`dumpcap --interface 1 -w {{path/to/output_file.pcapng}}`
```

2022-04-21 17:51 UTC, navarroaxel commented on pages/common/dumpcap.md
> +`dumpcap -i 1 -w path/to/write/file/to.pcapng -b filesize:500000 -b files:10`
```suggestion
`dumpcap --interface 1 -w {{path/to/output_file.pcapng}} --ring-buffer filesize:500000 --ring-buffer files:10`
```

2022-04-24 07:58 UTC, blueskyson commented on pages/common/dumpcap.md
> +`dumpcap --interface 1`
```suggestion
`dumpcap --interface {{1}}`
```

2022-04-24 07:58 UTC, blueskyson commented on pages/common/dumpcap.md
> +`dumpcap --interface 1 -w {{path/to/output_file.pcapng}}`
```suggestion
`dumpcap --interface {{1}} -w {{path/to/output_file.pcapng}}`
```

2022-04-24 07:58 UTC, blueskyson commented on pages/common/dumpcap.md
> +`dumpcap --interface 1 -w {{path/to/output_file.pcapng}} --ring-buffer filesize:500000 --ring-buffer files:10`
```suggestion
`dumpcap --interface {{1}} -w {{path/to/output_file.pcapng}} --ring-buffer filesize:{{500000}} --ring-buffer files:{{10}}`
```

2022-04-25 06:49 UTC, EmilySeville7cfg requested changes

2022-04-25 06:49 UTC, EmilySeville7cfg commented on pages/common/dumpcap.md
> +- Get a list of available interfaces:
```suggestion
- Display available interfaces:
```

2022-04-25 06:49 UTC, EmilySeville7cfg commented on pages/common/dumpcap.md
> +- Start capturing packets on the first interface:
```suggestion
- Capture packets on a specific interface:
```

2022-04-25 06:49 UTC, EmilySeville7cfg commented on pages/common/dumpcap.md
> +- Start capturing packets on the first interface to a specific location:
```suggestion
- Capture packets to a specific location:
```

2022-04-25 06:49 UTC, EmilySeville7cfg commented on pages/common/dumpcap.md
> +- Start capturing packets on the first interface to a specific location and writing to a ring buffer with a max of 10 files of 500MB each:
```suggestion
- Write to a ring buffer with a specific max file limit of a specific size:
```

2022-04-25 15:43 UTC, EmilySeville7cfg approved these changes

2022-04-26 19:06 UTC, blueskyson approved these changes

2022-04-26 22:23 UTC, CleanMachine1 approved these changes
LGTM, merging. Thanks for your contribution!

2022-04-26 22:23 UTC, merged