perl: improve matching pattern examples
tldr-pages/tldr pull request #8043
Opened 2022-04-21 19:46 UTC by shawnbot

This PR simplifies and improves the `perl` matching pattern example. I added another example for `perl -nle 'print if /{{pattern}}/`, but this page already has 8 examples, so I'm going to remove it. ☹️ 

- [ ] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).

**Version of the command being documented (if known):** Perl 5

2022-04-25 06:42 UTC, EmilySeville7cfg requested changes

2022-04-25 06:42 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +- Loo[p] over all lines of a file, editing them [i]n-place with a find/replace [e]xpression and saving the original file with a new extension:
```suggestion
- Edit all file lines [i]n-place with a specific replacement [e]xpression and save a file with a new extension:
```

2022-04-25 06:42 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +`perl -p -i'.{{extension}}' -e 's/{{find}}/{{replace}}/g' {{filename}}`
```suggestion
`perl -p -i'.{{extension}}' -e 's/{{regular_expression}}/{{replacement}}/g' {{path/to/file}}`
```

2022-04-25 06:42 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +- Run a multiline find/replace expression on a file, and save the result in another file:
```suggestion
- Run a multi-line replacement expression on a file, and save the result in a specific file:
```

2022-04-25 06:46 UTC, EmilySeville7cfg requested changes

2022-04-25 06:46 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +`perl -p -e 's/{{foo\nbar}}/{{foobar}}/g' {{input_file}} > {{output_file}}`
```suggestion
`perl -p -e 's/{{foo\nbar}}/{{foobar}}/g' {{path/to/input_file}} > {{path/to/output_file}}`
```

2022-04-25 06:46 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +`cat {{filename}} | perl -n -l -e 'print if /{{pattern}}/'`
```suggestion
`cat {{path/to/file}} | perl -n -l -e 'print if /{{regular_expression}}/'`
```

We prefer `path/to/file` placeholder.

2022-04-25 06:46 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +`cat {{filename}} | perl -n -l -e 'print $1 if /{{before}}({{pattern}}){{after}}/'`
```suggestion
`cat {{path/to/file}} | perl -n -l -e 'print $1 if /{{before}}({{regular_expression}}){{after}}/'`
```

2022-04-27 05:41 UTC, EmilySeville7cfg approved these changes
Just a few suggestions, everything else LGTM

2022-04-27 05:41 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +- Run a multi-line replacement expression on a file, and save the result in a specific file:
```suggestion
- Run a multi-line replacement [e]xpression on a file, and save the result in a specific file:
```

2022-04-27 05:41 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +- Run a regular expression on stdin, printing out matching [l]ines:
```suggestion
- Run a regular [e]xpression on stdin, printing out matching [l]ines:
```

2022-04-27 05:41 UTC, EmilySeville7cfg commented on pages/common/perl.md
> +- Run a regular expression on stdin, printing out only the first capture group for each matching [l]ine:
```suggestion
- Run a regular [e]xpression on stdin, printing out only the first capture group for each matching [l]ine:
```

2022-04-30 07:09 UTC, mfrw approved these changes
LGTM :)

2022-04-30 07:09 UTC, merged