rich: add page
tldr-pages/tldr pull request #8044
Opened 2022-04-22 02:35 UTC by nik-sm

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

1.6.0 - https://github.com/Textualize/rich-cli

2022-04-22 02:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8044) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8044) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8044) it.</sub>

2022-04-24 07:54 UTC, blueskyson reviewed
Thank you for contribution! We use `{{ ... }}` to highlight user-provided token, here are some suggestions.

2022-04-24 07:54 UTC, blueskyson commented on pages/common/rich.md
> +`rich file.py`
```suggestion
`rich {{path/to/file.py}}`
```

2022-04-24 07:54 UTC, blueskyson commented on pages/common/rich.md
> +`rich file.py --line-number --guides`
```suggestion
`rich {{path/to/file.py}} --line-number --guides`
```

2022-04-24 07:54 UTC, blueskyson commented on pages/common/rich.md
> +`rich file.py --theme monokai`
```suggestion
`rich {{path/to/file.py}} --theme {{monokai}}`
```

2022-04-24 07:54 UTC, blueskyson commented on pages/common/rich.md
> +`rich file.py --pager`
```suggestion
`rich {{path/to/file.py}} --pager`
```

2022-04-24 07:54 UTC, blueskyson commented on pages/common/rich.md
> +`rich https://raw.githubusercontent.com/Textualize/rich-cli/main/README.md --markdown --pager`
```suggestion
`rich {{https://raw.githubusercontent.com/Textualize/rich-cli/main/README.md}} --markdown --pager`
```

2022-04-24 07:54 UTC, blueskyson commented on pages/common/rich.md
> +`rich file.md -o file.html`
```suggestion
`rich {{path/to/file.md}} -o {{path/to/file.html}}`
```

2022-04-24 07:54 UTC, blueskyson commented on pages/common/rich.md
> +`rich --print "Hello [green on black]Stylized[/green on black] [bold]World[/bold]" --center --width 10`
```suggestion
`rich --print {{"Hello [green on black]Stylized[/green on black] [bold]World[/bold]"}} --center --width {{10}}`
```

2022-04-25 00:44 UTC, nik-sm commented
Thanks for the feedback! Let me know if any other changes would be useful

2022-04-25 06:31 UTC, EmilySeville7cfg requested changes

2022-04-25 06:31 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +- Show file contents with syntax highlighting:
```suggestion
- Show a specific file with syntax highlighting:
```

2022-04-25 06:31 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +- Apply a theme:
```suggestion
- Apply a specific theme:
```

2022-04-25 06:31 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +- Display file in an interactive pager:
```suggestion
- Display a specific file in an interactive pager:
```

2022-04-25 06:31 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +- Display contents from a URL:
```suggestion
- Display contents from a specific URL:
```

2022-04-25 06:31 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +- Export a file as HTML:
```suggestion
- Export a specific file as HTML:
```

2022-04-25 06:31 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +- Print text with formatting tags, custom alignment, and fixed line width:
```suggestion
- Display a text with specific formatting tags, alignment, and line width:
```

2022-04-25 06:31 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +`rich --print {{"Hello [green on black]Stylized[/green on black] [bold]World[/bold]"}} --center --width {{10}}`
```suggestion
`rich --print {{"Hello [green on black]Stylized[/green on black] [bold]World[/bold]"}} --{{left|center|right}} --width {{10}}`
```

2022-04-25 06:33 UTC, EmilySeville7cfg commented on pages/common/rich.md
> +- Show file contents with syntax highlighting:
@navarroaxel, what about to stick to `Display` word instead of `Print` in all pages?

2022-04-25 07:55 UTC, blueskyson approved these changes

2022-04-25 17:33 UTC, nik-sm commented
Hi there - thanks for the feedback! I incorporated some of the suggested changes above.
I removed the word `specific` to follow the grammatical style of a few other sample pages (`tldr cat`, `tldr pip`, `tldr vim`) - let me know what you think.

2022-04-26 10:49 UTC, navarroaxel commented on pages/common/rich.md
> +`rich {{path/to/file.md}} -o {{path/to/file.html}}`
We prefer long arguments if available
```suggestion
`rich {{path/to/file.md}} --export-html {{path/to/file.html}}`
```

2022-04-26 17:49 UTC, EmilySeville7cfg approved these changes

2022-04-26 17:49 UTC, merged

2022-04-26 17:50 UTC, EmilySeville7cfg commented
Merged, thanks? 👍🏻