Add @EmilySeville7cfg as an org member
tldr-pages/tldr pull request #8062
Opened 2022-04-28 10:00 UTC by EmilySeville7cfg

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-04-28 16:02 UTC, navarroaxel requested changes

2022-04-28 16:02 UTC, navarroaxel commented on MAINTAINERS.md
> +  [19 January 2022](https://github.com/tldr-pages/tldr/issues/1209#issuecomment-285924778) — [24 April 2022](https://github.com/tldr-pages/tldr/issues/8053)
Move this to the bottom of this section.

2022-04-28 17:23 UTC, navarroaxel commented on MAINTAINERS.md
> +- **Emily Grace Seville ([@EmilySeville7cfg](https://github.com/EmilySeville7cfg))**:
```suggestion
- Emily Grace Seville ([@EmilySeville7cfg](https://github.com/EmilySeville7cfg)):
```

2022-04-28 22:52 UTC, CleanMachine1 approved these changes
Welcome to the org!

2022-04-29 00:53 UTC, navarroaxel approved these changes

2022-04-29 00:54 UTC, merged