conntrack: add page
tldr-pages/tldr pull request #8081
Opened 2022-05-05 19:04 UTC by adrienthebo

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

Fedora 35 IoT, conntrack-tools-1.4.5-8.fc35.aarch64

2022-05-05 19:24 UTC, CleanMachine1 commented on pages/linux/conntrack.md
> +- Delete all flows to the given source IP address:
```suggestion
- Delete all flows to the specified source IP address:
```

2022-05-06 16:43 UTC, adrienthebo commented on pages/linux/conntrack.md
> +- Delete all flows to the given source IP address:
Applied in amended revision 1c134c63

2022-05-06 23:07 UTC, CleanMachine1 commented
Avoid force merging so that it is easier to view each and every commit

2022-05-07 13:58 UTC, mfrw approved these changes
LGTM :)
Thank you for your contribution

2022-05-08 11:19 UTC, EmilySeville7cfg requested changes
Looks nice, just one suggestion 😄

2022-05-08 11:19 UTC, EmilySeville7cfg commented on pages/linux/conntrack.md
> +- Delete all flows to the specified source IP address:
```suggestion
- Delete all flows for a specific source IP address:
```

2022-05-14 07:06 UTC, EmilySeville7cfg approved these changes

2022-05-14 07:06 UTC, merged

2022-05-14 07:06 UTC, EmilySeville7cfg commented
Merged, thanks! ❤️