sqlite-utils: add page
tldr-pages/tldr pull request #8088
Opened 2022-05-13 01:49 UTC by jeffabailey

- [ x] The page (if new), does not already exist in the repository.
- [ x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ x] The page has 8 or fewer examples.
- [ x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

3.26

2022-05-13 01:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8088) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8088) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8088) it.</sub>

2022-05-16 08:30 UTC, owenvoke requested changes
Hi @jeffabailey, just a couple of tweaks you can make to add token syntax. 👍🏻

2022-05-16 08:30 UTC, owenvoke commented on pages/common/sqlite-utils.md
> +`sqlite-utils create-database person.db`
```suggestion
`sqlite-utils create-database {{path/to/database.db}}`
```

2022-05-16 08:30 UTC, owenvoke commented on pages/common/sqlite-utils.md
> +`sqlite-utils create-table person.db people id integer name text height float photo blob --pk id`
```suggestion
`sqlite-utils create-table {{path/to/database.db}} {{table_name}} {{id integer name text height float photo blob --pk id}}`
```

2022-05-16 08:30 UTC, owenvoke commented on pages/common/sqlite-utils.md
> +`echo '[ {"id": 1, "name": "Linus Torvalds"}, {"id": 2, "name": "Steve Wozniak"}, {"id": 3, "name": "Tony Hoare"} ]' | sqlite-utils upsert person.db people - --pk id`
```suggestion
`{{echo '[ {"id": 1, "name": "Linus Torvalds"}, {"id": 2, "name": "Steve Wozniak"}, {"id": 3, "name": "Tony Hoare"} ]'}} | sqlite-utils upsert {{path/to/database.db}} {{table_name}} - {{--pk id}}`
```

2022-05-16 08:30 UTC, owenvoke commented on pages/common/sqlite-utils.md
> +`sqlite-utils rows person.db people`
```suggestion
`sqlite-utils rows {{path/to/database.db}} {{table_name}}`
```

2022-05-16 08:30 UTC, owenvoke commented on pages/common/sqlite-utils.md
> +`sqlite-utils query person.db "delete from people where name = 'Tony Hoare'"`
```suggestion
`sqlite-utils query {{path/to/database.db}} {{"delete from people where name = 'Tony Hoare'"}}`
```

2022-05-16 08:30 UTC, owenvoke commented on pages/common/sqlite-utils.md
> +`sqlite-utils drop-table person.db people`
```suggestion
`sqlite-utils drop-table {{path/to/database.db}} {{table_name}}`
```

2022-05-19 17:17 UTC, owenvoke approved these changes

2022-05-21 18:58 UTC, navarroaxel commented on pages/common/sqlite-utils.md
> +`sqlite-utils query {{path/to/database.db}} {{"delete from {{table_name}} where name = 'Tony Hoare'"}}`
By convention we use quotes `"` outside the token syntax. Also, the token syntax can't be nested, it's a markdown spec
```suggestion
`sqlite-utils query {{path/to/database.db}} "{{delete from table_name where name = 'Tony Hoare'}}"`
```

2022-05-21 18:59 UTC, navarroaxel commented on pages/common/sqlite-utils.md
> +`sqlite-utils query {{path/to/database.db}} {{"delete from {{table_name}} where name = 'Tony Hoare'"}}`
I'll apply this quick fix, then merge.

2022-05-21 18:59 UTC, navarroaxel approved these changes

2022-05-21 19:00 UTC, merged