Create ls.md
tldr-pages/tldr pull request #8143
Opened 2022-06-22 08:35 UTC by dengshenkk

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-06-22 08:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8143) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8143) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8143) it.</sub>

2022-06-22 10:54 UTC, einverne requested changes
Thank you for the new translation, however `ls` command already in `pages.zh/common` folder.

2022-07-08 10:03 UTC, marchersimon commented
@dengshenkk could you please apply the suggestions above?

2022-07-10 05:13 UTC, navarroaxel commented on pages.zh/linux/ls.md
> +- 列出所有文件, 并按文件大小降序排序:
```suggestion
- 列出所有文件, 并按文件大小降序排序：
```

2022-07-10 05:13 UTC, navarroaxel commented on pages.zh/linux/ls.md
> +- 列出所有文件, 并按修改时间降序排序:
```suggestion
- 列出所有文件, 并按修改时间降序排序：
```

2022-07-10 05:13 UTC, navarroaxel commented on pages.zh/linux/ls.md
> +- 列出所有文件, 包含隐藏文件以及显示权限,拥有者,文件大小和修改日期:
```suggestion
- 列出所有文件, 包含隐藏文件以及显示权限,拥有者,文件大小和修改日期：
```

2022-07-10 05:13 UTC, navarroaxel commented on pages.zh/linux/ls.md
> +- 列出所有文件, 包含隐藏文件:
```suggestion
- 列出所有文件, 包含隐藏文件：
```

2022-07-10 05:13 UTC, navarroaxel commented on pages.zh/linux/ls.md
> +- 以人类可读的文件大小单位列出文件列表(KB,MB,GB等)
```suggestion
- 以人类可读的文件大小单位列出文件列表(KB,MB,GB等)：
```

2022-07-10 05:13 UTC, navarroaxel commented on pages.zh/linux/ls.md
> +- 列出所有文件, 并在文件类型后面添加对应类型的符号(如目录会加上"/"):
```suggestion
- 列出所有文件, 并在文件类型后面添加对应类型的符号(如目录会加上"/")：
```

2022-07-10 05:14 UTC, navarroaxel approved these changes

2022-07-10 09:50 UTC, marchersimon requested changes
Wait. There's a few things wrong with this.
First, there is no `ls` in the `linux` directory. Second, some examples are in the wrong order, and the last one is missing completely

2022-07-10 10:01 UTC, marchersimon commented
@dengshenkk could you please make sure your page is an exact translation of [this page](https://github.com/tldr-pages/tldr/blob/main/pages/common/ls.md)? Otherwise we would have to close this PR.

2022-07-26 06:48 UTC, marchersimon commented
Ping @dengshenkk

2022-07-27 23:42 UTC, CleanMachine1 commented
I think the waiting tag should be added, I think it is entirely the purpose of the stalebot

2022-08-28 00:03 UTC, closed without merging

2022-11-17 06:22 UTC, dengshenkk commented
@marchersimon I don't how do it about this https://github.com/tldr-pages/tldr/pull/8143#issuecomment-1162817211