calc: add examples
tldr-pages/tldr pull request #8149
Opened 2022-06-23 18:46 UTC by marchersimon

#8148 has to be merged first

calc version 2.14.0.8

2022-06-26 18:59 UTC, navarroaxel commented
@marchersimon please resolve conflicts.

2022-07-15 14:57 UTC, EmilySeville7cfg requested changes

2022-07-15 14:57 UTC, EmilySeville7cfg commented on pages/common/calc.md
> +- Perform a calculation in non-interactive mode and exit:
```suggestion
- Perform a calculation in non-interactive mode:
```

If we assume that smth in non-interactive mode is exited by default then `and exit` is not necessary.

2022-07-15 14:57 UTC, EmilySeville7cfg commented on pages/common/calc.md
> +`calc help`
It's better to put this example to the bottom.

2022-07-15 14:57 UTC, EmilySeville7cfg commented on pages/common/calc.md
> +- Perform a calculation and then switch to interactive mode:
```suggestion
- Perform a calculation and then switch to [i]nteractive mode:
```

2022-07-15 15:07 UTC, EmilySeville7cfg commented
@marchersimon, you forgot to apply the same fixes to another page. 😄

2022-07-15 15:12 UTC, marchersimon commented
At it, I'm currently trying to set up my Github GPG key for my new machine

2022-07-16 20:52 UTC, navarroaxel approved these changes

2022-07-16 20:52 UTC, merged