tailscale-ssh: add page
tldr-pages/tldr pull request #8151
Opened 2022-06-24 02:34 UTC by mfrw

Closes: #8150

Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-06-24 11:17 UTC, einverne reviewed
It looks like tailscale ssh is a sub command of tailscale, and even there is no `tailscale ssh` sub command, should we merge these examples into `tailscale up`?

2022-06-24 11:55 UTC, navarroaxel commented
@einverne `tailscale up` has a lot of options, maybe the turn on/off the SSH should be in this page.

2022-06-24 12:25 UTC, mfrw commented
> @einverne `tailscale up` has a lot of options, maybe the turn on/off the SSH should be in this page.

It already had 8 examples and all of them seemed important; which is the reason I added these here.

2022-06-28 01:28 UTC, sbrl commented
> and even there is no tailscale ssh sub command


I'm confused. In this page, there's the example `tailscale ssh {{user}}@{{host}}`. Does the `ssh` subcommand exist, or not?

Either way, the title of a page *must* match the command name. For example, `awk.md` is the page for `awk`, `docker-ps.md` is the page for `docker ps`, and so on. The only exception is special case disambiguation pages such as `cgroups` for things users will commonly type.

2022-06-28 03:08 UTC, mfrw commented
> > and even there is no tailscale ssh sub command
> 
> I'm confused. In this page, there's the example `tailscale ssh {{user}}@{{host}}`. Does the `ssh` subcommand exist, or not?
> 
> Either way, the title of a page _must_ match the command name. For example, `awk.md` is the page for `awk`, `docker-ps.md` is the page for `docker ps`, and so on. The only exception is special case disambiguation pages such as `cgroups` for things users will commonly type.
> 
> To this end, if the `tailscale ssh` subcommand does not exist, I'm not sure we can accept this. The art of writing a tldr page is distilling the most useful knowledge down into a quick reference for new and experienced users alike - not providing comprehensive documentation.

`tailscale ssh` subcommand exists :)
The benefit of `tailscale ssh` is `password-less/key-less access` to host machines.
Ideally the options to `enable/disable` ssh should be in the `tailscale up` page, but that page already has 8 examples which are all pretty usefull.
Since `enable/disable` seemed helpful and make more sense here, it is the reason I added them here :)

![image](https://user-images.githubusercontent.com/4929861/176083523-84198071-dbc6-4a17-84f3-beff3a9a7d24.png)

2022-06-28 21:11 UTC, sbrl commented
Thanks for clarifying, @mfrw! In this case, are the `sudo tailscale up` commands required for using the `tailscale ssh` command?

2022-06-28 21:12 UTC, navarroaxel commented
> Thanks for clarifying, @mfrw! In this case, are the `sudo tailscale up` commands required for using the `tailscale ssh` command?

@sbrl The `--ssh=true` is required to enable this SSH feature.

2022-06-28 23:52 UTC, mfrw commented
> Thanks for clarifying, @mfrw! In this case, are the `sudo tailscale up` commands required for using the `tailscale ssh` command?

Yep, good catch. we do need `sudo`.
Fixing :)

2022-06-29 08:47 UTC, EmilySeville7cfg requested changes

2022-06-29 08:47 UTC, EmilySeville7cfg commented on pages/common/tailscale-ssh.md
> +- SSH to a host which has Tailscale-SSH enabled:
```suggestion
- SSH to a specific host which has Tailscale-SSH enabled:
```

2022-06-29 22:45 UTC, sbrl approved these changes

2022-06-29 23:05 UTC, EmilySeville7cfg approved these changes

2022-06-30 00:37 UTC, mfrw commented on pages/common/tailscale-ssh.md
> +- Advertise/Disable SSH on the host:
I was of the opinion to keep it `/` and keep it abstract :)

2022-06-30 00:39 UTC, merged