gnome-screenshot: replace dead link
tldr-pages/tldr pull request #8153
Opened 2022-06-25 14:34 UTC by centaurii44

- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-06-25 14:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8153) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8153) it.</sub>

2022-06-25 20:27 UTC, navarroaxel requested changes

2022-06-25 20:27 UTC, navarroaxel commented on pages/linux/gnome-screenshot.md
> +> More information: <https://linux.die.net/man/1/gnome-screenshot>.
We prefer manned over linux.die.net
```suggestion
> More information: <https://manned.org/gnome-screenshot>.
```

2022-06-26 03:02 UTC, mfrw approved these changes
Thanks @centaurii44.

2022-06-26 03:03 UTC, navarroaxel approved these changes

2022-06-26 03:03 UTC, merged