gdalinfo: add page
tldr-pages/tldr pull request #8162
Opened 2022-06-27 19:30 UTC by JakobMiksch

Add the CLI tool [gdalinfo](https://gdal.org/programs/gdalinfo.html) from the GDAL/OGR suite.

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**
3.2.2

2022-06-28 01:23 UTC, einverne approved these changes
LGTM.

2022-06-29 08:41 UTC, EmilySeville7cfg requested changes

2022-06-29 08:41 UTC, EmilySeville7cfg commented on pages/common/gdalinfo.md
> +- List supported raster formats:
```suggestion
- List all supported raster formats:
```

2022-06-29 10:39 UTC, JakobMiksch reviewed
@EmilySeville7cfg Thanks for your review. I addressed your notes.

2022-06-29 10:39 UTC, JakobMiksch commented on pages/common/gdalinfo.md
> +`gdalinfo --formats`
It definitely exists. I tried it locally.
See the [official docs](https://gdal.org/programs/raster_common_options.html#cmdoption-formats). There `--formats` is listed as common option for all GDAL raster programs.

2022-06-29 11:19 UTC, EmilySeville7cfg approved these changes

2022-07-14 03:15 UTC, einverne approved these changes

2022-07-15 14:10 UTC, merged

2022-07-15 14:10 UTC, EmilySeville7cfg commented
Merged, thanks! ❤️

2022-07-17 18:18 UTC, JakobMiksch commented
Thanks as well :-)