gdal_contour: add page
tldr-pages/tldr pull request #8200
Opened 2022-07-11 19:49 UTC by JakobMiksch

Add the CLI tool [gdalinfo](https://gdal.org/programs/gdalinfo.html) from the GDAL/OGR suite.

- [x] The page (if new), does not already exist in the repository.
- [x] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [x] The page has 8 or fewer examples.
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [x] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**
3.2.2

2022-07-12 07:56 UTC, reinhart1010 requested changes
It might be better to place some mnemonic tags here, as `gdal_contour` unfortunately doesn't put longer parameter names (e.g. `--attribute` instead of `-a`) which are more preferred for writing tldr-pages.

2022-07-12 07:56 UTC, reinhart1010 commented on pages/common/gdal_contour.md
> +- Create a vector dataset with polygons every 100 meter:
```suggestion
- Create a vector dataset with [p]olygons spread over an 100-meter [i]nterval:
```

2022-07-12 07:56 UTC, reinhart1010 commented on pages/common/gdal_contour.md
> +- Create a vector dataset with contour lines every 100 meter and name the elevation property "ele":
```suggestion
- Create a vector dataset with contour lines spread over a 100-meter [i]nterval while [a]ttributing the elevation property as "ele":
```

2022-07-13 19:25 UTC, JakobMiksch commented
@reinhart1010 thanks for your review, I applied your suggestions.

2022-07-21 11:03 UTC, marchersimon approved these changes
Looks good, thanks

2022-07-25 06:30 UTC, reinhart1010 approved these changes
Thanks!

2022-07-25 06:30 UTC, merged