python3: add -m venv example
tldr-pages/tldr pull request #8214
Opened 2022-07-15 06:32 UTC by linpan

- [ ] The page (if new), does not already exist in the repository.
- [ ] The page is in the correct platform directory (`common/`, `linux/`, etc.)
- [ ] The page has 8 or fewer examples.
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- [ ] The page follows the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The page description includes a link to documentation or a homepage (if applicable).

**Version of the command being documented (if known):**

2022-07-15 06:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8214) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8214) before we can accept your contribution.<br/><hr/>**hiro** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8214) it.</sub>

2022-07-16 11:07 UTC, EmilySeville7cfg requested changes

2022-07-16 11:07 UTC, EmilySeville7cfg commented on pages/common/python.md
> +`python3 -m venv {{path/to/myenv}}`
```suggestion
`python3 -m venv {{path/to/environment}}`
```

2022-07-16 11:52 UTC, CleanMachine1 commented
Please sign the the CLA otherwise we cannot merge this PR.

2022-07-18 11:08 UTC, EmilySeville7cfg approved these changes

2022-07-18 11:11 UTC, EmilySeville7cfg commented
Is 3rd example very useful? I am not sure what code example to remove but it must be done to successfully pass linter checks.

2022-07-18 16:02 UTC, CleanMachine1 submitted a review, later dismissed

2022-07-18 22:00 UTC, CleanMachine1 commented
https://github.com/tldr-pages/tldr/blob/main/contributing-guides/git-terminal.md#changing-the-email-of-any-commits

this maybe useful for the CLA issue.

2022-08-04 03:45 UTC, linpan commented
so long wait for winter

2022-08-04 08:12 UTC, EmilySeville7cfg requested changes

2022-08-04 08:12 UTC, EmilySeville7cfg commented on pages/common/python.md
> +`python3 -m venv {{path/to/environment}}`
```suggestion
`python3 -m venv {{path/to/environment1 path/to/environment2 ...}}`
```

2022-08-06 10:54 UTC, EmilySeville7cfg approved these changes

2022-08-08 08:03 UTC, marchersimon commented
@linpan could you please make sure the CLA is fully signed and the page doesn't have more than 8 examples?

2022-09-01 23:45 UTC, EmilySeville7cfg commented
Sorry, I just wanted these old PRs not to be closed and merged after at least two approvals.

2022-09-02 01:56 UTC, CleanMachine1 commented
I don't think there is much we can do when the CLA is not completely signed, even if the author has signed it on 1 email.

2022-10-03 00:04 UTC, closed without merging