new page" grafana-cli
tldr-pages/tldr pull request #8299
Opened 2022-08-04 07:30 UTC by hellojukay

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-08-04 08:42 UTC, EmilySeville7cfg requested changes

2022-08-04 08:42 UTC, EmilySeville7cfg commented on pages/linux/grafana-cli.md
> +- Install a grafana plugin:
```suggestion
- Install/update/remove specific plugins:
```

This page already describes `grafana-cli`, it's not needed to mention it explicitly.

2022-08-04 08:42 UTC, EmilySeville7cfg commented on pages/linux/grafana-cli.md
> +`grafana-cli plugins install "{{plugin-id}}"`
```suggestion
`grafana-cli plugins {{install|update|remove}} {{plugin_id1 plugin_id2 ...}}`
```

If you know that plugin id doesn't contain spaces in it or documentation states it explicitly please remove quotes.

2022-08-04 08:42 UTC, EmilySeville7cfg commented on pages/linux/grafana-cli.md
> +`grafana-cli plugins remove "{{plugin-id}}"`
This example can be joined with the first one.

2022-08-04 09:50 UTC, EmilySeville7cfg approved these changes

2022-08-04 21:36 UTC, CleanMachine1 approved these changes

2022-08-05 07:15 UTC, marchersimon commented on pages/linux/grafana-cli.md
> +> More information: <https://grafana.com>.
```suggestion
> More information: <https://grafana.com/docs/grafana/latest/cli/>.
```

2022-08-05 07:15 UTC, marchersimon commented on pages/linux/grafana-cli.md
> +- Install/update/remove specific plugins:
```suggestion
- Install, update, or remove specific plugins:
```

2022-08-05 07:15 UTC, marchersimon commented on pages/linux/grafana-cli.md
> +- List installed plugins:
```suggestion
- List all installed plugins:
```

2022-08-05 08:23 UTC, marchersimon approved these changes
Thanks @hellojukay

2022-08-05 08:25 UTC, marchersimon requested changes
I just noticed that this page should be moved to the `common` directory, as it's also available on OSX and Windows

2022-08-05 08:36 UTC, marchersimon approved these changes
👍🏽

2022-08-05 08:36 UTC, merged