feh: add Spanish translation
tldr-pages/tldr pull request #8332
Opened 2022-08-09 17:51 UTC by alexmailo

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-08-09 17:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8332) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8332) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8332) it.</sub>

2022-08-09 17:55 UTC, marchersimon reviewed
Thanks for your contribution. I just noticed some minor errors.

2022-08-09 17:55 UTC, marchersimon commented on pages.es/common/feh.md
> +# feh
```suggestion
# feh
```

2022-08-09 17:55 UTC, marchersimon commented on pages.es/common/feh.md
> +- Para ver imagenes recursivamente :
```suggestion
- Para ver imagenes recursivamente:
```

2022-08-09 17:55 UTC, marchersimon commented on pages.es/common/feh.md
> +- Cambia tu fondo de pantalla (centrado, llenar, maximizado, ampliado o amontonado ):
```suggestion
- Cambia tu fondo de pantalla (centrado, llenar, maximizado, ampliado o amontonado):
```

2022-08-09 17:55 UTC, marchersimon commented
And there's no need to force-push @alexmailo. We squash all commits anyways when we merge.

2022-08-09 19:34 UTC, CleanMachine1 commented
Let @navarroaxel merge since he can guarantee the quality of this page and find any errors (if there are any)

2022-08-09 22:13 UTC, navarroaxel requested changes
Hi @alexmailo, welcome and thanks for your submission. I don't like the terms used in the English page, but I made some suggestions to the translation.

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Para cerrar despues de una imagen:
```suggestion
- Cierra después de la última imagen:
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Agrega una demora a la presentacion:
Perhaps this better
```suggestion
- Agrega una demora al ciclo de la presentacion:
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Para ver imagenes sin bordes:
```suggestion
- Muestra imágenes sin bordes:
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Para ver imagenes recursivamente:
```suggestion
- Muestra imágenes recursivamente:
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Para imagenes locales o de URL:
```suggestion
- Muestra imágenes localmente o usando una URL:
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Crea un montage de todas las imagenes en un directorio. Produce una nueva imagen.
```suggestion
- Crea un montage de todas las imágenes en un directorio. Produce una nueva imagen.
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Cambia tu fondo de pantalla (centrado, llenar, maximizado, ampliado o amontonado):
```suggestion
- Cambia el fondo de pantalla (centrado, llenar, maximizado, ampliado o amontonado):
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +> Para mas informacion: <https://feh.finalrewind.org>.
```suggestion
> Más información: <https://feh.finalrewind.org>.
```

2022-08-09 22:13 UTC, navarroaxel commented on pages.es/common/feh.md
> +> Visor de imagenes.
```suggestion
> Utilidad ligera de visualización de imágenes.
```

2022-08-10 12:12 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Agrega una demora al ciclo de la presentacion:
I forgot this
```suggestion
- Agrega una demora al ciclo de la presentación:
```

2022-08-10 12:12 UTC, navarroaxel commented on pages.es/common/feh.md
> +- Crea un montage de todas las imágenes en un directorio. Produce una nueva imagen.
```suggestion
- Crea un montage de todas las imágenes en un directorio. Produce una nueva imagen:
```

2022-08-10 19:34 UTC, navarroaxel approved these changes

2022-08-14 00:20 UTC, CleanMachine1 approved these changes

2022-08-14 00:20 UTC, merged