databricks: new page
tldr-pages/tldr pull request #8342
Opened 2022-08-12 14:02 UTC by paprocki-r

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-08-12 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8342) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8342) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8342) it.</sub>

2022-08-12 16:43 UTC, kbdharun commented
@paprocki-r you need to sign the contributor license for this PR to go through. Please click on the link in CLAassistant's comment above and complete it.

2022-08-13 01:10 UTC, EmilySeville7cfg requested changes

2022-08-13 01:10 UTC, EmilySeville7cfg commented on pages/common/databricks.md
> +- set up host (https address of your databricks environment) and token (generated from databrics' settings)
```suggestion
- Set up the current host (https address of your databricks environment) and token (generated from databrics' settings)
```

2022-08-13 01:10 UTC, EmilySeville7cfg commented on pages/common/databricks.md
> +- list workspace content:
```suggestion
- List the current workspace content:
```

I don't see where workspace is specified so I assume we are talking about the current workspace.

2022-09-26 20:50 UTC, CleanMachine1 commented
Hi, due to the fact this PR has been unattended with errors, and the CI has not been signed, I am closing this.

2022-09-26 20:50 UTC, closed without merging