adb-logcat: add page(copied from logcat.md and enriched its examples)
tldr-pages/tldr pull request #8424
Opened 2022-08-29 09:59 UTC by HUGHNew

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2022-08-29 12:07 UTC, kbdharun requested changes
Welcome to tldr @HUGHNew , I have requested some changes that need to be addressed.

2022-08-29 12:07 UTC, kbdharun commented on pages/common/adb-logcat.md
> +- Color the log(usually use with filters)
```suggestion
- Color the log(usually use with filters):
```

2022-08-29 12:07 UTC, kbdharun commented on pages/common/adb-logcat.md
> +# logcat
```suggestion
# adb-logcat
```
Even though it is an extension of `logcat` , I think mentioning `adb-logcat` would be better

2022-08-31 11:26 UTC, HUGHNew commented
> Welcome to tldr @HUGHNew , I have requested some changes that need to be addressed.

Thanks for your advice.

2022-08-31 12:08 UTC, kbdharun approved these changes

2022-08-31 16:37 UTC, CleanMachine1 commented on pages/common/adb-logcat.md
> +- Filter the log with filterspecs(`{{complete_tag:[V | D | I | W | E | F | S]}}`), `*` for all but not a wildcard(`*:S` suppresses others)
I think we should change this as well. Its quite confusing.

2022-09-01 12:03 UTC, navarroaxel commented on pages/common/adb-logcat.md
> +`adb logcat {{tag0:V}} {{tag1:D}} *:S`
I think we can split this into 3 examples to be easier to understand
```suggestion
- Display logs for a tag in a specific mode ([V]erbose, [D]ebug, [I]nfo, [W]arning, [E]rror, [F]atal, [S]ilent), filtering other tags:

`adb logcat {{tag}}:{{mode}} *:S`

- Display logs for React Native applications in [V]erbose mode [S]ilencing other tags:

`adb logcat ReactNative:V ReactNativeJS:V *:S`

- Display logs for all tags with priority level [W]arning and higher:

`adb logcat *:W`
```

2022-09-01 20:04 UTC, CleanMachine1 commented on pages/common/adb-logcat.md
> +- Color the log(usually use with filters):
```suggestion
- Color the log (usually use with filters):
```

2022-09-01 20:04 UTC, CleanMachine1 approved these changes

2022-09-01 21:15 UTC, navarroaxel commented on pages/common/adb-logcat.md
> +- Color the log(usually use with filters):
I'll apply this tiny fix and merge it.

2022-09-01 21:15 UTC, navarroaxel approved these changes

2022-09-01 21:16 UTC, merged