npm-fund: add page
tldr-pages/tldr pull request #8495
Opened 2022-09-17 14:44 UTC by kbdharun

- [x] The page(s) are in the correct platform directories: `common`.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** 8.19.2

2022-09-17 16:17 UTC, CleanMachine1 commented on pages/common/npm-fund.md
> +> More information: <https://docs.npmjs.com/cli/v7/commands/npm-fund>.
```suggestion
> More information: <https://docs.npmjs.com/cli/v8/commands/npm-fund>.
```

2022-09-18 14:52 UTC, EmilySeville7cfg requested changes

2022-09-18 15:13 UTC, EmilySeville7cfg approved these changes

2022-09-18 21:14 UTC, navarroaxel commented on pages/common/npm-fund.md
> +- Fund a specific package:
```suggestion
- Open the funding URL for a specific package in the default web browser:
```

2022-09-18 21:14 UTC, navarroaxel commented on pages/common/npm-fund.md
> +- Fund dependencies by filtering a specific [w]orkspace in the current project:
```suggestion
- List dependencies with a founding URL for a specific [w]orkspace for the project in the current directory:
```

2022-09-18 21:14 UTC, navarroaxel commented on pages/common/npm-fund.md
> +- List information on funding dependencies of the current project:
```suggestion
- List dependencies with funding URL for the project in the current directory:
```

2022-09-18 23:58 UTC, navarroaxel commented on pages/common/npm-fund.md
> +> Retrive funding information.
```suggestion
> Retrieve funding information from packages.
```

2022-09-19 00:00 UTC, navarroaxel approved these changes

2022-09-19 00:00 UTC, merged