osmium: add file
tldr-pages/tldr pull request #8535
Opened 2022-09-27 19:45 UTC by JakobMiksch

- Add the CLI tool [osmium](https://osmcode.org/osmium-tool/manual)
- Version of the command: `1.14.0`

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-09-28 02:52 UTC, kbdharun requested changes
Thanks for your contribution @JakobMiksch, I have some suggestions for this page. We prefer placing the file extensions inside along with the path for example `{{path/to/file.exe}}`.

Tip: Batch all suggestions from the files tab and make it a single commit. or if you are using GitHub on mobile use the web version of GitHub to do the same.

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium fileinfo {{path/to/input}}.osm`
```suggestion
`osmium fileinfo {{path/to/input.osm}}`
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium show {{path/to/input}}.osm`
```suggestion
`osmium show {{path/to/input.osm}}`
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium cat {{path/to/input}}.osm.pbf -o {{path/to/output}}.osm`
```suggestion
`osmium cat {{path/to/input.osm.pbf}} -o {{path/to/output.osm}}`
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium extract -b {{min_longitude}},{{min_latitude}},{{max_longitude}},{{max_latitude}} {{path/to/input}}.pbf -o {{path/to/output}}.pbf`
```suggestion
`osmium extract -b {{min_longitude}},{{min_latitude}},{{max_longitude}},{{max_latitude}} {{path/to/input.pbf}} -o {{path/to/output.pbf}}`
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +- Extract a geographic region by the given bounding box:
```suggestion
- Extract a geographic region by the given [b]ounding box:
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium extract -p {{path/to/polygon}}.geojson {{path/to/input}}.pbf -o {{path/to/output}}.pbf`
```suggestion
`osmium extract -p {{path/to/polygon.geojson}} {{path/to/input.pbf}} -o {{path/to/output.pbf}}`
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium tags-filter {{path/to/input}}.pbf amenity=restaurant -o {{path/to/output}}.pbf`
```suggestion
`osmium tags-filter {{path/to/input.pbf}} amenity=restaurant -o {{path/to/output.pbf}}`
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium tags-filter {{path/to/input}}.pbf w/highway -o {{path/to/output}}.pbf`
```suggestion
`osmium tags-filter {{path/to/input.pbf}} w/highway -o {{path/to/output.pbf}}`
```

2022-09-28 02:52 UTC, kbdharun commented on pages/common/osmium.md
> +`osmium tags-filter {{path/to/input}}.pbf wr/building -o {{path/to/output}}.pbf`
```suggestion
`osmium tags-filter {{path/to/input.pbf}} wr/building -o {{path/to/output.pbf}}`
```

2022-09-28 16:08 UTC, JakobMiksch commented
thanks @kbdharun for your review!
I applied your suggestions :+1:

2022-09-28 16:11 UTC, kbdharun approved these changes

2022-09-29 01:49 UTC, einverne approved these changes
LGTM.

2022-09-29 07:23 UTC, merged