qmrestore: add German translation
tldr-pages/tldr pull request #8791
Opened 2022-10-07 07:33 UTC by Braintelligence

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**
version 7.2, Wed 04 May 2022 07:30:00 AM CEST ( https://pve.proxmox.com/pve-docs/qmrestore.1.html )

2022-10-07 08:10 UTC, kbdharun requested changes
Note to maintainers: Review this PR after #8790 's merge.

2022-10-09 21:54 UTC, Braintelligence commented
FYI #8790 was merged 💃

2022-10-09 22:01 UTC, navarroaxel commented on pages.de/linux/qmrestore.md
> +> Weitere Informationen (Englisch): <https://pve.proxmox.com/pve-docs/qmrestore.1.html>.
We have an standard translation for this
```suggestion
> Weitere Informationen: <https://pve.proxmox.com/pve-docs/qmrestore.1.html>.
```

2022-10-10 01:23 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2022-10-10 01:36 UTC, navarroaxel approved these changes

2022-10-10 01:36 UTC, merged