tc: add page
tldr-pages/tldr pull request #8795
Opened 2022-10-07 10:08 UTC by NimrodRak

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-07 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8795) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8795) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8795) it.</sub>

2022-10-08 01:52 UTC, einverne requested changes
Hi @NimrodRak  Thank you for the new page. It seems that `tc` command is complex. I left some suggestions for you to take a look.

2022-10-08 01:52 UTC, einverne commented on pages/linux/tc.md
> +`tc qdisc change dev eth0 root netem {{policy}} {{policy_parameters}}`
```suggestion
`tc qdisc change dev {{eth0}} root netem {{policy}} {{policy_parameters}}`
```

2022-10-08 21:00 UTC, NimrodRak commented
yup missed those, thx!

2022-10-09 01:35 UTC, einverne approved these changes
Looks good now.

2022-10-09 07:14 UTC, kbdharun approved these changes
LGTM, Welcome to tldr and thanks for your contribution.

2022-10-10 13:57 UTC, navarroaxel approved these changes

2022-10-10 13:58 UTC, merged