Linux hindi commands
tldr-pages/tldr pull request #8815
Opened 2022-10-08 09:59 UTC by lucifertrj

Added `reset.md`, `reboot.md` and `cpuid.md` commands details in hindi.

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-08 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8815) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8815) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8815) it.</sub>

2022-10-08 12:29 UTC, suyashbhawsar commented
Hello, it'd be better if you create separate pull requests for each page.

2022-10-08 13:21 UTC, blueskyson commented
Thanks for contribution. You can keep working on this pull request. Please sign the [Contributor License Aggrement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8815) and fix the syntax errors.

2022-10-08 13:26 UTC, suyashbhawsar requested changes

2022-10-08 13:26 UTC, suyashbhawsar commented on pages.hi/linux/free.md
> +`free -h'
Use this line instead `free -h`

2022-10-08 13:28 UTC, suyashbhawsar requested changes

2022-10-08 13:28 UTC, suyashbhawsar commented on pages.hi/linux/free.md
> +`free -h'
Check this line, you've used quote instead of a backtick

2022-10-08 15:17 UTC, lucifertrj commented
> Thanks for contribution. You can keep working on this pull request. Please sign the [Contributor License Aggrement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8815) and fix the syntax errors.

Done.

2022-10-08 15:26 UTC, suyashbhawsar commented
Check if you have any whitespaces at the blank new lines or after any sentences

2022-10-08 16:46 UTC, lucifertrj commented
I fixed the whitespace bug. And also agreed to CLA License

![Screenshot from 2022-10-08 22-15-32](https://user-images.githubusercontent.com/66197713/194718298-1afa8f17-a667-419d-917e-203130542597.png)
![Screenshot from 2022-10-08 22-15-04](https://user-images.githubusercontent.com/66197713/194718300-1ecb840e-df8d-422b-b8ef-282a9438b358.png)

2022-10-08 17:23 UTC, blueskyson commented
It seems that your CLA status is still pending, could you try to sign again and check the github account is correspond to your local git? (I used to face this situation when my user.email was wrongly set)

2022-10-08 18:21 UTC, lucifertrj commented
![IMG_20221008_234927](https://user-images.githubusercontent.com/66197713/194721941-6be7ad2f-e2a9-439e-917a-0449e72239f4.jpg)

I have tried multiple times. I checked my config details, but still it is showing pending. When I open CLA link it is redirecting me back to GitHub.

2022-10-08 20:19 UTC, navarroaxel approved these changes

2022-10-08 20:19 UTC, navarroaxel commented on pages.hi/linux/cpuid.md
> +> अधिक जानकार: <http://etallen.com/cpuid.html>.
We use this standard translation
```suggestion
> अधिक जानकारी: <http://etallen.com/cpuid.html>.
```

2022-10-09 03:36 UTC, blueskyson approved these changes

2022-10-09 05:50 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2022-10-09 05:50 UTC, merged

2022-10-09 06:01 UTC, lucifertrj commented
> LGTM, Thanks for your contribution.

You forgot to add Hacktoberfest label

2022-10-09 06:03 UTC, navarroaxel commented
@lucifertrj I can add it, but I think it's not required :think

2022-10-09 06:03 UTC, kbdharun commented
It isn't necessary to add the `hacktoberfest` label separately as our repository already has `hactoberfest` in its topic. This PR will soon be reflected in your profile. Thanks for your contribution.

2022-10-09 06:03 UTC, suyashbhawsar commented
> @lucifertrj I can add it, but I think it's not required :thinking: 

Yup it's not required

2022-10-09 06:04 UTC, suyashbhawsar commented
> > LGTM, Thanks for your contribution.
> 
> 
> 
> You forgot to add Hacktoberfest label

Your PR is going to be counted as 1/4 so, I'd recommend you to create different PRs for different pages