g++, gcc, java, json5, python: add Nepali translation
tldr-pages/tldr pull request #8821
Opened 2022-10-08 13:53 UTC by animeshdhakal

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-08 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8821) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8821) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8821) it.</sub>

2022-10-08 14:14 UTC, kbdharun requested changes
Welcome to tldr, Thanks for your contribution. 

Translate paths and other command arguments inside `{{}}`.

2022-10-08 14:17 UTC, kbdharun commented
If possible can you add Nepali words to [common-arguments](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/common-arguments.md) in a new PR above `nl` as it will be a helpful reference for reviewers and other translators in future?

> Thanks in advance

2022-10-08 15:03 UTC, animeshdhakal commented
> Welcome to tldr, Thanks for your contribution.
> 
> Translate paths and other command arguments inside `{{}}`.

Updated the Translations

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/g++.md
> +`g++ {{स्रोतफाइल/को/पथ}} -o {{आउटपुट/को/पथ}}`
```suggestion
`g++ {{स्रोतफाइल.cpp/को/पथ}} -o {{आउटपुट/को/पथ}}`
```

If possible can you mention the executable too in the output path?
Update this throughout all pages in this PR.

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/g++.md
> +`g++ {{स्रोतफाइल/को/पथ}} -std={{c++98|c++11|c++14|c++17}} -o {{आउटपुट/को/पथ}}`
```suggestion
`g++ {{स्रोतफाइल.cpp/को/पथ}} -std={{c++98|c++11|c++14|c++17}} -o {{आउटपुट/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/g++.md
> +`g++ {{स्रोतफाइल/को/पथ}} -o {{आउटपुट/को/पथ}} -I{{हेडर/को/पथ}} -L{{लाइब्ररी/को/पथ}} -l{{लाइब्ररी को नाम}}`
```suggestion
`g++ {{स्रोतफाइल/को/पथ.cpp}} -o {{आउटपुट/को/पथ}} -I{{हेडर/को/पथ}} -L{{लाइब्ररी/को/पथ}} -l{{लाइब्ररी_को_नाम}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/g++.md
> +`g++ -c {{स्रोतफाइल_१/को/पथ स्रोतफाइल_२/को/पथ ...}} && g++ -o {{आउटपुट/को/पथ}} {{आउटपुट_१/को/पथ आउटपुट_२/को/पथ ...}}`
```suggestion
`g++ -c {{स्रोतफाइल_१.cpp/को/पथ स्रोतफाइल_२.cpp/को/पथ ...}} && g++ -o {{आउटपुट/को/पथ}} {{आउटपुट_१/को/पथ आउटपुट_२/को/पथ ...}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/g++.md
> +`g++ {{स्रोतफाइल/को/पथ}} -Wall -o {{आउटपुट/को/पथ}}`
```suggestion
`g++ {{स्रोतफाइल.cpp/को/पथ}} -Wall -o {{आउटपुट/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/gcc.md
> +`gcc {{स्रोतफाइल/को/पथ}} -o {{आउटपुट/को/पथ}} -I{{हेडर/को/पथ}} -L{{लाइब्ररी/को/पथ}} -l{{लाइब्ररी को नाम}}`
```suggestion
`gcc {{स्रोतफाइल.c/को/पथ}} -o {{आउटपुट/को/पथ}} -I{{हेडर/को/पथ}} -L{{लाइब्ररी/को/पथ}} -l{{लाइब्ररी को नाम}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/gcc.md
> +`gcc -S {{स्रोतफाइल/को/पथ}}`
```suggestion
`gcc -S {{स्रोतफाइल.c/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/gcc.md
> +`gcc -c {{स्रोतफाइल/को/पथ}}`
```suggestion
`gcc -c {{स्रोतफाइल.c/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/json5.md
> +`json5 --space {{इन्डेन्ट मात्रा}}`
```suggestion
`json5 --space {{इन्डेन्ट_मात्रा}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/json5.md
> +`json5 {{निवेशफाइल/को/पथ}} --validate`
```suggestion
`json5 {{निवेशफाइल.json5/को/पथ}} --validate`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/json5.md
> +`json5 {{निवेशफाइल/को/पथ}} --out-file {{निर्गमफाइल/को/पथ}}`
```suggestion
`json5 {{निवेशफाइल.json5/को/पथ}} --out-file {{निर्गमफाइल/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/json5.md
> +`json5 {{निवेशफाइल/को/पथ}}`
```suggestion
`json5 {{निवेशफाइल.json5/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/python.md
> +`python {{फाइल/को/पथ}}`
```suggestion
`python {{फाइल.py/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/python.md
> +`python -i {{फाइल/को/पथ}}`
```suggestion
`python -i {{फाइल.py/को/पथ}}`
```

2022-10-08 15:26 UTC, kbdharun commented on pages.ne/common/python.md
> +`python -m {{pdb}} {{फाइल/को/पथ}}`
```suggestion
`python -m {{pdb}} {{फाइल.py/को/पथ}}`
```

2022-10-08 15:58 UTC, animeshdhakal commented
Added the Extension to Translation

2022-10-08 16:04 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2022-10-10 15:33 UTC, navarroaxel commented on pages.ne/common/json5.md
> +`json5 --space {{इन्डेन्ट मात्रा}}`
We use `snake_case` for placeholder:
```suggestion
`json5 --space {{इन्डेन्ट_मात्रा}}`
```

2022-10-11 10:44 UTC, closed without merging