hexdump: add page
tldr-pages/tldr pull request #8971
Opened 2022-10-12 15:57 UTC by ZeroDayOwl

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known): 2.37.2**

2022-10-14 11:48 UTC, ZeroDayOwl commented
@navarroaxel Hi! Could you kindly review my PR?

2022-10-14 12:48 UTC, navarroaxel commented
Hi @ZeroDayOwl this page already exists in the `common` directory because the command is available in macOS too https://github.com/tldr-pages/tldr/blob/main/pages/common/hexdump.md

2022-10-14 14:08 UTC, kbdharun commented
> Hi @ZeroDayOwl this page already exists in the `common` directory because the command is available in macOS too https://github.com/tldr-pages/tldr/blob/main/pages/common/hexdump.md

IMO, This page looks good but it doesn't have the last 2 commands in the [main page](https://github.com/tldr-pages/tldr/blob/main/pages/common/hexdump.md). I think the PRs author can update the main page in common with this one along with the 2 missing commands.

2022-12-21 00:57 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! 🚀

2022-12-21 00:57 UTC, EmilySeville7cfg commented on pages/linux/hexdump.md
> +`hexdump -b {{path/to/file}}`
```suggestion
- Display the input offset in hexadecimal, followed by three columns of data in octal, per line:

`hexdump --one-byte-octal {{path/to/file}}`
```

Mandatory fix: [long option must be used if it's portable](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax).

2022-12-21 00:57 UTC, EmilySeville7cfg commented on pages/linux/hexdump.md
> +`hexdump --length {{7}} {{path/to/file}}`
```suggestion
- Interpret only specified length bytes of the input:

`hexdump --length {{1..infinity}} {{path/to/file}}`
```

Optional fix: [range syntax can be used](https://github.com/tldr-pages/tldr/pull/9646).
Note: I am not sure whether length can't be 0.

2022-12-21 00:57 UTC, EmilySeville7cfg commented on pages/linux/hexdump.md
> +`hexdump --skip {{5}} {{path/to/file}}`
```suggestion
- Skip offset bytes from the beginning of the input and interpret:

`hexdump --skip {{1..infinity}} {{path/to/file}}`
```

The same issue as above.

2022-12-21 00:57 UTC, EmilySeville7cfg commented on pages/linux/hexdump.md
> +`hexdump -v {{path/to/file}}`
```suggestion
- Display all data in hexadecimal without skipping any output lines:

`hexdump --no-squeezing {{path/to/file}}`
```

Mandatory fix: [long option must be used if it's portable](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax).

2022-12-28 01:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8971) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=8971) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=8971) it.</sub>

2023-06-11 00:02 UTC, closed without merging