ping.md: add spanish translation
tldr-pages/tldr pull request #9083
Opened 2022-10-15 17:45 UTC by dagp-ucol

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-15 17:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9083) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9083) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9083) it.</sub>

2022-10-15 22:30 UTC, navarroaxel reviewed
This page isn't in sync with https://github.com/tldr-pages/tldr/blob/main/pages/common/ping.md. Please update this PR.

2022-10-16 16:16 UTC, blueskyson approved these changes

2022-12-20 01:56 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! 🚀

2022-12-20 01:56 UTC, EmilySeville7cfg commented on pages.es/linux/ping.md
> +# ping
```suggestion
# ping
```

Warning: `ping` was not found in `pages/linux/`.

2022-12-20 01:56 UTC, EmilySeville7cfg commented on pages.es/linux/ping.md
> +`ping -c {{count}} {{host}}`
```suggestion
`ping --count {{1..infinity}} {{host}}`
```

Mandatory fix: [long option must be used if it's portable](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax).
Optional fix: `--count` value can be converted to range (can't deduce the highest value for `--count`, `infinity` used as a fallback.

2022-12-20 01:56 UTC, EmilySeville7cfg commented on pages.es/linux/ping.md
> +`ping -w {{time}} {{host}}`
```suggestion
`ping --timeout {{1..infinity}} {{host}}`
```

The same issue as above.

2023-04-01 22:50 UTC, CleanMachine1 commented
If someone else would like to resubmit this PR, feel free, however due to the abandonment of it and the agreement isn't signed, I am closing this PR.

2023-04-01 22:50 UTC, closed without merging