hexdump: add Russian translation
tldr-pages/tldr pull request #9129
Opened 2022-10-17 14:51 UTC by trolzen

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2022-10-24 12:40 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2022-10-25 05:13 UTC, EmilySeville7cfg requested changes

2022-10-25 05:13 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump {{файл}}`
Syntax is incorrect both in the original page and here. Is should be (it's assumed that path to file is expected and not just a plain filename):

```suggestion
`hexdump {{путь/к/файлу}}`
```

2022-10-25 05:13 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump -C {{файл}}`
Syntax is incorrect both in the original page and here. Is should be (it's assumed that path to file is expected and not just a plain filename):

```suggestion
`hexdump -C {{путь/к/файлу}}`
```

2022-10-25 05:13 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump -C -n{{количество_байтов}} {{файл}}`
Syntax is incorrect both in the original page and here. Is should be (it's assumed that path to file is expected and not just a plain filename):

```suggestion
`hexdump -C -n{{количество_байтов}} {{путь/к/файлу}}`
```

2022-10-25 05:13 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump --no-squeezing {{файл}}`
Syntax is incorrect both in the original page and here. Is should be (it's assumed that path to file is expected and not just a plain filename):

```suggestion
`hexdump --no-squeezing {{путь/к/файлу}}`
```

2022-11-03 14:46 UTC, trolzen commented
@EmilySeville7cfg I've updated this PR with your suggestions, but I used the recommended form from the `common-arguments.md`

2022-11-16 20:17 UTC, EmilySeville7cfg requested changes
- No issues found but merging blocked to update the original page at the first place. PR will be approved after the original page is refreshed (I've already [sent](https://github.com/tldr-pages/tldr/pull/9520) a PR for it).
- Thanks for a contribution. 🚀

2022-11-16 20:17 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump {{путь/до/файла}}`
The [original](https://github.com/tldr-pages/tldr/blob/main/pages/common/hexdump.md) page should be updated too to reflect this change.

2022-11-16 20:17 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump -C {{путь/до/файла}}`
The [original](https://github.com/tldr-pages/tldr/blob/main/pages/common/hexdump.md) page should be updated too to reflect this change.

2022-11-16 20:17 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump -C -n{{количество_байтов}} {{путь/до/файла}}`
The [original](https://github.com/tldr-pages/tldr/blob/main/pages/common/hexdump.md) page should be updated too to reflect this change.

2022-11-16 20:17 UTC, EmilySeville7cfg commented on pages.ru/common/hexdump.md
> +`hexdump --no-squeezing {{путь/до/файла}}`
The [original](https://github.com/tldr-pages/tldr/blob/main/pages/common/hexdump.md) page should be updated too to reflect this change.

2022-11-18 02:55 UTC, EmilySeville7cfg approved these changes
- Approved because all issues are already addressed to.
- This page should be reviewed by `hexdump` users.
- Thanks for a contribution. 😸

2022-11-18 02:56 UTC, merged