qm-pending: add page
tldr-pages/tldr pull request #9149
Opened 2022-10-18 04:38 UTC by Muskan-Git-Code

- [✅] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [✅] The page(s) have at most 8 examples.
- [✅] The page description(s) have links to documentation or a homepage.
- [✅] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [✅] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-18 05:59 UTC, abhisheksrivastava177 commented
> * [x]  The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
> * [x]  The page(s) have at most 8 examples.
> * [x]  The page description(s) have links to documentation or a homepage.
> * [x]  The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
> * [x]  The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
> * **Version of the command being documented (if known):**

2022-10-18 06:02 UTC, abhisheksrivastava177 commented
@Muskan-Git-Code I don't think you need to mention issue in the command version.

2022-10-18 15:36 UTC, kbdharun commented
> @Muskan-Git-Code I don't think you need to mention issue in the command version.

I would recommend mentioning issues in the PR description. Like `Reference: #issue number` or `or Ref: #issue number` or whatever you feel convenient. `qm` is a command in which we are getting a lot of PRs so we would link this PR in issue description. 

Also, Whenever a PR closes a issue I would recommend adding `Closes: #no` to the description.

2022-10-18 15:54 UTC, abhisheksrivastava177 commented
@kbdharun Sure. Quick question : The `Closes: #no` description will close the entire issue, right? Which we should not do in case of qm PRs which only the document a subset of the commands?



> > @Muskan-Git-Code I don't think you need to mention issue in the command version.
> 
> I would recommend mentioning issues in the PR description. Like `Reference: #issue number` or `or Ref: #issue number` or whatever you feel convenient. `qm` is a command in which we are getting a lot of PRs so we would link this PR in issue description.
> 
> Also, Whenever a PR closes a issue I would recommend adding `Closes: #no` to the description.


@kbdharun Sure. Quick question : The `Closes: #no` description will close the entire issue, right? Which we should not do in case of qm PRs which only the document a subset of the commands?

2022-10-18 16:02 UTC, kbdharun commented
> @kbdharun Sure. But quick question : The `Closes: #no` description will close the entire issue, right? Which we should not do in case of qm PRs which only document a subset of qm commands?

Yes, It closes the entire issue and it **isn't applicable here**. I mentioned it generally for future reference. We use it for page requests (issues) for individual commands. And let's say there is a Let's document (issue) with 20 commands and 19 were already added. You use `Closes: #issue_no` in that case as with your PRs merge all commands are added.

2022-10-22 16:12 UTC, kbdharun reviewed
Thanks for your contribution. I have a suggestion for this page.

2022-10-22 16:12 UTC, kbdharun commented on pages/linux/qm-pending.md
> +- Get the virtual machine configuration:
```suggestion
- Get the virtual machine configuration of a specific virtual machine:
```

2022-10-22 16:24 UTC, kbdharun approved these changes

2022-10-22 16:40 UTC, abhisheksrivastava177 approved these changes

2022-10-25 07:54 UTC, EmilySeville7cfg requested changes

2022-10-25 07:54 UTC, EmilySeville7cfg commented on pages/linux/qm-pending.md
> +`qm pending {{vmid}}`
To make several PR's consistent take a look at #9110 where `vm_id` is used. 
```suggestion
`qm pending {{vm_id}}`
```

2022-10-25 08:03 UTC, kbdharun approved these changes

2022-10-25 08:05 UTC, EmilySeville7cfg approved these changes

2022-10-25 08:05 UTC, merged

2022-10-25 08:05 UTC, EmilySeville7cfg commented
Merged, thanks! ❤️