<ftxdiff>: add page
tldr-pages/tldr pull request #9177
Opened 2022-10-18 21:49 UTC by GingerKiwi

from page request: macOS Font Tools aka. Apple Font Tool Suite #8478 
Note: I'm a new dev, but experienced writer. This is my first docs PR. Feedback appreciated.

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-18 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9177) it.</sub>

2022-10-19 03:56 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

2022-10-19 03:56 UTC, kbdharun commented on pages/osx/ftxdiff.md
> +> Compares the differences between two fonts. More information can be found here https://developer.apple.com/fonts/ .
```suggestion
> Compare differences between two fonts. 
> More information:<https://developer.apple.com/fonts>.
```

2022-10-19 03:56 UTC, kbdharun commented on pages/osx/ftxdiff.md
> +`ftxdiff --output FontDiff.txt FirstFont.ttc SecondFont.ttc`
```suggestion
`ftxdiff --output {{FontDiff.txt}} {{FirstFont.ttc}} {{SecondFont.ttc}}`
```

2022-10-19 03:56 UTC, kbdharun commented on pages/osx/ftxdiff.md
> +
```suggestion
```

2022-10-19 03:56 UTC, kbdharun commented on pages/osx/ftxdiff.md
> +...
```suggestion
```

2022-10-22 05:29 UTC, kbdharun reviewed
These suggestions would fix the Linter errors.

2022-10-22 05:29 UTC, kbdharun commented on pages/osx/ftxdiff.md
> +> More information:<https://developer.apple.com/fonts>.
```suggestion
> More information: <https://developer.apple.com/fonts>.
```

2022-10-22 05:29 UTC, kbdharun commented on pages/osx/ftxdiff.md
> +> Compare differences between two fonts.
```suggestion
> Compare differences between two fonts.
```

2022-10-22 05:29 UTC, kbdharun commented on pages/osx/ftxdiff.md
> +`ftxdiff --include-glyph-names`
```suggestion
`ftxdiff --include-glyph-names`
```

2022-10-27 02:34 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2022-11-02 04:26 UTC, blueskyson commented on pages/osx/ftxdiff.md
> +`ftxdiff --output {{FontDiff.txt}} {{FirstFont.ttc}} {{SecondFont.ttc}}`
```suggestion
`ftxdiff --output {{fontdiff.txt}} {{path/to/font1.ttc}} {{path/to/font2.ttc}}`
```

2022-11-28 21:13 UTC, EmilySeville7cfg requested changes
- Mandatory fixes must be applied, changes requested.
- This PR should be reviewed by `ftxdiff` users.
- Thanks for a contribution! ❤️

2022-11-28 21:13 UTC, EmilySeville7cfg commented on pages/osx/ftxdiff.md
> +`ftxdiff --output {{fontdiff.txt}} {{path/to/font1.ttc}} {{path/to/font2.ttc}}`
```suggestion
- Output differences to a specific text file:

`ftxdiff --output {{path/to/fontdiff.txt}} {{path/to/font1.ttc}} {{path/to/font2.ttc}}`
```

- Optional fix: `a specific` may sound better.
- Mandatory fix: [path format violation](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths).

2022-12-19 09:53 UTC, EmilySeville7cfg approved these changes

2022-12-19 09:54 UTC, merged