Dnsenum
tldr-pages/tldr pull request #9195
Opened 2022-10-19 22:28 UTC by ciph3rz

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-20 12:05 UTC, navarroaxel commented on pages/linux/dnsenum.md
> +`dnsenum -enum {{domainname}`
I think an explicit example is better here
```suggestion
`dnsenum -enum {{example.com}`
```

2022-10-20 12:05 UTC, navarroaxel commented on pages/linux/dnsenum.md
> +`dnsenum --noreverse -o {{outputfile}} {{domainname}}`
```suggestion
`dnsenum --noreverse -o {{path/to/file}} {{example.com}}`
```

2022-10-20 12:05 UTC, navarroaxel commented on pages/linux/braa.md
> +- Query the whole subnet `{ip_range}` for `system.sysLocation.0`:
I can't understand these examples

2022-10-23 18:59 UTC, ciph3rz commented
Reference to #6863

2022-10-30 11:48 UTC, navarroaxel commented on pages/linux/dnsenum.md
> +`dnsenum -enum {{example.com}`
typo
```suggestion
`dnsenum -enum {{example.com}}`
```

2022-10-30 11:48 UTC, navarroaxel commented on pages/linux/dnsenum.md
> +- Enumerate domain without reverse lookup and save the output to file:
```suggestion
- Enumerate a domain without reverse lookup and save the output to file:
```

2022-10-30 11:48 UTC, navarroaxel commented on pages/linux/dnsenum.md
> +`dnsenum -f {{filename}} -r {{domainname}}`
```suggestion
`dnsenum -f {{filename}} -r {{example.com}}`
```

2022-11-17 15:00 UTC, kbdharun commented on pages/linux/dnsenum.md
> +> Multithreaded perl script used to enumerate DNS information from a domain.
```suggestion
> Multithreaded Perl script used to enumerate DNS information from a domain.
```

2022-11-17 15:00 UTC, kbdharun commented on pages/linux/dnsenum.md
> +- Brute force search on subdomains along with custom file with subdomains passed as attribute:
```suggestion
- Brute force search on subdomains along with a custom file with subdomains passed as an attribute:
```

2022-11-17 15:02 UTC, kbdharun approved these changes

2022-12-18 19:19 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! ❤️

2022-12-18 19:19 UTC, EmilySeville7cfg commented on pages/linux/dnsenum.md
> +`dnsenum -enum {{example.com}}`
```suggestion
- [enum]erate a specific domain with default settings:

`dnsenum -enum {{example.com}}`
```

Optional fix: mnemonic can be used.
Optional fix: `specific` may sound better.

2022-12-18 19:19 UTC, EmilySeville7cfg commented on pages/linux/dnsenum.md
> +`dnsenum --noreverse -o {{path/to/file}} {{example.com}}`
```suggestion
- Enumerate a domain without reverse lookup and save the [o]utput to a specific file:

`dnsenum --noreverse -o {{path/to/file}} {{example.com}}`
```

Almost the same issue as above.
Warning: [parsing man page failed, can't find `-o` option, possibly broken manual](https://manned.org/dnsenum.1).

2022-12-18 19:19 UTC, EmilySeville7cfg commented on pages/linux/dnsenum.md
> +`dnsenum -f {{filename}} -r {{example.com}}`
```suggestion
- Brute force search on subdomains along with a specific file with subdomains passed as an attribute:

`dnsenum --file {{path/to/file}} --recursion {{example.com}}`
```

Almost the same issue as above.
Mandatory fix: [path format is broken](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths).
Mandatory fix: [long option must be used if it's portable](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax).

2022-12-28 01:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9195) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: kbdharun<br/>:x: navarroaxel<br/>:x: ciph3rz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9195) it.</sub>

2023-06-19 00:48 UTC, Waples commented
Our dead pipeline is stopping this PR

2023-06-19 00:49 UTC, Waples commented
Also fixes have not been submitted, closing this.

2025-03-05 03:09 UTC, closed without merging