scd: Add page
tldr-pages/tldr pull request #9224
Opened 2022-10-21 11:06 UTC by jay-tau

Completes a task in https://github.com/tldr-pages/tldr/issues/3689

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-22 07:51 UTC, kbdharun commented
Seems like you accidentally added sam2p to this PR too. Can you remove it? 

Ref #9109

2022-10-22 07:55 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

2022-10-22 07:55 UTC, kbdharun commented on pages/common/scd.md
> +- change to a directory path that ends with "ts":
```suggestion
- Change to a directory path that ends with "ts":
```

2022-10-22 07:55 UTC, kbdharun commented on pages/common/scd.md
> +- To change to a path matching all of "a", "b" and "c":
```suggestion
- Change to a path matching all of "a", "b" and "c":
```
I think this would be better.

2022-10-22 07:55 UTC, kbdharun commented on pages/common/scd.md
> +- Alias current directory as {{name}}:
```suggestion
- Alias current directory:
```

2022-10-22 07:55 UTC, kbdharun commented on pages/common/scd.md
> +- Jump to directory with previously defined alias {{name}}:
```suggestion
- Jump to a directory with a previously defined alias:
```

2022-10-22 10:11 UTC, kbdharun commented on pages/common/scd.md
> +- Alias current directory:
```suggestion
- Add an alias to the current directory:
```
Would this be better?

2022-10-23 06:22 UTC, kbdharun commented
@jay-tau Was this PR closed by accident?

2022-10-26 10:33 UTC, navarroaxel commented on pages/common/scd.md
> +> A tiny file manager focused on shell integration.
```suggestion
> File manager focused on shell integration.
```

2022-10-26 10:33 UTC, navarroaxel commented on pages/common/scd.md
> +- Recursively index some paths for the very first run:
```suggestion
- Index paths recursively for the very first run:
```

2022-10-26 10:33 UTC, navarroaxel commented on pages/common/scd.md
> +- Change to a path matching all of "a", "b" and "c":
Could you give an specific example of this to understand?

2022-10-26 10:36 UTC, navarroaxel commented on pages/common/scd.md
> +- Add an alias to the current directory:
```suggestion
- Add an alias for the current directory:
```

2022-10-26 10:36 UTC, navarroaxel commented on pages/common/scd.md
> +`scd --alias={{name}}`
Perhaps this better
```suggestion
`scd --alias={{word}}`
```

2022-10-26 10:36 UTC, navarroaxel commented on pages/common/scd.md
> +`scd {{name}}`
```suggestion
`scd {{word}}`
```

2022-10-26 10:36 UTC, navarroaxel commented on pages/common/scd.md
> +- Jump to a directory with a previously defined alias:
```suggestion
- Change to a directory using an alias:
```

2022-12-14 06:36 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! ❤️

2022-12-15 06:13 UTC, EmilySeville7cfg requested changes

2022-12-15 06:13 UTC, EmilySeville7cfg commented on pages/common/scd.md
> +
```suggestion

```

Mandatory fix: syntax error.

2022-12-15 13:32 UTC, EmilySeville7cfg requested changes
Changes requested due to syntax error.

2022-12-15 13:32 UTC, EmilySeville7cfg commented on pages/common/scd.md
> +- Show selection menu and ranking of 20 most likely directories:
```suggestion
`scd "{{pattern1 pattern2 ...}}"`

- Show selection menu and ranking of 20 most likely directories:
```

2022-12-15 13:37 UTC, EmilySeville7cfg commented on pages/common/scd.md
> +`scd -ar {{path/to/directory}}`
@jay-tau, please reply to all my unresolved conversations. :) As [README](https://github.com/cshuaimin/scd) doesn't provide enough info about supported options I assume that long ones are exist and requesting changes based on this assumption.

2022-12-28 01:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9224) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9224) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kbdharun<br/>:x: jay-tau<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9224) it.</sub>

2023-01-02 10:49 UTC, EmilySeville7cfg approved these changes

2023-01-02 16:55 UTC, kbdharun approved these changes

2023-01-03 03:46 UTC, merged