Added LS, MV and SUDO descriptions in the pt_BR/linux folders.
tldr-pages/tldr pull request #9259
Opened 2022-10-23 00:05 UTC by OctavioFurio

- [X] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [X] The page(s) have at most 8 examples.
- [X] The page description(s) have links to documentation or a homepage.
- [X] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [X] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

2022-10-23 00:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9259) it.</sub>

2022-10-23 00:28 UTC, OctavioFurio commented
Sorry for the many commits, I was having some trouble with formatting.
Thanks for the opportunity.

2022-10-26 10:28 UTC, navarroaxel requested changes
For the non-English pages we only accept translations in sync with the main English page. You can update this PR translating the examples from the following pages:
https://github.com/tldr-pages/tldr/blob/main/pages/common/ls.md
https://github.com/tldr-pages/tldr/blob/main/pages/common/mv.md
https://github.com/tldr-pages/tldr/blob/main/pages/common/sudo.md

2022-10-26 19:28 UTC, OctavioFurio commented
Thank you for the instructions. I've just made the requested corrections.

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/ls.md
> +- Liste um arquivo por linha:
```suggestion
- Lista um arquivo por linha:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/ls.md
> +> Listar o conteúdo de um diretório. Mais informações [neste site](https://manned.org/ls).
```suggestion
> Listar o conteúdo de um diretório.
> Mais informações: <https://manned.org/ls>.
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/ls.md
> +- Liste todos os arquivos, inclusive arquivos ocultos:
```suggestion
- Lista todos os arquivos, inclusive arquivos ocultos:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/mv.md
> +> Movimentação de arquivos entre diretórios, ou renomeá-los. Mais informações [neste site](https://url-to-upstream.tld).
```suggestion
> Movimentação de arquivos entre diretórios, ou renomeá-los.
> Mais informações: <https://www.gnu.org/software/coreutils/mv>.
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/mv.md
> +- Mover um arquivo para um diretório arbitrário:
```suggestion
- Move um arquivo para um diretório arbitrário:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/mv.md
> +- Mover arquivos para outro diretório, mantendo os nomes dos arquivos:
```suggestion
- Move arquivos para outro diretório, mantendo os nomes dos arquivos:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/mv.md
> +- Mova os arquivos em modo Verbose, mostrando os arquivos após sua movimentação:
```suggestion
- Move os arquivos em modo Verbose, mostrando os arquivos após sua movimentação:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/mv.md
> +- Requisitar confirmação para sobrescrição de arquivos, independentemente das permissões de arquivo:
```suggestion
- Requisita confirmação para sobrescrição de arquivos, independentemente das permissões de arquivo:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/mv.md
> +- Não sobrescrever arquivos existentes no diretório de destino:
I think `sobrescritar` is the correct verb
```suggestion
- Não sobrescrita arquivos existentes no diretório de destino:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +> Executa um único comando como o Superuser, ou como outro usuário. Para mais informações, acesse [este site](https://manned.org/sudo).
```suggestion
> Executa um único comando como o Superuser, ou como outro usuário.
> Mais informações: <https://www.sudo.ws/sudo.html>.
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Executar um comando como Superuser:
```suggestion
- Executa um comando como Superuser:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Editar um arquivo, como Superuser, com seu editor padrão:
```suggestion
- Edita um arquivo, como Superuser, com seu editor padrão:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Executar um comando como outro usuário e/ou grupo:
```suggestion
- Executa um comando como outro usuário e/ou grupo:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Abrir o shell padrão com privilégios de Superuser e executar arquivos de login (`.profile`, `.bash_profile`, etc.):
```suggestion
- Abre o shell padrão com privilégios de Superuser e executar arquivos de login (`.profile`, `.bash_profile`, etc.):
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Executar um comando anterior com o prefixo `sudo` (apenas em `bash`, `zsh`, etc.):
```suggestion
- Executa um comando anterior com o prefixo `sudo` (apenas em `bash`, `zsh`, etc.):
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Abrir o shell padrão com privilégios de Superuser sem alterar o ambiente de execução:
```suggestion
- Abre o shell padrão com privilégios de Superuser sem alterar o ambiente de execução:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Listar os comandos permitidos (e não permitidos) para o usuário atual:
```suggestion
- Lista os comandos permitidos (e não permitidos) para o usuário atual:
```

2022-10-28 11:21 UTC, navarroaxel commented on pages.pt_BR/linux/sudo.md
> +- Abrir o shell padrão como dado usuário, carregando o ambiente de execução deste usuário e lendo arquivos de login (`.profile`, `.bash_profile`, etc.):
```suggestion
- Abre o shell padrão como dado usuário, carregando o ambiente de execução deste usuário e lendo arquivos de login (`.profile`, `.bash_profile`, etc.):
```

2022-10-29 00:41 UTC, navarroaxel approved these changes

2022-10-29 02:46 UTC, kbdharun commented on pages.pt_BR/linux/mv.md
> +> Mais informações: <https://www.gnu.org/software/coreutils/mv>
```suggestion
> Mais informações: <https://www.gnu.org/software/coreutils/mv>.
```

2022-10-29 02:46 UTC, kbdharun approved these changes

2022-10-29 02:50 UTC, merged