poetry: add german translation
tldr-pages/tldr pull request #9406
Opened 2022-10-28 18:56 UTC by micschwarz

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-29 03:16 UTC, kbdharun commented on pages.de/common/poetry.md
> +> Mehr Informationen: <https://python-poetry.org/docs/cli/>.
```suggestion
> Weitere Informationen: <https://python-poetry.org/docs/cli/>.
```
Translate command arguments here too.

2022-11-23 19:17 UTC, pixelcmtd requested changes
Please take the 5 minutes to read the contributing guide before submitting a PR to any sizable FOSS project.

2022-11-23 19:17 UTC, pixelcmtd commented on pages.de/common/poetry.md
> +> Verwalte Python-Paketen und -Abhängigkeiten.
```suggestion
> Verwalte Python-Pakete und -Abhängigkeiten.
```

2022-11-23 19:17 UTC, pixelcmtd commented on pages.de/common/poetry.md
> +- Erstellen eins neuen Poetry-Projekts im Verzeichnis mit dem angegebenem Namen:
I honestly hate the phrasing of the english page, but that's a discussion to be had somewhere else.

```suggestion
- Erstelle ein neues Poetry-Projekt im Verzeichnis mit dem angegebenem Namen:
```

2022-11-23 19:17 UTC, pixelcmtd commented on pages.de/common/poetry.md
> +- Installation einer Entwicklungsabhängigkeit und allen Unterabhängigkeiten:
```suggestion
- Installiere eine Entwicklungsabhängigkeit und alle Unterabhängigkeiten:
```

2022-11-23 19:17 UTC, pixelcmtd commented on pages.de/common/poetry.md
> +- Aktualisieren aller Abhängigkeiten und `poetry.lock` aktualisieren:
Very loose but adequate translation 😁

```suggestion
- Aktualisiere alle Abhängigkeiten und `poetry.lock`:
```

2022-11-23 19:17 UTC, pixelcmtd commented on pages.de/common/poetry.md
> +- Einen Befehl innerhalb der virtuellen Umgebung des Projekts ausführen:
```suggestion
- Führe einen Befehl innerhalb der virtuellen Umgebung des Projekts aus:
```

2022-11-23 19:17 UTC, pixelcmtd commented on pages.de/common/poetry.md
> +- Die Minor-Version des projects in `pyproject.toml` erhöhen:
```suggestion
- Erhöhe die Minor-Version des Projekts in `pyproject.toml`:
```

2022-11-23 19:17 UTC, pixelcmtd commented on pages.de/common/poetry.md
> +- Alle poetry Unterbefehle auflisten:
```suggestion
- Liste alle poetry Unterbefehle auf:
```

2022-11-24 06:59 UTC, EmilySeville7cfg approved these changes
- No mandatory fixes found, PR is approved.
- Page should be reviewed by `poetry` users.
- Thanks for a contribution! ❤️

2022-11-24 06:59 UTC, EmilySeville7cfg commented on pages.de/common/poetry.md
> +`poetry new {{projekt_name}}`
```suggestion
`poetry new "{{projekt_name}}"`
```

Optional fix (the [original](https://github.com/tldr-pages/tldr/blob/main/pages/common/poetry.md) page can be updated): possible missing quotes.

2022-11-24 06:59 UTC, EmilySeville7cfg commented on pages.de/common/poetry.md
> +`poetry run {{befehl}}`
```suggestion
`poetry run "{{befehl}}"`
```

The same issue as above.

2022-12-10 04:04 UTC, kbdharun approved these changes

2022-12-13 09:08 UTC, pixelcmtd approved these changes

2022-12-13 09:08 UTC, merged