ls page request: cvfsck #8512
tldr-pages/tldr pull request #9418
Opened 2022-10-29 09:51 UTC by manny-uncharted

fixed issue: page request: cvfsck #8512
- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-10-29 13:12 UTC, kbdharun reviewed
@manny-uncharted Can you remove the other 2 files in this PR?

> Seems like you accidentally added it.

2022-10-29 13:27 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

_Note to maintainers:_
Things I observed in this command.
1. There isn't a manned page for it.
2. It seems like it doesn't support long arguments/flags.

2022-10-29 13:27 UTC, kbdharun commented on pages/linux/cvfsck.md
> +- Provide a specific path to a configuration file that is to be used, overriding the implicit location:
```suggestion
- Provide a specific path to a configuration file to be used for overriding the implicit location:
```
I guess think would be better.

2022-10-29 13:27 UTC, kbdharun commented on pages/linux/cvfsck.md
> +- Internal debug use to dump a significant amount of data to the standard output device:
```suggestion
- Dump a significant amount of data to the standard output device (Internal debug use):
```

2022-10-29 13:27 UTC, kbdharun commented on pages/linux/cvfsck.md
> +`cvfsck -c {{pathname}}`
```suggestion
`cvfsck -c {{path/to/configuration_file}}`
```
I think this would be better

2022-10-29 16:21 UTC, navarroaxel commented on pages/linux/cvfsck.md
> +> More information: <https://www.unix.com/man-page/osx/1/cvfsck/>.
This looks like a macOS command, not for Linux.

2022-10-29 16:34 UTC, manny-uncharted commented
Yeah, I'll resolve this now


On Sat, Oct 29, 2022 at 5:22 PM Axel Navarro ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pages/linux/cvfsck.md
> <https://github.com/tldr-pages/tldr/pull/9418#discussion_r1008725410>:
>
> > @@ -0,0 +1,24 @@
> +# cvfsck
> +
> +> Check and Recover a Xsan Volume.
> +> More information: <https://www.unix.com/man-page/osx/1/cvfsck/>.
>
> This looks like a macOS command, not for Linux.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tldr-pages/tldr/pull/9418#pullrequestreview-1161011891>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKIT5BM35MR2OJ3IHXVAMU3WFVFK7ANCNFSM6AAAAAARRW2XNY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-29 20:30 UTC, navarroaxel commented on pages/osx/cvfsck.md
> +> More information: <https://www.unix.com/man-page/osx/1/cvfsck/>.
```suggestion
> More information: <https://www.unix.com/man-page/osx/1/cvfsck>.
```

2022-10-29 20:30 UTC, navarroaxel commented on pages/osx/cvfsck.md
> +> Check and Recover a Xsan Volume.
```suggestion
> Check and recover an Xsan volume.
```

2022-10-29 20:30 UTC, navarroaxel commented on pages/osx/cvfsck.md
> +`cvfsck -A`
Does this example also recovers the collisions?

2022-10-29 20:30 UTC, navarroaxel commented on pages/osx/cvfsck.md
> +- Provide a specific path to a configuration file to be used for overriding the implicit location:
You should explain the whole example, not the `-c` argument.

2022-10-29 20:30 UTC, navarroaxel commented on pages/osx/cvfsck.md
> +- Report free space fragmentation:
Where is reported? printed in the terminal?

2022-11-28 19:47 UTC, EmilySeville7cfg requested changes
- Mandatory changes found, changes requested.
- This page should be reviewed by `sequota`, `cvfsck` users.
- Thanks for a contribution! ❤️

2022-11-28 19:47 UTC, EmilySeville7cfg commented on pages/linux/setquota.md
> +`setquota -r, --remote`
```suggestion
`setquota --remote`
```

- Mandatory fix: [invalid](https://manned.org/setquota.8) command syntax: there is no `-r,` option: man pages can't be often copied without any modifications in TlDr pages.
- Note: long and short options can't be presented now without using placeholder syntax.

2022-11-28 19:47 UTC, EmilySeville7cfg commented on pages/linux/setquota.md
> +`setquota -u, --user`
```suggestion
`setquota --user`
```

The same issue as above.

2022-11-28 19:47 UTC, EmilySeville7cfg commented on pages/linux/setquota.md
> +`setquota -g, --group`
```suggestion
`setquota --group`
```

The same issue as above.

2022-11-28 19:47 UTC, EmilySeville7cfg commented on pages/linux/setquota.md
> +`setquota -p, --prototype={{protoname}}`
```suggestion
`setquota --prototype={{protoname}}`
```

The same issue as above.

2022-11-28 19:47 UTC, EmilySeville7cfg commented on pages/linux/setquota.md
> +`setquota -a, --all`
```suggestion
`setquota --all`
```

The same issue as above.

2022-11-28 19:47 UTC, EmilySeville7cfg commented on pages/osx/setquota.md
> +# setquota
Mandatory fix: [specification violation](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#platform): this page can be safely removed: it's the same as `linux/setquota.md`.

> If a page is common across multiple platforms, but slightly differently on a given platform, then the page is still stored in common, but a copy tailored for the differing platform is placed in that platform's specific folder.

2022-12-15 06:08 UTC, EmilySeville7cfg commented
According to our [maintainers guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md#ii-handling-prs) we can apply suggestions ourselves now. There is no need to wait not responding PR author:

> If the only issues holding up a merge are trivial fixes (typos, syntax errors, etc.), and the author doesn't respond in a day or two, maintainers can make the necessary changes themselves, and proceed with the merge process.

Warning: trivial fixes definition is not complete as it contains `etc` (possible misinterpretation of this term can occur).

2022-12-28 01:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9418) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9418) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9418) it.</sub>

2023-02-05 14:41 UTC, Waples commented
> According to our [maintainers guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md#ii-handling-prs) we can apply mandatory suggestions ourselves now. There is no need to wait not responding PR author:
> 
> > If the only issues holding up a merge are trivial fixes (typos, syntax errors, etc.), and the author doesn't respond in a day or two, maintainers can make the necessary changes themselves, and proceed with the merge process.
> 
> Warning: trivial fixes definition is not complete as it contains `etc` (possible misinterpretation of this term can occur).

@EmilySeville7cfg since this is stuck since December, shall we just apply the suggestions you made then and merge after moving it to /common (if thats even still needed)?

2023-02-05 14:42 UTC, Waples requested changes
Please apply the suggestions according to our styleguide (placeholder syntax)

2023-02-05 14:55 UTC, EmilySeville7cfg commented
> @EmilySeville7cfg since this is stuck since December, shall we just apply the suggestions you made then and merge after moving it to /common (if thats even still needed)?

It's up to you now, what apply and what not, do what you think is the most appropriate. Since it's usual to make exceptions to style guide I can't decide what is the best, sorry.

2023-04-21 00:02 UTC, closed without merging