gprof: add page
tldr-pages/tldr pull request #9485
Opened 2022-11-03 13:40 UTC by RaphGL

Added basic instructions for how to use the unix gprof C profiler

2022-11-03 14:59 UTC, kbdharun commented on pages/common/gprof.md
> +> Performance analysis tool for many programming languages
```suggestion
> Performance analysis tool for many programming languages.
```

2022-11-03 15:49 UTC, kbdharun commented on pages/common/gprof.md
> +> It profiles the function executions of a program
```suggestion
> It profiles the function executions of a program.
```

2022-11-06 05:04 UTC, pixelcmtd requested changes
Please include a "More information" link.

2022-11-06 05:04 UTC, pixelcmtd commented on pages/common/gprof.md
> +- Compile binary with gprof information and run it to get {{gmon.out}}:
```suggestion
- Compile binary with gprof information and run it to get `gmon.out`:
```

2022-11-06 13:58 UTC, RaphGL commented
I've added a link for more information

2022-11-06 15:26 UTC, pixelcmtd commented on pages/common/gprof.md
> +> More information: https://ftp.gnu.org/old-gnu/Manuals/gprof-2.9.1/html_mono/gprof.html
```suggestion
> More information: <https://ftp.gnu.org/old-gnu/Manuals/gprof-2.9.1/html_mono/gprof.html>
```

2022-11-06 15:33 UTC, kbdharun commented on pages/common/gprof.md
> +> It profiles the function executions of a program.
```suggestion
> It profiles the function executions of a program.
```

2022-11-06 22:35 UTC, RaphGL commented
Everything is in order now. Awaiting your approval.

2022-11-07 04:29 UTC, pixelcmtd approved these changes

2022-11-07 05:24 UTC, kbdharun approved these changes

2022-11-07 05:24 UTC, kbdharun commented on pages/common/gprof.md
> +- Suppress profile fields' description:
```suggestion
- Suppress profile field's description:
```
Is this better?

2022-11-08 21:47 UTC, merged