tshark: add Tamil translation
tldr-pages/tldr pull request #9568
Opened 2022-11-29 06:13 UTC by kbdharun

Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>

- [x] The page(s) are in the correct platform directories: `linux`.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known): TShark (Wireshark) 4.0.0**

2022-11-29 06:25 UTC, EmilySeville7cfg requested changes
- Changes requested because mandatory fixes detected.
- This page should be reviewed by `tshark` users.
- Thanks for a contribution! ❤️

2022-11-29 06:25 UTC, EmilySeville7cfg commented on pages.ta/linux/tshark.md
> +`tshark -r {{கோப்பு_பெயர்}}.pcap`
```suggestion
`tshark -r {{பாதை/டு/கோப்பு.pcap}}`
```

Mandatory fix (error source: [original page](https://github.com/tldr-pages/tldr/blob/main/pages/linux/tshark.md)): path placeholder is [broken](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths).

2022-11-29 06:27 UTC, EmilySeville7cfg approved these changes

2022-12-01 02:22 UTC, blueskyson approved these changes

2022-12-01 02:31 UTC, merged