git-stash: add option show
tldr-pages/tldr pull request #9571
Opened 2022-11-29 15:19 UTC by imdouyu

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-11-29 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9571) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9571) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9571) it.</sub>

2022-11-29 15:54 UTC, kbdharun requested changes
@imdouyu Welcome to tldr and thanks for your contribution. Our pages only support a maximum of 8 examples feel free to concatenate 2 examples if necessary. If you think this command must be kept separate, create a new page for the flag (Similar to ` tldr brew-cask` page) and reference the new page in the current page by adding `See also: example-a`  before More information link.

2022-11-30 03:20 UTC, EmilySeville7cfg requested changes
- Mandatory fixes found, changes requested.
- Thanks for a contribution! ❤️

2022-11-30 03:20 UTC, EmilySeville7cfg commented on pages/common/git-stash.md
> +- Show the changes as a patch between the stash (default is stash@{0}) and the commit back when stash entry was first created:
Mandatory fix: page format violation: join 7-8 examples or remove this example.

2022-12-17 08:22 UTC, EmilySeville7cfg approved these changes

2022-12-17 08:30 UTC, kbdharun approved these changes

2022-12-17 08:33 UTC, merged