mogrify: add page
tldr-pages/tldr pull request #9599
Opened 2022-12-07 06:19 UTC by sakibjunaed

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-12-07 13:40 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +- Surround image with border:
```suggestion
- Surround the image with a border:
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +- Flip image vertically:
```suggestion
- Flip the image vertically:
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +`mogrify -adjoin {{input-file}} {{input-file}}`
```suggestion
`mogrify -adjoin {{input_file}} {{input_file}}`
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +`mogrify -background color {{input-file}}`
```suggestion
`mogrify -background color {{input_file}}`
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +`mogrify -format type {{input-file}}`
```suggestion
`mogrify -format type {{input_file}}`
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +`mogrify -border geometry {{input-file}}`
```suggestion
`mogrify -border geometry {{input_file}}`
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +- Set image format type:
```suggestion
- Set the image format type:
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +- Set background color:
```suggestion
- Set the background color:
```

2022-12-07 13:40 UTC, kbdharun commented on pages/linux/mogrify.md
> +`mogrify -flip {{input-file}}`
```suggestion
`mogrify -flip {{input_file}}`
```

2022-12-08 06:54 UTC, EmilySeville7cfg requested changes
At least one mandatory fix detected, changes requested.
Page should be scanned for multiple violations of similar issues (suggestions are created just for their first occurrences).
Thanks for a contribution! 🚀

2022-12-08 06:54 UTC, EmilySeville7cfg commented on pages/linux/mogrify.md
> +`mogrify -adjoin {{input_file}} {{input_file}}`
```suggestion
`mogrify -adjoin {{path/to/file1 path/to/file2 ...}}`
```

Mandatory fix: [path format is incorrect](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths).
Mandatory fix: command syntax is incorrect: not just 2 arguments expected.

2022-12-28 01:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9599) it.</sub>

2023-02-05 14:32 UTC, Waples commented
@sakibjunaed are you still working on this or shall somebody else apply the changes?

2023-04-14 00:02 UTC, closed without merging