postmap: add page
tldr-pages/tldr pull request #9600
Opened 2022-12-07 06:40 UTC by sakibjunaed

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-12-07 12:49 UTC, kbdharun requested changes
Thanks for your contribution. This command must be placed in `common` directory as it works with both `linux` and macos `osx`.

2022-12-07 12:57 UTC, kbdharun commented on pages/linux/postmap.md
> +> Create or query one or more Postfix lookup tables, or updates an existing one.
```suggestion
> Create or query one or more Postfix lookup tables, or update an existing one.
```

2022-12-07 12:57 UTC, kbdharun commented on pages/linux/postmap.md
> +- Search the specified maps for key and remove one entry per map:
```suggestion
- Search specified maps for the key and remove one entry per map:
```
Is this better?

2022-12-07 12:57 UTC, kbdharun commented on pages/linux/postmap.md
> +`postmap -d {{key}} {{input file}}`
```suggestion
`postmap -d {{key}} {{input_file}}`
```

2022-12-07 12:57 UTC, kbdharun commented on pages/linux/postmap.md
> +`postmap -h {{input file}}`
```suggestion
`postmap -h {{input_file}}`
```

2022-12-07 12:57 UTC, kbdharun commented on pages/linux/postmap.md
> +- Search the specified maps for key and write the first value found to the standard output stream:
```suggestion
- Search specified maps for the key and write the first value found to the standard output stream:
```

2022-12-07 12:57 UTC, kbdharun commented on pages/linux/postmap.md
> +`postmap -q {{key}} {{input file}}`
```suggestion
`postmap -q {{key}} {{input_file}}`
```

2022-12-07 12:57 UTC, kbdharun commented on pages/linux/postmap.md
> +`postmap -s {{input file}}`
```suggestion
`postmap -s {{input_file}}`
```

2022-12-08 06:50 UTC, EmilySeville7cfg approved these changes
At least one mandatory fix detected, changes requested.
Page should be scanned for multiple violations of similar flaws found (suggestions are created just for their first occurrences).
Thanks for a contribution! ❤️

2022-12-08 06:50 UTC, EmilySeville7cfg commented on pages/common/postmap.md
> +- Search specified maps for the key and remove one entry per map:
```suggestion
- Search specific maps for a key and remove one entry per map (output stream: `stdout`):
```

```suggestion
- Search specific maps for a key and remove one entry per map (output stream: `stderr`):
```

Optional fix: `specific` may sound better.
Optional fix: add the correct output stream name explicitly.

2022-12-08 06:50 UTC, EmilySeville7cfg requested changes
- At least one mandatory fix detected, changes requested.
- Page should be scanned for multiple violations of similar flaws found (suggestions are created just for their first occurrences).
- Thanks for a contribution! heart

2022-12-08 09:14 UTC, pixelcmtd commented on pages/common/postmap.md
> +`postmap -d {{key}} {{input_file}}`
We're currently in the process of mandating that all paths start with `path/to/`.

```suggestion
`postmap -d {{key}} {{path/to/file}}`
```

2022-12-08 09:14 UTC, pixelcmtd commented on pages/common/postmap.md
> +`postmap -h {{input_file}}`
```suggestion
`postmap -h {{path/to/file}}`
```

2022-12-08 09:14 UTC, pixelcmtd commented on pages/common/postmap.md
> +`postmap -q {{key}} {{input_file}}`
```suggestion
`postmap -q {{key}} {{path/to/file}}`
```

2022-12-08 09:14 UTC, pixelcmtd commented on pages/common/postmap.md
> +`postmap -s {{input_file}}`
```suggestion
`postmap -s {{path/to/file}}`
```

2022-12-28 01:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9600) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9600) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9600) it.</sub>

2023-03-04 00:02 UTC, closed without merging