qmv: add -f do example
tldr-pages/tldr pull request #9620
Opened 2022-12-12 16:35 UTC by marekkowalczyk

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):** v1.3.0

2022-12-12 16:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9620) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9620) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9620) it.</sub>

2022-12-13 02:46 UTC, EmilySeville7cfg approved these changes
No mandatory fixes found, approved.
Thanks for a contribution! 🚀

2022-12-13 02:46 UTC, EmilySeville7cfg commented on pages/common/qmv.md
> +`qmv -f do .`
```suggestion
`qmv --format=do .`
```

Optional fix: long option can be used.

2022-12-13 05:37 UTC, blueskyson approved these changes

2022-12-13 05:43 UTC, EmilySeville7cfg requested changes
Changes were approved by mistake, suggestions were fixed.
Mandatory fixes found, changes requested.

2022-12-14 06:21 UTC, merged

2022-12-20 16:25 UTC, waldyrious commented
It seems like this PR was merged to `master`, so it doesn't appear in the `main` tag (I think there's an automatic `main`→`master` sync, but not the other way around. Commit 896abba24 should probably be cherry-picked back to `main` so the content isn't lost, especially when we eventually remove the master branch (#9628).