README: refresh page
tldr-pages/tldr pull request #9632
Opened 2022-12-16 15:58 UTC by EmilySeville7cfg

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-12-19 08:18 UTC, owenvoke requested changes
I have a couple of small grammatical changes, but otherwise looks good. 👍🏻

2022-12-19 08:18 UTC, owenvoke commented on README.md
> +But we have already some plugins to different editors to enhance TlDr page editing experience:
```suggestion
But we already have some plugins for different editors to enhance the tldr page editing experience:
```

2022-12-19 08:18 UTC, owenvoke commented on README.md
> +For editors without plugin system we provide set of configs in a [separate repo](https://github.com/tldr-pages/tldr-editor-configs).
```suggestion
For editors without a plugin system, we provide a set of configurations in a [separate repo](https://github.com/tldr-pages/tldr-editor-configs).
```

2022-12-19 10:34 UTC, owenvoke approved these changes
❤️

2022-12-20 10:07 UTC, kbdharun approved these changes
LGTM

2022-12-20 10:09 UTC, merged