bc: updated Spanish translation
tldr-pages/tldr pull request #9679
Opened 2022-12-27 23:38 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-12-27 23:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9679) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9679) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9679) it.</sub>

2022-12-28 00:12 UTC, kbdharun requested changes
Hi, Thanks for your contribution. The page doesn't seem to be synced with https://github.com/tldr-pages/tldr/blob/main/pages/common/bc.md.

2022-12-28 01:39 UTC, kant commented
you are right, tomorrow will be updated with the missing lines. Roger that!

2022-12-29 22:28 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! ❤️

2022-12-29 22:28 UTC, EmilySeville7cfg commented on pages.es/common/bc.md
>  `bc -l`
```suggestion
- Inicia `bc` en el modo interactivo utilizando la biblioteca matemática estándar:

`bc --mathlib`
```

Mandatory fix: [long option must be used](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax).

2022-12-30 00:31 UTC, EmilySeville7cfg approved these changes

2022-12-30 02:18 UTC, kbdharun reviewed
Still there seem to be some differences here with this page https://github.com/tldr-pages/tldr/blob/main/pages/common/bc.md. 

I have a question are you trying to translate the page in common or osx?

2023-04-02 00:02 UTC, closed without merging