adscript: add Spanish translation
tldr-pages/tldr pull request #9688
Opened 2022-12-31 01:35 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-12-31 03:15 UTC, EmilySeville7cfg approved these changes
No fixes found, approved.
Thanks for a contribution! ❤️ 🎄

2022-12-31 03:21 UTC, EmilySeville7cfg approved these changes
No mandatory fixes found, approved.
Thanks for a contribution! 🎄

2022-12-31 03:21 UTC, EmilySeville7cfg commented on pages.es/common/adscript.md
> +`adscript --output {{path/to/file.o}} {{path/to/input_file.adscript}}`
```suggestion
- Compilar un archivo en un archivo objeto:

`adscript --output {{ruta/al/archivo.o}} {{ruta/al/archivo_de_entrada.adscript}}`
```
Optional fix: placeholders can be translated.

2022-12-31 06:58 UTC, kbdharun approved these changes
LGTM, after @EmilySeville7cfg's suggestions.

2022-12-31 09:25 UTC, pixelcmtd requested changes
What @EmilySeville7cfg said, the rest LGTM.

2022-12-31 14:33 UTC, pixelcmtd approved these changes

2022-12-31 14:34 UTC, merged

2022-12-31 16:49 UTC, kant commented
@kbdharun @pixelcmtd @EmilySeville7cfg Best brand new year!

2022-12-31 16:50 UTC, kbdharun commented
> @kbdharun @pixelcmtd @EmilySeville7cfg Best brand new year!

Happy new year 🎉

2022-12-31 21:07 UTC, pixelcmtd commented
It's 22:07, but still happy new year y'all

2023-01-01 04:36 UTC, EmilySeville7cfg commented
Thanks! ❤️