alex: add Spanish translation
tldr-pages/tldr pull request #9692
Opened 2022-12-31 10:59 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2022-12-31 11:08 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! 🚀

2022-12-31 11:08 UTC, EmilySeville7cfg commented on pages.es/common/alex.md
> +`alex {{archivotexto.md}}`
```suggestion
- Analiza un archivo dado:

`alex {{ruta/al/archivo_de_texto.md}}`
```

Mandatory fix: [path placeholder format is incorrect](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths).

2022-12-31 11:08 UTC, EmilySeville7cfg commented on pages.es/common/alex.md
> +`alex *.md !{{ejemplo.md}}`
```suggestion
- Analiza todos los archivos Markdown excepto `ejemplo.md`.:

`alex *.md !{{ruta/hacia/ejemplo.md}}`
```

The same issue as above.

2023-01-01 04:42 UTC, EmilySeville7cfg approved these changes

2023-01-03 16:59 UTC, blueskyson approved these changes

2023-01-04 10:52 UTC, merged