amass-intel: add Spanish translation
tldr-pages/tldr pull request #9699
Opened 2022-12-31 13:36 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-01-01 04:15 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! ❤️

2023-01-01 04:15 UTC, EmilySeville7cfg commented on pages.es/common/amass-intel.md
> +`amass intel -addr {{192.168.0.1-254}}`
```suggestion
- Encuentre dominios raíz en un rango de direcciones IP específico:

`amass intel -addr {{192.168.0.1-254}}`
```

Optional fix (error source: original page): `specific` may sound better.

2023-01-01 04:15 UTC, EmilySeville7cfg commented on pages.es/common/amass-intel.md
> +`amass intel -whois -d {{nombre_de_dominio}}`
```suggestion
- Encuentre dominios raíz relacionados con un dominio específico:

`amass intel -whois -d {{nombre_de_dominio}}`
```

The same issue as above.

2023-01-01 04:15 UTC, EmilySeville7cfg commented on pages.es/common/amass-intel.md
> +`amass intel -org {{nombre_de_organizacion}}`
```suggestion
- Encuentre ASN pertenecientes a una organización específica:

`amass intel -org {{nombre_de_organizacion}}`
```

The same issue as above.

2023-01-01 04:15 UTC, EmilySeville7cfg commented on pages.es/common/amass-intel.md
> +`amass intel -asn {{asn}}`
```suggestion
- Encuentre dominios raíz pertenecientes a un Número de Sistema Autónomo específico:

`amass intel -asn {{string}}`
```

Almost the same issue as above.
Optional fix: `asn` term duplication can be reduced.
Warning: failed to deduce value type of `-asn` option, `string` used as a fallback.

2023-01-01 04:15 UTC, EmilySeville7cfg commented on pages.es/common/amass-intel.md
> +`amass intel -o {{archivo_de_salida}} -whois -d {{nombre_de_dominio}}`
```suggestion
- Guarde los resultados en un archivo de texto específico:

`amass intel -o {{ruta/al/archivo_de_salida}} -whois -d {{nombre_de_dominio}}`
```

Optional fix (error source: original page): `specific` may sound better.
Mandatory fix (error source: original page): [path placeholder is broken](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#paths).

2023-01-02 10:23 UTC, EmilySeville7cfg approved these changes

2023-01-02 10:55 UTC, navarroaxel commented on pages.es/common/amass-intel.md
> +- Encuentre dominios raíz en un rango de direcciones IP específico:
```suggestion
- Encuentra dominios raíz en un rango de direcciones IP específico:
```

2023-01-02 10:55 UTC, navarroaxel commented on pages.es/common/amass-intel.md
> +- Encuentre dominios raíz relacionados con un dominio específico:
```suggestion
- Encuentra dominios raíz relacionados con un dominio específico:
```

2023-01-02 10:55 UTC, navarroaxel commented on pages.es/common/amass-intel.md
> +- Encuentre ASN pertenecientes a una organización específica:
```suggestion
- Encuentra ASN pertenecientes a una organización específica:
```

2023-01-02 10:55 UTC, navarroaxel commented on pages.es/common/amass-intel.md
> +- Encuentre dominios raíz pertenecientes a un Número de Sistema Autónomo específico:
```suggestion
- Encuentra dominios raíz pertenecientes a un Número de Sistema Autónomo específico:
```

2023-01-02 10:55 UTC, navarroaxel commented on pages.es/common/amass-intel.md
> +- Guarde los resultados en un archivo de texto específico:
```suggestion
- Guarda los resultados en un archivo de texto específico:
```

2023-01-02 10:55 UTC, navarroaxel commented on pages.es/common/amass-intel.md
> +- Utiliza métodos activos de reconocimiento:
I prefer the verb `usar`
```suggestion
- Usa métodos activos de reconocimiento:
```

2023-01-02 16:49 UTC, kbdharun approved these changes
LGTM after navarroaxel's suggestions

2023-01-02 18:04 UTC, navarroaxel approved these changes

2023-01-02 18:04 UTC, merged