Update unzip.md to include the `-j` option
tldr-pages/tldr pull request #9719
Opened 2023-01-03 18:15 UTC by DUOLabs333

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-01-03 18:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9719) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9719) it.</sub>

2023-01-04 10:44 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! 🚀

2023-01-04 10:44 UTC, EmilySeville7cfg commented on pages/common/unzip.md
> +`unzip -j {{path/to/archive.zip}} {{path/to/file/in/archive}}`
```suggestion
`unzip -j {{path/to/archive.zip}} {{path/to/file_in_archive1 path/to/file_in_archive2 ...}}`
```

Mandatory fix: [unexpected `/` separator, `_` expected](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#naming): path placeholder format violated.
Mandatory fix: [unexpected `}}` term, `...` expected](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#special-cases): `unzip` can accept more than 1 path.

2023-01-04 13:44 UTC, EmilySeville7cfg approved these changes

2023-01-10 22:46 UTC, sbrl approved these changes
Great example to add, thanks @DUOLabs333!

2023-01-10 22:46 UTC, merged