man: add Russian translation
tldr-pages/tldr pull request #9731
Opened 2023-01-05 20:17 UTC by egor1wtf

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-01-05 20:20 UTC, egor1wtf commented
Hello maintainers. I'm sorry, I made a lot of mistakes in the past PR. I had to create a new one.

Please check if everything is correct. Thank you and have a nice day!

2023-01-06 02:52 UTC, kbdharun approved these changes
LGTM, Welcome to tldr and Thanks for your contribution.

2023-01-06 12:09 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! 🚀

2023-01-06 12:09 UTC, EmilySeville7cfg commented on pages.ru/linux/man.md
> +`man {{7}} {{команда}}`
```suggestion
- Показать справочную страницу пакета макросов команды из раздела:

`man {{1..9}} {{команда}}`
```

Mandatory fix (error source: original page): [unexpected `7` number, range construct expected](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#range-syntax).

2023-01-06 12:09 UTC, EmilySeville7cfg commented on pages.ru/linux/man.md
> +`man --locale={{locale}} {{команда}}`
```suggestion
- Отобразить справочную страницу с использованием определённой локали:

`man --locale={{строка}} {{команда}}`
```

Optional fix (error source: original page): unexpected `locale` term, `string` expected.

2023-01-06 16:39 UTC, EmilySeville7cfg approved these changes

2023-01-06 16:42 UTC, EmilySeville7cfg commented
@egor1wtf, notify me please when this PR can be merged (or anybody else can merge it). :)

2023-01-06 16:48 UTC, egor1wtf commented on pages.ru/linux/man.md
> +`man --locale={{locale}} {{команда}}`
@EmilySeville7cfg 

Thanks you for the suggestions!

I disagree about the change from argument: --locale={{locale}} to --locale={{строка}}.

A word "строка" translated in English means "string". It's not entirely clear what "string" to enter for the user. I propose to use the transcription of the English word "locale" into Russian "локаль".

The final version will look like this:

```suggestion
- Отобразить справочную страницу с использованием определённой локали:

`man --locale={{локаль}} {{команда}}`
```

I look forward to your thoughts and suggestions. Thank you

2023-01-06 16:49 UTC, EmilySeville7cfg commented on pages.ru/linux/man.md
> +`man --locale={{locale}} {{команда}}`
Your idea is neat, I like it. Let's use what u suggested as there is no word duplication.

2023-01-06 19:52 UTC, egor1wtf commented
@EmilySeville7cfg 

Thank you for your help! I'm all set, can you please approve the PR?

2023-01-07 01:46 UTC, kbdharun approved these changes

2023-01-07 01:47 UTC, merged