asciidoctor: add Russian translation
tldr-pages/tldr pull request #9760
Opened 2023-01-10 14:55 UTC by yuriskinfo

Hi, added the Russian translation for Asciidoctor. Thanks

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-01-10 16:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9760) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9760) it.</sub>

2023-01-10 22:21 UTC, sbrl commented on pages.ru/common/asciidoctor.md
> +`asciidoctor {{path/to/file.adoc}}`
Could you also translate the file paths please? Though of course the extensions should remain the same.

2023-01-11 11:14 UTC, EmilySeville7cfg requested changes
Mandatory fixes found, changes requested.
Thanks for a contribution! 🚀

2023-01-11 11:14 UTC, EmilySeville7cfg commented on pages.ru/common/asciidoctor.md
> +`asciidoctor -a stylesheet={{путь/до/таблицы-стилей.css}} {{путь/до/файла.adoc}}`
```suggestion
- Преобразовать данный `.adoc` файл в HTML и привязать к таблице стилей CSS:

`asciidoctor --attribute=stylesheet={{путь/до/таблицы-стилей.css}} {{путь/до/файла.adoc}}`
```

Mandatory fix (error source: original page): [broken option](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#option-syntax): long option expected.

2023-01-17 12:39 UTC, blueskyson approved these changes

2023-02-05 05:57 UTC, yuriskinfo commented
I have nothing to change here, just waiting for the committers review.

2023-02-05 07:06 UTC, EmilySeville7cfg commented
@kbdharun, can u review this PR? I have no rights to approve it and make it mergeable.

2023-02-05 07:10 UTC, kbdharun approved these changes

2023-02-05 07:14 UTC, merged