Nala: Front UI for apt and apt-get
tldr-pages/tldr pull request #9890
Opened 2023-02-23 11:01 UTC by rafay99-epic

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [x] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [x] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-02-25 08:21 UTC, kbdharun reviewed
Thanks for your contribution and welcome to tldr. I have some suggestions for this page.

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +> Debian and Ubuntu package management utility.
```suggestion
> Package management utility for Debian and Ubuntu.
```
How about this?

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +> More information: <https://gitlab.com/volian/nala>
```suggestion
> More information: <https://gitlab.com/volian/nala>.
```

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +- Nala will then go get all the mirrors from the respective master list. Once done we test the latency and score each mirror. Nala will choose the fastest 3 mirrors (configurable) and write them to a
```suggestion
- Fetch mirrors from the master list for your distribution (Nala will choose the fastest 3 configurable mirrors by testing latency and write them to a file):
```

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +- Clean the local repository - removing package files (`.deb`) from interrupted downloads that can no longer be downloaded:
```suggestion
- Clean the local repository by removing package files (`.deb`) from interrupted downloads that can no longer be downloaded:
```

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +- Upgrade installed packages (like `upgrade`), but remove obsolete packages and install additional packages to meet new dependencies:
```suggestion
- Upgrade installed packages, remove obsolete packages and install additional packages to meet new dependencies:
```

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +
```suggestion
```

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +- History
```suggestion
- Print history of all transactions:
```

2023-02-25 08:21 UTC, kbdharun commented on pages/linux/nala.md
> +- Remove all packages that are no longer needed:
```suggestion
- Remove all unused packages and dependencies:
```

2023-02-25 08:22 UTC, kbdharun commented on pages/linux/nala.md
> +
```suggestion
```

2023-02-25 08:24 UTC, kbdharun requested changes
Our pages can only hold a maximum of 8 examples, feel free to update the page in order to have a successful CI check.

2023-02-25 10:14 UTC, rafay99-epic commented
Sure, I will add some examples

2023-02-27 18:45 UTC, EmilySeville7cfg commented
@rafay99-epic, if u need unlimited amount of examples u can use my TlDr-like project. [Here](https://github.com/command-line-interface-pages/cli-pages/pull/47) is an example how it looks.

2023-02-27 19:48 UTC, rafay99-epic commented
Hey thanks I will look into it. @EmilySeville7cfg

2023-03-01 10:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9890) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9890) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9890) it.</sub>

2023-03-02 15:31 UTC, rafay99-epic commented
> [![CLA assistant check](https://camo.githubusercontent.com/777a078050c6b0e4f4af5f36272b0014312f4cafeea86f96c172ea30870fb940/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f7369676e6564)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9890) All committers have signed the CLA.

Done, signature this using my GitHub Account

2023-03-02 20:41 UTC, rafay99-epic commented
> The [build](https://github.com/tldr-pages/tldr/actions/runs/4318045983) for this PR failed with the following error(s):
> 
> ```
> pages/linux/nala.md:5: TLDR016 Label for information link should be spelled exactly `More information: `
> pages/linux/nala.md:22: TLDR014 Page should contain no trailing whitespace
> pages/linux/nala.md:25: TLDR014 Page should contain no trailing whitespace
> pages/linux/nala.md:0: TLDR019 Page should only include a maximum of 8 examples
> ```
> 
> Please fix the error(s) and push again.

@kbdharun  Brother, Can you explain this error? I can't seem to understand this.

2023-03-19 10:27 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-03-26 04:56 UTC, mfrw approved these changes
LGTM Thanks for your contribution @rafay99-epic

2023-03-26 04:56 UTC, merged

2023-03-26 10:13 UTC, rafay99-epic commented
> LGTM Thanks for your contribution @rafay99-epic

Happy to Contribute, and make this application more powerful and awesome.