apropos: add Spanish translation
tldr-pages/tldr pull request #9912
Opened 2023-03-04 01:42 UTC by kant

- [x] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [x] The page description(s) have links to documentation or a homepage.
- [x] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-03-04 06:38 UTC, kbdharun requested changes
Not again with the recursive directory 😭 , I can't keep fixing it every day. @kant **Can you ensure not to do this again**, and create a file, not a new directory?**

 Is this issue due to your editor or do you create PRs from GitHub's editor?

> I am confused, as I have used a lot of text editors but I never came across this issue.

Note: Take your own time for creating PRs, you have done an amazing job and I am glad that you are a regular contributor, nowadays I am noticing minor errors here and there in your PRs, We maintainers will try our best to fix them, but proofread/check your PRs once before submitting.

2023-03-04 06:58 UTC, kbdharun approved these changes
Thanks for your contribution.

2023-03-05 05:28 UTC, blueskyson approved these changes

2023-03-05 21:25 UTC, kant commented
All my PRs comes in from the site of Github.com. Everything. Not desktop or mobile app. I will try to change my workflow to continue to enhance and contribute with this repository. Thanks for your patience and effort!!

2023-03-06 15:49 UTC, merged