Create aircrack-ng.md
tldr-pages/tldr pull request #9938
Opened 2023-03-11 12:17 UTC by Slotharmy

Translated the current aircrack-ng.md into german.

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-03-11 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9938) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/tldr?pullRequest=9938) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/tldr?pullRequest=9938) it.</sub>

2023-03-12 16:52 UTC, kbdharun reviewed
Thanks for your contribution. I have some suggestions for this page.

2023-03-12 16:52 UTC, kbdharun commented on pages.de/common/aircrack-ng.md
> +> Mehr Informationen: <https://www.aircrack-ng.org/doku.php?id=aircrack-ng> (auf Englisch)
```suggestion
> Mehr Informationen: <https://www.aircrack-ng.org/doku.php?id=aircrack-ng>.
```

2023-03-12 16:52 UTC, kbdharun commented on pages.de/common/aircrack-ng.md
> +> Davor muss Packet abgefangen werden mit aircrack
```suggestion
```
Idk, if this line is required, I will wait for a native speakers opinion.

2023-03-12 16:57 UTC, blueskyson commented on pages.de/common/aircrack-ng.md
> +`aircrack-ng -w {{Pfad/zu/Wortliste.txt}} {{Pfad/zu/Packetdatei.cap}}`
```suggestion
`aircrack-ng -w {{pfad/zu/wortliste.txt}} {{pfad/zu/packetdatei.cap}}`
```

2023-03-12 16:57 UTC, blueskyson commented on pages.de/common/aircrack-ng.md
> +`aircrack-ng -w {{Pfad/zu/Wortliste.txt}} -e {{essid}} {{Pfad/zu/Packetdatei.cap}}`
```suggestion
`aircrack-ng -w {{pfad/zu/wortliste.txt}} -e {{essid}} {{pfad/zu/packetdatei.cap}}`
```

2023-03-12 16:57 UTC, blueskyson commented on pages.de/common/aircrack-ng.md
> +`aircrack-ng -w {{Pfad/zu/Wortliste.txt}} --bssid {{mac}} {{Pfad/zu/Packetdatei.cap}}`
```suggestion
`aircrack-ng -w {{pfad/zu/wortliste.txt}} --bssid {{mac}} {{pfad/zu/packetdatei.cap}}`
```

2023-03-12 17:00 UTC, kbdharun commented on pages.de/common/aircrack-ng.md
> +> Davor muss Packet abgefangen werden mit aircrack
```suggestion
```

2023-03-28 16:28 UTC, pixelcmtd requested changes
Please check the [Style Guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#imperative-mood) and a [dictionary](https://www.duden.de/rechtschreibung/Paket) _before_ contributing.

2023-03-28 16:28 UTC, pixelcmtd commented on pages.de/common/aircrack-ng.md
> +- Schlüssel knacken von abgefangenen Packeten mithilfe von Wortlisten:
```suggestion
- Knacke Schlüssel von abgefangenen Paketen mithilfe von Wortlisten:
```

2023-03-28 16:28 UTC, pixelcmtd commented on pages.de/common/aircrack-ng.md
> +- Schlüssel knacken von abgefangenen Packeten mithilfe einer Wortliste und der (E)SSID des Access Points:
```suggestion
- Knacke Schlüssel von abgefangenen Paketen mithilfe einer Wortliste und der (E)SSID des Access Points:
```

2023-03-28 16:28 UTC, pixelcmtd commented on pages.de/common/aircrack-ng.md
> +- Schlüssel knacken von abgefangenen Packeten mithilfe einer Wortliste und der MAC-Adresse des Access Points:
```suggestion
- Knacke Schlüssel von abgefangenen Paketen mithilfe einer Wortliste und der MAC-Adresse des Access Points:
```

2023-03-30 14:28 UTC, pixelcmtd approved these changes

2023-03-30 14:44 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-03-30 14:46 UTC, merged