aireplay-ng: add German translation
tldr-pages/tldr pull request #9980
Opened 2023-03-24 14:32 UTC by Slotharmy

Translated the current aireplay-ng.md into german.

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-03-28 16:39 UTC, pixelcmtd requested changes

2023-03-28 16:39 UTC, pixelcmtd commented on pages.de/common/aireplay-ng.md
> +> Packete in ein WLAN injizieren.
```suggestion
> Pakete in ein WLAN injizieren.
```

2023-03-28 16:39 UTC, pixelcmtd commented on pages.de/common/aireplay-ng.md
> +> Teil von `aicraick-ng`.
```suggestion
> Teil von `aircrack-ng`.
```

2023-03-30 14:15 UTC, Slotharmy commented on pages.de/common/aireplay-ng.md
> +- Senden einer bestimmten Anzahl an deauthentifizierungs Packeten mit der MAC-Adresse des Access POints, der MAC-Adresse des Clients und seines kabellosen interfaces:
In my 10 years working in studying and working, i have never heard of a Dissoziationspaket. But very surely i heard about a Deauthentifizierungspaket. I aggree with u on the rest of the changes but noch on the Dissoziationspaket part.

2023-03-30 16:09 UTC, pixelcmtd commented on pages.de/common/aireplay-ng.md
> +- Senden einer bestimmten Anzahl an deauthentifizierungs Packeten mit der MAC-Adresse des Access POints, der MAC-Adresse des Clients und seines kabellosen interfaces:
Is „Deauthentifizierungspaket“ the German term used for an 802.11 disassociate packet tho?

2023-04-08 10:21 UTC, kbdharun requested changes
Seems like you already added the page [here](https://github.com/tldr-pages/tldr/blob/main/pages.de/common/aircrack-ng.md) in #9938, feel free to merge the current PRs branch with main and update it with the suggestions here.

2023-04-08 10:23 UTC, kbdharun approved these changes
LGTM, Thanks for your contribution.

2023-04-19 14:22 UTC, Slotharmy commented on pages.de/common/aireplay-ng.md
> +- Senden einer bestimmten Anzahl an deauthentifizierungs Packeten mit der MAC-Adresse des Access POints, der MAC-Adresse des Clients und seines kabellosen interfaces:
yes it is

2023-04-23 11:32 UTC, pixelcmtd approved these changes

2023-04-23 11:32 UTC, merged