airmon-ng.md: add German translation
tldr-pages/tldr pull request #9981
Opened 2023-03-24 15:06 UTC by Slotharmy

airmon-ng.md

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-03-28 16:43 UTC, pixelcmtd requested changes

2023-03-28 16:43 UTC, pixelcmtd commented on pages.de/common/airmon-ng.md
> +- Wireless Geräte und deren Status auflisten:
```suggestion
- Liste Wireless Geräte und deren Status auf:
```

2023-03-28 16:43 UTC, pixelcmtd commented on pages.de/common/airmon-ng.md
> +- Überwachungsmodus für ein bestimmtes Gerät aktivieren:
```suggestion
- Aktiviere den Überwachungsmodus für ein bestimmtes Gerät:
```

2023-03-28 16:43 UTC, pixelcmtd commented on pages.de/common/airmon-ng.md
> +- Störende Prozesse killn, die das wireless Gerät verwenden:
```suggestion
- Kille störende Prozesse, die das Wireless Gerät verwenden:
```

2023-03-28 16:43 UTC, pixelcmtd commented on pages.de/common/airmon-ng.md
> +- Überwachungsmodus für ein spezifisches Interface deaktivieren:
```suggestion
- Deaktiviere den Überwachungsmodus für ein spezifisches Interface:
```

2023-03-28 16:43 UTC, pixelcmtd commented on pages.de/common/airmon-ng.md
> +> Aktiver Überwachungsmodus auf Wireless Network Geräten.
```suggestion
> Aktiveren des Überwachungsmodus auf Wireless Network Geräten.
```

2023-03-30 16:10 UTC, pixelcmtd approved these changes

2023-04-23 11:49 UTC, kbdharun approved these changes

2023-04-23 11:49 UTC, merged