translated the current aws-backup.md into German
tldr-pages/tldr pull request #9987
Opened 2023-03-25 17:09 UTC by Slotharmy

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-04-19 14:32 UTC, Slotharmy commented
Hello, can some pls make the approving reviews?

2023-05-01 17:51 UTC, pixelcmtd requested changes

2023-05-01 17:51 UTC, pixelcmtd commented on pages.de/common/aw-backup.md
> +- Rückgabe von Backup-Plan-Details für eine bestimmte Backup-Plan-ID:
```suggestion
- Gib Backup-Plan-Details für eine bestimmte Backup-Plan-ID aus:
```

2023-05-01 17:51 UTC, pixelcmtd commented on pages.de/common/aw-backup.md
> +- Erstellen eines Sicherungsplans unter Verwendung eines bestimmten Sicherungsplannamens und von Sicherungsregeln:
```suggestion
- Erstelle einen Backup-Plan unter Verwendung eines bestimmten Backup-Plan-Namens und von Backup-Regeln:
```

2023-05-01 17:51 UTC, pixelcmtd commented on pages.de/common/aw-backup.md
> +- Löschen eines bestimmten Backup-Plans
```suggestion
- Lösche einen bestimmten Backup-Plan:
```

2023-05-01 17:51 UTC, pixelcmtd commented on pages.de/common/aw-backup.md
> +- Liefert eine Liste aller aktiven Backup-Pläne für das aktuelle Konto:
```suggestion
- Gib eine Liste aller aktiven Backup-Pläne für das aktuelle Konto aus:
```

2023-05-01 17:51 UTC, pixelcmtd commented on pages.de/common/aw-backup.md
> +- Zeigt Deatuls über die Reportaufträge an:
```suggestion
- Zeige Details über die Report-Aufträge an:
```

2023-05-05 15:16 UTC, pixelcmtd approved these changes

2023-05-16 07:47 UTC, kbdharun approved these changes

2023-05-16 10:25 UTC, merged