arp.md: add German translation
tldr-pages/tldr pull request #9998
Opened 2023-03-30 16:19 UTC by Slotharmy

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-03-31 13:25 UTC, pixelcmtd requested changes
Are you sure you've read the style guide?

2023-03-31 13:25 UTC, pixelcmtd commented on pages.de/common/arp.md
> +> Den ARP Cache des Systems anzeigen und manipulieren
```suggestion
> Den ARP Cache des Systems anzeigen und manipulieren.
```

2023-03-31 13:25 UTC, pixelcmtd commented on pages.de/common/arp.md
> +- Die aktuelle ARP Tabelle anzeigen lassen:
```suggestion
- Zeige die aktuelle ARP Tabelle an:
```

2023-03-31 13:25 UTC, pixelcmtd commented on pages.de/common/arp.md
> +- Den gesamten Cache leeren:
```suggestion
- Leere den gesamten Cache:
```

2023-03-31 13:25 UTC, pixelcmtd commented on pages.de/common/arp.md
> +- Einen spezifizierten Eintrag in der Tabelle löschen:
```suggestion
- Lösche einen spezifischen Eintrag in der Tabelle:
```

2023-03-31 13:25 UTC, pixelcmtd commented on pages.de/common/arp.md
> +- Einen Eintrag in der ARP Tabelle erstellen:
```suggestion
- Erstelle einen Eintrag in der ARP Tabelle:
```

2023-04-23 11:34 UTC, pixelcmtd approved these changes

2023-05-16 12:40 UTC, acuteenvy approved these changes

2023-05-16 12:41 UTC, merged