arp-scan: add German translation
tldr-pages/tldr pull request #9999
Opened 2023-03-30 16:27 UTC by Slotharmy

- [ ] The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
- [ ] The page(s) have at most 8 examples.
- [ ] The page description(s) have links to documentation or a homepage.
- [ ] The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
- [ ] The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).
- **Version of the command being documented (if known):**

2023-03-31 13:26 UTC, pixelcmtd requested changes

2023-03-31 13:26 UTC, pixelcmtd commented on pages.de/common/arp-scan.md
> +- Das lokale Netzwerk scannen:
```suggestion
- Scanne das lokale Netzwerk:
```

2023-03-31 13:26 UTC, pixelcmtd commented on pages.de/common/arp-scan.md
> +- Ein IP Netzwerk mit einer benutzerdefinierten Bitmaske scannen:
```suggestion
- Scanne ein IP Netzwerk mit einer benutzerdefinierten Bitmaske:
```

2023-03-31 13:26 UTC, pixelcmtd commented on pages.de/common/arp-scan.md
> +- Ein IP Netzwerk innerhalb einer benutzerdefinierten Range scannen:
```suggestion
- Scanne ein IP Netzwerk innerhalb einer benutzerdefinierten Range:
```

2023-03-31 13:26 UTC, pixelcmtd commented on pages.de/common/arp-scan.md
> +- Ein IP Netzwerk mit einer benutzerdefinierten Netzmaske scannen:
```suggestion
- Scanne ein IP Netzwerk mit einer benutzerdefinierten Netzmaske:
```

2023-04-23 11:38 UTC, pixelcmtd approved these changes

2023-05-16 07:51 UTC, kbdharun approved these changes

2023-05-16 07:51 UTC, kbdharun approved these changes

2023-05-16 10:19 UTC, merged